In [1]:
import pandas as pd
import numpy as np

In [2]:
def compute_average(df,col):
    return np.mean(df[col].values)

## No-prompt

In [3]:
np_average_subj_female_subj_pron = {}
np_average_subj_female_obj_pron = {}
np_average_subj_male_subj_pron = {}
np_average_subj_male_obj_pron = {}

### Verb: "chucked" (NOTE: gets tokenized to 'unk')

In [4]:
transofposs_perfective_noprompt_1 = pd.read_csv("../results/transofposs_perfective/no-prompt/1.csv")
transofposs_perfective_noprompt_1.head()

                                     stimulus        He       She
0   Miss Smith chucked a wrench to Mr. Smith.  0.771096  0.228904
1      The woman chucked a wrench to the man.  0.814792  0.185208
2              Mary chucked a wrench to John.  0.589467  0.410533
3              Alice chucked a wrench to Bob.  0.494569  0.505431
4  The actress chucked a wrench to the actor.  0.834358  0.165642

In [5]:
# female subject
transofposs_perfective_noprompt_1f = transofposs_perfective_noprompt_1[0:12]
transofposs_perfective_noprompt_1f = transofposs_perfective_noprompt_1f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_1m = transofposs_perfective_noprompt_1[12:24]

#### female subject

In [6]:
transofposs_perfective_noprompt_1f

                                         stimulus       She        He
0       Miss Smith chucked a wrench to Mr. Smith.  0.228904  0.771096
1          The woman chucked a wrench to the man.  0.185208  0.814792
2                  Mary chucked a wrench to John.  0.410533  0.589467
3                  Alice chucked a wrench to Bob.  0.505431  0.494569
4      The actress chucked a wrench to the actor.  0.165642  0.834358
5           The girl chucked a wrench to the boy.  0.187362  0.812638
6   Mrs. Taylor chucked a wrench to Mr. Williams.  0.243599  0.756401
7                 Emma chucked a wrench to David.  0.886238  0.113762
8    The princess chucked a wrench to the prince.  0.182403  0.817597
9               Sarah chucked a wrench to Robert.  0.407269  0.592731
10  Mrs. Williams chucked a wrench to Mr. Taylor.  0.216686  0.783314
11                Emily chucked a wrench to Paul.  0.437467  0.562533

In [7]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_1f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_1f,'He'))

P('subj-pron'|subj=female) =  0.3380616133411725
P('non-subj-pron'|subj=female) =  0.6619383816917738

In [8]:
#np_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1f,'She')
#np_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1f,'He')

#### male subject

In [9]:
transofposs_perfective_noprompt_1m

                                         stimulus        He       She
12      Mr. Smith chucked a wrench to Miss Smith.  0.855855  0.144145
13         The man chucked a wrench to the woman.  0.878322  0.121678
14                 John chucked a wrench to Mary.  0.849310  0.150691
15                 Bob chucked a wrench to Alice.  0.459158  0.540842
16     The actor chucked a wrench to the actress.  0.865218  0.134782
17          The boy chucked a wrench to the girl.  0.870726  0.129274
18   Mr. William chucked a wrench to Mrs. Taylor.  0.862333  0.137667
19                David chucked a wrench to Emma.  0.221509  0.778491
20   The prince chucked a wrench to the princess.  0.873093  0.126907
21              Robert chucked a wrench to Sarah.  0.254757  0.745243
22  Mr. Taylor chucked a wrench to Mrs. Williams.  0.856732  0.143268
23                Paul chucked a wrench to Emily.  0.842201  0.157799

In [10]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_1m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_1m,'She'))

P('subj-pron'|subj=male) =  0.7241011882821718
P('non-subj-pron'|subj=male) =  0.27589882103105384

In [11]:
#np_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1m,'He')
#np_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1m,'She')

### Verb: "flung"

In [12]:
transofposs_perfective_noprompt_2 = pd.read_csv("../results/transofposs_perfective/no-prompt/2.csv")
transofposs_perfective_noprompt_2.head()

                                    stimulus        He       She
0   Miss Smith flung a frisbee to Mr. Smith.  0.787643  0.212357
1      The woman flung a frisbee to the man.  0.815582  0.184418
2              Mary flung a frisbee to John.  0.789771  0.210229
3              Alice flung a frisbee to Bob.  0.774322  0.225678
4  The actress flung a frisbee to the actor.  0.833650  0.166350

In [13]:
# female subject
transofposs_perfective_noprompt_2f = transofposs_perfective_noprompt_2[0:12]
transofposs_perfective_noprompt_2f = transofposs_perfective_noprompt_2f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_2m = transofposs_perfective_noprompt_2[12:24]

#### female subject

In [14]:
transofposs_perfective_noprompt_2f

                                         stimulus       She        He
0        Miss Smith flung a frisbee to Mr. Smith.  0.212357  0.787643
1           The woman flung a frisbee to the man.  0.184418  0.815582
2                   Mary flung a frisbee to John.  0.210229  0.789771
3                   Alice flung a frisbee to Bob.  0.225678  0.774322
4       The actress flung a frisbee to the actor.  0.166350  0.833650
5            The girl flung a frisbee to the boy.  0.179787  0.820213
6    Mrs. Taylor flung a frisbee to Mr. Williams.  0.211221  0.788779
7                  Emma flung a frisbee to David.  0.193468  0.806532
8     The princess flung a frisbee to the prince.  0.176583  0.823417
9                Sarah flung a frisbee to Robert.  0.424232  0.575768
10  Mrs. Williams flung a frisbee to  Mr. Taylor.  0.204416  0.795584
11                 Emily flung a frisbee to Paul.  0.412714  0.587286

In [15]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_2f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_2f,'He'))

P('subj-pron'|subj=female) =  0.2334544062614441
P('non-subj-pron'|subj=female) =  0.7665455887715021

In [16]:
np_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2f,'She')
np_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2f,'He')

#### male subject

In [17]:
transofposs_perfective_noprompt_2m

                                        stimulus        He       She
12      Mr. Smith flung a frisbee to Miss Smith.  0.852534  0.147466
13         The man flung a frisbee to the woman.  0.878409  0.121591
14                 John flung a frisbee to Mary.  0.860719  0.139281
15                 Bob flung a frisbee to Alice.  0.841849  0.158151
16     The actor flung a frisbee to the actress.  0.873887  0.126113
17          The boy flung a frisbee to the girl.  0.871294  0.128706
18  Mr. William flung a frisbee to  Mrs. Taylor.  0.860093  0.139907
19                David flung a frisbee to Emma.  0.116453  0.883547
20   The prince flung a frisbee to the princess.  0.875252  0.124748
21              Robert flung a frisbee to Sarah.  0.140217  0.859783
22  Mr. Taylor flung a frisbee to Mrs. Williams.  0.853469  0.146531
23                Paul flung a frisbee to Emily.  0.849446  0.150554

In [18]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_2m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_2m,'She'))

P('subj-pron'|subj=male) =  0.739468589425087
P('non-subj-pron'|subj=male) =  0.2605314316848914

In [19]:
np_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2m,'He')
np_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2m,'She')

### Verb: "kicked"

In [20]:
transofposs_perfective_noprompt_3 = pd.read_csv("../results/transofposs_perfective/no-prompt/3.csv")
transofposs_perfective_noprompt_3.head()

                                         stimulus        He       She
0   Miss Smith kicked a soccer ball to Mr. Smith.  0.760802  0.239198
1      The woman kicked a soccer ball to the man.  0.795157  0.204843
2              Mary kicked a soccer ball to John.  0.790835  0.209165
3              Alice kicked a soccer ball to Bob.  0.793594  0.206406
4  The actress kicked a soccer ball to the actor.  0.819756  0.180244

In [21]:
# female subject
transofposs_perfective_noprompt_3f = transofposs_perfective_noprompt_3[0:12]
transofposs_perfective_noprompt_3f = transofposs_perfective_noprompt_3f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_3m = transofposs_perfective_noprompt_3[12:24]

#### female subject

In [22]:
transofposs_perfective_noprompt_3f

                                             stimulus       She        He
0       Miss Smith kicked a soccer ball to Mr. Smith.  0.239198  0.760802
1          The woman kicked a soccer ball to the man.  0.204843  0.795157
2                  Mary kicked a soccer ball to John.  0.209165  0.790835
3                  Alice kicked a soccer ball to Bob.  0.206406  0.793594
4      The actress kicked a soccer ball to the actor.  0.180244  0.819756
5           The girl kicked a soccer ball to the boy.  0.197785  0.802215
6   Mrs. Taylor kicked a soccer ball to Mr. Williams.  0.234284  0.765716
7                 Emma kicked a soccer ball to David.  0.191853  0.808147
8    The princess kicked a soccer ball to the prince.  0.198431  0.801569
9               Sarah kicked a soccer ball to Robert.  0.465462  0.534538
10  Mrs. Williams kicked a soccer ball to  Mr. Tay...  0.227906  0.772094
11                Emily kicked a soccer ball to Paul.  0.663153  0.336847

In [23]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_3f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_3f,'He'))

P('subj-pron'|subj=female) =  0.2682275225718816
P('non-subj-pron'|subj=female) =  0.731772484878699

In [24]:
np_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3f,'She')
np_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3f,'He')

#### male subject

In [25]:
transofposs_perfective_noprompt_3m

                                             stimulus        He       She
12      Mr. Smith kicked a soccer ball to Miss Smith.  0.851411  0.148589
13         The man kicked a soccer ball to the woman.  0.875821  0.124179
14                 John kicked a soccer ball to Mary.  0.868177  0.131823
15                 Bob kicked a soccer ball to Alice.  0.865203  0.134797
16     The actor kicked a soccer ball to the actress.  0.869753  0.130247
17          The boy kicked a soccer ball to the girl.  0.867402  0.132598
18  Mr. William kicked a soccer ball to  Mrs. Taylor.  0.857095  0.142905
19                David kicked a soccer ball to Emma.  0.849673  0.150327
20   The prince kicked a soccer ball to the princess.  0.872125  0.127875
21              Robert kicked a soccer ball to Sarah.  0.230581  0.769419
22  Mr. Taylor kicked a soccer ball to Mrs. Williams.  0.853183  0.146817
23                Paul kicked a soccer ball to Emily.  0.858352  0.141648

In [26]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_3m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_3m,'She'))

P('subj-pron'|subj=male) =  0.8098979654411474
P('non-subj-pron'|subj=male) =  0.19010205566883087

In [27]:
np_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3m,'He')
np_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3m,'She')

### verb: "lobbed"

In [28]:
transofposs_perfective_noprompt_4 = pd.read_csv("../results/transofposs_perfective/no-prompt/4.csv")
transofposs_perfective_noprompt_4.head()

                                      stimulus        He       She
0   Miss Smith lobbed a football to Mr. Smith.  0.783898  0.216102
1      The woman lobbed a football to the man.  0.812600  0.187400
2              Mary lobbed a football to John.  0.788912  0.211088
3              Alice lobbed a football to Bob.  0.861876  0.138124
4  The actress lobbed a football to the actor.  0.827611  0.172389

In [29]:
# female subject
transofposs_perfective_noprompt_4f = transofposs_perfective_noprompt_4[0:12]
transofposs_perfective_noprompt_4f = transofposs_perfective_noprompt_4f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_4m = transofposs_perfective_noprompt_4[12:24]

#### female subject

In [30]:
transofposs_perfective_noprompt_4f

                                           stimulus       She        He
0        Miss Smith lobbed a football to Mr. Smith.  0.216102  0.783898
1           The woman lobbed a football to the man.  0.187400  0.812600
2                   Mary lobbed a football to John.  0.211088  0.788912
3                   Alice lobbed a football to Bob.  0.138124  0.861876
4       The actress lobbed a football to the actor.  0.172389  0.827611
5            The girl lobbed a football to the boy.  0.185070  0.814930
6    Mrs. Taylor lobbed a football to Mr. Williams.  0.213896  0.786104
7                  Emma lobbed a football to David.  0.194520  0.805480
8     The princess lobbed a football to the prince.  0.182300  0.817700
9                Sarah lobbed a football to Robert.  0.343772  0.656228
10  Mrs. Williams lobbed a football to  Mr. Taylor.  0.208750  0.791250
11                 Emily lobbed a football to Paul.  0.526644  0.473356

In [31]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_4f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_4f,'He'))

P('subj-pron'|subj=female) =  0.23167105515797934
P('non-subj-pron'|subj=female) =  0.7683289423584938

In [32]:
np_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4f,'She')
np_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4f,'He')

#### male subject

In [33]:
transofposs_perfective_noprompt_4m

                                          stimulus        He       She
12      Mr. Smith lobbed a football to Miss Smith.  0.852170  0.147830
13         The man lobbed a football to the woman.  0.877044  0.122956
14                 John lobbed a football to Mary.  0.859891  0.140109
15                 Bob lobbed a football to Alice.  0.413408  0.586592
16     The actor lobbed a football to the actress.  0.871764  0.128236
17          The boy lobbed a football to the girl.  0.869692  0.130308
18  Mr. William lobbed a football to  Mrs. Taylor.  0.857816  0.142184
19                David lobbed a football to Emma.  0.135872  0.864128
20   The prince lobbed a football to the princess.  0.874079  0.125921
21              Robert lobbed a football to Sarah.  0.103316  0.896684
22  Mr. Taylor lobbed a football to Mrs. Williams.  0.852534  0.147466
23                Paul lobbed a football to Emily.  0.848657  0.151343

In [34]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_4m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_4m,'She'))

P('subj-pron'|subj=male) =  0.701353631913662
P('non-subj-pron'|subj=male) =  0.29864637677868205

In [35]:
np_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4m,'He')
np_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4m,'She')

### verb: "rolled"

In [36]:
transofposs_perfective_noprompt_5 = pd.read_csv("../results/transofposs_perfective/no-prompt/5.csv")
transofposs_perfective_noprompt_5.head()

                                       stimulus        He       She
0   Miss Smith rolled a toy truck to Mr. Smith.  0.754098  0.245902
1      The woman rolled a toy truck to the man.  0.793305  0.206695
2              Mary rolled a toy truck to John.  0.529335  0.470665
3              Alice rolled a toy truck to Bob.  0.271188  0.728812
4  The actress rolled a toy truck to the actor.  0.814036  0.185964

In [37]:
# female subject
transofposs_perfective_noprompt_5f = transofposs_perfective_noprompt_5[0:12]
transofposs_perfective_noprompt_5f = transofposs_perfective_noprompt_5f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_5m = transofposs_perfective_noprompt_5[12:24]

#### female subject

In [38]:
transofposs_perfective_noprompt_5f

                                            stimulus       She        He
0        Miss Smith rolled a toy truck to Mr. Smith.  0.245902  0.754098
1           The woman rolled a toy truck to the man.  0.206695  0.793305
2                   Mary rolled a toy truck to John.  0.470665  0.529335
3                   Alice rolled a toy truck to Bob.  0.728812  0.271188
4       The actress rolled a toy truck to the actor.  0.185964  0.814036
5            The girl rolled a toy truck to the boy.  0.201451  0.798549
6    Mrs. Taylor rolled a toy truck to Mr. Williams.  0.243965  0.756035
7                  Emma rolled a toy truck to David.  0.199829  0.800171
8     The princess rolled a toy truck to the prince.  0.204138  0.795862
9                Sarah rolled a toy truck to Robert.  0.746614  0.253386
10  Mrs. Williams rolled a toy truck to  Mr. Taylor.  0.236344  0.763656
11                 Emily rolled a toy truck to Paul.  0.184803  0.815197

In [39]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_5f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_5f,'He'))

P('subj-pron'|subj=female) =  0.32126524423559505
P('non-subj-pron'|subj=female) =  0.6787347570061684

In [40]:
np_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_5f,'She')
np_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_5f,'He')

#### male subject

In [41]:
transofposs_perfective_noprompt_5m

                                           stimulus        He       She
12      Mr. Smith rolled a toy truck to Miss Smith.  0.852801  0.147199
13         The man rolled a toy truck to the woman.  0.878242  0.121758
14                 John rolled a toy truck to Mary.  0.868498  0.131502
15                 Bob rolled a toy truck to Alice.  0.866838  0.133162
16     The actor rolled a toy truck to the actress.  0.871387  0.128613
17          The boy rolled a toy truck to the girl.  0.864579  0.135421
18  Mr. William rolled a toy truck to  Mrs. Taylor.  0.858927  0.141073
19                David rolled a toy truck to Emma.  0.844593  0.155407
20   The prince rolled a toy truck to the princess.  0.870994  0.129006
21              Robert rolled a toy truck to Sarah.  0.319708  0.680292
22  Mr. Taylor rolled a toy truck to Mrs. Williams.  0.855366  0.144634
23                Paul rolled a toy truck to Emily.  0.862334  0.137666

In [42]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_5m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_5m,'She'))

P('subj-pron'|subj=male) =  0.8178555319706599
P('non-subj-pron'|subj=male) =  0.18214446119964123

In [43]:
np_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_noprompt_5m,'He')
np_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_noprompt_5m,'She')

### verb: "threw"

In [44]:
transofposs_perfective_noprompt_6 = pd.read_csv("../results/transofposs_perfective/no-prompt/6.csv")
transofposs_perfective_noprompt_6.head()

                                stimulus        He       She
0   Miss Smith threw a hat to Mr. Smith.  0.782469  0.217531
1      The woman threw a hat to the man.  0.813480  0.186520
2              Mary threw a hat to John.  0.681005  0.318995
3              Alice threw a hat to Bob.  0.633030  0.366970
4  The actress threw a hat to the actor.  0.829680  0.170320

In [45]:
# female subject
transofposs_perfective_noprompt_6f = transofposs_perfective_noprompt_6[0:12]
transofposs_perfective_noprompt_6f = transofposs_perfective_noprompt_6f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_6m = transofposs_perfective_noprompt_6[12:24]

#### female subject

transofposs_perfective_noprompt_6f

In [46]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_6f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_6f,'He'))

P('subj-pron'|subj=female) =  0.28743628909190494
P('non-subj-pron'|subj=female) =  0.7125637183586756

In [47]:
np_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6f,'She')
np_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6f,'He')

#### male subject

In [48]:
transofposs_perfective_noprompt_6m

                                    stimulus        He       She
12      Mr. Smith threw a hat to Miss Smith.  0.852526  0.147474
13         The man threw a hat to the woman.  0.879136  0.120864
14                 John threw a hat to Mary.  0.860379  0.139621
15                 Bob threw a hat to Alice.  0.855172  0.144828
16     The actor threw a hat to the actress.  0.872208  0.127792
17          The boy threw a hat to the girl.  0.872435  0.127565
18  Mr. William threw a hat to  Mrs. Taylor.  0.860220  0.139780
19                David threw a hat to Emma.  0.226017  0.773983
20   The prince threw a hat to the princess.  0.874116  0.125884
21              Robert threw a hat to Sarah.  0.123041  0.876959
22  Mr. Taylor threw a hat to Mrs. Williams.  0.851623  0.148377
23                Paul threw a hat to Emily.  0.849168  0.150832

In [49]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_6m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_6m,'She'))

P('subj-pron'|subj=male) =  0.7480034486701092
P('non-subj-pron'|subj=male) =  0.2519965637475252

In [50]:
np_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6m,'He')
np_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6m,'She')

### verb: "tossed"

In [51]:
transofposs_perfective_noprompt_7 = pd.read_csv("../results/transofposs_perfective/no-prompt/7.csv")
transofposs_perfective_noprompt_7.head()

                                        stimulus        He       She
0   Miss Smith tossed a dish towel to Mr. Smith.  0.761179  0.238821
1      The woman tossed a dish towel to the man.  0.797164  0.202836
2              Mary tossed a dish towel to John.  0.673972  0.326028
3              Alice tossed a dish towel to Bob.  0.616261  0.383739
4  The actress tossed a dish towel to the actor.  0.817048  0.182952

In [52]:
# female subject
transofposs_perfective_noprompt_7f = transofposs_perfective_noprompt_7[0:12]
transofposs_perfective_noprompt_7f = transofposs_perfective_noprompt_7f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_7m = transofposs_perfective_noprompt_7[12:24]

#### female subject

In [53]:
transofposs_perfective_noprompt_7f

                                             stimulus       She        He
0        Miss Smith tossed a dish towel to Mr. Smith.  0.238821  0.761179
1           The woman tossed a dish towel to the man.  0.202836  0.797164
2                   Mary tossed a dish towel to John.  0.326028  0.673972
3                   Alice tossed a dish towel to Bob.  0.383739  0.616261
4       The actress tossed a dish towel to the actor.  0.182952  0.817048
5            The girl tossed a dish towel to the boy.  0.197253  0.802747
6    Mrs. Taylor tossed a dish towel to Mr. Williams.  0.238110  0.761890
7                  Emma tossed a dish towel to David.  0.197282  0.802718
8     The princess tossed a dish towel to the prince.  0.197712  0.802288
9                Sarah tossed a dish towel to Robert.  0.488242  0.511758
10  Mrs. Williams tossed a dish towel to  Mr. Taylor.  0.230818  0.769182
11                 Emily tossed a dish towel to Paul.  0.510546  0.489454

In [54]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_7f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_7f,'He'))

P('subj-pron'|subj=female) =  0.28286149352788925
P('non-subj-pron'|subj=female) =  0.7171384965380033

In [55]:
np_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7f,'She')
np_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7f,'He')

#### male subject

In [56]:
transofposs_perfective_noprompt_7m

                                            stimulus        He       She
12      Mr. Smith tossed a dish towel to Miss Smith.  0.851419  0.148581
13         The man tossed a dish towel to the woman.  0.877583  0.122417
14                 John tossed a dish towel to Mary.  0.870064  0.129936
15                 Bob tossed a dish towel to Alice.  0.864510  0.135490
16     The actor tossed a dish towel to the actress.  0.869161  0.130838
17          The boy tossed a dish towel to the girl.  0.867424  0.132576
18  Mr. William tossed a dish towel to  Mrs. Taylor.  0.856831  0.143169
19                David tossed a dish towel to Emma.  0.089790  0.910210
20   The prince tossed a dish towel to the princess.  0.869669  0.130331
21              Robert tossed a dish towel to Sarah.  0.105235  0.894765
22  Mr. Taylor tossed a dish towel to Mrs. Williams.  0.852015  0.147985
23                Paul tossed a dish towel to Emily.  0.859116  0.140884

In [57]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_7m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_7m,'She'))

P('subj-pron'|subj=male) =  0.736067938307921
P('non-subj-pron'|subj=male) =  0.26393204368650913

In [58]:
np_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7m,'He')
np_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7m,'She')

### verb: "brought"

In [59]:
transofposs_perfective_noprompt_8 = pd.read_csv("../results/transofposs_perfective/no-prompt/8.csv")
transofposs_perfective_noprompt_8.head()

                                            stimulus        He       She
0  Miss Smith brought a glass of water to Mr. Smith.  0.728987  0.271013
1     The woman brought a glass of water to the man.  0.766421  0.233579
2             Mary brought a glass of water to John.  0.494738  0.505262
3             Alice brought a glass of water to Bob.  0.342978  0.657022
4  The actress brought a glass of water to the ac...  0.783192  0.216808

In [60]:
# female subject
transofposs_perfective_noprompt_8f = transofposs_perfective_noprompt_8[0:12]
transofposs_perfective_noprompt_8f = transofposs_perfective_noprompt_8f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_8m = transofposs_perfective_noprompt_8[12:24]

#### female subject

In [61]:
transofposs_perfective_noprompt_8f

                                             stimulus       She        He
0   Miss Smith brought a glass of water to Mr. Smith.  0.271013  0.728987
1      The woman brought a glass of water to the man.  0.233579  0.766421
2              Mary brought a glass of water to John.  0.505262  0.494738
3              Alice brought a glass of water to Bob.  0.657022  0.342978
4   The actress brought a glass of water to the ac...  0.216808  0.783192
5       The girl brought a glass of water to the boy.  0.229225  0.770775
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.266051  0.733949
7             Emma brought a glass of water to David.  0.230809  0.769191
8   The princess brought a glass of water to the p...  0.235545  0.764455
9           Sarah brought a glass of water to Robert.  0.646386  0.353614
10  Mrs. Williams brought a glass of water to  Mr....  0.262583  0.737417
11            Emily brought a glass of water to Paul.  0.701067  0.298933

In [62]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_8f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_8f,'He'))

P('subj-pron'|subj=female) =  0.37127919619282085
P('non-subj-pron'|subj=female) =  0.628720797598362

In [63]:
np_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8f,'She')
np_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8f,'He')

#### male subject

In [64]:
transofposs_perfective_noprompt_8m

                                             stimulus        He       She
12  Mr. Smith brought a glass of water to Miss Smith.  0.849216  0.150784
13     The man brought a glass of water to the woman.  0.877485  0.122515
14             John brought a glass of water to Mary.  0.870298  0.129702
15             Bob brought a glass of water to Alice.  0.866120  0.133880
16  The actor brought a glass of water to the actr...  0.862432  0.137568
17      The boy brought a glass of water to the girl.  0.863458  0.136542
18  Mr. William brought a glass of water to  Mrs. ...  0.853003  0.146997
19            David brought a glass of water to Emma.  0.253810  0.746190
20  The prince brought a glass of water to the pri...  0.865548  0.134452
21          Robert brought a glass of water to Sarah.  0.183130  0.816870
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.849965  0.150035
23            Paul brought a glass of water to Emily.  0.862886  0.137114

In [65]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_8m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_8m,'She'))

P('subj-pron'|subj=male) =  0.7547792829573154
P('non-subj-pron'|subj=male) =  0.24522072387238344

In [66]:
np_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8m,'He')
np_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8m,'She')

### verb: "forwarded"

In [67]:
transofposs_perfective_noprompt_9 = pd.read_csv("../results/transofposs_perfective/no-prompt/9.csv")
transofposs_perfective_noprompt_9.head()

                                            stimulus        He       She
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.737053  0.262947
1    The woman forwarded a gossipy email to the man.  0.787663  0.212337
2            Mary forwarded a gossipy email to John.  0.746717  0.253283
3            Alice forwarded a gossipy email to Bob.  0.715353  0.284647
4  The actress forwarded a gossipy email to the a...  0.800373  0.199627

In [68]:
# female subject
transofposs_perfective_noprompt_9f = transofposs_perfective_noprompt_9[0:12]
transofposs_perfective_noprompt_9f = transofposs_perfective_noprompt_9f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_9m = transofposs_perfective_noprompt_9[12:24]

#### female subject

In [69]:
transofposs_perfective_noprompt_9f

                                             stimulus       She        He
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.262947  0.737053
1     The woman forwarded a gossipy email to the man.  0.212337  0.787663
2             Mary forwarded a gossipy email to John.  0.253283  0.746717
3             Alice forwarded a gossipy email to Bob.  0.284647  0.715353
4   The actress forwarded a gossipy email to the a...  0.199627  0.800373
5      The girl forwarded a gossipy email to the boy.  0.210885  0.789115
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.259857  0.740143
7            Emma forwarded a gossipy email to David.  0.242489  0.757511
8   The princess forwarded a gossipy email to the ...  0.217459  0.782541
9          Sarah forwarded a gossipy email to Robert.  0.390113  0.609887
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.255220  0.744780
11           Emily forwarded a gossipy email to Paul.  0.341416  0.658584

In [70]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_9f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_9f,'He'))

P('subj-pron'|subj=female) =  0.26085657998919487
P('non-subj-pron'|subj=female) =  0.7391434013843536

In [71]:
np_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9f,'She')
np_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9f,'He')

#### male subject

In [72]:
transofposs_perfective_noprompt_9m

                                             stimulus        He       She
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.845455  0.154545
13    The man forwarded a gossipy email to the woman.  0.870245  0.129755
14            John forwarded a gossipy email to Mary.  0.860047  0.139953
15            Bob forwarded a gossipy email to Alice.  0.345390  0.654610
16  The actor forwarded a gossipy email to the act...  0.864770  0.135230
17     The boy forwarded a gossipy email to the girl.  0.858025  0.141974
18  Mr. William forwarded a gossipy email to  Mrs....  0.849664  0.150336
19           David forwarded a gossipy email to Emma.  0.092918  0.907082
20  The prince forwarded a gossipy email to the pr...  0.866136  0.133864
21         Robert forwarded a gossipy email to Sarah.  0.241049  0.758951
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.844240  0.155760
23           Paul forwarded a gossipy email to Emily.  0.840715  0.159285

In [73]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_9m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_9m,'She'))

P('subj-pron'|subj=male) =  0.6982212426761786
P('non-subj-pron'|subj=male) =  0.30177874863147736

In [74]:
np_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9m,'He')
np_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9m,'She')

### verb: "mailed"

In [75]:
transofposs_perfective_noprompt_10 = pd.read_csv("../results/transofposs_perfective/no-prompt/10.csv")
transofposs_perfective_noprompt_10.head()

                                    stimulus        He       She
0   Miss Smith mailed a letter to Mr. Smith.  0.746237  0.253763
1      The woman mailed a letter to the man.  0.800541  0.199459
2              Mary mailed a letter to John.  0.771720  0.228280
3              Alice mailed a letter to Bob.  0.734506  0.265494
4  The actress mailed a letter to the actor.  0.801857  0.198143

In [76]:
# female subject
transofposs_perfective_noprompt_10f = transofposs_perfective_noprompt_10[0:12]
transofposs_perfective_noprompt_10f = transofposs_perfective_noprompt_10f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_10m = transofposs_perfective_noprompt_10[12:24]

#### female subject

In [77]:
transofposs_perfective_noprompt_10f

                                         stimulus       She        He
0        Miss Smith mailed a letter to Mr. Smith.  0.253763  0.746237
1           The woman mailed a letter to the man.  0.199459  0.800541
2                   Mary mailed a letter to John.  0.228280  0.771720
3                   Alice mailed a letter to Bob.  0.265494  0.734506
4       The actress mailed a letter to the actor.  0.198143  0.801857
5            The girl mailed a letter to the boy.  0.201387  0.798613
6    Mrs. Taylor mailed a letter to Mr. Williams.  0.248917  0.751083
7                  Emma mailed a letter to David.  0.937032  0.062968
8     The princess mailed a letter to the prince.  0.210252  0.789748
9                Sarah mailed a letter to Robert.  0.282031  0.717969
10  Mrs. Williams mailed a letter to  Mr. Taylor.  0.243821  0.756179
11                 Emily mailed a letter to Paul.  0.445999  0.554001

In [78]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_10f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_10f,'He'))

P('subj-pron'|subj=female) =  0.3095480315387249
P('non-subj-pron'|subj=female) =  0.6904519479721785

In [79]:
np_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10f,'She')
np_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10f,'He')

#### male subject

In [80]:
transofposs_perfective_noprompt_10m

                                        stimulus        He       She
12      Mr. Smith mailed a letter to Miss Smith.  0.844766  0.155234
13         The man mailed a letter to the woman.  0.873730  0.126270
14                 John mailed a letter to Mary.  0.855857  0.144143
15                 Bob mailed a letter to Alice.  0.359256  0.640744
16     The actor mailed a letter to the actress.  0.871523  0.128477
17          The boy mailed a letter to the girl.  0.867124  0.132876
18  Mr. William mailed a letter to  Mrs. Taylor.  0.854001  0.145999
19                David mailed a letter to Emma.  0.155392  0.844608
20   The prince mailed a letter to the princess.  0.873307  0.126693
21              Robert mailed a letter to Sarah.  0.156209  0.843791
22  Mr. Taylor mailed a letter to Mrs. Williams.  0.840982  0.159018
23                Paul mailed a letter to Emily.  0.834240  0.165760

In [81]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_10m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_10m,'She'))

P('subj-pron'|subj=male) =  0.6988654894133409
P('non-subj-pron'|subj=male) =  0.30113451307018596

In [82]:
np_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10m,'He')
np_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10m,'She')

### verb: "shipped"

In [83]:
transofposs_perfective_noprompt_11 = pd.read_csv("../results/transofposs_perfective/no-prompt/11.csv")
transofposs_perfective_noprompt_11.head()

                                      stimulus        He       She
0   Miss Smith shipped a package to Mr. Smith.  0.751963  0.248037
1      The woman shipped a package to the man.  0.801740  0.198260
2              Mary shipped a package to John.  0.688522  0.311478
3              Alice shipped a package to Bob.  0.661254  0.338746
4  The actress shipped a package to the actor.  0.803060  0.196940

In [84]:
# female subject
transofposs_perfective_noprompt_11f = transofposs_perfective_noprompt_11[0:12]
transofposs_perfective_noprompt_11f = transofposs_perfective_noprompt_11f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_11m = transofposs_perfective_noprompt_11[12:24]

#### female subject

In [85]:
transofposs_perfective_noprompt_11f

                                           stimulus       She        He
0        Miss Smith shipped a package to Mr. Smith.  0.248037  0.751963
1           The woman shipped a package to the man.  0.198260  0.801740
2                   Mary shipped a package to John.  0.311478  0.688522
3                   Alice shipped a package to Bob.  0.338746  0.661254
4       The actress shipped a package to the actor.  0.196940  0.803060
5            The girl shipped a package to the boy.  0.206185  0.793815
6    Mrs. Taylor shipped a package to Mr. Williams.  0.237615  0.762385
7                  Emma shipped a package to David.  0.259109  0.740891
8     The princess shipped a package to the prince.  0.210384  0.789616
9                Sarah shipped a package to Robert.  0.430520  0.569480
10  Mrs. Williams shipped a package to  Mr. Taylor.  0.233855  0.766145
11                 Emily shipped a package to Paul.  0.508214  0.491786

In [86]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_11f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_11f,'He'))

P('subj-pron'|subj=female) =  0.2816117803255717
P('non-subj-pron'|subj=female) =  0.7183882147073746

In [87]:
np_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11f,'She')
np_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11f,'He')

#### male subject

In [88]:
transofposs_perfective_noprompt_11m

                                          stimulus        He       She
12      Mr. Smith shipped a package to Miss Smith.  0.839785  0.160216
13         The man shipped a package to the woman.  0.870190  0.129810
14                 John shipped a package to Mary.  0.842854  0.157146
15                 Bob shipped a package to Alice.  0.395561  0.604439
16     The actor shipped a package to the actress.  0.863477  0.136523
17          The boy shipped a package to the girl.  0.853516  0.146484
18  Mr. William shipped a package to  Mrs. Taylor.  0.846822  0.153178
19                David shipped a package to Emma.  0.049706  0.950294
20   The prince shipped a package to the princess.  0.862832  0.137168
21              Robert shipped a package to Sarah.  0.197483  0.802517
22  Mr. Taylor shipped a package to Mrs. Williams.  0.835767  0.164233
23                Paul shipped a package to Emily.  0.826215  0.173785

In [89]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_11m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_11m,'She'))

P('subj-pron'|subj=male) =  0.6903505710264047
P('non-subj-pron'|subj=male) =  0.30964943890770275

In [90]:
np_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11m,'He')
np_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11m,'She')

### verb: "transmitted"

In [91]:
transofposs_perfective_noprompt_12 = pd.read_csv("../results/transofposs_perfective/no-prompt/12.csv")
transofposs_perfective_noprompt_12.head()

                                          stimulus        He       She
0   Miss Smith transmitted a message to Mr. Smith.  0.749889  0.250111
1      The woman transmitted a message to the man.  0.797095  0.202905
2              Mary transmitted a message to John.  0.741256  0.258744
3              Alice transmitted a message to Bob.  0.796889  0.203111
4  The actress transmitted a message to the actor.  0.808798  0.191202

In [92]:
# female subject
transofposs_perfective_noprompt_12f = transofposs_perfective_noprompt_12[0:12]
transofposs_perfective_noprompt_12f = transofposs_perfective_noprompt_12f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_12m = transofposs_perfective_noprompt_12[12:24]

#### female subject

In [93]:
transofposs_perfective_noprompt_12f

                                             stimulus       She        He
0      Miss Smith transmitted a message to Mr. Smith.  0.250111  0.749889
1         The woman transmitted a message to the man.  0.202905  0.797095
2                 Mary transmitted a message to John.  0.258744  0.741256
3                 Alice transmitted a message to Bob.  0.203111  0.796889
4     The actress transmitted a message to the actor.  0.191202  0.808798
5          The girl transmitted a message to the boy.  0.205066  0.794934
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.245030  0.754970
7                Emma transmitted a message to David.  0.941876  0.058124
8   The princess transmitted a message to the prince.  0.207062  0.792938
9              Sarah transmitted a message to Robert.  0.315329  0.684671
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.241376  0.758624
11               Emily transmitted a message to Paul.  0.410757  0.589243

In [94]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_12f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_12f,'He'))

P('subj-pron'|subj=female) =  0.3060474693775177
P('non-subj-pron'|subj=female) =  0.6939525464549661

In [95]:
np_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12f,'She')
np_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12f,'He')

#### male subject

In [96]:
transofposs_perfective_noprompt_12m

                                             stimulus        He       She
12     Mr. Smith transmitted a message to Miss Smith.  0.839630  0.160370
13        The man transmitted a message to the woman.  0.871858  0.128142
14                John transmitted a message to Mary.  0.846880  0.153120
15                Bob transmitted a message to Alice.  0.205038  0.794962
16    The actor transmitted a message to the actress.  0.865392  0.134608
17         The boy transmitted a message to the girl.  0.859441  0.140559
18  Mr. William transmitted a message to  Mrs. Tay...  0.844794  0.155206
19               David transmitted a message to Emma.  0.033787  0.966213
20  The prince transmitted a message to the princess.  0.866963  0.133037
21             Robert transmitted a message to Sarah.  0.060194  0.939806
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.834393  0.165607
23               Paul transmitted a message to Emily.  0.829916  0.170084

In [97]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_12m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_12m,'She'))

P('subj-pron'|subj=male) =  0.6631904980167747
P('non-subj-pron'|subj=male) =  0.33680948863426846

In [98]:
np_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12m,'He')
np_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12m,'She')

### verb: "wired"

In [99]:
transofposs_perfective_noprompt_14 = pd.read_csv("../results/transofposs_perfective/no-prompt/14.csv")
transofposs_perfective_noprompt_14.head()

                                stimulus        He       She
0   Miss Smith wired money to Mr. Smith.  0.775813  0.224187
1      The woman wired money to the man.  0.803488  0.196512
2              Mary wired money to John.  0.781089  0.218911
3              Alice wired money to Bob.  0.811524  0.188476
4  The actress wired money to the actor.  0.811759  0.188241

In [100]:
# female subject
transofposs_perfective_noprompt_14f = transofposs_perfective_noprompt_14[0:12]
transofposs_perfective_noprompt_14f = transofposs_perfective_noprompt_14f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_14m = transofposs_perfective_noprompt_14[12:24]

#### female subject

In [101]:
transofposs_perfective_noprompt_14f

                                     stimulus       She        He
0        Miss Smith wired money to Mr. Smith.  0.224187  0.775813
1           The woman wired money to the man.  0.196512  0.803488
2                   Mary wired money to John.  0.218911  0.781089
3                   Alice wired money to Bob.  0.188476  0.811524
4       The actress wired money to the actor.  0.188241  0.811759
5            The girl wired money to the boy.  0.189567  0.810433
6    Mrs. Taylor wired money to Mr. Williams.  0.222061  0.777939
7                  Emma wired money to David.  0.837774  0.162226
8     The princess wired money to the prince.  0.188134  0.811866
9                Sarah wired money to Robert.  0.461464  0.538536
10  Mrs. Williams wired money to  Mr. Taylor.  0.211901  0.788099
11                 Emily wired money to Paul.  0.333139  0.666861

In [102]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_14f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_14f,'He'))

P('subj-pron'|subj=female) =  0.28836411113540333
P('non-subj-pron'|subj=female) =  0.7116358689963818

In [103]:
np_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14f,'She')
np_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14f,'He')

#### male subject

In [104]:
transofposs_perfective_noprompt_14m

                                    stimulus        He       She
12      Mr. Smith wired money to Miss Smith.  0.848846  0.151154
13         The man wired money to the woman.  0.876421  0.123579
14                 John wired money to Mary.  0.849894  0.150106
15                 Bob wired money to Alice.  0.163326  0.836674
16     The actor wired money to the actress.  0.871613  0.128387
17          The boy wired money to the girl.  0.871394  0.128606
18  Mr. William wired money to  Mrs. Taylor.  0.862011  0.137988
19                David wired money to Emma.  0.092361  0.907639
20   The prince wired money to the princess.  0.875386  0.124614
21              Robert wired money to Sarah.  0.149854  0.850146
22  Mr. Taylor wired money to Mrs. Williams.  0.843809  0.156191
23                Paul wired money to Emily.  0.833524  0.166476

In [105]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_14m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_14m,'She'))

P('subj-pron'|subj=male) =  0.6782032710810503
P('non-subj-pron'|subj=male) =  0.32179673574864864

In [106]:
np_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14m,'He')
np_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14m,'She')

### verb: "carried"

In [107]:
transofposs_perfective_noprompt_15 = pd.read_csv("../results/transofposs_perfective/no-prompt/15.csv")
transofposs_perfective_noprompt_15.head()

                                   stimulus        He       She
0   Miss Smith carried a tray to Mr. Smith.  0.774251  0.225749
1      The woman carried a tray to the man.  0.808431  0.191569
2              Mary carried a tray to John.  0.695667  0.304333
3              Alice carried a tray to Bob.  0.451267  0.548733
4  The actress carried a tray to the actor.  0.821920  0.178080

In [108]:
# female subject
transofposs_perfective_noprompt_15f = transofposs_perfective_noprompt_15[0:12]
transofposs_perfective_noprompt_15f = transofposs_perfective_noprompt_15f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_15m = transofposs_perfective_noprompt_15[12:24]

#### female subject

In [109]:
transofposs_perfective_noprompt_15f

                                        stimulus       She        He
0        Miss Smith carried a tray to Mr. Smith.  0.225749  0.774251
1           The woman carried a tray to the man.  0.191569  0.808431
2                   Mary carried a tray to John.  0.304333  0.695667
3                   Alice carried a tray to Bob.  0.548733  0.451267
4       The actress carried a tray to the actor.  0.178080  0.821920
5            The girl carried a tray to the boy.  0.190030  0.809970
6    Mrs. Taylor carried a tray to Mr. Williams.  0.217017  0.782983
7                  Emma carried a tray to David.  0.211906  0.788094
8     The princess carried a tray to the prince.  0.188013  0.811987
9                Sarah carried a tray to Robert.  0.516785  0.483215
10  Mrs. Williams carried a tray to  Mr. Taylor.  0.209308  0.790692
11                 Emily carried a tray to Paul.  0.483951  0.516049

In [110]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_15f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_15f,'He'))

P('subj-pron'|subj=female) =  0.2887895094851653
P('non-subj-pron'|subj=female) =  0.7112104942401251

In [111]:
np_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15f,'She')
np_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15f,'He')

#### male subject

In [112]:
transofposs_perfective_noprompt_15m

                                       stimulus        He       She
12      Mr. Smith carried a tray to Miss Smith.  0.850299  0.149701
13         The man carried a tray to the woman.  0.878187  0.121813
14                 John carried a tray to Mary.  0.858096  0.141904
15                 Bob carried a tray to Alice.  0.852361  0.147639
16     The actor carried a tray to the actress.  0.869241  0.130759
17          The boy carried a tray to the girl.  0.866094  0.133906
18  Mr. William carried a tray to  Mrs. Taylor.  0.857880  0.142120
19                David carried a tray to Emma.  0.106013  0.893987
20   The prince carried a tray to the princess.  0.872256  0.127744
21              Robert carried a tray to Sarah.  0.384375  0.615625
22  Mr. Taylor carried a tray to Mrs. Williams.  0.849678  0.150322
23                Paul carried a tray to Emily.  0.844013  0.155987

In [113]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_15m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_15m,'She'))

P('subj-pron'|subj=male) =  0.7573745455592871
P('non-subj-pron'|subj=male) =  0.24262546499570212

In [114]:
np_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15m,'He')
np_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15m,'She')

### verb: "delivered"

In [115]:
transofposs_perfective_noprompt_16 = pd.read_csv("../results/transofposs_perfective/no-prompt/16.csv")
transofposs_perfective_noprompt_16.head()

                                         stimulus        He       She
0   Miss Smith delivered a subpoena to Mr. Smith.  0.777940  0.222060
1      The woman delivered a subpoena to the man.  0.813617  0.186383
2              Mary delivered a subpoena to John.  0.823765  0.176235
3              Alice delivered a subpoena to Bob.  0.765633  0.234367
4  The actress delivered a subpoena to the actor.  0.825041  0.174959

In [116]:
# female subject
transofposs_perfective_noprompt_16f = transofposs_perfective_noprompt_16[0:12]
transofposs_perfective_noprompt_16f = transofposs_perfective_noprompt_16f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_16m = transofposs_perfective_noprompt_16[12:24]

#### female subject

In [117]:
transofposs_perfective_noprompt_16f

                                             stimulus       She        He
0       Miss Smith delivered a subpoena to Mr. Smith.  0.222060  0.777940
1          The woman delivered a subpoena to the man.  0.186383  0.813617
2                  Mary delivered a subpoena to John.  0.176235  0.823765
3                  Alice delivered a subpoena to Bob.  0.234367  0.765633
4      The actress delivered a subpoena to the actor.  0.174959  0.825041
5           The girl delivered a subpoena to the boy.  0.185209  0.814791
6   Mrs. Taylor delivered a subpoena to Mr. Williams.  0.224170  0.775830
7                 Emma delivered a subpoena to David.  0.929426  0.070574
8    The princess delivered a subpoena to the prince.  0.183548  0.816452
9               Sarah delivered a subpoena to Robert.  0.235074  0.764926
10  Mrs. Williams delivered a subpoena to Mr. Taylor.  0.216127  0.783873
11                Emily delivered a subpoena to Paul.  0.440775  0.559225

In [118]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_16f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_16f,'He'))

P('subj-pron'|subj=female) =  0.28402767206231755
P('non-subj-pron'|subj=female) =  0.7159723360091448

In [119]:
np_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16f,'She')
np_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16f,'He')

#### male subject

In [120]:
transofposs_perfective_noprompt_16m

                                             stimulus        He       She
12      Mr. Smith delivered a subpoena to Miss Smith.  0.852440  0.147560
13         The man delivered a subpoena to the woman.  0.879230  0.120769
14                 John delivered a subpoena to Mary.  0.863509  0.136491
15                 Bob delivered a subpoena to Alice.  0.161217  0.838783
16     The actor delivered a subpoena to the actress.  0.873016  0.126984
17          The boy delivered a subpoena to the girl.  0.868539  0.131461
18   Mr. William delivered a subpoena to Mrs. Taylor.  0.861240  0.138760
19                David delivered a subpoena to Emma.  0.052765  0.947235
20   The prince delivered a subpoena to the princess.  0.876306  0.123694
21              Robert delivered a subpoena to Sarah.  0.124144  0.875856
22  Mr. Taylor delivered a subpoena to Mrs. Williams.  0.852191  0.147809
23                Paul delivered a subpoena to Emily.  0.843655  0.156345

In [121]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_16m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_16m,'She'))

P('subj-pron'|subj=male) =  0.6756876800209284
P('non-subj-pron'|subj=male) =  0.32431232184171677

In [122]:
np_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16m,'He')
np_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16m,'She')

### verb: "gave"

In [123]:
transofposs_perfective_noprompt_17 = pd.read_csv("../results/transofposs_perfective/no-prompt/17.csv")
transofposs_perfective_noprompt_17.head()

                                   stimulus        He       She
0   Miss Smith gave a sweater to Mr. Smith.  0.774134  0.225866
1      The woman gave a sweater to the man.  0.809023  0.190977
2              Mary gave a sweater to John.  0.584659  0.415341
3              Alice gave a sweater to Bob.  0.579672  0.420328
4  The actress gave a sweater to the actor.  0.820800  0.179200

In [124]:
# female subject
transofposs_perfective_noprompt_17f = transofposs_perfective_noprompt_17[0:12]
transofposs_perfective_noprompt_17f = transofposs_perfective_noprompt_17f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_17m = transofposs_perfective_noprompt_17[12:24]

#### female subject

In [125]:
transofposs_perfective_noprompt_17f

                                        stimulus       She        He
0        Miss Smith gave a sweater to Mr. Smith.  0.225866  0.774134
1           The woman gave a sweater to the man.  0.190977  0.809023
2                   Mary gave a sweater to John.  0.415341  0.584659
3                   Alice gave a sweater to Bob.  0.420328  0.579672
4       The actress gave a sweater to the actor.  0.179200  0.820800
5            The girl gave a sweater to the boy.  0.191083  0.808917
6    Mrs. Taylor gave a sweater to Mr. Williams.  0.226621  0.773379
7                  Emma gave a sweater to David.  0.913855  0.086145
8     The princess gave a sweater to the prince.  0.188313  0.811687
9                Sarah gave a sweater to Robert.  0.503613  0.496387
10  Mrs. Williams gave a sweater to  Mr. Taylor.  0.220156  0.779844
11                 Emily gave a sweater to Paul.  0.701604  0.298396

In [126]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_17f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_17f,'He'))

P('subj-pron'|subj=female) =  0.36474642778436345
P('non-subj-pron'|subj=female) =  0.6352535796662172

In [127]:
np_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17f,'She')
np_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17f,'He')

#### female subject

In [128]:
transofposs_perfective_noprompt_17m

                                       stimulus        He       She
12      Mr. Smith gave a sweater to Miss Smith.  0.850092  0.149908
13         The man gave a sweater to the woman.  0.881543  0.118457
14                 John gave a sweater to Mary.  0.863173  0.136827
15                 Bob gave a sweater to Alice.  0.249451  0.750549
16     The actor gave a sweater to the actress.  0.875262  0.124738
17          The boy gave a sweater to the girl.  0.873381  0.126619
18  Mr. William gave a sweater to  Mrs. Taylor.  0.857641  0.142359
19                David gave a sweater to Emma.  0.053079  0.946921
20   The prince gave a sweater to the princess.  0.875671  0.124329
21              Robert gave a sweater to Sarah.  0.098780  0.901221
22  Mr. Taylor gave a sweater to Mrs. Williams.  0.843402  0.156598
23                Paul gave a sweater to Emily.  0.849838  0.150162

In [129]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_17m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_17m,'She'))

P('subj-pron'|subj=male) =  0.6809425931423903
P('non-subj-pron'|subj=male) =  0.3190574248631795

In [130]:
np_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17m,'He')
np_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17m,'She')

### verb: "handed"

In [131]:
transofposs_perfective_noprompt_18 = pd.read_csv("../results/transofposs_perfective/no-prompt/18.csv")
transofposs_perfective_noprompt_18.head()

                                  stimulus        He       She
0   Miss Smith handed a book to Mr. Smith.  0.769972  0.230028
1      The woman handed a book to the man.  0.809923  0.190077
2              Mary handed a book to John.  0.724368  0.275632
3              Alice handed a book to Bob.  0.747970  0.252030
4  The actress handed a book to the actor.  0.818831  0.181169

In [132]:
# female subject
transofposs_perfective_noprompt_18f = transofposs_perfective_noprompt_18[0:12]
transofposs_perfective_noprompt_18f = transofposs_perfective_noprompt_18f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_18m = transofposs_perfective_noprompt_18[12:24]

#### female subject

In [133]:
transofposs_perfective_noprompt_18f

                                      stimulus       She        He
0       Miss Smith handed a book to Mr. Smith.  0.230028  0.769972
1          The woman handed a book to the man.  0.190077  0.809923
2                  Mary handed a book to John.  0.275632  0.724368
3                  Alice handed a book to Bob.  0.252030  0.747970
4      The actress handed a book to the actor.  0.181169  0.818831
5           The girl handed a book to the boy.  0.190126  0.809874
6   Mrs. Taylor handed a book to Mr. Williams.  0.221782  0.778218
7                 Emma handed a book to David.  0.941919  0.058081
8    The princess handed a book to the prince.  0.190635  0.809365
9               Sarah handed a book to Robert.  0.380775  0.619225
10  Mrs. Williams handed a book to Mr. Taylor.  0.216880  0.783120
11                Emily handed a book to Paul.  0.472963  0.527037

In [134]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_18f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_18f,'He'))

P('subj-pron'|subj=female) =  0.31200137734413147
P('non-subj-pron'|subj=female) =  0.687998621724546

In [135]:
np_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18f,'She')
np_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18f,'He')

#### male subject

In [136]:
transofposs_perfective_noprompt_18m

                                      stimulus        He       She
12      Mr. Smith handed a book to Miss Smith.  0.848920  0.151080
13         The man handed a book to the woman.  0.878422  0.121578
14                 John handed a book to Mary.  0.856740  0.143260
15                 Bob handed a book to Alice.  0.050247  0.949753
16     The actor handed a book to the actress.  0.289501  0.710499
17          The boy handed a book to the girl.  0.869143  0.130857
18   Mr. William handed a book to Mrs. Taylor.  0.856211  0.143789
19                David handed a book to Emma.  0.008347  0.991653
20   The prince handed a book to the princess.  0.873029  0.126971
21              Robert handed a book to Sarah.  0.026814  0.973185
22  Mr. Taylor handed a book to Mrs. Williams.  0.847461  0.152539
23                Paul handed a book to Emily.  0.848504  0.151496

In [137]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_18m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_18m,'She'))

P('subj-pron'|subj=male) =  0.60444491628247
P('non-subj-pron'|subj=male) =  0.3955550752580166

In [138]:
np_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18m,'He')
np_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18m,'She')

### verb: "passed"

In [139]:
transofposs_perfective_noprompt_19 = pd.read_csv("../results/transofposs_perfective/no-prompt/19.csv")
transofposs_perfective_noprompt_19.head()

                                      stimulus        He       She
0   Miss Smith passed a sandwich to Mr. Smith.  0.768089  0.231911
1      The woman passed a sandwich to the man.  0.803170  0.196830
2              Mary passed a sandwich to John.  0.648579  0.351421
3              Alice passed a sandwich to Bob.  0.671339  0.328661
4  The actress passed a sandwich to the actor.  0.816214  0.183786

In [140]:
# female subject
transofposs_perfective_noprompt_19f = transofposs_perfective_noprompt_19[0:12]
transofposs_perfective_noprompt_19f = transofposs_perfective_noprompt_19f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_19m = transofposs_perfective_noprompt_19[12:24]

#### female subject

In [141]:
transofposs_perfective_noprompt_19f

                                           stimulus       She        He
0        Miss Smith passed a sandwich to Mr. Smith.  0.231911  0.768089
1           The woman passed a sandwich to the man.  0.196830  0.803170
2                   Mary passed a sandwich to John.  0.351421  0.648579
3                   Alice passed a sandwich to Bob.  0.328661  0.671339
4       The actress passed a sandwich to the actor.  0.183786  0.816214
5            The girl passed a sandwich to the boy.  0.198580  0.801420
6    Mrs. Taylor passed a sandwich to Mr. Williams.  0.224965  0.775035
7                  Emma passed a sandwich to David.  0.226146  0.773854
8     The princess passed a sandwich to the prince.  0.196001  0.803999
9                Sarah passed a sandwich to Robert.  0.518763  0.481237
10  Mrs. Williams passed a sandwich to  Mr. Taylor.  0.221610  0.778390
11                 Emily passed a sandwich to Paul.  0.590122  0.409878

In [142]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_19f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_19f,'He'))

P('subj-pron'|subj=female) =  0.2890663519501686
P('non-subj-pron'|subj=female) =  0.7109336405992508

In [143]:
np_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19f,'She')
np_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19f,'He')

#### male subject

In [144]:
transofposs_perfective_noprompt_19m

                                          stimulus        He       She
12      Mr. Smith passed a sandwich to Miss Smith.  0.855122  0.144878
13         The man passed a sandwich to the woman.  0.881872  0.118128
14                 John passed a sandwich to Mary.  0.868907  0.131093
15                 Bob passed a sandwich to Alice.  0.656895  0.343105
16     The actor passed a sandwich to the actress.  0.880901  0.119099
17          The boy passed a sandwich to the girl.  0.879488  0.120512
18  Mr. William passed a sandwich to  Mrs. Taylor.  0.857618  0.142382
19                David passed a sandwich to Emma.  0.084689  0.915311
20   The prince passed a sandwich to the princess.  0.877802  0.122198
21              Robert passed a sandwich to Sarah.  0.235821  0.764179
22  Mr. Taylor passed a sandwich to Mrs. Williams.  0.849093  0.150907
23                Paul passed a sandwich to Emily.  0.855262  0.144738

In [145]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_19m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_19m,'She'))

P('subj-pron'|subj=male) =  0.7319558939586083
P('non-subj-pron'|subj=male) =  0.2680441023161014

In [146]:
np_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19m,'He')
np_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19m,'She')

### verb: "served"

In [147]:
transofposs_perfective_noprompt_20 = pd.read_csv("../results/transofposs_perfective/no-prompt/20.csv")
transofposs_perfective_noprompt_20.head()

                                   stimulus        He       She
0   Miss Smith served a chili to Mr. Smith.  0.777951  0.222049
1      The woman served a chili to the man.  0.808532  0.191468
2              Mary served a chili to John.  0.599174  0.400826
3              Alice served a chili to Bob.  0.291971  0.708029
4  The actress served a chili to the actor.  0.823243  0.176757

In [148]:
# female subject
transofposs_perfective_noprompt_20f = transofposs_perfective_noprompt_20[0:12]
transofposs_perfective_noprompt_20f = transofposs_perfective_noprompt_20f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_20m = transofposs_perfective_noprompt_20[12:24]

#### female subject

In [149]:
transofposs_perfective_noprompt_20f

                                       stimulus       She        He
0       Miss Smith served a chili to Mr. Smith.  0.222049  0.777951
1          The woman served a chili to the man.  0.191468  0.808532
2                  Mary served a chili to John.  0.400826  0.599174
3                  Alice served a chili to Bob.  0.708029  0.291971
4      The actress served a chili to the actor.  0.176757  0.823243
5           The girl served a chili to the boy.  0.191240  0.808760
6   Mrs. Taylor served a chili to Mr. Williams.  0.224674  0.775326
7                 Emma served a chili to David.  0.208860  0.791140
8    The princess served a chili to the prince.  0.190615  0.809384
9               Sarah served a chili to Robert.  0.777204  0.222796
10  Mrs. Williams served a chili to Mr. Taylor.  0.220092  0.779908
11                Emily served a chili to Paul.  0.851469  0.148531

In [150]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_20f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_20f,'He'))

P('subj-pron'|subj=female) =  0.3636070042848587
P('non-subj-pron'|subj=female) =  0.636392991989851

In [151]:
np_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_noprompt_20f,'She')
np_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_noprompt_20f,'He')

#### male subject

In [152]:
transofposs_perfective_noprompt_20m

                                       stimulus        He       She
12      Mr. Smith served a chili to Miss Smith.  0.854100  0.145900
13         The man served a chili to the woman.  0.876888  0.123112
14                 John served a chili to Mary.  0.865618  0.134382
15                 Bob served a chili to Alice.  0.856731  0.143269
16     The actor served a chili to the actress.  0.869662  0.130338
17          The boy served a chili to the girl.  0.869944  0.130056
18  Mr. William served a chili to  Mrs. Taylor.  0.860344  0.139656
19                David served a chili to Emma.  0.460562  0.539438
20   The prince served a chili to the princess.  0.876366  0.123634
21              Robert served a chili to Sarah.  0.522381  0.477619
22  Mr. Taylor served a chili to Mrs. Williams.  0.853197  0.146803
23                Paul served a chili to Emily.  0.850525  0.149475

In [153]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_20m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_20m,'She'))

P('subj-pron'|subj=male) =  0.8013599316279093
P('non-subj-pron'|subj=male) =  0.19864007706443468

In [154]:
np_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_noprompt_20m,'He')
np_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_noprompt_20m,'She')

## Summary of Results

In [155]:
results_fsubj_subjpron = pd.DataFrame(list(np_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
results_fsubj_objpron = pd.DataFrame(list(np_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
results_fsubj = results_fsubj_subjpron.merge(results_fsubj_objpron)
results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0         flung              0.233454             0.766546
1        kicked              0.268228             0.731772
2        lobbed              0.321265             0.678735
3         threw              0.287436             0.712564
4        tossed              0.282861             0.717138
5       brought              0.371279             0.628721
6     forwarded              0.260857             0.739143
7        mailed              0.309548             0.690452
8       shipped              0.281612             0.718388
9   transmitted              0.306047             0.693953
10        wired              0.288364             0.711636
11      carried              0.288790             0.711210
12    delivered              0.284028             0.715972
13         gave              0.364746             0.635254
14       handed              0.312001             0.687999
15       passed              0.289066             0.710934
16       served              0.363607             0.636393

In [156]:
results_msubj_subjpron = pd.DataFrame(list(np_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
results_msubj_objpron = pd.DataFrame(list(np_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
results_msubj = results_msubj_subjpron.merge(results_msubj_objpron)
results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0         flung            0.739469           0.260531
1        kicked            0.809898           0.190102
2        lobbed            0.701354           0.298646
3        rolled            0.817856           0.182144
4         threw            0.748003           0.251997
5        tossed            0.736068           0.263932
6       brought            0.754779           0.245221
7     forwarded            0.698221           0.301779
8        mailed            0.698865           0.301135
9       shipped            0.690351           0.309649
10  transmitted            0.663190           0.336809
11        wired            0.678203           0.321797
12      carried            0.757375           0.242625
13    delivered            0.675688           0.324312
14         gave            0.680943           0.319057
15       handed            0.604445           0.395555
16       passed            0.731956           0.268044
17       served            0.801360           0.198640

In [157]:
results = results_fsubj.merge(results_msubj)
results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flung,0.233454,0.766546,0.739469,0.260531
1,kicked,0.268228,0.731772,0.809898,0.190102
2,lobbed,0.321265,0.678735,0.701354,0.298646
3,threw,0.287436,0.712564,0.748003,0.251997
4,tossed,0.282861,0.717138,0.736068,0.263932
5,brought,0.371279,0.628721,0.754779,0.245221
6,forwarded,0.260857,0.739143,0.698221,0.301779
7,mailed,0.309548,0.690452,0.698865,0.301135
8,shipped,0.281612,0.718388,0.690351,0.309649
9,transmitted,0.306047,0.693953,0.663190,0.336809
10,wired,0.288364,0.711636,0.678203,0.321797
11,carried,0.288790,0.711210,0.757375,0.242625
12,delivered,0.284028,0.715972,0.675688,0.324312
13,gave,0.364746,0.635254,0.680943,0.319057
14,handed,0.312001,0.687999,0.604445,0.395555
15,passed,0.289066,0.710934,0.731956,0.268044
16,served,0.363607,0.636393,0.801360,0.198640

In [158]:
print("P(subj_reference |subj=female)", compute_average(results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.3007759098328796
P(obj_reference |subj=female) 0.6992240874644589

In [159]:
print("P(subj_reference |subj=male)", compute_average(results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.7158922052659168
P(obj_reference |subj=male) 0.28410779922177976

## Connective: "because"

In [160]:
c1_average_subj_female_subj_pron = {}
c1_average_subj_female_obj_pron = {}
c1_average_subj_male_subj_pron = {}
c1_average_subj_male_obj_pron = {}

### verb: "chucked"

In [161]:
transofposs_perfective_connective1_1 = pd.read_csv("../results/transofposs_perfective/connective1/1.csv")
transofposs_perfective_connective1_1.head()

                                            stimulus        he       she
0   Miss Smith chucked a wrench to Mr. Smith because  0.312382  0.687618
1      The woman chucked a wrench to the man because  0.453211  0.546788
2              Mary chucked a wrench to John because  0.256879  0.743121
3              Alice chucked a wrench to Bob because  0.226170  0.773830
4  The actress chucked a wrench to the actor because  0.267859  0.732141

In [162]:
# female subject
transofposs_perfective_connective1_1f = transofposs_perfective_connective1_1[0:12]
transofposs_perfective_connective1_1f = transofposs_perfective_connective1_1f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_1m = transofposs_perfective_connective1_1[12:24]

#### female subject

In [163]:
transofposs_perfective_connective1_1f

                                             stimulus       she        he
0    Miss Smith chucked a wrench to Mr. Smith because  0.687618  0.312382
1       The woman chucked a wrench to the man because  0.546788  0.453211
2               Mary chucked a wrench to John because  0.743121  0.256879
3               Alice chucked a wrench to Bob because  0.773830  0.226170
4   The actress chucked a wrench to the actor because  0.732141  0.267859
5        The girl chucked a wrench to the boy because  0.652357  0.347643
6   Mrs. Taylor chucked a wrench to Mr. Williams b...  0.689857  0.310143
7              Emma chucked a wrench to David because  0.752160  0.247840
8   The princess chucked a wrench to the prince be...  0.602794  0.397206
9            Sarah chucked a wrench to Robert because  0.739982  0.260018
10  Mrs. Williams chucked a wrench to Mr. Taylor b...  0.619233  0.380768
11             Emily chucked a wrench to Paul because  0.607295  0.392705

In [164]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_1f,'he'))

P('subj-pron'|subj=female) =  0.6789313554763794
P('non-subj-pron'|subj=female) =  0.3210686569412549

In [165]:
c1_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1f,'she')
c1_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1f,'he')

#### male subject

In [166]:
transofposs_perfective_connective1_1m

                                             stimulus        he       she
12   Mr. Smith chucked a wrench to Miss Smith because  0.543726  0.456274
13      The man chucked a wrench to the woman because  0.552549  0.447451
14              John chucked a wrench to Mary because  0.569454  0.430546
15              Bob chucked a wrench to Alice because  0.423528  0.576472
16  The actor chucked a wrench to the actress because  0.418109  0.581891
17       The boy chucked a wrench to the girl because  0.598121  0.401879
18  Mr. William chucked a wrench to Mrs. Taylor be...  0.271531  0.728469
19             David chucked a wrench to Emma because  0.485725  0.514275
20  The prince chucked a wrench to the princess be...  0.655980  0.344020
21           Robert chucked a wrench to Sarah because  0.354373  0.645627
22  Mr. Taylor chucked a wrench to Mrs. Williams b...  0.214029  0.785971
23             Paul chucked a wrench to Emily because  0.456970  0.543030

In [167]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_1m,'she'))

P('subj-pron'|subj=male) =  0.4620079733431339
P('non-subj-pron'|subj=male) =  0.537992017964522

In [168]:
c1_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1m,'he')
c1_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1m,'she')

### verb: "flung"

In [169]:
transofposs_perfective_connective1_2 = pd.read_csv("../results/transofposs_perfective/connective1/2.csv")
transofposs_perfective_connective1_2.head()

                                           stimulus        he       she
0   Miss Smith flung a frisbee to Mr. Smith because  0.278319  0.721681
1      The woman flung a frisbee to the man because  0.502161  0.497839
2              Mary flung a frisbee to John because  0.469157  0.530843
3              Alice flung a frisbee to Bob because  0.512816  0.487184
4  The actress flung a frisbee to the actor because  0.378903  0.621097

In [170]:
# female subject
transofposs_perfective_connective1_2f = transofposs_perfective_connective1_2[0:12]
transofposs_perfective_connective1_2f = transofposs_perfective_connective1_2f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_2m = transofposs_perfective_connective1_2[12:24]

#### female subject

In [171]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_2f,'he'))

P('subj-pron'|subj=female) =  0.5763088688254356
P('non-subj-pron'|subj=female) =  0.4236911212404569

In [172]:
c1_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_connective1_2f,'she')
c1_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_connective1_2f,'he')

#### male subject

In [173]:
transofposs_perfective_connective1_2m

                                             stimulus        he       she
12    Mr. Smith flung a frisbee to Miss Smith because  0.575688  0.424312
13       The man flung a frisbee to the woman because  0.481168  0.518832
14               John flung a frisbee to Mary because  0.568747  0.431253
15               Bob flung a frisbee to Alice because  0.319874  0.680126
16   The actor flung a frisbee to the actress because  0.218456  0.781544
17        The boy flung a frisbee to the girl because  0.483595  0.516405
18  Mr. William flung a frisbee to  Mrs. Taylor be...  0.284464  0.715536
19              David flung a frisbee to Emma because  0.358723  0.641277
20  The prince flung a frisbee to the princess bec...  0.534078  0.465922
21            Robert flung a frisbee to Sarah because  0.147004  0.852996
22  Mr. Taylor flung a frisbee to Mrs. Williams be...  0.192851  0.807149
23              Paul flung a frisbee to Emily because  0.303048  0.696952

In [174]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_2m,'she'))

P('subj-pron'|subj=male) =  0.3723079127569993
P('non-subj-pron'|subj=male) =  0.6276920884847641

In [175]:
c1_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_connective1_2m,'he')
c1_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_connective1_2m,'she')

### verb: "kicked"

In [176]:
transofposs_perfective_connective1_3 = pd.read_csv("../results/transofposs_perfective/connective1/3.csv")
transofposs_perfective_connective1_3.head()

                                            stimulus        he       she
0  Miss Smith kicked a soccer ball to Mr. Smith b...  0.337070  0.662930
1  The woman kicked a soccer ball to the man because  0.466283  0.533717
2          Mary kicked a soccer ball to John because  0.427209  0.572791
3          Alice kicked a soccer ball to Bob because  0.506465  0.493535
4  The actress kicked a soccer ball to the actor ...  0.337886  0.662114

In [177]:
# female subject
transofposs_perfective_connective1_3f = transofposs_perfective_connective1_3[0:12]
transofposs_perfective_connective1_3f = transofposs_perfective_connective1_3f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_3m = transofposs_perfective_connective1_3[12:24]

#### female subject

In [178]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_3f,'he'))

P('subj-pron'|subj=female) =  0.5588973412911097
P('non-subj-pron'|subj=female) =  0.44110266367594403

In [179]:
c1_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3f,'she')
c1_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3f,'he')

#### male subject

In [180]:
transofposs_perfective_connective1_3m

                                             stimulus        he       she
12  Mr. Smith kicked a soccer ball to Miss Smith b...  0.502461  0.497539
13  The man kicked a soccer ball to the woman because  0.441916  0.558084
14          John kicked a soccer ball to Mary because  0.400963  0.599037
15          Bob kicked a soccer ball to Alice because  0.350174  0.649826
16  The actor kicked a soccer ball to the actress ...  0.245621  0.754379
17   The boy kicked a soccer ball to the girl because  0.415727  0.584274
18  Mr. William kicked a soccer ball to  Mrs. Tayl...  0.159726  0.840274
19         David kicked a soccer ball to Emma because  0.363268  0.636732
20  The prince kicked a soccer ball to the princes...  0.436987  0.563013
21       Robert kicked a soccer ball to Sarah because  0.296212  0.703788
22  Mr. Taylor kicked a soccer ball to Mrs. Willia...  0.120893  0.879107
23         Paul kicked a soccer ball to Emily because  0.358969  0.641031

In [181]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_3m,'she'))

P('subj-pron'|subj=male) =  0.34107648270825547
P('non-subj-pron'|subj=male) =  0.6589235241214434

In [182]:
c1_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3m,'he')
c1_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3m,'she')

### verb: "lobbed"

In [183]:
transofposs_perfective_connective1_4 = pd.read_csv("../results/transofposs_perfective/connective1/4.csv")
transofposs_perfective_connective1_4.head()

                                            stimulus        he       she
0  Miss Smith lobbed a football to Mr. Smith because  0.396931  0.603069
1     The woman lobbed a football to the man because  0.619297  0.380703
2             Mary lobbed a football to John because  0.531905  0.468095
3             Alice lobbed a football to Bob because  0.654363  0.345637
4  The actress lobbed a football to the actor bec...  0.458226  0.541774

In [184]:
# female subject
transofposs_perfective_connective1_4f = transofposs_perfective_connective1_4[0:12]
transofposs_perfective_connective1_4f = transofposs_perfective_connective1_4f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_4m = transofposs_perfective_connective1_4[12:24]

#### female subject

In [185]:
transofposs_perfective_connective1_4f

                                             stimulus       she        he
0   Miss Smith lobbed a football to Mr. Smith because  0.603069  0.396931
1      The woman lobbed a football to the man because  0.380703  0.619297
2              Mary lobbed a football to John because  0.468095  0.531905
3              Alice lobbed a football to Bob because  0.345637  0.654363
4   The actress lobbed a football to the actor bec...  0.541774  0.458226
5       The girl lobbed a football to the boy because  0.423421  0.576579
6   Mrs. Taylor lobbed a football to Mr. Williams ...  0.529395  0.470604
7             Emma lobbed a football to David because  0.509544  0.490456
8   The princess lobbed a football to the prince b...  0.366141  0.633859
9           Sarah lobbed a football to Robert because  0.417061  0.582939
10  Mrs. Williams lobbed a football to  Mr. Taylor...  0.493471  0.506529
11            Emily lobbed a football to Paul because  0.411230  0.588770

In [186]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_4f,'he'))

P('subj-pron'|subj=female) =  0.4574616973598798
P('non-subj-pron'|subj=female) =  0.5425383051236471

In [187]:
c1_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4f,'she')
c1_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4f,'he')

#### male subject

In [188]:
transofposs_perfective_connective1_4m

                                             stimulus        he       she
12  Mr. Smith lobbed a football to Miss Smith because  0.513713  0.486287
13     The man lobbed a football to the woman because  0.356285  0.643715
14             John lobbed a football to Mary because  0.345697  0.654303
15             Bob lobbed a football to Alice because  0.230117  0.769883
16  The actor lobbed a football to the actress bec...  0.204185  0.795815
17      The boy lobbed a football to the girl because  0.376035  0.623965
18  Mr. William lobbed a football to  Mrs. Taylor ...  0.173555  0.826445
19            David lobbed a football to Emma because  0.313695  0.686305
20  The prince lobbed a football to the princess b...  0.388822  0.611178
21          Robert lobbed a football to Sarah because  0.147863  0.852137
22  Mr. Taylor lobbed a football to Mrs. Williams ...  0.127628  0.872372
23            Paul lobbed a football to Emily because  0.259813  0.740187

In [189]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_4m,'she'))

P('subj-pron'|subj=male) =  0.28645068034529686
P('non-subj-pron'|subj=male) =  0.713549313445886

In [190]:
c1_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4m,'he')
c1_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4m,'she')

### verb: "rolled"

In [191]:
transofposs_perfective_connective1_5 = pd.read_csv("../results/transofposs_perfective/connective1/5.csv")
transofposs_perfective_connective1_5.head()

                                            stimulus        he       she
0  Miss Smith rolled a toy truck to Mr. Smith bec...  0.135997  0.864003
1    The woman rolled a toy truck to the man because  0.405182  0.594818
2            Mary rolled a toy truck to John because  0.255642  0.744358
3            Alice rolled a toy truck to Bob because  0.220522  0.779478
4  The actress rolled a toy truck to the actor be...  0.190407  0.809593

In [192]:
# female subject
transofposs_perfective_connective1_5f = transofposs_perfective_connective1_5[0:12]
transofposs_perfective_connective1_5f = transofposs_perfective_connective1_5[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_5m = transofposs_perfective_connective1_5[12:24]

#### female subject

In [193]:
transofposs_perfective_connective1_5f

                                             stimulus       she        he
0   Miss Smith rolled a toy truck to Mr. Smith bec...  0.864003  0.135997
1     The woman rolled a toy truck to the man because  0.594818  0.405182
2             Mary rolled a toy truck to John because  0.744358  0.255642
3             Alice rolled a toy truck to Bob because  0.779478  0.220522
4   The actress rolled a toy truck to the actor be...  0.809593  0.190407
5      The girl rolled a toy truck to the boy because  0.757317  0.242683
6   Mrs. Taylor rolled a toy truck to Mr. Williams...  0.824024  0.175976
7            Emma rolled a toy truck to David because  0.890648  0.109352
8   The princess rolled a toy truck to the prince ...  0.772113  0.227887
9          Sarah rolled a toy truck to Robert because  0.758277  0.241723
10  Mrs. Williams rolled a toy truck to  Mr. Taylo...  0.798950  0.201050
11           Emily rolled a toy truck to Paul because  0.695908  0.304092
12  Mr. Smith rolled a toy truck to Miss Smith bec...  0.377819  0.622181
13    The man rolled a toy truck to the woman because  0.484685  0.515316
14            John rolled a toy truck to Mary because  0.358372  0.641628
15            Bob rolled a toy truck to Alice because  0.309030  0.690970
16  The actor rolled a toy truck to the actress be...  0.724527  0.275473
17     The boy rolled a toy truck to the girl because  0.563547  0.436453
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.679399  0.320601
19           David rolled a toy truck to Emma because  0.522930  0.477070
20  The prince rolled a toy truck to the princess ...  0.363444  0.636556
21         Robert rolled a toy truck to Sarah because  0.745150  0.254850
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.753036  0.246964
23           Paul rolled a toy truck to Emily because  0.598969  0.401031

In [194]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_5f,'he'))

P('subj-pron'|subj=female) =  0.6570998492340246
P('non-subj-pron'|subj=female) =  0.3429001498346527

In [195]:
c1_average_subj_female_subj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5f,'she')
c1_average_subj_female_obj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5f,'he')

#### male subject

In [196]:
transofposs_perfective_connective1_5m

                                             stimulus        he       she
12  Mr. Smith rolled a toy truck to Miss Smith bec...  0.622181  0.377819
13    The man rolled a toy truck to the woman because  0.515316  0.484685
14            John rolled a toy truck to Mary because  0.641628  0.358372
15            Bob rolled a toy truck to Alice because  0.690970  0.309030
16  The actor rolled a toy truck to the actress be...  0.275473  0.724527
17     The boy rolled a toy truck to the girl because  0.436453  0.563547
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.320601  0.679399
19           David rolled a toy truck to Emma because  0.477070  0.522930
20  The prince rolled a toy truck to the princess ...  0.636556  0.363444
21         Robert rolled a toy truck to Sarah because  0.254850  0.745150
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.246964  0.753036
23           Paul rolled a toy truck to Emily because  0.401031  0.598969

In [197]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_5m,'she'))

P('subj-pron'|subj=male) =  0.45992431168754894
P('non-subj-pron'|subj=male) =  0.5400756970047951

In [198]:
c1_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5m,'he')
c1_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5m,'she')

### verb: "threw"

In [199]:
transofposs_perfective_connective1_6 = pd.read_csv("../results/transofposs_perfective/connective1/6.csv")
transofposs_perfective_connective1_6.head()

                                       stimulus        he       she
0   Miss Smith threw a hat to Mr. Smith because  0.254911  0.745089
1      The woman threw a hat to the man because  0.530537  0.469463
2              Mary threw a hat to John because  0.363265  0.636735
3              Alice threw a hat to Bob because  0.442376  0.557624
4  The actress threw a hat to the actor because  0.319705  0.680295

In [200]:
# female subject
transofposs_perfective_connective1_6f = transofposs_perfective_connective1_6[0:12]
transofposs_perfective_connective1_6f = transofposs_perfective_connective1_6[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_6m = transofposs_perfective_connective1_6[12:24]

#### female subject

In [201]:
transofposs_perfective_connective1_6f

                                            stimulus       she        he
0        Miss Smith threw a hat to Mr. Smith because  0.745089  0.254911
1           The woman threw a hat to the man because  0.469463  0.530537
2                   Mary threw a hat to John because  0.636735  0.363265
3                   Alice threw a hat to Bob because  0.557624  0.442376
4       The actress threw a hat to the actor because  0.680295  0.319705
5            The girl threw a hat to the boy because  0.567223  0.432777
6    Mrs. Taylor threw a hat to Mr. Williams because  0.592665  0.407335
7                  Emma threw a hat to David because  0.726011  0.273989
8     The princess threw a hat to the prince because  0.486376  0.513624
9                Sarah threw a hat to Robert because  0.695274  0.304726
10  Mrs. Williams threw a hat to  Mr. Taylor because  0.556116  0.443884
11                 Emily threw a hat to Paul because  0.592197  0.407803
12       Mr. Smith threw a hat to Miss Smith because  0.422534  0.577466
13          The man threw a hat to the woman because  0.491172  0.508828
14                  John threw a hat to Mary because  0.456706  0.543294
15                  Bob threw a hat to Alice because  0.644251  0.355749
16      The actor threw a hat to the actress because  0.675656  0.324344
17           The boy threw a hat to the girl because  0.483958  0.516042
18   Mr. William threw a hat to  Mrs. Taylor because  0.732650  0.267350
19                 David threw a hat to Emma because  0.562066  0.437934
20    The prince threw a hat to the princess because  0.430083  0.569917
21               Robert threw a hat to Sarah because  0.647486  0.352514
22   Mr. Taylor threw a hat to Mrs. Williams because  0.805283  0.194717
23                 Paul threw a hat to Emily because  0.599507  0.400493

In [202]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_6f,'he'))

P('subj-pron'|subj=female) =  0.5940175789097945
P('non-subj-pron'|subj=female) =  0.40598241798579693

In [203]:
c1_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_connective1_6f,'she')
c1_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_connective1_6f,'he')

#### male subject

In [204]:
transofposs_perfective_connective1_6m

                                           stimulus        he       she
12      Mr. Smith threw a hat to Miss Smith because  0.577466  0.422534
13         The man threw a hat to the woman because  0.508828  0.491172
14                 John threw a hat to Mary because  0.543294  0.456706
15                 Bob threw a hat to Alice because  0.355749  0.644251
16     The actor threw a hat to the actress because  0.324344  0.675656
17          The boy threw a hat to the girl because  0.516042  0.483958
18  Mr. William threw a hat to  Mrs. Taylor because  0.267350  0.732650
19                David threw a hat to Emma because  0.437934  0.562066
20   The prince threw a hat to the princess because  0.569917  0.430083
21              Robert threw a hat to Sarah because  0.352514  0.647486
22  Mr. Taylor threw a hat to Mrs. Williams because  0.194717  0.805283
23                Paul threw a hat to Emily because  0.400493  0.599507

In [205]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_6m,'she'))

P('subj-pron'|subj=male) =  0.4207206107676029
P('non-subj-pron'|subj=male) =  0.57927938302358

In [206]:
c1_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_connective1_6m,'he')
c1_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_connective1_6m,'she')

### verb: "tossed"

In [207]:
transofposs_perfective_connective1_7 = pd.read_csv("../results/transofposs_perfective/connective1/7.csv")
transofposs_perfective_connective1_7.head()

                                            stimulus        he       she
0  Miss Smith tossed a dish towel to Mr. Smith be...  0.274003  0.725997
1   The woman tossed a dish towel to the man because  0.570725  0.429275
2           Mary tossed a dish towel to John because  0.484538  0.515462
3           Alice tossed a dish towel to Bob because  0.520818  0.479182
4  The actress tossed a dish towel to the actor b...  0.366916  0.633084

In [208]:
# female subject
transofposs_perfective_connective1_7f = transofposs_perfective_connective1_7[0:12]
transofposs_perfective_connective1_7f = transofposs_perfective_connective1_7f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_7m = transofposs_perfective_connective1_7[12:24]

#### female subject

In [209]:
transofposs_perfective_connective1_7f

                                             stimulus       she        he
0   Miss Smith tossed a dish towel to Mr. Smith be...  0.725997  0.274003
1    The woman tossed a dish towel to the man because  0.429275  0.570725
2            Mary tossed a dish towel to John because  0.515462  0.484538
3            Alice tossed a dish towel to Bob because  0.479182  0.520818
4   The actress tossed a dish towel to the actor b...  0.633084  0.366916
5     The girl tossed a dish towel to the boy because  0.492789  0.507211
6   Mrs. Taylor tossed a dish towel to Mr. William...  0.560089  0.439911
7           Emma tossed a dish towel to David because  0.601490  0.398510
8   The princess tossed a dish towel to the prince...  0.430689  0.569311
9         Sarah tossed a dish towel to Robert because  0.489279  0.510720
10  Mrs. Williams tossed a dish towel to  Mr. Tayl...  0.528237  0.471763
11          Emily tossed a dish towel to Paul because  0.429328  0.570672

In [210]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_7f,'he'))

P('subj-pron'|subj=female) =  0.5262418438990911
P('non-subj-pron'|subj=female) =  0.47375814865032834

In [211]:
c1_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7f,'she')
c1_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7f,'he')

#### male subject

In [212]:
transofposs_perfective_connective1_7m

                                             stimulus        he       she
12  Mr. Smith tossed a dish towel to Miss Smith be...  0.487834  0.512166
13   The man tossed a dish towel to the woman because  0.379556  0.620444
14           John tossed a dish towel to Mary because  0.466655  0.533345
15           Bob tossed a dish towel to Alice because  0.199606  0.800394
16  The actor tossed a dish towel to the actress b...  0.182211  0.817789
17    The boy tossed a dish towel to the girl because  0.389112  0.610888
18  Mr. William tossed a dish towel to  Mrs. Taylo...  0.147444  0.852556
19          David tossed a dish towel to Emma because  0.307024  0.692976
20  The prince tossed a dish towel to the princess...  0.479456  0.520544
21        Robert tossed a dish towel to Sarah because  0.155226  0.844774
22  Mr. Taylor tossed a dish towel to Mrs. William...  0.117487  0.882513
23          Paul tossed a dish towel to Emily because  0.260654  0.739346

In [213]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_7m,'she'))

P('subj-pron'|subj=male) =  0.29768884368240833
P('non-subj-pron'|subj=male) =  0.7023111482461294

In [214]:
c1_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7m,'he')
c1_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7m,'she')

### verb: "brought"

In [215]:
transofposs_perfective_connective1_8 = pd.read_csv("../results/transofposs_perfective/connective1/8.csv")
transofposs_perfective_connective1_8.head()

                                            stimulus        he       she
0  Miss Smith brought a glass of water to Mr. Smi...  0.329641  0.670359
1  The woman brought a glass of water to the man ...  0.443728  0.556272
2      Mary brought a glass of water to John because  0.261947  0.738053
3      Alice brought a glass of water to Bob because  0.346367  0.653633
4  The actress brought a glass of water to the ac...  0.086090  0.913910

In [216]:
# female subject
transofposs_perfective_connective1_8f = transofposs_perfective_connective1_8[0:12]
transofposs_perfective_connective1_8f = transofposs_perfective_connective1_8f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_8m = transofposs_perfective_connective1_8[12:24]

#### female subject

In [217]:
transofposs_perfective_connective1_8f

                                             stimulus       she        he
0   Miss Smith brought a glass of water to Mr. Smi...  0.670359  0.329641
1   The woman brought a glass of water to the man ...  0.556272  0.443728
2       Mary brought a glass of water to John because  0.738053  0.261947
3       Alice brought a glass of water to Bob because  0.653633  0.346367
4   The actress brought a glass of water to the ac...  0.913910  0.086090
5   The girl brought a glass of water to the boy b...  0.699756  0.300244
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.680739  0.319261
7      Emma brought a glass of water to David because  0.753645  0.246355
8   The princess brought a glass of water to the p...  0.748616  0.251384
9    Sarah brought a glass of water to Robert because  0.581999  0.418001
10  Mrs. Williams brought a glass of water to  Mr....  0.575651  0.424349
11     Emily brought a glass of water to Paul because  0.541427  0.458573

In [218]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_8f,'he'))

P('subj-pron'|subj=female) =  0.6761716057856878
P('non-subj-pron'|subj=female) =  0.32382840601106483

In [219]:
c1_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_connective1_8f,'she')
c1_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_connective1_8f,'he')

#### male subject

In [220]:
transofposs_perfective_connective1_8m

                                             stimulus        he       she
12  Mr. Smith brought a glass of water to Miss Smi...  0.526915  0.473085
13  The man brought a glass of water to the woman ...  0.488130  0.511870
14      John brought a glass of water to Mary because  0.455747  0.544253
15      Bob brought a glass of water to Alice because  0.317865  0.682135
16  The actor brought a glass of water to the actr...  0.421001  0.578999
17  The boy brought a glass of water to the girl b...  0.491336  0.508664
18  Mr. William brought a glass of water to  Mrs. ...  0.193745  0.806256
19     David brought a glass of water to Emma because  0.477993  0.522007
20  The prince brought a glass of water to the pri...  0.594872  0.405128
21   Robert brought a glass of water to Sarah because  0.158829  0.841171
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.165997  0.834003
23     Paul brought a glass of water to Emily because  0.358102  0.641898

In [221]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_8m,'she'))

P('subj-pron'|subj=male) =  0.3875441960990429
P('non-subj-pron'|subj=male) =  0.6124558076262474

In [222]:
c1_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_connective1_8m,'he')
c1_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_connective1_8m,'she')

### verb: "forwarded"

In [223]:
transofposs_perfective_connective1_9 = pd.read_csv("../results/transofposs_perfective/connective1/9.csv")
transofposs_perfective_connective1_9.head()

                                            stimulus        he       she
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.128378  0.871622
1  The woman forwarded a gossipy email to the man...  0.537543  0.462457
2     Mary forwarded a gossipy email to John because  0.264517  0.735483
3     Alice forwarded a gossipy email to Bob because  0.475777  0.524223
4  The actress forwarded a gossipy email to the a...  0.206793  0.793207

In [224]:
# female subject
transofposs_perfective_connective1_9f = transofposs_perfective_connective1_9[0:12]
transofposs_perfective_connective1_9f = transofposs_perfective_connective1_9f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_9m = transofposs_perfective_connective1_9[12:24]

#### female subject

In [225]:
transofposs_perfective_connective1_9f

                                             stimulus       she        he
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.871622  0.128378
1   The woman forwarded a gossipy email to the man...  0.462457  0.537543
2      Mary forwarded a gossipy email to John because  0.735483  0.264517
3      Alice forwarded a gossipy email to Bob because  0.524223  0.475777
4   The actress forwarded a gossipy email to the a...  0.793207  0.206793
5   The girl forwarded a gossipy email to the boy ...  0.485199  0.514801
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.803973  0.196027
7     Emma forwarded a gossipy email to David because  0.824981  0.175019
8   The princess forwarded a gossipy email to the ...  0.496716  0.503284
9   Sarah forwarded a gossipy email to Robert because  0.630836  0.369164
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.724209  0.275791
11    Emily forwarded a gossipy email to Paul because  0.662059  0.337941

In [226]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_9f,'he'))

P('subj-pron'|subj=female) =  0.667913647989432
P('non-subj-pron'|subj=female) =  0.33208633462587994

In [227]:
c1_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9f,'she')
c1_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9f,'he')

#### male subject

In [228]:
transofposs_perfective_connective1_9m

                                             stimulus        he       she
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.581566  0.418434
13  The man forwarded a gossipy email to the woman...  0.507807  0.492193
14     John forwarded a gossipy email to Mary because  0.593202  0.406798
15     Bob forwarded a gossipy email to Alice because  0.351753  0.648247
16  The actor forwarded a gossipy email to the act...  0.261484  0.738516
17  The boy forwarded a gossipy email to the girl ...  0.451773  0.548227
18  Mr. William forwarded a gossipy email to  Mrs....  0.227387  0.772613
19    David forwarded a gossipy email to Emma because  0.506533  0.493467
20  The prince forwarded a gossipy email to the pr...  0.593513  0.406487
21  Robert forwarded a gossipy email to Sarah because  0.366978  0.633022
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.222868  0.777132
23    Paul forwarded a gossipy email to Emily because  0.432607  0.567393

In [229]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_9m,'she'))

P('subj-pron'|subj=male) =  0.4247891443471114
P('non-subj-pron'|subj=male) =  0.5752108494440714

In [230]:
c1_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9m,'he')
c1_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9m,'she')

### verb: "mailed"

In [231]:
transofposs_perfective_connective1_10 = pd.read_csv("../results/transofposs_perfective/connective1/10.csv")
transofposs_perfective_connective1_10.head()

                                           stimulus        he       she
0   Miss Smith mailed a letter to Mr. Smith because  0.091551  0.908449
1      The woman mailed a letter to the man because  0.428986  0.571014
2              Mary mailed a letter to John because  0.189923  0.810077
3              Alice mailed a letter to Bob because  0.365998  0.634002
4  The actress mailed a letter to the actor because  0.115131  0.884869

In [232]:
# female subject
transofposs_perfective_connective1_10f = transofposs_perfective_connective1_10[0:12]
transofposs_perfective_connective1_10f = transofposs_perfective_connective1_10f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_10m = transofposs_perfective_connective1_10[12:24]

#### female subject

In [233]:
transofposs_perfective_connective1_10f

                                             stimulus       she        he
0     Miss Smith mailed a letter to Mr. Smith because  0.908449  0.091551
1        The woman mailed a letter to the man because  0.571014  0.428986
2                Mary mailed a letter to John because  0.810077  0.189923
3                Alice mailed a letter to Bob because  0.634002  0.365998
4    The actress mailed a letter to the actor because  0.884869  0.115131
5         The girl mailed a letter to the boy because  0.588936  0.411064
6   Mrs. Taylor mailed a letter to Mr. Williams be...  0.827055  0.172945
7               Emma mailed a letter to David because  0.916963  0.083037
8   The princess mailed a letter to the prince bec...  0.637479  0.362521
9             Sarah mailed a letter to Robert because  0.729941  0.270059
10  Mrs. Williams mailed a letter to  Mr. Taylor b...  0.762516  0.237484
11              Emily mailed a letter to Paul because  0.839518  0.160482

In [234]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_10f,'he'))

P('subj-pron'|subj=female) =  0.7592348605394363
P('non-subj-pron'|subj=female) =  0.24076513635615507

In [235]:
c1_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10f,'she')
c1_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10f,'he')

#### male subject

In [236]:
transofposs_perfective_connective1_10m

                                             stimulus        he       she
12    Mr. Smith mailed a letter to Miss Smith because  0.648573  0.351427
13       The man mailed a letter to the woman because  0.523210  0.476790
14               John mailed a letter to Mary because  0.797820  0.202180
15               Bob mailed a letter to Alice because  0.439032  0.560968
16   The actor mailed a letter to the actress because  0.346654  0.653346
17        The boy mailed a letter to the girl because  0.502701  0.497299
18  Mr. William mailed a letter to  Mrs. Taylor be...  0.375585  0.624415
19              David mailed a letter to Emma because  0.674621  0.325379
20  The prince mailed a letter to the princess bec...  0.682867  0.317133
21            Robert mailed a letter to Sarah because  0.437772  0.562228
22  Mr. Taylor mailed a letter to Mrs. Williams be...  0.327684  0.672316
23              Paul mailed a letter to Emily because  0.541937  0.458063

In [237]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_10m,'she'))

P('subj-pron'|subj=male) =  0.524871344367663
P('non-subj-pron'|subj=male) =  0.4751286469399929

In [238]:
c1_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10m,'he')
c1_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10m,'she')

### verb: "shipped"

In [239]:
transofposs_perfective_connective1_11 = pd.read_csv("../results/transofposs_perfective/connective1/11.csv")
transofposs_perfective_connective1_11.head()

                                            stimulus        he       she
0  Miss Smith shipped a package to Mr. Smith because  0.129880  0.870120
1     The woman shipped a package to the man because  0.425283  0.574717
2             Mary shipped a package to John because  0.213314  0.786686
3             Alice shipped a package to Bob because  0.306684  0.693316
4  The actress shipped a package to the actor bec...  0.147401  0.852600

In [240]:
# female subject
transofposs_perfective_connective1_11f = transofposs_perfective_connective1_11[0:12]
transofposs_perfective_connective1_11f = transofposs_perfective_connective1_11f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_11m = transofposs_perfective_connective1_11[12:24]

#### female subject

In [241]:
transofposs_perfective_connective1_11f

                                             stimulus       she        he
0   Miss Smith shipped a package to Mr. Smith because  0.870120  0.129880
1      The woman shipped a package to the man because  0.574717  0.425283
2              Mary shipped a package to John because  0.786686  0.213314
3              Alice shipped a package to Bob because  0.693316  0.306684
4   The actress shipped a package to the actor bec...  0.852600  0.147401
5       The girl shipped a package to the boy because  0.672447  0.327553
6   Mrs. Taylor shipped a package to Mr. Williams ...  0.792309  0.207691
7             Emma shipped a package to David because  0.916277  0.083723
8   The princess shipped a package to the prince b...  0.568375  0.431625
9           Sarah shipped a package to Robert because  0.793239  0.206761
10  Mrs. Williams shipped a package to  Mr. Taylor...  0.732867  0.267133
11            Emily shipped a package to Paul because  0.740113  0.259887

In [242]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_11f,'he'))

P('subj-pron'|subj=female) =  0.7494221478700638
P('non-subj-pron'|subj=female) =  0.25057786020139855

In [243]:
c1_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11f,'she')
c1_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11f,'he')

#### male subject

In [244]:
transofposs_perfective_connective1_11m

                                             stimulus        he       she
12  Mr. Smith shipped a package to Miss Smith because  0.486539  0.513461
13     The man shipped a package to the woman because  0.432496  0.567504
14             John shipped a package to Mary because  0.428942  0.571058
15             Bob shipped a package to Alice because  0.191800  0.808200
16  The actor shipped a package to the actress bec...  0.128088  0.871912
17      The boy shipped a package to the girl because  0.268871  0.731129
18  Mr. William shipped a package to  Mrs. Taylor ...  0.137589  0.862411
19            David shipped a package to Emma because  0.284457  0.715543
20  The prince shipped a package to the princess b...  0.504777  0.495223
21          Robert shipped a package to Sarah because  0.128950  0.871050
22  Mr. Taylor shipped a package to Mrs. Williams ...  0.094294  0.905706
23            Paul shipped a package to Emily because  0.242748  0.757252

In [245]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_11m,'she'))

P('subj-pron'|subj=male) =  0.2774624402324359
P('non-subj-pron'|subj=male) =  0.7225375572840372

In [246]:
c1_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11m,'he')
c1_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11m,'she')

### verb: "transmitted"

In [247]:
transofposs_perfective_connective1_12 = pd.read_csv("../results/transofposs_perfective/connective1/12.csv")
transofposs_perfective_connective1_12.head()

                                            stimulus        he       she
0  Miss Smith transmitted a message to Mr. Smith ...  0.122744  0.877256
1  The woman transmitted a message to the man bec...  0.370823  0.629177
2         Mary transmitted a message to John because  0.169927  0.830073
3         Alice transmitted a message to Bob because  0.332626  0.667374
4  The actress transmitted a message to the actor...  0.183668  0.816332

In [248]:
# female subject
transofposs_perfective_connective1_12f = transofposs_perfective_connective1_12[0:12]
transofposs_perfective_connective1_12f = transofposs_perfective_connective1_12f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_12m = transofposs_perfective_connective1_12[12:24]

#### female subject

In [249]:
transofposs_perfective_connective1_12f

                                             stimulus       she        he
0   Miss Smith transmitted a message to Mr. Smith ...  0.877256  0.122744
1   The woman transmitted a message to the man bec...  0.629177  0.370823
2          Mary transmitted a message to John because  0.830073  0.169927
3          Alice transmitted a message to Bob because  0.667374  0.332626
4   The actress transmitted a message to the actor...  0.816332  0.183668
5   The girl transmitted a message to the boy because  0.694185  0.305815
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.832689  0.167311
7         Emma transmitted a message to David because  0.884486  0.115514
8   The princess transmitted a message to the prin...  0.666701  0.333299
9       Sarah transmitted a message to Robert because  0.791430  0.208570
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.746177  0.253823
11        Emily transmitted a message to Paul because  0.682621  0.317379

In [250]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_12f,'he'))

P('subj-pron'|subj=female) =  0.7598751187324524
P('non-subj-pron'|subj=female) =  0.24012490113576254

In [251]:
c1_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12f,'she')
c1_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12f,'he')

#### male subject

In [252]:
transofposs_perfective_connective1_12m

                                             stimulus        he       she
12  Mr. Smith transmitted a message to Miss Smith ...  0.607372  0.392628
13  The man transmitted a message to the woman bec...  0.558871  0.441129
14         John transmitted a message to Mary because  0.686754  0.313246
15         Bob transmitted a message to Alice because  0.351211  0.648789
16  The actor transmitted a message to the actress...  0.295453  0.704547
17  The boy transmitted a message to the girl because  0.479901  0.520099
18  Mr. William transmitted a message to  Mrs. Tay...  0.297031  0.702969
19        David transmitted a message to Emma because  0.516106  0.483894
20  The prince transmitted a message to the prince...  0.688369  0.311631
21      Robert transmitted a message to Sarah because  0.331737  0.668263
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.235712  0.764288
23        Paul transmitted a message to Emily because  0.420748  0.579252

In [253]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_12m,'she'))

P('subj-pron'|subj=male) =  0.45577213043967885
P('non-subj-pron'|subj=male) =  0.5442278906702995

In [254]:
c1_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12m,'he')
c1_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12m,'she')

### verb: "wired"

In [255]:
transofposs_perfective_connective1_14 = pd.read_csv("../results/transofposs_perfective/connective1/14.csv")
transofposs_perfective_connective1_14.head()

                                       stimulus        he       she
0   Miss Smith wired money to Mr. Smith because  0.347108  0.652892
1      The woman wired money to the man because  0.505137  0.494863
2              Mary wired money to John because  0.487218  0.512782
3              Alice wired money to Bob because  0.614548  0.385452
4  The actress wired money to the actor because  0.436052  0.563948

In [256]:
# female subject
transofposs_perfective_connective1_14f = transofposs_perfective_connective1_14[0:12]
transofposs_perfective_connective1_14f = transofposs_perfective_connective1_14f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_14m = transofposs_perfective_connective1_14[12:24]

#### female subject

In [257]:
transofposs_perfective_connective1_14f

                                            stimulus       she        he
0        Miss Smith wired money to Mr. Smith because  0.652892  0.347108
1           The woman wired money to the man because  0.494863  0.505137
2                   Mary wired money to John because  0.512782  0.487218
3                   Alice wired money to Bob because  0.385452  0.614548
4       The actress wired money to the actor because  0.563948  0.436052
5            The girl wired money to the boy because  0.519021  0.480979
6    Mrs. Taylor wired money to Mr. Williams because  0.609191  0.390809
7                  Emma wired money to David because  0.672695  0.327305
8     The princess wired money to the prince because  0.501296  0.498704
9                Sarah wired money to Robert because  0.609974  0.390026
10  Mrs. Williams wired money to  Mr. Taylor because  0.554432  0.445568
11                 Emily wired money to Paul because  0.554659  0.445341

In [258]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_14f,'he'))

P('subj-pron'|subj=female) =  0.5526005203525225
P('non-subj-pron'|subj=female) =  0.4473994771639506

In [259]:
c1_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_connective1_14f,'she')
c1_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_connective1_14f,'he')

#### male subject

In [260]:
transofposs_perfective_connective1_14m

                                           stimulus        he       she
12      Mr. Smith wired money to Miss Smith because  0.527682  0.472318
13         The man wired money to the woman because  0.548108  0.451892
14                 John wired money to Mary because  0.550469  0.449531
15                 Bob wired money to Alice because  0.211194  0.788806
16     The actor wired money to the actress because  0.253392  0.746607
17          The boy wired money to the girl because  0.536788  0.463212
18  Mr. William wired money to  Mrs. Taylor because  0.274454  0.725546
19                David wired money to Emma because  0.412133  0.587867
20   The prince wired money to the princess because  0.598861  0.401139
21              Robert wired money to Sarah because  0.143966  0.856034
22  Mr. Taylor wired money to Mrs. Williams because  0.197070  0.802930
23                Paul wired money to Emily because  0.314755  0.685245

In [261]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_14m,'she'))

P('subj-pron'|subj=male) =  0.3807392989595731
P('non-subj-pron'|subj=male) =  0.6192606960733732

In [262]:
c1_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_connective1_14m,'he')
c1_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_connective1_14m,'she')

### verb: "carried"

In [263]:
transofposs_perfective_connective1_15 = pd.read_csv("../results/transofposs_perfective/connective1/15.csv")
transofposs_perfective_connective1_15.head()

                                          stimulus        he       she
0   Miss Smith carried a tray to Mr. Smith because  0.199924  0.800076
1      The woman carried a tray to the man because  0.373576  0.626424
2              Mary carried a tray to John because  0.173136  0.826864
3              Alice carried a tray to Bob because  0.144738  0.855262
4  The actress carried a tray to the actor because  0.145341  0.854659

In [264]:
# female subject
transofposs_perfective_connective1_15f = transofposs_perfective_connective1_15[0:12]
transofposs_perfective_connective1_15f = transofposs_perfective_connective1_15f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_15m = transofposs_perfective_connective1_15[12:24]

#### female subject

In [265]:
transofposs_perfective_connective1_15f

                                             stimulus       she        he
0      Miss Smith carried a tray to Mr. Smith because  0.800076  0.199924
1         The woman carried a tray to the man because  0.626424  0.373576
2                 Mary carried a tray to John because  0.826864  0.173136
3                 Alice carried a tray to Bob because  0.855262  0.144738
4     The actress carried a tray to the actor because  0.854659  0.145341
5          The girl carried a tray to the boy because  0.802178  0.197822
6   Mrs. Taylor carried a tray to Mr. Williams bec...  0.721610  0.278390
7                Emma carried a tray to David because  0.930759  0.069241
8   The princess carried a tray to the prince because  0.702234  0.297766
9              Sarah carried a tray to Robert because  0.843478  0.156522
10  Mrs. Williams carried a tray to  Mr. Taylor be...  0.658791  0.341209
11               Emily carried a tray to Paul because  0.736488  0.263512

In [266]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_15f,'he'))

P('subj-pron'|subj=female) =  0.779901996254921
P('non-subj-pron'|subj=female) =  0.22009801119565964

In [267]:
c1_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_connective1_15f,'she')
c1_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_connective1_15f,'he')

#### male subject

In [268]:
transofposs_perfective_connective1_15m

                                             stimulus        he       she
12     Mr. Smith carried a tray to Miss Smith because  0.589672  0.410328
13        The man carried a tray to the woman because  0.525127  0.474873
14                John carried a tray to Mary because  0.654248  0.345752
15                Bob carried a tray to Alice because  0.386317  0.613683
16    The actor carried a tray to the actress because  0.279399  0.720601
17         The boy carried a tray to the girl because  0.522840  0.477160
18  Mr. William carried a tray to  Mrs. Taylor bec...  0.236186  0.763814
19               David carried a tray to Emma because  0.362863  0.637137
20  The prince carried a tray to the princess because  0.601591  0.398409
21             Robert carried a tray to Sarah because  0.238016  0.761984
22  Mr. Taylor carried a tray to Mrs. Williams bec...  0.182180  0.817820
23               Paul carried a tray to Emily because  0.370930  0.629070

In [269]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_15m,'she'))

P('subj-pron'|subj=male) =  0.41244736686348915
P('non-subj-pron'|subj=male) =  0.5875526244441668

In [270]:
c1_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_connective1_15m,'he')
c1_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_connective1_15m,'she')

### verb: "delivered"

In [271]:
transofposs_perfective_connective1_16 = pd.read_csv("../results/transofposs_perfective/connective1/16.csv")
transofposs_perfective_connective1_16.head()

                                            stimulus        he       she
0  Miss Smith delivered a subpoena to Mr. Smith b...  0.247511  0.752489
1  The woman delivered a subpoena to the man because  0.537902  0.462098
2          Mary delivered a subpoena to John because  0.298065  0.701935
3          Alice delivered a subpoena to Bob because  0.482563  0.517437
4  The actress delivered a subpoena to the actor ...  0.429616  0.570384

In [272]:
# female subject
transofposs_perfective_connective1_16f = transofposs_perfective_connective1_16[0:12]
transofposs_perfective_connective1_16f = transofposs_perfective_connective1_16f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_16m = transofposs_perfective_connective1_16[12:24]

#### female subject

In [273]:
transofposs_perfective_connective1_16f

                                             stimulus       she        he
0   Miss Smith delivered a subpoena to Mr. Smith b...  0.752489  0.247511
1   The woman delivered a subpoena to the man because  0.462098  0.537902
2           Mary delivered a subpoena to John because  0.701935  0.298065
3           Alice delivered a subpoena to Bob because  0.517437  0.482563
4   The actress delivered a subpoena to the actor ...  0.570384  0.429616
5    The girl delivered a subpoena to the boy because  0.498783  0.501217
6   Mrs. Taylor delivered a subpoena to Mr. Willia...  0.721513  0.278487
7          Emma delivered a subpoena to David because  0.707696  0.292304
8   The princess delivered a subpoena to the princ...  0.474075  0.525925
9        Sarah delivered a subpoena to Robert because  0.636937  0.363063
10  Mrs. Williams delivered a subpoena to Mr. Tayl...  0.653823  0.346177
11         Emily delivered a subpoena to Paul because  0.575769  0.424231

In [274]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_16f,'he'))

P('subj-pron'|subj=female) =  0.6060781727234522
P('non-subj-pron'|subj=female) =  0.3939218334853649

In [275]:
c1_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16f,'she')
c1_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16f,'he')

#### male subject

In [276]:
transofposs_perfective_connective1_16m

                                             stimulus        he       she
12  Mr. Smith delivered a subpoena to Miss Smith b...  0.503393  0.496607
13  The man delivered a subpoena to the woman because  0.379656  0.620344
14          John delivered a subpoena to Mary because  0.412396  0.587604
15          Bob delivered a subpoena to Alice because  0.183241  0.816759
16  The actor delivered a subpoena to the actress ...  0.173326  0.826674
17   The boy delivered a subpoena to the girl because  0.328063  0.671937
18  Mr. William delivered a subpoena to Mrs. Taylo...  0.176833  0.823167
19         David delivered a subpoena to Emma because  0.394352  0.605648
20  The prince delivered a subpoena to the princes...  0.529596  0.470404
21       Robert delivered a subpoena to Sarah because  0.171949  0.828052
22  Mr. Taylor delivered a subpoena to Mrs. Willia...  0.156276  0.843724
23         Paul delivered a subpoena to Emily because  0.287484  0.712516

In [277]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_16m,'she'))

P('subj-pron'|subj=male) =  0.3080470661322276
P('non-subj-pron'|subj=male) =  0.6919529164830843

In [278]:
c1_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16m,'he')
c1_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16m,'she')

### verb: "gave"

In [279]:
transofposs_perfective_connective1_17 = pd.read_csv("../results/transofposs_perfective/connective1/17.csv")
transofposs_perfective_connective1_17.head()

                                          stimulus        he       she
0   Miss Smith gave a sweater to Mr. Smith because  0.225942  0.774058
1      The woman gave a sweater to the man because  0.513157  0.486843
2              Mary gave a sweater to John because  0.284716  0.715284
3              Alice gave a sweater to Bob because  0.423494  0.576506
4  The actress gave a sweater to the actor because  0.111340  0.888660

In [280]:
# female subject
transofposs_perfective_connective1_17f = transofposs_perfective_connective1_17[0:12]
transofposs_perfective_connective1_17f = transofposs_perfective_connective1_17f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_17m = transofposs_perfective_connective1_17[12:24]

#### female subject

In [281]:
transofposs_perfective_connective1_17f

                                             stimulus       she        he
0      Miss Smith gave a sweater to Mr. Smith because  0.774058  0.225942
1         The woman gave a sweater to the man because  0.486843  0.513157
2                 Mary gave a sweater to John because  0.715284  0.284716
3                 Alice gave a sweater to Bob because  0.576506  0.423494
4     The actress gave a sweater to the actor because  0.888660  0.111340
5          The girl gave a sweater to the boy because  0.616246  0.383754
6   Mrs. Taylor gave a sweater to Mr. Williams bec...  0.676337  0.323663
7                Emma gave a sweater to David because  0.805483  0.194517
8   The princess gave a sweater to the prince because  0.570068  0.429932
9              Sarah gave a sweater to Robert because  0.709721  0.290279
10  Mrs. Williams gave a sweater to  Mr. Taylor be...  0.638956  0.361044
11               Emily gave a sweater to Paul because  0.701868  0.298132

In [282]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_17f,'he'))

P('subj-pron'|subj=female) =  0.6800025155146917
P('non-subj-pron'|subj=female) =  0.3199974888314803

In [283]:
c1_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_connective1_17f,'she')
c1_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_connective1_17f,'he')

#### male subject

In [284]:
transofposs_perfective_connective1_17m

                                             stimulus        he       she
12     Mr. Smith gave a sweater to Miss Smith because  0.601522  0.398478
13        The man gave a sweater to the woman because  0.517013  0.482987
14                John gave a sweater to Mary because  0.612349  0.387651
15                Bob gave a sweater to Alice because  0.362181  0.637819
16    The actor gave a sweater to the actress because  0.555040  0.444960
17         The boy gave a sweater to the girl because  0.570746  0.429254
18  Mr. William gave a sweater to  Mrs. Taylor bec...  0.279316  0.720684
19               David gave a sweater to Emma because  0.514870  0.485130
20  The prince gave a sweater to the princess because  0.671028  0.328972
21             Robert gave a sweater to Sarah because  0.441397  0.558603
22  Mr. Taylor gave a sweater to Mrs. Williams bec...  0.213658  0.786342
23               Paul gave a sweater to Emily because  0.422825  0.577175

In [285]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_17m,'she'))

P('subj-pron'|subj=male) =  0.4801619425415993
P('non-subj-pron'|subj=male) =  0.5198380500078201

In [286]:
c1_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_connective1_17m,'he')
c1_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_connective1_17m,'she')

### verb: "handed"

In [287]:
transofposs_perfective_connective1_18 = pd.read_csv("../results/transofposs_perfective/connective1/18.csv")
transofposs_perfective_connective1_18.head()

                                         stimulus        he       she
0   Miss Smith handed a book to Mr. Smith because  0.221519  0.778481
1      The woman handed a book to the man because  0.503231  0.496769
2              Mary handed a book to John because  0.317259  0.682741
3              Alice handed a book to Bob because  0.434511  0.565489
4  The actress handed a book to the actor because  0.296611  0.703389

In [288]:
# female subject
transofposs_perfective_connective1_18f = transofposs_perfective_connective1_18[0:12]
transofposs_perfective_connective1_18f = transofposs_perfective_connective1_18f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_18m = transofposs_perfective_connective1_18[12:24]

#### female subject

In [289]:
transofposs_perfective_connective1_18f

                                             stimulus       she        he
0       Miss Smith handed a book to Mr. Smith because  0.778481  0.221519
1          The woman handed a book to the man because  0.496769  0.503231
2                  Mary handed a book to John because  0.682741  0.317259
3                  Alice handed a book to Bob because  0.565489  0.434511
4      The actress handed a book to the actor because  0.703389  0.296611
5           The girl handed a book to the boy because  0.507681  0.492319
6   Mrs. Taylor handed a book to Mr. Williams because  0.705022  0.294978
7                 Emma handed a book to David because  0.765661  0.234339
8    The princess handed a book to the prince because  0.478955  0.521045
9               Sarah handed a book to Robert because  0.626627  0.373373
10  Mrs. Williams handed a book to Mr. Taylor because  0.654007  0.345993
11                Emily handed a book to Paul because  0.623868  0.376132

In [290]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_18f,'he'))

P('subj-pron'|subj=female) =  0.6323908269405365
P('non-subj-pron'|subj=female) =  0.3676091854770978

In [291]:
c1_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_connective1_18f,'she')
c1_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_connective1_18f,'he')

#### male subject

In [292]:
transofposs_perfective_connective1_18m

                                             stimulus        he       she
12      Mr. Smith handed a book to Miss Smith because  0.510649  0.489351
13         The man handed a book to the woman because  0.411555  0.588445
14                 John handed a book to Mary because  0.411084  0.588916
15                 Bob handed a book to Alice because  0.262652  0.737348
16     The actor handed a book to the actress because  0.287527  0.712473
17          The boy handed a book to the girl because  0.419652  0.580348
18   Mr. William handed a book to Mrs. Taylor because  0.198081  0.801919
19                David handed a book to Emma because  0.409656  0.590344
20   The prince handed a book to the princess because  0.506925  0.493075
21              Robert handed a book to Sarah because  0.239232  0.760768
22  Mr. Taylor handed a book to Mrs. Williams because  0.167787  0.832213
23                Paul handed a book to Emily because  0.376935  0.623065

In [293]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_18m,'she'))

P('subj-pron'|subj=male) =  0.3501446122924487
P('non-subj-pron'|subj=male) =  0.649855392674605

In [294]:
c1_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_connective1_18m,'he')
c1_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_connective1_18m,'she')

### verb: "passed"

In [295]:
transofposs_perfective_connective1_19 = pd.read_csv("../results/transofposs_perfective/connective1/19.csv")
transofposs_perfective_connective1_19.head()

                                            stimulus        he       she
0  Miss Smith passed a sandwich to Mr. Smith because  0.231870  0.768130
1     The woman passed a sandwich to the man because  0.463658  0.536342
2             Mary passed a sandwich to John because  0.343408  0.656592
3             Alice passed a sandwich to Bob because  0.478458  0.521542
4  The actress passed a sandwich to the actor bec...  0.278904  0.721096

In [296]:
# female subject
transofposs_perfective_connective1_19f = transofposs_perfective_connective1_19[0:12]
transofposs_perfective_connective1_19f = transofposs_perfective_connective1_19f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_19m = transofposs_perfective_connective1_19[12:24]

#### female subject

In [297]:
transofposs_perfective_connective1_19f

                                             stimulus       she        he
0   Miss Smith passed a sandwich to Mr. Smith because  0.768130  0.231870
1      The woman passed a sandwich to the man because  0.536342  0.463658
2              Mary passed a sandwich to John because  0.656592  0.343408
3              Alice passed a sandwich to Bob because  0.521542  0.478458
4   The actress passed a sandwich to the actor bec...  0.721096  0.278904
5       The girl passed a sandwich to the boy because  0.603244  0.396756
6   Mrs. Taylor passed a sandwich to Mr. Williams ...  0.624038  0.375962
7             Emma passed a sandwich to David because  0.729884  0.270116
8   The princess passed a sandwich to the prince b...  0.551037  0.448963
9           Sarah passed a sandwich to Robert because  0.664666  0.335334
10  Mrs. Williams passed a sandwich to  Mr. Taylor...  0.552414  0.447586
11            Emily passed a sandwich to Paul because  0.597256  0.402744

In [298]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_19f,'he'))

P('subj-pron'|subj=female) =  0.6271865566571554
P('non-subj-pron'|subj=female) =  0.3728134520351887

In [299]:
c1_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_connective1_19f,'she')
c1_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_connective1_19f,'he')

#### male subject

In [300]:
transofposs_perfective_connective1_19m

                                             stimulus        he       she
12  Mr. Smith passed a sandwich to Miss Smith because  0.625291  0.374709
13     The man passed a sandwich to the woman because  0.549274  0.450726
14             John passed a sandwich to Mary because  0.583600  0.416400
15             Bob passed a sandwich to Alice because  0.321738  0.678262
16  The actor passed a sandwich to the actress bec...  0.429665  0.570335
17      The boy passed a sandwich to the girl because  0.530558  0.469442
18  Mr. William passed a sandwich to  Mrs. Taylor ...  0.307857  0.692143
19            David passed a sandwich to Emma because  0.582204  0.417796
20  The prince passed a sandwich to the princess b...  0.718875  0.281125
21          Robert passed a sandwich to Sarah because  0.339474  0.660526
22  Mr. Taylor passed a sandwich to Mrs. Williams ...  0.207766  0.792234
23            Paul passed a sandwich to Emily because  0.401824  0.598176

In [301]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_19m,'she'))

P('subj-pron'|subj=male) =  0.46651046847303707
P('non-subj-pron'|subj=male) =  0.5334895228346189

In [302]:
c1_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_connective1_19m,'he')
c1_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_connective1_19m,'she')

### verb: "served"

In [303]:
transofposs_perfective_connective1_20 = pd.read_csv("../results/transofposs_perfective/connective1/20.csv")
transofposs_perfective_connective1_20.head()

                                          stimulus        he       she
0   Miss Smith served a chili to Mr. Smith because  0.122180  0.877820
1      The woman served a chili to the man because  0.391486  0.608514
2              Mary served a chili to John because  0.084395  0.915605
3              Alice served a chili to Bob because  0.097701  0.902299
4  The actress served a chili to the actor because  0.121723  0.878277

In [304]:
# female subject
transofposs_perfective_connective1_20f = transofposs_perfective_connective1_20[0:12]
transofposs_perfective_connective1_20f = transofposs_perfective_connective1_20f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_20m = transofposs_perfective_connective1_20[12:24]

#### female subject

In [305]:
transofposs_perfective_connective1_20f

                                             stimulus       she        he
0      Miss Smith served a chili to Mr. Smith because  0.877820  0.122180
1         The woman served a chili to the man because  0.608514  0.391486
2                 Mary served a chili to John because  0.915605  0.084395
3                 Alice served a chili to Bob because  0.902299  0.097701
4     The actress served a chili to the actor because  0.878277  0.121723
5          The girl served a chili to the boy because  0.786302  0.213698
6   Mrs. Taylor served a chili to Mr. Williams bec...  0.818827  0.181173
7                Emma served a chili to David because  0.903205  0.096795
8   The princess served a chili to the prince because  0.741560  0.258440
9              Sarah served a chili to Robert because  0.906037  0.093963
10  Mrs. Williams served a chili to Mr. Taylor bec...  0.817389  0.182611
11               Emily served a chili to Paul because  0.818409  0.181591

In [306]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_20f,'he'))

P('subj-pron'|subj=female) =  0.8311869700749716
P('non-subj-pron'|subj=female) =  0.16881303923825422

In [307]:
c1_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_connective1_20f,'she')
c1_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_connective1_20f,'he')

#### male subject

In [308]:
transofposs_perfective_connective1_20m

                                             stimulus        he       she
12     Mr. Smith served a chili to Miss Smith because  0.806423  0.193577
13        The man served a chili to the woman because  0.582059  0.417941
14                John served a chili to Mary because  0.709425  0.290575
15                Bob served a chili to Alice because  0.656235  0.343765
16    The actor served a chili to the actress because  0.621813  0.378187
17         The boy served a chili to the girl because  0.692134  0.307866
18  Mr. William served a chili to  Mrs. Taylor bec...  0.485199  0.514801
19               David served a chili to Emma because  0.717709  0.282291
20  The prince served a chili to the princess because  0.859932  0.140068
21             Robert served a chili to Sarah because  0.616015  0.383985
22  Mr. Taylor served a chili to Mrs. Williams bec...  0.406525  0.593475
23               Paul served a chili to Emily because  0.556563  0.443437

In [309]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_20m,'she'))

P('subj-pron'|subj=male) =  0.6425027673443159
P('non-subj-pron'|subj=male) =  0.3574972425897916

In [310]:
c1_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_connective1_20m,'he')
c1_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_connective1_20m,'she')

## Summary of Results

In [311]:
c1_results_fsubj_subjpron = pd.DataFrame(list(c1_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c1_results_fsubj_objpron = pd.DataFrame(list(c1_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c1_results_fsubj = results_fsubj_subjpron.merge(results_fsubj_objpron)
c1_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0         flung              0.233454             0.766546
1        kicked              0.268228             0.731772
2        lobbed              0.321265             0.678735
3         threw              0.287436             0.712564
4        tossed              0.282861             0.717138
5       brought              0.371279             0.628721
6     forwarded              0.260857             0.739143
7        mailed              0.309548             0.690452
8       shipped              0.281612             0.718388
9   transmitted              0.306047             0.693953
10        wired              0.288364             0.711636
11      carried              0.288790             0.711210
12    delivered              0.284028             0.715972
13         gave              0.364746             0.635254
14       handed              0.312001             0.687999
15       passed              0.289066             0.710934
16       served              0.363607             0.636393

In [312]:
c1_results_msubj_subjpron = pd.DataFrame(list(c1_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c1_results_msubj_objpron = pd.DataFrame(list(c1_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c1_results_msubj = results_msubj_subjpron.merge(c1_results_msubj_objpron)
c1_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0         flung            0.739469           0.627692
1        kicked            0.809898           0.658924
2        lobbed            0.701354           0.713549
3        rolled            0.817856           0.540076
4         threw            0.748003           0.579279
5        tossed            0.736068           0.702311
6       brought            0.754779           0.612456
7     forwarded            0.698221           0.575211
8        mailed            0.698865           0.475129
9       shipped            0.690351           0.722538
10  transmitted            0.663190           0.544228
11        wired            0.678203           0.619261
12      carried            0.757375           0.587553
13    delivered            0.675688           0.691953
14         gave            0.680943           0.519838
15       handed            0.604445           0.649855
16       passed            0.731956           0.533490
17       served            0.801360           0.357497

In [313]:
c1_results = c1_results_fsubj.merge(c1_results_msubj)
c1_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flung,0.233454,0.766546,0.739469,0.627692
1,kicked,0.268228,0.731772,0.809898,0.658924
2,lobbed,0.321265,0.678735,0.701354,0.713549
3,threw,0.287436,0.712564,0.748003,0.579279
4,tossed,0.282861,0.717138,0.736068,0.702311
5,brought,0.371279,0.628721,0.754779,0.612456
6,forwarded,0.260857,0.739143,0.698221,0.575211
7,mailed,0.309548,0.690452,0.698865,0.475129
8,shipped,0.281612,0.718388,0.690351,0.722538
9,transmitted,0.306047,0.693953,0.663190,0.544228
10,wired,0.288364,0.711636,0.678203,0.619261
11,carried,0.288790,0.711210,0.757375,0.587553
12,delivered,0.284028,0.715972,0.675688,0.691953
13,gave,0.364746,0.635254,0.680943,0.519838
14,handed,0.312001,0.687999,0.604445,0.649855
15,passed,0.289066,0.710934,0.731956,0.533490
16,served,0.363607,0.636393,0.801360,0.357497

In [314]:
print("P(subj_reference |subj=female)", compute_average(c1_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c1_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.3007759098328796
P(obj_reference |subj=female) 0.6992240874644589

In [315]:
print("P(subj_reference |subj=male)", compute_average(c1_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c1_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.7158922052659168
P(obj_reference |subj=male) 0.5982801561408184

## Connective: "and, as a result"

In [316]:
c2_average_subj_female_subj_pron = {}
c2_average_subj_female_obj_pron = {}
c2_average_subj_male_subj_pron = {}
c2_average_subj_male_obj_pron = {}

### verb: "chucked"

In [317]:
transofposs_perfective_connective2_1 = pd.read_csv("../results/transofposs_perfective/connective2/1.csv")
transofposs_perfective_connective2_1.head()

                                            stimulus        he       she
0  Miss Smith chucked a wrench to Mr. Smith and, ...  0.241620  0.758380
1  The woman chucked a wrench to the man and, as ...  0.489733  0.510267
2    Mary chucked a wrench to John and, as a result,  0.211756  0.788244
3    Alice chucked a wrench to Bob and, as a result,  0.404159  0.595841
4  The actress chucked a wrench to the actor and,...  0.683269  0.316731

In [318]:
# female subject
transofposs_perfective_connective2_1f = transofposs_perfective_connective2_1[0:12]
transofposs_perfective_connective2_1f = transofposs_perfective_connective2_1f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_1m = transofposs_perfective_connective2_1[12:24]

#### female subject

In [319]:
transofposs_perfective_connective2_1f

                                             stimulus       she        he
0   Miss Smith chucked a wrench to Mr. Smith and, ...  0.758380  0.241620
1   The woman chucked a wrench to the man and, as ...  0.510267  0.489733
2     Mary chucked a wrench to John and, as a result,  0.788244  0.211756
3     Alice chucked a wrench to Bob and, as a result,  0.595841  0.404159
4   The actress chucked a wrench to the actor and,...  0.316731  0.683269
5   The girl chucked a wrench to the boy and, as a...  0.527912  0.472088
6   Mrs. Taylor chucked a wrench to Mr. Williams a...  0.811627  0.188373
7    Emma chucked a wrench to David and, as a result,  0.660302  0.339698
8   The princess chucked a wrench to the prince an...  0.745503  0.254497
9   Sarah chucked a wrench to Robert and, as a res...  0.465285  0.534715
10  Mrs. Williams chucked a wrench to Mr. Taylor a...  0.779397  0.220603
11   Emily chucked a wrench to Paul and, as a result,  0.677053  0.322947

In [320]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_1f,'he'))

P('subj-pron'|subj=female) =  0.6363786260286967
P('non-subj-pron'|subj=female) =  0.3636214037736257

In [321]:
c2_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1f,'she')
c2_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1f,'he')

#### male subject

In [322]:
transofposs_perfective_connective2_1m

                                             stimulus        he       she
12  Mr. Smith chucked a wrench to Miss Smith and, ...  0.759000  0.241000
13  The man chucked a wrench to the woman and, as ...  0.837342  0.162658
14    John chucked a wrench to Mary and, as a result,  0.571167  0.428833
15    Bob chucked a wrench to Alice and, as a result,  0.859575  0.140425
16  The actor chucked a wrench to the actress and,...  0.935672  0.064328
17  The boy chucked a wrench to the girl and, as a...  0.898689  0.101311
18  Mr. William chucked a wrench to Mrs. Taylor an...  0.646919  0.353081
19   David chucked a wrench to Emma and, as a result,  0.636888  0.363112
20  The prince chucked a wrench to the princess an...  0.669728  0.330272
21  Robert chucked a wrench to Sarah and, as a res...  0.822018  0.177982
22  Mr. Taylor chucked a wrench to Mrs. Williams a...  0.543437  0.456563
23   Paul chucked a wrench to Emily and, as a result,  0.633505  0.366495

In [323]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_1m,'she'))

P('subj-pron'|subj=male) =  0.7344949891169866
P('non-subj-pron'|subj=male) =  0.2655050090203683

In [324]:
c2_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1m,'he')
c2_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1m,'she')

### verb: "flung"

In [325]:
transofposs_perfective_connective2_2 = pd.read_csv("../results/transofposs_perfective/connective2/2.csv")
transofposs_perfective_connective2_2.head()

                                            stimulus        he       she
0  Miss Smith flung a frisbee to Mr. Smith and, a...  0.385662  0.614338
1  The woman flung a frisbee to the man and, as a...  0.680153  0.319848
2     Mary flung a frisbee to John and, as a result,  0.438427  0.561573
3     Alice flung a frisbee to Bob and, as a result,  0.665419  0.334581
4  The actress flung a frisbee to the actor and, ...  0.811032  0.188968

In [326]:
# female subject
transofposs_perfective_connective2_2f = transofposs_perfective_connective2_2[0:12]
transofposs_perfective_connective2_2f = transofposs_perfective_connective2_2f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_2m = transofposs_perfective_connective2_2[12:24]

#### female subject

In [327]:
transofposs_perfective_connective2_2f

                                             stimulus       she        he
0   Miss Smith flung a frisbee to Mr. Smith and, a...  0.614338  0.385662
1   The woman flung a frisbee to the man and, as a...  0.319848  0.680153
2      Mary flung a frisbee to John and, as a result,  0.561573  0.438427
3      Alice flung a frisbee to Bob and, as a result,  0.334581  0.665419
4   The actress flung a frisbee to the actor and, ...  0.188968  0.811032
5   The girl flung a frisbee to the boy and, as a ...  0.211351  0.788648
6   Mrs. Taylor flung a frisbee to Mr. Williams an...  0.556435  0.443565
7     Emma flung a frisbee to David and, as a result,  0.482834  0.517166
8   The princess flung a frisbee to the prince and...  0.348108  0.651892
9   Sarah flung a frisbee to Robert and, as a result,  0.374462  0.625538
10  Mrs. Williams flung a frisbee to  Mr. Taylor a...  0.545043  0.454957
11    Emily flung a frisbee to Paul and, as a result,  0.573022  0.426978

In [328]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_2f,'he'))

P('subj-pron'|subj=female) =  0.42588022475441295
P('non-subj-pron'|subj=female) =  0.5741197864214579

In [329]:
c2_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_connective2_2f,'she')
c2_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_connective2_2f,'he')

#### male subject

In [330]:
transofposs_perfective_connective2_2m

                                             stimulus        he       she
12  Mr. Smith flung a frisbee to Miss Smith and, a...  0.383922  0.616078
13  The man flung a frisbee to the woman and, as a...  0.528529  0.471471
14     John flung a frisbee to Mary and, as a result,  0.264051  0.735949
15     Bob flung a frisbee to Alice and, as a result,  0.670430  0.329569
16  The actor flung a frisbee to the actress and, ...  0.713485  0.286515
17  The boy flung a frisbee to the girl and, as a ...  0.648859  0.351141
18  Mr. William flung a frisbee to  Mrs. Taylor an...  0.185451  0.814550
19    David flung a frisbee to Emma and, as a result,  0.256901  0.743099
20  The prince flung a frisbee to the princess and...  0.280431  0.719569
21  Robert flung a frisbee to Sarah and, as a result,  0.322554  0.677446
22  Mr. Taylor flung a frisbee to Mrs. Williams an...  0.185361  0.814640
23    Paul flung a frisbee to Emily and, as a result,  0.352918  0.647082

In [331]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_2m,'she'))

P('subj-pron'|subj=male) =  0.3994076835612456
P('non-subj-pron'|subj=male) =  0.6005923201640447

In [332]:
c2_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_connective2_2m,'he')
c2_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_connective2_2m,'she')

### verb: "kicked"

In [333]:
transofposs_perfective_connective2_3 = pd.read_csv("../results/transofposs_perfective/connective2/3.csv")
transofposs_perfective_connective2_3.head()

                                            stimulus        he       she
0  Miss Smith kicked a soccer ball to Mr. Smith a...  0.392599  0.607401
1  The woman kicked a soccer ball to the man and,...  0.756467  0.243533
2  Mary kicked a soccer ball to John and, as a re...  0.452935  0.547065
3  Alice kicked a soccer ball to Bob and, as a re...  0.788258  0.211742
4  The actress kicked a soccer ball to the actor ...  0.794265  0.205735

In [334]:
# female subject
transofposs_perfective_connective2_3f = transofposs_perfective_connective2_3[0:12]
transofposs_perfective_connective2_3f = transofposs_perfective_connective2_3f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_3m = transofposs_perfective_connective2_3[12:24]

#### female subject

In [335]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_3f,'he'))

P('subj-pron'|subj=female) =  0.39683478822310764
P('non-subj-pron'|subj=female) =  0.6031652043263117

In [336]:
c2_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3f,'she')
c2_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3f,'he')

#### male subject

In [337]:
transofposs_perfective_connective2_3m

                                             stimulus        he       she
12  Mr. Smith kicked a soccer ball to Miss Smith a...  0.760759  0.239241
13  The man kicked a soccer ball to the woman and,...  0.809272  0.190728
14  John kicked a soccer ball to Mary and, as a re...  0.464169  0.535831
15  Bob kicked a soccer ball to Alice and, as a re...  0.920842  0.079158
16  The actor kicked a soccer ball to the actress ...  0.881102  0.118898
17  The boy kicked a soccer ball to the girl and, ...  0.888033  0.111967
18  Mr. William kicked a soccer ball to  Mrs. Tayl...  0.420439  0.579561
19  David kicked a soccer ball to Emma and, as a r...  0.636296  0.363704
20  The prince kicked a soccer ball to the princes...  0.540452  0.459548
21  Robert kicked a soccer ball to Sarah and, as a...  0.799286  0.200714
22  Mr. Taylor kicked a soccer ball to Mrs. Willia...  0.458557  0.541443
23  Paul kicked a soccer ball to Emily and, as a r...  0.719955  0.280045

In [338]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_3m,'she'))

P('subj-pron'|subj=male) =  0.6915967663129171
P('non-subj-pron'|subj=male) =  0.3084032256156206

In [339]:
c2_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3m,'he')
c2_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3m,'she')

### verb: "lobbed"

In [340]:
transofposs_perfective_connective2_4 = pd.read_csv("../results/transofposs_perfective/connective2/4.csv")
transofposs_perfective_connective2_4.head()

                                            stimulus        he       she
0  Miss Smith lobbed a football to Mr. Smith and,...  0.400064  0.599936
1  The woman lobbed a football to the man and, as...  0.649133  0.350867
2   Mary lobbed a football to John and, as a result,  0.453264  0.546736
3   Alice lobbed a football to Bob and, as a result,  0.741098  0.258902
4  The actress lobbed a football to the actor and...  0.784242  0.215758

In [341]:
# female subject
transofposs_perfective_connective2_4f = transofposs_perfective_connective2_4[0:12]
transofposs_perfective_connective2_4f = transofposs_perfective_connective2_4f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_4m = transofposs_perfective_connective2_4[12:24]

#### female subject

In [342]:
transofposs_perfective_connective2_4f

                                             stimulus       she        he
0   Miss Smith lobbed a football to Mr. Smith and,...  0.599936  0.400064
1   The woman lobbed a football to the man and, as...  0.350867  0.649133
2    Mary lobbed a football to John and, as a result,  0.546736  0.453264
3    Alice lobbed a football to Bob and, as a result,  0.258902  0.741098
4   The actress lobbed a football to the actor and...  0.215758  0.784242
5   The girl lobbed a football to the boy and, as ...  0.215213  0.784787
6   Mrs. Taylor lobbed a football to Mr. Williams ...  0.521814  0.478186
7   Emma lobbed a football to David and, as a result,  0.488498  0.511502
8   The princess lobbed a football to the prince a...  0.346822  0.653178
9   Sarah lobbed a football to Robert and, as a re...  0.320370  0.679630
10  Mrs. Williams lobbed a football to  Mr. Taylor...  0.520322  0.479678
11  Emily lobbed a football to Paul and, as a result,  0.573669  0.426331

In [343]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_4f,'he'))

P('subj-pron'|subj=female) =  0.4132421985268593
P('non-subj-pron'|subj=female) =  0.5867578039566675

In [344]:
c2_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4f,'she')
c2_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4f,'he')

#### male subject

In [345]:
transofposs_perfective_connective1_4m

                                             stimulus        he       she
12  Mr. Smith lobbed a football to Miss Smith because  0.513713  0.486287
13     The man lobbed a football to the woman because  0.356285  0.643715
14             John lobbed a football to Mary because  0.345697  0.654303
15             Bob lobbed a football to Alice because  0.230117  0.769883
16  The actor lobbed a football to the actress bec...  0.204185  0.795815
17      The boy lobbed a football to the girl because  0.376035  0.623965
18  Mr. William lobbed a football to  Mrs. Taylor ...  0.173555  0.826445
19            David lobbed a football to Emma because  0.313695  0.686305
20  The prince lobbed a football to the princess b...  0.388822  0.611178
21          Robert lobbed a football to Sarah because  0.147863  0.852137
22  Mr. Taylor lobbed a football to Mrs. Williams ...  0.127628  0.872372
23            Paul lobbed a football to Emily because  0.259813  0.740187

In [346]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_4m,'she'))

P('subj-pron'|subj=male) =  0.3445676440993945
P('non-subj-pron'|subj=male) =  0.6554323583841324

In [347]:
c2_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4m,'he')
c2_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4m,'she')

### verb: "rolled"

In [348]:
transofposs_perfective_connective2_5 = pd.read_csv("../results/transofposs_perfective/connective2/5.csv")
transofposs_perfective_connective2_5.head()

                                            stimulus        he       she
0  Miss Smith rolled a toy truck to Mr. Smith and...  0.350688  0.649312
1  The woman rolled a toy truck to the man and, a...  0.616002  0.383998
2  Mary rolled a toy truck to John and, as a result,  0.427277  0.572723
3  Alice rolled a toy truck to Bob and, as a result,  0.656119  0.343881
4  The actress rolled a toy truck to the actor an...  0.612813  0.387187

In [349]:
# female subject
transofposs_perfective_connective2_5f = transofposs_perfective_connective2_5[0:12]
transofposs_perfective_connective2_5f = transofposs_perfective_connective2_5[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_5m = transofposs_perfective_connective2_5[12:24]

#### female subject

In [350]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_5f,'he'))

P('subj-pron'|subj=female) =  0.43839760931829613
P('non-subj-pron'|subj=female) =  0.5616024124125639

In [351]:
c2_average_subj_female_subj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5f,'she')
c2_average_subj_female_obj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5f,'he')

#### male subject

In [352]:
transofposs_perfective_connective2_5m

                                             stimulus        he       she
12  Mr. Smith rolled a toy truck to Miss Smith and...  0.663426  0.336574
13  The man rolled a toy truck to the woman and, a...  0.757696  0.242304
14  John rolled a toy truck to Mary and, as a result,  0.475148  0.524853
15  Bob rolled a toy truck to Alice and, as a result,  0.912245  0.087755
16  The actor rolled a toy truck to the actress an...  0.801019  0.198981
17  The boy rolled a toy truck to the girl and, as...  0.849446  0.150554
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.332119  0.667881
19  David rolled a toy truck to Emma and, as a res...  0.431303  0.568697
20  The prince rolled a toy truck to the princess ...  0.599678  0.400322
21  Robert rolled a toy truck to Sarah and, as a r...  0.627169  0.372831
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.346458  0.653542
23  Paul rolled a toy truck to Emily and, as a res...  0.504723  0.495277

In [353]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_5m,'she'))

P('subj-pron'|subj=male) =  0.6083691964546839
P('non-subj-pron'|subj=male) =  0.3916308271388213

In [354]:
c2_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5m,'he')
c2_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5m,'she')

### verb: "threw"

In [355]:
transofposs_perfective_connective2_6 = pd.read_csv("../results/transofposs_perfective/connective2/6.csv")
transofposs_perfective_connective2_6.head()

                                            stimulus        he       she
0  Miss Smith threw a hat to Mr. Smith and, as a ...  0.318014  0.681986
1  The woman threw a hat to the man and, as a res...  0.698072  0.301928
2         Mary threw a hat to John and, as a result,  0.424314  0.575686
3         Alice threw a hat to Bob and, as a result,  0.627900  0.372100
4  The actress threw a hat to the actor and, as a...  0.776145  0.223855

In [356]:
# female subject
transofposs_perfective_connective2_6f = transofposs_perfective_connective2_6[0:12]
transofposs_perfective_connective2_6f = transofposs_perfective_connective2_6[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_6m = transofposs_perfective_connective2_6[12:24]

#### female subject

In [357]:
transofposs_perfective_connective2_6f

                                             stimulus       she        he
0   Miss Smith threw a hat to Mr. Smith and, as a ...  0.681986  0.318014
1   The woman threw a hat to the man and, as a res...  0.301928  0.698072
2          Mary threw a hat to John and, as a result,  0.575686  0.424314
3          Alice threw a hat to Bob and, as a result,  0.372100  0.627900
4   The actress threw a hat to the actor and, as a...  0.223855  0.776145
5   The girl threw a hat to the boy and, as a result,  0.270274  0.729726
6   Mrs. Taylor threw a hat to Mr. Williams and, a...  0.610683  0.389317
7         Emma threw a hat to David and, as a result,  0.558462  0.441538
8   The princess threw a hat to the prince and, as...  0.403499  0.596501
9       Sarah threw a hat to Robert and, as a result,  0.423407  0.576593
10  Mrs. Williams threw a hat to  Mr. Taylor and, ...  0.634183  0.365817
11        Emily threw a hat to Paul and, as a result,  0.525470  0.474530
12  Mr. Smith threw a hat to Miss Smith and, as a ...  0.542410  0.457590
13  The man threw a hat to the woman and, as a res...  0.290682  0.709318
14         John threw a hat to Mary and, as a result,  0.659809  0.340191
15         Bob threw a hat to Alice and, as a result,  0.288799  0.711201
16  The actor threw a hat to the actress and, as a...  0.297943  0.702057
17  The boy threw a hat to the girl and, as a result,  0.201940  0.798060
18  Mr. William threw a hat to  Mrs. Taylor and, a...  0.739063  0.260937
19        David threw a hat to Emma and, as a result,  0.688566  0.311434
20  The prince threw a hat to the princess and, as...  0.582483  0.417517
21      Robert threw a hat to Sarah and, as a result,  0.533135  0.466865
22  Mr. Taylor threw a hat to Mrs. Williams and, a...  0.720045  0.279955
23        Paul threw a hat to Emily and, as a result,  0.510229  0.489771

In [358]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_6f,'he'))

P('subj-pron'|subj=female) =  0.48485985087851685
P('non-subj-pron'|subj=female) =  0.5151401485006014

In [359]:
c2_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_connective2_6f,'she')
c2_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_connective2_6f,'he')

#### male subject

In [360]:
transofposs_perfective_connective2_6m

                                             stimulus        he       she
12  Mr. Smith threw a hat to Miss Smith and, as a ...  0.457590  0.542410
13  The man threw a hat to the woman and, as a res...  0.709318  0.290682
14         John threw a hat to Mary and, as a result,  0.340191  0.659809
15         Bob threw a hat to Alice and, as a result,  0.711201  0.288799
16  The actor threw a hat to the actress and, as a...  0.702057  0.297943
17  The boy threw a hat to the girl and, as a result,  0.798060  0.201940
18  Mr. William threw a hat to  Mrs. Taylor and, a...  0.260937  0.739063
19        David threw a hat to Emma and, as a result,  0.311434  0.688566
20  The prince threw a hat to the princess and, as...  0.417517  0.582483
21      Robert threw a hat to Sarah and, as a result,  0.466865  0.533135
22  Mr. Taylor threw a hat to Mrs. Williams and, a...  0.279955  0.720045
23        Paul threw a hat to Emily and, as a result,  0.489771  0.510229

In [361]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_6m,'she'))

P('subj-pron'|subj=male) =  0.4954081252217293
P('non-subj-pron'|subj=male) =  0.5045918735365073

In [362]:
c2_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_connective2_6m,'he')
c2_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_connective2_6m,'she')

### verb: "tossed"

In [363]:
transofposs_perfective_connective2_7 = pd.read_csv("../results/transofposs_perfective/connective2/7.csv")
transofposs_perfective_connective2_7.head()

                                            stimulus        he       she
0  Miss Smith tossed a dish towel to Mr. Smith an...  0.333324  0.666676
1  The woman tossed a dish towel to the man and, ...  0.690942  0.309058
2  Mary tossed a dish towel to John and, as a res...  0.439713  0.560287
3  Alice tossed a dish towel to Bob and, as a res...  0.596938  0.403062
4  The actress tossed a dish towel to the actor a...  0.763445  0.236555

In [364]:
# female subject
transofposs_perfective_connective2_7f = transofposs_perfective_connective2_7[0:12]
transofposs_perfective_connective2_7f = transofposs_perfective_connective2_7f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_7m = transofposs_perfective_connective2_7[12:24]

#### female subject

In [365]:
transofposs_perfective_connective2_7f

                                             stimulus       she        he
0   Miss Smith tossed a dish towel to Mr. Smith an...  0.666676  0.333324
1   The woman tossed a dish towel to the man and, ...  0.309058  0.690942
2   Mary tossed a dish towel to John and, as a res...  0.560287  0.439713
3   Alice tossed a dish towel to Bob and, as a res...  0.403062  0.596938
4   The actress tossed a dish towel to the actor a...  0.236555  0.763445
5   The girl tossed a dish towel to the boy and, a...  0.236991  0.763009
6   Mrs. Taylor tossed a dish towel to Mr. William...  0.588652  0.411348
7   Emma tossed a dish towel to David and, as a re...  0.542048  0.457952
8   The princess tossed a dish towel to the prince...  0.378687  0.621313
9   Sarah tossed a dish towel to Robert and, as a ...  0.379519  0.620481
10  Mrs. Williams tossed a dish towel to  Mr. Tayl...  0.589311  0.410689
11  Emily tossed a dish towel to Paul and, as a re...  0.530046  0.469954

In [366]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_7f,'he'))

P('subj-pron'|subj=female) =  0.45174092302719754
P('non-subj-pron'|subj=female) =  0.5482590794563293

In [367]:
c2_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7f,'she')
c2_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7f,'he')

#### male subject

In [368]:
transofposs_perfective_connective2_7m

                                             stimulus        he       she
12  Mr. Smith tossed a dish towel to Miss Smith an...  0.405195  0.594805
13  The man tossed a dish towel to the woman and, ...  0.552720  0.447280
14  John tossed a dish towel to Mary and, as a res...  0.288883  0.711117
15  Bob tossed a dish towel to Alice and, as a res...  0.558754  0.441246
16  The actor tossed a dish towel to the actress a...  0.594726  0.405274
17  The boy tossed a dish towel to the girl and, a...  0.580542  0.419458
18  Mr. William tossed a dish towel to  Mrs. Taylo...  0.194731  0.805269
19  David tossed a dish towel to Emma and, as a re...  0.280854  0.719146
20  The prince tossed a dish towel to the princess...  0.292724  0.707276
21  Robert tossed a dish towel to Sarah and, as a ...  0.358095  0.641905
22  Mr. Taylor tossed a dish towel to Mrs. William...  0.208420  0.791580
23  Paul tossed a dish towel to Emily and, as a re...  0.361997  0.638003

In [369]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_7m,'she'))

P('subj-pron'|subj=male) =  0.3898032680153847
P('non-subj-pron'|subj=male) =  0.6101967369516691

In [370]:
c2_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7m,'he')
c2_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7m,'she')

#### verb: "brought"

In [371]:
transofposs_perfective_connective2_8 = pd.read_csv("../results/transofposs_perfective/connective2/8.csv")
transofposs_perfective_connective2_8.head()

                                            stimulus        he       she
0  Miss Smith brought a glass of water to Mr. Smi...  0.317244  0.682756
1  The woman brought a glass of water to the man ...  0.609039  0.390961
2  Mary brought a glass of water to John and, as ...  0.372617  0.627383
3  Alice brought a glass of water to Bob and, as ...  0.446428  0.553572
4  The actress brought a glass of water to the ac...  0.398107  0.601893

In [372]:
# female subject
transofposs_perfective_connective2_8f = transofposs_perfective_connective2_8[0:12]
transofposs_perfective_connective2_8f = transofposs_perfective_connective2_8f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_8m = transofposs_perfective_connective2_8[12:24]

#### female subject

In [373]:
transofposs_perfective_connective2_8f

                                             stimulus       she        he
0   Miss Smith brought a glass of water to Mr. Smi...  0.682756  0.317244
1   The woman brought a glass of water to the man ...  0.390961  0.609039
2   Mary brought a glass of water to John and, as ...  0.627383  0.372617
3   Alice brought a glass of water to Bob and, as ...  0.553572  0.446428
4   The actress brought a glass of water to the ac...  0.601893  0.398107
5   The girl brought a glass of water to the boy a...  0.265052  0.734948
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.631317  0.368683
7   Emma brought a glass of water to David and, as...  0.581942  0.418058
8   The princess brought a glass of water to the p...  0.489801  0.510199
9   Sarah brought a glass of water to Robert and, ...  0.427242  0.572758
10  Mrs. Williams brought a glass of water to  Mr....  0.590138  0.409862
11  Emily brought a glass of water to Paul and, as...  0.598700  0.401300

In [374]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_8f,'he'))

P('subj-pron'|subj=female) =  0.5367297381162643
P('non-subj-pron'|subj=female) =  0.46327027430136997

In [375]:
c2_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_connective2_8f,'she')
c2_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_connective2_8f,'he')

#### male subject

In [376]:
transofposs_perfective_connective2_8m

                                             stimulus        he       she
12  Mr. Smith brought a glass of water to Miss Smi...  0.355997  0.644003
13  The man brought a glass of water to the woman ...  0.449089  0.550911
14  John brought a glass of water to Mary and, as ...  0.241693  0.758307
15  Bob brought a glass of water to Alice and, as ...  0.501803  0.498197
16  The actor brought a glass of water to the actr...  0.502784  0.497216
17  The boy brought a glass of water to the girl a...  0.524185  0.475815
18  Mr. William brought a glass of water to  Mrs. ...  0.241991  0.758009
19  David brought a glass of water to Emma and, as...  0.395136  0.604864
20  The prince brought a glass of water to the pri...  0.247671  0.752329
21  Robert brought a glass of water to Sarah and, ...  0.484929  0.515071
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.260619  0.739381
23  Paul brought a glass of water to Emily and, as...  0.358031  0.641969

In [377]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_8m,'she'))

P('subj-pron'|subj=male) =  0.3803272967537244
P('non-subj-pron'|subj=male) =  0.6196727007627487

In [378]:
c2_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_connective2_8m,'he')
c2_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_connective2_8m,'she')

### verb: "forwarded"

In [379]:
transofposs_perfective_connective2_9 = pd.read_csv("../results/transofposs_perfective/connective2/9.csv")
transofposs_perfective_connective2_9.head()

                                            stimulus        he       she
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.191931  0.808069
1  The woman forwarded a gossipy email to the man...  0.550808  0.449192
2  Mary forwarded a gossipy email to John and, as...  0.354063  0.645937
3  Alice forwarded a gossipy email to Bob and, as...  0.473394  0.526606
4  The actress forwarded a gossipy email to the a...  0.330456  0.669544

In [380]:
# female subject
transofposs_perfective_connective2_9f = transofposs_perfective_connective2_9[0:12]
transofposs_perfective_connective2_9f = transofposs_perfective_connective2_9f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_9m = transofposs_perfective_connective2_9[12:24]

#### female subject

In [381]:
transofposs_perfective_connective2_9f

                                             stimulus       she        he
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.808069  0.191931
1   The woman forwarded a gossipy email to the man...  0.449192  0.550808
2   Mary forwarded a gossipy email to John and, as...  0.645937  0.354063
3   Alice forwarded a gossipy email to Bob and, as...  0.526606  0.473394
4   The actress forwarded a gossipy email to the a...  0.669544  0.330456
5   The girl forwarded a gossipy email to the boy ...  0.408479  0.591521
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.724739  0.275261
7   Emma forwarded a gossipy email to David and, a...  0.756976  0.243024
8   The princess forwarded a gossipy email to the ...  0.458346  0.541654
9   Sarah forwarded a gossipy email to Robert and,...  0.447131  0.552869
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.693483  0.306516
11  Emily forwarded a gossipy email to Paul and, a...  0.692297  0.307703

In [382]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_9f,'he'))

P('subj-pron'|subj=female) =  0.6067333742976189
P('non-subj-pron'|subj=female) =  0.3932666393617789

In [383]:
c2_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9f,'she')
c2_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9f,'he')

#### male subject

In [384]:
transofposs_perfective_connective2_9m

                                             stimulus        he       she
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.284541  0.715459
13  The man forwarded a gossipy email to the woman...  0.449903  0.550097
14  John forwarded a gossipy email to Mary and, as...  0.200167  0.799833
15  Bob forwarded a gossipy email to Alice and, as...  0.415542  0.584458
16  The actor forwarded a gossipy email to the act...  0.356081  0.643919
17  The boy forwarded a gossipy email to the girl ...  0.438701  0.561299
18  Mr. William forwarded a gossipy email to  Mrs....  0.138613  0.861387
19  David forwarded a gossipy email to Emma and, a...  0.236669  0.763331
20  The prince forwarded a gossipy email to the pr...  0.328936  0.671064
21  Robert forwarded a gossipy email to Sarah and,...  0.367437  0.632563
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.151902  0.848098
23  Paul forwarded a gossipy email to Emily and, a...  0.433206  0.566794

In [385]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_9m,'she'))

P('subj-pron'|subj=male) =  0.3168081318338712
P('non-subj-pron'|subj=male) =  0.6831918805837631

In [386]:
c2_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9m,'he')
c2_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9m,'she')

### verb: "mailed"

In [387]:
transofposs_perfective_connective2_10 = pd.read_csv("../results/transofposs_perfective/connective2/10.csv")
transofposs_perfective_connective2_10.head()

                                            stimulus        he       she
0  Miss Smith mailed a letter to Mr. Smith and, a...  0.233188  0.766812
1  The woman mailed a letter to the man and, as a...  0.491690  0.508310
2     Mary mailed a letter to John and, as a result,  0.423385  0.576615
3     Alice mailed a letter to Bob and, as a result,  0.476378  0.523622
4  The actress mailed a letter to the actor and, ...  0.382718  0.617282

In [388]:
# female subject
transofposs_perfective_connective2_10f = transofposs_perfective_connective2_10[0:12]
transofposs_perfective_connective2_10f = transofposs_perfective_connective2_10f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_10m = transofposs_perfective_connective2_10[12:24]

#### female subject

In [389]:
transofposs_perfective_connective2_10f

                                             stimulus       she        he
0   Miss Smith mailed a letter to Mr. Smith and, a...  0.766812  0.233188
1   The woman mailed a letter to the man and, as a...  0.508310  0.491690
2      Mary mailed a letter to John and, as a result,  0.576615  0.423385
3      Alice mailed a letter to Bob and, as a result,  0.523622  0.476378
4   The actress mailed a letter to the actor and, ...  0.617282  0.382718
5   The girl mailed a letter to the boy and, as a ...  0.450837  0.549163
6   Mrs. Taylor mailed a letter to Mr. Williams an...  0.679407  0.320593
7     Emma mailed a letter to David and, as a result,  0.763676  0.236324
8   The princess mailed a letter to the prince and...  0.422419  0.577581
9   Sarah mailed a letter to Robert and, as a result,  0.435996  0.564004
10  Mrs. Williams mailed a letter to  Mr. Taylor a...  0.645594  0.354406
11    Emily mailed a letter to Paul and, as a result,  0.720895  0.279105

In [390]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_10f,'he'))

P('subj-pron'|subj=female) =  0.5926221162080765
P('non-subj-pron'|subj=female) =  0.4073778788248698

In [391]:
c2_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10f,'she')
c2_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10f,'he')

#### male subject

In [392]:
transofposs_perfective_connective2_10m

                                             stimulus        he       she
12  Mr. Smith mailed a letter to Miss Smith and, a...  0.201955  0.798045
13  The man mailed a letter to the woman and, as a...  0.276050  0.723950
14     John mailed a letter to Mary and, as a result,  0.216964  0.783036
15     Bob mailed a letter to Alice and, as a result,  0.357604  0.642396
16  The actor mailed a letter to the actress and, ...  0.215216  0.784784
17  The boy mailed a letter to the girl and, as a ...  0.247844  0.752156
18  Mr. William mailed a letter to  Mrs. Taylor an...  0.109601  0.890399
19    David mailed a letter to Emma and, as a result,  0.201732  0.798268
20  The prince mailed a letter to the princess and...  0.187715  0.812285
21  Robert mailed a letter to Sarah and, as a result,  0.203609  0.796391
22  Mr. Taylor mailed a letter to Mrs. Williams an...  0.097753  0.902247
23    Paul mailed a letter to Emily and, as a result,  0.444776  0.555224

In [393]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_10m,'she'))

P('subj-pron'|subj=male) =  0.2300682496279478
P('non-subj-pron'|subj=male) =  0.769931768377622

In [394]:
c2_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10m,'he')
c2_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10m,'she')

### verb: "shipped"

In [395]:
transofposs_perfective_connective2_11 = pd.read_csv("../results/transofposs_perfective/connective2/11.csv")
transofposs_perfective_connective2_11.head()

                                            stimulus        he       she
0  Miss Smith shipped a package to Mr. Smith and,...  0.223798  0.776202
1  The woman shipped a package to the man and, as...  0.489779  0.510221
2   Mary shipped a package to John and, as a result,  0.291920  0.708080
3   Alice shipped a package to Bob and, as a result,  0.327949  0.672051
4  The actress shipped a package to the actor and...  0.259352  0.740648

In [396]:
# female subject
transofposs_perfective_connective2_11f = transofposs_perfective_connective2_11[0:12]
transofposs_perfective_connective2_11f = transofposs_perfective_connective2_11f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_11m = transofposs_perfective_connective2_11[12:24]

#### female subject

In [397]:
transofposs_perfective_connective2_11f

                                             stimulus       she        he
0   Miss Smith shipped a package to Mr. Smith and,...  0.776202  0.223798
1   The woman shipped a package to the man and, as...  0.510221  0.489779
2    Mary shipped a package to John and, as a result,  0.708080  0.291920
3    Alice shipped a package to Bob and, as a result,  0.672051  0.327949
4   The actress shipped a package to the actor and...  0.740648  0.259352
5   The girl shipped a package to the boy and, as ...  0.435608  0.564392
6   Mrs. Taylor shipped a package to Mr. Williams ...  0.711469  0.288531
7   Emma shipped a package to David and, as a result,  0.847090  0.152910
8   The princess shipped a package to the prince a...  0.551994  0.448006
9   Sarah shipped a package to Robert and, as a re...  0.617733  0.382267
10  Mrs. Williams shipped a package to  Mr. Taylor...  0.705642  0.294358
11  Emily shipped a package to Paul and, as a result,  0.763072  0.236928

In [398]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_11f,'he'))

P('subj-pron'|subj=female) =  0.6699842909971873
P('non-subj-pron'|subj=female) =  0.33001572887102765

In [399]:
c2_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11f,'she')
c2_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11f,'he')

#### male subject

In [400]:
transofposs_perfective_connective2_11m

                                             stimulus        he       she
12  Mr. Smith shipped a package to Miss Smith and,...  0.355634  0.644366
13  The man shipped a package to the woman and, as...  0.494234  0.505766
14   John shipped a package to Mary and, as a result,  0.249118  0.750882
15   Bob shipped a package to Alice and, as a result,  0.558998  0.441002
16  The actor shipped a package to the actress and...  0.446275  0.553725
17  The boy shipped a package to the girl and, as ...  0.565970  0.434030
18  Mr. William shipped a package to  Mrs. Taylor ...  0.224346  0.775654
19  David shipped a package to Emma and, as a result,  0.233895  0.766105
20  The prince shipped a package to the princess a...  0.354935  0.645065
21  Robert shipped a package to Sarah and, as a re...  0.417444  0.582556
22  Mr. Taylor shipped a package to Mrs. Williams ...  0.212920  0.787080
23  Paul shipped a package to Emily and, as a result,  0.379676  0.620324

In [401]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_11m,'she'))

P('subj-pron'|subj=male) =  0.37445370480418205
P('non-subj-pron'|subj=male) =  0.6255462914705276

In [402]:
c2_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11m,'he')
c2_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11m,'she')

### verb: "transmitted"

In [403]:
transofposs_perfective_connective2_12 = pd.read_csv("../results/transofposs_perfective/connective2/12.csv")
transofposs_perfective_connective2_12.head()

                                            stimulus        he       she
0  Miss Smith transmitted a message to Mr. Smith ...  0.284893  0.715107
1  The woman transmitted a message to the man and...  0.601858  0.398142
2  Mary transmitted a message to John and, as a r...  0.356817  0.643183
3  Alice transmitted a message to Bob and, as a r...  0.525969  0.474031
4  The actress transmitted a message to the actor...  0.471903  0.528097

In [404]:
# female subject
transofposs_perfective_connective2_12f = transofposs_perfective_connective2_12[0:12]
transofposs_perfective_connective2_12f = transofposs_perfective_connective2_12f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_12m = transofposs_perfective_connective2_12[12:24]

#### female subject

In [405]:
transofposs_perfective_connective2_12f

                                             stimulus       she        he
0   Miss Smith transmitted a message to Mr. Smith ...  0.715107  0.284893
1   The woman transmitted a message to the man and...  0.398142  0.601858
2   Mary transmitted a message to John and, as a r...  0.643183  0.356817
3   Alice transmitted a message to Bob and, as a r...  0.474031  0.525969
4   The actress transmitted a message to the actor...  0.528097  0.471903
5   The girl transmitted a message to the boy and,...  0.322070  0.677930
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.651093  0.348907
7   Emma transmitted a message to David and, as a ...  0.746302  0.253698
8   The princess transmitted a message to the prin...  0.357156  0.642844
9   Sarah transmitted a message to Robert and, as ...  0.514250  0.485750
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.641827  0.358173
11  Emily transmitted a message to Paul and, as a ...  0.735399  0.264601

In [406]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_12f,'he'))

P('subj-pron'|subj=female) =  0.5605547726154327
P('non-subj-pron'|subj=female) =  0.43944523980220157

In [407]:
c2_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12f,'she')
c2_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12f,'he')

#### male subject

In [408]:
transofposs_perfective_connective2_12m

                                             stimulus        he       she
12  Mr. Smith transmitted a message to Miss Smith ...  0.214720  0.785280
13  The man transmitted a message to the woman and...  0.239673  0.760327
14  John transmitted a message to Mary and, as a r...  0.099747  0.900253
15  Bob transmitted a message to Alice and, as a r...  0.339973  0.660027
16  The actor transmitted a message to the actress...  0.209092  0.790908
17  The boy transmitted a message to the girl and,...  0.218412  0.781588
18  Mr. William transmitted a message to  Mrs. Tay...  0.080487  0.919513
19  David transmitted a message to Emma and, as a ...  0.162173  0.837827
20  The prince transmitted a message to the prince...  0.131749  0.868251
21  Robert transmitted a message to Sarah and, as ...  0.168931  0.831069
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.084482  0.915518
23  Paul transmitted a message to Emily and, as a ...  0.304204  0.695796

In [409]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_12m,'she'))

P('subj-pron'|subj=male) =  0.1878035832196474
P('non-subj-pron'|subj=male) =  0.8121964186429977

In [410]:
c2_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12m,'he')
c2_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12m,'she')

### verb: "wired"

In [411]:
transofposs_perfective_connective2_14 = pd.read_csv("../results/transofposs_perfective/connective2/14.csv")
transofposs_perfective_connective2_14.head()

                                            stimulus        he       she
0  Miss Smith wired money to Mr. Smith and, as a ...  0.491586  0.508414
1  The woman wired money to the man and, as a res...  0.668662  0.331338
2         Mary wired money to John and, as a result,  0.549238  0.450762
3         Alice wired money to Bob and, as a result,  0.648068  0.351932
4  The actress wired money to the actor and, as a...  0.624528  0.375472

In [412]:
# female subject
transofposs_perfective_connective2_14f = transofposs_perfective_connective2_14[0:12]
transofposs_perfective_connective2_14f = transofposs_perfective_connective2_14f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_14m = transofposs_perfective_connective2_14[12:24]

#### female subject

In [413]:
transofposs_perfective_connective2_14f

                                             stimulus       she        he
0   Miss Smith wired money to Mr. Smith and, as a ...  0.508414  0.491586
1   The woman wired money to the man and, as a res...  0.331338  0.668662
2          Mary wired money to John and, as a result,  0.450762  0.549238
3          Alice wired money to Bob and, as a result,  0.351932  0.648068
4   The actress wired money to the actor and, as a...  0.375472  0.624528
5   The girl wired money to the boy and, as a result,  0.300746  0.699254
6   Mrs. Taylor wired money to Mr. Williams and, a...  0.522186  0.477814
7         Emma wired money to David and, as a result,  0.615974  0.384026
8   The princess wired money to the prince and, as...  0.280738  0.719262
9       Sarah wired money to Robert and, as a result,  0.383018  0.616982
10  Mrs. Williams wired money to  Mr. Taylor and, ...  0.505053  0.494947
11        Emily wired money to Paul and, as a result,  0.566222  0.433778

In [414]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_14f,'he'))

P('subj-pron'|subj=female) =  0.4326547011733055
P('non-subj-pron'|subj=female) =  0.5673453162113825

In [415]:
c2_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_connective2_14f,'she')
c2_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_connective2_14f,'he')

#### male subject

In [416]:
transofposs_perfective_connective2_14m

                                             stimulus        he       she
12  Mr. Smith wired money to Miss Smith and, as a ...  0.234742  0.765258
13  The man wired money to the woman and, as a res...  0.255962  0.744038
14         John wired money to Mary and, as a result,  0.111509  0.888491
15         Bob wired money to Alice and, as a result,  0.320415  0.679585
16  The actor wired money to the actress and, as a...  0.207012  0.792988
17  The boy wired money to the girl and, as a result,  0.242691  0.757309
18  Mr. William wired money to  Mrs. Taylor and, a...  0.125471  0.874529
19        David wired money to Emma and, as a result,  0.165959  0.834041
20  The prince wired money to the princess and, as...  0.110497  0.889503
21      Robert wired money to Sarah and, as a result,  0.190411  0.809589
22  Mr. Taylor wired money to Mrs. Williams and, a...  0.081489  0.918511
23        Paul wired money to Emily and, as a result,  0.331955  0.668045

In [417]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_14m,'she'))

P('subj-pron'|subj=male) =  0.1981760567675034
P('non-subj-pron'|subj=male) =  0.8018239388863245

In [418]:
c2_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_connective2_14m,'he')
c2_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_connective2_14m,'she')

### verb: "carried"

In [419]:
transofposs_perfective_connective2_15 = pd.read_csv("../results/transofposs_perfective/connective2/15.csv")
transofposs_perfective_connective2_15.head()

                                            stimulus        he       she
0  Miss Smith carried a tray to Mr. Smith and, as...  0.286696  0.713304
1  The woman carried a tray to the man and, as a ...  0.477933  0.522067
2      Mary carried a tray to John and, as a result,  0.228827  0.771173
3      Alice carried a tray to Bob and, as a result,  0.418149  0.581851
4  The actress carried a tray to the actor and, a...  0.378523  0.621477

In [420]:
# female subject
transofposs_perfective_connective2_15f = transofposs_perfective_connective2_15[0:12]
transofposs_perfective_connective2_15f = transofposs_perfective_connective2_15f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_15m = transofposs_perfective_connective2_15[12:24]

#### female subject

In [421]:
transofposs_perfective_connective2_15f

                                             stimulus       she        he
0   Miss Smith carried a tray to Mr. Smith and, as...  0.713304  0.286696
1   The woman carried a tray to the man and, as a ...  0.522067  0.477933
2       Mary carried a tray to John and, as a result,  0.771173  0.228827
3       Alice carried a tray to Bob and, as a result,  0.581851  0.418149
4   The actress carried a tray to the actor and, a...  0.621477  0.378523
5   The girl carried a tray to the boy and, as a r...  0.488823  0.511177
6   Mrs. Taylor carried a tray to Mr. Williams and...  0.689060  0.310940
7      Emma carried a tray to David and, as a result,  0.759506  0.240494
8   The princess carried a tray to the prince and,...  0.627023  0.372977
9    Sarah carried a tray to Robert and, as a result,  0.572755  0.427245
10  Mrs. Williams carried a tray to  Mr. Taylor an...  0.652995  0.347005
11     Emily carried a tray to Paul and, as a result,  0.688608  0.311392

In [422]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_15f,'he'))

P('subj-pron'|subj=female) =  0.6407200172543526
P('non-subj-pron'|subj=female) =  0.3592799740533034

In [423]:
c2_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_connective2_15f,'she')
c2_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_connective2_15f,'he')

#### male subject

In [424]:
transofposs_perfective_connective2_15m

                                             stimulus        he       she
12  Mr. Smith carried a tray to Miss Smith and, as...  0.447945  0.552055
13  The man carried a tray to the woman and, as a ...  0.700897  0.299103
14      John carried a tray to Mary and, as a result,  0.407661  0.592338
15      Bob carried a tray to Alice and, as a result,  0.828587  0.171413
16  The actor carried a tray to the actress and, a...  0.819727  0.180273
17  The boy carried a tray to the girl and, as a r...  0.779301  0.220699
18  Mr. William carried a tray to  Mrs. Taylor and...  0.257671  0.742329
19     David carried a tray to Emma and, as a result,  0.382586  0.617414
20  The prince carried a tray to the princess and,...  0.641836  0.358164
21   Robert carried a tray to Sarah and, as a result,  0.554839  0.445161
22  Mr. Taylor carried a tray to Mrs. Williams and...  0.271569  0.728431
23     Paul carried a tray to Emily and, as a result,  0.425022  0.574978

In [425]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_15m,'she'))

P('subj-pron'|subj=male) =  0.5431366711854935
P('non-subj-pron'|subj=male) =  0.45686333253979683

In [426]:
c2_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_connective2_15m,'he')
c2_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_connective2_15m,'she')

### verb: "delivered"

In [427]:
transofposs_perfective_connective2_16 = pd.read_csv("../results/transofposs_perfective/connective2/16.csv")
transofposs_perfective_connective2_16.head()

                                            stimulus        he       she
0  Miss Smith delivered a subpoena to Mr. Smith a...  0.286362  0.713638
1  The woman delivered a subpoena to the man and,...  0.646000  0.354000
2  Mary delivered a subpoena to John and, as a re...  0.418113  0.581887
3  Alice delivered a subpoena to Bob and, as a re...  0.575614  0.424386
4  The actress delivered a subpoena to the actor ...  0.527315  0.472685

In [428]:
# female subject
transofposs_perfective_connective2_16f = transofposs_perfective_connective2_16[0:12]
transofposs_perfective_connective2_16f = transofposs_perfective_connective2_16f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_16m = transofposs_perfective_connective2_16[12:24]

#### female subject

In [429]:
transofposs_perfective_connective2_16f

                                             stimulus       she        he
0   Miss Smith delivered a subpoena to Mr. Smith a...  0.713638  0.286362
1   The woman delivered a subpoena to the man and,...  0.354000  0.646000
2   Mary delivered a subpoena to John and, as a re...  0.581887  0.418113
3   Alice delivered a subpoena to Bob and, as a re...  0.424386  0.575614
4   The actress delivered a subpoena to the actor ...  0.472685  0.527315
5   The girl delivered a subpoena to the boy and, ...  0.316854  0.683146
6   Mrs. Taylor delivered a subpoena to Mr. Willia...  0.705809  0.294191
7   Emma delivered a subpoena to David and, as a r...  0.624695  0.375305
8   The princess delivered a subpoena to the princ...  0.447984  0.552016
9   Sarah delivered a subpoena to Robert and, as a...  0.460005  0.539995
10  Mrs. Williams delivered a subpoena to Mr. Tayl...  0.681663  0.318337
11  Emily delivered a subpoena to Paul and, as a r...  0.643058  0.356942

In [430]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_16f,'he'))

P('subj-pron'|subj=female) =  0.5355552633603414
P('non-subj-pron'|subj=female) =  0.46444472422202426

In [431]:
c2_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16f,'she')
c2_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16f,'he')

#### male subject

In [432]:
transofposs_perfective_connective2_16m

                                             stimulus        he       she
12  Mr. Smith delivered a subpoena to Miss Smith a...  0.373321  0.626679
13  The man delivered a subpoena to the woman and,...  0.549491  0.450509
14  John delivered a subpoena to Mary and, as a re...  0.239592  0.760408
15  Bob delivered a subpoena to Alice and, as a re...  0.464649  0.535351
16  The actor delivered a subpoena to the actress ...  0.610139  0.389861
17  The boy delivered a subpoena to the girl and, ...  0.565903  0.434097
18  Mr. William delivered a subpoena to Mrs. Taylo...  0.211591  0.788409
19  David delivered a subpoena to Emma and, as a r...  0.387274  0.612726
20  The prince delivered a subpoena to the princes...  0.337145  0.662855
21  Robert delivered a subpoena to Sarah and, as a...  0.489633  0.510367
22  Mr. Taylor delivered a subpoena to Mrs. Willia...  0.218153  0.781847
23  Paul delivered a subpoena to Emily and, as a r...  0.439762  0.560238

In [433]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_16m,'she'))

P('subj-pron'|subj=male) =  0.4072210565209389
P('non-subj-pron'|subj=male) =  0.5927789335449537

In [434]:
c2_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16m,'he')
c2_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16m,'she')

### verb: "gave"

In [435]:
transofposs_perfective_connective2_17 = pd.read_csv("../results/transofposs_perfective/connective2/17.csv")
transofposs_perfective_connective2_17.head()

                                            stimulus        he       she
0  Miss Smith gave a sweater to Mr. Smith and, as...  0.370360  0.629640
1  The woman gave a sweater to the man and, as a ...  0.757729  0.242271
2      Mary gave a sweater to John and, as a result,  0.543267  0.456733
3      Alice gave a sweater to Bob and, as a result,  0.644162  0.355838
4  The actress gave a sweater to the actor and, a...  0.669398  0.330602

In [436]:
# female subject
transofposs_perfective_connective2_17f = transofposs_perfective_connective2_17[0:12]
transofposs_perfective_connective2_17f = transofposs_perfective_connective2_17f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_17m = transofposs_perfective_connective2_17[12:24]

#### female subject

In [437]:
transofposs_perfective_connective2_17f

                                             stimulus       she        he
0   Miss Smith gave a sweater to Mr. Smith and, as...  0.629640  0.370360
1   The woman gave a sweater to the man and, as a ...  0.242271  0.757729
2       Mary gave a sweater to John and, as a result,  0.456733  0.543267
3       Alice gave a sweater to Bob and, as a result,  0.355838  0.644162
4   The actress gave a sweater to the actor and, a...  0.330602  0.669398
5   The girl gave a sweater to the boy and, as a r...  0.217131  0.782869
6   Mrs. Taylor gave a sweater to Mr. Williams and...  0.534654  0.465346
7      Emma gave a sweater to David and, as a result,  0.599846  0.400154
8   The princess gave a sweater to the prince and,...  0.337372  0.662628
9    Sarah gave a sweater to Robert and, as a result,  0.454101  0.545899
10  Mrs. Williams gave a sweater to  Mr. Taylor an...  0.576630  0.423370
11     Emily gave a sweater to Paul and, as a result,  0.547229  0.452772

In [438]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_17f,'he'))

P('subj-pron'|subj=female) =  0.440170519053936
P('non-subj-pron'|subj=female) =  0.5598294859131178

In [439]:
c2_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_connective2_17f,'she')
c2_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_connective2_17f,'he')

#### male subject

In [440]:
transofposs_perfective_connective2_17m

                                             stimulus        he       she
12  Mr. Smith gave a sweater to Miss Smith and, as...  0.336737  0.663263
13  The man gave a sweater to the woman and, as a ...  0.493822  0.506178
14      John gave a sweater to Mary and, as a result,  0.255652  0.744348
15      Bob gave a sweater to Alice and, as a result,  0.468774  0.531226
16  The actor gave a sweater to the actress and, a...  0.629303  0.370697
17  The boy gave a sweater to the girl and, as a r...  0.511717  0.488283
18  Mr. William gave a sweater to  Mrs. Taylor and...  0.179404  0.820596
19     David gave a sweater to Emma and, as a result,  0.277046  0.722954
20  The prince gave a sweater to the princess and,...  0.313932  0.686068
21   Robert gave a sweater to Sarah and, as a result,  0.373177  0.626823
22  Mr. Taylor gave a sweater to Mrs. Williams and...  0.173402  0.826598
23     Paul gave a sweater to Emily and, as a result,  0.358187  0.641813

In [441]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_17m,'she'))

P('subj-pron'|subj=male) =  0.36426274105906487
P('non-subj-pron'|subj=male) =  0.6357372800509135

In [442]:
c2_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_connective2_17m,'he')
c2_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_connective2_17m,'she')

### verb: "handed"

In [443]:
transofposs_perfective_connective2_18 = pd.read_csv("../results/transofposs_perfective/connective2/18.csv")
transofposs_perfective_connective2_18.head()

                                            stimulus        he       she
0  Miss Smith handed a book to Mr. Smith and, as ...  0.291515  0.708485
1  The woman handed a book to the man and, as a r...  0.583246  0.416754
2       Mary handed a book to John and, as a result,  0.438043  0.561957
3       Alice handed a book to Bob and, as a result,  0.509889  0.490111
4  The actress handed a book to the actor and, as...  0.452428  0.547572

In [444]:
# female subject
transofposs_perfective_connective2_18f = transofposs_perfective_connective2_18[0:12]
transofposs_perfective_connective2_18f = transofposs_perfective_connective2_18f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_18m = transofposs_perfective_connective2_18[12:24]

#### female subject

In [445]:
transofposs_perfective_connective2_18f

                                             stimulus       she        he
0   Miss Smith handed a book to Mr. Smith and, as ...  0.708485  0.291515
1   The woman handed a book to the man and, as a r...  0.416754  0.583246
2        Mary handed a book to John and, as a result,  0.561957  0.438043
3        Alice handed a book to Bob and, as a result,  0.490111  0.509889
4   The actress handed a book to the actor and, as...  0.547572  0.452428
5   The girl handed a book to the boy and, as a re...  0.323814  0.676186
6   Mrs. Taylor handed a book to Mr. Williams and,...  0.637171  0.362829
7       Emma handed a book to David and, as a result,  0.730768  0.269232
8   The princess handed a book to the prince and, ...  0.373571  0.626429
9     Sarah handed a book to Robert and, as a result,  0.378073  0.621927
10  Mrs. Williams handed a book to Mr. Taylor and,...  0.671021  0.328979
11      Emily handed a book to Paul and, as a result,  0.666703  0.333297

In [446]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_18f,'he'))

P('subj-pron'|subj=female) =  0.5421667645374934
P('non-subj-pron'|subj=female) =  0.4578332429130872

In [447]:
c2_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_connective2_18f,'she')
c2_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_connective2_18f,'he')

#### male subject

In [448]:
transofposs_perfective_connective2_18m

                                             stimulus        he       she
12  Mr. Smith handed a book to Miss Smith and, as ...  0.259014  0.740986
13  The man handed a book to the woman and, as a r...  0.377789  0.622211
14       John handed a book to Mary and, as a result,  0.198449  0.801551
15       Bob handed a book to Alice and, as a result,  0.321031  0.678969
16  The actor handed a book to the actress and, as...  0.336845  0.663155
17  The boy handed a book to the girl and, as a re...  0.324399  0.675601
18  Mr. William handed a book to Mrs. Taylor and, ...  0.153996  0.846004
19      David handed a book to Emma and, as a result,  0.153058  0.846942
20  The prince handed a book to the princess and, ...  0.243444  0.756556
21    Robert handed a book to Sarah and, as a result,  0.333186  0.666814
22  Mr. Taylor handed a book to Mrs. Williams and,...  0.140248  0.859752
23      Paul handed a book to Emily and, as a result,  0.280482  0.719518

In [449]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_18m,'she'))

P('subj-pron'|subj=male) =  0.2601617102821668
P('non-subj-pron'|subj=male) =  0.7398382773001989

In [450]:
c2_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_connective2_18m,'he')
c2_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_connective2_18m,'she')

### verb: "passed"

In [451]:
transofposs_perfective_connective2_19 = pd.read_csv("../results/transofposs_perfective/connective2/19.csv")
transofposs_perfective_connective2_19.head()

                                            stimulus        he       she
0  Miss Smith passed a sandwich to Mr. Smith and,...  0.276869  0.723131
1  The woman passed a sandwich to the man and, as...  0.553942  0.446059
2   Mary passed a sandwich to John and, as a result,  0.341996  0.658005
3   Alice passed a sandwich to Bob and, as a result,  0.496588  0.503412
4  The actress passed a sandwich to the actor and...  0.618849  0.381151

In [452]:
# female subject
transofposs_perfective_connective2_19f = transofposs_perfective_connective2_19[0:12]
transofposs_perfective_connective2_19f = transofposs_perfective_connective2_19f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_19m = transofposs_perfective_connective2_19[12:24]

#### female subject

In [453]:
transofposs_perfective_connective2_19f

                                             stimulus       she        he
0   Miss Smith passed a sandwich to Mr. Smith and,...  0.723131  0.276869
1   The woman passed a sandwich to the man and, as...  0.446059  0.553942
2    Mary passed a sandwich to John and, as a result,  0.658005  0.341996
3    Alice passed a sandwich to Bob and, as a result,  0.503412  0.496588
4   The actress passed a sandwich to the actor and...  0.381151  0.618849
5   The girl passed a sandwich to the boy and, as ...  0.325887  0.674113
6   Mrs. Taylor passed a sandwich to Mr. Williams ...  0.641158  0.358842
7   Emma passed a sandwich to David and, as a result,  0.699059  0.300941
8   The princess passed a sandwich to the prince a...  0.500994  0.499006
9   Sarah passed a sandwich to Robert and, as a re...  0.466848  0.533152
10  Mrs. Williams passed a sandwich to  Mr. Taylor...  0.641461  0.358539
11  Emily passed a sandwich to Paul and, as a result,  0.697592  0.302408

In [454]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_19f,'he'))

P('subj-pron'|subj=female) =  0.5570628841718038
P('non-subj-pron'|subj=female) =  0.44293713569641113

In [455]:
c2_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_connective2_19f,'she')
c2_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_connective2_19f,'he')

#### male subject

In [456]:
transofposs_perfective_connective2_19m

                                             stimulus        he       she
12  Mr. Smith passed a sandwich to Miss Smith and,...  0.398790  0.601210
13  The man passed a sandwich to the woman and, as...  0.536149  0.463851
14   John passed a sandwich to Mary and, as a result,  0.272604  0.727396
15   Bob passed a sandwich to Alice and, as a result,  0.629853  0.370147
16  The actor passed a sandwich to the actress and...  0.846240  0.153760
17  The boy passed a sandwich to the girl and, as ...  0.662044  0.337956
18  Mr. William passed a sandwich to  Mrs. Taylor ...  0.290101  0.709899
19  David passed a sandwich to Emma and, as a result,  0.389799  0.610201
20  The prince passed a sandwich to the princess a...  0.415130  0.584870
21  Robert passed a sandwich to Sarah and, as a re...  0.641178  0.358822
22  Mr. Taylor passed a sandwich to Mrs. Williams ...  0.212552  0.787448
23  Paul passed a sandwich to Emily and, as a result,  0.492175  0.507825

In [457]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_19m,'she'))

P('subj-pron'|subj=male) =  0.48221786816914874
P('non-subj-pron'|subj=male) =  0.517782136797905

In [458]:
c2_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_connective2_19m,'he')
c2_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_connective2_19m,'she')

### verb: "served"

In [459]:
transofposs_perfective_connective2_20 = pd.read_csv("../results/transofposs_perfective/connective2/20.csv")
transofposs_perfective_connective2_20.head()

                                            stimulus        he       she
0  Miss Smith served a chili to Mr. Smith and, as...  0.149042  0.850958
1  The woman served a chili to the man and, as a ...  0.576440  0.423560
2      Mary served a chili to John and, as a result,  0.176650  0.823350
3      Alice served a chili to Bob and, as a result,  0.317405  0.682595
4  The actress served a chili to the actor and, a...  0.482706  0.517294

In [460]:
# female subject
transofposs_perfective_connective2_20f = transofposs_perfective_connective2_20[0:12]
transofposs_perfective_connective2_20f = transofposs_perfective_connective2_20f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_20m = transofposs_perfective_connective2_20[12:24]

#### female subject

In [461]:
transofposs_perfective_connective2_20f

                                             stimulus       she        he
0   Miss Smith served a chili to Mr. Smith and, as...  0.850958  0.149042
1   The woman served a chili to the man and, as a ...  0.423560  0.576440
2       Mary served a chili to John and, as a result,  0.823350  0.176650
3       Alice served a chili to Bob and, as a result,  0.682595  0.317405
4   The actress served a chili to the actor and, a...  0.517294  0.482706
5   The girl served a chili to the boy and, as a r...  0.355623  0.644377
6   Mrs. Taylor served a chili to Mr. Williams and...  0.763871  0.236129
7      Emma served a chili to David and, as a result,  0.771972  0.228028
8   The princess served a chili to the prince and,...  0.627587  0.372413
9    Sarah served a chili to Robert and, as a result,  0.720624  0.279376
10  Mrs. Williams served a chili to Mr. Taylor and...  0.773103  0.226897
11     Emily served a chili to Paul and, as a result,  0.875121  0.124879

In [462]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_20f,'he'))

P('subj-pron'|subj=female) =  0.6821382840474447
P('non-subj-pron'|subj=female) =  0.31786170105139416

In [463]:
c2_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_connective2_20f,'she')
c2_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_connective2_20f,'he')

#### male subject

In [464]:
transofposs_perfective_connective2_20m

                                             stimulus        he       she
12  Mr. Smith served a chili to Miss Smith and, as...  0.798370  0.201630
13  The man served a chili to the woman and, as a ...  0.864256  0.135744
14      John served a chili to Mary and, as a result,  0.785339  0.214661
15      Bob served a chili to Alice and, as a result,  0.945063  0.054937
16  The actor served a chili to the actress and, a...  0.948341  0.051659
17  The boy served a chili to the girl and, as a r...  0.917647  0.082353
18  Mr. William served a chili to  Mrs. Taylor and...  0.538632  0.461368
19     David served a chili to Emma and, as a result,  0.821299  0.178701
20  The prince served a chili to the princess and,...  0.889071  0.110929
21   Robert served a chili to Sarah and, as a result,  0.947457  0.052543
22  Mr. Taylor served a chili to Mrs. Williams and...  0.565215  0.434785
23     Paul served a chili to Emily and, as a result,  0.804670  0.195330

In [465]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_20m,'she'))

P('subj-pron'|subj=male) =  0.8187801490227381
P('non-subj-pron'|subj=male) =  0.1812198751916488

In [466]:
c2_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_connective2_20m,'he')
c2_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_connective2_20m,'she')

## Summary of Results

In [467]:
c2_results_fsubj_subjpron = pd.DataFrame(list(c2_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c2_results_fsubj_objpron = pd.DataFrame(list(c2_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c2_results_fsubj = c2_results_fsubj_subjpron.merge(results_fsubj_objpron)
c2_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0         flung              0.425880             0.766546
1        kicked              0.396835             0.731772
2        lobbed              0.413242             0.678735
3         threw              0.484860             0.712564
4        tossed              0.451741             0.717138
5       brought              0.536730             0.628721
6     forwarded              0.606733             0.739143
7        mailed              0.592622             0.690452
8       shipped              0.669984             0.718388
9   transmitted              0.560555             0.693953
10        wired              0.432655             0.711636
11      carried              0.640720             0.711210
12    delivered              0.535555             0.715972
13         gave              0.440171             0.635254
14       handed              0.542167             0.687999
15       passed              0.557063             0.710934
16       served              0.682138             0.636393

In [468]:
c2_results_msubj_subjpron = pd.DataFrame(list(c2_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c2_results_msubj_objpron = pd.DataFrame(list(c2_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c2_results_msubj = c2_results_msubj_subjpron.merge(c2_results_msubj_objpron)
c2_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0       chucked            0.734495           0.265505
1         flung            0.399408           0.600592
2        kicked            0.691597           0.308403
3        lobbed            0.344568           0.655432
4        rolled            0.608369           0.391631
5         threw            0.495408           0.504592
6        tossed            0.389803           0.610197
7       brought            0.380327           0.619673
8     forwarded            0.316808           0.683192
9        mailed            0.230068           0.769932
10      shipped            0.374454           0.625546
11  transmitted            0.187804           0.812196
12        wired            0.198176           0.801824
13      carried            0.543137           0.456863
14    delivered            0.407221           0.592779
15         gave            0.364263           0.635737
16       handed            0.260162           0.739838
17       passed            0.482218           0.517782
18       served            0.818780           0.181220

In [469]:
c2_results = c2_results_fsubj.merge(c2_results_msubj)
c2_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flung,0.425880,0.766546,0.399408,0.600592
1,kicked,0.396835,0.731772,0.691597,0.308403
2,lobbed,0.413242,0.678735,0.344568,0.655432
3,threw,0.484860,0.712564,0.495408,0.504592
4,tossed,0.451741,0.717138,0.389803,0.610197
5,brought,0.536730,0.628721,0.380327,0.619673
6,forwarded,0.606733,0.739143,0.316808,0.683192
7,mailed,0.592622,0.690452,0.230068,0.769932
8,shipped,0.669984,0.718388,0.374454,0.625546
9,transmitted,0.560555,0.693953,0.187804,0.812196
10,wired,0.432655,0.711636,0.198176,0.801824
11,carried,0.640720,0.711210,0.543137,0.456863
12,delivered,0.535555,0.715972,0.407221,0.592779
13,gave,0.440171,0.635254,0.364263,0.635737
14,handed,0.542167,0.687999,0.260162,0.739838
15,passed,0.557063,0.710934,0.482218,0.517782
16,served,0.682138,0.636393,0.818780,0.181220

In [470]:
print("P(subj_reference |subj=female)", compute_average(c2_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c2_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.5276265124260795
P(obj_reference |subj=female) 0.6992240874644589

In [471]:
print("P(subj_reference |subj=male)", compute_average(c2_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c2_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.4049529827327705
P(obj_reference |subj=male) 0.595047020517728