In [1]:
import pandas as pd
import numpy as np

In [2]:
def compute_average(df,col):
    return np.mean(df[col].values)

## No-prompt

In [3]:
np_average_subj_female_subj_pron = {}
np_average_subj_female_obj_pron = {}
np_average_subj_male_subj_pron = {}
np_average_subj_male_obj_pron = {}

### Verb: "chucking" (NOTE: gets tokenized to 'unk')

In [4]:
transofposs_imperfective_noprompt_1 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/1.csv")
transofposs_imperfective_noprompt_1.head()

                                          stimulus        He       She
0   Miss Smith was chucking a wrench to Mr. Smith.  0.307260  0.692740
1      The woman was chucking a wrench to the man.  0.802453  0.197547
2              Mary was chucking a wrench to John.  0.672846  0.327154
3              Alice was chucking a wrench to Bob.  0.329361  0.670639
4  The actress was chucking a wrench to the actor.  0.823547  0.176453

In [5]:
# female subject
transofposs_imperfective_noprompt_1f = transofposs_imperfective_noprompt_1[0:12]
transofposs_imperfective_noprompt_1f = transofposs_imperfective_noprompt_1f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_1m = transofposs_imperfective_noprompt_1[12:24]

#### female subject

In [6]:
transofposs_imperfective_noprompt_1f

                                             stimulus       She        He
0      Miss Smith was chucking a wrench to Mr. Smith.  0.692740  0.307260
1         The woman was chucking a wrench to the man.  0.197547  0.802453
2                 Mary was chucking a wrench to John.  0.327154  0.672846
3                 Alice was chucking a wrench to Bob.  0.670639  0.329361
4     The actress was chucking a wrench to the actor.  0.176453  0.823547
5          The girl was chucking a wrench to the boy.  0.189874  0.810126
6   Mrs. Taylor was chucking a wrench to Mr. Willi...  0.789931  0.210069
7                Emma was chucking a wrench to David.  0.190824  0.809176
8   The princess was chucking a wrench to the prince.  0.187887  0.812113
9              Sarah was chucking a wrench to Robert.  0.713202  0.286798
10  Mrs. Williams was chucking a wrench to  Mr. Ta...  0.672945  0.327055
11               Emily was chucking a wrench to Paul.  0.716819  0.283181

In [7]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_1f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_1f,'He'))

P('subj-pron'|subj=female) =  0.4605012846489747
P('non-subj-pron'|subj=female) =  0.5394987314939499

In [8]:
#np_average_subj_female_subj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1f,'She')
#np_average_subj_female_obj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1f,'He')

#### male subject

In [9]:
transofposs_imperfective_noprompt_1m

                                             stimulus        He       She
12     Mr. Smith was chucking a wrench to Miss Smith.  0.869262  0.130738
13        The man was chucking a wrench to the woman.  0.893655  0.106345
14                John was chucking a wrench to Mary.  0.884366  0.115634
15                Bob was chucking a wrench to Alice.  0.885083  0.114917
16    The actor was chucking a wrench to the actress.  0.883255  0.116745
17         The boy was chucking a wrench to the girl.  0.883937  0.116063
18  Mr. William was chucking a wrench to  Mrs. Tay...  0.338330  0.661670
19               David was chucking a wrench to Emma.  0.111464  0.888536
20  The prince was chucking a wrench to the princess.  0.888851  0.111149
21             Robert was chucking a wrench to Sarah.  0.260443  0.739557
22  Mr. Taylor was chucking a wrench to Mrs. Willi...  0.169698  0.830302
23               Paul was chucking a wrench to Emily.  0.868888  0.131112

In [10]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_1m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_1m,'She'))

P('subj-pron'|subj=male) =  0.6614359393715858
P('non-subj-pron'|subj=male) =  0.3385640761504571

In [11]:
#np_average_subj_male_subj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1m,'He')
#np_average_subj_male_obj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1m,'She')

### Verb: "flinging"

In [12]:
transofposs_imperfective_noprompt_2 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/2.csv")
transofposs_imperfective_noprompt_2.head()

                                           stimulus        He       She
0   Miss Smith was flinging a frisbee to Mr. Smith.  0.283476  0.716524
1      The woman was flinging a frisbee to the man.  0.802719  0.197281
2              Mary was flinging a frisbee to John.  0.748011  0.251989
3              Alice was flinging a frisbee to Bob.  0.535117  0.464883
4  The actress was flinging a frisbee to the actor.  0.822873  0.177127

In [13]:
# female subject
transofposs_imperfective_noprompt_2f = transofposs_imperfective_noprompt_2[0:12]
transofposs_imperfective_noprompt_2f = transofposs_imperfective_noprompt_2f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_2m = transofposs_imperfective_noprompt_2[12:24]

#### female subject

In [14]:
transofposs_imperfective_noprompt_2f

                                             stimulus       She        He
0     Miss Smith was flinging a frisbee to Mr. Smith.  0.716524  0.283476
1        The woman was flinging a frisbee to the man.  0.197281  0.802719
2                Mary was flinging a frisbee to John.  0.251989  0.748011
3                Alice was flinging a frisbee to Bob.  0.464883  0.535117
4    The actress was flinging a frisbee to the actor.  0.177127  0.822873
5         The girl was flinging a frisbee to the boy.  0.191333  0.808667
6   Mrs. Taylor was flinging a frisbee to Mr. Will...  0.764565  0.235435
7               Emma was flinging a frisbee to David.  0.189642  0.810359
8   The princess was flinging a frisbee to the pri...  0.189475  0.810525
9             Sarah was flinging a frisbee to Robert.  0.657449  0.342550
10  Mrs. Williams was flinging a frisbee to  Mr. T...  0.623531  0.376469
11              Emily was flinging a frisbee to Paul.  0.631168  0.368832

In [15]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_2f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_2f,'He'))

P('subj-pron'|subj=female) =  0.4212473010023435
P('non-subj-pron'|subj=female) =  0.5787527076900005

In [16]:
np_average_subj_female_subj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2f,'She')
np_average_subj_female_obj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2f,'He')

#### male subject

In [17]:
transofposs_imperfective_noprompt_2m

                                             stimulus        He       She
12    Mr. Smith was flinging a frisbee to Miss Smith.  0.867494  0.132506
13       The man was flinging a frisbee to the woman.  0.893993  0.106007
14               John was flinging a frisbee to Mary.  0.885249  0.114751
15               Bob was flinging a frisbee to Alice.  0.880041  0.119959
16   The actor was flinging a frisbee to the actress.  0.882903  0.117097
17        The boy was flinging a frisbee to the girl.  0.882844  0.117156
18  Mr. William was flinging a frisbee to  Mrs. Ta...  0.328740  0.671260
19              David was flinging a frisbee to Emma.  0.092297  0.907703
20  The prince was flinging a frisbee to the princ...  0.887813  0.112187
21            Robert was flinging a frisbee to Sarah.  0.185748  0.814252
22  Mr. Taylor was flinging a frisbee to Mrs. Will...  0.158677  0.841323
23              Paul was flinging a frisbee to Emily.  0.868120  0.131880

In [18]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_2m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_2m,'She'))

P('subj-pron'|subj=male) =  0.6511597565064827
P('non-subj-pron'|subj=male) =  0.3488402341802915

In [19]:
np_average_subj_male_subj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2m,'He')
np_average_subj_male_obj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2m,'She')

### Verb: "kicking"

In [20]:
transofposs_imperfective_noprompt_3 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/3.csv")
transofposs_imperfective_noprompt_3.head()

                                            stimulus        He       She
0  Miss Smith was kicking a soccer ball to Mr. Sm...  0.294603  0.705397
1    The woman was kicking a soccer ball to the man.  0.783032  0.216968
2            Mary was kicking a soccer ball to John.  0.690499  0.309501
3            Alice was kicking a soccer ball to Bob.  0.416408  0.583592
4  The actress was kicking a soccer ball to the a...  0.811070  0.188930

In [21]:
# female subject
transofposs_imperfective_noprompt_3f = transofposs_imperfective_noprompt_3[0:12]
transofposs_imperfective_noprompt_3f = transofposs_imperfective_noprompt_3f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_3m = transofposs_imperfective_noprompt_3[12:24]

#### female subject

In [22]:
transofposs_imperfective_noprompt_3f

                                             stimulus       She        He
0   Miss Smith was kicking a soccer ball to Mr. Sm...  0.705397  0.294603
1     The woman was kicking a soccer ball to the man.  0.216968  0.783032
2             Mary was kicking a soccer ball to John.  0.309501  0.690499
3             Alice was kicking a soccer ball to Bob.  0.583592  0.416408
4   The actress was kicking a soccer ball to the a...  0.188930  0.811070
5      The girl was kicking a soccer ball to the boy.  0.208141  0.791859
6   Mrs. Taylor was kicking a soccer ball to Mr. W...  0.800077  0.199923
7            Emma was kicking a soccer ball to David.  0.210878  0.789122
8   The princess was kicking a soccer ball to the ...  0.209339  0.790661
9          Sarah was kicking a soccer ball to Robert.  0.746557  0.253443
10  Mrs. Williams was kicking a soccer ball to  Mr...  0.635841  0.364159
11           Emily was kicking a soccer ball to Paul.  0.821171  0.178829

In [23]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_3f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_3f,'He'))

P('subj-pron'|subj=female) =  0.46969930703441304
P('non-subj-pron'|subj=female) =  0.5303007004161676

In [24]:
np_average_subj_female_subj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3f,'She')
np_average_subj_female_obj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3f,'He')

#### male subject

In [25]:
transofposs_imperfective_noprompt_3m

                                             stimulus        He       She
12  Mr. Smith was kicking a soccer ball to Miss Sm...  0.869089  0.130911
13    The man was kicking a soccer ball to the woman.  0.893018  0.106982
14            John was kicking a soccer ball to Mary.  0.888304  0.111697
15            Bob was kicking a soccer ball to Alice.  0.883107  0.116893
16  The actor was kicking a soccer ball to the act...  0.880827  0.119173
17     The boy was kicking a soccer ball to the girl.  0.881826  0.118174
18  Mr. William was kicking a soccer ball to  Mrs....  0.311445  0.688555
19           David was kicking a soccer ball to Emma.  0.865220  0.134780
20  The prince was kicking a soccer ball to the pr...  0.886782  0.113218
21         Robert was kicking a soccer ball to Sarah.  0.287234  0.712766
22  Mr. Taylor was kicking a soccer ball to Mrs. W...  0.150223  0.849777
23           Paul was kicking a soccer ball to Emily.  0.870754  0.129246

In [26]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_3m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_3m,'She'))

P('subj-pron'|subj=male) =  0.7223190031945705
P('non-subj-pron'|subj=male) =  0.2776809961845477

In [27]:
np_average_subj_male_subj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3m,'He')
np_average_subj_male_obj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3m,'She')

### verb: "lobbing"

In [28]:
transofposs_imperfective_noprompt_4 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/4.csv")
transofposs_imperfective_noprompt_4.head()

                                           stimulus        He       She
0   Miss Smith was lobbing a football to Mr. Smith.  0.320991  0.679009
1      The woman was lobbing a football to the man.  0.807441  0.192559
2              Mary was lobbing a football to John.  0.796232  0.203768
3              Alice was lobbing a football to Bob.  0.784901  0.215099
4  The actress was lobbing a football to the actor.  0.821899  0.178101

In [29]:
# female subject
transofposs_imperfective_noprompt_4f = transofposs_imperfective_noprompt_4[0:12]
transofposs_imperfective_noprompt_4f = transofposs_imperfective_noprompt_4f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_4m = transofposs_imperfective_noprompt_4[12:24]

#### female subject

In [30]:
transofposs_imperfective_noprompt_4f

                                             stimulus       She        He
0     Miss Smith was lobbing a football to Mr. Smith.  0.679009  0.320991
1        The woman was lobbing a football to the man.  0.192559  0.807441
2                Mary was lobbing a football to John.  0.203768  0.796232
3                Alice was lobbing a football to Bob.  0.215099  0.784901
4    The actress was lobbing a football to the actor.  0.178101  0.821899
5         The girl was lobbing a football to the boy.  0.188766  0.811234
6   Mrs. Taylor was lobbing a football to Mr. Will...  0.769258  0.230742
7               Emma was lobbing a football to David.  0.184368  0.815632
8   The princess was lobbing a football to the pri...  0.189541  0.810459
9             Sarah was lobbing a football to Robert.  0.506719  0.493281
10  Mrs. Williams was lobbing a football to  Mr. T...  0.618574  0.381426
11              Emily was lobbing a football to Paul.  0.638193  0.361807

In [31]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_4f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_4f,'He'))

P('subj-pron'|subj=female) =  0.38032954931259155
P('non-subj-pron'|subj=female) =  0.6196704419950644

In [32]:
np_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4f,'She')
np_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4f,'He')

#### male subject

In [33]:
transofposs_imperfective_noprompt_4m

                                             stimulus        He       She
12    Mr. Smith was lobbing a football to Miss Smith.  0.869038  0.130962
13       The man was lobbing a football to the woman.  0.893733  0.106267
14               John was lobbing a football to Mary.  0.886474  0.113526
15               Bob was lobbing a football to Alice.  0.879773  0.120227
16   The actor was lobbing a football to the actress.  0.884497  0.115503
17        The boy was lobbing a football to the girl.  0.884529  0.115471
18  Mr. William was lobbing a football to  Mrs. Ta...  0.348834  0.651166
19              David was lobbing a football to Emma.  0.099056  0.900944
20  The prince was lobbing a football to the princ...  0.889032  0.110968
21            Robert was lobbing a football to Sarah.  0.334114  0.665886
22  Mr. Taylor was lobbing a football to Mrs. Will...  0.167144  0.832856
23              Paul was lobbing a football to Emily.  0.866597  0.133403

In [34]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_4m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_4m,'She'))

P('subj-pron'|subj=male) =  0.6669017517318329
P('non-subj-pron'|subj=male) =  0.3330982644110918

In [35]:
np_average_subj_male_subj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4m,'He')
np_average_subj_male_obj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4m,'She')

### verb: "rolling"

In [36]:
transofposs_imperfective_noprompt_5 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/5.csv")
transofposs_imperfective_noprompt_5.head()

                                            stimulus        He       She
0   Miss Smith was rolling a toy truck to Mr. Smith.  0.235378  0.764622
1      The woman was rolling a toy truck to the man.  0.774861  0.225139
2              Mary was rolling a toy truck to John.  0.346581  0.653419
3              Alice was rolling a toy truck to Bob.  0.163107  0.836893
4  The actress was rolling a toy truck to the actor.  0.799798  0.200201

In [37]:
# female subject
transofposs_imperfective_noprompt_5f = transofposs_imperfective_noprompt_5[0:12]
transofposs_imperfective_noprompt_5f = transofposs_imperfective_noprompt_5f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_5m = transofposs_imperfective_noprompt_5[12:24]

#### female subject

In [38]:
transofposs_imperfective_noprompt_5f

                                             stimulus       She        He
0    Miss Smith was rolling a toy truck to Mr. Smith.  0.764622  0.235378
1       The woman was rolling a toy truck to the man.  0.225139  0.774861
2               Mary was rolling a toy truck to John.  0.653419  0.346581
3               Alice was rolling a toy truck to Bob.  0.836893  0.163107
4   The actress was rolling a toy truck to the actor.  0.200201  0.799798
5        The girl was rolling a toy truck to the boy.  0.217746  0.782254
6   Mrs. Taylor was rolling a toy truck to Mr. Wil...  0.863997  0.136003
7              Emma was rolling a toy truck to David.  0.231458  0.768542
8   The princess was rolling a toy truck to the pr...  0.222665  0.777335
9            Sarah was rolling a toy truck to Robert.  0.910805  0.089195
10  Mrs. Williams was rolling a toy truck to  Mr. ...  0.739004  0.260996
11             Emily was rolling a toy truck to Paul.  0.893301  0.106698

In [39]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_5f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_5f,'He'))

P('subj-pron'|subj=female) =  0.5632709587613741
P('non-subj-pron'|subj=female) =  0.43672903006275493

In [40]:
np_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_5f,'She')
np_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_5f,'He')

#### male subject

In [41]:
transofposs_imperfective_noprompt_5m

                                             stimulus        He       She
12   Mr. Smith was rolling a toy truck to Miss Smith.  0.867937  0.132063
13      The man was rolling a toy truck to the woman.  0.892392  0.107608
14              John was rolling a toy truck to Mary.  0.885846  0.114154
15              Bob was rolling a toy truck to Alice.  0.879555  0.120445
16  The actor was rolling a toy truck to the actress.  0.878150  0.121850
17       The boy was rolling a toy truck to the girl.  0.876373  0.123627
18  Mr. William was rolling a toy truck to  Mrs. T...  0.331191  0.668809
19             David was rolling a toy truck to Emma.  0.860638  0.139362
20  The prince was rolling a toy truck to the prin...  0.883579  0.116421
21           Robert was rolling a toy truck to Sarah.  0.417097  0.582903
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.141652  0.858348
23             Paul was rolling a toy truck to Emily.  0.872302  0.127698

In [42]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_5m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_5m,'She'))

P('subj-pron'|subj=male) =  0.7322260228296121
P('non-subj-pron'|subj=male) =  0.2677739653736353

In [43]:
np_average_subj_male_subj_pron['rolling'] = compute_average(transofposs_imperfective_noprompt_5m,'He')
np_average_subj_male_obj_pron['rolling'] = compute_average(transofposs_imperfective_noprompt_5m,'She')

### verb: "throwing"

In [44]:
transofposs_imperfective_noprompt_6 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/6.csv")
transofposs_imperfective_noprompt_6.head()

                                       stimulus        He       She
0   Miss Smith was throwing a hat to Mr. Smith.  0.296905  0.703095
1      The woman was throwing a hat to the man.  0.801047  0.198953
2              Mary was throwing a hat to John.  0.665289  0.334711
3              Alice was throwing a hat to Bob.  0.481251  0.518749
4  The actress was throwing a hat to the actor.  0.820167  0.179833

In [45]:
# female subject
transofposs_imperfective_noprompt_6f = transofposs_imperfective_noprompt_6[0:12]
transofposs_imperfective_noprompt_6f = transofposs_imperfective_noprompt_6f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_6m = transofposs_imperfective_noprompt_6[12:24]

#### female subject

In [46]:
transofposs_imperfective_noprompt_6f

                                            stimulus       She        He
0        Miss Smith was throwing a hat to Mr. Smith.  0.703095  0.296905
1           The woman was throwing a hat to the man.  0.198953  0.801047
2                   Mary was throwing a hat to John.  0.334711  0.665289
3                   Alice was throwing a hat to Bob.  0.518749  0.481251
4       The actress was throwing a hat to the actor.  0.179833  0.820167
5            The girl was throwing a hat to the boy.  0.193993  0.806007
6    Mrs. Taylor was throwing a hat to Mr. Williams.  0.801047  0.198953
7                  Emma was throwing a hat to David.  0.196413  0.803587
8     The princess was throwing a hat to the prince.  0.193371  0.806629
9                Sarah was throwing a hat to Robert.  0.727471  0.272529
10  Mrs. Williams was throwing a hat to  Mr. Taylor.  0.665954  0.334046
11                 Emily was throwing a hat to Paul.  0.729567  0.270433

In [47]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_6f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_6f,'He'))

P('subj-pron'|subj=female) =  0.45359641934434575
P('non-subj-pron'|subj=female) =  0.5464035669962565

In [48]:
np_average_subj_female_subj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6f,'She')
np_average_subj_female_obj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6f,'He')

#### male subject

In [49]:
transofposs_imperfective_noprompt_6m

                                           stimulus        He       She
12      Mr. Smith was throwing a hat to Miss Smith.  0.866797  0.133203
13         The man was throwing a hat to the woman.  0.894515  0.105485
14                 John was throwing a hat to Mary.  0.884402  0.115598
15                 Bob was throwing a hat to Alice.  0.804219  0.195781
16     The actor was throwing a hat to the actress.  0.881376  0.118624
17          The boy was throwing a hat to the girl.  0.884204  0.115796
18  Mr. William was throwing a hat to  Mrs. Taylor.  0.298792  0.701208
19                David was throwing a hat to Emma.  0.104473  0.895526
20   The prince was throwing a hat to the princess.  0.886235  0.113765
21              Robert was throwing a hat to Sarah.  0.194353  0.805647
22  Mr. Taylor was throwing a hat to Mrs. Williams.  0.152224  0.847776
23                Paul was throwing a hat to Emily.  0.867738  0.132262

In [50]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_6m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_6m,'She'))

P('subj-pron'|subj=male) =  0.6432773775110642
P('non-subj-pron'|subj=male) =  0.3567226342856884

In [51]:
np_average_subj_male_subj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6m,'He')
np_average_subj_male_obj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6m,'She')

### verb: "tossing"

In [52]:
transofposs_imperfective_noprompt_7 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/7.csv")
transofposs_imperfective_noprompt_7.head()

                                            stimulus        He       She
0  Miss Smith was tossing a dish towel to Mr. Smith.  0.324171  0.675829
1     The woman was tossing a dish towel to the man.  0.784821  0.215179
2             Mary was tossing a dish towel to John.  0.614993  0.385007
3             Alice was tossing a dish towel to Bob.  0.414469  0.585531
4  The actress was tossing a dish towel to the ac...  0.806188  0.193812

In [53]:
# female subject
transofposs_imperfective_noprompt_7f = transofposs_imperfective_noprompt_7[0:12]
transofposs_imperfective_noprompt_7f = transofposs_imperfective_noprompt_7f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_7m = transofposs_imperfective_noprompt_7[12:24]

#### female subject

In [54]:
transofposs_imperfective_noprompt_7f

                                             stimulus       She        He
0   Miss Smith was tossing a dish towel to Mr. Smith.  0.675829  0.324171
1      The woman was tossing a dish towel to the man.  0.215179  0.784821
2              Mary was tossing a dish towel to John.  0.385007  0.614993
3              Alice was tossing a dish towel to Bob.  0.585531  0.414469
4   The actress was tossing a dish towel to the ac...  0.193812  0.806188
5       The girl was tossing a dish towel to the boy.  0.207850  0.792151
6   Mrs. Taylor was tossing a dish towel to Mr. Wi...  0.793912  0.206088
7             Emma was tossing a dish towel to David.  0.211826  0.788174
8   The princess was tossing a dish towel to the p...  0.210583  0.789417
9           Sarah was tossing a dish towel to Robert.  0.715028  0.284972
10  Mrs. Williams was tossing a dish towel to  Mr....  0.652970  0.347030
11            Emily was tossing a dish towel to Paul.  0.634650  0.365351

In [55]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_7f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_7f,'He'))

P('subj-pron'|subj=female) =  0.45684802159667015
P('non-subj-pron'|subj=female) =  0.5431519982715448

In [56]:
np_average_subj_female_subj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7f,'She')
np_average_subj_female_obj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7f,'He')

#### male subject

In [57]:
transofposs_imperfective_noprompt_7m

                                             stimulus        He       She
12  Mr. Smith was tossing a dish towel to Miss Smith.  0.868646  0.131354
13     The man was tossing a dish towel to the woman.  0.892879  0.107121
14             John was tossing a dish towel to Mary.  0.888178  0.111822
15             Bob was tossing a dish towel to Alice.  0.883630  0.116370
16  The actor was tossing a dish towel to the actr...  0.879233  0.120767
17      The boy was tossing a dish towel to the girl.  0.880236  0.119764
18  Mr. William was tossing a dish towel to  Mrs. ...  0.308500  0.691500
19            David was tossing a dish towel to Emma.  0.086695  0.913305
20  The prince was tossing a dish towel to the pri...  0.882832  0.117168
21          Robert was tossing a dish towel to Sarah.  0.164144  0.835856
22  Mr. Taylor was tossing a dish towel to Mrs. Wi...  0.142706  0.857294
23            Paul was tossing a dish towel to Emily.  0.873864  0.126136

In [58]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_7m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_7m,'She'))

P('subj-pron'|subj=male) =  0.645962011689941
P('non-subj-pron'|subj=male) =  0.3540379808594783

In [59]:
np_average_subj_male_subj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7m,'He')
np_average_subj_male_obj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7m,'She')

### verb: "bringing"

In [60]:
transofposs_imperfective_noprompt_8 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/8.csv")
transofposs_imperfective_noprompt_8.head()

                                            stimulus        He       She
0  Miss Smith was bringing a glass of water to Mr...  0.359178  0.640822
1  The woman was bringing a glass of water to the...  0.778734  0.221266
2        Mary was bringing a glass of water to John.  0.475218  0.524782
3        Alice was bringing a glass of water to Bob.  0.199114  0.800886
4  The actress was bringing a glass of water to t...  0.790319  0.209681

In [61]:
# female subject
transofposs_imperfective_noprompt_8f = transofposs_imperfective_noprompt_8[0:12]
transofposs_imperfective_noprompt_8f = transofposs_imperfective_noprompt_8f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_8m = transofposs_imperfective_noprompt_8[12:24]

#### female subject

In [62]:
transofposs_imperfective_noprompt_8f

                                             stimulus       She        He
0   Miss Smith was bringing a glass of water to Mr...  0.640822  0.359178
1   The woman was bringing a glass of water to the...  0.221266  0.778734
2         Mary was bringing a glass of water to John.  0.524782  0.475218
3         Alice was bringing a glass of water to Bob.  0.800886  0.199114
4   The actress was bringing a glass of water to t...  0.209681  0.790319
5   The girl was bringing a glass of water to the ...  0.218964  0.781036
6   Mrs. Taylor was bringing a glass of water to M...  0.785244  0.214756
7        Emma was bringing a glass of water to David.  0.249493  0.750507
8   The princess was bringing a glass of water to ...  0.223822  0.776178
9      Sarah was bringing a glass of water to Robert.  0.802865  0.197135
10  Mrs. Williams was bringing a glass of water to...  0.658243  0.341757
11       Emily was bringing a glass of water to Paul.  0.821454  0.178546

In [63]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_8f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_8f,'He'))

P('subj-pron'|subj=female) =  0.5131269730627537
P('non-subj-pron'|subj=female) =  0.48687302072842914

In [64]:
np_average_subj_female_subj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8f,'She')
np_average_subj_female_obj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8f,'He')

#### male subject

In [65]:
transofposs_imperfective_noprompt_8m

                                             stimulus        He       She
12  Mr. Smith was bringing a glass of water to Mis...  0.868790  0.131210
13  The man was bringing a glass of water to the w...  0.893275  0.106725
14        John was bringing a glass of water to Mary.  0.884174  0.115826
15        Bob was bringing a glass of water to Alice.  0.880841  0.119159
16  The actor was bringing a glass of water to the...  0.874624  0.125376
17  The boy was bringing a glass of water to the g...  0.880164  0.119836
18  Mr. William was bringing a glass of water to  ...  0.318594  0.681406
19       David was bringing a glass of water to Emma.  0.859358  0.140642
20  The prince was bringing a glass of water to th...  0.882347  0.117653
21     Robert was bringing a glass of water to Sarah.  0.235422  0.764578
22  Mr. Taylor was bringing a glass of water to Mr...  0.151600  0.848400
23       Paul was bringing a glass of water to Emily.  0.872143  0.127857

In [66]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_8m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_8m,'She'))

P('subj-pron'|subj=male) =  0.716777661194404
P('non-subj-pron'|subj=male) =  0.28322232762972516

In [67]:
np_average_subj_male_subj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8m,'He')
np_average_subj_male_obj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8m,'She')

### verb: "forwarding"

In [68]:
transofposs_imperfective_noprompt_9 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/9.csv")
transofposs_imperfective_noprompt_9.head()

                                            stimulus        He       She
0  Miss Smith was forwarding a gossipy email to M...  0.250694  0.749306
1  The woman was forwarding a gossipy email to th...  0.777654  0.222346
2       Mary was forwarding a gossipy email to John.  0.678426  0.321574
3       Alice was forwarding a gossipy email to Bob.  0.371437  0.628563
4  The actress was forwarding a gossipy email to ...  0.792491  0.207509

In [69]:
# female subject
transofposs_imperfective_noprompt_9f = transofposs_imperfective_noprompt_9[0:12]
transofposs_imperfective_noprompt_9f = transofposs_imperfective_noprompt_9f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_9m = transofposs_imperfective_noprompt_9[12:24]

#### female subject

In [70]:
transofposs_imperfective_noprompt_9f

                                             stimulus       She        He
0   Miss Smith was forwarding a gossipy email to M...  0.749306  0.250694
1   The woman was forwarding a gossipy email to th...  0.222346  0.777654
2        Mary was forwarding a gossipy email to John.  0.321574  0.678426
3        Alice was forwarding a gossipy email to Bob.  0.628563  0.371437
4   The actress was forwarding a gossipy email to ...  0.207509  0.792491
5   The girl was forwarding a gossipy email to the...  0.218506  0.781494
6   Mrs. Taylor was forwarding a gossipy email to ...  0.832207  0.167792
7       Emma was forwarding a gossipy email to David.  0.240420  0.759580
8   The princess was forwarding a gossipy email to...  0.226044  0.773956
9     Sarah was forwarding a gossipy email to Robert.  0.738009  0.261991
10  Mrs. Williams was forwarding a gossipy email t...  0.716273  0.283727
11      Emily was forwarding a gossipy email to Paul.  0.718627  0.281373

In [71]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_9f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_9f,'He'))

P('subj-pron'|subj=female) =  0.4849487133324146
P('non-subj-pron'|subj=female) =  0.5150512481729189

In [72]:
np_average_subj_female_subj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9f,'She')
np_average_subj_female_obj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9f,'He')

#### male subject

In [73]:
transofposs_imperfective_noprompt_9m

                                             stimulus        He       She
12  Mr. Smith was forwarding a gossipy email to Mi...  0.862400  0.137600
13  The man was forwarding a gossipy email to the ...  0.888601  0.111399
14       John was forwarding a gossipy email to Mary.  0.879567  0.120433
15       Bob was forwarding a gossipy email to Alice.  0.691949  0.308051
16  The actor was forwarding a gossipy email to th...  0.875216  0.124784
17  The boy was forwarding a gossipy email to the ...  0.874270  0.125730
18  Mr. William was forwarding a gossipy email to ...  0.318090  0.681910
19      David was forwarding a gossipy email to Emma.  0.121530  0.878470
20  The prince was forwarding a gossipy email to t...  0.879310  0.120690
21    Robert was forwarding a gossipy email to Sarah.  0.294858  0.705141
22  Mr. Taylor was forwarding a gossipy email to M...  0.125254  0.874746
23      Paul was forwarding a gossipy email to Emily.  0.852583  0.147417

In [74]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_9m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_9m,'She'))

P('subj-pron'|subj=male) =  0.6386356074362993
P('non-subj-pron'|subj=male) =  0.3613643969098727

In [75]:
np_average_subj_male_subj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9m,'He')
np_average_subj_male_obj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9m,'She')

### verb: "mailing"

In [76]:
transofposs_imperfective_noprompt_10 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/10.csv")
transofposs_imperfective_noprompt_10.head()

                                         stimulus        He       She
0   Miss Smith was mailing a letter to Mr. Smith.  0.110646  0.889354
1      The woman was mailing a letter to the man.  0.788728  0.211272
2              Mary was mailing a letter to John.  0.723896  0.276104
3              Alice was mailing a letter to Bob.  0.463989  0.536011
4  The actress was mailing a letter to the actor.  0.795463  0.204537

In [77]:
# female subject
transofposs_imperfective_noprompt_10f = transofposs_imperfective_noprompt_10[0:12]
transofposs_imperfective_noprompt_10f = transofposs_imperfective_noprompt_10f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_10m = transofposs_imperfective_noprompt_10[12:24]

#### female subject

In [78]:
transofposs_imperfective_noprompt_10f

                                             stimulus       She        He
0       Miss Smith was mailing a letter to Mr. Smith.  0.889354  0.110646
1          The woman was mailing a letter to the man.  0.211272  0.788728
2                  Mary was mailing a letter to John.  0.276104  0.723896
3                  Alice was mailing a letter to Bob.  0.536011  0.463989
4      The actress was mailing a letter to the actor.  0.204537  0.795463
5           The girl was mailing a letter to the boy.  0.213663  0.786337
6   Mrs. Taylor was mailing a letter to Mr. Williams.  0.820008  0.179992
7                 Emma was mailing a letter to David.  0.966623  0.033377
8    The princess was mailing a letter to the prince.  0.225809  0.774190
9               Sarah was mailing a letter to Robert.  0.538010  0.461990
10  Mrs. Williams was mailing a letter to Mr. Taylor.  0.677325  0.322675
11                Emily was mailing a letter to Paul.  0.801596  0.198404

In [79]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_10f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_10f,'He'))

P('subj-pron'|subj=female) =  0.5300260931253433
P('non-subj-pron'|subj=female) =  0.4699739043911298

In [80]:
np_average_subj_female_subj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10f,'She')
np_average_subj_female_obj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10f,'He')

#### male subject

In [81]:
transofposs_imperfective_noprompt_10m

                                             stimulus        He       She
12      Mr. Smith was mailing a letter to Miss Smith.  0.863625  0.136375
13         The man was mailing a letter to the woman.  0.895552  0.104448
14                 John was mailing a letter to Mary.  0.889093  0.110907
15                 Bob was mailing a letter to Alice.  0.567654  0.432346
16     The actor was mailing a letter to the actress.  0.885484  0.114516
17          The boy was mailing a letter to the girl.  0.886176  0.113824
18  Mr. William was mailing a letter to  Mrs. Taylor.  0.453104  0.546896
19                David was mailing a letter to Emma.  0.193750  0.806250
20   The prince was mailing a letter to the princess.  0.890580  0.109420
21              Robert was mailing a letter to Sarah.  0.276121  0.723879
22  Mr. Taylor was mailing a letter to Mrs. Williams.  0.171835  0.828165
23                Paul was mailing a letter to Emily.  0.860054  0.139946

In [82]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_10m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_10m,'She'))

P('subj-pron'|subj=male) =  0.6527522789935271
P('non-subj-pron'|subj=male) =  0.3472477284570535

In [83]:
np_average_subj_male_subj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10m,'He')
np_average_subj_male_obj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10m,'She')

### verb: "shipping"

In [84]:
transofposs_imperfective_noprompt_11 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/11.csv")
transofposs_imperfective_noprompt_11.head()

                                           stimulus        He       She
0   Miss Smith was shipping a package to Mr. Smith.  0.169305  0.830695
1      The woman was shipping a package to the man.  0.787233  0.212767
2              Mary was shipping a package to John.  0.472022  0.527978
3              Alice was shipping a package to Bob.  0.224827  0.775173
4  The actress was shipping a package to the actor.  0.787869  0.212131

In [85]:
# female subject
transofposs_imperfective_noprompt_11f = transofposs_imperfective_noprompt_11[0:12]
transofposs_imperfective_noprompt_11f = transofposs_imperfective_noprompt_11f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_11m = transofposs_imperfective_noprompt_11[12:24]

#### female subject

In [86]:
transofposs_imperfective_noprompt_11f

                                             stimulus       She        He
0     Miss Smith was shipping a package to Mr. Smith.  0.830695  0.169305
1        The woman was shipping a package to the man.  0.212767  0.787233
2                Mary was shipping a package to John.  0.527978  0.472022
3                Alice was shipping a package to Bob.  0.775173  0.224827
4    The actress was shipping a package to the actor.  0.212131  0.787869
5         The girl was shipping a package to the boy.  0.219875  0.780125
6   Mrs. Taylor was shipping a package to Mr. Will...  0.870801  0.129199
7               Emma was shipping a package to David.  0.248924  0.751076
8   The princess was shipping a package to the pri...  0.226815  0.773185
9             Sarah was shipping a package to Robert.  0.833353  0.166647
10  Mrs. Williams was shipping a package to Mr. Ta...  0.751921  0.248079
11              Emily was shipping a package to Paul.  0.825639  0.174361

In [87]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_11f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_11f,'He'))

P('subj-pron'|subj=female) =  0.5446726034084955
P('non-subj-pron'|subj=female) =  0.4553273965915044

In [88]:
np_average_subj_female_subj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11f,'She')
np_average_subj_female_obj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11f,'He')

#### male subject

In [89]:
transofposs_imperfective_noprompt_11m

                                             stimulus        He       She
12    Mr. Smith was shipping a package to Miss Smith.  0.854268  0.145732
13       The man was shipping a package to the woman.  0.887683  0.112317
14               John was shipping a package to Mary.  0.869748  0.130252
15               Bob was shipping a package to Alice.  0.822366  0.177634
16   The actor was shipping a package to the actress.  0.872455  0.127545
17        The boy was shipping a package to the girl.  0.869512  0.130488
18  Mr. William was shipping a package to  Mrs. Ta...  0.362617  0.637383
19              David was shipping a package to Emma.  0.172190  0.827810
20  The prince was shipping a package to the princ...  0.878012  0.121988
21            Robert was shipping a package to Sarah.  0.396643  0.603357
22  Mr. Taylor was shipping a package to Mrs. Will...  0.129308  0.870692
23              Paul was shipping a package to Emily.  0.842421  0.157579

In [90]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_11m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_11m,'She'))

P('subj-pron'|subj=male) =  0.6631020046770573
P('non-subj-pron'|subj=male) =  0.3368979940811793

In [91]:
np_average_subj_male_subj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11m,'He')
np_average_subj_male_obj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11m,'She')

### verb: "transmitting"

In [92]:
transofposs_imperfective_noprompt_12 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/12.csv")
transofposs_imperfective_noprompt_12.head()

                                            stimulus        He       She
0  Miss Smith was transmitting a message to Mr. S...  0.197604  0.802396
1   The woman was transmitting a message to the man.  0.791977  0.208023
2           Mary was transmitting a message to John.  0.734911  0.265089
3           Alice was transmitting a message to Bob.  0.503348  0.496652
4  The actress was transmitting a message to the ...  0.811587  0.188413

In [93]:
# female subject
transofposs_imperfective_noprompt_12f = transofposs_imperfective_noprompt_12[0:12]
transofposs_imperfective_noprompt_12f = transofposs_imperfective_noprompt_12f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_12m = transofposs_imperfective_noprompt_12[12:24]

#### female subject

In [94]:
transofposs_imperfective_noprompt_12f

                                             stimulus       She        He
0   Miss Smith was transmitting a message to Mr. S...  0.802396  0.197604
1    The woman was transmitting a message to the man.  0.208023  0.791977
2            Mary was transmitting a message to John.  0.265089  0.734911
3            Alice was transmitting a message to Bob.  0.496652  0.503348
4   The actress was transmitting a message to the ...  0.188413  0.811587
5     The girl was transmitting a message to the boy.  0.206142  0.793858
6   Mrs. Taylor was transmitting a message to Mr. ...  0.812961  0.187039
7           Emma was transmitting a message to David.  0.954391  0.045609
8   The princess was transmitting a message to the...  0.210431  0.789569
9         Sarah was transmitting a message to Robert.  0.538066  0.461933
10  Mrs. Williams was transmitting a message to Mr...  0.743866  0.256134
11          Emily was transmitting a message to Paul.  0.591009  0.408991

In [95]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_12f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_12f,'He'))

P('subj-pron'|subj=female) =  0.5014531972507635
P('non-subj-pron'|subj=female) =  0.49854679343601066

In [96]:
np_average_subj_female_subj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12f,'She')
np_average_subj_female_obj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12f,'He')

#### male subject

In [97]:
transofposs_imperfective_noprompt_12m

                                             stimulus        He       She
12  Mr. Smith was transmitting a message to Miss S...  0.858204  0.141796
13   The man was transmitting a message to the woman.  0.893577  0.106423
14           John was transmitting a message to Mary.  0.881776  0.118224
15           Bob was transmitting a message to Alice.  0.388745  0.611255
16  The actor was transmitting a message to the ac...  0.882948  0.117052
17    The boy was transmitting a message to the girl.  0.881354  0.118646
18  Mr. William was transmitting a message to  Mrs...  0.352708  0.647292
19          David was transmitting a message to Emma.  0.038923  0.961077
20  The prince was transmitting a message to the p...  0.886680  0.113320
21        Robert was transmitting a message to Sarah.  0.117074  0.882926
22  Mr. Taylor was transmitting a message to Mrs. ...  0.124011  0.875989
23          Paul was transmitting a message to Emily.  0.855377  0.144623

In [98]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_12m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_12m,'She'))

P('subj-pron'|subj=male) =  0.5967813885460297
P('non-subj-pron'|subj=male) =  0.4032186058660348

In [99]:
np_average_subj_male_subj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12m,'He')
np_average_subj_male_obj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12m,'She')

### verb: "wiring"

In [100]:
transofposs_imperfective_noprompt_14 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/14.csv")
transofposs_imperfective_noprompt_14.head()

                                     stimulus        He       She
0   Miss Smith was wiring money to Mr. Smith.  0.220849  0.779151
1      The woman was wiring money to the man.  0.821409  0.178591
2              Mary was wiring money to John.  0.732718  0.267282
3              Alice was wiring money to Bob.  0.637404  0.362596
4  The actress was wiring money to the actor.  0.836665  0.163335

In [101]:
# female subject
transofposs_imperfective_noprompt_14f = transofposs_imperfective_noprompt_14[0:12]
transofposs_imperfective_noprompt_14f = transofposs_imperfective_noprompt_14f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_14m = transofposs_imperfective_noprompt_14[12:24]

#### female subject

In [102]:
transofposs_imperfective_noprompt_14f

                                         stimulus       She        He
0       Miss Smith was wiring money to Mr. Smith.  0.779151  0.220849
1          The woman was wiring money to the man.  0.178591  0.821409
2                  Mary was wiring money to John.  0.267282  0.732718
3                  Alice was wiring money to Bob.  0.362596  0.637404
4      The actress was wiring money to the actor.  0.163335  0.836665
5           The girl was wiring money to the boy.  0.173584  0.826416
6   Mrs. Taylor was wiring money to Mr. Williams.  0.838406  0.161594
7                 Emma was wiring money to David.  0.201452  0.798548
8    The princess was wiring money to the prince.  0.172917  0.827083
9               Sarah was wiring money to Robert.  0.482585  0.517415
10  Mrs. Williams was wiring money to Mr. Taylor.  0.699850  0.300150
11                Emily was wiring money to Paul.  0.641759  0.358241

In [103]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_14f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_14f,'He'))

P('subj-pron'|subj=female) =  0.4134589632352193
P('non-subj-pron'|subj=female) =  0.5865410131712755

In [104]:
np_average_subj_female_subj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14f,'She')
np_average_subj_female_obj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14f,'He')

#### male subject

In [105]:
transofposs_imperfective_noprompt_14m

                                         stimulus        He       She
12      Mr. Smith was wiring money to Miss Smith.  0.871786  0.128214
13         The man was wiring money to the woman.  0.896040  0.103960
14                 John was wiring money to Mary.  0.881247  0.118753
15                 Bob was wiring money to Alice.  0.499608  0.500392
16     The actor was wiring money to the actress.  0.886010  0.113990
17          The boy was wiring money to the girl.  0.888383  0.111617
18  Mr. William was wiring money to  Mrs. Taylor.  0.349204  0.650796
19                David was wiring money to Emma.  0.076118  0.923882
20   The prince was wiring money to the princess.  0.893291  0.106709
21              Robert was wiring money to Sarah.  0.268064  0.731936
22  Mr. Taylor was wiring money to Mrs. Williams.  0.124690  0.875310
23                Paul was wiring money to Emily.  0.859405  0.140595

In [106]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_14m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_14m,'She'))

P('subj-pron'|subj=male) =  0.6244871163119873
P('non-subj-pron'|subj=male) =  0.37551288058360416

In [107]:
np_average_subj_male_subj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14m,'He')
np_average_subj_male_obj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14m,'She')

### verb: "carrying"

In [108]:
transofposs_imperfective_noprompt_15 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/15.csv")
transofposs_imperfective_noprompt_15.head()

                                        stimulus        He       She
0   Miss Smith was carrying a tray to Mr. Smith.  0.244565  0.755435
1      The woman was carrying a tray to the man.  0.797514  0.202486
2              Mary was carrying a tray to John.  0.584493  0.415507
3              Alice was carrying a tray to Bob.  0.212993  0.787007
4  The actress was carrying a tray to the actor.  0.814380  0.185620

In [109]:
# female subject
transofposs_imperfective_noprompt_15f = transofposs_imperfective_noprompt_15[0:12]
transofposs_imperfective_noprompt_15f = transofposs_imperfective_noprompt_15f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_15m = transofposs_imperfective_noprompt_15[12:24]

#### female subject

In [110]:
transofposs_imperfective_noprompt_15f

                                            stimulus       She        He
0       Miss Smith was carrying a tray to Mr. Smith.  0.755435  0.244565
1          The woman was carrying a tray to the man.  0.202486  0.797514
2                  Mary was carrying a tray to John.  0.415507  0.584493
3                  Alice was carrying a tray to Bob.  0.787007  0.212993
4      The actress was carrying a tray to the actor.  0.185620  0.814380
5           The girl was carrying a tray to the boy.  0.200209  0.799791
6   Mrs. Taylor was carrying a tray to Mr. Williams.  0.836871  0.163129
7                 Emma was carrying a tray to David.  0.206444  0.793556
8    The princess was carrying a tray to the prince.  0.200679  0.799321
9               Sarah was carrying a tray to Robert.  0.735020  0.264980
10  Mrs. Williams was carrying a tray to Mr. Taylor.  0.728099  0.271901
11                Emily was carrying a tray to Paul.  0.756112  0.243888

In [111]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_15f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_15f,'He'))

P('subj-pron'|subj=female) =  0.5007905500630537
P('non-subj-pron'|subj=female) =  0.4992094362775485

In [112]:
np_average_subj_female_subj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15f,'She')
np_average_subj_female_obj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15f,'He')

#### male subject

In [113]:
transofposs_imperfective_noprompt_15m

                                            stimulus        He       She
12      Mr. Smith was carrying a tray to Miss Smith.  0.867984  0.132016
13         The man was carrying a tray to the woman.  0.896167  0.103832
14                 John was carrying a tray to Mary.  0.885734  0.114266
15                 Bob was carrying a tray to Alice.  0.877913  0.122087
16     The actor was carrying a tray to the actress.  0.881501  0.118498
17          The boy was carrying a tray to the girl.  0.883460  0.116540
18  Mr. William was carrying a tray to  Mrs. Taylor.  0.366731  0.633269
19                David was carrying a tray to Emma.  0.155120  0.844880
20   The prince was carrying a tray to the princess.  0.887331  0.112669
21              Robert was carrying a tray to Sarah.  0.422960  0.577040
22  Mr. Taylor was carrying a tray to Mrs. Williams.  0.193080  0.806920
23                Paul was carrying a tray to Emily.  0.863317  0.136683

In [114]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_15m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_15m,'She'))

P('subj-pron'|subj=male) =  0.6817748385171095
P('non-subj-pron'|subj=male) =  0.31822515775760013

In [115]:
np_average_subj_male_subj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15m,'He')
np_average_subj_male_obj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15m,'She')

### verb: "delivering"

In [116]:
transofposs_imperfective_noprompt_16 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/16.csv")
transofposs_imperfective_noprompt_16.head()

                                            stimulus        He       She
0  Miss Smith was delivering a subpoena to Mr. Sm...  0.240313  0.759687
1    The woman was delivering a subpoena to the man.  0.805776  0.194224
2            Mary was delivering a subpoena to John.  0.788668  0.211332
3            Alice was delivering a subpoena to Bob.  0.579631  0.420369
4  The actress was delivering a subpoena to the a...  0.813288  0.186712

In [117]:
# female subject
transofposs_imperfective_noprompt_16f = transofposs_imperfective_noprompt_16[0:12]
transofposs_imperfective_noprompt_16f = transofposs_imperfective_noprompt_16f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_16m = transofposs_imperfective_noprompt_16[12:24]

#### female subject

In [118]:
transofposs_imperfective_noprompt_16f

                                             stimulus       She        He
0   Miss Smith was delivering a subpoena to Mr. Sm...  0.759687  0.240313
1     The woman was delivering a subpoena to the man.  0.194224  0.805776
2             Mary was delivering a subpoena to John.  0.211332  0.788668
3             Alice was delivering a subpoena to Bob.  0.420369  0.579631
4   The actress was delivering a subpoena to the a...  0.186712  0.813288
5      The girl was delivering a subpoena to the boy.  0.192541  0.807459
6   Mrs. Taylor was delivering a subpoena to Mr. W...  0.814918  0.185082
7            Emma was delivering a subpoena to David.  0.960250  0.039750
8   The princess was delivering a subpoena to the ...  0.194307  0.805693
9          Sarah was delivering a subpoena to Robert.  0.439079  0.560921
10  Mrs. Williams was delivering a subpoena to Mr....  0.734380  0.265620
11           Emily was delivering a subpoena to Paul.  0.747815  0.252185

In [119]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_16f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_16f,'He'))

P('subj-pron'|subj=female) =  0.4879679021735986
P('non-subj-pron'|subj=female) =  0.5120320984472831

In [120]:
np_average_subj_female_subj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16f,'She')
np_average_subj_female_obj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16f,'He')

#### male subject

In [121]:
transofposs_imperfective_noprompt_16m

                                             stimulus        He       She
12  Mr. Smith was delivering a subpoena to Miss Sm...  0.865098  0.134902
13    The man was delivering a subpoena to the woman.  0.894483  0.105517
14            John was delivering a subpoena to Mary.  0.888155  0.111845
15            Bob was delivering a subpoena to Alice.  0.274380  0.725620
16  The actor was delivering a subpoena to the act...  0.881700  0.118300
17     The boy was delivering a subpoena to the girl.  0.883012  0.116988
18  Mr. William was delivering a subpoena to Mrs. ...  0.313301  0.686699
19           David was delivering a subpoena to Emma.  0.042293  0.957707
20  The prince was delivering a subpoena to the pr...  0.887219  0.112781
21         Robert was delivering a subpoena to Sarah.  0.198145  0.801855
22  Mr. Taylor was delivering a subpoena to Mrs. W...  0.124019  0.875981
23           Paul was delivering a subpoena to Emily.  0.856193  0.143807

In [122]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_16m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_16m,'She'))

P('subj-pron'|subj=male) =  0.5923331870386997
P('non-subj-pron'|subj=male) =  0.4076668042689562

In [123]:
np_average_subj_male_subj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16m,'He')
np_average_subj_male_obj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16m,'She')

### verb: "giving"

In [124]:
transofposs_imperfective_noprompt_17 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/17.csv")
transofposs_imperfective_noprompt_17.head()

                                         stimulus        He       She
0   Miss Smith was giving a sweater to Mr. Smith.  0.205334  0.794666
1      The woman was giving a sweater to the man.  0.802258  0.197742
2              Mary was giving a sweater to John.  0.529525  0.470475
3              Alice was giving a sweater to Bob.  0.473553  0.526447
4  The actress was giving a sweater to the actor.  0.811442  0.188558

In [125]:
# female subject
transofposs_imperfective_noprompt_17f = transofposs_imperfective_noprompt_17[0:12]
transofposs_imperfective_noprompt_17f = transofposs_imperfective_noprompt_17f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_17m = transofposs_imperfective_noprompt_17[12:24]

#### female subject

In [126]:
transofposs_imperfective_noprompt_17f

                                             stimulus       She        He
0       Miss Smith was giving a sweater to Mr. Smith.  0.794666  0.205334
1          The woman was giving a sweater to the man.  0.197742  0.802258
2                  Mary was giving a sweater to John.  0.470475  0.529525
3                  Alice was giving a sweater to Bob.  0.526447  0.473553
4      The actress was giving a sweater to the actor.  0.188558  0.811442
5           The girl was giving a sweater to the boy.  0.201141  0.798859
6   Mrs. Taylor was giving a sweater to Mr. Williams.  0.840029  0.159971
7                 Emma was giving a sweater to David.  0.939432  0.060568
8    The princess was giving a sweater to the prince.  0.201603  0.798397
9               Sarah was giving a sweater to Robert.  0.755106  0.244894
10  Mrs. Williams was giving a sweater to Mr. Taylor.  0.748298  0.251702
11                Emily was giving a sweater to Paul.  0.770350  0.229650

In [127]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_17f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_17f,'He'))

P('subj-pron'|subj=female) =  0.5528206105033556
P('non-subj-pron'|subj=female) =  0.44717938515047234

In [128]:
np_average_subj_female_subj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17f,'She')
np_average_subj_female_obj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17f,'He')

#### female subject

In [129]:
transofposs_imperfective_noprompt_17m

                                             stimulus        He       She
12      Mr. Smith was giving a sweater to Miss Smith.  0.659102  0.340898
13         The man was giving a sweater to the woman.  0.897739  0.102261
14                 John was giving a sweater to Mary.  0.886948  0.113052
15                 Bob was giving a sweater to Alice.  0.537455  0.462545
16     The actor was giving a sweater to the actress.  0.882315  0.117685
17          The boy was giving a sweater to the girl.  0.888059  0.111941
18  Mr. William was giving a sweater to  Mrs. Taylor.  0.370896  0.629103
19                David was giving a sweater to Emma.  0.072193  0.927807
20   The prince was giving a sweater to the princess.  0.888503  0.111497
21              Robert was giving a sweater to Sarah.  0.183962  0.816038
22  Mr. Taylor was giving a sweater to Mrs. Williams.  0.156157  0.843843
23                Paul was giving a sweater to Emily.  0.869891  0.130109

In [130]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_17m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_17m,'She'))

P('subj-pron'|subj=male) =  0.6077683152010044
P('non-subj-pron'|subj=male) =  0.3922316947331031

In [131]:
np_average_subj_male_subj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17m,'He')
np_average_subj_male_obj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17m,'She')

### verb: "handing"

In [132]:
transofposs_imperfective_noprompt_18 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/18.csv")
transofposs_imperfective_noprompt_18.head()

                                       stimulus        He       She
0   Miss Smith was handing a book to Mr. Smith.  0.177636  0.822364
1      The woman was handing a book to the man.  0.799267  0.200733
2              Mary was handing a book to John.  0.661151  0.338849
3              Alice was handing a book to Bob.  0.512752  0.487248
4  The actress was handing a book to the actor.  0.810343  0.189657

In [133]:
# female subject
transofposs_imperfective_noprompt_18f = transofposs_imperfective_noprompt_18[0:12]
transofposs_imperfective_noprompt_18f = transofposs_imperfective_noprompt_18f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_18m = transofposs_imperfective_noprompt_18[12:24]

#### female subject

In [134]:
transofposs_imperfective_noprompt_18f

                                           stimulus       She        He
0       Miss Smith was handing a book to Mr. Smith.  0.822364  0.177636
1          The woman was handing a book to the man.  0.200733  0.799267
2                  Mary was handing a book to John.  0.338849  0.661151
3                  Alice was handing a book to Bob.  0.487248  0.512752
4      The actress was handing a book to the actor.  0.189657  0.810343
5           The girl was handing a book to the boy.  0.199192  0.800808
6   Mrs. Taylor was handing a book to Mr. Williams.  0.847563  0.152437
7                 Emma was handing a book to David.  0.216984  0.783016
8    The princess was handing a book to the prince.  0.200460  0.799540
9               Sarah was handing a book to Robert.  0.663050  0.336950
10  Mrs. Williams was handing a book to Mr. Taylor.  0.761877  0.238122
11                Emily was handing a book to Paul.  0.725833  0.274167

In [135]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_18f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_18f,'He'))

P('subj-pron'|subj=female) =  0.47115092476209003
P('non-subj-pron'|subj=female) =  0.5288490553696951

In [136]:
np_average_subj_female_subj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18f,'She')
np_average_subj_female_obj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18f,'He')

#### male subject

In [137]:
transofposs_imperfective_noprompt_18m

                                           stimulus        He       She
12      Mr. Smith was handing a book to Miss Smith.  0.861383  0.138617
13         The man was handing a book to the woman.  0.895005  0.104995
14                 John was handing a book to Mary.  0.882640  0.117360
15                 Bob was handing a book to Alice.  0.245047  0.754953
16     The actor was handing a book to the actress.  0.880154  0.119846
17          The boy was handing a book to the girl.  0.882914  0.117086
18   Mr. William was handing a book to Mrs. Taylor.  0.255980  0.744020
19                David was handing a book to Emma.  0.026509  0.973491
20   The prince was handing a book to the princess.  0.886268  0.113732
21              Robert was handing a book to Sarah.  0.127249  0.872751
22  Mr. Taylor was handing a book to Mrs. Williams.  0.120603  0.879397
23                Paul was handing a book to Emily.  0.866737  0.133263

In [138]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_18m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_18m,'She'))

P('subj-pron'|subj=male) =  0.5775409275665879
P('non-subj-pron'|subj=male) =  0.4224590777109067

In [139]:
np_average_subj_male_subj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18m,'He')
np_average_subj_male_obj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18m,'She')

### verb: "passing"

In [140]:
transofposs_imperfective_noprompt_19 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/19.csv")
transofposs_imperfective_noprompt_19.head()

                                           stimulus        He       She
0   Miss Smith was passing a sandwich to Mr. Smith.  0.321770  0.678230
1      The woman was passing a sandwich to the man.  0.794473  0.205527
2              Mary was passing a sandwich to John.  0.643495  0.356505
3              Alice was passing a sandwich to Bob.  0.416686  0.583314
4  The actress was passing a sandwich to the actor.  0.810340  0.189660

In [141]:
# female subject
transofposs_imperfective_noprompt_19f = transofposs_imperfective_noprompt_19[0:12]
transofposs_imperfective_noprompt_19f = transofposs_imperfective_noprompt_19f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_19m = transofposs_imperfective_noprompt_19[12:24]

#### female subject

In [142]:
transofposs_imperfective_noprompt_19f

                                             stimulus       She        He
0     Miss Smith was passing a sandwich to Mr. Smith.  0.678230  0.321770
1        The woman was passing a sandwich to the man.  0.205527  0.794473
2                Mary was passing a sandwich to John.  0.356505  0.643495
3                Alice was passing a sandwich to Bob.  0.583314  0.416686
4    The actress was passing a sandwich to the actor.  0.189660  0.810340
5         The girl was passing a sandwich to the boy.  0.202623  0.797377
6   Mrs. Taylor was passing a sandwich to Mr. Will...  0.773793  0.226207
7               Emma was passing a sandwich to David.  0.211937  0.788063
8   The princess was passing a sandwich to the pri...  0.204170  0.795830
9             Sarah was passing a sandwich to Robert.  0.761773  0.238227
10  Mrs. Williams was passing a sandwich to  Mr. T...  0.666431  0.333569
11              Emily was passing a sandwich to Paul.  0.675147  0.324853

In [143]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_19f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_19f,'He'))

P('subj-pron'|subj=female) =  0.45909259095788
P('non-subj-pron'|subj=female) =  0.5409073928991953

In [144]:
np_average_subj_female_subj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19f,'She')
np_average_subj_female_obj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19f,'He')

#### male subject

In [145]:
transofposs_imperfective_noprompt_19m

                                             stimulus        He       She
12    Mr. Smith was passing a sandwich to Miss Smith.  0.866041  0.133959
13       The man was passing a sandwich to the woman.  0.895963  0.104037
14               John was passing a sandwich to Mary.  0.886278  0.113722
15               Bob was passing a sandwich to Alice.  0.448835  0.551165
16   The actor was passing a sandwich to the actress.  0.888263  0.111737
17        The boy was passing a sandwich to the girl.  0.886622  0.113378
18  Mr. William was passing a sandwich to  Mrs. Ta...  0.378023  0.621977
19              David was passing a sandwich to Emma.  0.073266  0.926733
20  The prince was passing a sandwich to the princ...  0.888653  0.111347
21            Robert was passing a sandwich to Sarah.  0.224478  0.775522
22  Mr. Taylor was passing a sandwich to Mrs. Will...  0.174612  0.825388
23              Paul was passing a sandwich to Emily.  0.871346  0.128654

In [146]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_19m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_19m,'She'))

P('subj-pron'|subj=male) =  0.623531727741162
P('non-subj-pron'|subj=male) =  0.3764682908852895

In [147]:
np_average_subj_male_subj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19m,'He')
np_average_subj_male_obj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19m,'She')

### verb: "serving"

In [148]:
transofposs_imperfective_noprompt_20 = pd.read_csv("../results/transfoxl/transofposs_imperfective/no-prompt/20.csv")
transofposs_imperfective_noprompt_20.head()

                                        stimulus        He       She
0   Miss Smith was serving a chili to Mr. Smith.  0.327562  0.672438
1      The woman was serving a chili to the man.  0.798444  0.201556
2              Mary was serving a chili to John.  0.524534  0.475467
3              Alice was serving a chili to Bob.  0.136649  0.863351
4  The actress was serving a chili to the actor.  0.811954  0.188046

In [149]:
# female subject
transofposs_imperfective_noprompt_20f = transofposs_imperfective_noprompt_20[0:12]
transofposs_imperfective_noprompt_20f = transofposs_imperfective_noprompt_20f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_20m = transofposs_imperfective_noprompt_20[12:24]

#### female subject

In [150]:
transofposs_imperfective_noprompt_20f

                                            stimulus       She        He
0       Miss Smith was serving a chili to Mr. Smith.  0.672438  0.327562
1          The woman was serving a chili to the man.  0.201556  0.798444
2                  Mary was serving a chili to John.  0.475467  0.524534
3                  Alice was serving a chili to Bob.  0.863351  0.136649
4      The actress was serving a chili to the actor.  0.188046  0.811954
5           The girl was serving a chili to the boy.  0.201200  0.798800
6   Mrs. Taylor was serving a chili to Mr. Williams.  0.850310  0.149690
7                 Emma was serving a chili to David.  0.195675  0.804325
8    The princess was serving a chili to the prince.  0.202799  0.797201
9               Sarah was serving a chili to Robert.  0.905427  0.094573
10  Mrs. Williams was serving a chili to Mr. Taylor.  0.741193  0.258807
11                Emily was serving a chili to Paul.  0.900160  0.099840

In [151]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_20f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_20f,'He'))

P('subj-pron'|subj=female) =  0.5331350279351076
P('non-subj-pron'|subj=female) =  0.4668649851034085

In [152]:
np_average_subj_female_subj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20f,'She')
np_average_subj_female_obj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20f,'He')

#### male subject

In [153]:
transofposs_imperfective_noprompt_20m

                                            stimulus        He       She
12      Mr. Smith was serving a chili to Miss Smith.  0.871075  0.128925
13         The man was serving a chili to the woman.  0.896186  0.103814
14                 John was serving a chili to Mary.  0.889570  0.110430
15                 Bob was serving a chili to Alice.  0.881771  0.118229
16     The actor was serving a chili to the actress.  0.878630  0.121370
17          The boy was serving a chili to the girl.  0.884359  0.115641
18  Mr. William was serving a chili to  Mrs. Taylor.  0.497164  0.502835
19                David was serving a chili to Emma.  0.388659  0.611341
20   The prince was serving a chili to the princess.  0.889191  0.110809
21              Robert was serving a chili to Sarah.  0.475949  0.524050
22  Mr. Taylor was serving a chili to Mrs. Williams.  0.226363  0.773637
23                Paul was serving a chili to Emily.  0.868734  0.131266

In [154]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_20m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_20m,'She'))

P('subj-pron'|subj=male) =  0.7206376840670904
P('non-subj-pron'|subj=male) =  0.27936231593290967

In [155]:
np_average_subj_male_subj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20m,'He')
np_average_subj_male_obj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20m,'She')

## Summary of Results

In [156]:
np_results_fsubj_subjpron = pd.DataFrame(list(np_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
np_results_fsubj_objpron = pd.DataFrame(list(np_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
np_results_fsubj = np_results_fsubj_subjpron.merge(np_results_fsubj_objpron)
np_results_fsubj

            verb  subj_ref_female_subj  obj_ref_female_subj
0       flinging              0.421247             0.578753
1        kicking              0.469699             0.530301
2        lobbing              0.563271             0.436729
3       throwing              0.453596             0.546404
4        tossing              0.456848             0.543152
5       bringing              0.513127             0.486873
6     forwarding              0.484949             0.515051
7        mailing              0.530026             0.469974
8       shipping              0.544673             0.455327
9   transmitting              0.501453             0.498547
10        wiring              0.413459             0.586541
11      carrying              0.500791             0.499209
12    delivering              0.487968             0.512032
13        giving              0.552821             0.447179
14       handing              0.471151             0.528849
15       passing              0.459093             0.540907
16       serving              0.533135             0.466865

In [157]:
np_results_msubj_subjpron = pd.DataFrame(list(np_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
np_results_msubj_objpron = pd.DataFrame(list(np_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
np_results_msubj = np_results_msubj_subjpron.merge(np_results_msubj_objpron)
np_results_msubj

            verb  subj_ref_male_subj  obj_ref_male_subj
0       flinging            0.651160           0.348840
1        kicking            0.722319           0.277681
2        lobbing            0.666902           0.333098
3        rolling            0.732226           0.267774
4       throwing            0.643277           0.356723
5        tossing            0.645962           0.354038
6       bringing            0.716778           0.283222
7     forwarding            0.638636           0.361364
8        mailing            0.652752           0.347248
9       shipping            0.663102           0.336898
10  transmitting            0.596781           0.403219
11        wiring            0.624487           0.375513
12      carrying            0.681775           0.318225
13    delivering            0.592333           0.407667
14        giving            0.607768           0.392232
15       handing            0.577541           0.422459
16       passing            0.623532           0.376468
17       serving            0.720638           0.279362

In [158]:
np_results = np_results_fsubj.merge(np_results_msubj)
np_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flinging,0.421247,0.578753,0.651160,0.348840
1,kicking,0.469699,0.530301,0.722319,0.277681
2,lobbing,0.563271,0.436729,0.666902,0.333098
3,throwing,0.453596,0.546404,0.643277,0.356723
4,tossing,0.456848,0.543152,0.645962,0.354038
5,bringing,0.513127,0.486873,0.716778,0.283222
6,forwarding,0.484949,0.515051,0.638636,0.361364
7,mailing,0.530026,0.469974,0.652752,0.347248
8,shipping,0.544673,0.455327,0.663102,0.336898
9,transmitting,0.501453,0.498547,0.596781,0.403219
10,wiring,0.413459,0.586541,0.624487,0.375513
11,carrying,0.500791,0.499209,0.681775,0.318225
12,delivering,0.487968,0.512032,0.592333,0.407667
13,giving,0.552821,0.447179,0.607768,0.392232
14,handing,0.471151,0.528849,0.577541,0.422459
15,passing,0.459093,0.540907,0.623532,0.376468
16,serving,0.533135,0.466865,0.720638,0.279362

In [159]:
print("P(subj_reference |subj=female)", compute_average(np_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(np_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.491606244561719
P(obj_reference |subj=female) 0.5083937490103292

In [160]:
print("P(subj_reference |subj=male)", compute_average(np_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(np_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.6485730963485206
P(obj_reference |subj=male) 0.351426904984549

## Connective: "because"

In [161]:
c1_average_subj_female_subj_pron = {}
c1_average_subj_female_obj_pron = {}
c1_average_subj_male_subj_pron = {}
c1_average_subj_male_obj_pron = {}

### verb: "chucking"

In [162]:
transofposs_imperfective_connective1_1 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/1.csv")
transofposs_imperfective_connective1_1.head()

                                            stimulus        he       she
0  Miss Smith was chucking a wrench to Mr. Smith ...  0.064254  0.935746
1  The woman was chucking a wrench to the man bec...  0.479018  0.520982
2         Mary was chucking a wrench to John because  0.342780  0.657220
3         Alice was chucking a wrench to Bob because  0.346821  0.653179
4  The actress was chucking a wrench to the actor...  0.307212  0.692788

In [163]:
# female subject
transofposs_imperfective_connective1_1f = transofposs_imperfective_connective1_1[0:12]
transofposs_imperfective_connective1_1f = transofposs_imperfective_connective1_1f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_1m = transofposs_imperfective_connective1_1[12:24]

#### female subject

In [164]:
transofposs_imperfective_connective1_1f

                                             stimulus       she        he
0   Miss Smith was chucking a wrench to Mr. Smith ...  0.935746  0.064254
1   The woman was chucking a wrench to the man bec...  0.520982  0.479018
2          Mary was chucking a wrench to John because  0.657220  0.342780
3          Alice was chucking a wrench to Bob because  0.653179  0.346821
4   The actress was chucking a wrench to the actor...  0.692788  0.307212
5   The girl was chucking a wrench to the boy because  0.632969  0.367031
6   Mrs. Taylor was chucking a wrench to Mr. Willi...  0.693526  0.306474
7         Emma was chucking a wrench to David because  0.680918  0.319082
8   The princess was chucking a wrench to the prin...  0.590295  0.409705
9       Sarah was chucking a wrench to Robert because  0.687382  0.312618
10  Mrs. Williams was chucking a wrench to  Mr. Ta...  0.690035  0.309965
11        Emily was chucking a wrench to Paul because  0.567697  0.432303

In [165]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_1f,'he'))

P('subj-pron'|subj=female) =  0.6668947637081146
P('non-subj-pron'|subj=female) =  0.33310521580278873

In [166]:
c1_average_subj_female_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1f,'she')
c1_average_subj_female_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1f,'he')

#### male subject

In [167]:
transofposs_imperfective_connective1_1m

                                             stimulus        he       she
12  Mr. Smith was chucking a wrench to Miss Smith ...  0.538338  0.461662
13  The man was chucking a wrench to the woman bec...  0.454791  0.545209
14         John was chucking a wrench to Mary because  0.524644  0.475356
15         Bob was chucking a wrench to Alice because  0.330546  0.669454
16  The actor was chucking a wrench to the actress...  0.232030  0.767970
17  The boy was chucking a wrench to the girl because  0.470177  0.529823
18  Mr. William was chucking a wrench to  Mrs. Tay...  0.391941  0.608059
19        David was chucking a wrench to Emma because  0.378682  0.621318
20  The prince was chucking a wrench to the prince...  0.491303  0.508697
21      Robert was chucking a wrench to Sarah because  0.230464  0.769535
22  Mr. Taylor was chucking a wrench to Mrs. Willi...  0.294820  0.705180
23        Paul was chucking a wrench to Emily because  0.353942  0.646058

In [168]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_1m,'she'))

P('subj-pron'|subj=male) =  0.39097324137886363
P('non-subj-pron'|subj=male) =  0.6090267598628998

In [169]:
c1_average_subj_male_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1m,'he')
c1_average_subj_male_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1m,'she')

### verb: "flinging"

In [170]:
transofposs_imperfective_connective1_2 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/2.csv")
transofposs_imperfective_connective1_2.head()

                                            stimulus        he       she
0  Miss Smith was flinging a frisbee to Mr. Smith...  0.063868  0.936132
1  The woman was flinging a frisbee to the man be...  0.519827  0.480174
2        Mary was flinging a frisbee to John because  0.388026  0.611974
3        Alice was flinging a frisbee to Bob because  0.338188  0.661812
4  The actress was flinging a frisbee to the acto...  0.334299  0.665701

In [171]:
# female subject
transofposs_imperfective_connective1_2f = transofposs_imperfective_connective1_2[0:12]
transofposs_imperfective_connective1_2f = transofposs_imperfective_connective1_2f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_2m = transofposs_imperfective_connective1_2[12:24]

#### female subject

In [172]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_2f,'he'))

P('subj-pron'|subj=female) =  0.6517020364602407
P('non-subj-pron'|subj=female) =  0.3482979914794366

In [173]:
c1_average_subj_female_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2f,'she')
c1_average_subj_female_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2f,'he')

#### male subject

In [174]:
transofposs_imperfective_connective1_2m

                                             stimulus        he       she
12  Mr. Smith was flinging a frisbee to Miss Smith...  0.589898  0.410102
13  The man was flinging a frisbee to the woman be...  0.484296  0.515705
14        John was flinging a frisbee to Mary because  0.617278  0.382722
15        Bob was flinging a frisbee to Alice because  0.337192  0.662808
16  The actor was flinging a frisbee to the actres...  0.227188  0.772812
17  The boy was flinging a frisbee to the girl bec...  0.518403  0.481597
18  Mr. William was flinging a frisbee to  Mrs. Ta...  0.392811  0.607189
19       David was flinging a frisbee to Emma because  0.398809  0.601191
20  The prince was flinging a frisbee to the princ...  0.566817  0.433183
21     Robert was flinging a frisbee to Sarah because  0.205356  0.794644
22  Mr. Taylor was flinging a frisbee to Mrs. Will...  0.285047  0.714953
23       Paul was flinging a frisbee to Emily because  0.347576  0.652424

In [175]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_2m,'she'))

P('subj-pron'|subj=male) =  0.41422266761461896
P('non-subj-pron'|subj=male) =  0.5857773497700691

In [176]:
c1_average_subj_male_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2m,'he')
c1_average_subj_male_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2m,'she')

### verb: "kicking"

In [177]:
transofposs_imperfective_connective1_3 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/3.csv")
transofposs_imperfective_connective1_3.head()

                                            stimulus        he       she
0  Miss Smith was kicking a soccer ball to Mr. Sm...  0.054473  0.945527
1  The woman was kicking a soccer ball to the man...  0.435267  0.564733
2     Mary was kicking a soccer ball to John because  0.307711  0.692289
3     Alice was kicking a soccer ball to Bob because  0.300106  0.699894
4  The actress was kicking a soccer ball to the a...  0.298971  0.701029

In [178]:
# female subject
transofposs_imperfective_connective1_3f = transofposs_imperfective_connective1_3[0:12]
transofposs_imperfective_connective1_3f = transofposs_imperfective_connective1_3f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_3m = transofposs_imperfective_connective1_3[12:24]

#### female subject

In [179]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_3f,'he'))

P('subj-pron'|subj=female) =  0.6748370379209518
P('non-subj-pron'|subj=female) =  0.3251629589746396

In [180]:
c1_average_subj_female_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3f,'she')
c1_average_subj_female_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3f,'he')

#### male subject

In [181]:
transofposs_imperfective_connective1_3m

                                             stimulus        he       she
12  Mr. Smith was kicking a soccer ball to Miss Sm...  0.494247  0.505753
13  The man was kicking a soccer ball to the woman...  0.476783  0.523217
14     John was kicking a soccer ball to Mary because  0.498819  0.501181
15     Bob was kicking a soccer ball to Alice because  0.342440  0.657560
16  The actor was kicking a soccer ball to the act...  0.253978  0.746022
17  The boy was kicking a soccer ball to the girl ...  0.510054  0.489946
18  Mr. William was kicking a soccer ball to  Mrs....  0.313457  0.686544
19    David was kicking a soccer ball to Emma because  0.368153  0.631847
20  The prince was kicking a soccer ball to the pr...  0.558842  0.441158
21  Robert was kicking a soccer ball to Sarah because  0.324496  0.675504
22  Mr. Taylor was kicking a soccer ball to Mrs. W...  0.184848  0.815152
23    Paul was kicking a soccer ball to Emily because  0.382175  0.617825

In [182]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_3m,'she'))

P('subj-pron'|subj=male) =  0.3923576759795348
P('non-subj-pron'|subj=male) =  0.6076423327128092

In [183]:
c1_average_subj_male_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3m,'he')
c1_average_subj_male_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3m,'she')

### verb: "lobbing"

In [184]:
transofposs_imperfective_connective1_4 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/4.csv")
transofposs_imperfective_connective1_4.head()

                                            stimulus        he       she
0  Miss Smith was lobbing a football to Mr. Smith...  0.077899  0.922101
1  The woman was lobbing a football to the man be...  0.624943  0.375057
2        Mary was lobbing a football to John because  0.530433  0.469567
3        Alice was lobbing a football to Bob because  0.533024  0.466976
4  The actress was lobbing a football to the acto...  0.424454  0.575546

In [185]:
# female subject
transofposs_imperfective_connective1_4f = transofposs_imperfective_connective1_4[0:12]
transofposs_imperfective_connective1_4f = transofposs_imperfective_connective1_4f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_4m = transofposs_imperfective_connective1_4[12:24]

#### female subject

In [186]:
transofposs_imperfective_connective1_4f

                                             stimulus       she        he
0   Miss Smith was lobbing a football to Mr. Smith...  0.922101  0.077899
1   The woman was lobbing a football to the man be...  0.375057  0.624943
2         Mary was lobbing a football to John because  0.469567  0.530433
3         Alice was lobbing a football to Bob because  0.466976  0.533024
4   The actress was lobbing a football to the acto...  0.575546  0.424454
5   The girl was lobbing a football to the boy bec...  0.398056  0.601944
6   Mrs. Taylor was lobbing a football to Mr. Will...  0.650156  0.349844
7        Emma was lobbing a football to David because  0.579348  0.420652
8   The princess was lobbing a football to the pri...  0.390324  0.609676
9      Sarah was lobbing a football to Robert because  0.473776  0.526224
10  Mrs. Williams was lobbing a football to  Mr. T...  0.613109  0.386891
11       Emily was lobbing a football to Paul because  0.473328  0.526672

In [187]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_4f,'he'))

P('subj-pron'|subj=female) =  0.5322786793112755
P('non-subj-pron'|subj=female) =  0.46772131820519763

In [188]:
c1_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4f,'she')
c1_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4f,'he')

#### male subject

In [189]:
transofposs_imperfective_connective1_4m

                                             stimulus        he       she
12  Mr. Smith was lobbing a football to Miss Smith...  0.535897  0.464103
13  The man was lobbing a football to the woman be...  0.386314  0.613686
14        John was lobbing a football to Mary because  0.375362  0.624638
15        Bob was lobbing a football to Alice because  0.270257  0.729743
16  The actor was lobbing a football to the actres...  0.188588  0.811412
17  The boy was lobbing a football to the girl bec...  0.395293  0.604707
18  Mr. William was lobbing a football to  Mrs. Ta...  0.296453  0.703547
19       David was lobbing a football to Emma because  0.341467  0.658533
20  The prince was lobbing a football to the princ...  0.402933  0.597067
21     Robert was lobbing a football to Sarah because  0.158186  0.841814
22  Mr. Taylor was lobbing a football to Mrs. Will...  0.197469  0.802531
23       Paul was lobbing a football to Emily because  0.310634  0.689366

In [190]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_4m,'she'))

P('subj-pron'|subj=male) =  0.32157113030552864
P('non-subj-pron'|subj=male) =  0.678428848584493

In [191]:
c1_average_subj_male_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4m,'he')
c1_average_subj_male_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4m,'she')

### verb: "rolling"

In [192]:
transofposs_imperfective_connective1_5 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/5.csv")
transofposs_imperfective_connective1_5.head()

                                            stimulus        he       she
0  Miss Smith was rolling a toy truck to Mr. Smit...  0.037509  0.962491
1  The woman was rolling a toy truck to the man b...  0.401192  0.598808
2       Mary was rolling a toy truck to John because  0.218803  0.781197
3       Alice was rolling a toy truck to Bob because  0.117077  0.882923
4  The actress was rolling a toy truck to the act...  0.128966  0.871034

In [193]:
# female subject
transofposs_imperfective_connective1_5f = transofposs_imperfective_connective1_5[0:12]
transofposs_imperfective_connective1_5f = transofposs_imperfective_connective1_5[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_5m = transofposs_imperfective_connective1_5[12:24]

#### female subject

In [194]:
transofposs_imperfective_connective1_5f

                                             stimulus       she        he
0   Miss Smith was rolling a toy truck to Mr. Smit...  0.962491  0.037509
1   The woman was rolling a toy truck to the man b...  0.598808  0.401192
2        Mary was rolling a toy truck to John because  0.781197  0.218803
3        Alice was rolling a toy truck to Bob because  0.882923  0.117077
4   The actress was rolling a toy truck to the act...  0.871034  0.128966
5   The girl was rolling a toy truck to the boy be...  0.755467  0.244533
6   Mrs. Taylor was rolling a toy truck to Mr. Wil...  0.799785  0.200214
7       Emma was rolling a toy truck to David because  0.888419  0.111581
8   The princess was rolling a toy truck to the pr...  0.810850  0.189150
9     Sarah was rolling a toy truck to Robert because  0.829419  0.170581
10  Mrs. Williams was rolling a toy truck to  Mr. ...  0.810582  0.189418
11      Emily was rolling a toy truck to Paul because  0.769939  0.230061
12  Mr. Smith was rolling a toy truck to Miss Smit...  0.404356  0.595644
13  The man was rolling a toy truck to the woman b...  0.469093  0.530907
14       John was rolling a toy truck to Mary because  0.297335  0.702665
15       Bob was rolling a toy truck to Alice because  0.392520  0.607480
16  The actor was rolling a toy truck to the actre...  0.719222  0.280778
17  The boy was rolling a toy truck to the girl be...  0.495182  0.504818
18  Mr. William was rolling a toy truck to  Mrs. T...  0.633600  0.366400
19      David was rolling a toy truck to Emma because  0.486263  0.513737
20  The prince was rolling a toy truck to the prin...  0.298478  0.701522
21    Robert was rolling a toy truck to Sarah because  0.754269  0.245731
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.779733  0.220267
23      Paul was rolling a toy truck to Emily because  0.594355  0.405645

In [195]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_5f,'he'))

P('subj-pron'|subj=female) =  0.6702216006815434
P('non-subj-pron'|subj=female) =  0.3297783837964137

In [196]:
c1_average_subj_female_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5f,'she')
c1_average_subj_female_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5f,'he')

#### male subject

In [197]:
transofposs_imperfective_connective1_5m

                                             stimulus        he       she
12  Mr. Smith was rolling a toy truck to Miss Smit...  0.595644  0.404356
13  The man was rolling a toy truck to the woman b...  0.530907  0.469093
14       John was rolling a toy truck to Mary because  0.702665  0.297335
15       Bob was rolling a toy truck to Alice because  0.607480  0.392520
16  The actor was rolling a toy truck to the actre...  0.280778  0.719222
17  The boy was rolling a toy truck to the girl be...  0.504818  0.495182
18  Mr. William was rolling a toy truck to  Mrs. T...  0.366400  0.633600
19      David was rolling a toy truck to Emma because  0.513737  0.486263
20  The prince was rolling a toy truck to the prin...  0.701522  0.298478
21    Robert was rolling a toy truck to Sarah because  0.245731  0.754269
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.220267  0.779733
23      Paul was rolling a toy truck to Emily because  0.405645  0.594355

In [198]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_5m,'she'))

P('subj-pron'|subj=male) =  0.4729662910103798
P('non-subj-pron'|subj=male) =  0.5270336990555128

In [199]:
c1_average_subj_male_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5m,'he')
c1_average_subj_male_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5m,'she')

### verb: "throwing"

In [200]:
transofposs_imperfective_connective1_6 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/6.csv")
transofposs_imperfective_connective1_6.head()

                                            stimulus        he       she
0  Miss Smith was throwing a hat to Mr. Smith bec...  0.063817  0.936182
1    The woman was throwing a hat to the man because  0.577493  0.422507
2            Mary was throwing a hat to John because  0.355636  0.644364
3            Alice was throwing a hat to Bob because  0.373305  0.626695
4  The actress was throwing a hat to the actor be...  0.269200  0.730800

In [201]:
# female subject
transofposs_imperfective_connective1_6f = transofposs_imperfective_connective1_6[0:12]
transofposs_imperfective_connective1_6f = transofposs_imperfective_connective1_6[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_6m = transofposs_imperfective_connective1_6[12:24]

#### female subject

In [202]:
transofposs_imperfective_connective1_6f

                                             stimulus       she        he
0   Miss Smith was throwing a hat to Mr. Smith bec...  0.936182  0.063817
1     The woman was throwing a hat to the man because  0.422507  0.577493
2             Mary was throwing a hat to John because  0.644364  0.355636
3             Alice was throwing a hat to Bob because  0.626695  0.373305
4   The actress was throwing a hat to the actor be...  0.730800  0.269200
5      The girl was throwing a hat to the boy because  0.539490  0.460510
6   Mrs. Taylor was throwing a hat to Mr. Williams...  0.732315  0.267685
7            Emma was throwing a hat to David because  0.696164  0.303836
8   The princess was throwing a hat to the prince ...  0.502571  0.497429
9          Sarah was throwing a hat to Robert because  0.680292  0.319708
10  Mrs. Williams was throwing a hat to  Mr. Taylo...  0.694467  0.305533
11           Emily was throwing a hat to Paul because  0.576661  0.423339
12  Mr. Smith was throwing a hat to Miss Smith bec...  0.444868  0.555132
13    The man was throwing a hat to the woman because  0.524888  0.475112
14            John was throwing a hat to Mary because  0.430263  0.569737
15            Bob was throwing a hat to Alice because  0.701604  0.298396
16  The actor was throwing a hat to the actress be...  0.732716  0.267284
17     The boy was throwing a hat to the girl because  0.487880  0.512120
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.608867  0.391133
19           David was throwing a hat to Emma because  0.578287  0.421713
20  The prince was throwing a hat to the princess ...  0.450909  0.549091
21         Robert was throwing a hat to Sarah because  0.725395  0.274605
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.727756  0.272244
23           Paul was throwing a hat to Emily because  0.610692  0.389308

In [203]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_6f,'he'))

P('subj-pron'|subj=female) =  0.616942989329497
P('non-subj-pron'|subj=female) =  0.38305699949463207

In [204]:
c1_average_subj_female_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6f,'she')
c1_average_subj_female_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6f,'he')

#### male subject

In [205]:
transofposs_imperfective_connective1_6m

                                             stimulus        he       she
12  Mr. Smith was throwing a hat to Miss Smith bec...  0.555132  0.444868
13    The man was throwing a hat to the woman because  0.475112  0.524888
14            John was throwing a hat to Mary because  0.569737  0.430263
15            Bob was throwing a hat to Alice because  0.298396  0.701604
16  The actor was throwing a hat to the actress be...  0.267284  0.732716
17     The boy was throwing a hat to the girl because  0.512120  0.487880
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.391133  0.608867
19           David was throwing a hat to Emma because  0.421713  0.578287
20  The prince was throwing a hat to the princess ...  0.549091  0.450909
21         Robert was throwing a hat to Sarah because  0.274605  0.725395
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.272244  0.727756
23           Paul was throwing a hat to Emily because  0.389308  0.610692

In [206]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_6m,'she'))

P('subj-pron'|subj=male) =  0.4146563435594241
P('non-subj-pron'|subj=male) =  0.5853436465064684

In [207]:
c1_average_subj_male_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6m,'he')
c1_average_subj_male_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6m,'she')

### verb: "tossing"

In [208]:
transofposs_imperfective_connective1_7 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/7.csv")
transofposs_imperfective_connective1_7.head()

                                            stimulus        he       she
0  Miss Smith was tossing a dish towel to Mr. Smi...  0.054837  0.945163
1  The woman was tossing a dish towel to the man ...  0.597829  0.402171
2      Mary was tossing a dish towel to John because  0.456348  0.543652
3      Alice was tossing a dish towel to Bob because  0.451916  0.548084
4  The actress was tossing a dish towel to the ac...  0.320055  0.679945

In [209]:
# female subject
transofposs_imperfective_connective1_7f = transofposs_imperfective_connective1_7[0:12]
transofposs_imperfective_connective1_7f = transofposs_imperfective_connective1_7f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_7m = transofposs_imperfective_connective1_7[12:24]

#### female subject

In [210]:
transofposs_imperfective_connective1_7f

                                             stimulus       she        he
0   Miss Smith was tossing a dish towel to Mr. Smi...  0.945163  0.054837
1   The woman was tossing a dish towel to the man ...  0.402171  0.597829
2       Mary was tossing a dish towel to John because  0.543652  0.456348
3       Alice was tossing a dish towel to Bob because  0.548084  0.451916
4   The actress was tossing a dish towel to the ac...  0.679945  0.320055
5   The girl was tossing a dish towel to the boy b...  0.462954  0.537046
6   Mrs. Taylor was tossing a dish towel to Mr. Wi...  0.708023  0.291977
7      Emma was tossing a dish towel to David because  0.630733  0.369267
8   The princess was tossing a dish towel to the p...  0.467387  0.532613
9    Sarah was tossing a dish towel to Robert because  0.544736  0.455264
10  Mrs. Williams was tossing a dish towel to  Mr....  0.690957  0.309043
11     Emily was tossing a dish towel to Paul because  0.483344  0.516656

In [211]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_7f,'he'))

P('subj-pron'|subj=female) =  0.5922625040014585
P('non-subj-pron'|subj=female) =  0.407737501586477

In [212]:
c1_average_subj_female_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7f,'she')
c1_average_subj_female_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7f,'he')

#### male subject

In [213]:
transofposs_imperfective_connective1_7m

                                             stimulus        he       she
12  Mr. Smith was tossing a dish towel to Miss Smi...  0.511260  0.488740
13  The man was tossing a dish towel to the woman ...  0.392870  0.607130
14      John was tossing a dish towel to Mary because  0.508801  0.491199
15      Bob was tossing a dish towel to Alice because  0.214119  0.785881
16  The actor was tossing a dish towel to the actr...  0.192254  0.807746
17  The boy was tossing a dish towel to the girl b...  0.418776  0.581224
18  Mr. William was tossing a dish towel to  Mrs. ...  0.298337  0.701663
19     David was tossing a dish towel to Emma because  0.342585  0.657415
20  The prince was tossing a dish towel to the pri...  0.492896  0.507104
21   Robert was tossing a dish towel to Sarah because  0.161468  0.838532
22  Mr. Taylor was tossing a dish towel to Mrs. Wi...  0.194377  0.805623
23     Paul was tossing a dish towel to Emily because  0.278852  0.721148

In [214]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_7m,'she'))

P('subj-pron'|subj=male) =  0.33388304089506465
P('non-subj-pron'|subj=male) =  0.666116955379645

In [215]:
c1_average_subj_male_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7m,'he')
c1_average_subj_male_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7m,'she')

### verb: "bringing"

In [216]:
transofposs_imperfective_connective1_8 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/8.csv")
transofposs_imperfective_connective1_8.head()

                                            stimulus        he       she
0  Miss Smith was bringing a glass of water to Mr...  0.071390  0.928610
1  The woman was bringing a glass of water to the...  0.532627  0.467373
2  Mary was bringing a glass of water to John bec...  0.226381  0.773619
3  Alice was bringing a glass of water to Bob bec...  0.261133  0.738867
4  The actress was bringing a glass of water to t...  0.075671  0.924329

In [217]:
# female subject
transofposs_imperfective_connective1_8f = transofposs_imperfective_connective1_8[0:12]
transofposs_imperfective_connective1_8f = transofposs_imperfective_connective1_8f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_8m = transofposs_imperfective_connective1_8[12:24]

#### female subject

In [218]:
transofposs_imperfective_connective1_8f

                                             stimulus       she        he
0   Miss Smith was bringing a glass of water to Mr...  0.928610  0.071390
1   The woman was bringing a glass of water to the...  0.467373  0.532627
2   Mary was bringing a glass of water to John bec...  0.773619  0.226381
3   Alice was bringing a glass of water to Bob bec...  0.738867  0.261133
4   The actress was bringing a glass of water to t...  0.924329  0.075671
5   The girl was bringing a glass of water to the ...  0.690453  0.309547
6   Mrs. Taylor was bringing a glass of water to M...  0.675519  0.324481
7   Emma was bringing a glass of water to David be...  0.801863  0.198137
8   The princess was bringing a glass of water to ...  0.761915  0.238085
9   Sarah was bringing a glass of water to Robert ...  0.670571  0.329429
10  Mrs. Williams was bringing a glass of water to...  0.667559  0.332441
11  Emily was bringing a glass of water to Paul be...  0.599264  0.400736

In [219]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_8f,'he'))

P('subj-pron'|subj=female) =  0.7249951213598251
P('non-subj-pron'|subj=female) =  0.2750048724313577

In [220]:
c1_average_subj_female_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8f,'she')
c1_average_subj_female_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8f,'he')

#### male subject

In [221]:
transofposs_imperfective_connective1_8m

                                             stimulus        he       she
12  Mr. Smith was bringing a glass of water to Mis...  0.497185  0.502814
13  The man was bringing a glass of water to the w...  0.435989  0.564011
14  John was bringing a glass of water to Mary bec...  0.422207  0.577793
15  Bob was bringing a glass of water to Alice bec...  0.286598  0.713402
16  The actor was bringing a glass of water to the...  0.339578  0.660422
17  The boy was bringing a glass of water to the g...  0.447965  0.552035
18  Mr. William was bringing a glass of water to  ...  0.372948  0.627052
19  David was bringing a glass of water to Emma be...  0.440037  0.559963
20  The prince was bringing a glass of water to th...  0.523650  0.476350
21  Robert was bringing a glass of water to Sarah ...  0.099385  0.900615
22  Mr. Taylor was bringing a glass of water to Mr...  0.226567  0.773432
23  Paul was bringing a glass of water to Emily be...  0.323619  0.676381

In [222]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_8m,'she'))

P('subj-pron'|subj=male) =  0.36797739813725155
P('non-subj-pron'|subj=male) =  0.6320226068298022

In [223]:
c1_average_subj_male_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8m,'he')
c1_average_subj_male_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8m,'she')

### verb: "forwarding"

In [224]:
transofposs_imperfective_connective1_9 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/9.csv")
transofposs_imperfective_connective1_9.head()

                                            stimulus        he       she
0  Miss Smith was forwarding a gossipy email to M...  0.036440  0.963560
1  The woman was forwarding a gossipy email to th...  0.535800  0.464200
2  Mary was forwarding a gossipy email to John be...  0.354735  0.645265
3  Alice was forwarding a gossipy email to Bob be...  0.375820  0.624180
4  The actress was forwarding a gossipy email to ...  0.193496  0.806504

In [225]:
# female subject
transofposs_imperfective_connective1_9f = transofposs_imperfective_connective1_9[0:12]
transofposs_imperfective_connective1_9f = transofposs_imperfective_connective1_9f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_9m = transofposs_imperfective_connective1_9[12:24]

#### female subject

In [226]:
transofposs_imperfective_connective1_9f

                                             stimulus       she        he
0   Miss Smith was forwarding a gossipy email to M...  0.963560  0.036440
1   The woman was forwarding a gossipy email to th...  0.464200  0.535800
2   Mary was forwarding a gossipy email to John be...  0.645265  0.354735
3   Alice was forwarding a gossipy email to Bob be...  0.624180  0.375820
4   The actress was forwarding a gossipy email to ...  0.806504  0.193496
5   The girl was forwarding a gossipy email to the...  0.512011  0.487989
6   Mrs. Taylor was forwarding a gossipy email to ...  0.729260  0.270740
7   Emma was forwarding a gossipy email to David b...  0.785470  0.214530
8   The princess was forwarding a gossipy email to...  0.478994  0.521006
9   Sarah was forwarding a gossipy email to Robert...  0.687658  0.312342
10  Mrs. Williams was forwarding a gossipy email t...  0.717304  0.282696
11  Emily was forwarding a gossipy email to Paul b...  0.666568  0.333432

In [227]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_9f,'he'))

P('subj-pron'|subj=female) =  0.6734144960840543
P('non-subj-pron'|subj=female) =  0.32658549677580595

In [228]:
c1_average_subj_female_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9f,'she')
c1_average_subj_female_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9f,'he')

#### male subject

In [229]:
transofposs_imperfective_connective1_9m

                                             stimulus        he       she
12  Mr. Smith was forwarding a gossipy email to Mi...  0.550781  0.449219
13  The man was forwarding a gossipy email to the ...  0.503008  0.496992
14  John was forwarding a gossipy email to Mary be...  0.646795  0.353205
15  Bob was forwarding a gossipy email to Alice be...  0.265079  0.734921
16  The actor was forwarding a gossipy email to th...  0.202412  0.797588
17  The boy was forwarding a gossipy email to the ...  0.495744  0.504256
18  Mr. William was forwarding a gossipy email to ...  0.304452  0.695548
19  David was forwarding a gossipy email to Emma b...  0.457134  0.542866
20  The prince was forwarding a gossipy email to t...  0.595527  0.404473
21  Robert was forwarding a gossipy email to Sarah...  0.275900  0.724100
22  Mr. Taylor was forwarding a gossipy email to M...  0.162092  0.837908
23  Paul was forwarding a gossipy email to Emily b...  0.389387  0.610613

In [230]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_9m,'she'))

P('subj-pron'|subj=male) =  0.40402593091130257
P('non-subj-pron'|subj=male) =  0.595974067846934

In [231]:
c1_average_subj_male_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9m,'he')
c1_average_subj_male_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9m,'she')

### verb: "mailing"

In [232]:
transofposs_imperfective_connective1_10 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/10.csv")
transofposs_imperfective_connective1_10.head()

                                            stimulus        he       she
0  Miss Smith was mailing a letter to Mr. Smith b...  0.022332  0.977668
1  The woman was mailing a letter to the man because  0.400106  0.599894
2          Mary was mailing a letter to John because  0.160728  0.839272
3          Alice was mailing a letter to Bob because  0.193779  0.806221
4  The actress was mailing a letter to the actor ...  0.058389  0.941611

In [233]:
# female subject
transofposs_imperfective_connective1_10f = transofposs_imperfective_connective1_10[0:12]
transofposs_imperfective_connective1_10f = transofposs_imperfective_connective1_10f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_10m = transofposs_imperfective_connective1_10[12:24]

#### female subject

In [234]:
transofposs_imperfective_connective1_10f

                                             stimulus       she        he
0   Miss Smith was mailing a letter to Mr. Smith b...  0.977668  0.022332
1   The woman was mailing a letter to the man because  0.599894  0.400106
2           Mary was mailing a letter to John because  0.839272  0.160728
3           Alice was mailing a letter to Bob because  0.806221  0.193779
4   The actress was mailing a letter to the actor ...  0.941611  0.058389
5    The girl was mailing a letter to the boy because  0.679771  0.320229
6   Mrs. Taylor was mailing a letter to Mr. Willia...  0.753095  0.246905
7          Emma was mailing a letter to David because  0.942905  0.057095
8   The princess was mailing a letter to the princ...  0.715273  0.284727
9        Sarah was mailing a letter to Robert because  0.875550  0.124450
10  Mrs. Williams was mailing a letter to Mr. Tayl...  0.751026  0.248974
11         Emily was mailing a letter to Paul because  0.901751  0.098249

In [235]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_10f,'he'))

P('subj-pron'|subj=female) =  0.8153363366921743
P('non-subj-pron'|subj=female) =  0.18466364809622368

In [236]:
c1_average_subj_female_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10f,'she')
c1_average_subj_female_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10f,'he')

#### male subject

In [237]:
transofposs_imperfective_connective1_10m

                                             stimulus        he       she
12  Mr. Smith was mailing a letter to Miss Smith b...  0.651069  0.348932
13  The man was mailing a letter to the woman because  0.522287  0.477713
14          John was mailing a letter to Mary because  0.845374  0.154626
15          Bob was mailing a letter to Alice because  0.437582  0.562418
16  The actor was mailing a letter to the actress ...  0.355006  0.644994
17   The boy was mailing a letter to the girl because  0.591030  0.408970
18  Mr. William was mailing a letter to  Mrs. Tayl...  0.400479  0.599521
19         David was mailing a letter to Emma because  0.719700  0.280300
20  The prince was mailing a letter to the princes...  0.714898  0.285102
21       Robert was mailing a letter to Sarah because  0.440880  0.559120
22  Mr. Taylor was mailing a letter to Mrs. Willia...  0.225861  0.774139
23         Paul was mailing a letter to Emily because  0.591099  0.408901

In [238]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_10m,'she'))

P('subj-pron'|subj=male) =  0.5412720081706842
P('non-subj-pron'|subj=male) =  0.45872800921400386

In [239]:
c1_average_subj_male_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10m,'he')
c1_average_subj_male_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10m,'she')

### verb: "shipping"

In [240]:
transofposs_imperfective_connective1_11 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/11.csv")
transofposs_imperfective_connective1_11.head()

                                            stimulus        he       she
0  Miss Smith was shipping a package to Mr. Smith...  0.035122  0.964878
1  The woman was shipping a package to the man be...  0.461758  0.538242
2        Mary was shipping a package to John because  0.212908  0.787092
3        Alice was shipping a package to Bob because  0.214598  0.785402
4  The actress was shipping a package to the acto...  0.168382  0.831618

In [241]:
# female subject
transofposs_imperfective_connective1_11f = transofposs_imperfective_connective1_11[0:12]
transofposs_imperfective_connective1_11f = transofposs_imperfective_connective1_11f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_11m = transofposs_imperfective_connective1_11[12:24]

#### female subject

In [242]:
transofposs_imperfective_connective1_11f

                                             stimulus       she        he
0   Miss Smith was shipping a package to Mr. Smith...  0.964878  0.035122
1   The woman was shipping a package to the man be...  0.538242  0.461758
2         Mary was shipping a package to John because  0.787092  0.212908
3         Alice was shipping a package to Bob because  0.785402  0.214598
4   The actress was shipping a package to the acto...  0.831618  0.168382
5   The girl was shipping a package to the boy bec...  0.703771  0.296229
6   Mrs. Taylor was shipping a package to Mr. Will...  0.717119  0.282881
7        Emma was shipping a package to David because  0.914173  0.085827
8   The princess was shipping a package to the pri...  0.602118  0.397882
9      Sarah was shipping a package to Robert because  0.834773  0.165227
10  Mrs. Williams was shipping a package to Mr. Ta...  0.744683  0.255317
11       Emily was shipping a package to Paul because  0.741123  0.258877

In [243]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_11f,'he'))

P('subj-pron'|subj=female) =  0.7637493759393692
P('non-subj-pron'|subj=female) =  0.2362506603822112

In [244]:
c1_average_subj_female_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11f,'she')
c1_average_subj_female_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11f,'he')

#### male subject

In [245]:
transofposs_imperfective_connective1_11m

                                             stimulus        he       she
12  Mr. Smith was shipping a package to Miss Smith...  0.576386  0.423614
13  The man was shipping a package to the woman be...  0.473717  0.526283
14        John was shipping a package to Mary because  0.590983  0.409016
15        Bob was shipping a package to Alice because  0.213154  0.786846
16  The actor was shipping a package to the actres...  0.163577  0.836423
17  The boy was shipping a package to the girl bec...  0.371554  0.628446
18  Mr. William was shipping a package to  Mrs. Ta...  0.338826  0.661174
19       David was shipping a package to Emma because  0.385070  0.614930
20  The prince was shipping a package to the princ...  0.634844  0.365156
21     Robert was shipping a package to Sarah because  0.210928  0.789072
22  Mr. Taylor was shipping a package to Mrs. Will...  0.188306  0.811694
23       Paul was shipping a package to Emily because  0.338264  0.661736

In [246]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_11m,'she'))

P('subj-pron'|subj=male) =  0.37380074958006543
P('non-subj-pron'|subj=male) =  0.6261992280681928

In [247]:
c1_average_subj_male_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11m,'he')
c1_average_subj_male_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11m,'she')

### verb: "transmitting"

In [248]:
transofposs_imperfective_connective1_12 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/12.csv")
transofposs_imperfective_connective1_12.head()

                                            stimulus        he       she
0  Miss Smith was transmitting a message to Mr. S...  0.047524  0.952476
1  The woman was transmitting a message to the ma...  0.370746  0.629254
2    Mary was transmitting a message to John because  0.163725  0.836275
3    Alice was transmitting a message to Bob because  0.205664  0.794336
4  The actress was transmitting a message to the ...  0.126239  0.873761

In [249]:
# female subject
transofposs_imperfective_connective1_12f = transofposs_imperfective_connective1_12[0:12]
transofposs_imperfective_connective1_12f = transofposs_imperfective_connective1_12f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_12m = transofposs_imperfective_connective1_12[12:24]

#### female subject

In [250]:
transofposs_imperfective_connective1_12f

                                             stimulus       she        he
0   Miss Smith was transmitting a message to Mr. S...  0.952476  0.047524
1   The woman was transmitting a message to the ma...  0.629254  0.370746
2     Mary was transmitting a message to John because  0.836275  0.163725
3     Alice was transmitting a message to Bob because  0.794336  0.205664
4   The actress was transmitting a message to the ...  0.873761  0.126239
5   The girl was transmitting a message to the boy...  0.736778  0.263222
6   Mrs. Taylor was transmitting a message to Mr. ...  0.772783  0.227217
7    Emma was transmitting a message to David because  0.887273  0.112727
8   The princess was transmitting a message to the...  0.715192  0.284808
9   Sarah was transmitting a message to Robert bec...  0.845329  0.154671
10  Mrs. Williams was transmitting a message to Mr...  0.746256  0.253744
11   Emily was transmitting a message to Paul because  0.740996  0.259004

In [251]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_12f,'he'))

P('subj-pron'|subj=female) =  0.7942257970571518
P('non-subj-pron'|subj=female) =  0.2057741933191816

In [252]:
c1_average_subj_female_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12f,'she')
c1_average_subj_female_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12f,'he')

#### male subject

In [253]:
transofposs_imperfective_connective1_12m

                                             stimulus        he       she
12  Mr. Smith was transmitting a message to Miss S...  0.651288  0.348712
13  The man was transmitting a message to the woma...  0.542773  0.457227
14    John was transmitting a message to Mary because  0.704844  0.295156
15    Bob was transmitting a message to Alice because  0.331934  0.668066
16  The actor was transmitting a message to the ac...  0.316691  0.683309
17  The boy was transmitting a message to the girl...  0.533743  0.466257
18  Mr. William was transmitting a message to  Mrs...  0.346046  0.653953
19   David was transmitting a message to Emma because  0.528002  0.471998
20  The prince was transmitting a message to the p...  0.747947  0.252053
21  Robert was transmitting a message to Sarah bec...  0.351036  0.648964
22  Mr. Taylor was transmitting a message to Mrs. ...  0.194109  0.805891
23   Paul was transmitting a message to Emily because  0.466606  0.533394

In [254]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_12m,'she'))

P('subj-pron'|subj=male) =  0.4762515376011531
P('non-subj-pron'|subj=male) =  0.5237484723329544

In [255]:
c1_average_subj_male_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12m,'he')
c1_average_subj_male_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12m,'she')

### verb: "wiring"

In [256]:
transofposs_imperfective_connective1_14 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/14.csv")
transofposs_imperfective_connective1_14.head()

                                            stimulus        he       she
0   Miss Smith was wiring money to Mr. Smith because  0.046529  0.953471
1      The woman was wiring money to the man because  0.464726  0.535274
2              Mary was wiring money to John because  0.293869  0.706131
3              Alice was wiring money to Bob because  0.346410  0.653590
4  The actress was wiring money to the actor because  0.153410  0.846590

In [257]:
# female subject
transofposs_imperfective_connective1_14f = transofposs_imperfective_connective1_14[0:12]
transofposs_imperfective_connective1_14f = transofposs_imperfective_connective1_14f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_14m = transofposs_imperfective_connective1_14[12:24]

#### female subject

In [258]:
transofposs_imperfective_connective1_14f

                                             stimulus       she        he
0    Miss Smith was wiring money to Mr. Smith because  0.953471  0.046529
1       The woman was wiring money to the man because  0.535274  0.464726
2               Mary was wiring money to John because  0.706131  0.293869
3               Alice was wiring money to Bob because  0.653590  0.346410
4   The actress was wiring money to the actor because  0.846590  0.153410
5        The girl was wiring money to the boy because  0.657371  0.342629
6   Mrs. Taylor was wiring money to Mr. Williams b...  0.690847  0.309153
7              Emma was wiring money to David because  0.690837  0.309163
8   The princess was wiring money to the prince be...  0.607798  0.392202
9            Sarah was wiring money to Robert because  0.719669  0.280331
10  Mrs. Williams was wiring money to Mr. Taylor b...  0.732364  0.267636
11             Emily was wiring money to Paul because  0.595234  0.404766

In [259]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_14f,'he'))

P('subj-pron'|subj=female) =  0.6990978370110194
P('non-subj-pron'|subj=female) =  0.3009021769588192

In [260]:
c1_average_subj_female_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14f,'she')
c1_average_subj_female_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14f,'he')

#### male subject

In [261]:
transofposs_imperfective_connective1_14m

                                             stimulus        he       she
12   Mr. Smith was wiring money to Miss Smith because  0.583997  0.416003
13      The man was wiring money to the woman because  0.566362  0.433638
14              John was wiring money to Mary because  0.594546  0.405454
15              Bob was wiring money to Alice because  0.259482  0.740518
16  The actor was wiring money to the actress because  0.326370  0.673630
17       The boy was wiring money to the girl because  0.630463  0.369537
18  Mr. William was wiring money to  Mrs. Taylor b...  0.374153  0.625847
19             David was wiring money to Emma because  0.392458  0.607542
20  The prince was wiring money to the princess be...  0.729353  0.270647
21           Robert was wiring money to Sarah because  0.221674  0.778326
22  Mr. Taylor was wiring money to Mrs. Williams b...  0.189734  0.810266
23             Paul was wiring money to Emily because  0.363149  0.636851

In [262]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_14m,'she'))

P('subj-pron'|subj=male) =  0.43597837040821713
P('non-subj-pron'|subj=male) =  0.5640216122070948

In [263]:
c1_average_subj_male_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14m,'he')
c1_average_subj_male_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14m,'she')

### verb: "carrying"

In [264]:
transofposs_imperfective_connective1_15 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/15.csv")
transofposs_imperfective_connective1_15.head()

                                            stimulus        he       she
0  Miss Smith was carrying a tray to Mr. Smith be...  0.046227  0.953773
1   The woman was carrying a tray to the man because  0.386572  0.613428
2           Mary was carrying a tray to John because  0.140880  0.859120
3           Alice was carrying a tray to Bob because  0.064010  0.935990
4  The actress was carrying a tray to the actor b...  0.122655  0.877345

In [265]:
# female subject
transofposs_imperfective_connective1_15f = transofposs_imperfective_connective1_15[0:12]
transofposs_imperfective_connective1_15f = transofposs_imperfective_connective1_15f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_15m = transofposs_imperfective_connective1_15[12:24]

#### female subject

In [266]:
transofposs_imperfective_connective1_15f

                                             stimulus       she        he
0   Miss Smith was carrying a tray to Mr. Smith be...  0.953773  0.046227
1    The woman was carrying a tray to the man because  0.613428  0.386572
2            Mary was carrying a tray to John because  0.859120  0.140880
3            Alice was carrying a tray to Bob because  0.935990  0.064010
4   The actress was carrying a tray to the actor b...  0.877345  0.122655
5     The girl was carrying a tray to the boy because  0.849494  0.150506
6   Mrs. Taylor was carrying a tray to Mr. William...  0.757493  0.242507
7           Emma was carrying a tray to David because  0.942605  0.057395
8   The princess was carrying a tray to the prince...  0.758273  0.241727
9         Sarah was carrying a tray to Robert because  0.896509  0.103491
10  Mrs. Williams was carrying a tray to Mr. Taylo...  0.749407  0.250593
11          Emily was carrying a tray to Paul because  0.819900  0.180100

In [267]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_15f,'he'))

P('subj-pron'|subj=female) =  0.834444652001063
P('non-subj-pron'|subj=female) =  0.16555533030380806

In [268]:
c1_average_subj_female_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15f,'she')
c1_average_subj_female_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15f,'he')

#### male subject

In [269]:
transofposs_imperfective_connective1_15m

                                             stimulus        he       she
12  Mr. Smith was carrying a tray to Miss Smith be...  0.600315  0.399685
13   The man was carrying a tray to the woman because  0.565945  0.434055
14           John was carrying a tray to Mary because  0.662332  0.337668
15           Bob was carrying a tray to Alice because  0.403128  0.596872
16  The actor was carrying a tray to the actress b...  0.323117  0.676883
17    The boy was carrying a tray to the girl because  0.609849  0.390151
18  Mr. William was carrying a tray to  Mrs. Taylo...  0.373678  0.626322
19          David was carrying a tray to Emma because  0.451475  0.548525
20  The prince was carrying a tray to the princess...  0.655148  0.344852
21        Robert was carrying a tray to Sarah because  0.270300  0.729700
22  Mr. Taylor was carrying a tray to Mrs. William...  0.255505  0.744495
23          Paul was carrying a tray to Emily because  0.410370  0.589630

In [270]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_15m,'she'))

P('subj-pron'|subj=male) =  0.46509698281685513
P('non-subj-pron'|subj=male) =  0.5349030097325643

In [271]:
c1_average_subj_male_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15m,'he')
c1_average_subj_male_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15m,'she')

### verb: "delivering"

In [272]:
transofposs_imperfective_connective1_16 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/16.csv")
transofposs_imperfective_connective1_16.head()

                                            stimulus        he       she
0  Miss Smith was delivering a subpoena to Mr. Sm...  0.051767  0.948233
1  The woman was delivering a subpoena to the man...  0.528834  0.471166
2     Mary was delivering a subpoena to John because  0.254629  0.745370
3     Alice was delivering a subpoena to Bob because  0.304588  0.695412
4  The actress was delivering a subpoena to the a...  0.282806  0.717193

In [273]:
# female subject
transofposs_imperfective_connective1_16f = transofposs_imperfective_connective1_16[0:12]
transofposs_imperfective_connective1_16f = transofposs_imperfective_connective1_16f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_16m = transofposs_imperfective_connective1_16[12:24]

#### female subject

In [274]:
transofposs_imperfective_connective1_16f

                                             stimulus       she        he
0   Miss Smith was delivering a subpoena to Mr. Sm...  0.948233  0.051767
1   The woman was delivering a subpoena to the man...  0.471166  0.528834
2      Mary was delivering a subpoena to John because  0.745370  0.254629
3      Alice was delivering a subpoena to Bob because  0.695412  0.304588
4   The actress was delivering a subpoena to the a...  0.717193  0.282806
5   The girl was delivering a subpoena to the boy ...  0.594645  0.405355
6   Mrs. Taylor was delivering a subpoena to Mr. W...  0.699912  0.300088
7     Emma was delivering a subpoena to David because  0.792698  0.207302
8   The princess was delivering a subpoena to the ...  0.568483  0.431517
9   Sarah was delivering a subpoena to Robert because  0.768399  0.231601
10  Mrs. Williams was delivering a subpoena to Mr....  0.722139  0.277861
11    Emily was delivering a subpoena to Paul because  0.703967  0.296033

In [275]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_16f,'he'))

P('subj-pron'|subj=female) =  0.7023015295465788
P('non-subj-pron'|subj=female) =  0.2976984561731418

In [276]:
c1_average_subj_female_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16f,'she')
c1_average_subj_female_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16f,'he')

#### male subject

In [277]:
transofposs_imperfective_connective1_16m

                                             stimulus        he       she
12  Mr. Smith was delivering a subpoena to Miss Sm...  0.528982  0.471018
13  The man was delivering a subpoena to the woman...  0.343799  0.656201
14     John was delivering a subpoena to Mary because  0.508736  0.491264
15     Bob was delivering a subpoena to Alice because  0.145670  0.854330
16  The actor was delivering a subpoena to the act...  0.165736  0.834264
17  The boy was delivering a subpoena to the girl ...  0.359000  0.641000
18  Mr. William was delivering a subpoena to Mrs. ...  0.332872  0.667128
19    David was delivering a subpoena to Emma because  0.417706  0.582294
20  The prince was delivering a subpoena to the pr...  0.560810  0.439190
21  Robert was delivering a subpoena to Sarah because  0.196085  0.803915
22  Mr. Taylor was delivering a subpoena to Mrs. W...  0.206747  0.793253
23    Paul was delivering a subpoena to Emily because  0.290084  0.709916

In [278]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_16m,'she'))

P('subj-pron'|subj=male) =  0.3380189600090186
P('non-subj-pron'|subj=male) =  0.6619810288151106

In [279]:
c1_average_subj_male_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16m,'he')
c1_average_subj_male_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16m,'she')

### verb: "giving"

In [280]:
transofposs_imperfective_connective1_17 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/17.csv")
transofposs_imperfective_connective1_17.head()

                                            stimulus        he       she
0  Miss Smith was giving a sweater to Mr. Smith b...  0.072294  0.927706
1  The woman was giving a sweater to the man because  0.581262  0.418738
2          Mary was giving a sweater to John because  0.299138  0.700862
3          Alice was giving a sweater to Bob because  0.326029  0.673971
4  The actress was giving a sweater to the actor ...  0.140821  0.859179

In [281]:
# female subject
transofposs_imperfective_connective1_17f = transofposs_imperfective_connective1_17[0:12]
transofposs_imperfective_connective1_17f = transofposs_imperfective_connective1_17f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_17m = transofposs_imperfective_connective1_17[12:24]

#### female subject

In [282]:
transofposs_imperfective_connective1_17f

                                             stimulus       she        he
0   Miss Smith was giving a sweater to Mr. Smith b...  0.927706  0.072294
1   The woman was giving a sweater to the man because  0.418738  0.581262
2           Mary was giving a sweater to John because  0.700862  0.299138
3           Alice was giving a sweater to Bob because  0.673971  0.326029
4   The actress was giving a sweater to the actor ...  0.859179  0.140821
5    The girl was giving a sweater to the boy because  0.571352  0.428648
6   Mrs. Taylor was giving a sweater to Mr. Willia...  0.734794  0.265206
7          Emma was giving a sweater to David because  0.770688  0.229312
8   The princess was giving a sweater to the princ...  0.568306  0.431694
9        Sarah was giving a sweater to Robert because  0.713795  0.286204
10  Mrs. Williams was giving a sweater to Mr. Tayl...  0.726081  0.273919
11         Emily was giving a sweater to Paul because  0.654537  0.345463

In [283]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_17f,'he'))

P('subj-pron'|subj=female) =  0.6933339834213257
P('non-subj-pron'|subj=female) =  0.3066660289963086

In [284]:
c1_average_subj_female_subj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17f,'she')
c1_average_subj_female_obj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17f,'he')

#### male subject

In [285]:
transofposs_imperfective_connective1_17m

                                             stimulus        he       she
12  Mr. Smith was giving a sweater to Miss Smith b...  0.568428  0.431572
13  The man was giving a sweater to the woman because  0.510277  0.489723
14          John was giving a sweater to Mary because  0.566148  0.433852
15          Bob was giving a sweater to Alice because  0.299828  0.700172
16  The actor was giving a sweater to the actress ...  0.445453  0.554547
17   The boy was giving a sweater to the girl because  0.580525  0.419475
18  Mr. William was giving a sweater to  Mrs. Tayl...  0.383649  0.616351
19         David was giving a sweater to Emma because  0.484683  0.515317
20  The prince was giving a sweater to the princes...  0.617047  0.382953
21       Robert was giving a sweater to Sarah because  0.244856  0.755144
22  Mr. Taylor was giving a sweater to Mrs. Willia...  0.223583  0.776417
23         Paul was giving a sweater to Emily because  0.360597  0.639403

In [286]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_17m,'she'))

P('subj-pron'|subj=male) =  0.44042279819647473
P('non-subj-pron'|subj=male) =  0.5595771943529447

In [287]:
c1_average_subj_male_subj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17m,'he')
c1_average_subj_male_obj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17m,'she')

### verb: "handing"

In [288]:
transofposs_imperfective_connective1_18 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/18.csv")
transofposs_imperfective_connective1_18.head()

                                            stimulus        he       she
0  Miss Smith was handing a book to Mr. Smith bec...  0.049986  0.950014
1    The woman was handing a book to the man because  0.514123  0.485877
2            Mary was handing a book to John because  0.303871  0.696129
3            Alice was handing a book to Bob because  0.331211  0.668789
4  The actress was handing a book to the actor be...  0.240508  0.759492

In [289]:
# female subject
transofposs_imperfective_connective1_18f = transofposs_imperfective_connective1_18[0:12]
transofposs_imperfective_connective1_18f = transofposs_imperfective_connective1_18f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_18m = transofposs_imperfective_connective1_18[12:24]

#### female subject

In [290]:
transofposs_imperfective_connective1_18f

                                             stimulus       she        he
0   Miss Smith was handing a book to Mr. Smith bec...  0.950014  0.049986
1     The woman was handing a book to the man because  0.485877  0.514123
2             Mary was handing a book to John because  0.696129  0.303871
3             Alice was handing a book to Bob because  0.668789  0.331211
4   The actress was handing a book to the actor be...  0.759492  0.240508
5      The girl was handing a book to the boy because  0.537241  0.462759
6   Mrs. Taylor was handing a book to Mr. Williams...  0.737955  0.262045
7            Emma was handing a book to David because  0.777247  0.222753
8   The princess was handing a book to the prince ...  0.529907  0.470093
9          Sarah was handing a book to Robert because  0.699203  0.300797
10  Mrs. Williams was handing a book to Mr. Taylor...  0.746507  0.253493
11           Emily was handing a book to Paul because  0.647164  0.352836

In [291]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_18f,'he'))

P('subj-pron'|subj=female) =  0.6862936690449715
P('non-subj-pron'|subj=female) =  0.31370632102092105

In [292]:
c1_average_subj_female_subj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18f,'she')
c1_average_subj_female_obj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18f,'he')

#### male subject

In [293]:
transofposs_imperfective_connective1_18m

                                             stimulus        he       she
12  Mr. Smith was handing a book to Miss Smith bec...  0.525096  0.474904
13    The man was handing a book to the woman because  0.433810  0.566190
14            John was handing a book to Mary because  0.454643  0.545357
15            Bob was handing a book to Alice because  0.254963  0.745037
16  The actor was handing a book to the actress be...  0.256527  0.743473
17     The boy was handing a book to the girl because  0.444413  0.555587
18  Mr. William was handing a book to Mrs. Taylor ...  0.303697  0.696304
19           David was handing a book to Emma because  0.434429  0.565571
20  The prince was handing a book to the princess ...  0.539498  0.460502
21         Robert was handing a book to Sarah because  0.227138  0.772862
22  Mr. Taylor was handing a book to Mrs. Williams...  0.174833  0.825167
23           Paul was handing a book to Emily because  0.360218  0.639782

In [294]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_18m,'she'))

P('subj-pron'|subj=male) =  0.3674387149512768
P('non-subj-pron'|subj=male) =  0.6325613111257553

In [295]:
c1_average_subj_male_subj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18m,'he')
c1_average_subj_male_obj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18m,'she')

### verb: "passing"

In [296]:
transofposs_imperfective_connective1_19 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/19.csv")
transofposs_imperfective_connective1_19.head()

                                            stimulus        he       she
0  Miss Smith was passing a sandwich to Mr. Smith...  0.064449  0.935551
1  The woman was passing a sandwich to the man be...  0.484387  0.515613
2        Mary was passing a sandwich to John because  0.396289  0.603711
3        Alice was passing a sandwich to Bob because  0.346316  0.653684
4  The actress was passing a sandwich to the acto...  0.283192  0.716808

In [297]:
# female subject
transofposs_imperfective_connective1_19f = transofposs_imperfective_connective1_19[0:12]
transofposs_imperfective_connective1_19f = transofposs_imperfective_connective1_19f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_19m = transofposs_imperfective_connective1_19[12:24]

#### female subject

In [298]:
transofposs_imperfective_connective1_19f

                                             stimulus       she        he
0   Miss Smith was passing a sandwich to Mr. Smith...  0.935551  0.064449
1   The woman was passing a sandwich to the man be...  0.515613  0.484387
2         Mary was passing a sandwich to John because  0.603711  0.396289
3         Alice was passing a sandwich to Bob because  0.653684  0.346316
4   The actress was passing a sandwich to the acto...  0.716808  0.283192
5   The girl was passing a sandwich to the boy bec...  0.581553  0.418447
6   Mrs. Taylor was passing a sandwich to Mr. Will...  0.660797  0.339203
7        Emma was passing a sandwich to David because  0.727474  0.272526
8   The princess was passing a sandwich to the pri...  0.604730  0.395270
9      Sarah was passing a sandwich to Robert because  0.735082  0.264918
10  Mrs. Williams was passing a sandwich to  Mr. T...  0.663999  0.336001
11       Emily was passing a sandwich to Paul because  0.639148  0.360852

In [299]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_19f,'he'))

P('subj-pron'|subj=female) =  0.6698458393414816
P('non-subj-pron'|subj=female) =  0.3301541581749916

In [300]:
c1_average_subj_female_subj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19f,'she')
c1_average_subj_female_obj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19f,'he')

#### male subject

In [301]:
transofposs_imperfective_connective1_19m

                                             stimulus        he       she
12  Mr. Smith was passing a sandwich to Miss Smith...  0.631198  0.368802
13  The man was passing a sandwich to the woman be...  0.563621  0.436380
14        John was passing a sandwich to Mary because  0.645293  0.354707
15        Bob was passing a sandwich to Alice because  0.307102  0.692898
16  The actor was passing a sandwich to the actres...  0.409765  0.590235
17  The boy was passing a sandwich to the girl bec...  0.562549  0.437451
18  Mr. William was passing a sandwich to  Mrs. Ta...  0.363062  0.636938
19       David was passing a sandwich to Emma because  0.552128  0.447872
20  The prince was passing a sandwich to the princ...  0.711056  0.288944
21     Robert was passing a sandwich to Sarah because  0.276116  0.723884
22  Mr. Taylor was passing a sandwich to Mrs. Will...  0.243826  0.756174
23       Paul was passing a sandwich to Emily because  0.393902  0.606098

In [302]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_19m,'she'))

P('subj-pron'|subj=male) =  0.4716348002354304
P('non-subj-pron'|subj=male) =  0.5283652171492577

In [303]:
c1_average_subj_male_subj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19m,'he')
c1_average_subj_male_obj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19m,'she')

### verb: "serving"

In [304]:
transofposs_imperfective_connective1_20 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective1/20.csv")
transofposs_imperfective_connective1_20.head()

                                            stimulus        he       she
0  Miss Smith was serving a chili to Mr. Smith be...  0.041525  0.958475
1   The woman was serving a chili to the man because  0.470282  0.529718
2           Mary was serving a chili to John because  0.085737  0.914263
3           Alice was serving a chili to Bob because  0.062630  0.937370
4  The actress was serving a chili to the actor b...  0.139120  0.860880

In [305]:
# female subject
transofposs_imperfective_connective1_20f = transofposs_imperfective_connective1_20[0:12]
transofposs_imperfective_connective1_20f = transofposs_imperfective_connective1_20f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_20m = transofposs_imperfective_connective1_20[12:24]

#### female subject

In [306]:
transofposs_imperfective_connective1_20f

                                             stimulus       she        he
0   Miss Smith was serving a chili to Mr. Smith be...  0.958475  0.041525
1    The woman was serving a chili to the man because  0.529718  0.470282
2            Mary was serving a chili to John because  0.914263  0.085737
3            Alice was serving a chili to Bob because  0.937370  0.062630
4   The actress was serving a chili to the actor b...  0.860880  0.139120
5     The girl was serving a chili to the boy because  0.740589  0.259411
6   Mrs. Taylor was serving a chili to Mr. William...  0.808854  0.191146
7           Emma was serving a chili to David because  0.910449  0.089551
8   The princess was serving a chili to the prince...  0.806737  0.193263
9         Sarah was serving a chili to Robert because  0.902055  0.097945
10  Mrs. Williams was serving a chili to Mr. Taylo...  0.826809  0.173191
11          Emily was serving a chili to Paul because  0.830530  0.169470

In [307]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_20f,'he'))

P('subj-pron'|subj=female) =  0.8355607092380524
P('non-subj-pron'|subj=female) =  0.1644393103197217

In [308]:
c1_average_subj_female_subj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20f,'she')
c1_average_subj_female_obj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20f,'he')

#### male subject

In [309]:
transofposs_imperfective_connective1_20m

                                             stimulus        he       she
12  Mr. Smith was serving a chili to Miss Smith be...  0.732444  0.267556
13   The man was serving a chili to the woman because  0.562291  0.437709
14           John was serving a chili to Mary because  0.706926  0.293074
15           Bob was serving a chili to Alice because  0.531670  0.468330
16  The actor was serving a chili to the actress b...  0.523122  0.476878
17    The boy was serving a chili to the girl because  0.671633  0.328367
18  Mr. William was serving a chili to  Mrs. Taylo...  0.514292  0.485708
19          David was serving a chili to Emma because  0.701053  0.298947
20  The prince was serving a chili to the princess...  0.830750  0.169250
21        Robert was serving a chili to Sarah because  0.522826  0.477174
22  Mr. Taylor was serving a chili to Mrs. William...  0.346342  0.653658
23          Paul was serving a chili to Emily because  0.514539  0.485461

In [310]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_20m,'she'))

P('subj-pron'|subj=male) =  0.5964905122915903
P('non-subj-pron'|subj=male) =  0.4035094790160656

In [311]:
c1_average_subj_male_subj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20m,'he')
c1_average_subj_male_obj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20m,'she')

## Summary of Results

In [312]:
c1_results_fsubj_subjpron = pd.DataFrame(list(c1_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c1_results_fsubj_objpron = pd.DataFrame(list(c1_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c1_results_fsubj = c1_results_fsubj_subjpron.merge(c1_results_fsubj_objpron)
c1_results_fsubj

            verb  subj_ref_female_subj  obj_ref_female_subj
0       chucking              0.666895             0.333105
1       flinging              0.651702             0.348298
2        kicking              0.674837             0.325163
3        lobbing              0.532279             0.467721
4        rolling              0.670222             0.329778
5       throwing              0.616943             0.383057
6        tossing              0.592263             0.407738
7       bringing              0.724995             0.275005
8     forwarding              0.673414             0.326585
9        mailing              0.815336             0.184664
10      shipping              0.763749             0.236251
11  transmitting              0.794226             0.205774
12        wiring              0.699098             0.300902
13      carrying              0.834445             0.165555
14    delivering              0.702302             0.297698
15        giving              0.693334             0.306666
16       handing              0.686294             0.313706
17       passing              0.669846             0.330154
18       serving              0.835561             0.164439

In [313]:
c1_results_msubj_subjpron = pd.DataFrame(list(c1_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c1_results_msubj_objpron = pd.DataFrame(list(c1_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c1_results_msubj = c1_results_msubj_subjpron.merge(c1_results_msubj_objpron)
c1_results_msubj

            verb  subj_ref_male_subj  obj_ref_male_subj
0       chucking            0.390973           0.609027
1       flinging            0.414223           0.585777
2        kicking            0.392358           0.607642
3        lobbing            0.321571           0.678429
4        rolling            0.472966           0.527034
5       throwing            0.414656           0.585344
6        tossing            0.333883           0.666117
7       bringing            0.367977           0.632023
8     forwarding            0.404026           0.595974
9        mailing            0.541272           0.458728
10      shipping            0.373801           0.626199
11  transmitting            0.476252           0.523748
12        wiring            0.435978           0.564022
13      carrying            0.465097           0.534903
14    delivering            0.338019           0.661981
15        giving            0.440423           0.559577
16       handing            0.367439           0.632561
17       passing            0.471635           0.528365
18       serving            0.596491           0.403509

In [314]:
c1_results = c1_results_fsubj.merge(c1_results_msubj)
c1_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,chucking,0.666895,0.333105,0.390973,0.609027
1,flinging,0.651702,0.348298,0.414223,0.585777
2,kicking,0.674837,0.325163,0.392358,0.607642
3,lobbing,0.532279,0.467721,0.321571,0.678429
4,rolling,0.670222,0.329778,0.472966,0.527034
5,throwing,0.616943,0.383057,0.414656,0.585344
6,tossing,0.592263,0.407738,0.333883,0.666117
7,bringing,0.724995,0.275005,0.367977,0.632023
8,forwarding,0.673414,0.326585,0.404026,0.595974
9,mailing,0.815336,0.184664,0.541272,0.458728
10,shipping,0.763749,0.236251,0.373801,0.626199
11,transmitting,0.794226,0.205774,0.476252,0.523748
12,wiring,0.699098,0.300902,0.435978,0.564022
13,carrying,0.834445,0.165555,0.465097,0.534903
14,delivering,0.702302,0.297698,0.338019,0.661981
15,giving,0.693334,0.306666,0.440423,0.559577
16,handing,0.686294,0.313706,0.367439,0.632561
17,passing,0.669846,0.330154,0.471635,0.528365
18,serving,0.835561,0.164439,0.596491,0.403509

In [315]:
print("P(subj_reference |subj=female)", compute_average(c1_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c1_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.6998809977973763
P(obj_reference |subj=female) 0.30011900117326723

In [316]:
print("P(subj_reference |subj=male)", compute_average(c1_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c1_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.42205469231856496
P(obj_reference |subj=male) 0.5779453067664515

## Connective: "and, as a result"

In [317]:
c2_average_subj_female_subj_pron = {}
c2_average_subj_female_obj_pron = {}
c2_average_subj_male_subj_pron = {}
c2_average_subj_male_obj_pron = {}

### verb: "chucking"

In [318]:
transofposs_imperfective_connective2_1 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/1.csv")
transofposs_imperfective_connective2_1.head()

                                            stimulus        he       she
0  Miss Smith was chucking a wrench to Mr. Smith ...  0.256153  0.743847
1  The woman was chucking a wrench to the man and...  0.612586  0.387414
2  Mary was chucking a wrench to John and, as a r...  0.260632  0.739368
3  Alice was chucking a wrench to Bob and, as a r...  0.358459  0.641541
4  The actress was chucking a wrench to the actor...  0.522436  0.477564

In [319]:
# female subject
transofposs_imperfective_connective2_1f = transofposs_imperfective_connective2_1[0:12]
transofposs_imperfective_connective2_1f = transofposs_imperfective_connective2_1f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_1m = transofposs_imperfective_connective2_1[12:24]

#### female subject

In [320]:
transofposs_imperfective_connective2_1f

                                             stimulus       she        he
0   Miss Smith was chucking a wrench to Mr. Smith ...  0.743847  0.256153
1   The woman was chucking a wrench to the man and...  0.387414  0.612586
2   Mary was chucking a wrench to John and, as a r...  0.739368  0.260632
3   Alice was chucking a wrench to Bob and, as a r...  0.641541  0.358459
4   The actress was chucking a wrench to the actor...  0.477564  0.522436
5   The girl was chucking a wrench to the boy and,...  0.408867  0.591133
6   Mrs. Taylor was chucking a wrench to Mr. Willi...  0.551494  0.448506
7   Emma was chucking a wrench to David and, as a ...  0.728715  0.271285
8   The princess was chucking a wrench to the prin...  0.566091  0.433909
9   Sarah was chucking a wrench to Robert and, as ...  0.755935  0.244065
10  Mrs. Williams was chucking a wrench to  Mr. Ta...  0.575096  0.424904
11  Emily was chucking a wrench to Paul and, as a ...  0.754827  0.245173

In [321]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_1f,'he'))

P('subj-pron'|subj=female) =  0.6108965873718262
P('non-subj-pron'|subj=female) =  0.3891034039358298

In [322]:
#c2_average_subj_female_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1f,'she')
#c2_average_subj_female_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1f,'he')

#### male subject

In [323]:
transofposs_imperfective_connective2_1m

                                             stimulus        he       she
12  Mr. Smith was chucking a wrench to Miss Smith ...  0.468383  0.531617
13  The man was chucking a wrench to the woman and...  0.838463  0.161537
14  John was chucking a wrench to Mary and, as a r...  0.643756  0.356244
15  Bob was chucking a wrench to Alice and, as a r...  0.898182  0.101818
16  The actor was chucking a wrench to the actress...  0.870061  0.129939
17  The boy was chucking a wrench to the girl and,...  0.893756  0.106244
18  Mr. William was chucking a wrench to  Mrs. Tay...  0.549410  0.450590
19  David was chucking a wrench to Emma and, as a ...  0.583072  0.416928
20  The prince was chucking a wrench to the prince...  0.685368  0.314632
21  Robert was chucking a wrench to Sarah and, as ...  0.753765  0.246235
22  Mr. Taylor was chucking a wrench to Mrs. Willi...  0.517983  0.482017
23  Paul was chucking a wrench to Emily and, as a ...  0.580960  0.419040

In [324]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_1m,'she'))

P('subj-pron'|subj=male) =  0.6902631695071856
P('non-subj-pron'|subj=male) =  0.30973682055870694

In [325]:
#c2_average_subj_male_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1m,'he')
#c2_average_subj_male_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1m,'she')

### verb: "flinging"

In [326]:
transofposs_imperfective_connective2_2 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/2.csv")
transofposs_imperfective_connective2_2.head()

                                            stimulus        he       she
0  Miss Smith was flinging a frisbee to Mr. Smith...  0.258988  0.741012
1  The woman was flinging a frisbee to the man an...  0.627067  0.372933
2  Mary was flinging a frisbee to John and, as a ...  0.325783  0.674217
3  Alice was flinging a frisbee to Bob and, as a ...  0.403724  0.596276
4  The actress was flinging a frisbee to the acto...  0.562894  0.437106

In [327]:
# female subject
transofposs_imperfective_connective2_2f = transofposs_imperfective_connective2_2[0:12]
transofposs_imperfective_connective2_2f = transofposs_imperfective_connective2_2f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_2m = transofposs_imperfective_connective2_2[12:24]

#### female subject

In [328]:
transofposs_imperfective_connective2_2f

                                             stimulus       she        he
0   Miss Smith was flinging a frisbee to Mr. Smith...  0.741012  0.258988
1   The woman was flinging a frisbee to the man an...  0.372933  0.627067
2   Mary was flinging a frisbee to John and, as a ...  0.674217  0.325783
3   Alice was flinging a frisbee to Bob and, as a ...  0.596276  0.403724
4   The actress was flinging a frisbee to the acto...  0.437106  0.562894
5   The girl was flinging a frisbee to the boy and...  0.363128  0.636872
6   Mrs. Taylor was flinging a frisbee to Mr. Will...  0.564235  0.435765
7   Emma was flinging a frisbee to David and, as a...  0.676794  0.323206
8   The princess was flinging a frisbee to the pri...  0.498323  0.501677
9   Sarah was flinging a frisbee to Robert and, as...  0.660358  0.339642
10  Mrs. Williams was flinging a frisbee to  Mr. T...  0.572989  0.427010
11  Emily was flinging a frisbee to Paul and, as a...  0.735708  0.264292

In [329]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_2f,'he'))

P('subj-pron'|subj=female) =  0.5744233354926109
P('non-subj-pron'|subj=female) =  0.42557665705680847

In [330]:
c2_average_subj_female_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2f,'she')
c2_average_subj_female_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2f,'he')

#### male subject

In [331]:
transofposs_imperfective_connective2_2m

                                             stimulus        he       she
12  Mr. Smith was flinging a frisbee to Miss Smith...  0.432580  0.567420
13  The man was flinging a frisbee to the woman an...  0.816330  0.183670
14  John was flinging a frisbee to Mary and, as a ...  0.586636  0.413364
15  Bob was flinging a frisbee to Alice and, as a ...  0.870827  0.129173
16  The actor was flinging a frisbee to the actres...  0.858602  0.141398
17  The boy was flinging a frisbee to the girl and...  0.900810  0.099190
18  Mr. William was flinging a frisbee to  Mrs. Ta...  0.515739  0.484261
19  David was flinging a frisbee to Emma and, as a...  0.609426  0.390574
20  The prince was flinging a frisbee to the princ...  0.709719  0.290281
21  Robert was flinging a frisbee to Sarah and, as...  0.732219  0.267781
22  Mr. Taylor was flinging a frisbee to Mrs. Will...  0.482237  0.517763
23  Paul was flinging a frisbee to Emily and, as a...  0.563786  0.436214

In [332]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_2m,'she'))

P('subj-pron'|subj=male) =  0.6732425093650818
P('non-subj-pron'|subj=male) =  0.326757475733757

In [333]:
c2_average_subj_male_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2m,'he')
c2_average_subj_male_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2m,'she')

### verb: "kicking"

In [334]:
transofposs_imperfective_connective2_3 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/3.csv")
transofposs_imperfective_connective2_3.head()

                                            stimulus        he       she
0  Miss Smith was kicking a soccer ball to Mr. Sm...  0.266283  0.733717
1  The woman was kicking a soccer ball to the man...  0.624925  0.375075
2  Mary was kicking a soccer ball to John and, as...  0.273561  0.726439
3  Alice was kicking a soccer ball to Bob and, as...  0.432446  0.567554
4  The actress was kicking a soccer ball to the a...  0.597199  0.402801

In [335]:
# female subject
transofposs_imperfective_connective2_3f = transofposs_imperfective_connective2_3[0:12]
transofposs_imperfective_connective2_3f = transofposs_imperfective_connective2_3f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_3m = transofposs_imperfective_connective2_3[12:24]

#### female subject

In [336]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_3f,'he'))

P('subj-pron'|subj=female) =  0.5761752451459566
P('non-subj-pron'|subj=female) =  0.423824742436409

In [337]:
c2_average_subj_female_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3f,'she')
c2_average_subj_female_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3f,'he')

#### male subject

In [338]:
transofposs_imperfective_connective2_3m

                                             stimulus        he       she
12  Mr. Smith was kicking a soccer ball to Miss Sm...  0.710876  0.289124
13  The man was kicking a soccer ball to the woman...  0.929654  0.070346
14  John was kicking a soccer ball to Mary and, as...  0.834353  0.165647
15  Bob was kicking a soccer ball to Alice and, as...  0.959879  0.040121
16  The actor was kicking a soccer ball to the act...  0.938192  0.061807
17  The boy was kicking a soccer ball to the girl ...  0.968580  0.031420
18  Mr. William was kicking a soccer ball to  Mrs....  0.618402  0.381598
19  David was kicking a soccer ball to Emma and, a...  0.832948  0.167052
20  The prince was kicking a soccer ball to the pr...  0.886795  0.113205
21  Robert was kicking a soccer ball to Sarah and,...  0.929695  0.070305
22  Mr. Taylor was kicking a soccer ball to Mrs. W...  0.575084  0.424916
23  Paul was kicking a soccer ball to Emily and, a...  0.837672  0.162328

In [339]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_3m,'she'))

P('subj-pron'|subj=male) =  0.8351775060097376
P('non-subj-pron'|subj=male) =  0.16482250827054182

In [340]:
c2_average_subj_male_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3m,'he')
c2_average_subj_male_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3m,'she')

### verb: "lobbing"

In [341]:
transofposs_imperfective_connective2_4 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/4.csv")
transofposs_imperfective_connective2_4.head()

                                            stimulus        he       she
0  Miss Smith was lobbing a football to Mr. Smith...  0.314682  0.685318
1  The woman was lobbing a football to the man an...  0.619407  0.380593
2  Mary was lobbing a football to John and, as a ...  0.333134  0.666866
3  Alice was lobbing a football to Bob and, as a ...  0.418726  0.581274
4  The actress was lobbing a football to the acto...  0.484882  0.515118

In [342]:
# female subject
transofposs_imperfective_connective2_4f = transofposs_imperfective_connective2_4[0:12]
transofposs_imperfective_connective2_4f = transofposs_imperfective_connective2_4f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_4m = transofposs_imperfective_connective2_4[12:24]

#### female subject

In [343]:
transofposs_imperfective_connective2_4f

                                             stimulus       she        he
0   Miss Smith was lobbing a football to Mr. Smith...  0.685318  0.314682
1   The woman was lobbing a football to the man an...  0.380593  0.619407
2   Mary was lobbing a football to John and, as a ...  0.666866  0.333134
3   Alice was lobbing a football to Bob and, as a ...  0.581274  0.418726
4   The actress was lobbing a football to the acto...  0.515118  0.484882
5   The girl was lobbing a football to the boy and...  0.399514  0.600486
6   Mrs. Taylor was lobbing a football to Mr. Will...  0.573529  0.426471
7   Emma was lobbing a football to David and, as a...  0.706725  0.293275
8   The princess was lobbing a football to the pri...  0.536622  0.463378
9   Sarah was lobbing a football to Robert and, as...  0.654842  0.345158
10  Mrs. Williams was lobbing a football to  Mr. T...  0.575596  0.424404
11  Emily was lobbing a football to Paul and, as a...  0.761611  0.238389

In [344]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_4f,'he'))

P('subj-pron'|subj=female) =  0.586467333137989
P('non-subj-pron'|subj=female) =  0.41353266562024754

In [345]:
c2_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4f,'she')
c2_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4f,'he')

#### male subject

In [346]:
transofposs_imperfective_connective2_4m

                                             stimulus        he       she
12  Mr. Smith was lobbing a football to Miss Smith...  0.466492  0.533508
13  The man was lobbing a football to the woman an...  0.768419  0.231581
14  John was lobbing a football to Mary and, as a ...  0.588525  0.411475
15  Bob was lobbing a football to Alice and, as a ...  0.886007  0.113994
16  The actor was lobbing a football to the actres...  0.825077  0.174923
17  The boy was lobbing a football to the girl and...  0.882702  0.117298
18  Mr. William was lobbing a football to  Mrs. Ta...  0.410641  0.589359
19  David was lobbing a football to Emma and, as a...  0.522755  0.477245
20  The prince was lobbing a football to the princ...  0.616633  0.383367
21  Robert was lobbing a football to Sarah and, as...  0.697481  0.302519
22  Mr. Taylor was lobbing a football to Mrs. Will...  0.372958  0.627042
23  Paul was lobbing a football to Emily and, as a...  0.511549  0.488451

In [347]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_4m,'she'))

P('subj-pron'|subj=male) =  0.6291032284498215
P('non-subj-pron'|subj=male) =  0.3708967696875334

In [348]:
c2_average_subj_male_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4m,'he')
c2_average_subj_male_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4m,'she')

### verb: "rolling"

In [349]:
transofposs_imperfective_connective2_5 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/5.csv")
transofposs_imperfective_connective2_5.head()

                                            stimulus        he       she
0  Miss Smith was rolling a toy truck to Mr. Smit...  0.229551  0.770449
1  The woman was rolling a toy truck to the man a...  0.554753  0.445247
2  Mary was rolling a toy truck to John and, as a...  0.291919  0.708081
3  Alice was rolling a toy truck to Bob and, as a...  0.321971  0.678029
4  The actress was rolling a toy truck to the act...  0.375827  0.624173

In [350]:
# female subject
transofposs_imperfective_connective2_5f = transofposs_imperfective_connective2_5[0:12]
transofposs_imperfective_connective2_5f = transofposs_imperfective_connective2_5[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_5m = transofposs_imperfective_connective2_5[12:24]

#### female subject

In [351]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_5f,'he'))

P('subj-pron'|subj=female) =  0.44847143689791363
P('non-subj-pron'|subj=female) =  0.5515285599976778

In [352]:
c2_average_subj_female_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5f,'she')
c2_average_subj_female_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5f,'he')

#### male subject

In [353]:
transofposs_imperfective_connective2_5m

                                             stimulus        he       she
12  Mr. Smith was rolling a toy truck to Miss Smit...  0.638064  0.361936
13  The man was rolling a toy truck to the woman a...  0.926445  0.073555
14  John was rolling a toy truck to Mary and, as a...  0.718983  0.281017
15  Bob was rolling a toy truck to Alice and, as a...  0.941572  0.058428
16  The actor was rolling a toy truck to the actre...  0.902360  0.097640
17  The boy was rolling a toy truck to the girl an...  0.953497  0.046503
18  Mr. William was rolling a toy truck to  Mrs. T...  0.564793  0.435207
19  David was rolling a toy truck to Emma and, as ...  0.651621  0.348379
20  The prince was rolling a toy truck to the prin...  0.876420  0.123579
21  Robert was rolling a toy truck to Sarah and, a...  0.829202  0.170798
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.475445  0.524555
23  Paul was rolling a toy truck to Emily and, as ...  0.617824  0.382176

In [354]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_5m,'she'))

P('subj-pron'|subj=male) =  0.758018838862578
P('non-subj-pron'|subj=male) =  0.24198115865389505

In [355]:
c2_average_subj_male_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5m,'he')
c2_average_subj_male_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5m,'she')

### verb: "throwing"

In [356]:
transofposs_imperfective_connective2_6 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/6.csv")
transofposs_imperfective_connective2_6.head()

                                            stimulus        he       she
0  Miss Smith was throwing a hat to Mr. Smith and...  0.243211  0.756789
1  The woman was throwing a hat to the man and, a...  0.667166  0.332834
2  Mary was throwing a hat to John and, as a result,  0.319114  0.680886
3  Alice was throwing a hat to Bob and, as a result,  0.390798  0.609202
4  The actress was throwing a hat to the actor an...  0.562169  0.437832

In [357]:
# female subject
transofposs_imperfective_connective2_6f = transofposs_imperfective_connective2_6[0:12]
transofposs_imperfective_connective2_6f = transofposs_imperfective_connective2_6[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_6m = transofposs_imperfective_connective2_6[12:24]

#### female subject

In [358]:
transofposs_imperfective_connective2_6f

                                             stimulus       she        he
0   Miss Smith was throwing a hat to Mr. Smith and...  0.756789  0.243211
1   The woman was throwing a hat to the man and, a...  0.332834  0.667166
2   Mary was throwing a hat to John and, as a result,  0.680886  0.319114
3   Alice was throwing a hat to Bob and, as a result,  0.609202  0.390798
4   The actress was throwing a hat to the actor an...  0.437832  0.562169
5   The girl was throwing a hat to the boy and, as...  0.359036  0.640964
6   Mrs. Taylor was throwing a hat to Mr. Williams...  0.607727  0.392273
7   Emma was throwing a hat to David and, as a res...  0.722357  0.277643
8   The princess was throwing a hat to the prince ...  0.489648  0.510352
9   Sarah was throwing a hat to Robert and, as a r...  0.718847  0.281153
10  Mrs. Williams was throwing a hat to  Mr. Taylo...  0.611770  0.388230
11  Emily was throwing a hat to Paul and, as a res...  0.696710  0.303290
12  Mr. Smith was throwing a hat to Miss Smith and...  0.539518  0.460482
13  The man was throwing a hat to the woman and, a...  0.159322  0.840678
14  John was throwing a hat to Mary and, as a result,  0.362811  0.637189
15  Bob was throwing a hat to Alice and, as a result,  0.130690  0.869310
16  The actor was throwing a hat to the actress an...  0.195614  0.804386
17  The boy was throwing a hat to the girl and, as...  0.090549  0.909451
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.453328  0.546672
19  David was throwing a hat to Emma and, as a res...  0.425497  0.574503
20  The prince was throwing a hat to the princess ...  0.312914  0.687086
21  Robert was throwing a hat to Sarah and, as a r...  0.242380  0.757620
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.513630  0.486370
23  Paul was throwing a hat to Emily and, as a res...  0.358889  0.641111

In [359]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_6f,'he'))

P('subj-pron'|subj=female) =  0.45036580227315426
P('non-subj-pron'|subj=female) =  0.5496341971059641

In [360]:
c2_average_subj_female_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6f,'she')
c2_average_subj_female_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6f,'he')

#### male subject

In [361]:
transofposs_imperfective_connective2_6m

                                             stimulus        he       she
12  Mr. Smith was throwing a hat to Miss Smith and...  0.460482  0.539518
13  The man was throwing a hat to the woman and, a...  0.840678  0.159322
14  John was throwing a hat to Mary and, as a result,  0.637189  0.362811
15  Bob was throwing a hat to Alice and, as a result,  0.869310  0.130690
16  The actor was throwing a hat to the actress an...  0.804386  0.195614
17  The boy was throwing a hat to the girl and, as...  0.909451  0.090549
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.546672  0.453328
19  David was throwing a hat to Emma and, as a res...  0.574503  0.425497
20  The prince was throwing a hat to the princess ...  0.687086  0.312914
21  Robert was throwing a hat to Sarah and, as a r...  0.757620  0.242380
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.486370  0.513630
23  Paul was throwing a hat to Emily and, as a res...  0.641111  0.358889

In [362]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_6m,'she'))

P('subj-pron'|subj=male) =  0.6845715045928955
P('non-subj-pron'|subj=male) =  0.3154284966488679

In [363]:
c2_average_subj_male_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6m,'he')
c2_average_subj_male_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6m,'she')

### verb: "tossing"

In [364]:
transofposs_imperfective_connective2_7 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/7.csv")
transofposs_imperfective_connective2_7.head()

                                            stimulus        he       she
0  Miss Smith was tossing a dish towel to Mr. Smi...  0.311691  0.688309
1  The woman was tossing a dish towel to the man ...  0.644752  0.355248
2  Mary was tossing a dish towel to John and, as ...  0.368947  0.631053
3  Alice was tossing a dish towel to Bob and, as ...  0.400402  0.599598
4  The actress was tossing a dish towel to the ac...  0.518524  0.481476

In [365]:
# female subject
transofposs_imperfective_connective2_7f = transofposs_imperfective_connective2_7[0:12]
transofposs_imperfective_connective2_7f = transofposs_imperfective_connective2_7f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_7m = transofposs_imperfective_connective2_7[12:24]

#### female subject

In [366]:
transofposs_imperfective_connective2_7f

                                             stimulus       she        he
0   Miss Smith was tossing a dish towel to Mr. Smi...  0.688309  0.311691
1   The woman was tossing a dish towel to the man ...  0.355248  0.644752
2   Mary was tossing a dish towel to John and, as ...  0.631053  0.368947
3   Alice was tossing a dish towel to Bob and, as ...  0.599598  0.400402
4   The actress was tossing a dish towel to the ac...  0.481476  0.518524
5   The girl was tossing a dish towel to the boy a...  0.328494  0.671506
6   Mrs. Taylor was tossing a dish towel to Mr. Wi...  0.545360  0.454640
7   Emma was tossing a dish towel to David and, as...  0.676522  0.323478
8   The princess was tossing a dish towel to the p...  0.454483  0.545516
9   Sarah was tossing a dish towel to Robert and, ...  0.661361  0.338639
10  Mrs. Williams was tossing a dish towel to  Mr....  0.529215  0.470785
11  Emily was tossing a dish towel to Paul and, as...  0.691430  0.308570

In [367]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_7f,'he'))

P('subj-pron'|subj=female) =  0.553545854985714
P('non-subj-pron'|subj=female) =  0.44645415743192035

In [368]:
c2_average_subj_female_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7f,'she')
c2_average_subj_female_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7f,'he')

#### male subject

In [369]:
transofposs_imperfective_connective2_7m

                                             stimulus        he       she
12  Mr. Smith was tossing a dish towel to Miss Smi...  0.420788  0.579212
13  The man was tossing a dish towel to the woman ...  0.733838  0.266161
14  John was tossing a dish towel to Mary and, as ...  0.548416  0.451584
15  Bob was tossing a dish towel to Alice and, as ...  0.807323  0.192677
16  The actor was tossing a dish towel to the actr...  0.741974  0.258026
17  The boy was tossing a dish towel to the girl a...  0.820756  0.179244
18  Mr. William was tossing a dish towel to  Mrs. ...  0.515765  0.484235
19  David was tossing a dish towel to Emma and, as...  0.480252  0.519748
20  The prince was tossing a dish towel to the pri...  0.589433  0.410567
21  Robert was tossing a dish towel to Sarah and, ...  0.671564  0.328436
22  Mr. Taylor was tossing a dish towel to Mrs. Wi...  0.452629  0.547370
23  Paul was tossing a dish towel to Emily and, as...  0.535014  0.464986

In [370]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_7m,'she'))

P('subj-pron'|subj=male) =  0.6098128780722618
P('non-subj-pron'|subj=male) =  0.3901871119936307

In [371]:
c2_average_subj_male_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7m,'he')
c2_average_subj_male_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7m,'she')

### verb: "bringing"

In [372]:
transofposs_imperfective_connective2_8 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/8.csv")
transofposs_imperfective_connective2_8.head()

                                            stimulus        he       she
0  Miss Smith was bringing a glass of water to Mr...  0.217603  0.782397
1  The woman was bringing a glass of water to the...  0.570350  0.429650
2  Mary was bringing a glass of water to John and...  0.290568  0.709432
3  Alice was bringing a glass of water to Bob and...  0.275037  0.724963
4  The actress was bringing a glass of water to t...  0.230816  0.769184

In [373]:
# female subject
transofposs_imperfective_connective2_8f = transofposs_imperfective_connective2_8[0:12]
transofposs_imperfective_connective2_8f = transofposs_imperfective_connective2_8f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_8m = transofposs_imperfective_connective2_8[12:24]

#### female subject

In [374]:
transofposs_imperfective_connective2_8f

                                             stimulus       she        he
0   Miss Smith was bringing a glass of water to Mr...  0.782397  0.217603
1   The woman was bringing a glass of water to the...  0.429650  0.570350
2   Mary was bringing a glass of water to John and...  0.709432  0.290568
3   Alice was bringing a glass of water to Bob and...  0.724963  0.275037
4   The actress was bringing a glass of water to t...  0.769184  0.230816
5   The girl was bringing a glass of water to the ...  0.384390  0.615610
6   Mrs. Taylor was bringing a glass of water to M...  0.580922  0.419078
7   Emma was bringing a glass of water to David an...  0.702241  0.297759
8   The princess was bringing a glass of water to ...  0.606879  0.393121
9   Sarah was bringing a glass of water to Robert ...  0.618524  0.381476
10  Mrs. Williams was bringing a glass of water to...  0.575292  0.424708
11  Emily was bringing a glass of water to Paul an...  0.753434  0.246566

In [375]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_8f,'he'))

P('subj-pron'|subj=female) =  0.6364423185586929
P('non-subj-pron'|subj=female) =  0.36355768144130707

In [376]:
c2_average_subj_female_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8f,'she')
c2_average_subj_female_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8f,'he')

#### male subject

In [377]:
transofposs_imperfective_connective2_8m

                                             stimulus        he       she
12  Mr. Smith was bringing a glass of water to Mis...  0.388161  0.611839
13  The man was bringing a glass of water to the w...  0.578801  0.421199
14  John was bringing a glass of water to Mary and...  0.410091  0.589909
15  Bob was bringing a glass of water to Alice and...  0.706757  0.293243
16  The actor was bringing a glass of water to the...  0.570603  0.429397
17  The boy was bringing a glass of water to the g...  0.682200  0.317800
18  Mr. William was bringing a glass of water to  ...  0.500599  0.499401
19  David was bringing a glass of water to Emma an...  0.511605  0.488395
20  The prince was bringing a glass of water to th...  0.499424  0.500576
21  Robert was bringing a glass of water to Sarah ...  0.652469  0.347531
22  Mr. Taylor was bringing a glass of water to Mr...  0.438693  0.561307
23  Paul was bringing a glass of water to Emily an...  0.494629  0.505371

In [378]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_8m,'she'))

P('subj-pron'|subj=male) =  0.5361693575978279
P('non-subj-pron'|subj=male) =  0.46383065233627957

In [379]:
c2_average_subj_male_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8m,'he')
c2_average_subj_male_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8m,'she')

### verb: "forwarding"

In [380]:
transofposs_imperfective_connective2_9 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/9.csv")
transofposs_imperfective_connective2_9.head()

                                            stimulus        he       she
0  Miss Smith was forwarding a gossipy email to M...  0.140182  0.859818
1  The woman was forwarding a gossipy email to th...  0.539540  0.460460
2  Mary was forwarding a gossipy email to John an...  0.307605  0.692395
3  Alice was forwarding a gossipy email to Bob an...  0.291380  0.708620
4  The actress was forwarding a gossipy email to ...  0.211310  0.788690

In [381]:
# female subject
transofposs_imperfective_connective2_9f = transofposs_imperfective_connective2_9[0:12]
transofposs_imperfective_connective2_9f = transofposs_imperfective_connective2_9f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_9m = transofposs_imperfective_connective2_9[12:24]

#### female subject

In [382]:
transofposs_imperfective_connective2_9f

                                             stimulus       she        he
0   Miss Smith was forwarding a gossipy email to M...  0.859818  0.140182
1   The woman was forwarding a gossipy email to th...  0.460460  0.539540
2   Mary was forwarding a gossipy email to John an...  0.692395  0.307605
3   Alice was forwarding a gossipy email to Bob an...  0.708620  0.291380
4   The actress was forwarding a gossipy email to ...  0.788690  0.211310
5   The girl was forwarding a gossipy email to the...  0.472348  0.527652
6   Mrs. Taylor was forwarding a gossipy email to ...  0.717220  0.282780
7   Emma was forwarding a gossipy email to David a...  0.822917  0.177083
8   The princess was forwarding a gossipy email to...  0.559084  0.440916
9   Sarah was forwarding a gossipy email to Robert...  0.687953  0.312047
10  Mrs. Williams was forwarding a gossipy email t...  0.726965  0.273035
11  Emily was forwarding a gossipy email to Paul a...  0.822001  0.177999

In [383]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_9f,'he'))

P('subj-pron'|subj=female) =  0.6932058706879616
P('non-subj-pron'|subj=female) =  0.30679412682851154

In [384]:
c2_average_subj_female_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9f,'she')
c2_average_subj_female_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9f,'he')

#### male subject

In [385]:
transofposs_imperfective_connective2_9m

                                             stimulus        he       she
12  Mr. Smith was forwarding a gossipy email to Mi...  0.334540  0.665460
13  The man was forwarding a gossipy email to the ...  0.667917  0.332083
14  John was forwarding a gossipy email to Mary an...  0.448341  0.551659
15  Bob was forwarding a gossipy email to Alice an...  0.711205  0.288795
16  The actor was forwarding a gossipy email to th...  0.603957  0.396043
17  The boy was forwarding a gossipy email to the ...  0.707874  0.292126
18  Mr. William was forwarding a gossipy email to ...  0.338794  0.661206
19  David was forwarding a gossipy email to Emma a...  0.470781  0.529219
20  The prince was forwarding a gossipy email to t...  0.639434  0.360566
21  Robert was forwarding a gossipy email to Sarah...  0.696872  0.303128
22  Mr. Taylor was forwarding a gossipy email to M...  0.270840  0.729160
23  Paul was forwarding a gossipy email to Emily a...  0.634931  0.365069

In [386]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_9m,'she'))

P('subj-pron'|subj=male) =  0.5437903801600138
P('non-subj-pron'|subj=male) =  0.45620962729056674

In [387]:
c2_average_subj_male_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9m,'he')
c2_average_subj_male_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9m,'she')

### verb: "mailing"

In [388]:
transofposs_imperfective_connective2_10 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/10.csv")
transofposs_imperfective_connective2_10.head()

                                            stimulus        he       she
0  Miss Smith was mailing a letter to Mr. Smith a...  0.107666  0.892334
1  The woman was mailing a letter to the man and,...  0.472451  0.527549
2  Mary was mailing a letter to John and, as a re...  0.300909  0.699091
3  Alice was mailing a letter to Bob and, as a re...  0.273125  0.726875
4  The actress was mailing a letter to the actor ...  0.190246  0.809754

In [389]:
# female subject
transofposs_imperfective_connective2_10f = transofposs_imperfective_connective2_10[0:12]
transofposs_imperfective_connective2_10f = transofposs_imperfective_connective2_10f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_10m = transofposs_imperfective_connective2_10[12:24]

#### female subject

In [390]:
transofposs_imperfective_connective2_10f

                                             stimulus       she        he
0   Miss Smith was mailing a letter to Mr. Smith a...  0.892334  0.107666
1   The woman was mailing a letter to the man and,...  0.527549  0.472451
2   Mary was mailing a letter to John and, as a re...  0.699091  0.300909
3   Alice was mailing a letter to Bob and, as a re...  0.726875  0.273125
4   The actress was mailing a letter to the actor ...  0.809754  0.190246
5   The girl was mailing a letter to the boy and, ...  0.539623  0.460377
6   Mrs. Taylor was mailing a letter to Mr. Willia...  0.725196  0.274804
7   Emma was mailing a letter to David and, as a r...  0.874435  0.125565
8   The princess was mailing a letter to the princ...  0.577818  0.422182
9   Sarah was mailing a letter to Robert and, as a...  0.710145  0.289855
10  Mrs. Williams was mailing a letter to Mr. Tayl...  0.742685  0.257315
11  Emily was mailing a letter to Paul and, as a r...  0.856160  0.143840

In [391]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_10f,'he'))

P('subj-pron'|subj=female) =  0.7234721730152766
P('non-subj-pron'|subj=female) =  0.276527834435304

In [392]:
c2_average_subj_female_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10f,'she')
c2_average_subj_female_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10f,'he')

#### male subject

In [393]:
transofposs_imperfective_connective2_10m

                                             stimulus        he       she
12  Mr. Smith was mailing a letter to Miss Smith a...  0.265952  0.734048
13  The man was mailing a letter to the woman and,...  0.499290  0.500710
14  John was mailing a letter to Mary and, as a re...  0.490384  0.509616
15  Bob was mailing a letter to Alice and, as a re...  0.659784  0.340216
16  The actor was mailing a letter to the actress ...  0.496978  0.503022
17  The boy was mailing a letter to the girl and, ...  0.594565  0.405435
18  Mr. William was mailing a letter to  Mrs. Tayl...  0.366557  0.633443
19  David was mailing a letter to Emma and, as a r...  0.426769  0.573231
20  The prince was mailing a letter to the princes...  0.511700  0.488300
21  Robert was mailing a letter to Sarah and, as a...  0.553726  0.446274
22  Mr. Taylor was mailing a letter to Mrs. Willia...  0.256262  0.743738
23  Paul was mailing a letter to Emily and, as a r...  0.620726  0.379274

In [394]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_10m,'she'))

P('subj-pron'|subj=male) =  0.47855769097805023
P('non-subj-pron'|subj=male) =  0.5214422966043154

In [395]:
c2_average_subj_male_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10m,'he')
c2_average_subj_male_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10m,'she')

### verb: "shipping"

In [396]:
transofposs_imperfective_connective2_11 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/11.csv")
transofposs_imperfective_connective2_11.head()

                                            stimulus        he       she
0  Miss Smith was shipping a package to Mr. Smith...  0.153831  0.846169
1  The woman was shipping a package to the man an...  0.463343  0.536657
2  Mary was shipping a package to John and, as a ...  0.255138  0.744862
3  Alice was shipping a package to Bob and, as a ...  0.222282  0.777718
4  The actress was shipping a package to the acto...  0.231204  0.768796

In [397]:
# female subject
transofposs_imperfective_connective2_11f = transofposs_imperfective_connective2_11[0:12]
transofposs_imperfective_connective2_11f = transofposs_imperfective_connective2_11f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_11m = transofposs_imperfective_connective2_11[12:24]

#### female subject

In [398]:
transofposs_imperfective_connective2_11f

                                             stimulus       she        he
0   Miss Smith was shipping a package to Mr. Smith...  0.846169  0.153831
1   The woman was shipping a package to the man an...  0.536657  0.463343
2   Mary was shipping a package to John and, as a ...  0.744862  0.255138
3   Alice was shipping a package to Bob and, as a ...  0.777718  0.222282
4   The actress was shipping a package to the acto...  0.768796  0.231204
5   The girl was shipping a package to the boy and...  0.621746  0.378254
6   Mrs. Taylor was shipping a package to Mr. Will...  0.759452  0.240548
7   Emma was shipping a package to David and, as a...  0.862063  0.137937
8   The princess was shipping a package to the pri...  0.682657  0.317343
9   Sarah was shipping a package to Robert and, as...  0.763230  0.236770
10  Mrs. Williams was shipping a package to Mr. Ta...  0.773501  0.226499
11  Emily was shipping a package to Paul and, as a...  0.806426  0.193574

In [399]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_11f,'he'))

P('subj-pron'|subj=female) =  0.7452728947003683
P('non-subj-pron'|subj=female) =  0.254727091640234

In [400]:
c2_average_subj_female_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11f,'she')
c2_average_subj_female_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11f,'he')

#### male subject

In [401]:
transofposs_imperfective_connective2_11m

                                             stimulus        he       she
12  Mr. Smith was shipping a package to Miss Smith...  0.554477  0.445523
13  The man was shipping a package to the woman an...  0.803064  0.196936
14  John was shipping a package to Mary and, as a ...  0.603821  0.396179
15  Bob was shipping a package to Alice and, as a ...  0.864559  0.135441
16  The actor was shipping a package to the actres...  0.766561  0.233439
17  The boy was shipping a package to the girl and...  0.895627  0.104373
18  Mr. William was shipping a package to  Mrs. Ta...  0.418101  0.581899
19  David was shipping a package to Emma and, as a...  0.606685  0.393315
20  The prince was shipping a package to the princ...  0.819633  0.180367
21  Robert was shipping a package to Sarah and, as...  0.810004  0.189996
22  Mr. Taylor was shipping a package to Mrs. Will...  0.292205  0.707795
23  Paul was shipping a package to Emily and, as a...  0.643175  0.356825

In [402]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_11m,'she'))

P('subj-pron'|subj=male) =  0.6731593161821365
P('non-subj-pron'|subj=male) =  0.3268406968563795

In [403]:
c2_average_subj_male_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11m,'he')
c2_average_subj_male_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11m,'she')

### verb: "transmitting"

In [404]:
transofposs_imperfective_connective2_12 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/12.csv")
transofposs_imperfective_connective2_12.head()

                                            stimulus        he       she
0  Miss Smith was transmitting a message to Mr. S...  0.160283  0.839717
1  The woman was transmitting a message to the ma...  0.571579  0.428421
2  Mary was transmitting a message to John and, a...  0.301782  0.698218
3  Alice was transmitting a message to Bob and, a...  0.343176  0.656824
4  The actress was transmitting a message to the ...  0.354830  0.645170

In [405]:
# female subject
transofposs_imperfective_connective2_12f = transofposs_imperfective_connective2_12[0:12]
transofposs_imperfective_connective2_12f = transofposs_imperfective_connective2_12f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_12m = transofposs_imperfective_connective2_12[12:24]

#### female subject

In [406]:
transofposs_imperfective_connective2_12f

                                             stimulus       she        he
0   Miss Smith was transmitting a message to Mr. S...  0.839717  0.160283
1   The woman was transmitting a message to the ma...  0.428421  0.571579
2   Mary was transmitting a message to John and, a...  0.698218  0.301782
3   Alice was transmitting a message to Bob and, a...  0.656824  0.343176
4   The actress was transmitting a message to the ...  0.645170  0.354830
5   The girl was transmitting a message to the boy...  0.368710  0.631290
6   Mrs. Taylor was transmitting a message to Mr. ...  0.757223  0.242777
7   Emma was transmitting a message to David and, ...  0.814600  0.185400
8   The princess was transmitting a message to the...  0.452550  0.547450
9   Sarah was transmitting a message to Robert and...  0.654668  0.345332
10  Mrs. Williams was transmitting a message to Mr...  0.789407  0.210593
11  Emily was transmitting a message to Paul and, ...  0.823496  0.176504

In [407]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_12f,'he'))

P('subj-pron'|subj=female) =  0.6607503915826479
P('non-subj-pron'|subj=female) =  0.3392496220767498

In [408]:
c2_average_subj_female_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12f,'she')
c2_average_subj_female_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12f,'he')

#### male subject

In [409]:
transofposs_imperfective_connective2_12m

                                             stimulus        he       she
12  Mr. Smith was transmitting a message to Miss S...  0.245113  0.754887
13  The man was transmitting a message to the woma...  0.448942  0.551058
14  John was transmitting a message to Mary and, a...  0.279819  0.720181
15  Bob was transmitting a message to Alice and, a...  0.523845  0.476155
16  The actor was transmitting a message to the ac...  0.373306  0.626694
17  The boy was transmitting a message to the girl...  0.399796  0.600204
18  Mr. William was transmitting a message to  Mrs...  0.253514  0.746486
19  David was transmitting a message to Emma and, ...  0.341866  0.658134
20  The prince was transmitting a message to the p...  0.344376  0.655624
21  Robert was transmitting a message to Sarah and...  0.410693  0.589307
22  Mr. Taylor was transmitting a message to Mrs. ...  0.185148  0.814852
23  Paul was transmitting a message to Emily and, ...  0.476832  0.523168

In [410]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_12m,'she'))

P('subj-pron'|subj=male) =  0.35693751523892087
P('non-subj-pron'|subj=male) =  0.6430624897281328

In [411]:
c2_average_subj_male_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12m,'he')
c2_average_subj_male_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12m,'she')

### verb: "wiring"

In [412]:
transofposs_imperfective_connective2_14 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/14.csv")
transofposs_imperfective_connective2_14.head()

                                            stimulus        he       she
0  Miss Smith was wiring money to Mr. Smith and, ...  0.209986  0.790014
1  The woman was wiring money to the man and, as ...  0.565475  0.434525
2    Mary was wiring money to John and, as a result,  0.334461  0.665539
3    Alice was wiring money to Bob and, as a result,  0.430406  0.569594
4  The actress was wiring money to the actor and,...  0.341931  0.658069

In [413]:
# female subject
transofposs_imperfective_connective2_14f = transofposs_imperfective_connective2_14[0:12]
transofposs_imperfective_connective2_14f = transofposs_imperfective_connective2_14f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_14m = transofposs_imperfective_connective2_14[12:24]

#### female subject

In [414]:
transofposs_imperfective_connective2_14f

                                             stimulus       she        he
0   Miss Smith was wiring money to Mr. Smith and, ...  0.790014  0.209986
1   The woman was wiring money to the man and, as ...  0.434525  0.565475
2     Mary was wiring money to John and, as a result,  0.665539  0.334461
3     Alice was wiring money to Bob and, as a result,  0.569594  0.430406
4   The actress was wiring money to the actor and,...  0.658069  0.341931
5   The girl was wiring money to the boy and, as a...  0.435953  0.564047
6   Mrs. Taylor was wiring money to Mr. Williams a...  0.661167  0.338833
7    Emma was wiring money to David and, as a result,  0.744728  0.255272
8   The princess was wiring money to the prince an...  0.605963  0.394037
9   Sarah was wiring money to Robert and, as a res...  0.688723  0.311277
10  Mrs. Williams was wiring money to Mr. Taylor a...  0.646840  0.353160
11   Emily was wiring money to Paul and, as a result,  0.769804  0.230195

In [415]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_14f,'he'))

P('subj-pron'|subj=female) =  0.6392433568835258
P('non-subj-pron'|subj=female) =  0.36075666422645253

In [416]:
c2_average_subj_female_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14f,'she')
c2_average_subj_female_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14f,'he')

#### male subject

In [417]:
transofposs_imperfective_connective2_14m

                                             stimulus        he       she
12  Mr. Smith was wiring money to Miss Smith and, ...  0.424237  0.575763
13  The man was wiring money to the woman and, as ...  0.795375  0.204625
14    John was wiring money to Mary and, as a result,  0.414753  0.585247
15    Bob was wiring money to Alice and, as a result,  0.742243  0.257757
16  The actor was wiring money to the actress and,...  0.854668  0.145332
17  The boy was wiring money to the girl and, as a...  0.855575  0.144425
18  Mr. William was wiring money to  Mrs. Taylor a...  0.457747  0.542253
19   David was wiring money to Emma and, as a result,  0.584529  0.415471
20  The prince was wiring money to the princess an...  0.652703  0.347297
21  Robert was wiring money to Sarah and, as a res...  0.807881  0.192119
22  Mr. Taylor was wiring money to Mrs. Williams a...  0.356093  0.643907
23   Paul was wiring money to Emily and, as a result,  0.613635  0.386365

In [418]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_14m,'she'))

P('subj-pron'|subj=male) =  0.6299530218044916
P('non-subj-pron'|subj=male) =  0.3700469695031643

In [419]:
c2_average_subj_male_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14m,'he')
c2_average_subj_male_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14m,'she')

### verb: "carrying"

In [420]:
transofposs_imperfective_connective2_15 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/15.csv")
transofposs_imperfective_connective2_15.head()

                                            stimulus        he       she
0  Miss Smith was carrying a tray to Mr. Smith an...  0.188178  0.811822
1  The woman was carrying a tray to the man and, ...  0.421124  0.578876
2  Mary was carrying a tray to John and, as a res...  0.165344  0.834656
3  Alice was carrying a tray to Bob and, as a res...  0.182012  0.817988
4  The actress was carrying a tray to the actor a...  0.289545  0.710455

In [421]:
# female subject
transofposs_imperfective_connective2_15f = transofposs_imperfective_connective2_15[0:12]
transofposs_imperfective_connective2_15f = transofposs_imperfective_connective2_15f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_15m = transofposs_imperfective_connective2_15[12:24]

#### female subject

In [422]:
transofposs_imperfective_connective2_15f

                                             stimulus       she        he
0   Miss Smith was carrying a tray to Mr. Smith an...  0.811822  0.188178
1   The woman was carrying a tray to the man and, ...  0.578876  0.421124
2   Mary was carrying a tray to John and, as a res...  0.834656  0.165344
3   Alice was carrying a tray to Bob and, as a res...  0.817988  0.182012
4   The actress was carrying a tray to the actor a...  0.710455  0.289545
5   The girl was carrying a tray to the boy and, a...  0.666793  0.333207
6   Mrs. Taylor was carrying a tray to Mr. William...  0.736130  0.263870
7   Emma was carrying a tray to David and, as a re...  0.844708  0.155292
8   The princess was carrying a tray to the prince...  0.744995  0.255005
9   Sarah was carrying a tray to Robert and, as a ...  0.819738  0.180262
10  Mrs. Williams was carrying a tray to Mr. Taylo...  0.749766  0.250234
11  Emily was carrying a tray to Paul and, as a re...  0.854929  0.145071

In [423]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_15f,'he'))

P('subj-pron'|subj=female) =  0.7642380644877752
P('non-subj-pron'|subj=female) =  0.23576195538043976

In [424]:
c2_average_subj_female_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15f,'she')
c2_average_subj_female_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15f,'he')

#### male subject

In [425]:
transofposs_imperfective_connective2_15m

                                             stimulus        he       she
12  Mr. Smith was carrying a tray to Miss Smith an...  0.600594  0.399406
13  The man was carrying a tray to the woman and, ...  0.871743  0.128257
14  John was carrying a tray to Mary and, as a res...  0.710705  0.289295
15  Bob was carrying a tray to Alice and, as a res...  0.942064  0.057936
16  The actor was carrying a tray to the actress a...  0.878989  0.121011
17  The boy was carrying a tray to the girl and, a...  0.914631  0.085369
18  Mr. William was carrying a tray to  Mrs. Taylo...  0.477505  0.522495
19  David was carrying a tray to Emma and, as a re...  0.672223  0.327777
20  The prince was carrying a tray to the princess...  0.850867  0.149133
21  Robert was carrying a tray to Sarah and, as a ...  0.828205  0.171795
22  Mr. Taylor was carrying a tray to Mrs. William...  0.404576  0.595424
23  Paul was carrying a tray to Emily and, as a re...  0.671434  0.328566

In [426]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_15m,'she'))

P('subj-pron'|subj=male) =  0.7352947443723679
P('non-subj-pron'|subj=male) =  0.2647052633886536

In [427]:
c2_average_subj_male_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15m,'he')
c2_average_subj_male_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15m,'she')

### verb: "delivering"

In [428]:
transofposs_imperfective_connective2_16 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/16.csv")
transofposs_imperfective_connective2_16.head()

                                            stimulus        he       she
0  Miss Smith was delivering a subpoena to Mr. Sm...  0.201043  0.798957
1  The woman was delivering a subpoena to the man...  0.576180  0.423820
2  Mary was delivering a subpoena to John and, as...  0.313769  0.686231
3  Alice was delivering a subpoena to Bob and, as...  0.327352  0.672648
4  The actress was delivering a subpoena to the a...  0.288044  0.711956

In [429]:
# female subject
transofposs_imperfective_connective2_16f = transofposs_imperfective_connective2_16[0:12]
transofposs_imperfective_connective2_16f = transofposs_imperfective_connective2_16f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_16m = transofposs_imperfective_connective2_16[12:24]

#### female subject

In [430]:
transofposs_imperfective_connective2_16f

                                             stimulus       she        he
0   Miss Smith was delivering a subpoena to Mr. Sm...  0.798957  0.201043
1   The woman was delivering a subpoena to the man...  0.423820  0.576180
2   Mary was delivering a subpoena to John and, as...  0.686231  0.313769
3   Alice was delivering a subpoena to Bob and, as...  0.672648  0.327352
4   The actress was delivering a subpoena to the a...  0.711956  0.288044
5   The girl was delivering a subpoena to the boy ...  0.480205  0.519795
6   Mrs. Taylor was delivering a subpoena to Mr. W...  0.614933  0.385067
7   Emma was delivering a subpoena to David and, a...  0.785708  0.214292
8   The princess was delivering a subpoena to the ...  0.596205  0.403795
9   Sarah was delivering a subpoena to Robert and,...  0.724305  0.275695
10  Mrs. Williams was delivering a subpoena to Mr....  0.638382  0.361618
11  Emily was delivering a subpoena to Paul and, a...  0.823686  0.176314

In [431]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_16f,'he'))

P('subj-pron'|subj=female) =  0.6630862702926
P('non-subj-pron'|subj=female) =  0.33691372722387314

In [432]:
c2_average_subj_female_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16f,'she')
c2_average_subj_female_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16f,'he')

#### male subject

In [433]:
transofposs_imperfective_connective2_16m

                                             stimulus        he       she
12  Mr. Smith was delivering a subpoena to Miss Sm...  0.402116  0.597884
13  The man was delivering a subpoena to the woman...  0.803655  0.196345
14  John was delivering a subpoena to Mary and, as...  0.513989  0.486011
15  Bob was delivering a subpoena to Alice and, as...  0.690112  0.309888
16  The actor was delivering a subpoena to the act...  0.807323  0.192677
17  The boy was delivering a subpoena to the girl ...  0.885983  0.114017
18  Mr. William was delivering a subpoena to Mrs. ...  0.361517  0.638483
19  David was delivering a subpoena to Emma and, a...  0.657582  0.342418
20  The prince was delivering a subpoena to the pr...  0.748292  0.251708
21  Robert was delivering a subpoena to Sarah and,...  0.739981  0.260019
22  Mr. Taylor was delivering a subpoena to Mrs. W...  0.289327  0.710673
23  Paul was delivering a subpoena to Emily and, a...  0.596782  0.403218

In [434]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_16m,'she'))

P('subj-pron'|subj=male) =  0.6247215469678243
P('non-subj-pron'|subj=male) =  0.3752784449607134

In [435]:
c2_average_subj_male_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16m,'he')
c2_average_subj_male_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16m,'she')

### verb: "giving"

In [436]:
transofposs_imperfective_connective2_17 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/17.csv")
transofposs_imperfective_connective2_17.head()

                                            stimulus        he       she
0  Miss Smith was giving a sweater to Mr. Smith a...  0.194847  0.805153
1  The woman was giving a sweater to the man and,...  0.648147  0.351853
2  Mary was giving a sweater to John and, as a re...  0.391182  0.608818
3  Alice was giving a sweater to Bob and, as a re...  0.431648  0.568352
4  The actress was giving a sweater to the actor ...  0.409643  0.590357

In [437]:
# female subject
transofposs_imperfective_connective2_17f = transofposs_imperfective_connective2_17[0:12]
transofposs_imperfective_connective2_17f = transofposs_imperfective_connective2_17f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_17m = transofposs_imperfective_connective2_17[12:24]

#### female subject

In [438]:
transofposs_imperfective_connective2_17f

                                             stimulus       she        he
0   Miss Smith was giving a sweater to Mr. Smith a...  0.805153  0.194847
1   The woman was giving a sweater to the man and,...  0.351853  0.648147
2   Mary was giving a sweater to John and, as a re...  0.608818  0.391182
3   Alice was giving a sweater to Bob and, as a re...  0.568352  0.431648
4   The actress was giving a sweater to the actor ...  0.590357  0.409643
5   The girl was giving a sweater to the boy and, ...  0.403583  0.596417
6   Mrs. Taylor was giving a sweater to Mr. Willia...  0.693361  0.306639
7   Emma was giving a sweater to David and, as a r...  0.719914  0.280085
8   The princess was giving a sweater to the princ...  0.495928  0.504072
9   Sarah was giving a sweater to Robert and, as a...  0.705321  0.294679
10  Mrs. Williams was giving a sweater to Mr. Tayl...  0.719092  0.280908
11  Emily was giving a sweater to Paul and, as a r...  0.721018  0.278982

In [439]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_17f,'he'))

P('subj-pron'|subj=female) =  0.6152292142311732
P('non-subj-pron'|subj=female) =  0.3847707969446977

In [440]:
c2_average_subj_female_subj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17f,'she')
c2_average_subj_female_obj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17f,'he')

#### male subject

In [441]:
transofposs_imperfective_connective2_17m

                                             stimulus        he       she
12  Mr. Smith was giving a sweater to Miss Smith a...  0.435769  0.564231
13  The man was giving a sweater to the woman and,...  0.736132  0.263868
14  John was giving a sweater to Mary and, as a re...  0.549118  0.450882
15  Bob was giving a sweater to Alice and, as a re...  0.688911  0.311089
16  The actor was giving a sweater to the actress ...  0.744873  0.255127
17  The boy was giving a sweater to the girl and, ...  0.858203  0.141797
18  Mr. William was giving a sweater to  Mrs. Tayl...  0.487698  0.512302
19  David was giving a sweater to Emma and, as a r...  0.474074  0.525926
20  The prince was giving a sweater to the princes...  0.660460  0.339540
21  Robert was giving a sweater to Sarah and, as a...  0.673927  0.326073
22  Mr. Taylor was giving a sweater to Mrs. Willia...  0.391864  0.608136
23  Paul was giving a sweater to Emily and, as a r...  0.517902  0.482098

In [442]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_17m,'she'))

P('subj-pron'|subj=male) =  0.6015774756669998
P('non-subj-pron'|subj=male) =  0.3984225255747636

In [443]:
c2_average_subj_male_subj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17m,'he')
c2_average_subj_male_obj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17m,'she')

### verb: "handing"

In [444]:
transofposs_imperfective_connective2_18 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/18.csv")
transofposs_imperfective_connective2_18.head()

                                            stimulus        he       she
0  Miss Smith was handing a book to Mr. Smith and...  0.179213  0.820787
1  The woman was handing a book to the man and, a...  0.594744  0.405256
2  Mary was handing a book to John and, as a result,  0.395204  0.604796
3  Alice was handing a book to Bob and, as a result,  0.385583  0.614417
4  The actress was handing a book to the actor an...  0.326069  0.673931

In [445]:
# female subject
transofposs_imperfective_connective2_18f = transofposs_imperfective_connective2_18[0:12]
transofposs_imperfective_connective2_18f = transofposs_imperfective_connective2_18f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_18m = transofposs_imperfective_connective2_18[12:24]

#### female subject

In [446]:
transofposs_imperfective_connective2_18f

                                             stimulus       she        he
0   Miss Smith was handing a book to Mr. Smith and...  0.820787  0.179213
1   The woman was handing a book to the man and, a...  0.405256  0.594744
2   Mary was handing a book to John and, as a result,  0.604796  0.395204
3   Alice was handing a book to Bob and, as a result,  0.614417  0.385583
4   The actress was handing a book to the actor an...  0.673931  0.326069
5   The girl was handing a book to the boy and, as...  0.368575  0.631425
6   Mrs. Taylor was handing a book to Mr. Williams...  0.711870  0.288130
7   Emma was handing a book to David and, as a res...  0.754354  0.245646
8   The princess was handing a book to the prince ...  0.452885  0.547115
9   Sarah was handing a book to Robert and, as a r...  0.569829  0.430171
10  Mrs. Williams was handing a book to Mr. Taylor...  0.756393  0.243606
11  Emily was handing a book to Paul and, as a res...  0.739279  0.260721

In [447]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_18f,'he'))

P('subj-pron'|subj=female) =  0.6226978624860445
P('non-subj-pron'|subj=female) =  0.3773021325469017

In [448]:
c2_average_subj_female_subj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18f,'she')
c2_average_subj_female_obj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18f,'he')

#### male subject

In [449]:
transofposs_imperfective_connective2_18m

                                             stimulus        he       she
12  Mr. Smith was handing a book to Miss Smith and...  0.321623  0.678377
13  The man was handing a book to the woman and, a...  0.576515  0.423485
14  John was handing a book to Mary and, as a result,  0.454047  0.545953
15  Bob was handing a book to Alice and, as a result,  0.644463  0.355537
16  The actor was handing a book to the actress an...  0.518287  0.481713
17  The boy was handing a book to the girl and, as...  0.635940  0.364060
18  Mr. William was handing a book to Mrs. Taylor ...  0.383290  0.616710
19  David was handing a book to Emma and, as a res...  0.341942  0.658058
20  The prince was handing a book to the princess ...  0.516876  0.483124
21  Robert was handing a book to Sarah and, as a r...  0.591705  0.408295
22  Mr. Taylor was handing a book to Mrs. Williams...  0.304175  0.695825
23  Paul was handing a book to Emily and, as a res...  0.483620  0.516380

In [450]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_18m,'she'))

P('subj-pron'|subj=male) =  0.48104023436705273
P('non-subj-pron'|subj=male) =  0.5189597755670547

In [451]:
c2_average_subj_male_subj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18m,'he')
c2_average_subj_male_obj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18m,'she')

### verb: "passing"

In [452]:
transofposs_imperfective_connective2_19 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/19.csv")
transofposs_imperfective_connective2_19.head()

                                            stimulus        he       she
0  Miss Smith was passing a sandwich to Mr. Smith...  0.216607  0.783393
1  The woman was passing a sandwich to the man an...  0.551407  0.448593
2  Mary was passing a sandwich to John and, as a ...  0.275366  0.724634
3  Alice was passing a sandwich to Bob and, as a ...  0.254895  0.745105
4  The actress was passing a sandwich to the acto...  0.326749  0.673252

In [453]:
# female subject
transofposs_imperfective_connective2_19f = transofposs_imperfective_connective2_19[0:12]
transofposs_imperfective_connective2_19f = transofposs_imperfective_connective2_19f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_19m = transofposs_imperfective_connective2_19[12:24]

#### female subject

In [454]:
transofposs_imperfective_connective2_19f

                                             stimulus       she        he
0   Miss Smith was passing a sandwich to Mr. Smith...  0.783393  0.216607
1   The woman was passing a sandwich to the man an...  0.448593  0.551407
2   Mary was passing a sandwich to John and, as a ...  0.724634  0.275366
3   Alice was passing a sandwich to Bob and, as a ...  0.745105  0.254895
4   The actress was passing a sandwich to the acto...  0.673252  0.326749
5   The girl was passing a sandwich to the boy and...  0.360757  0.639243
6   Mrs. Taylor was passing a sandwich to Mr. Will...  0.701499  0.298501
7   Emma was passing a sandwich to David and, as a...  0.803461  0.196539
8   The princess was passing a sandwich to the pri...  0.529614  0.470386
9   Sarah was passing a sandwich to Robert and, as...  0.735008  0.264992
10  Mrs. Williams was passing a sandwich to  Mr. T...  0.730186  0.269814
11  Emily was passing a sandwich to Paul and, as a...  0.819866  0.180134

In [455]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_19f,'he'))

P('subj-pron'|subj=female) =  0.6712806150317192
P('non-subj-pron'|subj=female) =  0.32871940607825917

In [456]:
c2_average_subj_female_subj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19f,'she')
c2_average_subj_female_obj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19f,'he')

#### male subject

In [457]:
transofposs_imperfective_connective2_19m

                                             stimulus        he       she
12  Mr. Smith was passing a sandwich to Miss Smith...  0.462871  0.537129
13  The man was passing a sandwich to the woman an...  0.661156  0.338844
14  John was passing a sandwich to Mary and, as a ...  0.441210  0.558790
15  Bob was passing a sandwich to Alice and, as a ...  0.766904  0.233096
16  The actor was passing a sandwich to the actres...  0.759453  0.240547
17  The boy was passing a sandwich to the girl and...  0.680078  0.319922
18  Mr. William was passing a sandwich to  Mrs. Ta...  0.408371  0.591629
19  David was passing a sandwich to Emma and, as a...  0.533579  0.466421
20  The prince was passing a sandwich to the princ...  0.634813  0.365186
21  Robert was passing a sandwich to Sarah and, as...  0.686494  0.313506
22  Mr. Taylor was passing a sandwich to Mrs. Will...  0.322727  0.677273
23  Paul was passing a sandwich to Emily and, as a...  0.593222  0.406778

In [458]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_19m,'she'))

P('subj-pron'|subj=male) =  0.579240063826243
P('non-subj-pron'|subj=male) =  0.4207599212725957

In [459]:
c2_average_subj_male_subj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19m,'he')
c2_average_subj_male_obj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19m,'she')

### verb: "serving"

In [460]:
transofposs_imperfective_connective2_20 = pd.read_csv("../results/transfoxl/transofposs_imperfective/connective2/20.csv")
transofposs_imperfective_connective2_20.head()

                                            stimulus        he       she
0  Miss Smith was serving a chili to Mr. Smith an...  0.187263  0.812737
1  The woman was serving a chili to the man and, ...  0.446720  0.553280
2  Mary was serving a chili to John and, as a res...  0.192200  0.807800
3  Alice was serving a chili to Bob and, as a res...  0.201857  0.798143
4  The actress was serving a chili to the actor a...  0.336201  0.663799

In [461]:
# female subject
transofposs_imperfective_connective2_20f = transofposs_imperfective_connective2_20[0:12]
transofposs_imperfective_connective2_20f = transofposs_imperfective_connective2_20f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_20m = transofposs_imperfective_connective2_20[12:24]

#### female subject

In [462]:
transofposs_imperfective_connective2_20f

                                             stimulus       she        he
0   Miss Smith was serving a chili to Mr. Smith an...  0.812737  0.187263
1   The woman was serving a chili to the man and, ...  0.553280  0.446720
2   Mary was serving a chili to John and, as a res...  0.807800  0.192200
3   Alice was serving a chili to Bob and, as a res...  0.798143  0.201857
4   The actress was serving a chili to the actor a...  0.663799  0.336201
5   The girl was serving a chili to the boy and, a...  0.602154  0.397846
6   Mrs. Taylor was serving a chili to Mr. William...  0.715767  0.284233
7   Emma was serving a chili to David and, as a re...  0.805353  0.194647
8   The princess was serving a chili to the prince...  0.763450  0.236550
9   Sarah was serving a chili to Robert and, as a ...  0.853107  0.146893
10  Mrs. Williams was serving a chili to Mr. Taylo...  0.731447  0.268553
11  Emily was serving a chili to Paul and, as a re...  0.880825  0.119175

In [463]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_20f,'he'))

P('subj-pron'|subj=female) =  0.748988484342893
P('non-subj-pron'|subj=female) =  0.25101150882740814

In [464]:
c2_average_subj_female_subj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20f,'she')
c2_average_subj_female_obj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20f,'he')

#### male subject

In [465]:
transofposs_imperfective_connective2_20m

                                             stimulus        he       she
12  Mr. Smith was serving a chili to Miss Smith an...  0.816731  0.183269
13  The man was serving a chili to the woman and, ...  0.924806  0.075194
14  John was serving a chili to Mary and, as a res...  0.919460  0.080540
15  Bob was serving a chili to Alice and, as a res...  0.968694  0.031307
16  The actor was serving a chili to the actress a...  0.954098  0.045902
17  The boy was serving a chili to the girl and, a...  0.957301  0.042699
18  Mr. William was serving a chili to  Mrs. Taylo...  0.739963  0.260037
19  David was serving a chili to Emma and, as a re...  0.914155  0.085845
20  The prince was serving a chili to the princess...  0.944043  0.055957
21  Robert was serving a chili to Sarah and, as a ...  0.963734  0.036266
22  Mr. Taylor was serving a chili to Mrs. William...  0.584814  0.415186
23  Paul was serving a chili to Emily and, as a re...  0.874017  0.125983

In [466]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_20m,'she'))

P('subj-pron'|subj=male) =  0.8801512072483698
P('non-subj-pron'|subj=male) =  0.11984879554559787

In [467]:
c2_average_subj_male_subj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20m,'he')
c2_average_subj_male_obj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20m,'she')

## Summary of Results

In [468]:
c2_results_fsubj_subjpron = pd.DataFrame(list(c2_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c2_results_fsubj_objpron = pd.DataFrame(list(c2_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c2_results_fsubj = c2_results_fsubj_subjpron.merge(c2_results_fsubj_objpron)
c2_results_fsubj

            verb  subj_ref_female_subj  obj_ref_female_subj
0       flinging              0.574423             0.425577
1        kicking              0.576175             0.423825
2        lobbing              0.586467             0.413533
3        rolling              0.448471             0.551529
4       throwing              0.450366             0.549634
5        tossing              0.553546             0.446454
6       bringing              0.636442             0.363558
7     forwarding              0.693206             0.306794
8        mailing              0.723472             0.276528
9       shipping              0.745273             0.254727
10  transmitting              0.660750             0.339250
11        wiring              0.639243             0.360757
12      carrying              0.764238             0.235762
13    delivering              0.663086             0.336914
14        giving              0.615229             0.384771
15       handing              0.622698             0.377302
16       passing              0.671281             0.328719
17       serving              0.748988             0.251012

In [469]:
c2_results_msubj_subjpron = pd.DataFrame(list(c2_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c2_results_msubj_objpron = pd.DataFrame(list(c2_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c2_results_msubj = c2_results_msubj_subjpron.merge(c2_results_msubj_objpron)
c2_results_msubj

            verb  subj_ref_male_subj  obj_ref_male_subj
0       flinging            0.673243           0.326757
1        kicking            0.835178           0.164823
2        lobbing            0.629103           0.370897
3        rolling            0.758019           0.241981
4       throwing            0.684572           0.315428
5        tossing            0.609813           0.390187
6       bringing            0.536169           0.463831
7     forwarding            0.543790           0.456210
8        mailing            0.478558           0.521442
9       shipping            0.673159           0.326841
10  transmitting            0.356938           0.643062
11        wiring            0.629953           0.370047
12      carrying            0.735295           0.264705
13    delivering            0.624722           0.375278
14        giving            0.601577           0.398423
15       handing            0.481040           0.518960
16       passing            0.579240           0.420760
17       serving            0.880151           0.119849

In [470]:
c2_results = c2_results_fsubj.merge(c2_results_msubj)
c2_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flinging,0.574423,0.425577,0.673243,0.326757
1,kicking,0.576175,0.423825,0.835178,0.164823
2,lobbing,0.586467,0.413533,0.629103,0.370897
3,rolling,0.448471,0.551529,0.758019,0.241981
4,throwing,0.450366,0.549634,0.684572,0.315428
5,tossing,0.553546,0.446454,0.609813,0.390187
6,bringing,0.636442,0.363558,0.536169,0.463831
7,forwarding,0.693206,0.306794,0.543790,0.456210
8,mailing,0.723472,0.276528,0.478558,0.521442
9,shipping,0.745273,0.254727,0.673159,0.326841
10,transmitting,0.660750,0.339250,0.356938,0.643062
11,wiring,0.639243,0.360757,0.629953,0.370047
12,carrying,0.764238,0.235762,0.735295,0.264705
13,delivering,0.663086,0.336914,0.624722,0.375278
14,giving,0.615229,0.384771,0.601577,0.398423
15,handing,0.622698,0.377302,0.481040,0.518960
16,passing,0.671281,0.328719,0.579240,0.420760
17,serving,0.748988,0.251012,0.880151,0.119849

In [471]:
print("P(subj_reference |subj=female)", compute_average(c2_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c2_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.6318531402352232
P(obj_reference |subj=female) 0.36814686262773144

In [472]:
print("P(subj_reference |subj=male)", compute_average(c2_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c2_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.628362167764593
P(obj_reference |subj=male) 0.37163783220091345

In [473]:
# save results to csv
col_headers = ['verb','subj_ref_female_subj','obj_ref_female_subj','subj_ref_male_subj','obj_ref_male_subj']
np_results.to_csv("../results/transfoxl/summary/transofposs_imperfective-noprompt.csv",index=False,header=col_headers)
c1_results.to_csv("../results/transfoxl/summary/transofposs_imperfective-connective1.csv",index=False,header=col_headers)
c2_results.to_csv("../results/transfoxl/summary/transofposs_imperfective-connective2.csv",index=False,header=col_headers)