In [1]:
import pandas as pd
import numpy as np

In [2]:
def compute_average(df,col):
    return np.mean(df[col].values)

## No-prompt

In [3]:
np_average_subj_female_subj_pron = {}
np_average_subj_female_obj_pron = {}
np_average_subj_male_subj_pron = {}
np_average_subj_male_obj_pron = {}

### Verb: "chucking" (NOTE: gets tokenized to 'unk')

In [4]:
transofposs_imperfective_noprompt_1 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/1.csv")
transofposs_imperfective_noprompt_1.head()

                                          stimulus        He       She
0   Miss Smith was chucking a wrench to Mr. Smith.  0.480978  0.519022
1      The woman was chucking a wrench to the man.  0.428241  0.571759
2              Mary was chucking a wrench to John.  0.384234  0.615766
3              Alice was chucking a wrench to Bob.  0.298829  0.701171
4  The actress was chucking a wrench to the actor.  0.269870  0.730130

In [5]:
# female subject
transofposs_imperfective_noprompt_1f = transofposs_imperfective_noprompt_1[0:12]
transofposs_imperfective_noprompt_1f = transofposs_imperfective_noprompt_1f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_1m = transofposs_imperfective_noprompt_1[12:24]

#### female subject

In [6]:
transofposs_imperfective_noprompt_1f

                                             stimulus       She        He
0      Miss Smith was chucking a wrench to Mr. Smith.  0.519022  0.480978
1         The woman was chucking a wrench to the man.  0.571759  0.428241
2                 Mary was chucking a wrench to John.  0.615766  0.384234
3                 Alice was chucking a wrench to Bob.  0.701171  0.298829
4     The actress was chucking a wrench to the actor.  0.730130  0.269870
5          The girl was chucking a wrench to the boy.  0.586374  0.413626
6   Mrs. Taylor was chucking a wrench to Mr. Willi...  0.470646  0.529354
7                Emma was chucking a wrench to David.  0.656741  0.343259
8   The princess was chucking a wrench to the prince.  0.613121  0.386879
9              Sarah was chucking a wrench to Robert.  0.512196  0.487804
10  Mrs. Williams was chucking a wrench to  Mr. Ta...  0.369742  0.630258
11               Emily was chucking a wrench to Paul.  0.692369  0.307631

In [7]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_1f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_1f,'He'))

P('subj-pron'|subj=female) =  0.5865864157676697
P('non-subj-pron'|subj=female) =  0.41341358174880344

In [8]:
#np_average_subj_female_subj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1f,'She')
#np_average_subj_female_obj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1f,'He')

#### male subject

In [9]:
transofposs_imperfective_noprompt_1m

                                             stimulus        He       She
12     Mr. Smith was chucking a wrench to Miss Smith.  0.505488  0.494512
13        The man was chucking a wrench to the woman.  0.536684  0.463316
14                John was chucking a wrench to Mary.  0.655077  0.344923
15                Bob was chucking a wrench to Alice.  0.650578  0.349422
16    The actor was chucking a wrench to the actress.  0.663452  0.336548
17         The boy was chucking a wrench to the girl.  0.584814  0.415186
18  Mr. William was chucking a wrench to  Mrs. Tay...  0.524246  0.475754
19               David was chucking a wrench to Emma.  0.609955  0.390045
20  The prince was chucking a wrench to the princess.  0.602692  0.397308
21             Robert was chucking a wrench to Sarah.  0.632064  0.367937
22  Mr. Taylor was chucking a wrench to Mrs. Willi...  0.537711  0.462289
23               Paul was chucking a wrench to Emily.  0.639204  0.360796

In [10]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_1m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_1m,'She'))

P('subj-pron'|subj=male) =  0.5951637526353201
P('non-subj-pron'|subj=male) =  0.4048362597823143

In [11]:
#np_average_subj_male_subj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1m,'He')
#np_average_subj_male_obj_pron['chucking'] = compute_average(transofposs_imperfective_noprompt_1m,'She')

### Verb: "flinging"

In [12]:
transofposs_imperfective_noprompt_2 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/2.csv")
transofposs_imperfective_noprompt_2.head()

                                           stimulus        He       She
0   Miss Smith was flinging a frisbee to Mr. Smith.  0.537338  0.462662
1      The woman was flinging a frisbee to the man.  0.381608  0.618392
2              Mary was flinging a frisbee to John.  0.387132  0.612868
3              Alice was flinging a frisbee to Bob.  0.240305  0.759695
4  The actress was flinging a frisbee to the actor.  0.301995  0.698005

In [13]:
# female subject
transofposs_imperfective_noprompt_2f = transofposs_imperfective_noprompt_2[0:12]
transofposs_imperfective_noprompt_2f = transofposs_imperfective_noprompt_2f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_2m = transofposs_imperfective_noprompt_2[12:24]

#### female subject

In [14]:
transofposs_imperfective_noprompt_2f

                                             stimulus       She        He
0     Miss Smith was flinging a frisbee to Mr. Smith.  0.462662  0.537338
1        The woman was flinging a frisbee to the man.  0.618392  0.381608
2                Mary was flinging a frisbee to John.  0.612868  0.387132
3                Alice was flinging a frisbee to Bob.  0.759695  0.240305
4    The actress was flinging a frisbee to the actor.  0.698005  0.301995
5         The girl was flinging a frisbee to the boy.  0.608678  0.391322
6   Mrs. Taylor was flinging a frisbee to Mr. Will...  0.512822  0.487178
7               Emma was flinging a frisbee to David.  0.677145  0.322855
8   The princess was flinging a frisbee to the pri...  0.631397  0.368603
9             Sarah was flinging a frisbee to Robert.  0.599614  0.400386
10  Mrs. Williams was flinging a frisbee to  Mr. T...  0.491660  0.508340
11              Emily was flinging a frisbee to Paul.  0.752479  0.247521

In [15]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_2f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_2f,'He'))

P('subj-pron'|subj=female) =  0.6187846486767133
P('non-subj-pron'|subj=female) =  0.38121535753210384

In [16]:
np_average_subj_female_subj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2f,'She')
np_average_subj_female_obj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2f,'He')

#### male subject

In [17]:
transofposs_imperfective_noprompt_2m

                                             stimulus        He       She
12    Mr. Smith was flinging a frisbee to Miss Smith.  0.508734  0.491266
13       The man was flinging a frisbee to the woman.  0.508193  0.491807
14               John was flinging a frisbee to Mary.  0.588329  0.411671
15               Bob was flinging a frisbee to Alice.  0.523472  0.476528
16   The actor was flinging a frisbee to the actress.  0.555711  0.444289
17        The boy was flinging a frisbee to the girl.  0.520939  0.479061
18  Mr. William was flinging a frisbee to  Mrs. Ta...  0.596428  0.403572
19              David was flinging a frisbee to Emma.  0.511242  0.488758
20  The prince was flinging a frisbee to the princ...  0.478217  0.521783
21            Robert was flinging a frisbee to Sarah.  0.560889  0.439111
22  Mr. Taylor was flinging a frisbee to Mrs. Will...  0.539732  0.460268
23              Paul was flinging a frisbee to Emily.  0.491106  0.508894

In [18]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_2m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_2m,'She'))

P('subj-pron'|subj=male) =  0.5319160148501396
P('non-subj-pron'|subj=male) =  0.4680840000510216

In [19]:
np_average_subj_male_subj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2m,'He')
np_average_subj_male_obj_pron['flinging'] = compute_average(transofposs_imperfective_noprompt_2m,'She')

### Verb: "kicking"

In [20]:
transofposs_imperfective_noprompt_3 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/3.csv")
transofposs_imperfective_noprompt_3.head()

                                            stimulus        He       She
0  Miss Smith was kicking a soccer ball to Mr. Sm...  0.457798  0.542202
1    The woman was kicking a soccer ball to the man.  0.347015  0.652985
2            Mary was kicking a soccer ball to John.  0.326604  0.673396
3            Alice was kicking a soccer ball to Bob.  0.209892  0.790108
4  The actress was kicking a soccer ball to the a...  0.257775  0.742225

In [21]:
# female subject
transofposs_imperfective_noprompt_3f = transofposs_imperfective_noprompt_3[0:12]
transofposs_imperfective_noprompt_3f = transofposs_imperfective_noprompt_3f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_3m = transofposs_imperfective_noprompt_3[12:24]

#### female subject

In [22]:
transofposs_imperfective_noprompt_3f

                                             stimulus       She        He
0   Miss Smith was kicking a soccer ball to Mr. Sm...  0.542202  0.457798
1     The woman was kicking a soccer ball to the man.  0.652985  0.347015
2             Mary was kicking a soccer ball to John.  0.673396  0.326604
3             Alice was kicking a soccer ball to Bob.  0.790108  0.209892
4   The actress was kicking a soccer ball to the a...  0.742225  0.257775
5      The girl was kicking a soccer ball to the boy.  0.673564  0.326436
6   Mrs. Taylor was kicking a soccer ball to Mr. W...  0.594308  0.405692
7            Emma was kicking a soccer ball to David.  0.723949  0.276051
8   The princess was kicking a soccer ball to the ...  0.740614  0.259386
9          Sarah was kicking a soccer ball to Robert.  0.591118  0.408882
10  Mrs. Williams was kicking a soccer ball to  Mr...  0.503441  0.496559
11           Emily was kicking a soccer ball to Paul.  0.766677  0.233324

In [23]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_3f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_3f,'He'))

P('subj-pron'|subj=female) =  0.666215697924296
P('non-subj-pron'|subj=female) =  0.3337842995921771

In [24]:
np_average_subj_female_subj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3f,'She')
np_average_subj_female_obj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3f,'He')

#### male subject

In [25]:
transofposs_imperfective_noprompt_3m

                                             stimulus        He       She
12  Mr. Smith was kicking a soccer ball to Miss Sm...  0.483620  0.516380
13    The man was kicking a soccer ball to the woman.  0.449402  0.550598
14            John was kicking a soccer ball to Mary.  0.569991  0.430009
15            Bob was kicking a soccer ball to Alice.  0.591241  0.408759
16  The actor was kicking a soccer ball to the act...  0.578979  0.421021
17     The boy was kicking a soccer ball to the girl.  0.481700  0.518300
18  Mr. William was kicking a soccer ball to  Mrs....  0.542271  0.457729
19           David was kicking a soccer ball to Emma.  0.472395  0.527605
20  The prince was kicking a soccer ball to the pr...  0.616127  0.383873
21         Robert was kicking a soccer ball to Sarah.  0.555373  0.444627
22  Mr. Taylor was kicking a soccer ball to Mrs. W...  0.486178  0.513822
23           Paul was kicking a soccer ball to Emily.  0.455534  0.544466

In [26]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_3m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_3m,'She'))

P('subj-pron'|subj=male) =  0.5235675945878029
P('non-subj-pron'|subj=male) =  0.476432407895724

In [27]:
np_average_subj_male_subj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3m,'He')
np_average_subj_male_obj_pron['kicking'] = compute_average(transofposs_imperfective_noprompt_3m,'She')

### verb: "lobbing"

In [28]:
transofposs_imperfective_noprompt_4 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/4.csv")
transofposs_imperfective_noprompt_4.head()

                                           stimulus        He       She
0   Miss Smith was lobbing a football to Mr. Smith.  0.573370  0.426630
1      The woman was lobbing a football to the man.  0.409986  0.590014
2              Mary was lobbing a football to John.  0.375522  0.624478
3              Alice was lobbing a football to Bob.  0.267646  0.732354
4  The actress was lobbing a football to the actor.  0.260466  0.739534

In [29]:
# female subject
transofposs_imperfective_noprompt_4f = transofposs_imperfective_noprompt_4[0:12]
transofposs_imperfective_noprompt_4f = transofposs_imperfective_noprompt_4f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_4m = transofposs_imperfective_noprompt_4[12:24]

#### female subject

In [30]:
transofposs_imperfective_noprompt_4f

                                             stimulus       She        He
0     Miss Smith was lobbing a football to Mr. Smith.  0.426630  0.573370
1        The woman was lobbing a football to the man.  0.590014  0.409986
2                Mary was lobbing a football to John.  0.624478  0.375522
3                Alice was lobbing a football to Bob.  0.732354  0.267646
4    The actress was lobbing a football to the actor.  0.739534  0.260466
5         The girl was lobbing a football to the boy.  0.600841  0.399159
6   Mrs. Taylor was lobbing a football to Mr. Will...  0.461534  0.538466
7               Emma was lobbing a football to David.  0.663082  0.336918
8   The princess was lobbing a football to the pri...  0.628376  0.371624
9             Sarah was lobbing a football to Robert.  0.529243  0.470757
10  Mrs. Williams was lobbing a football to  Mr. T...  0.379653  0.620347
11              Emily was lobbing a football to Paul.  0.716725  0.283275

In [31]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_4f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_4f,'He'))

P('subj-pron'|subj=female) =  0.5910386790831884
P('non-subj-pron'|subj=female) =  0.4089613084991773

In [32]:
np_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4f,'She')
np_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4f,'He')

#### male subject

In [33]:
transofposs_imperfective_noprompt_4m

                                             stimulus        He       She
12    Mr. Smith was lobbing a football to Miss Smith.  0.495505  0.504495
13       The man was lobbing a football to the woman.  0.459513  0.540487
14               John was lobbing a football to Mary.  0.557437  0.442563
15               Bob was lobbing a football to Alice.  0.531500  0.468500
16   The actor was lobbing a football to the actress.  0.584040  0.415960
17        The boy was lobbing a football to the girl.  0.502384  0.497616
18  Mr. William was lobbing a football to  Mrs. Ta...  0.525541  0.474459
19              David was lobbing a football to Emma.  0.494293  0.505707
20  The prince was lobbing a football to the princ...  0.564730  0.435270
21            Robert was lobbing a football to Sarah.  0.557255  0.442745
22  Mr. Taylor was lobbing a football to Mrs. Will...  0.515707  0.484293
23              Paul was lobbing a football to Emily.  0.462817  0.537183

In [34]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_4m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_4m,'She'))

P('subj-pron'|subj=male) =  0.5208935166398684
P('non-subj-pron'|subj=male) =  0.47910648336013156

In [35]:
np_average_subj_male_subj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4m,'He')
np_average_subj_male_obj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_4m,'She')

### verb: "rolling"

In [36]:
transofposs_imperfective_noprompt_5 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/5.csv")
transofposs_imperfective_noprompt_5.head()

                                            stimulus        He       She
0   Miss Smith was rolling a toy truck to Mr. Smith.  0.372981  0.627019
1      The woman was rolling a toy truck to the man.  0.275254  0.724746
2              Mary was rolling a toy truck to John.  0.273572  0.726428
3              Alice was rolling a toy truck to Bob.  0.190031  0.809969
4  The actress was rolling a toy truck to the actor.  0.231748  0.768252

In [37]:
# female subject
transofposs_imperfective_noprompt_5f = transofposs_imperfective_noprompt_5[0:12]
transofposs_imperfective_noprompt_5f = transofposs_imperfective_noprompt_5f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_5m = transofposs_imperfective_noprompt_5[12:24]

#### female subject

In [38]:
transofposs_imperfective_noprompt_5f

                                             stimulus       She        He
0    Miss Smith was rolling a toy truck to Mr. Smith.  0.627019  0.372981
1       The woman was rolling a toy truck to the man.  0.724746  0.275254
2               Mary was rolling a toy truck to John.  0.726428  0.273572
3               Alice was rolling a toy truck to Bob.  0.809969  0.190031
4   The actress was rolling a toy truck to the actor.  0.768252  0.231748
5        The girl was rolling a toy truck to the boy.  0.709060  0.290940
6   Mrs. Taylor was rolling a toy truck to Mr. Wil...  0.613196  0.386804
7              Emma was rolling a toy truck to David.  0.756533  0.243467
8   The princess was rolling a toy truck to the pr...  0.729679  0.270321
9            Sarah was rolling a toy truck to Robert.  0.645988  0.354012
10  Mrs. Williams was rolling a toy truck to  Mr. ...  0.552849  0.447151
11             Emily was rolling a toy truck to Paul.  0.804050  0.195950

In [39]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_5f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_5f,'He'))

P('subj-pron'|subj=female) =  0.705647403995196
P('non-subj-pron'|subj=female) =  0.294352604697148

In [40]:
np_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_5f,'She')
np_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_noprompt_5f,'He')

#### male subject

In [41]:
transofposs_imperfective_noprompt_5m

                                             stimulus        He       She
12   Mr. Smith was rolling a toy truck to Miss Smith.  0.518323  0.481677
13      The man was rolling a toy truck to the woman.  0.539127  0.460873
14              John was rolling a toy truck to Mary.  0.667480  0.332520
15              Bob was rolling a toy truck to Alice.  0.649429  0.350571
16  The actor was rolling a toy truck to the actress.  0.626613  0.373387
17       The boy was rolling a toy truck to the girl.  0.563389  0.436611
18  Mr. William was rolling a toy truck to  Mrs. T...  0.581539  0.418461
19             David was rolling a toy truck to Emma.  0.577873  0.422127
20  The prince was rolling a toy truck to the prin...  0.678742  0.321258
21           Robert was rolling a toy truck to Sarah.  0.631599  0.368401
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.553299  0.446701
23             Paul was rolling a toy truck to Emily.  0.580500  0.419500

In [42]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_5m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_5m,'She'))

P('subj-pron'|subj=male) =  0.5973261296749115
P('non-subj-pron'|subj=male) =  0.4026738777756691

In [43]:
np_average_subj_male_subj_pron['rolling'] = compute_average(transofposs_imperfective_noprompt_5m,'He')
np_average_subj_male_obj_pron['rolling'] = compute_average(transofposs_imperfective_noprompt_5m,'She')

### verb: "throwing"

In [44]:
transofposs_imperfective_noprompt_6 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/6.csv")
transofposs_imperfective_noprompt_6.head()

                                       stimulus        He       She
0   Miss Smith was throwing a hat to Mr. Smith.  0.501911  0.498089
1      The woman was throwing a hat to the man.  0.361211  0.638789
2              Mary was throwing a hat to John.  0.386408  0.613592
3              Alice was throwing a hat to Bob.  0.221121  0.778879
4  The actress was throwing a hat to the actor.  0.225512  0.774488

In [45]:
# female subject
transofposs_imperfective_noprompt_6f = transofposs_imperfective_noprompt_6[0:12]
transofposs_imperfective_noprompt_6f = transofposs_imperfective_noprompt_6f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_6m = transofposs_imperfective_noprompt_6[12:24]

#### female subject

In [46]:
transofposs_imperfective_noprompt_6f

                                            stimulus       She        He
0        Miss Smith was throwing a hat to Mr. Smith.  0.498089  0.501911
1           The woman was throwing a hat to the man.  0.638789  0.361211
2                   Mary was throwing a hat to John.  0.613592  0.386408
3                   Alice was throwing a hat to Bob.  0.778879  0.221121
4       The actress was throwing a hat to the actor.  0.774488  0.225512
5            The girl was throwing a hat to the boy.  0.640261  0.359739
6    Mrs. Taylor was throwing a hat to Mr. Williams.  0.511464  0.488536
7                  Emma was throwing a hat to David.  0.697526  0.302474
8     The princess was throwing a hat to the prince.  0.677976  0.322024
9                Sarah was throwing a hat to Robert.  0.577678  0.422322
10  Mrs. Williams was throwing a hat to  Mr. Taylor.  0.488657  0.511343
11                 Emily was throwing a hat to Paul.  0.758633  0.241367

In [47]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_6f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_6f,'He'))

P('subj-pron'|subj=female) =  0.638002559542656
P('non-subj-pron'|subj=female) =  0.36199743797381717

In [48]:
np_average_subj_female_subj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6f,'She')
np_average_subj_female_obj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6f,'He')

#### male subject

In [49]:
transofposs_imperfective_noprompt_6m

                                           stimulus        He       She
12      Mr. Smith was throwing a hat to Miss Smith.  0.563837  0.436163
13         The man was throwing a hat to the woman.  0.550680  0.449320
14                 John was throwing a hat to Mary.  0.763304  0.236696
15                 Bob was throwing a hat to Alice.  0.677885  0.322115
16     The actor was throwing a hat to the actress.  0.654986  0.345014
17          The boy was throwing a hat to the girl.  0.574610  0.425390
18  Mr. William was throwing a hat to  Mrs. Taylor.  0.632112  0.367888
19                David was throwing a hat to Emma.  0.623252  0.376748
20   The prince was throwing a hat to the princess.  0.591509  0.408491
21              Robert was throwing a hat to Sarah.  0.631673  0.368327
22  Mr. Taylor was throwing a hat to Mrs. Williams.  0.591274  0.408726
23                Paul was throwing a hat to Emily.  0.664160  0.335840

In [50]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_6m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_6m,'She'))

P('subj-pron'|subj=male) =  0.6266069412231445
P('non-subj-pron'|subj=male) =  0.373393048842748

In [51]:
np_average_subj_male_subj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6m,'He')
np_average_subj_male_obj_pron['throwing'] = compute_average(transofposs_imperfective_noprompt_6m,'She')

### verb: "tossing"

In [52]:
transofposs_imperfective_noprompt_7 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/7.csv")
transofposs_imperfective_noprompt_7.head()

                                            stimulus        He       She
0  Miss Smith was tossing a dish towel to Mr. Smith.  0.491793  0.508207
1     The woman was tossing a dish towel to the man.  0.337821  0.662179
2             Mary was tossing a dish towel to John.  0.295644  0.704356
3             Alice was tossing a dish towel to Bob.  0.208946  0.791054
4  The actress was tossing a dish towel to the ac...  0.286441  0.713558

In [53]:
# female subject
transofposs_imperfective_noprompt_7f = transofposs_imperfective_noprompt_7[0:12]
transofposs_imperfective_noprompt_7f = transofposs_imperfective_noprompt_7f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_7m = transofposs_imperfective_noprompt_7[12:24]

#### female subject

In [54]:
transofposs_imperfective_noprompt_7f

                                             stimulus       She        He
0   Miss Smith was tossing a dish towel to Mr. Smith.  0.508207  0.491793
1      The woman was tossing a dish towel to the man.  0.662179  0.337821
2              Mary was tossing a dish towel to John.  0.704356  0.295644
3              Alice was tossing a dish towel to Bob.  0.791054  0.208946
4   The actress was tossing a dish towel to the ac...  0.713558  0.286441
5       The girl was tossing a dish towel to the boy.  0.648358  0.351642
6   Mrs. Taylor was tossing a dish towel to Mr. Wi...  0.552461  0.447539
7             Emma was tossing a dish towel to David.  0.680149  0.319851
8   The princess was tossing a dish towel to the p...  0.747125  0.252875
9           Sarah was tossing a dish towel to Robert.  0.626248  0.373752
10  Mrs. Williams was tossing a dish towel to  Mr....  0.523856  0.476144
11            Emily was tossing a dish towel to Paul.  0.767848  0.232152

In [55]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_7f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_7f,'He'))

P('subj-pron'|subj=female) =  0.6604500611623129
P('non-subj-pron'|subj=female) =  0.3395499301453431

In [56]:
np_average_subj_female_subj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7f,'She')
np_average_subj_female_obj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7f,'He')

#### male subject

In [57]:
transofposs_imperfective_noprompt_7m

                                             stimulus        He       She
12  Mr. Smith was tossing a dish towel to Miss Smith.  0.473988  0.526012
13     The man was tossing a dish towel to the woman.  0.520392  0.479608
14             John was tossing a dish towel to Mary.  0.610563  0.389437
15             Bob was tossing a dish towel to Alice.  0.475105  0.524895
16  The actor was tossing a dish towel to the actr...  0.585324  0.414676
17      The boy was tossing a dish towel to the girl.  0.556899  0.443101
18  Mr. William was tossing a dish towel to  Mrs. ...  0.545571  0.454429
19            David was tossing a dish towel to Emma.  0.492955  0.507045
20  The prince was tossing a dish towel to the pri...  0.606186  0.393814
21          Robert was tossing a dish towel to Sarah.  0.577819  0.422181
22  Mr. Taylor was tossing a dish towel to Mrs. Wi...  0.490396  0.509604
23            Paul was tossing a dish towel to Emily.  0.526018  0.473981

In [58]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_7m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_7m,'She'))

P('subj-pron'|subj=male) =  0.538434679309527
P('non-subj-pron'|subj=male) =  0.4615653057893117

In [59]:
np_average_subj_male_subj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7m,'He')
np_average_subj_male_obj_pron['tossing'] = compute_average(transofposs_imperfective_noprompt_7m,'She')

### verb: "bringing"

In [60]:
transofposs_imperfective_noprompt_8 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/8.csv")
transofposs_imperfective_noprompt_8.head()

                                            stimulus        He       She
0  Miss Smith was bringing a glass of water to Mr...  0.537870  0.462130
1  The woman was bringing a glass of water to the...  0.371150  0.628850
2        Mary was bringing a glass of water to John.  0.424314  0.575686
3        Alice was bringing a glass of water to Bob.  0.283415  0.716585
4  The actress was bringing a glass of water to t...  0.315111  0.684889

In [61]:
# female subject
transofposs_imperfective_noprompt_8f = transofposs_imperfective_noprompt_8[0:12]
transofposs_imperfective_noprompt_8f = transofposs_imperfective_noprompt_8f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_8m = transofposs_imperfective_noprompt_8[12:24]

#### female subject

In [62]:
transofposs_imperfective_noprompt_8f

                                             stimulus       She        He
0   Miss Smith was bringing a glass of water to Mr...  0.462130  0.537870
1   The woman was bringing a glass of water to the...  0.628850  0.371150
2         Mary was bringing a glass of water to John.  0.575686  0.424314
3         Alice was bringing a glass of water to Bob.  0.716585  0.283415
4   The actress was bringing a glass of water to t...  0.684889  0.315111
5   The girl was bringing a glass of water to the ...  0.626941  0.373059
6   Mrs. Taylor was bringing a glass of water to M...  0.462602  0.537398
7        Emma was bringing a glass of water to David.  0.649858  0.350142
8   The princess was bringing a glass of water to ...  0.665325  0.334675
9      Sarah was bringing a glass of water to Robert.  0.551825  0.448175
10  Mrs. Williams was bringing a glass of water to...  0.473373  0.526627
11       Emily was bringing a glass of water to Paul.  0.711669  0.288331

In [63]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_8f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_8f,'He'))

P('subj-pron'|subj=female) =  0.6008111437161764
P('non-subj-pron'|subj=female) =  0.39918887863556546

In [64]:
np_average_subj_female_subj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8f,'She')
np_average_subj_female_obj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8f,'He')

#### male subject

In [65]:
transofposs_imperfective_noprompt_8m

                                             stimulus        He       She
12  Mr. Smith was bringing a glass of water to Mis...  0.480626  0.519373
13  The man was bringing a glass of water to the w...  0.550908  0.449092
14        John was bringing a glass of water to Mary.  0.668822  0.331178
15        Bob was bringing a glass of water to Alice.  0.459396  0.540604
16  The actor was bringing a glass of water to the...  0.560457  0.439543
17  The boy was bringing a glass of water to the g...  0.541728  0.458272
18  Mr. William was bringing a glass of water to  ...  0.554753  0.445247
19       David was bringing a glass of water to Emma.  0.493690  0.506310
20  The prince was bringing a glass of water to th...  0.506154  0.493846
21     Robert was bringing a glass of water to Sarah.  0.590698  0.409301
22  Mr. Taylor was bringing a glass of water to Mr...  0.510279  0.489721
23       Paul was bringing a glass of water to Emily.  0.545344  0.454656

In [66]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_8m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_8m,'She'))

P('subj-pron'|subj=male) =  0.5385714297493299
P('non-subj-pron'|subj=male) =  0.46142857521772385

In [67]:
np_average_subj_male_subj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8m,'He')
np_average_subj_male_obj_pron['bringing'] = compute_average(transofposs_imperfective_noprompt_8m,'She')

### verb: "forwarding"

In [68]:
transofposs_imperfective_noprompt_9 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/9.csv")
transofposs_imperfective_noprompt_9.head()

                                            stimulus        He       She
0  Miss Smith was forwarding a gossipy email to M...  0.391449  0.608551
1  The woman was forwarding a gossipy email to th...  0.327375  0.672625
2       Mary was forwarding a gossipy email to John.  0.262951  0.737049
3       Alice was forwarding a gossipy email to Bob.  0.200665  0.799335
4  The actress was forwarding a gossipy email to ...  0.249794  0.750206

In [69]:
# female subject
transofposs_imperfective_noprompt_9f = transofposs_imperfective_noprompt_9[0:12]
transofposs_imperfective_noprompt_9f = transofposs_imperfective_noprompt_9f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_9m = transofposs_imperfective_noprompt_9[12:24]

#### female subject

In [70]:
transofposs_imperfective_noprompt_9f

                                             stimulus       She        He
0   Miss Smith was forwarding a gossipy email to M...  0.608551  0.391449
1   The woman was forwarding a gossipy email to th...  0.672625  0.327375
2        Mary was forwarding a gossipy email to John.  0.737049  0.262951
3        Alice was forwarding a gossipy email to Bob.  0.799335  0.200665
4   The actress was forwarding a gossipy email to ...  0.750206  0.249794
5   The girl was forwarding a gossipy email to the...  0.681010  0.318990
6   Mrs. Taylor was forwarding a gossipy email to ...  0.658332  0.341669
7       Emma was forwarding a gossipy email to David.  0.697721  0.302279
8   The princess was forwarding a gossipy email to...  0.707132  0.292868
9     Sarah was forwarding a gossipy email to Robert.  0.673469  0.326531
10  Mrs. Williams was forwarding a gossipy email t...  0.640889  0.359111
11      Emily was forwarding a gossipy email to Paul.  0.758174  0.241826

In [71]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_9f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_9f,'He'))

P('subj-pron'|subj=female) =  0.6987077047427496
P('non-subj-pron'|subj=female) =  0.3012923027078311

In [72]:
np_average_subj_female_subj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9f,'She')
np_average_subj_female_obj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9f,'He')

#### male subject

In [73]:
transofposs_imperfective_noprompt_9m

                                             stimulus        He       She
12  Mr. Smith was forwarding a gossipy email to Mi...  0.510767  0.489233
13  The man was forwarding a gossipy email to the ...  0.531739  0.468261
14       John was forwarding a gossipy email to Mary.  0.581242  0.418758
15       Bob was forwarding a gossipy email to Alice.  0.455427  0.544573
16  The actor was forwarding a gossipy email to th...  0.536538  0.463462
17  The boy was forwarding a gossipy email to the ...  0.541235  0.458765
18  Mr. William was forwarding a gossipy email to ...  0.570803  0.429197
19      David was forwarding a gossipy email to Emma.  0.509779  0.490221
20  The prince was forwarding a gossipy email to t...  0.525054  0.474946
21    Robert was forwarding a gossipy email to Sarah.  0.623987  0.376013
22  Mr. Taylor was forwarding a gossipy email to M...  0.490986  0.509014
23      Paul was forwarding a gossipy email to Emily.  0.533087  0.466913

In [74]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_9m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_9m,'She'))

P('subj-pron'|subj=male) =  0.5342202708125114
P('non-subj-pron'|subj=male) =  0.46577973167101544

In [75]:
np_average_subj_male_subj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9m,'He')
np_average_subj_male_obj_pron['forwarding'] = compute_average(transofposs_imperfective_noprompt_9m,'She')

### verb: "mailing"

In [76]:
transofposs_imperfective_noprompt_10 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/10.csv")
transofposs_imperfective_noprompt_10.head()

                                         stimulus        He       She
0   Miss Smith was mailing a letter to Mr. Smith.  0.333321  0.666679
1      The woman was mailing a letter to the man.  0.271422  0.728578
2              Mary was mailing a letter to John.  0.273685  0.726315
3              Alice was mailing a letter to Bob.  0.112790  0.887210
4  The actress was mailing a letter to the actor.  0.185156  0.814844

In [77]:
# female subject
transofposs_imperfective_noprompt_10f = transofposs_imperfective_noprompt_10[0:12]
transofposs_imperfective_noprompt_10f = transofposs_imperfective_noprompt_10f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_10m = transofposs_imperfective_noprompt_10[12:24]

#### female subject

In [78]:
transofposs_imperfective_noprompt_10f

                                             stimulus       She        He
0       Miss Smith was mailing a letter to Mr. Smith.  0.666679  0.333321
1          The woman was mailing a letter to the man.  0.728578  0.271422
2                  Mary was mailing a letter to John.  0.726315  0.273685
3                  Alice was mailing a letter to Bob.  0.887210  0.112790
4      The actress was mailing a letter to the actor.  0.814844  0.185156
5           The girl was mailing a letter to the boy.  0.709238  0.290762
6   Mrs. Taylor was mailing a letter to Mr. Williams.  0.672921  0.327079
7                 Emma was mailing a letter to David.  0.762358  0.237642
8    The princess was mailing a letter to the prince.  0.777167  0.222833
9               Sarah was mailing a letter to Robert.  0.698235  0.301765
10  Mrs. Williams was mailing a letter to Mr. Taylor.  0.667889  0.332111
11                Emily was mailing a letter to Paul.  0.818997  0.181003

In [79]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_10f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_10f,'He'))

P('subj-pron'|subj=female) =  0.7442025045553843
P('non-subj-pron'|subj=female) =  0.2557975010325511

In [80]:
np_average_subj_female_subj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10f,'She')
np_average_subj_female_obj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10f,'He')

#### male subject

In [81]:
transofposs_imperfective_noprompt_10m

                                             stimulus        He       She
12      Mr. Smith was mailing a letter to Miss Smith.  0.621441  0.378559
13         The man was mailing a letter to the woman.  0.679084  0.320916
14                 John was mailing a letter to Mary.  0.793707  0.206293
15                 Bob was mailing a letter to Alice.  0.784089  0.215911
16     The actor was mailing a letter to the actress.  0.714389  0.285611
17          The boy was mailing a letter to the girl.  0.693900  0.306100
18  Mr. William was mailing a letter to  Mrs. Taylor.  0.674882  0.325118
19                David was mailing a letter to Emma.  0.715713  0.284287
20   The prince was mailing a letter to the princess.  0.715739  0.284261
21              Robert was mailing a letter to Sarah.  0.770298  0.229702
22  Mr. Taylor was mailing a letter to Mrs. Williams.  0.659132  0.340868
23                Paul was mailing a letter to Emily.  0.759315  0.240685

In [82]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_10m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_10m,'She'))

P('subj-pron'|subj=male) =  0.7151408344507217
P('non-subj-pron'|subj=male) =  0.28485916927456856

In [83]:
np_average_subj_male_subj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10m,'He')
np_average_subj_male_obj_pron['mailing'] = compute_average(transofposs_imperfective_noprompt_10m,'She')

### verb: "shipping"

In [84]:
transofposs_imperfective_noprompt_11 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/11.csv")
transofposs_imperfective_noprompt_11.head()

                                           stimulus        He       She
0   Miss Smith was shipping a package to Mr. Smith.  0.409245  0.590755
1      The woman was shipping a package to the man.  0.322169  0.677831
2              Mary was shipping a package to John.  0.313917  0.686083
3              Alice was shipping a package to Bob.  0.119478  0.880522
4  The actress was shipping a package to the actor.  0.246566  0.753434

In [85]:
# female subject
transofposs_imperfective_noprompt_11f = transofposs_imperfective_noprompt_11[0:12]
transofposs_imperfective_noprompt_11f = transofposs_imperfective_noprompt_11f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_11m = transofposs_imperfective_noprompt_11[12:24]

#### female subject

In [86]:
transofposs_imperfective_noprompt_11f

                                             stimulus       She        He
0     Miss Smith was shipping a package to Mr. Smith.  0.590755  0.409245
1        The woman was shipping a package to the man.  0.677831  0.322169
2                Mary was shipping a package to John.  0.686083  0.313917
3                Alice was shipping a package to Bob.  0.880522  0.119478
4    The actress was shipping a package to the actor.  0.753434  0.246566
5         The girl was shipping a package to the boy.  0.672239  0.327761
6   Mrs. Taylor was shipping a package to Mr. Will...  0.570056  0.429944
7               Emma was shipping a package to David.  0.733404  0.266596
8   The princess was shipping a package to the pri...  0.748680  0.251320
9             Sarah was shipping a package to Robert.  0.636005  0.363995
10  Mrs. Williams was shipping a package to Mr. Ta...  0.587842  0.412158
11              Emily was shipping a package to Paul.  0.789380  0.210620

In [87]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_11f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_11f,'He'))

P('subj-pron'|subj=female) =  0.6938523898522059
P('non-subj-pron'|subj=female) =  0.30614760766426724

In [88]:
np_average_subj_female_subj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11f,'She')
np_average_subj_female_obj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11f,'He')

#### male subject

In [89]:
transofposs_imperfective_noprompt_11m

                                             stimulus        He       She
12    Mr. Smith was shipping a package to Miss Smith.  0.540804  0.459196
13       The man was shipping a package to the woman.  0.584934  0.415066
14               John was shipping a package to Mary.  0.673286  0.326714
15               Bob was shipping a package to Alice.  0.645599  0.354401
16   The actor was shipping a package to the actress.  0.606012  0.393988
17        The boy was shipping a package to the girl.  0.583863  0.416137
18  Mr. William was shipping a package to  Mrs. Ta...  0.604355  0.395645
19              David was shipping a package to Emma.  0.568090  0.431910
20  The prince was shipping a package to the princ...  0.642657  0.357343
21            Robert was shipping a package to Sarah.  0.614436  0.385564
22  Mr. Taylor was shipping a package to Mrs. Will...  0.565127  0.434873
23              Paul was shipping a package to Emily.  0.603217  0.396783

In [90]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_11m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_11m,'She'))

P('subj-pron'|subj=male) =  0.6026983708143234
P('non-subj-pron'|subj=male) =  0.39730163663625717

In [91]:
np_average_subj_male_subj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11m,'He')
np_average_subj_male_obj_pron['shipping'] = compute_average(transofposs_imperfective_noprompt_11m,'She')

### verb: "transmitting"

In [92]:
transofposs_imperfective_noprompt_12 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/12.csv")
transofposs_imperfective_noprompt_12.head()

                                            stimulus        He       She
0  Miss Smith was transmitting a message to Mr. S...  0.417313  0.582687
1   The woman was transmitting a message to the man.  0.325777  0.674223
2           Mary was transmitting a message to John.  0.327404  0.672596
3           Alice was transmitting a message to Bob.  0.146816  0.853184
4  The actress was transmitting a message to the ...  0.222274  0.777726

In [93]:
# female subject
transofposs_imperfective_noprompt_12f = transofposs_imperfective_noprompt_12[0:12]
transofposs_imperfective_noprompt_12f = transofposs_imperfective_noprompt_12f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_12m = transofposs_imperfective_noprompt_12[12:24]

#### female subject

In [94]:
transofposs_imperfective_noprompt_12f

                                             stimulus       She        He
0   Miss Smith was transmitting a message to Mr. S...  0.582687  0.417313
1    The woman was transmitting a message to the man.  0.674223  0.325777
2            Mary was transmitting a message to John.  0.672596  0.327404
3            Alice was transmitting a message to Bob.  0.853184  0.146816
4   The actress was transmitting a message to the ...  0.777726  0.222274
5     The girl was transmitting a message to the boy.  0.671047  0.328953
6   Mrs. Taylor was transmitting a message to Mr. ...  0.593114  0.406886
7           Emma was transmitting a message to David.  0.731586  0.268414
8   The princess was transmitting a message to the...  0.791424  0.208576
9         Sarah was transmitting a message to Robert.  0.643267  0.356733
10  Mrs. Williams was transmitting a message to Mr...  0.602671  0.397329
11          Emily was transmitting a message to Paul.  0.801980  0.198020

In [95]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_12f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_12f,'He'))

P('subj-pron'|subj=female) =  0.6996253828207651
P('non-subj-pron'|subj=female) =  0.30037462959686917

In [96]:
np_average_subj_female_subj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12f,'She')
np_average_subj_female_obj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12f,'He')

#### male subject

In [97]:
transofposs_imperfective_noprompt_12m

                                             stimulus        He       She
12  Mr. Smith was transmitting a message to Miss S...  0.569084  0.430916
13   The man was transmitting a message to the woman.  0.620138  0.379862
14           John was transmitting a message to Mary.  0.752768  0.247232
15           Bob was transmitting a message to Alice.  0.811549  0.188451
16  The actor was transmitting a message to the ac...  0.705927  0.294072
17    The boy was transmitting a message to the girl.  0.642276  0.357724
18  Mr. William was transmitting a message to  Mrs...  0.627580  0.372420
19          David was transmitting a message to Emma.  0.598439  0.401561
20  The prince was transmitting a message to the p...  0.688074  0.311926
21        Robert was transmitting a message to Sarah.  0.666635  0.333365
22  Mr. Taylor was transmitting a message to Mrs. ...  0.565616  0.434384
23          Paul was transmitting a message to Emily.  0.699254  0.300746

In [98]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_12m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_12m,'She'))

P('subj-pron'|subj=male) =  0.6622785081466039
P('non-subj-pron'|subj=male) =  0.3377214918533961

In [99]:
np_average_subj_male_subj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12m,'He')
np_average_subj_male_obj_pron['transmitting'] = compute_average(transofposs_imperfective_noprompt_12m,'She')

### verb: "wiring"

In [100]:
transofposs_imperfective_noprompt_14 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/14.csv")
transofposs_imperfective_noprompt_14.head()

                                     stimulus        He       She
0   Miss Smith was wiring money to Mr. Smith.  0.350330  0.649670
1      The woman was wiring money to the man.  0.302569  0.697431
2              Mary was wiring money to John.  0.317949  0.682051
3              Alice was wiring money to Bob.  0.178749  0.821251
4  The actress was wiring money to the actor.  0.238895  0.761105

In [101]:
# female subject
transofposs_imperfective_noprompt_14f = transofposs_imperfective_noprompt_14[0:12]
transofposs_imperfective_noprompt_14f = transofposs_imperfective_noprompt_14f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_14m = transofposs_imperfective_noprompt_14[12:24]

#### female subject

In [102]:
transofposs_imperfective_noprompt_14f

                                         stimulus       She        He
0       Miss Smith was wiring money to Mr. Smith.  0.649670  0.350330
1          The woman was wiring money to the man.  0.697431  0.302569
2                  Mary was wiring money to John.  0.682051  0.317949
3                  Alice was wiring money to Bob.  0.821251  0.178749
4      The actress was wiring money to the actor.  0.761105  0.238895
5           The girl was wiring money to the boy.  0.701394  0.298606
6   Mrs. Taylor was wiring money to Mr. Williams.  0.643429  0.356571
7                 Emma was wiring money to David.  0.717422  0.282578
8    The princess was wiring money to the prince.  0.703029  0.296971
9               Sarah was wiring money to Robert.  0.629392  0.370608
10  Mrs. Williams was wiring money to Mr. Taylor.  0.644463  0.355537
11                Emily was wiring money to Paul.  0.772105  0.227895

In [103]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_14f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_14f,'He'))

P('subj-pron'|subj=female) =  0.7018950631221136
P('non-subj-pron'|subj=female) =  0.2981049207349618

In [104]:
np_average_subj_female_subj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14f,'She')
np_average_subj_female_obj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14f,'He')

#### male subject

In [105]:
transofposs_imperfective_noprompt_14m

                                         stimulus        He       She
12      Mr. Smith was wiring money to Miss Smith.  0.537782  0.462218
13         The man was wiring money to the woman.  0.616756  0.383244
14                 John was wiring money to Mary.  0.679222  0.320778
15                 Bob was wiring money to Alice.  0.813776  0.186225
16     The actor was wiring money to the actress.  0.631893  0.368107
17          The boy was wiring money to the girl.  0.644014  0.355986
18  Mr. William was wiring money to  Mrs. Taylor.  0.578275  0.421725
19                David was wiring money to Emma.  0.621145  0.378855
20   The prince was wiring money to the princess.  0.671239  0.328761
21              Robert was wiring money to Sarah.  0.659492  0.340508
22  Mr. Taylor was wiring money to Mrs. Williams.  0.535061  0.464939
23                Paul was wiring money to Emily.  0.618384  0.381616

In [106]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_14m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_14m,'She'))

P('subj-pron'|subj=male) =  0.633919914563497
P('non-subj-pron'|subj=male) =  0.36608007674415904

In [107]:
np_average_subj_male_subj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14m,'He')
np_average_subj_male_obj_pron['wiring'] = compute_average(transofposs_imperfective_noprompt_14m,'She')

### verb: "carrying"

In [108]:
transofposs_imperfective_noprompt_15 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/15.csv")
transofposs_imperfective_noprompt_15.head()

                                        stimulus        He       She
0   Miss Smith was carrying a tray to Mr. Smith.  0.391171  0.608829
1      The woman was carrying a tray to the man.  0.279232  0.720768
2              Mary was carrying a tray to John.  0.318672  0.681328
3              Alice was carrying a tray to Bob.  0.160006  0.839994
4  The actress was carrying a tray to the actor.  0.252799  0.747201

In [109]:
# female subject
transofposs_imperfective_noprompt_15f = transofposs_imperfective_noprompt_15[0:12]
transofposs_imperfective_noprompt_15f = transofposs_imperfective_noprompt_15f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_15m = transofposs_imperfective_noprompt_15[12:24]

#### female subject

In [110]:
transofposs_imperfective_noprompt_15f

                                            stimulus       She        He
0       Miss Smith was carrying a tray to Mr. Smith.  0.608829  0.391171
1          The woman was carrying a tray to the man.  0.720768  0.279232
2                  Mary was carrying a tray to John.  0.681328  0.318672
3                  Alice was carrying a tray to Bob.  0.839994  0.160006
4      The actress was carrying a tray to the actor.  0.747201  0.252799
5           The girl was carrying a tray to the boy.  0.713454  0.286546
6   Mrs. Taylor was carrying a tray to Mr. Williams.  0.520172  0.479828
7                 Emma was carrying a tray to David.  0.720686  0.279314
8    The princess was carrying a tray to the prince.  0.800377  0.199623
9               Sarah was carrying a tray to Robert.  0.634826  0.365174
10  Mrs. Williams was carrying a tray to Mr. Taylor.  0.564609  0.435391
11                Emily was carrying a tray to Paul.  0.779675  0.220325

In [111]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_15f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_15f,'He'))

P('subj-pron'|subj=female) =  0.6943265994389852
P('non-subj-pron'|subj=female) =  0.30567337324221927

In [112]:
np_average_subj_female_subj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15f,'She')
np_average_subj_female_obj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15f,'He')

#### male subject

In [113]:
transofposs_imperfective_noprompt_15m

                                            stimulus        He       She
12      Mr. Smith was carrying a tray to Miss Smith.  0.540057  0.459943
13         The man was carrying a tray to the woman.  0.626543  0.373457
14                 John was carrying a tray to Mary.  0.691511  0.308489
15                 Bob was carrying a tray to Alice.  0.566219  0.433781
16     The actor was carrying a tray to the actress.  0.618804  0.381196
17          The boy was carrying a tray to the girl.  0.621018  0.378982
18  Mr. William was carrying a tray to  Mrs. Taylor.  0.586311  0.413689
19                David was carrying a tray to Emma.  0.519094  0.480906
20   The prince was carrying a tray to the princess.  0.628736  0.371264
21              Robert was carrying a tray to Sarah.  0.607816  0.392184
22  Mr. Taylor was carrying a tray to Mrs. Williams.  0.539652  0.460348
23                Paul was carrying a tray to Emily.  0.551204  0.448796

In [114]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_15m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_15m,'She'))

P('subj-pron'|subj=male) =  0.5914135773976644
P('non-subj-pron'|subj=male) =  0.40858642260233563

In [115]:
np_average_subj_male_subj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15m,'He')
np_average_subj_male_obj_pron['carrying'] = compute_average(transofposs_imperfective_noprompt_15m,'She')

### verb: "delivering"

In [116]:
transofposs_imperfective_noprompt_16 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/16.csv")
transofposs_imperfective_noprompt_16.head()

                                            stimulus        He       She
0  Miss Smith was delivering a subpoena to Mr. Sm...  0.361228  0.638772
1    The woman was delivering a subpoena to the man.  0.329477  0.670523
2            Mary was delivering a subpoena to John.  0.470727  0.529273
3            Alice was delivering a subpoena to Bob.  0.227661  0.772339
4  The actress was delivering a subpoena to the a...  0.195719  0.804281

In [117]:
# female subject
transofposs_imperfective_noprompt_16f = transofposs_imperfective_noprompt_16[0:12]
transofposs_imperfective_noprompt_16f = transofposs_imperfective_noprompt_16f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_16m = transofposs_imperfective_noprompt_16[12:24]

#### female subject

In [118]:
transofposs_imperfective_noprompt_16f

                                             stimulus       She        He
0   Miss Smith was delivering a subpoena to Mr. Sm...  0.638772  0.361228
1     The woman was delivering a subpoena to the man.  0.670523  0.329477
2             Mary was delivering a subpoena to John.  0.529273  0.470727
3             Alice was delivering a subpoena to Bob.  0.772339  0.227661
4   The actress was delivering a subpoena to the a...  0.804281  0.195719
5      The girl was delivering a subpoena to the boy.  0.665150  0.334850
6   Mrs. Taylor was delivering a subpoena to Mr. W...  0.558034  0.441966
7            Emma was delivering a subpoena to David.  0.583071  0.416929
8   The princess was delivering a subpoena to the ...  0.669232  0.330768
9          Sarah was delivering a subpoena to Robert.  0.506484  0.493516
10  Mrs. Williams was delivering a subpoena to Mr....  0.583813  0.416187
11           Emily was delivering a subpoena to Paul.  0.633072  0.366928

In [119]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_16f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_16f,'He'))

P('subj-pron'|subj=female) =  0.6345036625862122
P('non-subj-pron'|subj=female) =  0.36549633865555126

In [120]:
np_average_subj_female_subj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16f,'She')
np_average_subj_female_obj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16f,'He')

#### male subject

In [121]:
transofposs_imperfective_noprompt_16m

                                             stimulus        He       She
12  Mr. Smith was delivering a subpoena to Miss Sm...  0.571268  0.428732
13    The man was delivering a subpoena to the woman.  0.637335  0.362665
14            John was delivering a subpoena to Mary.  0.700161  0.299839
15            Bob was delivering a subpoena to Alice.  0.770793  0.229207
16  The actor was delivering a subpoena to the act...  0.533789  0.466211
17     The boy was delivering a subpoena to the girl.  0.669349  0.330651
18  Mr. William was delivering a subpoena to Mrs. ...  0.670374  0.329626
19           David was delivering a subpoena to Emma.  0.567769  0.432231
20  The prince was delivering a subpoena to the pr...  0.652699  0.347301
21         Robert was delivering a subpoena to Sarah.  0.647040  0.352960
22  Mr. Taylor was delivering a subpoena to Mrs. W...  0.623336  0.376664
23           Paul was delivering a subpoena to Emily.  0.571940  0.428060

In [122]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_16m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_16m,'She'))

P('subj-pron'|subj=male) =  0.6346543381611506
P('non-subj-pron'|subj=male) =  0.36534565190474194

In [123]:
np_average_subj_male_subj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16m,'He')
np_average_subj_male_obj_pron['delivering'] = compute_average(transofposs_imperfective_noprompt_16m,'She')

### verb: "giving"

In [124]:
transofposs_imperfective_noprompt_17 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/17.csv")
transofposs_imperfective_noprompt_17.head()

                                         stimulus        He       She
0   Miss Smith was giving a sweater to Mr. Smith.  0.448264  0.551736
1      The woman was giving a sweater to the man.  0.365874  0.634126
2              Mary was giving a sweater to John.  0.365226  0.634774
3              Alice was giving a sweater to Bob.  0.238804  0.761196
4  The actress was giving a sweater to the actor.  0.287200  0.712800

In [125]:
# female subject
transofposs_imperfective_noprompt_17f = transofposs_imperfective_noprompt_17[0:12]
transofposs_imperfective_noprompt_17f = transofposs_imperfective_noprompt_17f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_17m = transofposs_imperfective_noprompt_17[12:24]

#### female subject

In [126]:
transofposs_imperfective_noprompt_17f

                                             stimulus       She        He
0       Miss Smith was giving a sweater to Mr. Smith.  0.551736  0.448264
1          The woman was giving a sweater to the man.  0.634126  0.365874
2                  Mary was giving a sweater to John.  0.634774  0.365226
3                  Alice was giving a sweater to Bob.  0.761196  0.238804
4      The actress was giving a sweater to the actor.  0.712800  0.287200
5           The girl was giving a sweater to the boy.  0.632225  0.367776
6   Mrs. Taylor was giving a sweater to Mr. Williams.  0.574635  0.425365
7                 Emma was giving a sweater to David.  0.685535  0.314465
8    The princess was giving a sweater to the prince.  0.667712  0.332288
9               Sarah was giving a sweater to Robert.  0.564908  0.435092
10  Mrs. Williams was giving a sweater to Mr. Taylor.  0.601292  0.398708
11                Emily was giving a sweater to Paul.  0.733293  0.266707

In [127]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_17f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_17f,'He'))

P('subj-pron'|subj=female) =  0.6461860487858454
P('non-subj-pron'|subj=female) =  0.35381395121415454

In [128]:
np_average_subj_female_subj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17f,'She')
np_average_subj_female_obj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17f,'He')

#### female subject

In [129]:
transofposs_imperfective_noprompt_17m

                                             stimulus        He       She
12      Mr. Smith was giving a sweater to Miss Smith.  0.529694  0.470306
13         The man was giving a sweater to the woman.  0.555403  0.444597
14                 John was giving a sweater to Mary.  0.682710  0.317290
15                 Bob was giving a sweater to Alice.  0.609185  0.390815
16     The actor was giving a sweater to the actress.  0.616053  0.383947
17          The boy was giving a sweater to the girl.  0.574670  0.425330
18  Mr. William was giving a sweater to  Mrs. Taylor.  0.586284  0.413716
19                David was giving a sweater to Emma.  0.566964  0.433036
20   The prince was giving a sweater to the princess.  0.608772  0.391228
21              Robert was giving a sweater to Sarah.  0.606573  0.393427
22  Mr. Taylor was giving a sweater to Mrs. Williams.  0.539124  0.460876
23                Paul was giving a sweater to Emily.  0.601292  0.398708

In [130]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_17m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_17m,'She'))

P('subj-pron'|subj=male) =  0.5897269695997238
P('non-subj-pron'|subj=male) =  0.4102730304002762

In [131]:
np_average_subj_male_subj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17m,'He')
np_average_subj_male_obj_pron['giving'] = compute_average(transofposs_imperfective_noprompt_17m,'She')

### verb: "handing"

In [132]:
transofposs_imperfective_noprompt_18 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/18.csv")
transofposs_imperfective_noprompt_18.head()

                                       stimulus        He       She
0   Miss Smith was handing a book to Mr. Smith.  0.548525  0.451475
1      The woman was handing a book to the man.  0.425924  0.574076
2              Mary was handing a book to John.  0.393438  0.606561
3              Alice was handing a book to Bob.  0.235588  0.764412
4  The actress was handing a book to the actor.  0.336671  0.663329

In [133]:
# female subject
transofposs_imperfective_noprompt_18f = transofposs_imperfective_noprompt_18[0:12]
transofposs_imperfective_noprompt_18f = transofposs_imperfective_noprompt_18f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_18m = transofposs_imperfective_noprompt_18[12:24]

#### female subject

In [134]:
transofposs_imperfective_noprompt_18f

                                           stimulus       She        He
0       Miss Smith was handing a book to Mr. Smith.  0.451475  0.548525
1          The woman was handing a book to the man.  0.574076  0.425924
2                  Mary was handing a book to John.  0.606561  0.393438
3                  Alice was handing a book to Bob.  0.764412  0.235588
4      The actress was handing a book to the actor.  0.663329  0.336671
5           The girl was handing a book to the boy.  0.591523  0.408477
6   Mrs. Taylor was handing a book to Mr. Williams.  0.447442  0.552558
7                 Emma was handing a book to David.  0.661022  0.338978
8    The princess was handing a book to the prince.  0.698691  0.301309
9               Sarah was handing a book to Robert.  0.543042  0.456958
10  Mrs. Williams was handing a book to Mr. Taylor.  0.482101  0.517899
11                Emily was handing a book to Paul.  0.742761  0.257239

In [135]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_18f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_18f,'He'))

P('subj-pron'|subj=female) =  0.6022028724352518
P('non-subj-pron'|subj=female) =  0.3977971139053504

In [136]:
np_average_subj_female_subj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18f,'She')
np_average_subj_female_obj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18f,'He')

#### male subject

In [137]:
transofposs_imperfective_noprompt_18m

                                           stimulus        He       She
12      Mr. Smith was handing a book to Miss Smith.  0.451746  0.548254
13         The man was handing a book to the woman.  0.491539  0.508461
14                 John was handing a book to Mary.  0.645052  0.354948
15                 Bob was handing a book to Alice.  0.477068  0.522932
16     The actor was handing a book to the actress.  0.538941  0.461059
17          The boy was handing a book to the girl.  0.512253  0.487747
18   Mr. William was handing a book to Mrs. Taylor.  0.508690  0.491310
19                David was handing a book to Emma.  0.470829  0.529171
20   The prince was handing a book to the princess.  0.479854  0.520146
21              Robert was handing a book to Sarah.  0.523958  0.476042
22  Mr. Taylor was handing a book to Mrs. Williams.  0.466017  0.533983
23                Paul was handing a book to Emily.  0.532612  0.467389

In [138]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_18m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_18m,'She'))

P('subj-pron'|subj=male) =  0.5082132468620936
P('non-subj-pron'|subj=male) =  0.49178676555554074

In [139]:
np_average_subj_male_subj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18m,'He')
np_average_subj_male_obj_pron['handing'] = compute_average(transofposs_imperfective_noprompt_18m,'She')

### verb: "passing"

In [140]:
transofposs_imperfective_noprompt_19 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/19.csv")
transofposs_imperfective_noprompt_19.head()

                                           stimulus        He       She
0   Miss Smith was passing a sandwich to Mr. Smith.  0.495649  0.504351
1      The woman was passing a sandwich to the man.  0.362893  0.637107
2              Mary was passing a sandwich to John.  0.394989  0.605011
3              Alice was passing a sandwich to Bob.  0.216709  0.783291
4  The actress was passing a sandwich to the actor.  0.310477  0.689523

In [141]:
# female subject
transofposs_imperfective_noprompt_19f = transofposs_imperfective_noprompt_19[0:12]
transofposs_imperfective_noprompt_19f = transofposs_imperfective_noprompt_19f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_19m = transofposs_imperfective_noprompt_19[12:24]

#### female subject

In [142]:
transofposs_imperfective_noprompt_19f

                                             stimulus       She        He
0     Miss Smith was passing a sandwich to Mr. Smith.  0.504351  0.495649
1        The woman was passing a sandwich to the man.  0.637107  0.362893
2                Mary was passing a sandwich to John.  0.605011  0.394989
3                Alice was passing a sandwich to Bob.  0.783291  0.216709
4    The actress was passing a sandwich to the actor.  0.689523  0.310477
5         The girl was passing a sandwich to the boy.  0.622161  0.377839
6   Mrs. Taylor was passing a sandwich to Mr. Will...  0.481480  0.518520
7               Emma was passing a sandwich to David.  0.616653  0.383347
8   The princess was passing a sandwich to the pri...  0.670970  0.329030
9             Sarah was passing a sandwich to Robert.  0.538553  0.461447
10  Mrs. Williams was passing a sandwich to  Mr. T...  0.454300  0.545700
11              Emily was passing a sandwich to Paul.  0.706366  0.293633

In [143]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_19f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_19f,'He'))

P('subj-pron'|subj=female) =  0.6091472531358401
P('non-subj-pron'|subj=female) =  0.39085276300708455

In [144]:
np_average_subj_female_subj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19f,'She')
np_average_subj_female_obj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19f,'He')

#### male subject

In [145]:
transofposs_imperfective_noprompt_19m

                                             stimulus        He       She
12    Mr. Smith was passing a sandwich to Miss Smith.  0.462162  0.537838
13       The man was passing a sandwich to the woman.  0.473440  0.526560
14               John was passing a sandwich to Mary.  0.638157  0.361843
15               Bob was passing a sandwich to Alice.  0.506495  0.493505
16   The actor was passing a sandwich to the actress.  0.549874  0.450126
17        The boy was passing a sandwich to the girl.  0.509681  0.490319
18  Mr. William was passing a sandwich to  Mrs. Ta...  0.545141  0.454859
19              David was passing a sandwich to Emma.  0.491571  0.508429
20  The prince was passing a sandwich to the princ...  0.503635  0.496365
21            Robert was passing a sandwich to Sarah.  0.554687  0.445313
22  Mr. Taylor was passing a sandwich to Mrs. Will...  0.477846  0.522154
23              Paul was passing a sandwich to Emily.  0.520397  0.479603

In [146]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_19m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_19m,'She'))

P('subj-pron'|subj=male) =  0.5194238175948461
P('non-subj-pron'|subj=male) =  0.48057618737220764

In [147]:
np_average_subj_male_subj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19m,'He')
np_average_subj_male_obj_pron['passing'] = compute_average(transofposs_imperfective_noprompt_19m,'She')

### verb: "serving"

In [148]:
transofposs_imperfective_noprompt_20 = pd.read_csv("../results/gpt2/transofposs_imperfective/no-prompt/20.csv")
transofposs_imperfective_noprompt_20.head()

                                        stimulus        He       She
0   Miss Smith was serving a chili to Mr. Smith.  0.465242  0.534758
1      The woman was serving a chili to the man.  0.345825  0.654175
2              Mary was serving a chili to John.  0.464550  0.535450
3              Alice was serving a chili to Bob.  0.283283  0.716717
4  The actress was serving a chili to the actor.  0.268998  0.731002

In [149]:
# female subject
transofposs_imperfective_noprompt_20f = transofposs_imperfective_noprompt_20[0:12]
transofposs_imperfective_noprompt_20f = transofposs_imperfective_noprompt_20f[["stimulus","She","He"]]
# male subject
transofposs_imperfective_noprompt_20m = transofposs_imperfective_noprompt_20[12:24]

#### female subject

In [150]:
transofposs_imperfective_noprompt_20f

                                            stimulus       She        He
0       Miss Smith was serving a chili to Mr. Smith.  0.534758  0.465242
1          The woman was serving a chili to the man.  0.654175  0.345825
2                  Mary was serving a chili to John.  0.535450  0.464550
3                  Alice was serving a chili to Bob.  0.716717  0.283283
4      The actress was serving a chili to the actor.  0.731002  0.268998
5           The girl was serving a chili to the boy.  0.606322  0.393678
6   Mrs. Taylor was serving a chili to Mr. Williams.  0.499480  0.500520
7                 Emma was serving a chili to David.  0.639801  0.360199
8    The princess was serving a chili to the prince.  0.646430  0.353570
9               Sarah was serving a chili to Robert.  0.510605  0.489395
10  Mrs. Williams was serving a chili to Mr. Taylor.  0.516839  0.483161
11                Emily was serving a chili to Paul.  0.673894  0.326106

In [151]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_20f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_noprompt_20f,'He'))

P('subj-pron'|subj=female) =  0.6054560641447703
P('non-subj-pron'|subj=female) =  0.39454395075639087

In [152]:
np_average_subj_female_subj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20f,'She')
np_average_subj_female_obj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20f,'He')

#### male subject

In [153]:
transofposs_imperfective_noprompt_20m

                                            stimulus        He       She
12      Mr. Smith was serving a chili to Miss Smith.  0.548987  0.451013
13         The man was serving a chili to the woman.  0.595409  0.404591
14                 John was serving a chili to Mary.  0.687536  0.312464
15                 Bob was serving a chili to Alice.  0.544929  0.455071
16     The actor was serving a chili to the actress.  0.628217  0.371783
17          The boy was serving a chili to the girl.  0.555314  0.444686
18  Mr. William was serving a chili to  Mrs. Taylor.  0.592488  0.407512
19                David was serving a chili to Emma.  0.537600  0.462400
20   The prince was serving a chili to the princess.  0.594069  0.405931
21              Robert was serving a chili to Sarah.  0.593764  0.406236
22  Mr. Taylor was serving a chili to Mrs. Williams.  0.564879  0.435122
23                Paul was serving a chili to Emily.  0.552866  0.447134

In [154]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_20m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_noprompt_20m,'She'))

P('subj-pron'|subj=male) =  0.5830046186844507
P('non-subj-pron'|subj=male) =  0.4169953614473343

In [155]:
np_average_subj_male_subj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20m,'He')
np_average_subj_male_obj_pron['serving'] = compute_average(transofposs_imperfective_noprompt_20m,'She')

## Summary of Results

In [156]:
np_results_fsubj_subjpron = pd.DataFrame(list(np_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
np_results_fsubj_objpron = pd.DataFrame(list(np_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
np_results_fsubj = np_results_fsubj_subjpron.merge(np_results_fsubj_objpron)
np_results_fsubj

            verb  subj_ref_female_subj  obj_ref_female_subj
0       flinging              0.618785             0.381215
1        kicking              0.666216             0.333784
2        lobbing              0.705647             0.294353
3       throwing              0.638003             0.361997
4        tossing              0.660450             0.339550
5       bringing              0.600811             0.399189
6     forwarding              0.698708             0.301292
7        mailing              0.744203             0.255798
8       shipping              0.693852             0.306148
9   transmitting              0.699625             0.300375
10        wiring              0.701895             0.298105
11      carrying              0.694327             0.305673
12    delivering              0.634504             0.365496
13        giving              0.646186             0.353814
14       handing              0.602203             0.397797
15       passing              0.609147             0.390853
16       serving              0.605456             0.394544

In [157]:
np_results_msubj_subjpron = pd.DataFrame(list(np_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
np_results_msubj_objpron = pd.DataFrame(list(np_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
np_results_msubj = np_results_msubj_subjpron.merge(np_results_msubj_objpron)
np_results_msubj

            verb  subj_ref_male_subj  obj_ref_male_subj
0       flinging            0.531916           0.468084
1        kicking            0.523568           0.476432
2        lobbing            0.520894           0.479106
3        rolling            0.597326           0.402674
4       throwing            0.626607           0.373393
5        tossing            0.538435           0.461565
6       bringing            0.538571           0.461429
7     forwarding            0.534220           0.465780
8        mailing            0.715141           0.284859
9       shipping            0.602698           0.397302
10  transmitting            0.662279           0.337721
11        wiring            0.633920           0.366080
12      carrying            0.591414           0.408586
13    delivering            0.634654           0.365346
14        giving            0.589727           0.410273
15       handing            0.508213           0.491787
16       passing            0.519424           0.480576
17       serving            0.583005           0.416995

In [158]:
np_results = np_results_fsubj.merge(np_results_msubj)
np_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flinging,0.618785,0.381215,0.531916,0.468084
1,kicking,0.666216,0.333784,0.523568,0.476432
2,lobbing,0.705647,0.294353,0.520894,0.479106
3,throwing,0.638003,0.361997,0.626607,0.373393
4,tossing,0.660450,0.339550,0.538435,0.461565
5,bringing,0.600811,0.399189,0.538571,0.461429
6,forwarding,0.698708,0.301292,0.534220,0.465780
7,mailing,0.744203,0.255798,0.715141,0.284859
8,shipping,0.693852,0.306148,0.602698,0.397302
9,transmitting,0.699625,0.300375,0.662279,0.337721
10,wiring,0.701895,0.298105,0.633920,0.366080
11,carrying,0.694327,0.305673,0.591414,0.408586
12,delivering,0.634504,0.365496,0.634654,0.365346
13,giving,0.646186,0.353814,0.589727,0.410273
14,handing,0.602203,0.397797,0.508213,0.491787
15,passing,0.609147,0.390853,0.519424,0.480576
16,serving,0.605456,0.394544,0.583005,0.416995

In [159]:
print("P(subj_reference |subj=female)", compute_average(np_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(np_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.6600010035669102
P(obj_reference |subj=female) 0.33999899771137565

In [160]:
print("P(subj_reference |subj=male)", compute_average(np_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(np_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.5796873319674941
P(obj_reference |subj=male) 0.4203126674481467

## Connective: "because"

In [161]:
c1_average_subj_female_subj_pron = {}
c1_average_subj_female_obj_pron = {}
c1_average_subj_male_subj_pron = {}
c1_average_subj_male_obj_pron = {}

### verb: "chucking"

In [162]:
transofposs_imperfective_connective1_1 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/1.csv")
transofposs_imperfective_connective1_1.head()

                                            stimulus        he       she
0  Miss Smith was chucking a wrench to Mr. Smith ...  0.617794  0.382206
1  The woman was chucking a wrench to the man bec...  0.624097  0.375903
2         Mary was chucking a wrench to John because  0.431529  0.568471
3         Alice was chucking a wrench to Bob because  0.414417  0.585583
4  The actress was chucking a wrench to the actor...  0.565316  0.434684

In [163]:
# female subject
transofposs_imperfective_connective1_1f = transofposs_imperfective_connective1_1[0:12]
transofposs_imperfective_connective1_1f = transofposs_imperfective_connective1_1f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_1m = transofposs_imperfective_connective1_1[12:24]

#### female subject

In [164]:
transofposs_imperfective_connective1_1f

                                             stimulus       she        he
0   Miss Smith was chucking a wrench to Mr. Smith ...  0.382206  0.617794
1   The woman was chucking a wrench to the man bec...  0.375903  0.624097
2          Mary was chucking a wrench to John because  0.568471  0.431529
3          Alice was chucking a wrench to Bob because  0.585583  0.414417
4   The actress was chucking a wrench to the actor...  0.434684  0.565316
5   The girl was chucking a wrench to the boy because  0.481211  0.518789
6   Mrs. Taylor was chucking a wrench to Mr. Willi...  0.343879  0.656121
7         Emma was chucking a wrench to David because  0.571767  0.428233
8   The princess was chucking a wrench to the prin...  0.606673  0.393327
9       Sarah was chucking a wrench to Robert because  0.452170  0.547831
10  Mrs. Williams was chucking a wrench to  Mr. Ta...  0.286756  0.713244
11        Emily was chucking a wrench to Paul because  0.569093  0.430907

In [165]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_1f,'he'))

P('subj-pron'|subj=female) =  0.4715328961610794
P('non-subj-pron'|subj=female) =  0.528467116256555

In [166]:
c1_average_subj_female_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1f,'she')
c1_average_subj_female_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1f,'he')

#### male subject

In [167]:
transofposs_imperfective_connective1_1m

                                             stimulus        he       she
12  Mr. Smith was chucking a wrench to Miss Smith ...  0.470542  0.529458
13  The man was chucking a wrench to the woman bec...  0.505572  0.494428
14         John was chucking a wrench to Mary because  0.597006  0.402994
15         Bob was chucking a wrench to Alice because  0.600610  0.399390
16  The actor was chucking a wrench to the actress...  0.515134  0.484866
17  The boy was chucking a wrench to the girl because  0.521181  0.478819
18  Mr. William was chucking a wrench to  Mrs. Tay...  0.433416  0.566584
19        David was chucking a wrench to Emma because  0.497499  0.502501
20  The prince was chucking a wrench to the prince...  0.570308  0.429692
21      Robert was chucking a wrench to Sarah because  0.556378  0.443622
22  Mr. Taylor was chucking a wrench to Mrs. Willi...  0.473315  0.526685
23        Paul was chucking a wrench to Emily because  0.520703  0.479297

In [168]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_1m,'she'))

P('subj-pron'|subj=male) =  0.5218054081002871
P('non-subj-pron'|subj=male) =  0.47819459686676663

In [169]:
c1_average_subj_male_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1m,'he')
c1_average_subj_male_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective1_1m,'she')

### verb: "flinging"

In [170]:
transofposs_imperfective_connective1_2 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/2.csv")
transofposs_imperfective_connective1_2.head()

                                            stimulus        he       she
0  Miss Smith was flinging a frisbee to Mr. Smith...  0.603081  0.396919
1  The woman was flinging a frisbee to the man be...  0.570741  0.429260
2        Mary was flinging a frisbee to John because  0.416277  0.583723
3        Alice was flinging a frisbee to Bob because  0.356697  0.643303
4  The actress was flinging a frisbee to the acto...  0.562110  0.437890

In [171]:
# female subject
transofposs_imperfective_connective1_2f = transofposs_imperfective_connective1_2[0:12]
transofposs_imperfective_connective1_2f = transofposs_imperfective_connective1_2f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_2m = transofposs_imperfective_connective1_2[12:24]

#### female subject

In [172]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_2f,'he'))

P('subj-pron'|subj=female) =  0.5093709031740824
P('non-subj-pron'|subj=female) =  0.490629106760025

In [173]:
c1_average_subj_female_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2f,'she')
c1_average_subj_female_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2f,'he')

#### male subject

In [174]:
transofposs_imperfective_connective1_2m

                                             stimulus        he       she
12  Mr. Smith was flinging a frisbee to Miss Smith...  0.538801  0.461200
13  The man was flinging a frisbee to the woman be...  0.567381  0.432619
14        John was flinging a frisbee to Mary because  0.618526  0.381474
15        Bob was flinging a frisbee to Alice because  0.613004  0.386996
16  The actor was flinging a frisbee to the actres...  0.555675  0.444325
17  The boy was flinging a frisbee to the girl bec...  0.603514  0.396486
18  Mr. William was flinging a frisbee to  Mrs. Ta...  0.505313  0.494687
19       David was flinging a frisbee to Emma because  0.506385  0.493615
20  The prince was flinging a frisbee to the princ...  0.620866  0.379134
21     Robert was flinging a frisbee to Sarah because  0.580525  0.419475
22  Mr. Taylor was flinging a frisbee to Mrs. Will...  0.551476  0.448524
23       Paul was flinging a frisbee to Emily because  0.532142  0.467858

In [175]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_2m,'she'))

P('subj-pron'|subj=male) =  0.5661338617404302
P('non-subj-pron'|subj=male) =  0.43386612832546234

In [176]:
c1_average_subj_male_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2m,'he')
c1_average_subj_male_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective1_2m,'she')

### verb: "kicking"

In [177]:
transofposs_imperfective_connective1_3 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/3.csv")
transofposs_imperfective_connective1_3.head()

                                            stimulus        he       she
0  Miss Smith was kicking a soccer ball to Mr. Sm...  0.552831  0.447169
1  The woman was kicking a soccer ball to the man...  0.526873  0.473127
2     Mary was kicking a soccer ball to John because  0.360946  0.639054
3     Alice was kicking a soccer ball to Bob because  0.293064  0.706936
4  The actress was kicking a soccer ball to the a...  0.466600  0.533400

In [178]:
# female subject
transofposs_imperfective_connective1_3f = transofposs_imperfective_connective1_3[0:12]
transofposs_imperfective_connective1_3f = transofposs_imperfective_connective1_3f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_3m = transofposs_imperfective_connective1_3[12:24]

#### female subject

In [179]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_3f,'he'))

P('subj-pron'|subj=female) =  0.5677599087357521
P('non-subj-pron'|subj=female) =  0.4322400912642479

In [180]:
c1_average_subj_female_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3f,'she')
c1_average_subj_female_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3f,'he')

#### male subject

In [181]:
transofposs_imperfective_connective1_3m

                                             stimulus        he       she
12  Mr. Smith was kicking a soccer ball to Miss Sm...  0.513062  0.486938
13  The man was kicking a soccer ball to the woman...  0.547336  0.452664
14     John was kicking a soccer ball to Mary because  0.566987  0.433013
15     Bob was kicking a soccer ball to Alice because  0.582880  0.417120
16  The actor was kicking a soccer ball to the act...  0.551672  0.448328
17  The boy was kicking a soccer ball to the girl ...  0.582457  0.417543
18  Mr. William was kicking a soccer ball to  Mrs....  0.492549  0.507451
19    David was kicking a soccer ball to Emma because  0.505212  0.494788
20  The prince was kicking a soccer ball to the pr...  0.683480  0.316520
21  Robert was kicking a soccer ball to Sarah because  0.545941  0.454059
22  Mr. Taylor was kicking a soccer ball to Mrs. W...  0.541455  0.458545
23    Paul was kicking a soccer ball to Emily because  0.493721  0.506279

In [182]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_3m,'she'))

P('subj-pron'|subj=male) =  0.5505627021193504
P('non-subj-pron'|subj=male) =  0.4494373028477033

In [183]:
c1_average_subj_male_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3m,'he')
c1_average_subj_male_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective1_3m,'she')

### verb: "lobbing"

In [184]:
transofposs_imperfective_connective1_4 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/4.csv")
transofposs_imperfective_connective1_4.head()

                                            stimulus        he       she
0  Miss Smith was lobbing a football to Mr. Smith...  0.568456  0.431544
1  The woman was lobbing a football to the man be...  0.631455  0.368545
2        Mary was lobbing a football to John because  0.428225  0.571775
3        Alice was lobbing a football to Bob because  0.387401  0.612599
4  The actress was lobbing a football to the acto...  0.537419  0.462581

In [185]:
# female subject
transofposs_imperfective_connective1_4f = transofposs_imperfective_connective1_4[0:12]
transofposs_imperfective_connective1_4f = transofposs_imperfective_connective1_4f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_4m = transofposs_imperfective_connective1_4[12:24]

#### female subject

In [186]:
transofposs_imperfective_connective1_4f

                                             stimulus       she        he
0   Miss Smith was lobbing a football to Mr. Smith...  0.431544  0.568456
1   The woman was lobbing a football to the man be...  0.368545  0.631455
2         Mary was lobbing a football to John because  0.571775  0.428225
3         Alice was lobbing a football to Bob because  0.612599  0.387401
4   The actress was lobbing a football to the acto...  0.462581  0.537419
5   The girl was lobbing a football to the boy bec...  0.451390  0.548610
6   Mrs. Taylor was lobbing a football to Mr. Will...  0.406405  0.593595
7        Emma was lobbing a football to David because  0.592276  0.407724
8   The princess was lobbing a football to the pri...  0.548822  0.451178
9      Sarah was lobbing a football to Robert because  0.422545  0.577455
10  Mrs. Williams was lobbing a football to  Mr. T...  0.326149  0.673851
11       Emily was lobbing a football to Paul because  0.583602  0.416398

In [187]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_4f,'he'))

P('subj-pron'|subj=female) =  0.4815192793806394
P('non-subj-pron'|subj=female) =  0.5184807156523069

In [188]:
c1_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4f,'she')
c1_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4f,'he')

#### male subject

In [189]:
transofposs_imperfective_connective1_4m

                                             stimulus        he       she
12  Mr. Smith was lobbing a football to Miss Smith...  0.502544  0.497456
13  The man was lobbing a football to the woman be...  0.507386  0.492614
14        John was lobbing a football to Mary because  0.578556  0.421444
15        Bob was lobbing a football to Alice because  0.587818  0.412182
16  The actor was lobbing a football to the actres...  0.525259  0.474741
17  The boy was lobbing a football to the girl bec...  0.563340  0.436660
18  Mr. William was lobbing a football to  Mrs. Ta...  0.494409  0.505591
19       David was lobbing a football to Emma because  0.516800  0.483200
20  The prince was lobbing a football to the princ...  0.627136  0.372864
21     Robert was lobbing a football to Sarah because  0.579815  0.420185
22  Mr. Taylor was lobbing a football to Mrs. Will...  0.557331  0.442669
23       Paul was lobbing a football to Emily because  0.497607  0.502393

In [190]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_4m,'she'))

P('subj-pron'|subj=male) =  0.5448333323001862
P('non-subj-pron'|subj=male) =  0.45516668011744815

In [191]:
c1_average_subj_male_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4m,'he')
c1_average_subj_male_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective1_4m,'she')

### verb: "rolling"

In [192]:
transofposs_imperfective_connective1_5 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/5.csv")
transofposs_imperfective_connective1_5.head()

                                            stimulus        he       she
0  Miss Smith was rolling a toy truck to Mr. Smit...  0.429772  0.570229
1  The woman was rolling a toy truck to the man b...  0.419367  0.580633
2       Mary was rolling a toy truck to John because  0.304606  0.695394
3       Alice was rolling a toy truck to Bob because  0.284114  0.715886
4  The actress was rolling a toy truck to the act...  0.388143  0.611857

In [193]:
# female subject
transofposs_imperfective_connective1_5f = transofposs_imperfective_connective1_5[0:12]
transofposs_imperfective_connective1_5f = transofposs_imperfective_connective1_5[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_5m = transofposs_imperfective_connective1_5[12:24]

#### female subject

In [194]:
transofposs_imperfective_connective1_5f

                                             stimulus       she        he
0   Miss Smith was rolling a toy truck to Mr. Smit...  0.570229  0.429772
1   The woman was rolling a toy truck to the man b...  0.580633  0.419367
2        Mary was rolling a toy truck to John because  0.695394  0.304606
3        Alice was rolling a toy truck to Bob because  0.715886  0.284114
4   The actress was rolling a toy truck to the act...  0.611857  0.388143
5   The girl was rolling a toy truck to the boy be...  0.705354  0.294646
6   Mrs. Taylor was rolling a toy truck to Mr. Wil...  0.525520  0.474480
7       Emma was rolling a toy truck to David because  0.707647  0.292353
8   The princess was rolling a toy truck to the pr...  0.769993  0.230007
9     Sarah was rolling a toy truck to Robert because  0.529674  0.470326
10  Mrs. Williams was rolling a toy truck to  Mr. ...  0.461692  0.538308
11      Emily was rolling a toy truck to Paul because  0.707790  0.292210
12  Mr. Smith was rolling a toy truck to Miss Smit...  0.400561  0.599439
13  The man was rolling a toy truck to the woman b...  0.336682  0.663318
14       John was rolling a toy truck to Mary because  0.284233  0.715767
15       Bob was rolling a toy truck to Alice because  0.287762  0.712238
16  The actor was rolling a toy truck to the actre...  0.370458  0.629542
17  The boy was rolling a toy truck to the girl be...  0.314892  0.685108
18  Mr. William was rolling a toy truck to  Mrs. T...  0.404085  0.595915
19      David was rolling a toy truck to Emma because  0.380931  0.619069
20  The prince was rolling a toy truck to the prin...  0.222917  0.777083
21    Robert was rolling a toy truck to Sarah because  0.369545  0.630455
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.369278  0.630722
23      Paul was rolling a toy truck to Emily because  0.387728  0.612272

In [195]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_5f,'he'))

P('subj-pron'|subj=female) =  0.4879476483911276
P('non-subj-pron'|subj=female) =  0.512052346020937

In [196]:
c1_average_subj_female_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5f,'she')
c1_average_subj_female_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5f,'he')

#### male subject

In [197]:
transofposs_imperfective_connective1_5m

                                             stimulus        he       she
12  Mr. Smith was rolling a toy truck to Miss Smit...  0.599439  0.400561
13  The man was rolling a toy truck to the woman b...  0.663318  0.336682
14       John was rolling a toy truck to Mary because  0.715767  0.284233
15       Bob was rolling a toy truck to Alice because  0.712238  0.287762
16  The actor was rolling a toy truck to the actre...  0.629542  0.370458
17  The boy was rolling a toy truck to the girl be...  0.685108  0.314892
18  Mr. William was rolling a toy truck to  Mrs. T...  0.595915  0.404085
19      David was rolling a toy truck to Emma because  0.619069  0.380931
20  The prince was rolling a toy truck to the prin...  0.777083  0.222917
21    Robert was rolling a toy truck to Sarah because  0.630455  0.369545
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.630722  0.369278
23      Paul was rolling a toy truck to Emily because  0.612272  0.387728

In [198]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_5m,'she'))

P('subj-pron'|subj=male) =  0.6559105018774668
P('non-subj-pron'|subj=male) =  0.3440895043313503

In [199]:
c1_average_subj_male_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5m,'he')
c1_average_subj_male_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective1_5m,'she')

### verb: "throwing"

In [200]:
transofposs_imperfective_connective1_6 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/6.csv")
transofposs_imperfective_connective1_6.head()

                                            stimulus        he       she
0  Miss Smith was throwing a hat to Mr. Smith bec...  0.579804  0.420196
1    The woman was throwing a hat to the man because  0.540062  0.459938
2            Mary was throwing a hat to John because  0.436248  0.563752
3            Alice was throwing a hat to Bob because  0.369293  0.630707
4  The actress was throwing a hat to the actor be...  0.514479  0.485521

In [201]:
# female subject
transofposs_imperfective_connective1_6f = transofposs_imperfective_connective1_6[0:12]
transofposs_imperfective_connective1_6f = transofposs_imperfective_connective1_6[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_6m = transofposs_imperfective_connective1_6[12:24]

#### female subject

In [202]:
transofposs_imperfective_connective1_6f

                                             stimulus       she        he
0   Miss Smith was throwing a hat to Mr. Smith bec...  0.420196  0.579804
1     The woman was throwing a hat to the man because  0.459938  0.540062
2             Mary was throwing a hat to John because  0.563752  0.436248
3             Alice was throwing a hat to Bob because  0.630707  0.369293
4   The actress was throwing a hat to the actor be...  0.485521  0.514479
5      The girl was throwing a hat to the boy because  0.556906  0.443094
6   Mrs. Taylor was throwing a hat to Mr. Williams...  0.372608  0.627392
7            Emma was throwing a hat to David because  0.587504  0.412496
8   The princess was throwing a hat to the prince ...  0.674506  0.325494
9          Sarah was throwing a hat to Robert because  0.419429  0.580571
10  Mrs. Williams was throwing a hat to  Mr. Taylo...  0.302661  0.697339
11           Emily was throwing a hat to Paul because  0.597454  0.402546
12  Mr. Smith was throwing a hat to Miss Smith bec...  0.456672  0.543328
13    The man was throwing a hat to the woman because  0.438673  0.561327
14            John was throwing a hat to Mary because  0.387180  0.612820
15            Bob was throwing a hat to Alice because  0.460551  0.539449
16  The actor was throwing a hat to the actress be...  0.451539  0.548461
17     The boy was throwing a hat to the girl because  0.417259  0.582741
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.543269  0.456731
19           David was throwing a hat to Emma because  0.574122  0.425878
20  The prince was throwing a hat to the princess ...  0.418722  0.581279
21         Robert was throwing a hat to Sarah because  0.458108  0.541892
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.451780  0.548220
23           Paul was throwing a hat to Emily because  0.516687  0.483313

In [203]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_6f,'he'))

P('subj-pron'|subj=female) =  0.48523935054739314
P('non-subj-pron'|subj=female) =  0.5147606420020262

In [204]:
c1_average_subj_female_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6f,'she')
c1_average_subj_female_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6f,'he')

#### male subject

In [205]:
transofposs_imperfective_connective1_6m

                                             stimulus        he       she
12  Mr. Smith was throwing a hat to Miss Smith bec...  0.543328  0.456672
13    The man was throwing a hat to the woman because  0.561327  0.438673
14            John was throwing a hat to Mary because  0.612820  0.387180
15            Bob was throwing a hat to Alice because  0.539449  0.460551
16  The actor was throwing a hat to the actress be...  0.548461  0.451539
17     The boy was throwing a hat to the girl because  0.582741  0.417259
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.456731  0.543269
19           David was throwing a hat to Emma because  0.425878  0.574122
20  The prince was throwing a hat to the princess ...  0.581279  0.418722
21         Robert was throwing a hat to Sarah because  0.541892  0.458108
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.548220  0.451780
23           Paul was throwing a hat to Emily because  0.483313  0.516687

In [206]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_6m,'she'))

P('subj-pron'|subj=male) =  0.5354531705379486
P('non-subj-pron'|subj=male) =  0.4645468294620514

In [207]:
c1_average_subj_male_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6m,'he')
c1_average_subj_male_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective1_6m,'she')

### verb: "tossing"

In [208]:
transofposs_imperfective_connective1_7 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/7.csv")
transofposs_imperfective_connective1_7.head()

                                            stimulus        he       she
0  Miss Smith was tossing a dish towel to Mr. Smi...  0.585328  0.414672
1  The woman was tossing a dish towel to the man ...  0.523493  0.476507
2      Mary was tossing a dish towel to John because  0.388213  0.611787
3      Alice was tossing a dish towel to Bob because  0.331699  0.668301
4  The actress was tossing a dish towel to the ac...  0.508965  0.491035

In [209]:
# female subject
transofposs_imperfective_connective1_7f = transofposs_imperfective_connective1_7[0:12]
transofposs_imperfective_connective1_7f = transofposs_imperfective_connective1_7f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_7m = transofposs_imperfective_connective1_7[12:24]

#### female subject

In [210]:
transofposs_imperfective_connective1_7f

                                             stimulus       she        he
0   Miss Smith was tossing a dish towel to Mr. Smi...  0.414672  0.585328
1   The woman was tossing a dish towel to the man ...  0.476507  0.523493
2       Mary was tossing a dish towel to John because  0.611787  0.388213
3       Alice was tossing a dish towel to Bob because  0.668301  0.331699
4   The actress was tossing a dish towel to the ac...  0.491035  0.508965
5   The girl was tossing a dish towel to the boy b...  0.591183  0.408817
6   Mrs. Taylor was tossing a dish towel to Mr. Wi...  0.422855  0.577145
7      Emma was tossing a dish towel to David because  0.617119  0.382881
8   The princess was tossing a dish towel to the p...  0.656419  0.343581
9    Sarah was tossing a dish towel to Robert because  0.521670  0.478330
10  Mrs. Williams was tossing a dish towel to  Mr....  0.405925  0.594075
11     Emily was tossing a dish towel to Paul because  0.651711  0.348289

In [211]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_7f,'he'))

P('subj-pron'|subj=female) =  0.5440986280639967
P('non-subj-pron'|subj=female) =  0.4559013570348422

In [212]:
c1_average_subj_female_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7f,'she')
c1_average_subj_female_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7f,'he')

#### male subject

In [213]:
transofposs_imperfective_connective1_7m

                                             stimulus        he       she
12  Mr. Smith was tossing a dish towel to Miss Smi...  0.472673  0.527327
13  The man was tossing a dish towel to the woman ...  0.510290  0.489710
14      John was tossing a dish towel to Mary because  0.527501  0.472499
15      Bob was tossing a dish towel to Alice because  0.471346  0.528654
16  The actor was tossing a dish towel to the actr...  0.528834  0.471166
17  The boy was tossing a dish towel to the girl b...  0.533008  0.466992
18  Mr. William was tossing a dish towel to  Mrs. ...  0.446375  0.553625
19     David was tossing a dish towel to Emma because  0.419020  0.580980
20  The prince was tossing a dish towel to the pri...  0.599484  0.400516
21   Robert was tossing a dish towel to Sarah because  0.492627  0.507373
22  Mr. Taylor was tossing a dish towel to Mrs. Wi...  0.445299  0.554701
23     Paul was tossing a dish towel to Emily because  0.450842  0.549158

In [214]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_7m,'she'))

P('subj-pron'|subj=male) =  0.49144163727760315
P('non-subj-pron'|subj=male) =  0.5085583503047625

In [215]:
c1_average_subj_male_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7m,'he')
c1_average_subj_male_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective1_7m,'she')

### verb: "bringing"

In [216]:
transofposs_imperfective_connective1_8 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/8.csv")
transofposs_imperfective_connective1_8.head()

                                            stimulus        he       she
0  Miss Smith was bringing a glass of water to Mr...  0.585163  0.414837
1  The woman was bringing a glass of water to the...  0.461939  0.538061
2  Mary was bringing a glass of water to John bec...  0.357913  0.642086
3  Alice was bringing a glass of water to Bob bec...  0.347732  0.652268
4  The actress was bringing a glass of water to t...  0.482347  0.517653

In [217]:
# female subject
transofposs_imperfective_connective1_8f = transofposs_imperfective_connective1_8[0:12]
transofposs_imperfective_connective1_8f = transofposs_imperfective_connective1_8f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_8m = transofposs_imperfective_connective1_8[12:24]

#### female subject

In [218]:
transofposs_imperfective_connective1_8f

                                             stimulus       she        he
0   Miss Smith was bringing a glass of water to Mr...  0.414837  0.585163
1   The woman was bringing a glass of water to the...  0.538061  0.461939
2   Mary was bringing a glass of water to John bec...  0.642086  0.357913
3   Alice was bringing a glass of water to Bob bec...  0.652268  0.347732
4   The actress was bringing a glass of water to t...  0.517653  0.482347
5   The girl was bringing a glass of water to the ...  0.594020  0.405980
6   Mrs. Taylor was bringing a glass of water to M...  0.340263  0.659737
7   Emma was bringing a glass of water to David be...  0.643285  0.356715
8   The princess was bringing a glass of water to ...  0.706448  0.293552
9   Sarah was bringing a glass of water to Robert ...  0.487411  0.512589
10  Mrs. Williams was bringing a glass of water to...  0.378784  0.621216
11  Emily was bringing a glass of water to Paul be...  0.650310  0.349690

In [219]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_8f,'he'))

P('subj-pron'|subj=female) =  0.5471188897887865
P('non-subj-pron'|subj=female) =  0.452881100277106

In [220]:
c1_average_subj_female_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8f,'she')
c1_average_subj_female_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8f,'he')

#### male subject

In [221]:
transofposs_imperfective_connective1_8m

                                             stimulus        he       she
12  Mr. Smith was bringing a glass of water to Mis...  0.454991  0.545009
13  The man was bringing a glass of water to the w...  0.476797  0.523203
14  John was bringing a glass of water to Mary bec...  0.588296  0.411704
15  Bob was bringing a glass of water to Alice bec...  0.533660  0.466340
16  The actor was bringing a glass of water to the...  0.533904  0.466096
17  The boy was bringing a glass of water to the g...  0.507618  0.492382
18  Mr. William was bringing a glass of water to  ...  0.433090  0.566910
19  David was bringing a glass of water to Emma be...  0.466984  0.533016
20  The prince was bringing a glass of water to th...  0.548844  0.451156
21  Robert was bringing a glass of water to Sarah ...  0.513589  0.486411
22  Mr. Taylor was bringing a glass of water to Mr...  0.466539  0.533461
23  Paul was bringing a glass of water to Emily be...  0.500463  0.499537

In [222]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_8m,'she'))

P('subj-pron'|subj=male) =  0.5020645335316658
P('non-subj-pron'|subj=male) =  0.4979354788859685

In [223]:
c1_average_subj_male_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8m,'he')
c1_average_subj_male_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective1_8m,'she')

### verb: "forwarding"

In [224]:
transofposs_imperfective_connective1_9 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/9.csv")
transofposs_imperfective_connective1_9.head()

                                            stimulus        he       she
0  Miss Smith was forwarding a gossipy email to M...  0.355915  0.644085
1  The woman was forwarding a gossipy email to th...  0.240062  0.759938
2  Mary was forwarding a gossipy email to John be...  0.243269  0.756731
3  Alice was forwarding a gossipy email to Bob be...  0.180062  0.819938
4  The actress was forwarding a gossipy email to ...  0.222259  0.777741

In [225]:
# female subject
transofposs_imperfective_connective1_9f = transofposs_imperfective_connective1_9[0:12]
transofposs_imperfective_connective1_9f = transofposs_imperfective_connective1_9f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_9m = transofposs_imperfective_connective1_9[12:24]

#### female subject

In [226]:
transofposs_imperfective_connective1_9f

                                             stimulus       she        he
0   Miss Smith was forwarding a gossipy email to M...  0.644085  0.355915
1   The woman was forwarding a gossipy email to th...  0.759938  0.240062
2   Mary was forwarding a gossipy email to John be...  0.756731  0.243269
3   Alice was forwarding a gossipy email to Bob be...  0.819938  0.180062
4   The actress was forwarding a gossipy email to ...  0.777741  0.222259
5   The girl was forwarding a gossipy email to the...  0.796253  0.203747
6   Mrs. Taylor was forwarding a gossipy email to ...  0.670339  0.329661
7   Emma was forwarding a gossipy email to David b...  0.739293  0.260707
8   The princess was forwarding a gossipy email to...  0.803684  0.196315
9   Sarah was forwarding a gossipy email to Robert...  0.609557  0.390443
10  Mrs. Williams was forwarding a gossipy email t...  0.601948  0.398052
11  Emily was forwarding a gossipy email to Paul b...  0.757565  0.242435

In [227]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_9f,'he'))

P('subj-pron'|subj=female) =  0.7280892779429754
P('non-subj-pron'|subj=female) =  0.2719107170899709

In [228]:
c1_average_subj_female_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9f,'she')
c1_average_subj_female_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9f,'he')

#### male subject

In [229]:
transofposs_imperfective_connective1_9m

                                             stimulus        he       she
12  Mr. Smith was forwarding a gossipy email to Mi...  0.562521  0.437479
13  The man was forwarding a gossipy email to the ...  0.680577  0.319423
14  John was forwarding a gossipy email to Mary be...  0.625240  0.374760
15  Bob was forwarding a gossipy email to Alice be...  0.632196  0.367804
16  The actor was forwarding a gossipy email to th...  0.573705  0.426295
17  The boy was forwarding a gossipy email to the ...  0.702597  0.297403
18  Mr. William was forwarding a gossipy email to ...  0.521947  0.478053
19  David was forwarding a gossipy email to Emma b...  0.533753  0.466246
20  The prince was forwarding a gossipy email to t...  0.685170  0.314830
21  Robert was forwarding a gossipy email to Sarah...  0.609403  0.390597
22  Mr. Taylor was forwarding a gossipy email to M...  0.590611  0.409389
23  Paul was forwarding a gossipy email to Emily b...  0.590736  0.409264

In [230]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_9m,'she'))

P('subj-pron'|subj=male) =  0.6090379953384399
P('non-subj-pron'|subj=male) =  0.3909620021780332

In [231]:
c1_average_subj_male_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9m,'he')
c1_average_subj_male_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective1_9m,'she')

### verb: "mailing"

In [232]:
transofposs_imperfective_connective1_10 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/10.csv")
transofposs_imperfective_connective1_10.head()

                                            stimulus        he       she
0  Miss Smith was mailing a letter to Mr. Smith b...  0.469440  0.530560
1  The woman was mailing a letter to the man because  0.367252  0.632748
2          Mary was mailing a letter to John because  0.294446  0.705554
3          Alice was mailing a letter to Bob because  0.191434  0.808566
4  The actress was mailing a letter to the actor ...  0.329055  0.670945

In [233]:
# female subject
transofposs_imperfective_connective1_10f = transofposs_imperfective_connective1_10[0:12]
transofposs_imperfective_connective1_10f = transofposs_imperfective_connective1_10f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_10m = transofposs_imperfective_connective1_10[12:24]

#### female subject

In [234]:
transofposs_imperfective_connective1_10f

                                             stimulus       she        he
0   Miss Smith was mailing a letter to Mr. Smith b...  0.530560  0.469440
1   The woman was mailing a letter to the man because  0.632748  0.367252
2           Mary was mailing a letter to John because  0.705554  0.294446
3           Alice was mailing a letter to Bob because  0.808566  0.191434
4   The actress was mailing a letter to the actor ...  0.670945  0.329055
5    The girl was mailing a letter to the boy because  0.721327  0.278673
6   Mrs. Taylor was mailing a letter to Mr. Willia...  0.560517  0.439483
7          Emma was mailing a letter to David because  0.693140  0.306860
8   The princess was mailing a letter to the princ...  0.804163  0.195837
9        Sarah was mailing a letter to Robert because  0.560446  0.439554
10  Mrs. Williams was mailing a letter to Mr. Tayl...  0.556852  0.443148
11         Emily was mailing a letter to Paul because  0.698260  0.301740

In [235]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_10f,'he'))

P('subj-pron'|subj=female) =  0.6619230906168619
P('non-subj-pron'|subj=female) =  0.33807691435019177

In [236]:
c1_average_subj_female_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10f,'she')
c1_average_subj_female_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10f,'he')

#### male subject

In [237]:
transofposs_imperfective_connective1_10m

                                             stimulus        he       she
12  Mr. Smith was mailing a letter to Miss Smith b...  0.632816  0.367184
13  The man was mailing a letter to the woman because  0.718203  0.281797
14          John was mailing a letter to Mary because  0.732690  0.267310
15          Bob was mailing a letter to Alice because  0.802370  0.197630
16  The actor was mailing a letter to the actress ...  0.666528  0.333472
17   The boy was mailing a letter to the girl because  0.753389  0.246611
18  Mr. William was mailing a letter to  Mrs. Tayl...  0.616409  0.383591
19         David was mailing a letter to Emma because  0.671110  0.328890
20  The prince was mailing a letter to the princes...  0.755585  0.244415
21       Robert was mailing a letter to Sarah because  0.693115  0.306885
22  Mr. Taylor was mailing a letter to Mrs. Willia...  0.691427  0.308573
23         Paul was mailing a letter to Emily because  0.679355  0.320645

In [238]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_10m,'she'))

P('subj-pron'|subj=male) =  0.7010830938816071
P('non-subj-pron'|subj=male) =  0.29891690611839294

In [239]:
c1_average_subj_male_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10m,'he')
c1_average_subj_male_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective1_10m,'she')

### verb: "shipping"

In [240]:
transofposs_imperfective_connective1_11 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/11.csv")
transofposs_imperfective_connective1_11.head()

                                            stimulus        he       she
0  Miss Smith was shipping a package to Mr. Smith...  0.451310  0.548690
1  The woman was shipping a package to the man be...  0.354469  0.645531
2        Mary was shipping a package to John because  0.296083  0.703917
3        Alice was shipping a package to Bob because  0.200801  0.799199
4  The actress was shipping a package to the acto...  0.357390  0.642610

In [241]:
# female subject
transofposs_imperfective_connective1_11f = transofposs_imperfective_connective1_11[0:12]
transofposs_imperfective_connective1_11f = transofposs_imperfective_connective1_11f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_11m = transofposs_imperfective_connective1_11[12:24]

#### female subject

In [242]:
transofposs_imperfective_connective1_11f

                                             stimulus       she        he
0   Miss Smith was shipping a package to Mr. Smith...  0.548690  0.451310
1   The woman was shipping a package to the man be...  0.645531  0.354469
2         Mary was shipping a package to John because  0.703917  0.296083
3         Alice was shipping a package to Bob because  0.799199  0.200801
4   The actress was shipping a package to the acto...  0.642610  0.357390
5   The girl was shipping a package to the boy bec...  0.708737  0.291263
6   Mrs. Taylor was shipping a package to Mr. Will...  0.530015  0.469985
7        Emma was shipping a package to David because  0.723698  0.276302
8   The princess was shipping a package to the pri...  0.792348  0.207652
9      Sarah was shipping a package to Robert because  0.527960  0.472040
10  Mrs. Williams was shipping a package to Mr. Ta...  0.543194  0.456806
11       Emily was shipping a package to Paul because  0.665655  0.334345

In [243]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_11f,'he'))

P('subj-pron'|subj=female) =  0.6526294549306234
P('non-subj-pron'|subj=female) =  0.34737054631114006

In [244]:
c1_average_subj_female_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11f,'she')
c1_average_subj_female_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11f,'he')

#### male subject

In [245]:
transofposs_imperfective_connective1_11m

                                             stimulus        he       she
12  Mr. Smith was shipping a package to Miss Smith...  0.552903  0.447097
13  The man was shipping a package to the woman be...  0.651923  0.348077
14        John was shipping a package to Mary because  0.683188  0.316812
15        Bob was shipping a package to Alice because  0.697031  0.302969
16  The actor was shipping a package to the actres...  0.602195  0.397805
17  The boy was shipping a package to the girl bec...  0.667644  0.332356
18  Mr. William was shipping a package to  Mrs. Ta...  0.542458  0.457542
19       David was shipping a package to Emma because  0.585278  0.414722
20  The prince was shipping a package to the princ...  0.715452  0.284548
21     Robert was shipping a package to Sarah because  0.609379  0.390621
22  Mr. Taylor was shipping a package to Mrs. Will...  0.603233  0.396767
23       Paul was shipping a package to Emily because  0.655071  0.344929

In [246]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_11m,'she'))

P('subj-pron'|subj=male) =  0.6304795493682226
P('non-subj-pron'|subj=male) =  0.36952048788468045

In [247]:
c1_average_subj_male_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11m,'he')
c1_average_subj_male_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective1_11m,'she')

### verb: "transmitting"

In [248]:
transofposs_imperfective_connective1_12 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/12.csv")
transofposs_imperfective_connective1_12.head()

                                            stimulus        he       she
0  Miss Smith was transmitting a message to Mr. S...  0.471645  0.528355
1  The woman was transmitting a message to the ma...  0.320482  0.679518
2    Mary was transmitting a message to John because  0.285516  0.714485
3    Alice was transmitting a message to Bob because  0.179184  0.820816
4  The actress was transmitting a message to the ...  0.237930  0.762070

In [249]:
# female subject
transofposs_imperfective_connective1_12f = transofposs_imperfective_connective1_12[0:12]
transofposs_imperfective_connective1_12f = transofposs_imperfective_connective1_12f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_12m = transofposs_imperfective_connective1_12[12:24]

#### female subject

In [250]:
transofposs_imperfective_connective1_12f

                                             stimulus       she        he
0   Miss Smith was transmitting a message to Mr. S...  0.528355  0.471645
1   The woman was transmitting a message to the ma...  0.679518  0.320482
2     Mary was transmitting a message to John because  0.714485  0.285516
3     Alice was transmitting a message to Bob because  0.820816  0.179184
4   The actress was transmitting a message to the ...  0.762070  0.237930
5   The girl was transmitting a message to the boy...  0.727662  0.272338
6   Mrs. Taylor was transmitting a message to Mr. ...  0.513728  0.486272
7    Emma was transmitting a message to David because  0.700842  0.299158
8   The princess was transmitting a message to the...  0.811306  0.188694
9   Sarah was transmitting a message to Robert bec...  0.586768  0.413232
10  Mrs. Williams was transmitting a message to Mr...  0.539290  0.460710
11   Emily was transmitting a message to Paul because  0.705351  0.294649

In [251]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_12f,'he'))

P('subj-pron'|subj=female) =  0.6741824646790823
P('non-subj-pron'|subj=female) =  0.3258175390462081

In [252]:
c1_average_subj_female_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12f,'she')
c1_average_subj_female_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12f,'he')

#### male subject

In [253]:
transofposs_imperfective_connective1_12m

                                             stimulus        he       she
12  Mr. Smith was transmitting a message to Miss S...  0.571645  0.428355
13  The man was transmitting a message to the woma...  0.666905  0.333095
14    John was transmitting a message to Mary because  0.715619  0.284381
15    Bob was transmitting a message to Alice because  0.848791  0.151209
16  The actor was transmitting a message to the ac...  0.676830  0.323170
17  The boy was transmitting a message to the girl...  0.681252  0.318747
18  Mr. William was transmitting a message to  Mrs...  0.569655  0.430345
19   David was transmitting a message to Emma because  0.644348  0.355652
20  The prince was transmitting a message to the p...  0.665910  0.334090
21  Robert was transmitting a message to Sarah bec...  0.693192  0.306808
22  Mr. Taylor was transmitting a message to Mrs. ...  0.632418  0.367582
23   Paul was transmitting a message to Emily because  0.720520  0.279480

In [254]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_12m,'she'))

P('subj-pron'|subj=male) =  0.6739237705866495
P('non-subj-pron'|subj=male) =  0.3260762393474579

In [255]:
c1_average_subj_male_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12m,'he')
c1_average_subj_male_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective1_12m,'she')

### verb: "wiring"

In [256]:
transofposs_imperfective_connective1_14 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/14.csv")
transofposs_imperfective_connective1_14.head()

                                            stimulus        he       she
0   Miss Smith was wiring money to Mr. Smith because  0.471844  0.528156
1      The woman was wiring money to the man because  0.447142  0.552858
2              Mary was wiring money to John because  0.388709  0.611291
3              Alice was wiring money to Bob because  0.262952  0.737048
4  The actress was wiring money to the actor because  0.349760  0.650240

In [257]:
# female subject
transofposs_imperfective_connective1_14f = transofposs_imperfective_connective1_14[0:12]
transofposs_imperfective_connective1_14f = transofposs_imperfective_connective1_14f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_14m = transofposs_imperfective_connective1_14[12:24]

#### female subject

In [258]:
transofposs_imperfective_connective1_14f

                                             stimulus       she        he
0    Miss Smith was wiring money to Mr. Smith because  0.528156  0.471844
1       The woman was wiring money to the man because  0.552858  0.447142
2               Mary was wiring money to John because  0.611291  0.388709
3               Alice was wiring money to Bob because  0.737048  0.262952
4   The actress was wiring money to the actor because  0.650240  0.349760
5        The girl was wiring money to the boy because  0.627121  0.372879
6   Mrs. Taylor was wiring money to Mr. Williams b...  0.511246  0.488754
7              Emma was wiring money to David because  0.650654  0.349346
8   The princess was wiring money to the prince be...  0.700067  0.299933
9            Sarah was wiring money to Robert because  0.474751  0.525249
10  Mrs. Williams was wiring money to Mr. Taylor b...  0.496558  0.503442
11             Emily was wiring money to Paul because  0.595563  0.404437

In [259]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_14f,'he'))

P('subj-pron'|subj=female) =  0.5946294168631235
P('non-subj-pron'|subj=female) =  0.40537059555451077

In [260]:
c1_average_subj_female_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14f,'she')
c1_average_subj_female_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14f,'he')

#### male subject

In [261]:
transofposs_imperfective_connective1_14m

                                             stimulus        he       she
12   Mr. Smith was wiring money to Miss Smith because  0.507320  0.492680
13      The man was wiring money to the woman because  0.603983  0.396017
14              John was wiring money to Mary because  0.589744  0.410256
15              Bob was wiring money to Alice because  0.766349  0.233651
16  The actor was wiring money to the actress because  0.583664  0.416336
17       The boy was wiring money to the girl because  0.651048  0.348952
18  Mr. William was wiring money to  Mrs. Taylor b...  0.512385  0.487615
19             David was wiring money to Emma because  0.560322  0.439678
20  The prince was wiring money to the princess be...  0.664932  0.335068
21           Robert was wiring money to Sarah because  0.582847  0.417153
22  Mr. Taylor was wiring money to Mrs. Williams b...  0.590371  0.409629
23             Paul was wiring money to Emily because  0.577758  0.422242

In [262]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_14m,'she'))

P('subj-pron'|subj=male) =  0.5992268174886703
P('non-subj-pron'|subj=male) =  0.40077320237954456

In [263]:
c1_average_subj_male_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14m,'he')
c1_average_subj_male_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective1_14m,'she')

### verb: "carrying"

In [264]:
transofposs_imperfective_connective1_15 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/15.csv")
transofposs_imperfective_connective1_15.head()

                                            stimulus        he       she
0  Miss Smith was carrying a tray to Mr. Smith be...  0.520668  0.479332
1   The woman was carrying a tray to the man because  0.388970  0.611030
2           Mary was carrying a tray to John because  0.345812  0.654188
3           Alice was carrying a tray to Bob because  0.288949  0.711051
4  The actress was carrying a tray to the actor b...  0.393517  0.606483

In [265]:
# female subject
transofposs_imperfective_connective1_15f = transofposs_imperfective_connective1_15[0:12]
transofposs_imperfective_connective1_15f = transofposs_imperfective_connective1_15f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_15m = transofposs_imperfective_connective1_15[12:24]

#### female subject

In [266]:
transofposs_imperfective_connective1_15f

                                             stimulus       she        he
0   Miss Smith was carrying a tray to Mr. Smith be...  0.479332  0.520668
1    The woman was carrying a tray to the man because  0.611030  0.388970
2            Mary was carrying a tray to John because  0.654188  0.345812
3            Alice was carrying a tray to Bob because  0.711051  0.288949
4   The actress was carrying a tray to the actor b...  0.606483  0.393517
5     The girl was carrying a tray to the boy because  0.653700  0.346300
6   Mrs. Taylor was carrying a tray to Mr. William...  0.393632  0.606368
7           Emma was carrying a tray to David because  0.632748  0.367252
8   The princess was carrying a tray to the prince...  0.799592  0.200408
9         Sarah was carrying a tray to Robert because  0.499887  0.500113
10  Mrs. Williams was carrying a tray to Mr. Taylo...  0.444715  0.555285
11          Emily was carrying a tray to Paul because  0.619897  0.380103

In [267]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_15f,'he'))

P('subj-pron'|subj=female) =  0.5921879261732101
P('non-subj-pron'|subj=female) =  0.40781207258502644

In [268]:
c1_average_subj_female_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15f,'she')
c1_average_subj_female_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15f,'he')

#### male subject

In [269]:
transofposs_imperfective_connective1_15m

                                             stimulus        he       she
12  Mr. Smith was carrying a tray to Miss Smith be...  0.500722  0.499278
13   The man was carrying a tray to the woman because  0.584062  0.415938
14           John was carrying a tray to Mary because  0.602922  0.397078
15           Bob was carrying a tray to Alice because  0.598082  0.401918
16  The actor was carrying a tray to the actress b...  0.586351  0.413649
17    The boy was carrying a tray to the girl because  0.592755  0.407245
18  Mr. William was carrying a tray to  Mrs. Taylo...  0.437017  0.562983
19          David was carrying a tray to Emma because  0.487179  0.512821
20  The prince was carrying a tray to the princess...  0.611551  0.388449
21        Robert was carrying a tray to Sarah because  0.525920  0.474080
22  Mr. Taylor was carrying a tray to Mrs. William...  0.469818  0.530182
23          Paul was carrying a tray to Emily because  0.503009  0.496991

In [270]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_15m,'she'))

P('subj-pron'|subj=male) =  0.5416156078378359
P('non-subj-pron'|subj=male) =  0.45838438471158344

In [271]:
c1_average_subj_male_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15m,'he')
c1_average_subj_male_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective1_15m,'she')

### verb: "delivering"

In [272]:
transofposs_imperfective_connective1_16 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/16.csv")
transofposs_imperfective_connective1_16.head()

                                            stimulus        he       she
0  Miss Smith was delivering a subpoena to Mr. Sm...  0.542259  0.457741
1  The woman was delivering a subpoena to the man...  0.508794  0.491206
2     Mary was delivering a subpoena to John because  0.517529  0.482471
3     Alice was delivering a subpoena to Bob because  0.337448  0.662552
4  The actress was delivering a subpoena to the a...  0.348446  0.651555

In [273]:
# female subject
transofposs_imperfective_connective1_16f = transofposs_imperfective_connective1_16[0:12]
transofposs_imperfective_connective1_16f = transofposs_imperfective_connective1_16f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_16m = transofposs_imperfective_connective1_16[12:24]

#### female subject

In [274]:
transofposs_imperfective_connective1_16f

                                             stimulus       she        he
0   Miss Smith was delivering a subpoena to Mr. Sm...  0.457741  0.542259
1   The woman was delivering a subpoena to the man...  0.491206  0.508794
2      Mary was delivering a subpoena to John because  0.482471  0.517529
3      Alice was delivering a subpoena to Bob because  0.662552  0.337448
4   The actress was delivering a subpoena to the a...  0.651555  0.348446
5   The girl was delivering a subpoena to the boy ...  0.520955  0.479045
6   Mrs. Taylor was delivering a subpoena to Mr. W...  0.459582  0.540417
7     Emma was delivering a subpoena to David because  0.512393  0.487607
8   The princess was delivering a subpoena to the ...  0.638026  0.361974
9   Sarah was delivering a subpoena to Robert because  0.384624  0.615376
10  Mrs. Williams was delivering a subpoena to Mr....  0.473134  0.526866
11    Emily was delivering a subpoena to Paul because  0.538986  0.461014

In [275]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_16f,'he'))

P('subj-pron'|subj=female) =  0.5227689296007156
P('non-subj-pron'|subj=female) =  0.47723107288281125

In [276]:
c1_average_subj_female_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16f,'she')
c1_average_subj_female_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16f,'he')

#### male subject

In [277]:
transofposs_imperfective_connective1_16m

                                             stimulus        he       she
12  Mr. Smith was delivering a subpoena to Miss Sm...  0.513258  0.486742
13  The man was delivering a subpoena to the woman...  0.490757  0.509243
14     John was delivering a subpoena to Mary because  0.546910  0.453090
15     Bob was delivering a subpoena to Alice because  0.658721  0.341279
16  The actor was delivering a subpoena to the act...  0.534659  0.465341
17  The boy was delivering a subpoena to the girl ...  0.502218  0.497782
18  Mr. William was delivering a subpoena to Mrs. ...  0.540937  0.459063
19    David was delivering a subpoena to Emma because  0.482967  0.517033
20  The prince was delivering a subpoena to the pr...  0.546910  0.453090
21  Robert was delivering a subpoena to Sarah because  0.509661  0.490339
22  Mr. Taylor was delivering a subpoena to Mrs. W...  0.545914  0.454086
23    Paul was delivering a subpoena to Emily because  0.484140  0.515860

In [278]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_16m,'she'))

P('subj-pron'|subj=male) =  0.5297543158133825
P('non-subj-pron'|subj=male) =  0.47024569660425186

In [279]:
c1_average_subj_male_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16m,'he')
c1_average_subj_male_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective1_16m,'she')

### verb: "giving"

In [280]:
transofposs_imperfective_connective1_17 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/17.csv")
transofposs_imperfective_connective1_17.head()

                                            stimulus        he       she
0  Miss Smith was giving a sweater to Mr. Smith b...  0.576049  0.423951
1  The woman was giving a sweater to the man because  0.541416  0.458584
2          Mary was giving a sweater to John because  0.402719  0.597281
3          Alice was giving a sweater to Bob because  0.371662  0.628338
4  The actress was giving a sweater to the actor ...  0.472646  0.527354

In [281]:
# female subject
transofposs_imperfective_connective1_17f = transofposs_imperfective_connective1_17[0:12]
transofposs_imperfective_connective1_17f = transofposs_imperfective_connective1_17f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_17m = transofposs_imperfective_connective1_17[12:24]

#### female subject

In [282]:
transofposs_imperfective_connective1_17f

                                             stimulus       she        he
0   Miss Smith was giving a sweater to Mr. Smith b...  0.423951  0.576049
1   The woman was giving a sweater to the man because  0.458584  0.541416
2           Mary was giving a sweater to John because  0.597281  0.402719
3           Alice was giving a sweater to Bob because  0.628338  0.371662
4   The actress was giving a sweater to the actor ...  0.527354  0.472646
5    The girl was giving a sweater to the boy because  0.525253  0.474747
6   Mrs. Taylor was giving a sweater to Mr. Willia...  0.393194  0.606806
7          Emma was giving a sweater to David because  0.592531  0.407469
8   The princess was giving a sweater to the princ...  0.613353  0.386647
9        Sarah was giving a sweater to Robert because  0.451506  0.548495
10  Mrs. Williams was giving a sweater to Mr. Tayl...  0.432704  0.567296
11         Emily was giving a sweater to Paul because  0.609407  0.390593

In [283]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_17f,'he'))

P('subj-pron'|subj=female) =  0.5211212585369746
P('non-subj-pron'|subj=female) =  0.47887874643007916

In [284]:
c1_average_subj_female_subj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17f,'she')
c1_average_subj_female_obj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17f,'he')

#### male subject

In [285]:
transofposs_imperfective_connective1_17m

                                             stimulus        he       she
12  Mr. Smith was giving a sweater to Miss Smith b...  0.470889  0.529111
13  The man was giving a sweater to the woman because  0.475160  0.524840
14          John was giving a sweater to Mary because  0.541532  0.458468
15          Bob was giving a sweater to Alice because  0.482351  0.517649
16  The actor was giving a sweater to the actress ...  0.526880  0.473120
17   The boy was giving a sweater to the girl because  0.476711  0.523289
18  Mr. William was giving a sweater to  Mrs. Tayl...  0.452786  0.547214
19         David was giving a sweater to Emma because  0.386210  0.613790
20  The prince was giving a sweater to the princes...  0.554841  0.445159
21       Robert was giving a sweater to Sarah because  0.476718  0.523282
22  Mr. Taylor was giving a sweater to Mrs. Willia...  0.498049  0.501951
23         Paul was giving a sweater to Emily because  0.435657  0.564343

In [286]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_17m,'she'))

P('subj-pron'|subj=male) =  0.48148200412591297
P('non-subj-pron'|subj=male) =  0.5185179760058721

In [287]:
c1_average_subj_male_subj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17m,'he')
c1_average_subj_male_obj_pron['giving'] = compute_average(transofposs_imperfective_connective1_17m,'she')

### verb: "handing"

In [288]:
transofposs_imperfective_connective1_18 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/18.csv")
transofposs_imperfective_connective1_18.head()

                                            stimulus        he       she
0  Miss Smith was handing a book to Mr. Smith bec...  0.523235  0.476765
1    The woman was handing a book to the man because  0.456459  0.543541
2            Mary was handing a book to John because  0.327475  0.672525
3            Alice was handing a book to Bob because  0.281865  0.718135
4  The actress was handing a book to the actor be...  0.420222  0.579778

In [289]:
# female subject
transofposs_imperfective_connective1_18f = transofposs_imperfective_connective1_18[0:12]
transofposs_imperfective_connective1_18f = transofposs_imperfective_connective1_18f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_18m = transofposs_imperfective_connective1_18[12:24]

#### female subject

In [290]:
transofposs_imperfective_connective1_18f

                                             stimulus       she        he
0   Miss Smith was handing a book to Mr. Smith bec...  0.476765  0.523235
1     The woman was handing a book to the man because  0.543541  0.456459
2             Mary was handing a book to John because  0.672525  0.327475
3             Alice was handing a book to Bob because  0.718135  0.281865
4   The actress was handing a book to the actor be...  0.579778  0.420222
5      The girl was handing a book to the boy because  0.552295  0.447705
6   Mrs. Taylor was handing a book to Mr. Williams...  0.454898  0.545102
7            Emma was handing a book to David because  0.641852  0.358148
8   The princess was handing a book to the prince ...  0.752176  0.247824
9          Sarah was handing a book to Robert because  0.484161  0.515839
10  Mrs. Williams was handing a book to Mr. Taylor...  0.491957  0.508044
11           Emily was handing a book to Paul because  0.667765  0.332235

In [291]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_18f,'he'))

P('subj-pron'|subj=female) =  0.5863204623262087
P('non-subj-pron'|subj=female) =  0.4136795538167159

In [292]:
c1_average_subj_female_subj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18f,'she')
c1_average_subj_female_obj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18f,'he')

#### male subject

In [293]:
transofposs_imperfective_connective1_18m

                                             stimulus        he       she
12  Mr. Smith was handing a book to Miss Smith bec...  0.520308  0.479692
13    The man was handing a book to the woman because  0.538024  0.461976
14            John was handing a book to Mary because  0.606818  0.393182
15            Bob was handing a book to Alice because  0.578113  0.421887
16  The actor was handing a book to the actress be...  0.552253  0.447747
17     The boy was handing a book to the girl because  0.557331  0.442669
18  Mr. William was handing a book to Mrs. Taylor ...  0.517984  0.482016
19           David was handing a book to Emma because  0.460045  0.539955
20  The prince was handing a book to the princess ...  0.623971  0.376030
21         Robert was handing a book to Sarah because  0.509835  0.490165
22  Mr. Taylor was handing a book to Mrs. Williams...  0.534270  0.465730
23           Paul was handing a book to Emily because  0.520912  0.479088

In [294]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_18m,'she'))

P('subj-pron'|subj=male) =  0.5433219398061434
P('non-subj-pron'|subj=male) =  0.456678070127964

In [295]:
c1_average_subj_male_subj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18m,'he')
c1_average_subj_male_obj_pron['handing'] = compute_average(transofposs_imperfective_connective1_18m,'she')

### verb: "passing"

In [296]:
transofposs_imperfective_connective1_19 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/19.csv")
transofposs_imperfective_connective1_19.head()

                                            stimulus        he       she
0  Miss Smith was passing a sandwich to Mr. Smith...  0.531989  0.468011
1  The woman was passing a sandwich to the man be...  0.488933  0.511068
2        Mary was passing a sandwich to John because  0.422719  0.577281
3        Alice was passing a sandwich to Bob because  0.345306  0.654694
4  The actress was passing a sandwich to the acto...  0.462032  0.537968

In [297]:
# female subject
transofposs_imperfective_connective1_19f = transofposs_imperfective_connective1_19[0:12]
transofposs_imperfective_connective1_19f = transofposs_imperfective_connective1_19f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_19m = transofposs_imperfective_connective1_19[12:24]

#### female subject

In [298]:
transofposs_imperfective_connective1_19f

                                             stimulus       she        he
0   Miss Smith was passing a sandwich to Mr. Smith...  0.468011  0.531989
1   The woman was passing a sandwich to the man be...  0.511068  0.488933
2         Mary was passing a sandwich to John because  0.577281  0.422719
3         Alice was passing a sandwich to Bob because  0.654694  0.345306
4   The actress was passing a sandwich to the acto...  0.537968  0.462032
5   The girl was passing a sandwich to the boy bec...  0.540167  0.459833
6   Mrs. Taylor was passing a sandwich to Mr. Will...  0.338923  0.661077
7        Emma was passing a sandwich to David because  0.553887  0.446113
8   The princess was passing a sandwich to the pri...  0.651650  0.348350
9      Sarah was passing a sandwich to Robert because  0.436421  0.563578
10  Mrs. Williams was passing a sandwich to  Mr. T...  0.287479  0.712521
11       Emily was passing a sandwich to Paul because  0.560626  0.439374

In [299]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_19f,'he'))

P('subj-pron'|subj=female) =  0.5098477949698766
P('non-subj-pron'|subj=female) =  0.4901522025465965

In [300]:
c1_average_subj_female_subj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19f,'she')
c1_average_subj_female_obj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19f,'he')

#### male subject

In [301]:
transofposs_imperfective_connective1_19m

                                             stimulus        he       she
12  Mr. Smith was passing a sandwich to Miss Smith...  0.520653  0.479347
13  The man was passing a sandwich to the woman be...  0.550607  0.449393
14        John was passing a sandwich to Mary because  0.623898  0.376102
15        Bob was passing a sandwich to Alice because  0.601025  0.398975
16  The actor was passing a sandwich to the actres...  0.559984  0.440016
17  The boy was passing a sandwich to the girl bec...  0.552297  0.447703
18  Mr. William was passing a sandwich to  Mrs. Ta...  0.473318  0.526682
19       David was passing a sandwich to Emma because  0.488048  0.511952
20  The prince was passing a sandwich to the princ...  0.582856  0.417144
21     Robert was passing a sandwich to Sarah because  0.550550  0.449450
22  Mr. Taylor was passing a sandwich to Mrs. Will...  0.514056  0.485944
23       Paul was passing a sandwich to Emily because  0.530511  0.469489

In [302]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_19m,'she'))

P('subj-pron'|subj=male) =  0.5456502710779508
P('non-subj-pron'|subj=male) =  0.45434971650441486

In [303]:
c1_average_subj_male_subj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19m,'he')
c1_average_subj_male_obj_pron['passing'] = compute_average(transofposs_imperfective_connective1_19m,'she')

### verb: "serving"

In [304]:
transofposs_imperfective_connective1_20 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective1/20.csv")
transofposs_imperfective_connective1_20.head()

                                            stimulus        he       she
0  Miss Smith was serving a chili to Mr. Smith be...  0.626060  0.373940
1   The woman was serving a chili to the man because  0.567962  0.432038
2           Mary was serving a chili to John because  0.489605  0.510395
3           Alice was serving a chili to Bob because  0.473679  0.526321
4  The actress was serving a chili to the actor b...  0.520922  0.479078

In [305]:
# female subject
transofposs_imperfective_connective1_20f = transofposs_imperfective_connective1_20[0:12]
transofposs_imperfective_connective1_20f = transofposs_imperfective_connective1_20f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective1_20m = transofposs_imperfective_connective1_20[12:24]

#### female subject

In [306]:
transofposs_imperfective_connective1_20f

                                             stimulus       she        he
0   Miss Smith was serving a chili to Mr. Smith be...  0.373940  0.626060
1    The woman was serving a chili to the man because  0.432038  0.567962
2            Mary was serving a chili to John because  0.510395  0.489605
3            Alice was serving a chili to Bob because  0.526321  0.473679
4   The actress was serving a chili to the actor b...  0.479078  0.520922
5     The girl was serving a chili to the boy because  0.432692  0.567308
6   Mrs. Taylor was serving a chili to Mr. William...  0.363729  0.636271
7           Emma was serving a chili to David because  0.554049  0.445951
8   The princess was serving a chili to the prince...  0.624254  0.375746
9         Sarah was serving a chili to Robert because  0.385191  0.614809
10  Mrs. Williams was serving a chili to Mr. Taylo...  0.364405  0.635595
11          Emily was serving a chili to Paul because  0.526506  0.473494

In [307]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective1_20f,'he'))

P('subj-pron'|subj=female) =  0.4643833264708519
P('non-subj-pron'|subj=female) =  0.5356166561444601

In [308]:
c1_average_subj_female_subj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20f,'she')
c1_average_subj_female_obj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20f,'he')

#### male subject

In [309]:
transofposs_imperfective_connective1_20m

                                             stimulus        he       she
12  Mr. Smith was serving a chili to Miss Smith be...  0.497199  0.502801
13   The man was serving a chili to the woman because  0.506957  0.493043
14           John was serving a chili to Mary because  0.567750  0.432250
15           Bob was serving a chili to Alice because  0.509648  0.490352
16  The actor was serving a chili to the actress b...  0.539560  0.460440
17    The boy was serving a chili to the girl because  0.499083  0.500917
18  Mr. William was serving a chili to  Mrs. Taylo...  0.467423  0.532577
19          David was serving a chili to Emma because  0.441238  0.558762
20  The prince was serving a chili to the princess...  0.629208  0.370792
21        Robert was serving a chili to Sarah because  0.527335  0.472665
22  Mr. Taylor was serving a chili to Mrs. William...  0.522990  0.477011
23          Paul was serving a chili to Emily because  0.460878  0.539122

In [310]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective1_20m,'she'))

P('subj-pron'|subj=male) =  0.5141057297587395
P('non-subj-pron'|subj=male) =  0.4858942652742068

In [311]:
c1_average_subj_male_subj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20m,'he')
c1_average_subj_male_obj_pron['serving'] = compute_average(transofposs_imperfective_connective1_20m,'she')

## Summary of Results

In [312]:
c1_results_fsubj_subjpron = pd.DataFrame(list(c1_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c1_results_fsubj_objpron = pd.DataFrame(list(c1_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c1_results_fsubj = c1_results_fsubj_subjpron.merge(c1_results_fsubj_objpron)
c1_results_fsubj

            verb  subj_ref_female_subj  obj_ref_female_subj
0       chucking              0.471533             0.528467
1       flinging              0.509371             0.490629
2        kicking              0.567760             0.432240
3        lobbing              0.481519             0.518481
4        rolling              0.487948             0.512052
5       throwing              0.485239             0.514761
6        tossing              0.544099             0.455901
7       bringing              0.547119             0.452881
8     forwarding              0.728089             0.271911
9        mailing              0.661923             0.338077
10      shipping              0.652629             0.347371
11  transmitting              0.674182             0.325818
12        wiring              0.594629             0.405371
13      carrying              0.592188             0.407812
14    delivering              0.522769             0.477231
15        giving              0.521121             0.478879
16       handing              0.586320             0.413680
17       passing              0.509848             0.490152
18       serving              0.464383             0.535617

In [313]:
c1_results_msubj_subjpron = pd.DataFrame(list(c1_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c1_results_msubj_objpron = pd.DataFrame(list(c1_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c1_results_msubj = c1_results_msubj_subjpron.merge(c1_results_msubj_objpron)
c1_results_msubj

            verb  subj_ref_male_subj  obj_ref_male_subj
0       chucking            0.521805           0.478195
1       flinging            0.566134           0.433866
2        kicking            0.550563           0.449437
3        lobbing            0.544833           0.455167
4        rolling            0.655911           0.344090
5       throwing            0.535453           0.464547
6        tossing            0.491442           0.508558
7       bringing            0.502065           0.497935
8     forwarding            0.609038           0.390962
9        mailing            0.701083           0.298917
10      shipping            0.630480           0.369520
11  transmitting            0.673924           0.326076
12        wiring            0.599227           0.400773
13      carrying            0.541616           0.458384
14    delivering            0.529754           0.470246
15        giving            0.481482           0.518518
16       handing            0.543322           0.456678
17       passing            0.545650           0.454350
18       serving            0.514106           0.485894

In [314]:
c1_results = c1_results_fsubj.merge(c1_results_msubj)
c1_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,chucking,0.471533,0.528467,0.521805,0.478195
1,flinging,0.509371,0.490629,0.566134,0.433866
2,kicking,0.567760,0.432240,0.550563,0.449437
3,lobbing,0.481519,0.518481,0.544833,0.455167
4,rolling,0.487948,0.512052,0.655911,0.344090
5,throwing,0.485239,0.514761,0.535453,0.464547
6,tossing,0.544099,0.455901,0.491442,0.508558
7,bringing,0.547119,0.452881,0.502065,0.497935
8,forwarding,0.728089,0.271911,0.609038,0.390962
9,mailing,0.661923,0.338077,0.701083,0.298917
10,shipping,0.652629,0.347371,0.630480,0.369520
11,transmitting,0.674182,0.325818,0.673924,0.326076
12,wiring,0.594629,0.405371,0.599227,0.400773
13,carrying,0.592188,0.407812,0.541616,0.458384
14,delivering,0.522769,0.477231,0.529754,0.470246
15,giving,0.521121,0.478879,0.481482,0.518518
16,handing,0.586320,0.413680,0.543322,0.456678
17,passing,0.509848,0.490152,0.545650,0.454350
18,serving,0.464383,0.535617,0.514106,0.485894

In [315]:
print("P(subj_reference |subj=female)", compute_average(c1_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c1_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.5580353109133348
P(obj_reference |subj=female) 0.4419646890539872

In [316]:
print("P(subj_reference |subj=male)", compute_average(c1_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c1_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.5651519075036049
P(obj_reference |subj=male) 0.4348480956988376

## Connective: "and, as a result"

In [317]:
c2_average_subj_female_subj_pron = {}
c2_average_subj_female_obj_pron = {}
c2_average_subj_male_subj_pron = {}
c2_average_subj_male_obj_pron = {}

### verb: "chucking"

In [318]:
transofposs_imperfective_connective2_1 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/1.csv")
transofposs_imperfective_connective2_1.head()

                                            stimulus        he       she
0  Miss Smith was chucking a wrench to Mr. Smith ...  0.777231  0.222769
1  The woman was chucking a wrench to the man and...  0.658173  0.341827
2  Mary was chucking a wrench to John and, as a r...  0.632273  0.367727
3  Alice was chucking a wrench to Bob and, as a r...  0.450082  0.549918
4  The actress was chucking a wrench to the actor...  0.659739  0.340261

In [319]:
# female subject
transofposs_imperfective_connective2_1f = transofposs_imperfective_connective2_1[0:12]
transofposs_imperfective_connective2_1f = transofposs_imperfective_connective2_1f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_1m = transofposs_imperfective_connective2_1[12:24]

#### female subject

In [320]:
transofposs_imperfective_connective2_1f

                                             stimulus       she        he
0   Miss Smith was chucking a wrench to Mr. Smith ...  0.222769  0.777231
1   The woman was chucking a wrench to the man and...  0.341827  0.658173
2   Mary was chucking a wrench to John and, as a r...  0.367727  0.632273
3   Alice was chucking a wrench to Bob and, as a r...  0.549918  0.450082
4   The actress was chucking a wrench to the actor...  0.340261  0.659739
5   The girl was chucking a wrench to the boy and,...  0.381246  0.618754
6   Mrs. Taylor was chucking a wrench to Mr. Willi...  0.293566  0.706434
7   Emma was chucking a wrench to David and, as a ...  0.379755  0.620245
8   The princess was chucking a wrench to the prin...  0.388966  0.611034
9   Sarah was chucking a wrench to Robert and, as ...  0.359987  0.640013
10  Mrs. Williams was chucking a wrench to  Mr. Ta...  0.326397  0.673603
11  Emily was chucking a wrench to Paul and, as a ...  0.449331  0.550669

In [321]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_1f,'he'))

P('subj-pron'|subj=female) =  0.3668125085532665
P('non-subj-pron'|subj=female) =  0.6331874951720238

In [322]:
#c2_average_subj_female_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1f,'she')
#c2_average_subj_female_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1f,'he')

#### male subject

In [323]:
transofposs_imperfective_connective2_1m

                                             stimulus        he       she
12  Mr. Smith was chucking a wrench to Miss Smith ...  0.357940  0.642060
13  The man was chucking a wrench to the woman and...  0.277595  0.722405
14  John was chucking a wrench to Mary and, as a r...  0.372138  0.627861
15  Bob was chucking a wrench to Alice and, as a r...  0.324987  0.675013
16  The actor was chucking a wrench to the actress...  0.259382  0.740618
17  The boy was chucking a wrench to the girl and,...  0.301237  0.698763
18  Mr. William was chucking a wrench to  Mrs. Tay...  0.384980  0.615020
19  David was chucking a wrench to Emma and, as a ...  0.336234  0.663766
20  The prince was chucking a wrench to the prince...  0.260315  0.739685
21  Robert was chucking a wrench to Sarah and, as ...  0.368329  0.631671
22  Mr. Taylor was chucking a wrench to Mrs. Willi...  0.330106  0.669894
23  Paul was chucking a wrench to Emily and, as a ...  0.310647  0.689354

In [324]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_1m,'she'))

P('subj-pron'|subj=male) =  0.32365738848845166
P('non-subj-pron'|subj=male) =  0.676342616478602

In [325]:
#c2_average_subj_male_subj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1m,'he')
#c2_average_subj_male_obj_pron['chucking'] = compute_average(transofposs_imperfective_connective2_1m,'she')

### verb: "flinging"

In [326]:
transofposs_imperfective_connective2_2 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/2.csv")
transofposs_imperfective_connective2_2.head()

                                            stimulus        he       she
0  Miss Smith was flinging a frisbee to Mr. Smith...  0.663580  0.336420
1  The woman was flinging a frisbee to the man an...  0.553490  0.446510
2  Mary was flinging a frisbee to John and, as a ...  0.545900  0.454100
3  Alice was flinging a frisbee to Bob and, as a ...  0.298835  0.701165
4  The actress was flinging a frisbee to the acto...  0.535582  0.464418

In [327]:
# female subject
transofposs_imperfective_connective2_2f = transofposs_imperfective_connective2_2[0:12]
transofposs_imperfective_connective2_2f = transofposs_imperfective_connective2_2f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_2m = transofposs_imperfective_connective2_2[12:24]

#### female subject

In [328]:
transofposs_imperfective_connective2_2f

                                             stimulus       she        he
0   Miss Smith was flinging a frisbee to Mr. Smith...  0.336420  0.663580
1   The woman was flinging a frisbee to the man an...  0.446510  0.553490
2   Mary was flinging a frisbee to John and, as a ...  0.454100  0.545900
3   Alice was flinging a frisbee to Bob and, as a ...  0.701165  0.298835
4   The actress was flinging a frisbee to the acto...  0.464418  0.535582
5   The girl was flinging a frisbee to the boy and...  0.466177  0.533823
6   Mrs. Taylor was flinging a frisbee to Mr. Will...  0.374546  0.625454
7   Emma was flinging a frisbee to David and, as a...  0.474456  0.525544
8   The princess was flinging a frisbee to the pri...  0.604717  0.395283
9   Sarah was flinging a frisbee to Robert and, as...  0.448972  0.551028
10  Mrs. Williams was flinging a frisbee to  Mr. T...  0.406261  0.593739
11  Emily was flinging a frisbee to Paul and, as a...  0.530431  0.469569

In [329]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_2f,'he'))

P('subj-pron'|subj=female) =  0.47568120062351227
P('non-subj-pron'|subj=female) =  0.5243187844753265

In [330]:
c2_average_subj_female_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2f,'she')
c2_average_subj_female_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2f,'he')

#### male subject

In [331]:
transofposs_imperfective_connective2_2m

                                             stimulus        he       she
12  Mr. Smith was flinging a frisbee to Miss Smith...  0.489562  0.510438
13  The man was flinging a frisbee to the woman an...  0.435542  0.564458
14  John was flinging a frisbee to Mary and, as a ...  0.475190  0.524810
15  Bob was flinging a frisbee to Alice and, as a ...  0.427734  0.572266
16  The actor was flinging a frisbee to the actres...  0.368219  0.631781
17  The boy was flinging a frisbee to the girl and...  0.418597  0.581403
18  Mr. William was flinging a frisbee to  Mrs. Ta...  0.584795  0.415205
19  David was flinging a frisbee to Emma and, as a...  0.436860  0.563140
20  The prince was flinging a frisbee to the princ...  0.418567  0.581433
21  Robert was flinging a frisbee to Sarah and, as...  0.475542  0.524458
22  Mr. Taylor was flinging a frisbee to Mrs. Will...  0.475442  0.524558
23  Paul was flinging a frisbee to Emily and, as a...  0.416118  0.583882

In [332]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_2m,'she'))

P('subj-pron'|subj=male) =  0.45184727261463803
P('non-subj-pron'|subj=male) =  0.5481527398029963

In [333]:
c2_average_subj_male_subj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2m,'he')
c2_average_subj_male_obj_pron['flinging'] = compute_average(transofposs_imperfective_connective2_2m,'she')

### verb: "kicking"

In [334]:
transofposs_imperfective_connective2_3 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/3.csv")
transofposs_imperfective_connective2_3.head()

                                            stimulus        he       she
0  Miss Smith was kicking a soccer ball to Mr. Sm...  0.604386  0.395614
1  The woman was kicking a soccer ball to the man...  0.554585  0.445415
2  Mary was kicking a soccer ball to John and, as...  0.426936  0.573064
3  Alice was kicking a soccer ball to Bob and, as...  0.237392  0.762608
4  The actress was kicking a soccer ball to the a...  0.391809  0.608191

In [335]:
# female subject
transofposs_imperfective_connective2_3f = transofposs_imperfective_connective2_3[0:12]
transofposs_imperfective_connective2_3f = transofposs_imperfective_connective2_3f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_3m = transofposs_imperfective_connective2_3[12:24]

#### female subject

In [336]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_3f,'he'))

P('subj-pron'|subj=female) =  0.5591924165685972
P('non-subj-pron'|subj=female) =  0.4408075821896394

In [337]:
c2_average_subj_female_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3f,'she')
c2_average_subj_female_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3f,'he')

#### male subject

In [338]:
transofposs_imperfective_connective2_3m

                                             stimulus        he       she
12  Mr. Smith was kicking a soccer ball to Miss Sm...  0.490626  0.509374
13  The man was kicking a soccer ball to the woman...  0.378939  0.621060
14  John was kicking a soccer ball to Mary and, as...  0.565212  0.434788
15  Bob was kicking a soccer ball to Alice and, as...  0.516600  0.483400
16  The actor was kicking a soccer ball to the act...  0.489546  0.510454
17  The boy was kicking a soccer ball to the girl ...  0.435989  0.564011
18  Mr. William was kicking a soccer ball to  Mrs....  0.615490  0.384510
19  David was kicking a soccer ball to Emma and, a...  0.465403  0.534597
20  The prince was kicking a soccer ball to the pr...  0.571374  0.428626
21  Robert was kicking a soccer ball to Sarah and,...  0.529193  0.470807
22  Mr. Taylor was kicking a soccer ball to Mrs. W...  0.449103  0.550897
23  Paul was kicking a soccer ball to Emily and, a...  0.483559  0.516441

In [339]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_3m,'she'))

P('subj-pron'|subj=male) =  0.4992528185248375
P('non-subj-pron'|subj=male) =  0.5007471765081087

In [340]:
c2_average_subj_male_subj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3m,'he')
c2_average_subj_male_obj_pron['kicking'] = compute_average(transofposs_imperfective_connective2_3m,'she')

### verb: "lobbing"

In [341]:
transofposs_imperfective_connective2_4 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/4.csv")
transofposs_imperfective_connective2_4.head()

                                            stimulus        he       she
0  Miss Smith was lobbing a football to Mr. Smith...  0.710965  0.289035
1  The woman was lobbing a football to the man an...  0.587504  0.412496
2  Mary was lobbing a football to John and, as a ...  0.588114  0.411886
3  Alice was lobbing a football to Bob and, as a ...  0.363581  0.636419
4  The actress was lobbing a football to the acto...  0.542832  0.457168

In [342]:
# female subject
transofposs_imperfective_connective2_4f = transofposs_imperfective_connective2_4[0:12]
transofposs_imperfective_connective2_4f = transofposs_imperfective_connective2_4f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_4m = transofposs_imperfective_connective2_4[12:24]

#### female subject

In [343]:
transofposs_imperfective_connective2_4f

                                             stimulus       she        he
0   Miss Smith was lobbing a football to Mr. Smith...  0.289035  0.710965
1   The woman was lobbing a football to the man an...  0.412496  0.587504
2   Mary was lobbing a football to John and, as a ...  0.411886  0.588114
3   Alice was lobbing a football to Bob and, as a ...  0.636419  0.363581
4   The actress was lobbing a football to the acto...  0.457168  0.542832
5   The girl was lobbing a football to the boy and...  0.401499  0.598501
6   Mrs. Taylor was lobbing a football to Mr. Will...  0.320907  0.679093
7   Emma was lobbing a football to David and, as a...  0.431392  0.568608
8   The princess was lobbing a football to the pri...  0.443695  0.556305
9   Sarah was lobbing a football to Robert and, as...  0.411468  0.588532
10  Mrs. Williams was lobbing a football to  Mr. T...  0.289124  0.710876
11  Emily was lobbing a football to Paul and, as a...  0.445520  0.554480

In [344]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_4f,'he'))

P('subj-pron'|subj=female) =  0.41255075732866925
P('non-subj-pron'|subj=female) =  0.5874492501219114

In [345]:
c2_average_subj_female_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4f,'she')
c2_average_subj_female_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4f,'he')

#### male subject

In [346]:
transofposs_imperfective_connective2_4m

                                             stimulus        he       she
12  Mr. Smith was lobbing a football to Miss Smith...  0.335980  0.664020
13  The man was lobbing a football to the woman an...  0.321461  0.678539
14  John was lobbing a football to Mary and, as a ...  0.357241  0.642759
15  Bob was lobbing a football to Alice and, as a ...  0.267578  0.732422
16  The actor was lobbing a football to the actres...  0.276276  0.723724
17  The boy was lobbing a football to the girl and...  0.332152  0.667848
18  Mr. William was lobbing a football to  Mrs. Ta...  0.415088  0.584912
19  David was lobbing a football to Emma and, as a...  0.302098  0.697902
20  The prince was lobbing a football to the princ...  0.279144  0.720856
21  Robert was lobbing a football to Sarah and, as...  0.350982  0.649018
22  Mr. Taylor was lobbing a football to Mrs. Will...  0.323072  0.676928
23  Paul was lobbing a football to Emily and, as a...  0.300622  0.699378

In [347]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_4m,'she'))

P('subj-pron'|subj=male) =  0.3218078960975011
P('non-subj-pron'|subj=male) =  0.6781920989354452

In [348]:
c2_average_subj_male_subj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4m,'he')
c2_average_subj_male_obj_pron['lobbing'] = compute_average(transofposs_imperfective_connective2_4m,'she')

### verb: "rolling"

In [349]:
transofposs_imperfective_connective2_5 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/5.csv")
transofposs_imperfective_connective2_5.head()

                                            stimulus        he       she
0  Miss Smith was rolling a toy truck to Mr. Smit...  0.501489  0.498511
1  The woman was rolling a toy truck to the man a...  0.396698  0.603303
2  Mary was rolling a toy truck to John and, as a...  0.378778  0.621222
3  Alice was rolling a toy truck to Bob and, as a...  0.192398  0.807602
4  The actress was rolling a toy truck to the act...  0.332554  0.667446

In [350]:
# female subject
transofposs_imperfective_connective2_5f = transofposs_imperfective_connective2_5[0:12]
transofposs_imperfective_connective2_5f = transofposs_imperfective_connective2_5[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_5m = transofposs_imperfective_connective2_5[12:24]

#### female subject

In [351]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_5f,'he'))

P('subj-pron'|subj=female) =  0.5471937730908394
P('non-subj-pron'|subj=female) =  0.45280624615649384

In [352]:
c2_average_subj_female_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5f,'she')
c2_average_subj_female_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5f,'he')

#### male subject

In [353]:
transofposs_imperfective_connective2_5m

                                             stimulus        he       she
12  Mr. Smith was rolling a toy truck to Miss Smit...  0.539068  0.460932
13  The man was rolling a toy truck to the woman a...  0.448465  0.551535
14  John was rolling a toy truck to Mary and, as a...  0.583097  0.416903
15  Bob was rolling a toy truck to Alice and, as a...  0.507975  0.492025
16  The actor was rolling a toy truck to the actre...  0.508006  0.491994
17  The boy was rolling a toy truck to the girl an...  0.535362  0.464638
18  Mr. William was rolling a toy truck to  Mrs. T...  0.639924  0.360076
19  David was rolling a toy truck to Emma and, as ...  0.510627  0.489373
20  The prince was rolling a toy truck to the prin...  0.565059  0.434941
21  Robert was rolling a toy truck to Sarah and, a...  0.558586  0.441414
22  Mr. Taylor was rolling a toy truck to Mrs. Wil...  0.490107  0.509893
23  Paul was rolling a toy truck to Emily and, as ...  0.486801  0.513199

In [354]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_5m,'she'))

P('subj-pron'|subj=male) =  0.5310897578795751
P('non-subj-pron'|subj=male) =  0.4689102644721667

In [355]:
c2_average_subj_male_subj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5m,'he')
c2_average_subj_male_obj_pron['rolling'] = compute_average(transofposs_imperfective_connective2_5m,'she')

### verb: "throwing"

In [356]:
transofposs_imperfective_connective2_6 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/6.csv")
transofposs_imperfective_connective2_6.head()

                                            stimulus        he       she
0  Miss Smith was throwing a hat to Mr. Smith and...  0.641889  0.358111
1  The woman was throwing a hat to the man and, a...  0.595685  0.404315
2  Mary was throwing a hat to John and, as a result,  0.532820  0.467180
3  Alice was throwing a hat to Bob and, as a result,  0.315956  0.684044
4  The actress was throwing a hat to the actor an...  0.483199  0.516801

In [357]:
# female subject
transofposs_imperfective_connective2_6f = transofposs_imperfective_connective2_6[0:12]
transofposs_imperfective_connective2_6f = transofposs_imperfective_connective2_6[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_6m = transofposs_imperfective_connective2_6[12:24]

#### female subject

In [358]:
transofposs_imperfective_connective2_6f

                                             stimulus       she        he
0   Miss Smith was throwing a hat to Mr. Smith and...  0.358111  0.641889
1   The woman was throwing a hat to the man and, a...  0.404315  0.595685
2   Mary was throwing a hat to John and, as a result,  0.467180  0.532820
3   Alice was throwing a hat to Bob and, as a result,  0.684044  0.315956
4   The actress was throwing a hat to the actor an...  0.516801  0.483199
5   The girl was throwing a hat to the boy and, as...  0.408694  0.591306
6   Mrs. Taylor was throwing a hat to Mr. Williams...  0.347929  0.652071
7   Emma was throwing a hat to David and, as a res...  0.458252  0.541748
8   The princess was throwing a hat to the prince ...  0.514710  0.485290
9   Sarah was throwing a hat to Robert and, as a r...  0.462591  0.537409
10  Mrs. Williams was throwing a hat to  Mr. Taylo...  0.389791  0.610209
11  Emily was throwing a hat to Paul and, as a res...  0.551920  0.448080
12  Mr. Smith was throwing a hat to Miss Smith and...  0.486095  0.513905
13  The man was throwing a hat to the woman and, a...  0.610283  0.389717
14  John was throwing a hat to Mary and, as a result,  0.413803  0.586197
15  Bob was throwing a hat to Alice and, as a result,  0.549487  0.450513
16  The actor was throwing a hat to the actress an...  0.550106  0.449894
17  The boy was throwing a hat to the girl and, as...  0.626217  0.373783
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.428896  0.571104
19  David was throwing a hat to Emma and, as a res...  0.520241  0.479759
20  The prince was throwing a hat to the princess ...  0.588661  0.411339
21  Robert was throwing a hat to Sarah and, as a r...  0.495279  0.504721
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.506016  0.493984
23  Paul was throwing a hat to Emily and, as a res...  0.485197  0.514803

In [359]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_6f,'he'))

P('subj-pron'|subj=female) =  0.4926924780011177
P('non-subj-pron'|subj=female) =  0.5073075306912264

In [360]:
c2_average_subj_female_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6f,'she')
c2_average_subj_female_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6f,'he')

#### male subject

In [361]:
transofposs_imperfective_connective2_6m

                                             stimulus        he       she
12  Mr. Smith was throwing a hat to Miss Smith and...  0.513905  0.486095
13  The man was throwing a hat to the woman and, a...  0.389717  0.610283
14  John was throwing a hat to Mary and, as a result,  0.586197  0.413803
15  Bob was throwing a hat to Alice and, as a result,  0.450513  0.549487
16  The actor was throwing a hat to the actress an...  0.449894  0.550106
17  The boy was throwing a hat to the girl and, as...  0.373783  0.626217
18  Mr. William was throwing a hat to  Mrs. Taylor...  0.571104  0.428896
19  David was throwing a hat to Emma and, as a res...  0.479759  0.520241
20  The prince was throwing a hat to the princess ...  0.411339  0.588661
21  Robert was throwing a hat to Sarah and, as a r...  0.504721  0.495279
22  Mr. Taylor was throwing a hat to Mrs. Williams...  0.493984  0.506016
23  Paul was throwing a hat to Emily and, as a res...  0.514803  0.485197

In [362]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_6m,'she'))

P('subj-pron'|subj=male) =  0.4783099368214607
P('non-subj-pron'|subj=male) =  0.5216900780797005

In [363]:
c2_average_subj_male_subj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6m,'he')
c2_average_subj_male_obj_pron['throwing'] = compute_average(transofposs_imperfective_connective2_6m,'she')

### verb: "tossing"

In [364]:
transofposs_imperfective_connective2_7 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/7.csv")
transofposs_imperfective_connective2_7.head()

                                            stimulus        he       she
0  Miss Smith was tossing a dish towel to Mr. Smi...  0.595363  0.404637
1  The woman was tossing a dish towel to the man ...  0.541180  0.458820
2  Mary was tossing a dish towel to John and, as ...  0.500243  0.499757
3  Alice was tossing a dish towel to Bob and, as ...  0.272237  0.727763
4  The actress was tossing a dish towel to the ac...  0.472708  0.527292

In [365]:
# female subject
transofposs_imperfective_connective2_7f = transofposs_imperfective_connective2_7[0:12]
transofposs_imperfective_connective2_7f = transofposs_imperfective_connective2_7f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_7m = transofposs_imperfective_connective2_7[12:24]

#### female subject

In [366]:
transofposs_imperfective_connective2_7f

                                             stimulus       she        he
0   Miss Smith was tossing a dish towel to Mr. Smi...  0.404637  0.595363
1   The woman was tossing a dish towel to the man ...  0.458820  0.541180
2   Mary was tossing a dish towel to John and, as ...  0.499757  0.500243
3   Alice was tossing a dish towel to Bob and, as ...  0.727763  0.272237
4   The actress was tossing a dish towel to the ac...  0.527292  0.472708
5   The girl was tossing a dish towel to the boy a...  0.514752  0.485248
6   Mrs. Taylor was tossing a dish towel to Mr. Wi...  0.434231  0.565769
7   Emma was tossing a dish towel to David and, as...  0.496616  0.503384
8   The princess was tossing a dish towel to the p...  0.635752  0.364248
9   Sarah was tossing a dish towel to Robert and, ...  0.470533  0.529467
10  Mrs. Williams was tossing a dish towel to  Mr....  0.481113  0.518887
11  Emily was tossing a dish towel to Paul and, as...  0.585703  0.414297

In [367]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_7f,'he'))

P('subj-pron'|subj=female) =  0.5197474037607511
P('non-subj-pron'|subj=female) =  0.48025258878866833

In [368]:
c2_average_subj_female_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7f,'she')
c2_average_subj_female_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7f,'he')

#### male subject

In [369]:
transofposs_imperfective_connective2_7m

                                             stimulus        he       she
12  Mr. Smith was tossing a dish towel to Miss Smi...  0.453967  0.546033
13  The man was tossing a dish towel to the woman ...  0.373331  0.626669
14  John was tossing a dish towel to Mary and, as ...  0.481008  0.518992
15  Bob was tossing a dish towel to Alice and, as ...  0.369707  0.630293
16  The actor was tossing a dish towel to the actr...  0.378790  0.621210
17  The boy was tossing a dish towel to the girl a...  0.429075  0.570925
18  Mr. William was tossing a dish towel to  Mrs. ...  0.541072  0.458928
19  David was tossing a dish towel to Emma and, as...  0.414013  0.585987
20  The prince was tossing a dish towel to the pri...  0.523859  0.476141
21  Robert was tossing a dish towel to Sarah and, ...  0.481053  0.518947
22  Mr. Taylor was tossing a dish towel to Mrs. Wi...  0.388552  0.611448
23  Paul was tossing a dish towel to Emily and, as...  0.405504  0.594495

In [370]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_7m,'she'))

P('subj-pron'|subj=male) =  0.43666088332732517
P('non-subj-pron'|subj=male) =  0.5633391092220942

In [371]:
c2_average_subj_male_subj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7m,'he')
c2_average_subj_male_obj_pron['tossing'] = compute_average(transofposs_imperfective_connective2_7m,'she')

### verb: "bringing"

In [372]:
transofposs_imperfective_connective2_8 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/8.csv")
transofposs_imperfective_connective2_8.head()

                                            stimulus        he       she
0  Miss Smith was bringing a glass of water to Mr...  0.732899  0.267101
1  The woman was bringing a glass of water to the...  0.536540  0.463460
2  Mary was bringing a glass of water to John and...  0.610336  0.389664
3  Alice was bringing a glass of water to Bob and...  0.374272  0.625728
4  The actress was bringing a glass of water to t...  0.675712  0.324288

In [373]:
# female subject
transofposs_imperfective_connective2_8f = transofposs_imperfective_connective2_8[0:12]
transofposs_imperfective_connective2_8f = transofposs_imperfective_connective2_8f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_8m = transofposs_imperfective_connective2_8[12:24]

#### female subject

In [374]:
transofposs_imperfective_connective2_8f

                                             stimulus       she        he
0   Miss Smith was bringing a glass of water to Mr...  0.267101  0.732899
1   The woman was bringing a glass of water to the...  0.463460  0.536540
2   Mary was bringing a glass of water to John and...  0.389664  0.610336
3   Alice was bringing a glass of water to Bob and...  0.625728  0.374272
4   The actress was bringing a glass of water to t...  0.324288  0.675712
5   The girl was bringing a glass of water to the ...  0.387616  0.612384
6   Mrs. Taylor was bringing a glass of water to M...  0.321763  0.678237
7   Emma was bringing a glass of water to David an...  0.401596  0.598404
8   The princess was bringing a glass of water to ...  0.515983  0.484017
9   Sarah was bringing a glass of water to Robert ...  0.401150  0.598850
10  Mrs. Williams was bringing a glass of water to...  0.354678  0.645322
11  Emily was bringing a glass of water to Paul an...  0.469662  0.530338

In [375]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_8f,'he'))

P('subj-pron'|subj=female) =  0.4102240080634753
P('non-subj-pron'|subj=female) =  0.5897760068376859

In [376]:
c2_average_subj_female_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8f,'she')
c2_average_subj_female_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8f,'he')

#### male subject

In [377]:
transofposs_imperfective_connective2_8m

                                             stimulus        he       she
12  Mr. Smith was bringing a glass of water to Mis...  0.437924  0.562076
13  The man was bringing a glass of water to the w...  0.387967  0.612033
14  John was bringing a glass of water to Mary and...  0.450059  0.549941
15  Bob was bringing a glass of water to Alice and...  0.282818  0.717182
16  The actor was bringing a glass of water to the...  0.261380  0.738620
17  The boy was bringing a glass of water to the g...  0.408183  0.591817
18  Mr. William was bringing a glass of water to  ...  0.491356  0.508643
19  David was bringing a glass of water to Emma an...  0.351827  0.648173
20  The prince was bringing a glass of water to th...  0.439616  0.560384
21  Robert was bringing a glass of water to Sarah ...  0.433076  0.566924
22  Mr. Taylor was bringing a glass of water to Mr...  0.412831  0.587169
23  Paul was bringing a glass of water to Emily an...  0.370747  0.629253

In [378]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_8m,'she'))

P('subj-pron'|subj=male) =  0.3939820279677709
P('non-subj-pron'|subj=male) =  0.6060179769992828

In [379]:
c2_average_subj_male_subj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8m,'he')
c2_average_subj_male_obj_pron['bringing'] = compute_average(transofposs_imperfective_connective2_8m,'she')

### verb: "forwarding"

In [380]:
transofposs_imperfective_connective2_9 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/9.csv")
transofposs_imperfective_connective2_9.head()

                                            stimulus        he       she
0  Miss Smith was forwarding a gossipy email to M...  0.813865  0.186135
1  The woman was forwarding a gossipy email to th...  0.719081  0.280919
2  Mary was forwarding a gossipy email to John an...  0.683381  0.316619
3  Alice was forwarding a gossipy email to Bob an...  0.501511  0.498489
4  The actress was forwarding a gossipy email to ...  0.655705  0.344295

In [381]:
# female subject
transofposs_imperfective_connective2_9f = transofposs_imperfective_connective2_9[0:12]
transofposs_imperfective_connective2_9f = transofposs_imperfective_connective2_9f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_9m = transofposs_imperfective_connective2_9[12:24]

#### female subject

In [382]:
transofposs_imperfective_connective2_9f

                                             stimulus       she        he
0   Miss Smith was forwarding a gossipy email to M...  0.186135  0.813865
1   The woman was forwarding a gossipy email to th...  0.280919  0.719081
2   Mary was forwarding a gossipy email to John an...  0.316619  0.683381
3   Alice was forwarding a gossipy email to Bob an...  0.498489  0.501511
4   The actress was forwarding a gossipy email to ...  0.344295  0.655705
5   The girl was forwarding a gossipy email to the...  0.233942  0.766058
6   Mrs. Taylor was forwarding a gossipy email to ...  0.259805  0.740195
7   Emma was forwarding a gossipy email to David a...  0.256447  0.743553
8   The princess was forwarding a gossipy email to...  0.318269  0.681731
9   Sarah was forwarding a gossipy email to Robert...  0.347519  0.652481
10  Mrs. Williams was forwarding a gossipy email t...  0.316707  0.683293
11  Emily was forwarding a gossipy email to Paul a...  0.354872  0.645128

In [383]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_9f,'he'))

P('subj-pron'|subj=female) =  0.3095014976958434
P('non-subj-pron'|subj=female) =  0.6904985159635544

In [384]:
c2_average_subj_female_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9f,'she')
c2_average_subj_female_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9f,'he')

#### male subject

In [385]:
transofposs_imperfective_connective2_9m

                                             stimulus        he       she
12  Mr. Smith was forwarding a gossipy email to Mi...  0.252976  0.747024
13  The man was forwarding a gossipy email to the ...  0.278824  0.721176
14  John was forwarding a gossipy email to Mary an...  0.359890  0.640110
15  Bob was forwarding a gossipy email to Alice an...  0.198678  0.801322
16  The actor was forwarding a gossipy email to th...  0.210767  0.789233
17  The boy was forwarding a gossipy email to the ...  0.283717  0.716283
18  Mr. William was forwarding a gossipy email to ...  0.279524  0.720476
19  David was forwarding a gossipy email to Emma a...  0.281281  0.718719
20  The prince was forwarding a gossipy email to t...  0.202888  0.797112
21  Robert was forwarding a gossipy email to Sarah...  0.328674  0.671326
22  Mr. Taylor was forwarding a gossipy email to M...  0.202100  0.797900
23  Paul was forwarding a gossipy email to Emily a...  0.338996  0.661004

In [386]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_9m,'she'))

P('subj-pron'|subj=male) =  0.2681930524607499
P('non-subj-pron'|subj=male) =  0.7318069338798523

In [387]:
c2_average_subj_male_subj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9m,'he')
c2_average_subj_male_obj_pron['forwarding'] = compute_average(transofposs_imperfective_connective2_9m,'she')

### verb: "mailing"

In [388]:
transofposs_imperfective_connective2_10 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/10.csv")
transofposs_imperfective_connective2_10.head()

                                            stimulus        he       she
0  Miss Smith was mailing a letter to Mr. Smith a...  0.736496  0.263504
1  The woman was mailing a letter to the man and,...  0.631402  0.368598
2  Mary was mailing a letter to John and, as a re...  0.546673  0.453327
3  Alice was mailing a letter to Bob and, as a re...  0.345341  0.654659
4  The actress was mailing a letter to the actor ...  0.545199  0.454801

In [389]:
# female subject
transofposs_imperfective_connective2_10f = transofposs_imperfective_connective2_10[0:12]
transofposs_imperfective_connective2_10f = transofposs_imperfective_connective2_10f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_10m = transofposs_imperfective_connective2_10[12:24]

#### female subject

In [390]:
transofposs_imperfective_connective2_10f

                                             stimulus       she        he
0   Miss Smith was mailing a letter to Mr. Smith a...  0.263504  0.736496
1   The woman was mailing a letter to the man and,...  0.368598  0.631402
2   Mary was mailing a letter to John and, as a re...  0.453327  0.546673
3   Alice was mailing a letter to Bob and, as a re...  0.654659  0.345341
4   The actress was mailing a letter to the actor ...  0.454801  0.545199
5   The girl was mailing a letter to the boy and, ...  0.375767  0.624233
6   Mrs. Taylor was mailing a letter to Mr. Willia...  0.324464  0.675536
7   Emma was mailing a letter to David and, as a r...  0.398108  0.601892
8   The princess was mailing a letter to the princ...  0.528766  0.471234
9   Sarah was mailing a letter to Robert and, as a...  0.423700  0.576300
10  Mrs. Williams was mailing a letter to Mr. Tayl...  0.377789  0.622211
11  Emily was mailing a letter to Paul and, as a r...  0.464719  0.535281

In [391]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_10f,'he'))

P('subj-pron'|subj=female) =  0.4240168457229932
P('non-subj-pron'|subj=female) =  0.5759831567605337

In [392]:
c2_average_subj_female_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10f,'she')
c2_average_subj_female_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10f,'he')

#### male subject

In [393]:
transofposs_imperfective_connective2_10m

                                             stimulus        he       she
12  Mr. Smith was mailing a letter to Miss Smith a...  0.383372  0.616628
13  The man was mailing a letter to the woman and,...  0.419339  0.580661
14  John was mailing a letter to Mary and, as a re...  0.501036  0.498964
15  Bob was mailing a letter to Alice and, as a re...  0.388870  0.611130
16  The actor was mailing a letter to the actress ...  0.344343  0.655657
17  The boy was mailing a letter to the girl and, ...  0.458851  0.541149
18  Mr. William was mailing a letter to  Mrs. Tayl...  0.473338  0.526661
19  David was mailing a letter to Emma and, as a r...  0.401946  0.598054
20  The prince was mailing a letter to the princes...  0.357514  0.642486
21  Robert was mailing a letter to Sarah and, as a...  0.438664  0.561336
22  Mr. Taylor was mailing a letter to Mrs. Willia...  0.348431  0.651569
23  Paul was mailing a letter to Emily and, as a r...  0.445131  0.554869

In [394]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_10m,'she'))

P('subj-pron'|subj=male) =  0.4134030689795812
P('non-subj-pron'|subj=male) =  0.5865969260533651

In [395]:
c2_average_subj_male_subj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10m,'he')
c2_average_subj_male_obj_pron['mailing'] = compute_average(transofposs_imperfective_connective2_10m,'she')

### verb: "shipping"

In [396]:
transofposs_imperfective_connective2_11 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/11.csv")
transofposs_imperfective_connective2_11.head()

                                            stimulus        he       she
0  Miss Smith was shipping a package to Mr. Smith...  0.594969  0.405031
1  The woman was shipping a package to the man an...  0.422170  0.577830
2  Mary was shipping a package to John and, as a ...  0.401697  0.598303
3  Alice was shipping a package to Bob and, as a ...  0.212959  0.787041
4  The actress was shipping a package to the acto...  0.391332  0.608668

In [397]:
# female subject
transofposs_imperfective_connective2_11f = transofposs_imperfective_connective2_11[0:12]
transofposs_imperfective_connective2_11f = transofposs_imperfective_connective2_11f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_11m = transofposs_imperfective_connective2_11[12:24]

#### female subject

In [398]:
transofposs_imperfective_connective2_11f

                                             stimulus       she        he
0   Miss Smith was shipping a package to Mr. Smith...  0.405031  0.594969
1   The woman was shipping a package to the man an...  0.577830  0.422170
2   Mary was shipping a package to John and, as a ...  0.598303  0.401697
3   Alice was shipping a package to Bob and, as a ...  0.787041  0.212959
4   The actress was shipping a package to the acto...  0.608668  0.391332
5   The girl was shipping a package to the boy and...  0.611326  0.388674
6   Mrs. Taylor was shipping a package to Mr. Will...  0.440116  0.559884
7   Emma was shipping a package to David and, as a...  0.540760  0.459240
8   The princess was shipping a package to the pri...  0.674341  0.325659
9   Sarah was shipping a package to Robert and, as...  0.515305  0.484695
10  Mrs. Williams was shipping a package to Mr. Ta...  0.490645  0.509355
11  Emily was shipping a package to Paul and, as a...  0.622347  0.377653

In [399]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_11f,'he'))

P('subj-pron'|subj=female) =  0.5726426442464193
P('non-subj-pron'|subj=female) =  0.42735736444592476

In [400]:
c2_average_subj_female_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11f,'she')
c2_average_subj_female_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11f,'he')

#### male subject

In [401]:
transofposs_imperfective_connective2_11m

                                             stimulus        he       she
12  Mr. Smith was shipping a package to Miss Smith...  0.511065  0.488935
13  The man was shipping a package to the woman an...  0.514206  0.485794
14  John was shipping a package to Mary and, as a ...  0.567026  0.432974
15  Bob was shipping a package to Alice and, as a ...  0.462712  0.537288
16  The actor was shipping a package to the actres...  0.459126  0.540874
17  The boy was shipping a package to the girl and...  0.533826  0.466174
18  Mr. William was shipping a package to  Mrs. Ta...  0.599260  0.400740
19  David was shipping a package to Emma and, as a...  0.428320  0.571680
20  The prince was shipping a package to the princ...  0.566552  0.433448
21  Robert was shipping a package to Sarah and, as...  0.508423  0.491577
22  Mr. Taylor was shipping a package to Mrs. Will...  0.495482  0.504518
23  Paul was shipping a package to Emily and, as a...  0.465600  0.534401

In [402]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_11m,'she'))

P('subj-pron'|subj=male) =  0.5092996060848236
P('non-subj-pron'|subj=male) =  0.4907003814975421

In [403]:
c2_average_subj_male_subj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11m,'he')
c2_average_subj_male_obj_pron['shipping'] = compute_average(transofposs_imperfective_connective2_11m,'she')

### verb: "transmitting"

In [404]:
transofposs_imperfective_connective2_12 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/12.csv")
transofposs_imperfective_connective2_12.head()

                                            stimulus        he       she
0  Miss Smith was transmitting a message to Mr. S...  0.721396  0.278604
1  The woman was transmitting a message to the ma...  0.613468  0.386532
2  Mary was transmitting a message to John and, a...  0.588913  0.411087
3  Alice was transmitting a message to Bob and, a...  0.356417  0.643583
4  The actress was transmitting a message to the ...  0.430591  0.569409

In [405]:
# female subject
transofposs_imperfective_connective2_12f = transofposs_imperfective_connective2_12[0:12]
transofposs_imperfective_connective2_12f = transofposs_imperfective_connective2_12f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_12m = transofposs_imperfective_connective2_12[12:24]

#### female subject

In [406]:
transofposs_imperfective_connective2_12f

                                             stimulus       she        he
0   Miss Smith was transmitting a message to Mr. S...  0.278604  0.721396
1   The woman was transmitting a message to the ma...  0.386532  0.613468
2   Mary was transmitting a message to John and, a...  0.411087  0.588913
3   Alice was transmitting a message to Bob and, a...  0.643583  0.356417
4   The actress was transmitting a message to the ...  0.569409  0.430591
5   The girl was transmitting a message to the boy...  0.344608  0.655392
6   Mrs. Taylor was transmitting a message to Mr. ...  0.299579  0.700421
7   Emma was transmitting a message to David and, ...  0.358623  0.641377
8   The princess was transmitting a message to the...  0.565378  0.434622
9   Sarah was transmitting a message to Robert and...  0.345224  0.654776
10  Mrs. Williams was transmitting a message to Mr...  0.361492  0.638508
11  Emily was transmitting a message to Paul and, ...  0.400611  0.599389

In [407]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_12f,'he'))

P('subj-pron'|subj=female) =  0.4137275392810504
P('non-subj-pron'|subj=female) =  0.5862724532683691

In [408]:
c2_average_subj_female_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12f,'she')
c2_average_subj_female_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12f,'he')

#### male subject

In [409]:
transofposs_imperfective_connective2_12m

                                             stimulus        he       she
12  Mr. Smith was transmitting a message to Miss S...  0.412985  0.587015
13  The man was transmitting a message to the woma...  0.415964  0.584036
14  John was transmitting a message to Mary and, a...  0.438729  0.561271
15  Bob was transmitting a message to Alice and, a...  0.355276  0.644724
16  The actor was transmitting a message to the ac...  0.384778  0.615222
17  The boy was transmitting a message to the girl...  0.395395  0.604605
18  Mr. William was transmitting a message to  Mrs...  0.486445  0.513555
19  David was transmitting a message to Emma and, ...  0.355556  0.644444
20  The prince was transmitting a message to the p...  0.385362  0.614638
21  Robert was transmitting a message to Sarah and...  0.405531  0.594469
22  Mr. Taylor was transmitting a message to Mrs. ...  0.357678  0.642322
23  Paul was transmitting a message to Emily and, ...  0.374036  0.625964

In [410]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_12m,'she'))

P('subj-pron'|subj=male) =  0.39731134474277496
P('non-subj-pron'|subj=male) =  0.6026886701583862

In [411]:
c2_average_subj_male_subj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12m,'he')
c2_average_subj_male_obj_pron['transmitting'] = compute_average(transofposs_imperfective_connective2_12m,'she')

### verb: "wiring"

In [412]:
transofposs_imperfective_connective2_14 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/14.csv")
transofposs_imperfective_connective2_14.head()

                                            stimulus        he       she
0  Miss Smith was wiring money to Mr. Smith and, ...  0.690368  0.309632
1  The woman was wiring money to the man and, as ...  0.657531  0.342469
2    Mary was wiring money to John and, as a result,  0.548423  0.451577
3    Alice was wiring money to Bob and, as a result,  0.365372  0.634628
4  The actress was wiring money to the actor and,...  0.576595  0.423405

In [413]:
# female subject
transofposs_imperfective_connective2_14f = transofposs_imperfective_connective2_14[0:12]
transofposs_imperfective_connective2_14f = transofposs_imperfective_connective2_14f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_14m = transofposs_imperfective_connective2_14[12:24]

#### female subject

In [414]:
transofposs_imperfective_connective2_14f

                                             stimulus       she        he
0   Miss Smith was wiring money to Mr. Smith and, ...  0.309632  0.690368
1   The woman was wiring money to the man and, as ...  0.342469  0.657531
2     Mary was wiring money to John and, as a result,  0.451577  0.548423
3     Alice was wiring money to Bob and, as a result,  0.634628  0.365372
4   The actress was wiring money to the actor and,...  0.423405  0.576595
5   The girl was wiring money to the boy and, as a...  0.335808  0.664192
6   Mrs. Taylor was wiring money to Mr. Williams a...  0.345604  0.654396
7    Emma was wiring money to David and, as a result,  0.393706  0.606294
8   The princess was wiring money to the prince an...  0.387137  0.612863
9   Sarah was wiring money to Robert and, as a res...  0.429800  0.570200
10  Mrs. Williams was wiring money to Mr. Taylor a...  0.396480  0.603520
11   Emily was wiring money to Paul and, as a result,  0.477744  0.522256

In [415]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_14f,'he'))

P('subj-pron'|subj=female) =  0.4106658423940341
P('non-subj-pron'|subj=female) =  0.5893341625730196

In [416]:
c2_average_subj_female_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14f,'she')
c2_average_subj_female_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14f,'he')

#### male subject

In [417]:
transofposs_imperfective_connective2_14m

                                             stimulus        he       she
12  Mr. Smith was wiring money to Miss Smith and, ...  0.362295  0.637705
13  The man was wiring money to the woman and, as ...  0.361733  0.638267
14    John was wiring money to Mary and, as a result,  0.417816  0.582184
15    Bob was wiring money to Alice and, as a result,  0.446554  0.553446
16  The actor was wiring money to the actress and,...  0.291077  0.708923
17  The boy was wiring money to the girl and, as a...  0.356091  0.643909
18  Mr. William was wiring money to  Mrs. Taylor a...  0.448481  0.551519
19   David was wiring money to Emma and, as a result,  0.386335  0.613665
20  The prince was wiring money to the princess an...  0.254368  0.745632
21  Robert was wiring money to Sarah and, as a res...  0.393830  0.606170
22  Mr. Taylor was wiring money to Mrs. Williams a...  0.350600  0.649400
23   Paul was wiring money to Emily and, as a result,  0.377625  0.622375

In [418]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_14m,'she'))

P('subj-pron'|subj=male) =  0.3705671528975169
P('non-subj-pron'|subj=male) =  0.6294328520695368

In [419]:
c2_average_subj_male_subj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14m,'he')
c2_average_subj_male_obj_pron['wiring'] = compute_average(transofposs_imperfective_connective2_14m,'she')

### verb: "carrying"

In [420]:
transofposs_imperfective_connective2_15 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/15.csv")
transofposs_imperfective_connective2_15.head()

                                            stimulus        he       she
0  Miss Smith was carrying a tray to Mr. Smith an...  0.506778  0.493222
1  The woman was carrying a tray to the man and, ...  0.365466  0.634534
2  Mary was carrying a tray to John and, as a res...  0.360009  0.639991
3  Alice was carrying a tray to Bob and, as a res...  0.221740  0.778260
4  The actress was carrying a tray to the actor a...  0.333479  0.666521

In [421]:
# female subject
transofposs_imperfective_connective2_15f = transofposs_imperfective_connective2_15[0:12]
transofposs_imperfective_connective2_15f = transofposs_imperfective_connective2_15f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_15m = transofposs_imperfective_connective2_15[12:24]

#### female subject

In [422]:
transofposs_imperfective_connective2_15f

                                             stimulus       she        he
0   Miss Smith was carrying a tray to Mr. Smith an...  0.493222  0.506778
1   The woman was carrying a tray to the man and, ...  0.634534  0.365466
2   Mary was carrying a tray to John and, as a res...  0.639991  0.360009
3   Alice was carrying a tray to Bob and, as a res...  0.778260  0.221740
4   The actress was carrying a tray to the actor a...  0.666521  0.333479
5   The girl was carrying a tray to the boy and, a...  0.633331  0.366669
6   Mrs. Taylor was carrying a tray to Mr. William...  0.499181  0.500819
7   Emma was carrying a tray to David and, as a re...  0.578816  0.421183
8   The princess was carrying a tray to the prince...  0.780556  0.219444
9   Sarah was carrying a tray to Robert and, as a ...  0.571846  0.428154
10  Mrs. Williams was carrying a tray to Mr. Taylo...  0.542894  0.457106
11  Emily was carrying a tray to Paul and, as a re...  0.672329  0.327671

In [423]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_15f,'he'))

P('subj-pron'|subj=female) =  0.624289999405543
P('non-subj-pron'|subj=female) =  0.37571001425385475

In [424]:
c2_average_subj_female_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15f,'she')
c2_average_subj_female_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15f,'he')

#### male subject

In [425]:
transofposs_imperfective_connective2_15m

                                             stimulus        he       she
12  Mr. Smith was carrying a tray to Miss Smith an...  0.620495  0.379505
13  The man was carrying a tray to the woman and, ...  0.520819  0.479181
14  John was carrying a tray to Mary and, as a res...  0.633511  0.366489
15  Bob was carrying a tray to Alice and, as a res...  0.578403  0.421597
16  The actor was carrying a tray to the actress a...  0.526430  0.473569
17  The boy was carrying a tray to the girl and, a...  0.568080  0.431920
18  Mr. William was carrying a tray to  Mrs. Taylo...  0.693266  0.306734
19  David was carrying a tray to Emma and, as a re...  0.544349  0.455651
20  The prince was carrying a tray to the princess...  0.641008  0.358992
21  Robert was carrying a tray to Sarah and, as a ...  0.591386  0.408614
22  Mr. Taylor was carrying a tray to Mrs. William...  0.593927  0.406073
23  Paul was carrying a tray to Emily and, as a re...  0.515285  0.484715

In [426]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_15m,'she'))

P('subj-pron'|subj=male) =  0.5855798770984014
P('non-subj-pron'|subj=male) =  0.41442012041807175

In [427]:
c2_average_subj_male_subj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15m,'he')
c2_average_subj_male_obj_pron['carrying'] = compute_average(transofposs_imperfective_connective2_15m,'she')

### verb: "delivering"

In [428]:
transofposs_imperfective_connective2_16 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/16.csv")
transofposs_imperfective_connective2_16.head()

                                            stimulus        he       she
0  Miss Smith was delivering a subpoena to Mr. Sm...  0.708169  0.291831
1  The woman was delivering a subpoena to the man...  0.463635  0.536365
2  Mary was delivering a subpoena to John and, as...  0.563713  0.436287
3  Alice was delivering a subpoena to Bob and, as...  0.415838  0.584162
4  The actress was delivering a subpoena to the a...  0.505489  0.494511

In [429]:
# female subject
transofposs_imperfective_connective2_16f = transofposs_imperfective_connective2_16[0:12]
transofposs_imperfective_connective2_16f = transofposs_imperfective_connective2_16f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_16m = transofposs_imperfective_connective2_16[12:24]

#### female subject

In [430]:
transofposs_imperfective_connective2_16f

                                             stimulus       she        he
0   Miss Smith was delivering a subpoena to Mr. Sm...  0.291831  0.708169
1   The woman was delivering a subpoena to the man...  0.536365  0.463635
2   Mary was delivering a subpoena to John and, as...  0.436287  0.563713
3   Alice was delivering a subpoena to Bob and, as...  0.584162  0.415838
4   The actress was delivering a subpoena to the a...  0.494511  0.505489
5   The girl was delivering a subpoena to the boy ...  0.439899  0.560101
6   Mrs. Taylor was delivering a subpoena to Mr. W...  0.344079  0.655921
7   Emma was delivering a subpoena to David and, a...  0.378942  0.621058
8   The princess was delivering a subpoena to the ...  0.536857  0.463143
9   Sarah was delivering a subpoena to Robert and,...  0.420584  0.579416
10  Mrs. Williams was delivering a subpoena to Mr....  0.400303  0.599697
11  Emily was delivering a subpoena to Paul and, a...  0.453825  0.546175

In [431]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_16f,'he'))

P('subj-pron'|subj=female) =  0.4431369751691818
P('non-subj-pron'|subj=female) =  0.5568630148967108

In [432]:
c2_average_subj_female_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16f,'she')
c2_average_subj_female_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16f,'he')

#### male subject

In [433]:
transofposs_imperfective_connective2_16m

                                             stimulus        he       she
12  Mr. Smith was delivering a subpoena to Miss Sm...  0.428814  0.571186
13  The man was delivering a subpoena to the woman...  0.507339  0.492661
14  John was delivering a subpoena to Mary and, as...  0.510649  0.489351
15  Bob was delivering a subpoena to Alice and, as...  0.479028  0.520972
16  The actor was delivering a subpoena to the act...  0.261698  0.738302
17  The boy was delivering a subpoena to the girl ...  0.502345  0.497655
18  Mr. William was delivering a subpoena to Mrs. ...  0.605482  0.394518
19  David was delivering a subpoena to Emma and, a...  0.392877  0.607123
20  The prince was delivering a subpoena to the pr...  0.422045  0.577955
21  Robert was delivering a subpoena to Sarah and,...  0.438656  0.561344
22  Mr. Taylor was delivering a subpoena to Mrs. W...  0.461774  0.538226
23  Paul was delivering a subpoena to Emily and, a...  0.445012  0.554988

In [434]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_16m,'she'))

P('subj-pron'|subj=male) =  0.45464332898457843
P('non-subj-pron'|subj=male) =  0.5453566734989485

In [435]:
c2_average_subj_male_subj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16m,'he')
c2_average_subj_male_obj_pron['delivering'] = compute_average(transofposs_imperfective_connective2_16m,'she')

### verb: "giving"

In [436]:
transofposs_imperfective_connective2_17 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/17.csv")
transofposs_imperfective_connective2_17.head()

                                            stimulus        he       she
0  Miss Smith was giving a sweater to Mr. Smith a...  0.647221  0.352779
1  The woman was giving a sweater to the man and,...  0.574008  0.425993
2  Mary was giving a sweater to John and, as a re...  0.526556  0.473444
3  Alice was giving a sweater to Bob and, as a re...  0.371256  0.628744
4  The actress was giving a sweater to the actor ...  0.499205  0.500795

In [437]:
# female subject
transofposs_imperfective_connective2_17f = transofposs_imperfective_connective2_17[0:12]
transofposs_imperfective_connective2_17f = transofposs_imperfective_connective2_17f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_17m = transofposs_imperfective_connective2_17[12:24]

#### female subject

In [438]:
transofposs_imperfective_connective2_17f

                                             stimulus       she        he
0   Miss Smith was giving a sweater to Mr. Smith a...  0.352779  0.647221
1   The woman was giving a sweater to the man and,...  0.425993  0.574008
2   Mary was giving a sweater to John and, as a re...  0.473444  0.526556
3   Alice was giving a sweater to Bob and, as a re...  0.628744  0.371256
4   The actress was giving a sweater to the actor ...  0.500795  0.499205
5   The girl was giving a sweater to the boy and, ...  0.417303  0.582697
6   Mrs. Taylor was giving a sweater to Mr. Willia...  0.340042  0.659958
7   Emma was giving a sweater to David and, as a r...  0.413771  0.586229
8   The princess was giving a sweater to the princ...  0.476546  0.523454
9   Sarah was giving a sweater to Robert and, as a...  0.418131  0.581869
10  Mrs. Williams was giving a sweater to Mr. Tayl...  0.406199  0.593801
11  Emily was giving a sweater to Paul and, as a r...  0.490758  0.509242

In [439]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_17f,'he'))

P('subj-pron'|subj=female) =  0.4453753853837649
P('non-subj-pron'|subj=female) =  0.5546246046821276

In [440]:
c2_average_subj_female_subj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17f,'she')
c2_average_subj_female_obj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17f,'he')

#### male subject

In [441]:
transofposs_imperfective_connective2_17m

                                             stimulus        he       she
12  Mr. Smith was giving a sweater to Miss Smith a...  0.493985  0.506015
13  The man was giving a sweater to the woman and,...  0.407906  0.592094
14  John was giving a sweater to Mary and, as a re...  0.546216  0.453784
15  Bob was giving a sweater to Alice and, as a re...  0.396147  0.603853
16  The actor was giving a sweater to the actress ...  0.436262  0.563738
17  The boy was giving a sweater to the girl and, ...  0.395091  0.604909
18  Mr. William was giving a sweater to  Mrs. Tayl...  0.553506  0.446494
19  David was giving a sweater to Emma and, as a r...  0.461157  0.538843
20  The prince was giving a sweater to the princes...  0.407685  0.592315
21  Robert was giving a sweater to Sarah and, as a...  0.512662  0.487338
22  Mr. Taylor was giving a sweater to Mrs. Willia...  0.481336  0.518664
23  Paul was giving a sweater to Emily and, as a r...  0.471714  0.528287

In [442]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_17m,'she'))

P('subj-pron'|subj=male) =  0.46363882968823117
P('non-subj-pron'|subj=male) =  0.5363611603776614

In [443]:
c2_average_subj_male_subj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17m,'he')
c2_average_subj_male_obj_pron['giving'] = compute_average(transofposs_imperfective_connective2_17m,'she')

### verb: "handing"

In [444]:
transofposs_imperfective_connective2_18 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/18.csv")
transofposs_imperfective_connective2_18.head()

                                            stimulus        he       she
0  Miss Smith was handing a book to Mr. Smith and...  0.697594  0.302406
1  The woman was handing a book to the man and, a...  0.596451  0.403549
2  Mary was handing a book to John and, as a result,  0.555897  0.444103
3  Alice was handing a book to Bob and, as a result,  0.379944  0.620056
4  The actress was handing a book to the actor an...  0.552202  0.447798

In [445]:
# female subject
transofposs_imperfective_connective2_18f = transofposs_imperfective_connective2_18[0:12]
transofposs_imperfective_connective2_18f = transofposs_imperfective_connective2_18f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_18m = transofposs_imperfective_connective2_18[12:24]

#### female subject

In [446]:
transofposs_imperfective_connective2_18f

                                             stimulus       she        he
0   Miss Smith was handing a book to Mr. Smith and...  0.302406  0.697594
1   The woman was handing a book to the man and, a...  0.403549  0.596451
2   Mary was handing a book to John and, as a result,  0.444103  0.555897
3   Alice was handing a book to Bob and, as a result,  0.620056  0.379944
4   The actress was handing a book to the actor an...  0.447798  0.552202
5   The girl was handing a book to the boy and, as...  0.383784  0.616216
6   Mrs. Taylor was handing a book to Mr. Williams...  0.340683  0.659317
7   Emma was handing a book to David and, as a res...  0.407399  0.592601
8   The princess was handing a book to the prince ...  0.546091  0.453909
9   Sarah was handing a book to Robert and, as a r...  0.426562  0.573438
10  Mrs. Williams was handing a book to Mr. Taylor...  0.376219  0.623781
11  Emily was handing a book to Paul and, as a res...  0.518411  0.481589

In [447]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_18f,'he'))

P('subj-pron'|subj=female) =  0.43475505461295444
P('non-subj-pron'|subj=female) =  0.5652449677387873

In [448]:
c2_average_subj_female_subj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18f,'she')
c2_average_subj_female_obj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18f,'he')

#### male subject

In [449]:
transofposs_imperfective_connective2_18m

                                             stimulus        he       she
12  Mr. Smith was handing a book to Miss Smith and...  0.456285  0.543715
13  The man was handing a book to the woman and, a...  0.368006  0.631994
14  John was handing a book to Mary and, as a result,  0.477240  0.522760
15  Bob was handing a book to Alice and, as a result,  0.311201  0.688799
16  The actor was handing a book to the actress an...  0.336308  0.663692
17  The boy was handing a book to the girl and, as...  0.394839  0.605161
18  Mr. William was handing a book to Mrs. Taylor ...  0.498174  0.501827
19  David was handing a book to Emma and, as a res...  0.366005  0.633995
20  The prince was handing a book to the princess ...  0.344292  0.655708
21  Robert was handing a book to Sarah and, as a r...  0.440873  0.559127
22  Mr. Taylor was handing a book to Mrs. Williams...  0.411802  0.588198
23  Paul was handing a book to Emily and, as a res...  0.402128  0.597872

In [450]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_18m,'she'))

P('subj-pron'|subj=male) =  0.40059616416692734
P('non-subj-pron'|subj=male) =  0.5994038333495458

In [451]:
c2_average_subj_male_subj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18m,'he')
c2_average_subj_male_obj_pron['handing'] = compute_average(transofposs_imperfective_connective2_18m,'she')

### verb: "passing"

In [452]:
transofposs_imperfective_connective2_19 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/19.csv")
transofposs_imperfective_connective2_19.head()

                                            stimulus        he       she
0  Miss Smith was passing a sandwich to Mr. Smith...  0.633675  0.366325
1  The woman was passing a sandwich to the man an...  0.498996  0.501004
2  Mary was passing a sandwich to John and, as a ...  0.539277  0.460723
3  Alice was passing a sandwich to Bob and, as a ...  0.285966  0.714034
4  The actress was passing a sandwich to the acto...  0.502950  0.497050

In [453]:
# female subject
transofposs_imperfective_connective2_19f = transofposs_imperfective_connective2_19[0:12]
transofposs_imperfective_connective2_19f = transofposs_imperfective_connective2_19f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_19m = transofposs_imperfective_connective2_19[12:24]

#### female subject

In [454]:
transofposs_imperfective_connective2_19f

                                             stimulus       she        he
0   Miss Smith was passing a sandwich to Mr. Smith...  0.366325  0.633675
1   The woman was passing a sandwich to the man an...  0.501004  0.498996
2   Mary was passing a sandwich to John and, as a ...  0.460723  0.539277
3   Alice was passing a sandwich to Bob and, as a ...  0.714034  0.285966
4   The actress was passing a sandwich to the acto...  0.497050  0.502950
5   The girl was passing a sandwich to the boy and...  0.525713  0.474287
6   Mrs. Taylor was passing a sandwich to Mr. Will...  0.318922  0.681078
7   Emma was passing a sandwich to David and, as a...  0.384829  0.615171
8   The princess was passing a sandwich to the pri...  0.601275  0.398725
9   Sarah was passing a sandwich to Robert and, as...  0.419485  0.580515
10  Mrs. Williams was passing a sandwich to  Mr. T...  0.338236  0.661764
11  Emily was passing a sandwich to Paul and, as a...  0.490585  0.509415

In [455]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_19f,'he'))

P('subj-pron'|subj=female) =  0.4681816026568413
P('non-subj-pron'|subj=female) =  0.5318183998266856

In [456]:
c2_average_subj_female_subj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19f,'she')
c2_average_subj_female_obj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19f,'he')

#### male subject

In [457]:
transofposs_imperfective_connective2_19m

                                             stimulus        he       she
12  Mr. Smith was passing a sandwich to Miss Smith...  0.508513  0.491487
13  The man was passing a sandwich to the woman an...  0.444531  0.555469
14  John was passing a sandwich to Mary and, as a ...  0.559261  0.440739
15  Bob was passing a sandwich to Alice and, as a ...  0.394202  0.605798
16  The actor was passing a sandwich to the actres...  0.401939  0.598061
17  The boy was passing a sandwich to the girl and...  0.465554  0.534446
18  Mr. William was passing a sandwich to  Mrs. Ta...  0.567998  0.432002
19  David was passing a sandwich to Emma and, as a...  0.437044  0.562956
20  The prince was passing a sandwich to the princ...  0.529673  0.470327
21  Robert was passing a sandwich to Sarah and, as...  0.494682  0.505318
22  Mr. Taylor was passing a sandwich to Mrs. Will...  0.461660  0.538340
23  Paul was passing a sandwich to Emily and, as a...  0.411998  0.588003

In [458]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_19m,'she'))

P('subj-pron'|subj=male) =  0.4730878695845604
P('non-subj-pron'|subj=male) =  0.5269121353824934

In [459]:
c2_average_subj_male_subj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19m,'he')
c2_average_subj_male_obj_pron['passing'] = compute_average(transofposs_imperfective_connective2_19m,'she')

### verb: "serving"

In [460]:
transofposs_imperfective_connective2_20 = pd.read_csv("../results/gpt2/transofposs_imperfective/connective2/20.csv")
transofposs_imperfective_connective2_20.head()

                                            stimulus        he       she
0  Miss Smith was serving a chili to Mr. Smith an...  0.669357  0.330644
1  The woman was serving a chili to the man and, ...  0.430098  0.569902
2  Mary was serving a chili to John and, as a res...  0.552261  0.447739
3  Alice was serving a chili to Bob and, as a res...  0.372460  0.627540
4  The actress was serving a chili to the actor a...  0.468828  0.531172

In [461]:
# female subject
transofposs_imperfective_connective2_20f = transofposs_imperfective_connective2_20[0:12]
transofposs_imperfective_connective2_20f = transofposs_imperfective_connective2_20f[["stimulus","she","he"]]
# male subject
transofposs_imperfective_connective2_20m = transofposs_imperfective_connective2_20[12:24]

#### female subject

In [462]:
transofposs_imperfective_connective2_20f

                                             stimulus       she        he
0   Miss Smith was serving a chili to Mr. Smith an...  0.330644  0.669357
1   The woman was serving a chili to the man and, ...  0.569902  0.430098
2   Mary was serving a chili to John and, as a res...  0.447739  0.552261
3   Alice was serving a chili to Bob and, as a res...  0.627540  0.372460
4   The actress was serving a chili to the actor a...  0.531172  0.468828
5   The girl was serving a chili to the boy and, a...  0.507522  0.492478
6   Mrs. Taylor was serving a chili to Mr. William...  0.307964  0.692036
7   Emma was serving a chili to David and, as a re...  0.458688  0.541312
8   The princess was serving a chili to the prince...  0.593661  0.406339
9   Sarah was serving a chili to Robert and, as a ...  0.418973  0.581027
10  Mrs. Williams was serving a chili to Mr. Taylo...  0.364323  0.635677
11  Emily was serving a chili to Paul and, as a re...  0.558204  0.441796

In [463]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_imperfective_connective2_20f,'he'))

P('subj-pron'|subj=female) =  0.47636088728904724
P('non-subj-pron'|subj=female) =  0.5236391102274259

In [464]:
c2_average_subj_female_subj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20f,'she')
c2_average_subj_female_obj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20f,'he')

#### male subject

In [465]:
transofposs_imperfective_connective2_20m

                                             stimulus        he       she
12  Mr. Smith was serving a chili to Miss Smith an...  0.473921  0.526079
13  The man was serving a chili to the woman and, ...  0.488125  0.511875
14  John was serving a chili to Mary and, as a res...  0.558784  0.441216
15  Bob was serving a chili to Alice and, as a res...  0.402203  0.597797
16  The actor was serving a chili to the actress a...  0.443691  0.556309
17  The boy was serving a chili to the girl and, a...  0.458166  0.541834
18  Mr. William was serving a chili to  Mrs. Taylo...  0.584203  0.415797
19  David was serving a chili to Emma and, as a re...  0.443386  0.556615
20  The prince was serving a chili to the princess...  0.503007  0.496993
21  Robert was serving a chili to Sarah and, as a ...  0.520242  0.479758
22  Mr. Taylor was serving a chili to Mrs. William...  0.460100  0.539900
23  Paul was serving a chili to Emily and, as a re...  0.425142  0.574858

In [466]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_imperfective_connective2_20m,'she'))

P('subj-pron'|subj=male) =  0.4800808106859525
P('non-subj-pron'|subj=male) =  0.51991917937994

In [467]:
c2_average_subj_male_subj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20m,'he')
c2_average_subj_male_obj_pron['serving'] = compute_average(transofposs_imperfective_connective2_20m,'she')

## Summary of Results

In [468]:
c2_results_fsubj_subjpron = pd.DataFrame(list(c2_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c2_results_fsubj_objpron = pd.DataFrame(list(c2_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c2_results_fsubj = c2_results_fsubj_subjpron.merge(c2_results_fsubj_objpron)
c2_results_fsubj

            verb  subj_ref_female_subj  obj_ref_female_subj
0       flinging              0.475681             0.524319
1        kicking              0.559192             0.440808
2        lobbing              0.412551             0.587449
3        rolling              0.547194             0.452806
4       throwing              0.492692             0.507308
5        tossing              0.519747             0.480253
6       bringing              0.410224             0.589776
7     forwarding              0.309501             0.690499
8        mailing              0.424017             0.575983
9       shipping              0.572643             0.427357
10  transmitting              0.413728             0.586272
11        wiring              0.410666             0.589334
12      carrying              0.624290             0.375710
13    delivering              0.443137             0.556863
14        giving              0.445375             0.554625
15       handing              0.434755             0.565245
16       passing              0.468182             0.531818
17       serving              0.476361             0.523639

In [469]:
c2_results_msubj_subjpron = pd.DataFrame(list(c2_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c2_results_msubj_objpron = pd.DataFrame(list(c2_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c2_results_msubj = c2_results_msubj_subjpron.merge(c2_results_msubj_objpron)
c2_results_msubj

            verb  subj_ref_male_subj  obj_ref_male_subj
0       flinging            0.451847           0.548153
1        kicking            0.499253           0.500747
2        lobbing            0.321808           0.678192
3        rolling            0.531090           0.468910
4       throwing            0.478310           0.521690
5        tossing            0.436661           0.563339
6       bringing            0.393982           0.606018
7     forwarding            0.268193           0.731807
8        mailing            0.413403           0.586597
9       shipping            0.509300           0.490700
10  transmitting            0.397311           0.602689
11        wiring            0.370567           0.629433
12      carrying            0.585580           0.414420
13    delivering            0.454643           0.545357
14        giving            0.463639           0.536361
15       handing            0.400596           0.599404
16       passing            0.473088           0.526912
17       serving            0.480081           0.519919

In [470]:
c2_results = c2_results_fsubj.merge(c2_results_msubj)
c2_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flinging,0.475681,0.524319,0.451847,0.548153
1,kicking,0.559192,0.440808,0.499253,0.500747
2,lobbing,0.412551,0.587449,0.321808,0.678192
3,rolling,0.547194,0.452806,0.531090,0.468910
4,throwing,0.492692,0.507308,0.478310,0.521690
5,tossing,0.519747,0.480253,0.436661,0.563339
6,bringing,0.410224,0.589776,0.393982,0.606018
7,forwarding,0.309501,0.690499,0.268193,0.731807
8,mailing,0.424017,0.575983,0.413403,0.586597
9,shipping,0.572643,0.427357,0.509300,0.490700
10,transmitting,0.413728,0.586272,0.397311,0.602689
11,wiring,0.410666,0.589334,0.370567,0.629433
12,carrying,0.624290,0.375710,0.585580,0.414420
13,delivering,0.443137,0.556863,0.454643,0.545357
14,giving,0.445375,0.554625,0.463639,0.536361
15,handing,0.434755,0.565245,0.400596,0.599404
16,passing,0.468182,0.531818,0.473088,0.526912
17,serving,0.476361,0.523639,0.480081,0.519919

In [471]:
print("P(subj_reference |subj=female)", compute_average(c2_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c2_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.46888535062747977
P(obj_reference |subj=female) 0.5311146529943304

In [472]:
print("P(subj_reference |subj=male)", compute_average(c2_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c2_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.4405195388115114
P(obj_reference |subj=male) 0.5594804616713965

In [473]:
# save results to csv
col_headers = ['verb','subj_ref_female_subj','obj_ref_female_subj','subj_ref_male_subj','obj_ref_male_subj']
np_results.to_csv("../results/gpt2/summary/transofposs_imperfective-noprompt.csv",index=False,header=col_headers)
c1_results.to_csv("../results/gpt2/summary/transofposs_imperfective-connective1.csv",index=False,header=col_headers)
c2_results.to_csv("../results/gpt2/summary/transofposs_imperfective-connective2.csv",index=False,header=col_headers)