In [1]:
import pandas as pd
import numpy as np

In [2]:
def compute_average(df,col):
    return np.mean(df[col].values)

## No-prompt

In [3]:
np_average_subj_female_subj_pron = {}
np_average_subj_female_obj_pron = {}
np_average_subj_male_subj_pron = {}
np_average_subj_male_obj_pron = {}

### Verb: "chucked" (NOTE: gets tokenized to 'unk')

In [4]:
transofposs_perfective_noprompt_1 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/1.csv")
transofposs_perfective_noprompt_1.head()

                                     stimulus        He       She
0   Miss Smith chucked a wrench to Mr. Smith.  0.655106  0.344894
1      The woman chucked a wrench to the man.  0.573790  0.426210
2              Mary chucked a wrench to John.  0.557705  0.442295
3              Alice chucked a wrench to Bob.  0.551179  0.448821
4  The actress chucked a wrench to the actor.  0.332716  0.667284

In [5]:
# female subject
transofposs_perfective_noprompt_1f = transofposs_perfective_noprompt_1[0:12]
transofposs_perfective_noprompt_1f = transofposs_perfective_noprompt_1f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_1m = transofposs_perfective_noprompt_1[12:24]

#### female subject

In [6]:
transofposs_perfective_noprompt_1f

                                         stimulus       She        He
0       Miss Smith chucked a wrench to Mr. Smith.  0.344894  0.655106
1          The woman chucked a wrench to the man.  0.426210  0.573790
2                  Mary chucked a wrench to John.  0.442295  0.557705
3                  Alice chucked a wrench to Bob.  0.448821  0.551179
4      The actress chucked a wrench to the actor.  0.667284  0.332716
5           The girl chucked a wrench to the boy.  0.454494  0.545506
6   Mrs. Taylor chucked a wrench to Mr. Williams.  0.274131  0.725869
7                 Emma chucked a wrench to David.  0.471277  0.528723
8    The princess chucked a wrench to the prince.  0.444167  0.555833
9               Sarah chucked a wrench to Robert.  0.383990  0.616010
10  Mrs. Williams chucked a wrench to Mr. Taylor.  0.270219  0.729780
11                Emily chucked a wrench to Paul.  0.552218  0.447782

In [7]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_1f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_1f,'He'))

P('subj-pron'|subj=female) =  0.43166663746039075
P('non-subj-pron'|subj=female) =  0.5683333550890287

In [8]:
#np_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1f,'She')
#np_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1f,'He')

#### male subject

In [9]:
transofposs_perfective_noprompt_1m

                                         stimulus        He       She
12      Mr. Smith chucked a wrench to Miss Smith.  0.408445  0.591555
13         The man chucked a wrench to the woman.  0.442712  0.557288
14                 John chucked a wrench to Mary.  0.526091  0.473909
15                 Bob chucked a wrench to Alice.  0.464462  0.535538
16     The actor chucked a wrench to the actress.  0.578819  0.421181
17          The boy chucked a wrench to the girl.  0.445032  0.554968
18   Mr. William chucked a wrench to Mrs. Taylor.  0.430708  0.569292
19                David chucked a wrench to Emma.  0.510903  0.489097
20   The prince chucked a wrench to the princess.  0.467019  0.532981
21              Robert chucked a wrench to Sarah.  0.519733  0.480267
22  Mr. Taylor chucked a wrench to Mrs. Williams.  0.426140  0.573860
23                Paul chucked a wrench to Emily.  0.516331  0.483669

In [10]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_1m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_1m,'She'))

P('subj-pron'|subj=male) =  0.4780328596631686
P('non-subj-pron'|subj=male) =  0.5219671428203583

In [11]:
#np_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1m,'He')
#np_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1m,'She')

### Verb: "flung"

In [12]:
transofposs_perfective_noprompt_2 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/2.csv")
transofposs_perfective_noprompt_2.head()

                                    stimulus        He       She
0   Miss Smith flung a frisbee to Mr. Smith.  0.682866  0.317134
1      The woman flung a frisbee to the man.  0.551684  0.448316
2              Mary flung a frisbee to John.  0.507793  0.492207
3              Alice flung a frisbee to Bob.  0.486313  0.513687
4  The actress flung a frisbee to the actor.  0.343582  0.656418

In [13]:
# female subject
transofposs_perfective_noprompt_2f = transofposs_perfective_noprompt_2[0:12]
transofposs_perfective_noprompt_2f = transofposs_perfective_noprompt_2f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_2m = transofposs_perfective_noprompt_2[12:24]

#### female subject

In [14]:
transofposs_perfective_noprompt_2f

                                         stimulus       She        He
0        Miss Smith flung a frisbee to Mr. Smith.  0.317134  0.682866
1           The woman flung a frisbee to the man.  0.448316  0.551684
2                   Mary flung a frisbee to John.  0.492207  0.507793
3                   Alice flung a frisbee to Bob.  0.513687  0.486313
4       The actress flung a frisbee to the actor.  0.656418  0.343582
5            The girl flung a frisbee to the boy.  0.424782  0.575218
6    Mrs. Taylor flung a frisbee to Mr. Williams.  0.410144  0.589856
7                  Emma flung a frisbee to David.  0.502035  0.497965
8     The princess flung a frisbee to the prince.  0.452229  0.547771
9                Sarah flung a frisbee to Robert.  0.470560  0.529440
10  Mrs. Williams flung a frisbee to  Mr. Taylor.  0.437202  0.562798
11                 Emily flung a frisbee to Paul.  0.617815  0.382185

In [15]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_2f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_2f,'He'))

P('subj-pron'|subj=female) =  0.4785441110531489
P('non-subj-pron'|subj=female) =  0.5214558939139048

In [16]:
np_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2f,'She')
np_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2f,'He')

#### male subject

In [17]:
transofposs_perfective_noprompt_2m

                                        stimulus        He       She
12      Mr. Smith flung a frisbee to Miss Smith.  0.396258  0.603742
13         The man flung a frisbee to the woman.  0.329184  0.670816
14                 John flung a frisbee to Mary.  0.444762  0.555238
15                 Bob flung a frisbee to Alice.  0.259614  0.740386
16     The actor flung a frisbee to the actress.  0.420831  0.579169
17          The boy flung a frisbee to the girl.  0.300518  0.699482
18  Mr. William flung a frisbee to  Mrs. Taylor.  0.496799  0.503201
19                David flung a frisbee to Emma.  0.362033  0.637967
20   The prince flung a frisbee to the princess.  0.303950  0.696050
21              Robert flung a frisbee to Sarah.  0.374137  0.625863
22  Mr. Taylor flung a frisbee to Mrs. Williams.  0.427812  0.572188
23                Paul flung a frisbee to Emily.  0.359298  0.640702

In [18]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_2m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_2m,'She'))

P('subj-pron'|subj=male) =  0.37293299039204914
P('non-subj-pron'|subj=male) =  0.627067024509112

In [19]:
np_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2m,'He')
np_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2m,'She')

### Verb: "kicked"

In [20]:
transofposs_perfective_noprompt_3 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/3.csv")
transofposs_perfective_noprompt_3.head()

                                         stimulus        He       She
0   Miss Smith kicked a soccer ball to Mr. Smith.  0.586300  0.413700
1      The woman kicked a soccer ball to the man.  0.415796  0.584204
2              Mary kicked a soccer ball to John.  0.402908  0.597092
3              Alice kicked a soccer ball to Bob.  0.319002  0.680998
4  The actress kicked a soccer ball to the actor.  0.253796  0.746204

In [21]:
# female subject
transofposs_perfective_noprompt_3f = transofposs_perfective_noprompt_3[0:12]
transofposs_perfective_noprompt_3f = transofposs_perfective_noprompt_3f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_3m = transofposs_perfective_noprompt_3[12:24]

#### female subject

In [22]:
transofposs_perfective_noprompt_3f

                                             stimulus       She        He
0       Miss Smith kicked a soccer ball to Mr. Smith.  0.413700  0.586300
1          The woman kicked a soccer ball to the man.  0.584204  0.415796
2                  Mary kicked a soccer ball to John.  0.597092  0.402908
3                  Alice kicked a soccer ball to Bob.  0.680998  0.319002
4      The actress kicked a soccer ball to the actor.  0.746204  0.253796
5           The girl kicked a soccer ball to the boy.  0.621714  0.378286
6   Mrs. Taylor kicked a soccer ball to Mr. Williams.  0.475434  0.524566
7                 Emma kicked a soccer ball to David.  0.588382  0.411618
8    The princess kicked a soccer ball to the prince.  0.620447  0.379553
9               Sarah kicked a soccer ball to Robert.  0.487658  0.512342
10  Mrs. Williams kicked a soccer ball to  Mr. Tay...  0.374495  0.625505
11                Emily kicked a soccer ball to Paul.  0.655493  0.344507

In [23]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_3f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_3f,'He'))

P('subj-pron'|subj=female) =  0.5704849561055502
P('non-subj-pron'|subj=female) =  0.4295150438944499

In [24]:
np_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3f,'She')
np_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3f,'He')

#### male subject

In [25]:
transofposs_perfective_noprompt_3m

                                             stimulus        He       She
12      Mr. Smith kicked a soccer ball to Miss Smith.  0.378555  0.621445
13         The man kicked a soccer ball to the woman.  0.380959  0.619041
14                 John kicked a soccer ball to Mary.  0.413443  0.586557
15                 Bob kicked a soccer ball to Alice.  0.331099  0.668901
16     The actor kicked a soccer ball to the actress.  0.517995  0.482005
17          The boy kicked a soccer ball to the girl.  0.369490  0.630510
18  Mr. William kicked a soccer ball to  Mrs. Taylor.  0.449160  0.550840
19                David kicked a soccer ball to Emma.  0.345737  0.654262
20   The prince kicked a soccer ball to the princess.  0.444380  0.555620
21              Robert kicked a soccer ball to Sarah.  0.403876  0.596124
22  Mr. Taylor kicked a soccer ball to Mrs. Williams.  0.398010  0.601990
23                Paul kicked a soccer ball to Emily.  0.320931  0.679069

In [26]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_3m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_3m,'She'))

P('subj-pron'|subj=male) =  0.3961363459626834
P('non-subj-pron'|subj=male) =  0.6038636416196823

In [27]:
np_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3m,'He')
np_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3m,'She')

### verb: "lobbed"

In [28]:
transofposs_perfective_noprompt_4 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/4.csv")
transofposs_perfective_noprompt_4.head()

                                      stimulus        He       She
0   Miss Smith lobbed a football to Mr. Smith.  0.793298  0.206702
1      The woman lobbed a football to the man.  0.519214  0.480786
2              Mary lobbed a football to John.  0.471333  0.528667
3              Alice lobbed a football to Bob.  0.421603  0.578397
4  The actress lobbed a football to the actor.  0.303534  0.696465

In [29]:
# female subject
transofposs_perfective_noprompt_4f = transofposs_perfective_noprompt_4[0:12]
transofposs_perfective_noprompt_4f = transofposs_perfective_noprompt_4f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_4m = transofposs_perfective_noprompt_4[12:24]

#### female subject

In [30]:
transofposs_perfective_noprompt_4f

                                           stimulus       She        He
0        Miss Smith lobbed a football to Mr. Smith.  0.206702  0.793298
1           The woman lobbed a football to the man.  0.480786  0.519214
2                   Mary lobbed a football to John.  0.528667  0.471333
3                   Alice lobbed a football to Bob.  0.578397  0.421603
4       The actress lobbed a football to the actor.  0.696465  0.303534
5            The girl lobbed a football to the boy.  0.506626  0.493374
6    Mrs. Taylor lobbed a football to Mr. Williams.  0.272544  0.727456
7                  Emma lobbed a football to David.  0.507371  0.492629
8     The princess lobbed a football to the prince.  0.500973  0.499027
9                Sarah lobbed a football to Robert.  0.425351  0.574649
10  Mrs. Williams lobbed a football to  Mr. Taylor.  0.262237  0.737763
11                 Emily lobbed a football to Paul.  0.605833  0.394167

In [31]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_4f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_4f,'He'))

P('subj-pron'|subj=female) =  0.46432942276199657
P('non-subj-pron'|subj=female) =  0.5356705635786057

In [32]:
np_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4f,'She')
np_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4f,'He')

#### male subject

In [33]:
transofposs_perfective_noprompt_4m

                                          stimulus        He       She
12      Mr. Smith lobbed a football to Miss Smith.  0.361953  0.638047
13         The man lobbed a football to the woman.  0.362696  0.637303
14                 John lobbed a football to Mary.  0.407523  0.592477
15                 Bob lobbed a football to Alice.  0.298020  0.701980
16     The actor lobbed a football to the actress.  0.480052  0.519948
17          The boy lobbed a football to the girl.  0.361605  0.638395
18  Mr. William lobbed a football to  Mrs. Taylor.  0.404610  0.595390
19                David lobbed a football to Emma.  0.359623  0.640377
20   The prince lobbed a football to the princess.  0.393563  0.606437
21              Robert lobbed a football to Sarah.  0.423665  0.576335
22  Mr. Taylor lobbed a football to Mrs. Williams.  0.391904  0.608096
23                Paul lobbed a football to Emily.  0.350329  0.649671

In [34]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_4m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_4m,'She'))

P('subj-pron'|subj=male) =  0.38296207288901013
P('non-subj-pron'|subj=male) =  0.6170379122098287

In [35]:
np_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4m,'He')
np_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4m,'She')

### verb: "rolled"

In [36]:
transofposs_perfective_noprompt_5 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/5.csv")
transofposs_perfective_noprompt_5.head()

                                       stimulus        He       She
0   Miss Smith rolled a toy truck to Mr. Smith.  0.466073  0.533927
1      The woman rolled a toy truck to the man.  0.317557  0.682443
2              Mary rolled a toy truck to John.  0.359899  0.640101
3              Alice rolled a toy truck to Bob.  0.330972  0.669028
4  The actress rolled a toy truck to the actor.  0.231389  0.768611

In [37]:
# female subject
transofposs_perfective_noprompt_5f = transofposs_perfective_noprompt_5[0:12]
transofposs_perfective_noprompt_5f = transofposs_perfective_noprompt_5f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_5m = transofposs_perfective_noprompt_5[12:24]

#### female subject

In [38]:
transofposs_perfective_noprompt_5f

                                            stimulus       She        He
0        Miss Smith rolled a toy truck to Mr. Smith.  0.533927  0.466073
1           The woman rolled a toy truck to the man.  0.682443  0.317557
2                   Mary rolled a toy truck to John.  0.640101  0.359899
3                   Alice rolled a toy truck to Bob.  0.669028  0.330972
4       The actress rolled a toy truck to the actor.  0.768611  0.231389
5            The girl rolled a toy truck to the boy.  0.666937  0.333063
6    Mrs. Taylor rolled a toy truck to Mr. Williams.  0.490068  0.509932
7                  Emma rolled a toy truck to David.  0.630682  0.369318
8     The princess rolled a toy truck to the prince.  0.669544  0.330456
9                Sarah rolled a toy truck to Robert.  0.540017  0.459983
10  Mrs. Williams rolled a toy truck to  Mr. Taylor.  0.390033  0.609967
11                 Emily rolled a toy truck to Paul.  0.720290  0.279710

In [39]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_5f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_5f,'He'))

P('subj-pron'|subj=female) =  0.616806743045648
P('non-subj-pron'|subj=female) =  0.3831932557125886

In [40]:
np_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_5f,'She')
np_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_5f,'He')

#### male subject

In [41]:
transofposs_perfective_noprompt_5m

                                           stimulus        He       She
12      Mr. Smith rolled a toy truck to Miss Smith.  0.410975  0.589025
13         The man rolled a toy truck to the woman.  0.462499  0.537501
14                 John rolled a toy truck to Mary.  0.504326  0.495674
15                 Bob rolled a toy truck to Alice.  0.402514  0.597486
16     The actor rolled a toy truck to the actress.  0.555422  0.444578
17          The boy rolled a toy truck to the girl.  0.468276  0.531724
18  Mr. William rolled a toy truck to  Mrs. Taylor.  0.445133  0.554867
19                David rolled a toy truck to Emma.  0.431010  0.568990
20   The prince rolled a toy truck to the princess.  0.516921  0.483079
21              Robert rolled a toy truck to Sarah.  0.476517  0.523483
22  Mr. Taylor rolled a toy truck to Mrs. Williams.  0.450841  0.549159
23                Paul rolled a toy truck to Emily.  0.418029  0.581971

In [42]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_5m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_5m,'She'))

P('subj-pron'|subj=male) =  0.461871974170208
P('non-subj-pron'|subj=male) =  0.53812804321448

In [43]:
np_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_noprompt_5m,'He')
np_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_noprompt_5m,'She')

### verb: "threw"

In [44]:
transofposs_perfective_noprompt_6 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/6.csv")
transofposs_perfective_noprompt_6.head()

                                stimulus        He       She
0   Miss Smith threw a hat to Mr. Smith.  0.529576  0.470424
1      The woman threw a hat to the man.  0.419714  0.580286
2              Mary threw a hat to John.  0.477657  0.522343
3              Alice threw a hat to Bob.  0.331695  0.668305
4  The actress threw a hat to the actor.  0.235620  0.764380

In [45]:
# female subject
transofposs_perfective_noprompt_6f = transofposs_perfective_noprompt_6[0:12]
transofposs_perfective_noprompt_6f = transofposs_perfective_noprompt_6f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_6m = transofposs_perfective_noprompt_6[12:24]

#### female subject

In [46]:
transofposs_perfective_noprompt_6f

                                     stimulus       She        He
0        Miss Smith threw a hat to Mr. Smith.  0.470424  0.529576
1           The woman threw a hat to the man.  0.580286  0.419714
2                   Mary threw a hat to John.  0.522343  0.477657
3                   Alice threw a hat to Bob.  0.668305  0.331695
4       The actress threw a hat to the actor.  0.764380  0.235620
5            The girl threw a hat to the boy.  0.574668  0.425332
6    Mrs. Taylor threw a hat to Mr. Williams.  0.483631  0.516369
7                  Emma threw a hat to David.  0.617564  0.382436
8     The princess threw a hat to the prince.  0.571502  0.428498
9                Sarah threw a hat to Robert.  0.524504  0.475496
10  Mrs. Williams threw a hat to  Mr. Taylor.  0.422675  0.577325
11                 Emily threw a hat to Paul.  0.709332  0.290668

In [47]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_6f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_6f,'He'))

P('subj-pron'|subj=female) =  0.5758012334505717
P('non-subj-pron'|subj=female) =  0.42419874916474026

In [48]:
np_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6f,'She')
np_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6f,'He')

#### male subject

In [49]:
transofposs_perfective_noprompt_6m

                                    stimulus        He       She
12      Mr. Smith threw a hat to Miss Smith.  0.457545  0.542455
13         The man threw a hat to the woman.  0.413519  0.586481
14                 John threw a hat to Mary.  0.717069  0.282931
15                 Bob threw a hat to Alice.  0.543803  0.456197
16     The actor threw a hat to the actress.  0.606643  0.393357
17          The boy threw a hat to the girl.  0.424419  0.575581
18  Mr. William threw a hat to  Mrs. Taylor.  0.499886  0.500114
19                David threw a hat to Emma.  0.560038  0.439962
20   The prince threw a hat to the princess.  0.428331  0.571669
21              Robert threw a hat to Sarah.  0.518003  0.481997
22  Mr. Taylor threw a hat to Mrs. Williams.  0.522288  0.477712
23                Paul threw a hat to Emily.  0.576889  0.423111

In [50]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_6m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_6m,'She'))

P('subj-pron'|subj=male) =  0.522369422018528
P('non-subj-pron'|subj=male) =  0.4776305804649989

In [51]:
np_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6m,'He')
np_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6m,'She')

### verb: "tossed"

In [52]:
transofposs_perfective_noprompt_7 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/7.csv")
transofposs_perfective_noprompt_7.head()

                                        stimulus        He       She
0   Miss Smith tossed a dish towel to Mr. Smith.  0.557592  0.442408
1      The woman tossed a dish towel to the man.  0.384281  0.615719
2              Mary tossed a dish towel to John.  0.368834  0.631166
3              Alice tossed a dish towel to Bob.  0.415740  0.584260
4  The actress tossed a dish towel to the actor.  0.270641  0.729359

In [53]:
# female subject
transofposs_perfective_noprompt_7f = transofposs_perfective_noprompt_7[0:12]
transofposs_perfective_noprompt_7f = transofposs_perfective_noprompt_7f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_7m = transofposs_perfective_noprompt_7[12:24]

#### female subject

In [54]:
transofposs_perfective_noprompt_7f

                                             stimulus       She        He
0        Miss Smith tossed a dish towel to Mr. Smith.  0.442408  0.557592
1           The woman tossed a dish towel to the man.  0.615719  0.384281
2                   Mary tossed a dish towel to John.  0.631166  0.368834
3                   Alice tossed a dish towel to Bob.  0.584260  0.415740
4       The actress tossed a dish towel to the actor.  0.729359  0.270641
5            The girl tossed a dish towel to the boy.  0.614251  0.385749
6    Mrs. Taylor tossed a dish towel to Mr. Williams.  0.476976  0.523024
7                  Emma tossed a dish towel to David.  0.568917  0.431083
8     The princess tossed a dish towel to the prince.  0.709001  0.290999
9                Sarah tossed a dish towel to Robert.  0.515610  0.484390
10  Mrs. Williams tossed a dish towel to  Mr. Taylor.  0.438545  0.561455
11                 Emily tossed a dish towel to Paul.  0.689722  0.310278

In [55]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_7f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_7f,'He'))

P('subj-pron'|subj=female) =  0.5846611857414246
P('non-subj-pron'|subj=female) =  0.4153388092915217

In [56]:
np_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7f,'She')
np_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7f,'He')

#### male subject

In [57]:
transofposs_perfective_noprompt_7m

                                            stimulus        He       She
12      Mr. Smith tossed a dish towel to Miss Smith.  0.363167  0.636833
13         The man tossed a dish towel to the woman.  0.438355  0.561645
14                 John tossed a dish towel to Mary.  0.478687  0.521313
15                 Bob tossed a dish towel to Alice.  0.311720  0.688280
16     The actor tossed a dish towel to the actress.  0.531675  0.468325
17          The boy tossed a dish towel to the girl.  0.437957  0.562043
18  Mr. William tossed a dish towel to  Mrs. Taylor.  0.396297  0.603703
19                David tossed a dish towel to Emma.  0.380900  0.619100
20   The prince tossed a dish towel to the princess.  0.472418  0.527582
21              Robert tossed a dish towel to Sarah.  0.436924  0.563076
22  Mr. Taylor tossed a dish towel to Mrs. Williams.  0.378383  0.621617
23                Paul tossed a dish towel to Emily.  0.398209  0.601791

In [58]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_7m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_7m,'She'))

P('subj-pron'|subj=male) =  0.4187242016196251
P('non-subj-pron'|subj=male) =  0.5812757834792137

In [59]:
np_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7m,'He')
np_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7m,'She')

### verb: "brought"

In [60]:
transofposs_perfective_noprompt_8 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/8.csv")
transofposs_perfective_noprompt_8.head()

                                            stimulus        He       She
0  Miss Smith brought a glass of water to Mr. Smith.  0.650046  0.349954
1     The woman brought a glass of water to the man.  0.418704  0.581296
2             Mary brought a glass of water to John.  0.557008  0.442992
3             Alice brought a glass of water to Bob.  0.449314  0.550686
4  The actress brought a glass of water to the ac...  0.299484  0.700516

In [61]:
# female subject
transofposs_perfective_noprompt_8f = transofposs_perfective_noprompt_8[0:12]
transofposs_perfective_noprompt_8f = transofposs_perfective_noprompt_8f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_8m = transofposs_perfective_noprompt_8[12:24]

#### female subject

In [62]:
transofposs_perfective_noprompt_8f

                                             stimulus       She        He
0   Miss Smith brought a glass of water to Mr. Smith.  0.349954  0.650046
1      The woman brought a glass of water to the man.  0.581296  0.418704
2              Mary brought a glass of water to John.  0.442992  0.557008
3              Alice brought a glass of water to Bob.  0.550686  0.449314
4   The actress brought a glass of water to the ac...  0.700516  0.299484
5       The girl brought a glass of water to the boy.  0.566471  0.433529
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.396723  0.603277
7             Emma brought a glass of water to David.  0.541175  0.458825
8   The princess brought a glass of water to the p...  0.536847  0.463153
9           Sarah brought a glass of water to Robert.  0.476732  0.523268
10  Mrs. Williams brought a glass of water to  Mr....  0.327903  0.672097
11            Emily brought a glass of water to Paul.  0.650306  0.349694

In [63]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_8f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_8f,'He'))

P('subj-pron'|subj=female) =  0.5101335669557253
P('non-subj-pron'|subj=female) =  0.4898664404948552

In [64]:
np_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8f,'She')
np_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8f,'He')

#### male subject

In [65]:
transofposs_perfective_noprompt_8m

                                             stimulus        He       She
12  Mr. Smith brought a glass of water to Miss Smith.  0.435655  0.564345
13     The man brought a glass of water to the woman.  0.470738  0.529262
14             John brought a glass of water to Mary.  0.629651  0.370349
15             Bob brought a glass of water to Alice.  0.361632  0.638368
16  The actor brought a glass of water to the actr...  0.488734  0.511266
17      The boy brought a glass of water to the girl.  0.441030  0.558970
18  Mr. William brought a glass of water to  Mrs. ...  0.487040  0.512960
19            David brought a glass of water to Emma.  0.408972  0.591028
20  The prince brought a glass of water to the pri...  0.378494  0.621506
21          Robert brought a glass of water to Sarah.  0.499829  0.500171
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.467856  0.532144
23            Paul brought a glass of water to Emily.  0.460763  0.539237

In [66]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_8m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_8m,'She'))

P('subj-pron'|subj=male) =  0.46086613833904266
P('non-subj-pron'|subj=male) =  0.5391338765621185

In [67]:
np_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8m,'He')
np_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8m,'She')

### verb: "forwarded"

In [68]:
transofposs_perfective_noprompt_9 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/9.csv")
transofposs_perfective_noprompt_9.head()

                                            stimulus        He       She
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.402147  0.597853
1    The woman forwarded a gossipy email to the man.  0.381406  0.618594
2            Mary forwarded a gossipy email to John.  0.256243  0.743757
3            Alice forwarded a gossipy email to Bob.  0.253519  0.746481
4  The actress forwarded a gossipy email to the a...  0.238669  0.761331

In [69]:
# female subject
transofposs_perfective_noprompt_9f = transofposs_perfective_noprompt_9[0:12]
transofposs_perfective_noprompt_9f = transofposs_perfective_noprompt_9f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_9m = transofposs_perfective_noprompt_9[12:24]

#### female subject

In [70]:
transofposs_perfective_noprompt_9f

                                             stimulus       She        He
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.597853  0.402147
1     The woman forwarded a gossipy email to the man.  0.618594  0.381406
2             Mary forwarded a gossipy email to John.  0.743757  0.256243
3             Alice forwarded a gossipy email to Bob.  0.746481  0.253519
4   The actress forwarded a gossipy email to the a...  0.761331  0.238669
5      The girl forwarded a gossipy email to the boy.  0.632799  0.367201
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.654185  0.345815
7            Emma forwarded a gossipy email to David.  0.634458  0.365542
8   The princess forwarded a gossipy email to the ...  0.688536  0.311464
9          Sarah forwarded a gossipy email to Robert.  0.683247  0.316753
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.636905  0.363095
11           Emily forwarded a gossipy email to Paul.  0.725319  0.274681

In [71]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_9f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_9f,'He'))

P('subj-pron'|subj=female) =  0.6769554068644842
P('non-subj-pron'|subj=female) =  0.3230445918937524

In [72]:
np_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9f,'She')
np_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9f,'He')

#### male subject

In [73]:
transofposs_perfective_noprompt_9m

                                             stimulus        He       She
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.466317  0.533683
13    The man forwarded a gossipy email to the woman.  0.469241  0.530759
14            John forwarded a gossipy email to Mary.  0.577396  0.422604
15            Bob forwarded a gossipy email to Alice.  0.397423  0.602577
16  The actor forwarded a gossipy email to the act...  0.524231  0.475769
17     The boy forwarded a gossipy email to the girl.  0.432932  0.567068
18  Mr. William forwarded a gossipy email to  Mrs....  0.503300  0.496700
19           David forwarded a gossipy email to Emma.  0.506933  0.493067
20  The prince forwarded a gossipy email to the pr...  0.488329  0.511671
21         Robert forwarded a gossipy email to Sarah.  0.561484  0.438516
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.450406  0.549594
23           Paul forwarded a gossipy email to Emily.  0.532936  0.467064

In [74]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_9m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_9m,'She'))

P('subj-pron'|subj=male) =  0.4925774733225505
P('non-subj-pron'|subj=male) =  0.507422536611557

In [75]:
np_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9m,'He')
np_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9m,'She')

### verb: "mailed"

In [76]:
transofposs_perfective_noprompt_10 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/10.csv")
transofposs_perfective_noprompt_10.head()

                                    stimulus        He       She
0   Miss Smith mailed a letter to Mr. Smith.  0.283856  0.716144
1      The woman mailed a letter to the man.  0.225767  0.774233
2              Mary mailed a letter to John.  0.187583  0.812418
3              Alice mailed a letter to Bob.  0.128522  0.871478
4  The actress mailed a letter to the actor.  0.128937  0.871063

In [77]:
# female subject
transofposs_perfective_noprompt_10f = transofposs_perfective_noprompt_10[0:12]
transofposs_perfective_noprompt_10f = transofposs_perfective_noprompt_10f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_10m = transofposs_perfective_noprompt_10[12:24]

#### female subject

In [78]:
transofposs_perfective_noprompt_10f

                                         stimulus       She        He
0        Miss Smith mailed a letter to Mr. Smith.  0.716144  0.283856
1           The woman mailed a letter to the man.  0.774233  0.225767
2                   Mary mailed a letter to John.  0.812418  0.187583
3                   Alice mailed a letter to Bob.  0.871478  0.128522
4       The actress mailed a letter to the actor.  0.871063  0.128937
5            The girl mailed a letter to the boy.  0.753656  0.246343
6    Mrs. Taylor mailed a letter to Mr. Williams.  0.706960  0.293040
7                  Emma mailed a letter to David.  0.771254  0.228746
8     The princess mailed a letter to the prince.  0.783560  0.216440
9                Sarah mailed a letter to Robert.  0.761290  0.238710
10  Mrs. Williams mailed a letter to  Mr. Taylor.  0.689763  0.310237
11                 Emily mailed a letter to Paul.  0.843846  0.156154

In [79]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_10f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_10f,'He'))

P('subj-pron'|subj=female) =  0.7796386877695719
P('non-subj-pron'|subj=female) =  0.22036132216453552

In [80]:
np_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10f,'She')
np_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10f,'He')

#### male subject

In [81]:
transofposs_perfective_noprompt_10m

                                        stimulus        He       She
12      Mr. Smith mailed a letter to Miss Smith.  0.591246  0.408754
13         The man mailed a letter to the woman.  0.717962  0.282038
14                 John mailed a letter to Mary.  0.796714  0.203286
15                 Bob mailed a letter to Alice.  0.754284  0.245716
16     The actor mailed a letter to the actress.  0.712006  0.287994
17          The boy mailed a letter to the girl.  0.686742  0.313258
18  Mr. William mailed a letter to  Mrs. Taylor.  0.627027  0.372973
19                David mailed a letter to Emma.  0.738798  0.261202
20   The prince mailed a letter to the princess.  0.715178  0.284822
21              Robert mailed a letter to Sarah.  0.755703  0.244298
22  Mr. Taylor mailed a letter to Mrs. Williams.  0.642068  0.357932
23                Paul mailed a letter to Emily.  0.756380  0.243620

In [82]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_10m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_10m,'She'))

P('subj-pron'|subj=male) =  0.7078423003355662
P('non-subj-pron'|subj=male) =  0.29215769842267036

In [83]:
np_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10m,'He')
np_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10m,'She')

### verb: "shipped"

In [84]:
transofposs_perfective_noprompt_11 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/11.csv")
transofposs_perfective_noprompt_11.head()

                                      stimulus        He       She
0   Miss Smith shipped a package to Mr. Smith.  0.470996  0.529004
1      The woman shipped a package to the man.  0.315864  0.684136
2              Mary shipped a package to John.  0.318245  0.681755
3              Alice shipped a package to Bob.  0.197450  0.802550
4  The actress shipped a package to the actor.  0.195582  0.804418

In [85]:
# female subject
transofposs_perfective_noprompt_11f = transofposs_perfective_noprompt_11[0:12]
transofposs_perfective_noprompt_11f = transofposs_perfective_noprompt_11f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_11m = transofposs_perfective_noprompt_11[12:24]

#### female subject

In [86]:
transofposs_perfective_noprompt_11f

                                           stimulus       She        He
0        Miss Smith shipped a package to Mr. Smith.  0.529004  0.470996
1           The woman shipped a package to the man.  0.684136  0.315864
2                   Mary shipped a package to John.  0.681755  0.318245
3                   Alice shipped a package to Bob.  0.802550  0.197450
4       The actress shipped a package to the actor.  0.804418  0.195582
5            The girl shipped a package to the boy.  0.669853  0.330147
6    Mrs. Taylor shipped a package to Mr. Williams.  0.546229  0.453771
7                  Emma shipped a package to David.  0.698033  0.301967
8     The princess shipped a package to the prince.  0.699491  0.300509
9                Sarah shipped a package to Robert.  0.575747  0.424253
10  Mrs. Williams shipped a package to  Mr. Taylor.  0.513371  0.486629
11                 Emily shipped a package to Paul.  0.739101  0.260899

In [87]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_11f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_11f,'He'))

P('subj-pron'|subj=female) =  0.6619740724563599
P('non-subj-pron'|subj=female) =  0.33802590767542523

In [88]:
np_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11f,'She')
np_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11f,'He')

#### male subject

In [89]:
transofposs_perfective_noprompt_11m

                                          stimulus        He       She
12      Mr. Smith shipped a package to Miss Smith.  0.429316  0.570684
13         The man shipped a package to the woman.  0.538325  0.461675
14                 John shipped a package to Mary.  0.611429  0.388571
15                 Bob shipped a package to Alice.  0.450968  0.549032
16     The actor shipped a package to the actress.  0.561013  0.438987
17          The boy shipped a package to the girl.  0.542523  0.457477
18  Mr. William shipped a package to  Mrs. Taylor.  0.472029  0.527971
19                David shipped a package to Emma.  0.502260  0.497740
20   The prince shipped a package to the princess.  0.557154  0.442846
21              Robert shipped a package to Sarah.  0.515949  0.484051
22  Mr. Taylor shipped a package to Mrs. Williams.  0.437170  0.562830
23                Paul shipped a package to Emily.  0.502451  0.497549

In [90]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_11m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_11m,'She'))

P('subj-pron'|subj=male) =  0.5100488811731339
P('non-subj-pron'|subj=male) =  0.48995111137628555

In [91]:
np_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11m,'He')
np_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11m,'She')

### verb: "transmitted"

In [92]:
transofposs_perfective_noprompt_12 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/12.csv")
transofposs_perfective_noprompt_12.head()

                                          stimulus        He       She
0   Miss Smith transmitted a message to Mr. Smith.  0.452728  0.547272
1      The woman transmitted a message to the man.  0.363483  0.636517
2              Mary transmitted a message to John.  0.383751  0.616249
3              Alice transmitted a message to Bob.  0.273756  0.726244
4  The actress transmitted a message to the actor.  0.209657  0.790343

In [93]:
# female subject
transofposs_perfective_noprompt_12f = transofposs_perfective_noprompt_12[0:12]
transofposs_perfective_noprompt_12f = transofposs_perfective_noprompt_12f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_12m = transofposs_perfective_noprompt_12[12:24]

#### female subject

In [94]:
transofposs_perfective_noprompt_12f

                                             stimulus       She        He
0      Miss Smith transmitted a message to Mr. Smith.  0.547272  0.452728
1         The woman transmitted a message to the man.  0.636517  0.363483
2                 Mary transmitted a message to John.  0.616249  0.383751
3                 Alice transmitted a message to Bob.  0.726244  0.273756
4     The actress transmitted a message to the actor.  0.790343  0.209657
5          The girl transmitted a message to the boy.  0.652408  0.347592
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.577056  0.422944
7                Emma transmitted a message to David.  0.690831  0.309169
8   The princess transmitted a message to the prince.  0.741750  0.258250
9              Sarah transmitted a message to Robert.  0.639741  0.360259
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.529952  0.470048
11               Emily transmitted a message to Paul.  0.779202  0.220798

In [95]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_12f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_12f,'He'))

P('subj-pron'|subj=female) =  0.6606303801139196
P('non-subj-pron'|subj=female) =  0.3393695962925752

In [96]:
np_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12f,'She')
np_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12f,'He')

#### male subject

In [97]:
transofposs_perfective_noprompt_12m

                                             stimulus        He       She
12     Mr. Smith transmitted a message to Miss Smith.  0.529994  0.470006
13        The man transmitted a message to the woman.  0.565186  0.434814
14                John transmitted a message to Mary.  0.717496  0.282504
15                Bob transmitted a message to Alice.  0.658891  0.341109
16    The actor transmitted a message to the actress.  0.677906  0.322095
17         The boy transmitted a message to the girl.  0.586308  0.413692
18  Mr. William transmitted a message to  Mrs. Tay...  0.590803  0.409197
19               David transmitted a message to Emma.  0.612558  0.387442
20  The prince transmitted a message to the princess.  0.593119  0.406881
21             Robert transmitted a message to Sarah.  0.662610  0.337390
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.563062  0.436938
23               Paul transmitted a message to Emily.  0.688495  0.311505

In [98]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_12m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_12m,'She'))

P('subj-pron'|subj=male) =  0.620535597205162
P('non-subj-pron'|subj=male) =  0.37946440776189166

In [99]:
np_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12m,'He')
np_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12m,'She')

### verb: "wired"

In [100]:
transofposs_perfective_noprompt_14 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/14.csv")
transofposs_perfective_noprompt_14.head()

                                stimulus        He       She
0   Miss Smith wired money to Mr. Smith.  0.384143  0.615857
1      The woman wired money to the man.  0.338253  0.661747
2              Mary wired money to John.  0.330188  0.669812
3              Alice wired money to Bob.  0.238996  0.761004
4  The actress wired money to the actor.  0.239803  0.760197

In [101]:
# female subject
transofposs_perfective_noprompt_14f = transofposs_perfective_noprompt_14[0:12]
transofposs_perfective_noprompt_14f = transofposs_perfective_noprompt_14f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_14m = transofposs_perfective_noprompt_14[12:24]

#### female subject

In [102]:
transofposs_perfective_noprompt_14f

                                     stimulus       She        He
0        Miss Smith wired money to Mr. Smith.  0.615857  0.384143
1           The woman wired money to the man.  0.661747  0.338253
2                   Mary wired money to John.  0.669812  0.330188
3                   Alice wired money to Bob.  0.761004  0.238996
4       The actress wired money to the actor.  0.760197  0.239803
5            The girl wired money to the boy.  0.670528  0.329472
6    Mrs. Taylor wired money to Mr. Williams.  0.598013  0.401987
7                  Emma wired money to David.  0.696953  0.303047
8     The princess wired money to the prince.  0.666910  0.333090
9                Sarah wired money to Robert.  0.629175  0.370825
10  Mrs. Williams wired money to  Mr. Taylor.  0.521624  0.478376
11                 Emily wired money to Paul.  0.748382  0.251618

In [103]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_14f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_14f,'He'))

P('subj-pron'|subj=female) =  0.6666835248470306
P('non-subj-pron'|subj=female) =  0.33331649253765744

In [104]:
np_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14f,'She')
np_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14f,'He')

#### male subject

In [105]:
transofposs_perfective_noprompt_14m

                                    stimulus        He       She
12      Mr. Smith wired money to Miss Smith.  0.490071  0.509929
13         The man wired money to the woman.  0.603380  0.396620
14                 John wired money to Mary.  0.668155  0.331845
15                 Bob wired money to Alice.  0.751740  0.248260
16     The actor wired money to the actress.  0.591736  0.408264
17          The boy wired money to the girl.  0.566260  0.433740
18  Mr. William wired money to  Mrs. Taylor.  0.546001  0.453999
19                David wired money to Emma.  0.620537  0.379463
20   The prince wired money to the princess.  0.595530  0.404470
21              Robert wired money to Sarah.  0.663990  0.336010
22  Mr. Taylor wired money to Mrs. Williams.  0.493465  0.506535
23                Paul wired money to Emily.  0.611523  0.388477

In [106]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_14m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_14m,'She'))

P('subj-pron'|subj=male) =  0.60019900649786
P('non-subj-pron'|subj=male) =  0.39980098729332286

In [107]:
np_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14m,'He')
np_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14m,'She')

### verb: "carried"

In [108]:
transofposs_perfective_noprompt_15 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/15.csv")
transofposs_perfective_noprompt_15.head()

                                   stimulus        He       She
0   Miss Smith carried a tray to Mr. Smith.  0.481231  0.518769
1      The woman carried a tray to the man.  0.259691  0.740309
2              Mary carried a tray to John.  0.364605  0.635395
3              Alice carried a tray to Bob.  0.251680  0.748320
4  The actress carried a tray to the actor.  0.227474  0.772526

In [109]:
# female subject
transofposs_perfective_noprompt_15f = transofposs_perfective_noprompt_15[0:12]
transofposs_perfective_noprompt_15f = transofposs_perfective_noprompt_15f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_15m = transofposs_perfective_noprompt_15[12:24]

#### female subject

In [110]:
transofposs_perfective_noprompt_15f

                                        stimulus       She        He
0        Miss Smith carried a tray to Mr. Smith.  0.518769  0.481231
1           The woman carried a tray to the man.  0.740309  0.259691
2                   Mary carried a tray to John.  0.635395  0.364605
3                   Alice carried a tray to Bob.  0.748320  0.251680
4       The actress carried a tray to the actor.  0.772526  0.227474
5            The girl carried a tray to the boy.  0.724136  0.275864
6    Mrs. Taylor carried a tray to Mr. Williams.  0.451424  0.548576
7                  Emma carried a tray to David.  0.709519  0.290481
8     The princess carried a tray to the prince.  0.784144  0.215856
9                Sarah carried a tray to Robert.  0.597394  0.402606
10  Mrs. Williams carried a tray to  Mr. Taylor.  0.411179  0.588821
11                 Emily carried a tray to Paul.  0.777555  0.222445

In [111]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_15f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_15f,'He'))

P('subj-pron'|subj=female) =  0.6558891957004865
P('non-subj-pron'|subj=female) =  0.34411079188187915

In [112]:
np_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15f,'She')
np_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15f,'He')

#### male subject

In [113]:
transofposs_perfective_noprompt_15m

                                       stimulus        He       She
12      Mr. Smith carried a tray to Miss Smith.  0.456015  0.543985
13         The man carried a tray to the woman.  0.594413  0.405587
14                 John carried a tray to Mary.  0.608012  0.391988
15                 Bob carried a tray to Alice.  0.441121  0.558879
16     The actor carried a tray to the actress.  0.627150  0.372850
17          The boy carried a tray to the girl.  0.580658  0.419342
18  Mr. William carried a tray to  Mrs. Taylor.  0.467510  0.532490
19                David carried a tray to Emma.  0.382918  0.617082
20   The prince carried a tray to the princess.  0.569462  0.430538
21              Robert carried a tray to Sarah.  0.462208  0.537792
22  Mr. Taylor carried a tray to Mrs. Williams.  0.494750  0.505250
23                Paul carried a tray to Emily.  0.377317  0.622683

In [114]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_15m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_15m,'She'))

P('subj-pron'|subj=male) =  0.5051278521617254
P('non-subj-pron'|subj=male) =  0.4948721503218015

In [115]:
np_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15m,'He')
np_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15m,'She')

### verb: "delivered"

In [116]:
transofposs_perfective_noprompt_16 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/16.csv")
transofposs_perfective_noprompt_16.head()

                                         stimulus        He       She
0   Miss Smith delivered a subpoena to Mr. Smith.  0.483180  0.516821
1      The woman delivered a subpoena to the man.  0.419504  0.580496
2              Mary delivered a subpoena to John.  0.516951  0.483049
3              Alice delivered a subpoena to Bob.  0.373467  0.626533
4  The actress delivered a subpoena to the actor.  0.199264  0.800736

In [117]:
# female subject
transofposs_perfective_noprompt_16f = transofposs_perfective_noprompt_16[0:12]
transofposs_perfective_noprompt_16f = transofposs_perfective_noprompt_16f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_16m = transofposs_perfective_noprompt_16[12:24]

#### female subject

In [118]:
transofposs_perfective_noprompt_16f

                                             stimulus       She        He
0       Miss Smith delivered a subpoena to Mr. Smith.  0.516821  0.483180
1          The woman delivered a subpoena to the man.  0.580496  0.419504
2                  Mary delivered a subpoena to John.  0.483049  0.516951
3                  Alice delivered a subpoena to Bob.  0.626533  0.373467
4      The actress delivered a subpoena to the actor.  0.800736  0.199264
5           The girl delivered a subpoena to the boy.  0.594500  0.405500
6   Mrs. Taylor delivered a subpoena to Mr. Williams.  0.383506  0.616494
7                 Emma delivered a subpoena to David.  0.501986  0.498014
8    The princess delivered a subpoena to the prince.  0.544286  0.455714
9               Sarah delivered a subpoena to Robert.  0.475001  0.524999
10  Mrs. Williams delivered a subpoena to Mr. Taylor.  0.436689  0.563311
11                Emily delivered a subpoena to Paul.  0.601097  0.398903

In [119]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_16f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_16f,'He'))

P('subj-pron'|subj=female) =  0.5453916316231092
P('non-subj-pron'|subj=female) =  0.45460839197039604

In [120]:
np_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16f,'She')
np_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16f,'He')

#### male subject

In [121]:
transofposs_perfective_noprompt_16m

                                             stimulus        He       She
12      Mr. Smith delivered a subpoena to Miss Smith.  0.412946  0.587054
13         The man delivered a subpoena to the woman.  0.587790  0.412210
14                 John delivered a subpoena to Mary.  0.657367  0.342633
15                 Bob delivered a subpoena to Alice.  0.586368  0.413632
16     The actor delivered a subpoena to the actress.  0.622874  0.377126
17          The boy delivered a subpoena to the girl.  0.597324  0.402676
18   Mr. William delivered a subpoena to Mrs. Taylor.  0.477725  0.522274
19                David delivered a subpoena to Emma.  0.526461  0.473539
20   The prince delivered a subpoena to the princess.  0.544918  0.455082
21              Robert delivered a subpoena to Sarah.  0.618008  0.381992
22  Mr. Taylor delivered a subpoena to Mrs. Williams.  0.470568  0.529432
23                Paul delivered a subpoena to Emily.  0.536492  0.463508

In [122]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_16m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_16m,'She'))

P('subj-pron'|subj=male) =  0.5532369489471117
P('non-subj-pron'|subj=male) =  0.4467630336682002

In [123]:
np_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16m,'He')
np_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16m,'She')

### verb: "gave"

In [124]:
transofposs_perfective_noprompt_17 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/17.csv")
transofposs_perfective_noprompt_17.head()

                                   stimulus        He       She
0   Miss Smith gave a sweater to Mr. Smith.  0.470961  0.529039
1      The woman gave a sweater to the man.  0.406920  0.593080
2              Mary gave a sweater to John.  0.387139  0.612861
3              Alice gave a sweater to Bob.  0.307391  0.692609
4  The actress gave a sweater to the actor.  0.255975  0.744025

In [125]:
# female subject
transofposs_perfective_noprompt_17f = transofposs_perfective_noprompt_17[0:12]
transofposs_perfective_noprompt_17f = transofposs_perfective_noprompt_17f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_17m = transofposs_perfective_noprompt_17[12:24]

#### female subject

In [126]:
transofposs_perfective_noprompt_17f

                                        stimulus       She        He
0        Miss Smith gave a sweater to Mr. Smith.  0.529039  0.470961
1           The woman gave a sweater to the man.  0.593080  0.406920
2                   Mary gave a sweater to John.  0.612861  0.387139
3                   Alice gave a sweater to Bob.  0.692609  0.307391
4       The actress gave a sweater to the actor.  0.744025  0.255975
5            The girl gave a sweater to the boy.  0.589831  0.410169
6    Mrs. Taylor gave a sweater to Mr. Williams.  0.556877  0.443123
7                  Emma gave a sweater to David.  0.646535  0.353465
8     The princess gave a sweater to the prince.  0.599365  0.400635
9                Sarah gave a sweater to Robert.  0.528505  0.471495
10  Mrs. Williams gave a sweater to  Mr. Taylor.  0.449340  0.550660
11                 Emily gave a sweater to Paul.  0.713417  0.286583

In [127]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_17f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_17f,'He'))

P('subj-pron'|subj=female) =  0.6046237250169119
P('non-subj-pron'|subj=female) =  0.39537626256545383

In [128]:
np_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17f,'She')
np_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17f,'He')

#### female subject

In [129]:
transofposs_perfective_noprompt_17m

                                       stimulus        He       She
12      Mr. Smith gave a sweater to Miss Smith.  0.465841  0.534159
13         The man gave a sweater to the woman.  0.494351  0.505649
14                 John gave a sweater to Mary.  0.654021  0.345979
15                 Bob gave a sweater to Alice.  0.520612  0.479388
16     The actor gave a sweater to the actress.  0.599709  0.400291
17          The boy gave a sweater to the girl.  0.471622  0.528378
18  Mr. William gave a sweater to  Mrs. Taylor.  0.534865  0.465135
19                David gave a sweater to Emma.  0.542491  0.457509
20   The prince gave a sweater to the princess.  0.531890  0.468110
21              Robert gave a sweater to Sarah.  0.524382  0.475618
22  Mr. Taylor gave a sweater to Mrs. Williams.  0.530641  0.469359
23                Paul gave a sweater to Emily.  0.536675  0.463325

In [130]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_17m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_17m,'She'))

P('subj-pron'|subj=male) =  0.5339250365893046
P('non-subj-pron'|subj=male) =  0.46607495844364166

In [131]:
np_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17m,'He')
np_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17m,'She')

### verb: "handed"

In [132]:
transofposs_perfective_noprompt_18 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/18.csv")
transofposs_perfective_noprompt_18.head()

                                  stimulus        He       She
0   Miss Smith handed a book to Mr. Smith.  0.652177  0.347823
1      The woman handed a book to the man.  0.469775  0.530225
2              Mary handed a book to John.  0.488221  0.511779
3              Alice handed a book to Bob.  0.409264  0.590736
4  The actress handed a book to the actor.  0.325460  0.674540

In [133]:
# female subject
transofposs_perfective_noprompt_18f = transofposs_perfective_noprompt_18[0:12]
transofposs_perfective_noprompt_18f = transofposs_perfective_noprompt_18f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_18m = transofposs_perfective_noprompt_18[12:24]

#### female subject

In [134]:
transofposs_perfective_noprompt_18f

                                      stimulus       She        He
0       Miss Smith handed a book to Mr. Smith.  0.347823  0.652177
1          The woman handed a book to the man.  0.530225  0.469775
2                  Mary handed a book to John.  0.511779  0.488221
3                  Alice handed a book to Bob.  0.590736  0.409264
4      The actress handed a book to the actor.  0.674540  0.325460
5           The girl handed a book to the boy.  0.496878  0.503122
6   Mrs. Taylor handed a book to Mr. Williams.  0.351605  0.648395
7                 Emma handed a book to David.  0.555649  0.444351
8    The princess handed a book to the prince.  0.609933  0.390067
9               Sarah handed a book to Robert.  0.447762  0.552238
10  Mrs. Williams handed a book to Mr. Taylor.  0.365406  0.634594
11                Emily handed a book to Paul.  0.679751  0.320249

In [135]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_18f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_18f,'He'))

P('subj-pron'|subj=female) =  0.5135072593887647
P('non-subj-pron'|subj=female) =  0.4864927331606547

In [136]:
np_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18f,'She')
np_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18f,'He')

#### male subject

In [137]:
transofposs_perfective_noprompt_18m

                                      stimulus        He       She
12      Mr. Smith handed a book to Miss Smith.  0.362536  0.637464
13         The man handed a book to the woman.  0.410686  0.589314
14                 John handed a book to Mary.  0.574074  0.425926
15                 Bob handed a book to Alice.  0.336554  0.663446
16     The actor handed a book to the actress.  0.460247  0.539753
17          The boy handed a book to the girl.  0.375980  0.624020
18   Mr. William handed a book to Mrs. Taylor.  0.400383  0.599617
19                David handed a book to Emma.  0.404032  0.595968
20   The prince handed a book to the princess.  0.379780  0.620220
21              Robert handed a book to Sarah.  0.398116  0.601884
22  Mr. Taylor handed a book to Mrs. Williams.  0.403259  0.596741
23                Paul handed a book to Emily.  0.451973  0.548027

In [138]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_18m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_18m,'She'))

P('subj-pron'|subj=male) =  0.4131349300344785
P('non-subj-pron'|subj=male) =  0.5868650451302528

In [139]:
np_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18m,'He')
np_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18m,'She')

### verb: "passed"

In [140]:
transofposs_perfective_noprompt_19 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/19.csv")
transofposs_perfective_noprompt_19.head()

                                      stimulus        He       She
0   Miss Smith passed a sandwich to Mr. Smith.  0.648223  0.351777
1      The woman passed a sandwich to the man.  0.493917  0.506083
2              Mary passed a sandwich to John.  0.496135  0.503865
3              Alice passed a sandwich to Bob.  0.415379  0.584621
4  The actress passed a sandwich to the actor.  0.348432  0.651568

In [141]:
# female subject
transofposs_perfective_noprompt_19f = transofposs_perfective_noprompt_19[0:12]
transofposs_perfective_noprompt_19f = transofposs_perfective_noprompt_19f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_19m = transofposs_perfective_noprompt_19[12:24]

#### female subject

In [142]:
transofposs_perfective_noprompt_19f

                                           stimulus       She        He
0        Miss Smith passed a sandwich to Mr. Smith.  0.351777  0.648223
1           The woman passed a sandwich to the man.  0.506083  0.493917
2                   Mary passed a sandwich to John.  0.503865  0.496135
3                   Alice passed a sandwich to Bob.  0.584621  0.415379
4       The actress passed a sandwich to the actor.  0.651568  0.348432
5            The girl passed a sandwich to the boy.  0.511769  0.488231
6    Mrs. Taylor passed a sandwich to Mr. Williams.  0.351884  0.648116
7                  Emma passed a sandwich to David.  0.470960  0.529040
8     The princess passed a sandwich to the prince.  0.512374  0.487626
9                Sarah passed a sandwich to Robert.  0.403037  0.596963
10  Mrs. Williams passed a sandwich to  Mr. Taylor.  0.277560  0.722440
11                 Emily passed a sandwich to Paul.  0.604816  0.395184

In [143]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_19f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_19f,'He'))

P('subj-pron'|subj=female) =  0.47752630958954495
P('non-subj-pron'|subj=female) =  0.5224736755092939

In [144]:
np_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19f,'She')
np_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19f,'He')

#### male subject

In [145]:
transofposs_perfective_noprompt_19m

                                          stimulus        He       She
12      Mr. Smith passed a sandwich to Miss Smith.  0.365907  0.634093
13         The man passed a sandwich to the woman.  0.370059  0.629941
14                 John passed a sandwich to Mary.  0.458146  0.541854
15                 Bob passed a sandwich to Alice.  0.290151  0.709849
16     The actor passed a sandwich to the actress.  0.481380  0.518620
17          The boy passed a sandwich to the girl.  0.382409  0.617591
18  Mr. William passed a sandwich to  Mrs. Taylor.  0.400604  0.599396
19                David passed a sandwich to Emma.  0.358652  0.641348
20   The prince passed a sandwich to the princess.  0.377190  0.622810
21              Robert passed a sandwich to Sarah.  0.380290  0.619710
22  Mr. Taylor passed a sandwich to Mrs. Williams.  0.406463  0.593537
23                Paul passed a sandwich to Emily.  0.371566  0.628434

In [146]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_19m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_19m,'She'))

P('subj-pron'|subj=male) =  0.3869015574455261
P('non-subj-pron'|subj=male) =  0.6130984673897425

In [147]:
np_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19m,'He')
np_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19m,'She')

### verb: "served"

In [148]:
transofposs_perfective_noprompt_20 = pd.read_csv("../results/gpt2/transofposs_perfective/no-prompt/20.csv")
transofposs_perfective_noprompt_20.head()

                                   stimulus        He       She
0   Miss Smith served a chili to Mr. Smith.  0.543349  0.456651
1      The woman served a chili to the man.  0.357687  0.642313
2              Mary served a chili to John.  0.563780  0.436220
3              Alice served a chili to Bob.  0.391608  0.608392
4  The actress served a chili to the actor.  0.261106  0.738894

In [149]:
# female subject
transofposs_perfective_noprompt_20f = transofposs_perfective_noprompt_20[0:12]
transofposs_perfective_noprompt_20f = transofposs_perfective_noprompt_20f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_20m = transofposs_perfective_noprompt_20[12:24]

#### female subject

In [150]:
transofposs_perfective_noprompt_20f

                                       stimulus       She        He
0       Miss Smith served a chili to Mr. Smith.  0.456651  0.543349
1          The woman served a chili to the man.  0.642313  0.357687
2                  Mary served a chili to John.  0.436220  0.563780
3                  Alice served a chili to Bob.  0.608392  0.391608
4      The actress served a chili to the actor.  0.738894  0.261106
5           The girl served a chili to the boy.  0.597510  0.402490
6   Mrs. Taylor served a chili to Mr. Williams.  0.473914  0.526085
7                 Emma served a chili to David.  0.571283  0.428718
8    The princess served a chili to the prince.  0.564775  0.435225
9               Sarah served a chili to Robert.  0.412512  0.587488
10  Mrs. Williams served a chili to Mr. Taylor.  0.462450  0.537550
11                Emily served a chili to Paul.  0.577001  0.422999

In [151]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_20f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_20f,'He'))

P('subj-pron'|subj=female) =  0.5451595336198807
P('non-subj-pron'|subj=female) =  0.4548404837648074

In [152]:
np_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_noprompt_20f,'She')
np_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_noprompt_20f,'He')

#### male subject

In [153]:
transofposs_perfective_noprompt_20m

                                       stimulus        He       She
12      Mr. Smith served a chili to Miss Smith.  0.481749  0.518251
13         The man served a chili to the woman.  0.581119  0.418881
14                 John served a chili to Mary.  0.719889  0.280111
15                 Bob served a chili to Alice.  0.461179  0.538821
16     The actor served a chili to the actress.  0.591574  0.408426
17          The boy served a chili to the girl.  0.519133  0.480867
18  Mr. William served a chili to  Mrs. Taylor.  0.525691  0.474309
19                David served a chili to Emma.  0.497377  0.502624
20   The prince served a chili to the princess.  0.563585  0.436415
21              Robert served a chili to Sarah.  0.543234  0.456766
22  Mr. Taylor served a chili to Mrs. Williams.  0.521337  0.478663
23                Paul served a chili to Emily.  0.459586  0.540413

In [154]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_20m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_20m,'She'))

P('subj-pron'|subj=male) =  0.5387877151370049
P('non-subj-pron'|subj=male) =  0.46121228983004886

In [155]:
np_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_noprompt_20m,'He')
np_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_noprompt_20m,'She')

## Summary of Results

In [156]:
np_results_fsubj_subjpron = pd.DataFrame(list(np_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
np_results_fsubj_objpron = pd.DataFrame(list(np_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
np_results_fsubj = np_results_fsubj_subjpron.merge(np_results_fsubj_objpron)
np_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0         flung              0.478544             0.521456
1        kicked              0.570485             0.429515
2        lobbed              0.616807             0.383193
3         threw              0.575801             0.424199
4        tossed              0.584661             0.415339
5       brought              0.510134             0.489866
6     forwarded              0.676955             0.323045
7        mailed              0.779639             0.220361
8       shipped              0.661974             0.338026
9   transmitted              0.660630             0.339370
10        wired              0.666684             0.333316
11      carried              0.655889             0.344111
12    delivered              0.545392             0.454608
13         gave              0.604624             0.395376
14       handed              0.513507             0.486493
15       passed              0.477526             0.522474
16       served              0.545160             0.454840

In [157]:
np_results_msubj_subjpron = pd.DataFrame(list(np_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
np_results_msubj_objpron = pd.DataFrame(list(np_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
np_results_msubj = np_results_msubj_subjpron.merge(np_results_msubj_objpron)
np_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0         flung            0.372933           0.627067
1        kicked            0.396136           0.603864
2        lobbed            0.382962           0.617038
3        rolled            0.461872           0.538128
4         threw            0.522369           0.477631
5        tossed            0.418724           0.581276
6       brought            0.460866           0.539134
7     forwarded            0.492577           0.507423
8        mailed            0.707842           0.292158
9       shipped            0.510049           0.489951
10  transmitted            0.620536           0.379464
11        wired            0.600199           0.399801
12      carried            0.505128           0.494872
13    delivered            0.553237           0.446763
14         gave            0.533925           0.466075
15       handed            0.413135           0.586865
16       passed            0.386902           0.613098
17       served            0.538788           0.461212

In [158]:
np_results = np_results_fsubj.merge(np_results_msubj)
np_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flung,0.478544,0.521456,0.372933,0.627067
1,kicked,0.570485,0.429515,0.396136,0.603864
2,lobbed,0.616807,0.383193,0.382962,0.617038
3,threw,0.575801,0.424199,0.522369,0.477631
4,tossed,0.584661,0.415339,0.418724,0.581276
5,brought,0.510134,0.489866,0.460866,0.539134
6,forwarded,0.676955,0.323045,0.492577,0.507423
7,mailed,0.779639,0.220361,0.707842,0.292158
8,shipped,0.661974,0.338026,0.510049,0.489951
9,transmitted,0.660630,0.339370,0.620536,0.379464
10,wired,0.666684,0.333316,0.600199,0.399801
11,carried,0.655889,0.344111,0.505128,0.494872
12,delivered,0.545392,0.454608,0.553237,0.446763
13,gave,0.604624,0.395376,0.533925,0.466075
14,handed,0.513507,0.486493,0.413135,0.586865
15,passed,0.477526,0.522474,0.386902,0.613098
16,served,0.545160,0.454840,0.538788,0.461212

In [159]:
print("P(subj_reference |subj=female)", compute_average(np_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(np_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.5955536190201255
P(obj_reference |subj=female) 0.40444637893461716

In [160]:
print("P(subj_reference |subj=male)", compute_average(np_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(np_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.4950769688276684
P(obj_reference |subj=male) 0.5049230297114335

## Connective: "because"

In [161]:
c1_average_subj_female_subj_pron = {}
c1_average_subj_female_obj_pron = {}
c1_average_subj_male_subj_pron = {}
c1_average_subj_male_obj_pron = {}

### verb: "chucked"

In [162]:
transofposs_perfective_connective1_1 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/1.csv")
transofposs_perfective_connective1_1.head()

                                            stimulus        he       she
0   Miss Smith chucked a wrench to Mr. Smith because  0.639876  0.360124
1      The woman chucked a wrench to the man because  0.590443  0.409557
2              Mary chucked a wrench to John because  0.531494  0.468506
3              Alice chucked a wrench to Bob because  0.522532  0.477468
4  The actress chucked a wrench to the actor because  0.515124  0.484876

In [163]:
# female subject
transofposs_perfective_connective1_1f = transofposs_perfective_connective1_1[0:12]
transofposs_perfective_connective1_1f = transofposs_perfective_connective1_1f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_1m = transofposs_perfective_connective1_1[12:24]

#### female subject

In [164]:
transofposs_perfective_connective1_1f

                                             stimulus       she        he
0    Miss Smith chucked a wrench to Mr. Smith because  0.360124  0.639876
1       The woman chucked a wrench to the man because  0.409557  0.590443
2               Mary chucked a wrench to John because  0.468506  0.531494
3               Alice chucked a wrench to Bob because  0.477468  0.522532
4   The actress chucked a wrench to the actor because  0.484876  0.515124
5        The girl chucked a wrench to the boy because  0.520872  0.479128
6   Mrs. Taylor chucked a wrench to Mr. Williams b...  0.315508  0.684492
7              Emma chucked a wrench to David because  0.475492  0.524508
8   The princess chucked a wrench to the prince be...  0.578446  0.421554
9            Sarah chucked a wrench to Robert because  0.382659  0.617341
10  Mrs. Williams chucked a wrench to Mr. Taylor b...  0.339444  0.660556
11             Emily chucked a wrench to Paul because  0.525050  0.474950

In [165]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_1f,'he'))

P('subj-pron'|subj=female) =  0.44483351210753125
P('non-subj-pron'|subj=female) =  0.555166482925415

In [166]:
c1_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1f,'she')
c1_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1f,'he')

#### male subject

In [167]:
transofposs_perfective_connective1_1m

                                             stimulus        he       she
12   Mr. Smith chucked a wrench to Miss Smith because  0.373179  0.626821
13      The man chucked a wrench to the woman because  0.466753  0.533247
14              John chucked a wrench to Mary because  0.442688  0.557312
15              Bob chucked a wrench to Alice because  0.455407  0.544593
16  The actor chucked a wrench to the actress because  0.482217  0.517783
17       The boy chucked a wrench to the girl because  0.490334  0.509666
18  Mr. William chucked a wrench to Mrs. Taylor be...  0.372532  0.627468
19             David chucked a wrench to Emma because  0.412395  0.587605
20  The prince chucked a wrench to the princess be...  0.536609  0.463391
21           Robert chucked a wrench to Sarah because  0.451464  0.548536
22  Mr. Taylor chucked a wrench to Mrs. Williams b...  0.376188  0.623812
23             Paul chucked a wrench to Emily because  0.359390  0.640610

In [168]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_1m,'she'))

P('subj-pron'|subj=male) =  0.43492968877156574
P('non-subj-pron'|subj=male) =  0.5650703112284342

In [169]:
c1_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1m,'he')
c1_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1m,'she')

### verb: "flung"

In [170]:
transofposs_perfective_connective1_2 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/2.csv")
transofposs_perfective_connective1_2.head()

                                           stimulus        he       she
0   Miss Smith flung a frisbee to Mr. Smith because  0.658690  0.341310
1      The woman flung a frisbee to the man because  0.549163  0.450837
2              Mary flung a frisbee to John because  0.487113  0.512887
3              Alice flung a frisbee to Bob because  0.444786  0.555214
4  The actress flung a frisbee to the actor because  0.504795  0.495205

In [171]:
# female subject
transofposs_perfective_connective1_2f = transofposs_perfective_connective1_2[0:12]
transofposs_perfective_connective1_2f = transofposs_perfective_connective1_2f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_2m = transofposs_perfective_connective1_2[12:24]

#### female subject

In [172]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_2f,'he'))

P('subj-pron'|subj=female) =  0.47763560712337494
P('non-subj-pron'|subj=female) =  0.5223643903930982

In [173]:
c1_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_connective1_2f,'she')
c1_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_connective1_2f,'he')

#### male subject

In [174]:
transofposs_perfective_connective1_2m

                                             stimulus        he       she
12    Mr. Smith flung a frisbee to Miss Smith because  0.431580  0.568420
13       The man flung a frisbee to the woman because  0.543088  0.456912
14               John flung a frisbee to Mary because  0.471833  0.528166
15               Bob flung a frisbee to Alice because  0.499146  0.500854
16   The actor flung a frisbee to the actress because  0.567366  0.432634
17        The boy flung a frisbee to the girl because  0.568433  0.431567
18  Mr. William flung a frisbee to  Mrs. Taylor be...  0.404266  0.595734
19              David flung a frisbee to Emma because  0.448237  0.551763
20  The prince flung a frisbee to the princess bec...  0.508608  0.491392
21            Robert flung a frisbee to Sarah because  0.497846  0.502154
22  Mr. Taylor flung a frisbee to Mrs. Williams be...  0.442693  0.557307
23              Paul flung a frisbee to Emily because  0.428744  0.571256

In [175]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_2m,'she'))

P('subj-pron'|subj=male) =  0.4843200047810872
P('non-subj-pron'|subj=male) =  0.5156799852848053

In [176]:
c1_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_connective1_2m,'he')
c1_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_connective1_2m,'she')

### verb: "kicked"

In [177]:
transofposs_perfective_connective1_3 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/3.csv")
transofposs_perfective_connective1_3.head()

                                            stimulus        he       she
0  Miss Smith kicked a soccer ball to Mr. Smith b...  0.603892  0.396108
1  The woman kicked a soccer ball to the man because  0.518599  0.481401
2          Mary kicked a soccer ball to John because  0.388454  0.611546
3          Alice kicked a soccer ball to Bob because  0.381239  0.618761
4  The actress kicked a soccer ball to the actor ...  0.471862  0.528138

In [178]:
# female subject
transofposs_perfective_connective1_3f = transofposs_perfective_connective1_3[0:12]
transofposs_perfective_connective1_3f = transofposs_perfective_connective1_3f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_3m = transofposs_perfective_connective1_3[12:24]

#### female subject

In [179]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_3f,'he'))

P('subj-pron'|subj=female) =  0.5335619101921717
P('non-subj-pron'|subj=female) =  0.46643809229135513

In [180]:
c1_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3f,'she')
c1_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3f,'he')

#### male subject

In [181]:
transofposs_perfective_connective1_3m

                                             stimulus        he       she
12  Mr. Smith kicked a soccer ball to Miss Smith b...  0.435211  0.564789
13  The man kicked a soccer ball to the woman because  0.544661  0.455339
14          John kicked a soccer ball to Mary because  0.440516  0.559484
15          Bob kicked a soccer ball to Alice because  0.477251  0.522749
16  The actor kicked a soccer ball to the actress ...  0.554378  0.445622
17   The boy kicked a soccer ball to the girl because  0.554716  0.445284
18  Mr. William kicked a soccer ball to  Mrs. Tayl...  0.421302  0.578698
19         David kicked a soccer ball to Emma because  0.456953  0.543047
20  The prince kicked a soccer ball to the princes...  0.646541  0.353458
21       Robert kicked a soccer ball to Sarah because  0.478506  0.521494
22  Mr. Taylor kicked a soccer ball to Mrs. Willia...  0.471934  0.528066
23         Paul kicked a soccer ball to Emily because  0.409331  0.590669

In [182]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_3m,'she'))

P('subj-pron'|subj=male) =  0.49094165364901227
P('non-subj-pron'|subj=male) =  0.5090583488345146

In [183]:
c1_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3m,'he')
c1_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3m,'she')

### verb: "lobbed"

In [184]:
transofposs_perfective_connective1_4 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/4.csv")
transofposs_perfective_connective1_4.head()

                                            stimulus        he       she
0  Miss Smith lobbed a football to Mr. Smith because  0.617023  0.382977
1     The woman lobbed a football to the man because  0.612363  0.387637
2             Mary lobbed a football to John because  0.444299  0.555701
3             Alice lobbed a football to Bob because  0.418089  0.581911
4  The actress lobbed a football to the actor bec...  0.511463  0.488537

In [185]:
# female subject
transofposs_perfective_connective1_4f = transofposs_perfective_connective1_4[0:12]
transofposs_perfective_connective1_4f = transofposs_perfective_connective1_4f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_4m = transofposs_perfective_connective1_4[12:24]

#### female subject

In [186]:
transofposs_perfective_connective1_4f

                                             stimulus       she        he
0   Miss Smith lobbed a football to Mr. Smith because  0.382977  0.617023
1      The woman lobbed a football to the man because  0.387637  0.612363
2              Mary lobbed a football to John because  0.555701  0.444299
3              Alice lobbed a football to Bob because  0.581911  0.418089
4   The actress lobbed a football to the actor bec...  0.488537  0.511463
5       The girl lobbed a football to the boy because  0.475941  0.524059
6   Mrs. Taylor lobbed a football to Mr. Williams ...  0.393274  0.606726
7             Emma lobbed a football to David because  0.593863  0.406137
8   The princess lobbed a football to the prince b...  0.525955  0.474045
9           Sarah lobbed a football to Robert because  0.414270  0.585730
10  Mrs. Williams lobbed a football to  Mr. Taylor...  0.319868  0.680132
11            Emily lobbed a football to Paul because  0.604993  0.395007

In [187]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_4f,'he'))

P('subj-pron'|subj=female) =  0.47707729289929074
P('non-subj-pron'|subj=female) =  0.5229226996501287

In [188]:
c1_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4f,'she')
c1_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4f,'he')

#### male subject

In [189]:
transofposs_perfective_connective1_4m

                                             stimulus        he       she
12  Mr. Smith lobbed a football to Miss Smith because  0.432891  0.567109
13     The man lobbed a football to the woman because  0.509249  0.490751
14             John lobbed a football to Mary because  0.457835  0.542165
15             Bob lobbed a football to Alice because  0.477408  0.522592
16  The actor lobbed a football to the actress bec...  0.520037  0.479963
17      The boy lobbed a football to the girl because  0.511875  0.488125
18  Mr. William lobbed a football to  Mrs. Taylor ...  0.439290  0.560710
19            David lobbed a football to Emma because  0.440364  0.559636
20  The prince lobbed a football to the princess b...  0.588100  0.411900
21          Robert lobbed a football to Sarah because  0.512700  0.487300
22  Mr. Taylor lobbed a football to Mrs. Williams ...  0.497837  0.502163
23            Paul lobbed a football to Emily because  0.402616  0.597384

In [190]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_4m,'she'))

P('subj-pron'|subj=male) =  0.48251689225435257
P('non-subj-pron'|subj=male) =  0.5174830953280131

In [191]:
c1_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4m,'he')
c1_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4m,'she')

### verb: "rolled"

In [192]:
transofposs_perfective_connective1_5 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/5.csv")
transofposs_perfective_connective1_5.head()

                                            stimulus        he       she
0  Miss Smith rolled a toy truck to Mr. Smith bec...  0.480421  0.519579
1    The woman rolled a toy truck to the man because  0.449154  0.550846
2            Mary rolled a toy truck to John because  0.392614  0.607386
3            Alice rolled a toy truck to Bob because  0.439861  0.560139
4  The actress rolled a toy truck to the actor be...  0.362135  0.637865

In [193]:
# female subject
transofposs_perfective_connective1_5f = transofposs_perfective_connective1_5[0:12]
transofposs_perfective_connective1_5f = transofposs_perfective_connective1_5[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_5m = transofposs_perfective_connective1_5[12:24]

#### female subject

In [194]:
transofposs_perfective_connective1_5f

                                             stimulus       she        he
0   Miss Smith rolled a toy truck to Mr. Smith bec...  0.519579  0.480421
1     The woman rolled a toy truck to the man because  0.550846  0.449154
2             Mary rolled a toy truck to John because  0.607386  0.392614
3             Alice rolled a toy truck to Bob because  0.560139  0.439861
4   The actress rolled a toy truck to the actor be...  0.637865  0.362135
5      The girl rolled a toy truck to the boy because  0.661639  0.338361
6   Mrs. Taylor rolled a toy truck to Mr. Williams...  0.459979  0.540021
7            Emma rolled a toy truck to David because  0.545876  0.454124
8   The princess rolled a toy truck to the prince ...  0.738856  0.261144
9          Sarah rolled a toy truck to Robert because  0.428791  0.571209
10  Mrs. Williams rolled a toy truck to  Mr. Taylo...  0.418070  0.581930
11           Emily rolled a toy truck to Paul because  0.580990  0.419010
12  Mr. Smith rolled a toy truck to Miss Smith bec...  0.491629  0.508371
13    The man rolled a toy truck to the woman because  0.384826  0.615174
14            John rolled a toy truck to Mary because  0.422538  0.577462
15            Bob rolled a toy truck to Alice because  0.428362  0.571638
16  The actor rolled a toy truck to the actress be...  0.377229  0.622771
17     The boy rolled a toy truck to the girl because  0.378806  0.621194
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.497833  0.502167
19           David rolled a toy truck to Emma because  0.469350  0.530650
20  The prince rolled a toy truck to the princess ...  0.271082  0.728918
21         Robert rolled a toy truck to Sarah because  0.483507  0.516493
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.466314  0.533686
23           Paul rolled a toy truck to Emily because  0.540222  0.459778

In [195]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_5f,'he'))

P('subj-pron'|subj=female) =  0.4967381718258063
P('non-subj-pron'|subj=female) =  0.503261831899484

In [196]:
c1_average_subj_female_subj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5f,'she')
c1_average_subj_female_obj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5f,'he')

#### male subject

In [197]:
transofposs_perfective_connective1_5m

                                             stimulus        he       she
12  Mr. Smith rolled a toy truck to Miss Smith bec...  0.508371  0.491629
13    The man rolled a toy truck to the woman because  0.615174  0.384826
14            John rolled a toy truck to Mary because  0.577462  0.422538
15            Bob rolled a toy truck to Alice because  0.571638  0.428362
16  The actor rolled a toy truck to the actress be...  0.622771  0.377229
17     The boy rolled a toy truck to the girl because  0.621194  0.378806
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.502167  0.497833
19           David rolled a toy truck to Emma because  0.530650  0.469350
20  The prince rolled a toy truck to the princess ...  0.728918  0.271082
21         Robert rolled a toy truck to Sarah because  0.516493  0.483507
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.533686  0.466314
23           Paul rolled a toy truck to Emily because  0.459778  0.540222

In [198]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_5m,'she'))

P('subj-pron'|subj=male) =  0.5656916821996371
P('non-subj-pron'|subj=male) =  0.43430832773447037

In [199]:
c1_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5m,'he')
c1_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5m,'she')

### verb: "threw"

In [200]:
transofposs_perfective_connective1_6 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/6.csv")
transofposs_perfective_connective1_6.head()

                                       stimulus        he       she
0   Miss Smith threw a hat to Mr. Smith because  0.648271  0.351729
1      The woman threw a hat to the man because  0.559165  0.440835
2              Mary threw a hat to John because  0.513368  0.486632
3              Alice threw a hat to Bob because  0.483693  0.516307
4  The actress threw a hat to the actor because  0.540275  0.459725

In [201]:
# female subject
transofposs_perfective_connective1_6f = transofposs_perfective_connective1_6[0:12]
transofposs_perfective_connective1_6f = transofposs_perfective_connective1_6[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_6m = transofposs_perfective_connective1_6[12:24]

#### female subject

In [202]:
transofposs_perfective_connective1_6f

                                            stimulus       she        he
0        Miss Smith threw a hat to Mr. Smith because  0.351729  0.648271
1           The woman threw a hat to the man because  0.440835  0.559165
2                   Mary threw a hat to John because  0.486632  0.513368
3                   Alice threw a hat to Bob because  0.516307  0.483693
4       The actress threw a hat to the actor because  0.459725  0.540275
5            The girl threw a hat to the boy because  0.538417  0.461583
6    Mrs. Taylor threw a hat to Mr. Williams because  0.318785  0.681215
7                  Emma threw a hat to David because  0.485002  0.514998
8     The princess threw a hat to the prince because  0.626009  0.373991
9                Sarah threw a hat to Robert because  0.371210  0.628790
10  Mrs. Williams threw a hat to  Mr. Taylor because  0.251358  0.748642
11                 Emily threw a hat to Paul because  0.538882  0.461118
12       Mr. Smith threw a hat to Miss Smith because  0.579353  0.420647
13          The man threw a hat to the woman because  0.474532  0.525468
14                  John threw a hat to Mary because  0.536828  0.463172
15                  Bob threw a hat to Alice because  0.578561  0.421440
16      The actor threw a hat to the actress because  0.470340  0.529660
17           The boy threw a hat to the girl because  0.467150  0.532850
18   Mr. William threw a hat to  Mrs. Taylor because  0.630110  0.369890
19                 David threw a hat to Emma because  0.651012  0.348988
20    The prince threw a hat to the princess because  0.490317  0.509683
21               Robert threw a hat to Sarah because  0.558088  0.441912
22   Mr. Taylor threw a hat to Mrs. Williams because  0.553077  0.446923
23                 Paul threw a hat to Emily because  0.657389  0.342611

In [203]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_6f,'he'))

P('subj-pron'|subj=female) =  0.5013185925781727
P('non-subj-pron'|subj=female) =  0.4986814111471176

In [204]:
c1_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_connective1_6f,'she')
c1_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_connective1_6f,'he')

#### male subject

In [205]:
transofposs_perfective_connective1_6m

                                           stimulus        he       she
12      Mr. Smith threw a hat to Miss Smith because  0.420647  0.579353
13         The man threw a hat to the woman because  0.525468  0.474532
14                 John threw a hat to Mary because  0.463172  0.536828
15                 Bob threw a hat to Alice because  0.421440  0.578561
16     The actor threw a hat to the actress because  0.529660  0.470340
17          The boy threw a hat to the girl because  0.532850  0.467150
18  Mr. William threw a hat to  Mrs. Taylor because  0.369890  0.630110
19                David threw a hat to Emma because  0.348988  0.651012
20   The prince threw a hat to the princess because  0.509683  0.490317
21              Robert threw a hat to Sarah because  0.441912  0.558088
22  Mr. Taylor threw a hat to Mrs. Williams because  0.446923  0.553077
23                Paul threw a hat to Emily because  0.342611  0.657389

In [206]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_6m,'she'))

P('subj-pron'|subj=male) =  0.44610367218653363
P('non-subj-pron'|subj=male) =  0.5538963228464127

In [207]:
c1_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_connective1_6m,'he')
c1_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_connective1_6m,'she')

### verb: "tossed"

In [208]:
transofposs_perfective_connective1_7 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/7.csv")
transofposs_perfective_connective1_7.head()

                                            stimulus        he       she
0  Miss Smith tossed a dish towel to Mr. Smith be...  0.619380  0.380620
1   The woman tossed a dish towel to the man because  0.526963  0.473037
2           Mary tossed a dish towel to John because  0.415202  0.584798
3           Alice tossed a dish towel to Bob because  0.459634  0.540366
4  The actress tossed a dish towel to the actor b...  0.478520  0.521480

In [209]:
# female subject
transofposs_perfective_connective1_7f = transofposs_perfective_connective1_7[0:12]
transofposs_perfective_connective1_7f = transofposs_perfective_connective1_7f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_7m = transofposs_perfective_connective1_7[12:24]

#### female subject

In [210]:
transofposs_perfective_connective1_7f

                                             stimulus       she        he
0   Miss Smith tossed a dish towel to Mr. Smith be...  0.380620  0.619380
1    The woman tossed a dish towel to the man because  0.473037  0.526963
2            Mary tossed a dish towel to John because  0.584798  0.415202
3            Alice tossed a dish towel to Bob because  0.540366  0.459634
4   The actress tossed a dish towel to the actor b...  0.521480  0.478520
5     The girl tossed a dish towel to the boy because  0.582821  0.417179
6   Mrs. Taylor tossed a dish towel to Mr. William...  0.401527  0.598473
7           Emma tossed a dish towel to David because  0.549258  0.450742
8   The princess tossed a dish towel to the prince...  0.633709  0.366291
9         Sarah tossed a dish towel to Robert because  0.445087  0.554913
10  Mrs. Williams tossed a dish towel to  Mr. Tayl...  0.372694  0.627306
11          Emily tossed a dish towel to Paul because  0.603156  0.396844

In [211]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_7f,'he'))

P('subj-pron'|subj=female) =  0.5073794399698576
P('non-subj-pron'|subj=female) =  0.4926205525795619

In [212]:
c1_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7f,'she')
c1_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7f,'he')

#### male subject

In [213]:
transofposs_perfective_connective1_7m

                                             stimulus        he       she
12  Mr. Smith tossed a dish towel to Miss Smith be...  0.424808  0.575192
13   The man tossed a dish towel to the woman because  0.512400  0.487600
14           John tossed a dish towel to Mary because  0.435768  0.564232
15           Bob tossed a dish towel to Alice because  0.397485  0.602516
16  The actor tossed a dish towel to the actress b...  0.541229  0.458771
17    The boy tossed a dish towel to the girl because  0.520004  0.479996
18  Mr. William tossed a dish towel to  Mrs. Taylo...  0.374885  0.625115
19          David tossed a dish towel to Emma because  0.365106  0.634894
20  The prince tossed a dish towel to the princess...  0.567218  0.432782
21        Robert tossed a dish towel to Sarah because  0.434697  0.565303
22  Mr. Taylor tossed a dish towel to Mrs. William...  0.408192  0.591808
23          Paul tossed a dish towel to Emily because  0.368316  0.631684

In [214]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_7m,'she'))

P('subj-pron'|subj=male) =  0.44584231326977414
P('non-subj-pron'|subj=male) =  0.5541576892137527

In [215]:
c1_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7m,'he')
c1_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7m,'she')

### verb: "brought"

In [216]:
transofposs_perfective_connective1_8 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/8.csv")
transofposs_perfective_connective1_8.head()

                                            stimulus        he       she
0  Miss Smith brought a glass of water to Mr. Smi...  0.652580  0.347420
1  The woman brought a glass of water to the man ...  0.380350  0.619650
2      Mary brought a glass of water to John because  0.366760  0.633240
3      Alice brought a glass of water to Bob because  0.418850  0.581150
4  The actress brought a glass of water to the ac...  0.417099  0.582901

In [217]:
# female subject
transofposs_perfective_connective1_8f = transofposs_perfective_connective1_8[0:12]
transofposs_perfective_connective1_8f = transofposs_perfective_connective1_8f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_8m = transofposs_perfective_connective1_8[12:24]

#### female subject

In [218]:
transofposs_perfective_connective1_8f

                                             stimulus       she        he
0   Miss Smith brought a glass of water to Mr. Smi...  0.347420  0.652580
1   The woman brought a glass of water to the man ...  0.619650  0.380350
2       Mary brought a glass of water to John because  0.633240  0.366760
3       Alice brought a glass of water to Bob because  0.581150  0.418850
4   The actress brought a glass of water to the ac...  0.582901  0.417099
5   The girl brought a glass of water to the boy b...  0.655461  0.344539
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.334697  0.665303
7      Emma brought a glass of water to David because  0.541291  0.458709
8   The princess brought a glass of water to the p...  0.745522  0.254478
9    Sarah brought a glass of water to Robert because  0.438509  0.561490
10  Mrs. Williams brought a glass of water to  Mr....  0.282149  0.717851
11     Emily brought a glass of water to Paul because  0.612343  0.387657

In [219]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_8f,'he'))

P('subj-pron'|subj=female) =  0.5311945304274559
P('non-subj-pron'|subj=female) =  0.468805472056071

In [220]:
c1_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_connective1_8f,'she')
c1_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_connective1_8f,'he')

#### male subject

In [221]:
transofposs_perfective_connective1_8m

                                             stimulus        he       she
12  Mr. Smith brought a glass of water to Miss Smi...  0.437240  0.562760
13  The man brought a glass of water to the woman ...  0.584156  0.415844
14      John brought a glass of water to Mary because  0.483146  0.516854
15      Bob brought a glass of water to Alice because  0.460795  0.539205
16  The actor brought a glass of water to the actr...  0.594283  0.405717
17  The boy brought a glass of water to the girl b...  0.572030  0.427970
18  Mr. William brought a glass of water to  Mrs. ...  0.408708  0.591292
19     David brought a glass of water to Emma because  0.403923  0.596077
20  The prince brought a glass of water to the pri...  0.580177  0.419823
21   Robert brought a glass of water to Sarah because  0.448429  0.551571
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.429355  0.570645
23     Paul brought a glass of water to Emily because  0.410541  0.589459

In [222]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_8m,'she'))

P('subj-pron'|subj=male) =  0.4843985711534818
P('non-subj-pron'|subj=male) =  0.5156014114618301

In [223]:
c1_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_connective1_8m,'he')
c1_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_connective1_8m,'she')

### verb: "forwarded"

In [224]:
transofposs_perfective_connective1_9 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/9.csv")
transofposs_perfective_connective1_9.head()

                                            stimulus        he       she
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.397988  0.602012
1  The woman forwarded a gossipy email to the man...  0.250004  0.749996
2     Mary forwarded a gossipy email to John because  0.348614  0.651386
3     Alice forwarded a gossipy email to Bob because  0.310749  0.689251
4  The actress forwarded a gossipy email to the a...  0.214963  0.785037

In [225]:
# female subject
transofposs_perfective_connective1_9f = transofposs_perfective_connective1_9[0:12]
transofposs_perfective_connective1_9f = transofposs_perfective_connective1_9f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_9m = transofposs_perfective_connective1_9[12:24]

#### female subject

In [226]:
transofposs_perfective_connective1_9f

                                             stimulus       she        he
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.602012  0.397988
1   The woman forwarded a gossipy email to the man...  0.749996  0.250004
2      Mary forwarded a gossipy email to John because  0.651386  0.348614
3      Alice forwarded a gossipy email to Bob because  0.689251  0.310749
4   The actress forwarded a gossipy email to the a...  0.785037  0.214963
5   The girl forwarded a gossipy email to the boy ...  0.760949  0.239051
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.625533  0.374467
7     Emma forwarded a gossipy email to David because  0.601663  0.398337
8   The princess forwarded a gossipy email to the ...  0.806156  0.193844
9   Sarah forwarded a gossipy email to Robert because  0.508065  0.491935
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.511246  0.488754
11    Emily forwarded a gossipy email to Paul because  0.671152  0.328848

In [227]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_9f,'he'))

P('subj-pron'|subj=female) =  0.6635371446609497
P('non-subj-pron'|subj=female) =  0.33646285161376

In [228]:
c1_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9f,'she')
c1_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9f,'he')

#### male subject

In [229]:
transofposs_perfective_connective1_9m

                                             stimulus        he       she
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.486946  0.513054
13  The man forwarded a gossipy email to the woman...  0.669265  0.330735
14     John forwarded a gossipy email to Mary because  0.540781  0.459219
15     Bob forwarded a gossipy email to Alice because  0.551186  0.448814
16  The actor forwarded a gossipy email to the act...  0.589391  0.410609
17  The boy forwarded a gossipy email to the girl ...  0.649708  0.350292
18  Mr. William forwarded a gossipy email to  Mrs....  0.441722  0.558278
19    David forwarded a gossipy email to Emma because  0.480788  0.519212
20  The prince forwarded a gossipy email to the pr...  0.668732  0.331268
21  Robert forwarded a gossipy email to Sarah because  0.543280  0.456720
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.514654  0.485346
23    Paul forwarded a gossipy email to Emily because  0.512620  0.487380

In [230]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_9m,'she'))

P('subj-pron'|subj=male) =  0.5540892978509268
P('non-subj-pron'|subj=male) =  0.44591070463260013

In [231]:
c1_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9m,'he')
c1_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9m,'she')

### verb: "mailed"

In [232]:
transofposs_perfective_connective1_10 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/10.csv")
transofposs_perfective_connective1_10.head()

                                           stimulus        he       she
0   Miss Smith mailed a letter to Mr. Smith because  0.395141  0.604859
1      The woman mailed a letter to the man because  0.258321  0.741679
2              Mary mailed a letter to John because  0.278777  0.721223
3              Alice mailed a letter to Bob because  0.217946  0.782055
4  The actress mailed a letter to the actor because  0.224437  0.775563

In [233]:
# female subject
transofposs_perfective_connective1_10f = transofposs_perfective_connective1_10[0:12]
transofposs_perfective_connective1_10f = transofposs_perfective_connective1_10f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_10m = transofposs_perfective_connective1_10[12:24]

#### female subject

In [234]:
transofposs_perfective_connective1_10f

                                             stimulus       she        he
0     Miss Smith mailed a letter to Mr. Smith because  0.604859  0.395141
1        The woman mailed a letter to the man because  0.741679  0.258321
2                Mary mailed a letter to John because  0.721223  0.278777
3                Alice mailed a letter to Bob because  0.782055  0.217946
4    The actress mailed a letter to the actor because  0.775563  0.224437
5         The girl mailed a letter to the boy because  0.781857  0.218143
6   Mrs. Taylor mailed a letter to Mr. Williams be...  0.604301  0.395699
7               Emma mailed a letter to David because  0.729085  0.270915
8   The princess mailed a letter to the prince bec...  0.833941  0.166059
9             Sarah mailed a letter to Robert because  0.614095  0.385905
10  Mrs. Williams mailed a letter to  Mr. Taylor b...  0.464553  0.535447
11              Emily mailed a letter to Paul because  0.745680  0.254320

In [235]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_10f,'he'))

P('subj-pron'|subj=female) =  0.6999075412750244
P('non-subj-pron'|subj=female) =  0.3000924661755562

In [236]:
c1_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10f,'she')
c1_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10f,'he')

#### male subject

In [237]:
transofposs_perfective_connective1_10m

                                             stimulus        he       she
12    Mr. Smith mailed a letter to Miss Smith because  0.603154  0.396846
13       The man mailed a letter to the woman because  0.770669  0.229331
14               John mailed a letter to Mary because  0.675385  0.324615
15               Bob mailed a letter to Alice because  0.713986  0.286014
16   The actor mailed a letter to the actress because  0.717882  0.282118
17        The boy mailed a letter to the girl because  0.781908  0.218092
18  Mr. William mailed a letter to  Mrs. Taylor be...  0.592245  0.407755
19              David mailed a letter to Emma because  0.632094  0.367906
20  The prince mailed a letter to the princess bec...  0.750944  0.249056
21            Robert mailed a letter to Sarah because  0.657723  0.342277
22  Mr. Taylor mailed a letter to Mrs. Williams be...  0.638384  0.361616
23              Paul mailed a letter to Emily because  0.632240  0.367760

In [238]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_10m,'she'))

P('subj-pron'|subj=male) =  0.6805511564016342
P('non-subj-pron'|subj=male) =  0.3194488274554412

In [239]:
c1_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10m,'he')
c1_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10m,'she')

### verb: "shipped"

In [240]:
transofposs_perfective_connective1_11 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/11.csv")
transofposs_perfective_connective1_11.head()

                                            stimulus        he       she
0  Miss Smith shipped a package to Mr. Smith because  0.488951  0.511049
1     The woman shipped a package to the man because  0.331940  0.668060
2             Mary shipped a package to John because  0.346104  0.653896
3             Alice shipped a package to Bob because  0.344956  0.655044
4  The actress shipped a package to the actor bec...  0.285228  0.714772

In [241]:
# female subject
transofposs_perfective_connective1_11f = transofposs_perfective_connective1_11[0:12]
transofposs_perfective_connective1_11f = transofposs_perfective_connective1_11f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_11m = transofposs_perfective_connective1_11[12:24]

#### female subject

In [242]:
transofposs_perfective_connective1_11f

                                             stimulus       she        he
0   Miss Smith shipped a package to Mr. Smith because  0.511049  0.488951
1      The woman shipped a package to the man because  0.668060  0.331940
2              Mary shipped a package to John because  0.653896  0.346104
3              Alice shipped a package to Bob because  0.655044  0.344956
4   The actress shipped a package to the actor bec...  0.714772  0.285228
5       The girl shipped a package to the boy because  0.685223  0.314777
6   Mrs. Taylor shipped a package to Mr. Williams ...  0.494277  0.505723
7             Emma shipped a package to David because  0.615559  0.384441
8   The princess shipped a package to the prince b...  0.758927  0.241073
9           Sarah shipped a package to Robert because  0.428625  0.571375
10  Mrs. Williams shipped a package to  Mr. Taylor...  0.349029  0.650971
11            Emily shipped a package to Paul because  0.577949  0.422051

In [243]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_11f,'he'))

P('subj-pron'|subj=female) =  0.5927008713285128
P('non-subj-pron'|subj=female) =  0.40729911997914314

In [244]:
c1_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11f,'she')
c1_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11f,'he')

#### male subject

In [245]:
transofposs_perfective_connective1_11m

                                             stimulus        he       she
12  Mr. Smith shipped a package to Miss Smith because  0.512452  0.487548
13     The man shipped a package to the woman because  0.691518  0.308482
14             John shipped a package to Mary because  0.634764  0.365236
15             Bob shipped a package to Alice because  0.658410  0.341590
16  The actor shipped a package to the actress bec...  0.646222  0.353778
17      The boy shipped a package to the girl because  0.683747  0.316253
18  Mr. William shipped a package to  Mrs. Taylor ...  0.478489  0.521511
19            David shipped a package to Emma because  0.559004  0.440996
20  The prince shipped a package to the princess b...  0.723009  0.276991
21          Robert shipped a package to Sarah because  0.570045  0.429955
22  Mr. Taylor shipped a package to Mrs. Williams ...  0.554990  0.445010
23            Paul shipped a package to Emily because  0.580570  0.419430

In [246]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_11m,'she'))

P('subj-pron'|subj=male) =  0.6077684089541435
P('non-subj-pron'|subj=male) =  0.3922315761446953

In [247]:
c1_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11m,'he')
c1_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11m,'she')

### verb: "transmitted"

In [248]:
transofposs_perfective_connective1_12 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/12.csv")
transofposs_perfective_connective1_12.head()

                                            stimulus        he       she
0  Miss Smith transmitted a message to Mr. Smith ...  0.440550  0.559450
1  The woman transmitted a message to the man bec...  0.300831  0.699169
2         Mary transmitted a message to John because  0.328718  0.671282
3         Alice transmitted a message to Bob because  0.263468  0.736532
4  The actress transmitted a message to the actor...  0.214764  0.785236

In [249]:
# female subject
transofposs_perfective_connective1_12f = transofposs_perfective_connective1_12[0:12]
transofposs_perfective_connective1_12f = transofposs_perfective_connective1_12f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_12m = transofposs_perfective_connective1_12[12:24]

#### female subject

In [250]:
transofposs_perfective_connective1_12f

                                             stimulus       she        he
0   Miss Smith transmitted a message to Mr. Smith ...  0.559450  0.440550
1   The woman transmitted a message to the man bec...  0.699169  0.300831
2          Mary transmitted a message to John because  0.671282  0.328718
3          Alice transmitted a message to Bob because  0.736532  0.263468
4   The actress transmitted a message to the actor...  0.785236  0.214764
5   The girl transmitted a message to the boy because  0.721418  0.278582
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.542958  0.457042
7         Emma transmitted a message to David because  0.690840  0.309160
8   The princess transmitted a message to the prin...  0.801872  0.198128
9       Sarah transmitted a message to Robert because  0.576358  0.423642
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.404317  0.595683
11        Emily transmitted a message to Paul because  0.687347  0.312653

In [251]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_12f,'he'))

P('subj-pron'|subj=female) =  0.6563982913891474
P('non-subj-pron'|subj=female) =  0.3436017024020354

In [252]:
c1_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12f,'she')
c1_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12f,'he')

#### male subject

In [253]:
transofposs_perfective_connective1_12m

                                             stimulus        he       she
12  Mr. Smith transmitted a message to Miss Smith ...  0.558174  0.441826
13  The man transmitted a message to the woman bec...  0.673768  0.326232
14         John transmitted a message to Mary because  0.623348  0.376652
15         Bob transmitted a message to Alice because  0.728179  0.271821
16  The actor transmitted a message to the actress...  0.669267  0.330733
17  The boy transmitted a message to the girl because  0.676233  0.323767
18  Mr. William transmitted a message to  Mrs. Tay...  0.529447  0.470553
19        David transmitted a message to Emma because  0.601160  0.398840
20  The prince transmitted a message to the prince...  0.633270  0.366730
21      Robert transmitted a message to Sarah because  0.643230  0.356770
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.598091  0.401909
23        Paul transmitted a message to Emily because  0.660568  0.339432

In [254]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_12m,'she'))

P('subj-pron'|subj=male) =  0.6328944563865662
P('non-subj-pron'|subj=male) =  0.36710553119579953

In [255]:
c1_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12m,'he')
c1_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12m,'she')

### verb: "wired"

In [256]:
transofposs_perfective_connective1_14 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/14.csv")
transofposs_perfective_connective1_14.head()

                                       stimulus        he       she
0   Miss Smith wired money to Mr. Smith because  0.452100  0.547900
1      The woman wired money to the man because  0.397514  0.602486
2              Mary wired money to John because  0.349961  0.650039
3              Alice wired money to Bob because  0.280527  0.719473
4  The actress wired money to the actor because  0.286160  0.713840

In [257]:
# female subject
transofposs_perfective_connective1_14f = transofposs_perfective_connective1_14[0:12]
transofposs_perfective_connective1_14f = transofposs_perfective_connective1_14f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_14m = transofposs_perfective_connective1_14[12:24]

#### female subject

In [258]:
transofposs_perfective_connective1_14f

                                            stimulus       she        he
0        Miss Smith wired money to Mr. Smith because  0.547900  0.452100
1           The woman wired money to the man because  0.602486  0.397514
2                   Mary wired money to John because  0.650039  0.349961
3                   Alice wired money to Bob because  0.719473  0.280527
4       The actress wired money to the actor because  0.713840  0.286160
5            The girl wired money to the boy because  0.651453  0.348547
6    Mrs. Taylor wired money to Mr. Williams because  0.565797  0.434203
7                  Emma wired money to David because  0.685354  0.314646
8     The princess wired money to the prince because  0.724231  0.275769
9                Sarah wired money to Robert because  0.509585  0.490415
10  Mrs. Williams wired money to  Mr. Taylor because  0.376582  0.623418
11                 Emily wired money to Paul because  0.639353  0.360647

In [259]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_14f,'he'))

P('subj-pron'|subj=female) =  0.615507630010446
P('non-subj-pron'|subj=female) =  0.38449235757191974

In [260]:
c1_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_connective1_14f,'she')
c1_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_connective1_14f,'he')

#### male subject

In [261]:
transofposs_perfective_connective1_14m

                                           stimulus        he       she
12      Mr. Smith wired money to Miss Smith because  0.493052  0.506948
13         The man wired money to the woman because  0.624611  0.375389
14                 John wired money to Mary because  0.558387  0.441613
15                 Bob wired money to Alice because  0.738938  0.261062
16     The actor wired money to the actress because  0.619310  0.380690
17          The boy wired money to the girl because  0.653045  0.346955
18  Mr. William wired money to  Mrs. Taylor because  0.472248  0.527752
19                David wired money to Emma because  0.538613  0.461387
20   The prince wired money to the princess because  0.662307  0.337693
21              Robert wired money to Sarah because  0.573202  0.426798
22  Mr. Taylor wired money to Mrs. Williams because  0.567941  0.432059
23                Paul wired money to Emily because  0.545155  0.454845

In [262]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_14m,'she'))

P('subj-pron'|subj=male) =  0.5872340152661005
P('non-subj-pron'|subj=male) =  0.4127659897009532

In [263]:
c1_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_connective1_14m,'he')
c1_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_connective1_14m,'she')

### verb: "carried"

In [264]:
transofposs_perfective_connective1_15 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/15.csv")
transofposs_perfective_connective1_15.head()

                                          stimulus        he       she
0   Miss Smith carried a tray to Mr. Smith because  0.552488  0.447512
1      The woman carried a tray to the man because  0.323292  0.676708
2              Mary carried a tray to John because  0.382095  0.617905
3              Alice carried a tray to Bob because  0.366435  0.633565
4  The actress carried a tray to the actor because  0.328303  0.671697

In [265]:
# female subject
transofposs_perfective_connective1_15f = transofposs_perfective_connective1_15[0:12]
transofposs_perfective_connective1_15f = transofposs_perfective_connective1_15f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_15m = transofposs_perfective_connective1_15[12:24]

#### female subject

In [266]:
transofposs_perfective_connective1_15f

                                             stimulus       she        he
0      Miss Smith carried a tray to Mr. Smith because  0.447512  0.552488
1         The woman carried a tray to the man because  0.676708  0.323292
2                 Mary carried a tray to John because  0.617905  0.382095
3                 Alice carried a tray to Bob because  0.633565  0.366435
4     The actress carried a tray to the actor because  0.671697  0.328303
5          The girl carried a tray to the boy because  0.663039  0.336961
6   Mrs. Taylor carried a tray to Mr. Williams bec...  0.378546  0.621454
7                Emma carried a tray to David because  0.579206  0.420794
8   The princess carried a tray to the prince because  0.788407  0.211593
9              Sarah carried a tray to Robert because  0.455072  0.544928
10  Mrs. Williams carried a tray to  Mr. Taylor be...  0.312616  0.687384
11               Emily carried a tray to Paul because  0.606229  0.393771

In [267]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_15f,'he'))

P('subj-pron'|subj=female) =  0.5692086120446523
P('non-subj-pron'|subj=female) =  0.43079140906532604

In [268]:
c1_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_connective1_15f,'she')
c1_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_connective1_15f,'he')

#### male subject

In [269]:
transofposs_perfective_connective1_15m

                                             stimulus        he       she
12     Mr. Smith carried a tray to Miss Smith because  0.458175  0.541825
13        The man carried a tray to the woman because  0.579126  0.420874
14                John carried a tray to Mary because  0.493487  0.506513
15                Bob carried a tray to Alice because  0.496082  0.503918
16    The actor carried a tray to the actress because  0.632593  0.367407
17         The boy carried a tray to the girl because  0.567377  0.432623
18  Mr. William carried a tray to  Mrs. Taylor bec...  0.403052  0.596948
19               David carried a tray to Emma because  0.426210  0.573790
20  The prince carried a tray to the princess because  0.572122  0.427878
21             Robert carried a tray to Sarah because  0.465839  0.534161
22  Mr. Taylor carried a tray to Mrs. Williams bec...  0.439914  0.560086
23               Paul carried a tray to Emily because  0.400106  0.599894

In [270]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_15m,'she'))

P('subj-pron'|subj=male) =  0.49450699736674625
P('non-subj-pron'|subj=male) =  0.5054930051167806

In [271]:
c1_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_connective1_15m,'he')
c1_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_connective1_15m,'she')

### verb: "delivered"

In [272]:
transofposs_perfective_connective1_16 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/16.csv")
transofposs_perfective_connective1_16.head()

                                            stimulus        he       she
0  Miss Smith delivered a subpoena to Mr. Smith b...  0.565621  0.434379
1  The woman delivered a subpoena to the man because  0.468351  0.531649
2          Mary delivered a subpoena to John because  0.557842  0.442158
3          Alice delivered a subpoena to Bob because  0.442191  0.557809
4  The actress delivered a subpoena to the actor ...  0.277455  0.722545

In [273]:
# female subject
transofposs_perfective_connective1_16f = transofposs_perfective_connective1_16[0:12]
transofposs_perfective_connective1_16f = transofposs_perfective_connective1_16f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_16m = transofposs_perfective_connective1_16[12:24]

#### female subject

In [274]:
transofposs_perfective_connective1_16f

                                             stimulus       she        he
0   Miss Smith delivered a subpoena to Mr. Smith b...  0.434379  0.565621
1   The woman delivered a subpoena to the man because  0.531649  0.468351
2           Mary delivered a subpoena to John because  0.442158  0.557842
3           Alice delivered a subpoena to Bob because  0.557809  0.442191
4   The actress delivered a subpoena to the actor ...  0.722545  0.277455
5    The girl delivered a subpoena to the boy because  0.550735  0.449265
6   Mrs. Taylor delivered a subpoena to Mr. Willia...  0.424344  0.575656
7          Emma delivered a subpoena to David because  0.465448  0.534552
8   The princess delivered a subpoena to the princ...  0.654799  0.345201
9        Sarah delivered a subpoena to Robert because  0.363241  0.636759
10  Mrs. Williams delivered a subpoena to Mr. Tayl...  0.432762  0.567238
11         Emily delivered a subpoena to Paul because  0.528758  0.471242

In [275]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_16f,'he'))

P('subj-pron'|subj=female) =  0.5090522766113281
P('non-subj-pron'|subj=female) =  0.4909477159380913

In [276]:
c1_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16f,'she')
c1_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16f,'he')

#### male subject

In [277]:
transofposs_perfective_connective1_16m

                                             stimulus        he       she
12  Mr. Smith delivered a subpoena to Miss Smith b...  0.455331  0.544669
13  The man delivered a subpoena to the woman because  0.490283  0.509717
14          John delivered a subpoena to Mary because  0.444710  0.555290
15          Bob delivered a subpoena to Alice because  0.551915  0.448085
16  The actor delivered a subpoena to the actress ...  0.536457  0.463543
17   The boy delivered a subpoena to the girl because  0.505837  0.494163
18  Mr. William delivered a subpoena to Mrs. Taylo...  0.473159  0.526841
19         David delivered a subpoena to Emma because  0.424524  0.575476
20  The prince delivered a subpoena to the princes...  0.498104  0.501896
21       Robert delivered a subpoena to Sarah because  0.447896  0.552104
22  Mr. Taylor delivered a subpoena to Mrs. Willia...  0.481265  0.518735
23         Paul delivered a subpoena to Emily because  0.405882  0.594118

In [278]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_16m,'she'))

P('subj-pron'|subj=male) =  0.4762802595893542
P('non-subj-pron'|subj=male) =  0.5237197453776995

In [279]:
c1_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16m,'he')
c1_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16m,'she')

### verb: "gave"

In [280]:
transofposs_perfective_connective1_17 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/17.csv")
transofposs_perfective_connective1_17.head()

                                          stimulus        he       she
0   Miss Smith gave a sweater to Mr. Smith because  0.632432  0.367568
1      The woman gave a sweater to the man because  0.516092  0.483909
2              Mary gave a sweater to John because  0.383734  0.616266
3              Alice gave a sweater to Bob because  0.403254  0.596746
4  The actress gave a sweater to the actor because  0.462795  0.537205

In [281]:
# female subject
transofposs_perfective_connective1_17f = transofposs_perfective_connective1_17[0:12]
transofposs_perfective_connective1_17f = transofposs_perfective_connective1_17f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_17m = transofposs_perfective_connective1_17[12:24]

#### female subject

In [282]:
transofposs_perfective_connective1_17f

                                             stimulus       she        he
0      Miss Smith gave a sweater to Mr. Smith because  0.367568  0.632432
1         The woman gave a sweater to the man because  0.483909  0.516092
2                 Mary gave a sweater to John because  0.616266  0.383734
3                 Alice gave a sweater to Bob because  0.596746  0.403254
4     The actress gave a sweater to the actor because  0.537205  0.462795
5          The girl gave a sweater to the boy because  0.543047  0.456953
6   Mrs. Taylor gave a sweater to Mr. Williams bec...  0.379580  0.620420
7                Emma gave a sweater to David because  0.555065  0.444935
8   The princess gave a sweater to the prince because  0.629919  0.370081
9              Sarah gave a sweater to Robert because  0.432173  0.567827
10  Mrs. Williams gave a sweater to  Mr. Taylor be...  0.332763  0.667237
11               Emily gave a sweater to Paul because  0.607670  0.392330

In [283]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_17f,'he'))

P('subj-pron'|subj=female) =  0.5068258518973986
P('non-subj-pron'|subj=female) =  0.49317414313554764

In [284]:
c1_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_connective1_17f,'she')
c1_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_connective1_17f,'he')

#### male subject

In [285]:
transofposs_perfective_connective1_17m

                                             stimulus        he       she
12     Mr. Smith gave a sweater to Miss Smith because  0.431825  0.568175
13        The man gave a sweater to the woman because  0.525709  0.474291
14                John gave a sweater to Mary because  0.466845  0.533155
15                Bob gave a sweater to Alice because  0.447876  0.552124
16    The actor gave a sweater to the actress because  0.559999  0.440001
17         The boy gave a sweater to the girl because  0.510075  0.489925
18  Mr. William gave a sweater to  Mrs. Taylor bec...  0.430241  0.569759
19               David gave a sweater to Emma because  0.357297  0.642703
20  The prince gave a sweater to the princess because  0.567210  0.432790
21             Robert gave a sweater to Sarah because  0.421306  0.578694
22  Mr. Taylor gave a sweater to Mrs. Williams bec...  0.465878  0.534122
23               Paul gave a sweater to Emily because  0.343919  0.656081

In [286]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_17m,'she'))

P('subj-pron'|subj=male) =  0.4606816694140434
P('non-subj-pron'|subj=male) =  0.5393183355530103

In [287]:
c1_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_connective1_17m,'he')
c1_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_connective1_17m,'she')

### verb: "handed"

In [288]:
transofposs_perfective_connective1_18 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/18.csv")
transofposs_perfective_connective1_18.head()

                                         stimulus        he       she
0   Miss Smith handed a book to Mr. Smith because  0.563633  0.436367
1      The woman handed a book to the man because  0.435498  0.564502
2              Mary handed a book to John because  0.361678  0.638322
3              Alice handed a book to Bob because  0.369905  0.630095
4  The actress handed a book to the actor because  0.396144  0.603856

In [289]:
# female subject
transofposs_perfective_connective1_18f = transofposs_perfective_connective1_18[0:12]
transofposs_perfective_connective1_18f = transofposs_perfective_connective1_18f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_18m = transofposs_perfective_connective1_18[12:24]

#### female subject

In [290]:
transofposs_perfective_connective1_18f

                                             stimulus       she        he
0       Miss Smith handed a book to Mr. Smith because  0.436367  0.563633
1          The woman handed a book to the man because  0.564502  0.435498
2                  Mary handed a book to John because  0.638322  0.361678
3                  Alice handed a book to Bob because  0.630095  0.369905
4      The actress handed a book to the actor because  0.603856  0.396144
5           The girl handed a book to the boy because  0.579762  0.420239
6   Mrs. Taylor handed a book to Mr. Williams because  0.427463  0.572537
7                 Emma handed a book to David because  0.581344  0.418656
8    The princess handed a book to the prince because  0.772781  0.227219
9               Sarah handed a book to Robert because  0.426171  0.573829
10  Mrs. Williams handed a book to Mr. Taylor because  0.456013  0.543988
11                Emily handed a book to Paul because  0.649845  0.350155

In [291]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_18f,'he'))

P('subj-pron'|subj=female) =  0.5638768126567205
P('non-subj-pron'|subj=female) =  0.43612319976091385

In [292]:
c1_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_connective1_18f,'she')
c1_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_connective1_18f,'he')

#### male subject

In [293]:
transofposs_perfective_connective1_18m

                                             stimulus        he       she
12      Mr. Smith handed a book to Miss Smith because  0.462046  0.537954
13         The man handed a book to the woman because  0.568403  0.431597
14                 John handed a book to Mary because  0.497937  0.502063
15                 Bob handed a book to Alice because  0.530046  0.469954
16     The actor handed a book to the actress because  0.578492  0.421508
17          The boy handed a book to the girl because  0.576432  0.423568
18   Mr. William handed a book to Mrs. Taylor because  0.441534  0.558466
19                David handed a book to Emma because  0.418993  0.581007
20   The prince handed a book to the princess because  0.619435  0.380565
21              Robert handed a book to Sarah because  0.449519  0.550481
22  Mr. Taylor handed a book to Mrs. Williams because  0.463836  0.536164
23                Paul handed a book to Emily because  0.424314  0.575686

In [294]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_18m,'she'))

P('subj-pron'|subj=male) =  0.5025822420914968
P('non-subj-pron'|subj=male) =  0.49741777032613754

In [295]:
c1_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_connective1_18m,'he')
c1_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_connective1_18m,'she')

### verb: "passed"

In [296]:
transofposs_perfective_connective1_19 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/19.csv")
transofposs_perfective_connective1_19.head()

                                            stimulus        he       she
0  Miss Smith passed a sandwich to Mr. Smith because  0.569860  0.430140
1     The woman passed a sandwich to the man because  0.473426  0.526574
2             Mary passed a sandwich to John because  0.481536  0.518464
3             Alice passed a sandwich to Bob because  0.469690  0.530310
4  The actress passed a sandwich to the actor bec...  0.416366  0.583634

In [297]:
# female subject
transofposs_perfective_connective1_19f = transofposs_perfective_connective1_19[0:12]
transofposs_perfective_connective1_19f = transofposs_perfective_connective1_19f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_19m = transofposs_perfective_connective1_19[12:24]

#### female subject

In [298]:
transofposs_perfective_connective1_19f

                                             stimulus       she        he
0   Miss Smith passed a sandwich to Mr. Smith because  0.430140  0.569860
1      The woman passed a sandwich to the man because  0.526574  0.473426
2              Mary passed a sandwich to John because  0.518464  0.481536
3              Alice passed a sandwich to Bob because  0.530310  0.469690
4   The actress passed a sandwich to the actor bec...  0.583634  0.416366
5       The girl passed a sandwich to the boy because  0.543754  0.456246
6   Mrs. Taylor passed a sandwich to Mr. Williams ...  0.324777  0.675223
7             Emma passed a sandwich to David because  0.447859  0.552141
8   The princess passed a sandwich to the prince b...  0.653045  0.346955
9           Sarah passed a sandwich to Robert because  0.369298  0.630702
10  Mrs. Williams passed a sandwich to  Mr. Taylor...  0.235059  0.764941
11            Emily passed a sandwich to Paul because  0.503258  0.496742

In [299]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_19f,'he'))

P('subj-pron'|subj=female) =  0.47218088433146477
P('non-subj-pron'|subj=female) =  0.5278191169102987

In [300]:
c1_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_connective1_19f,'she')
c1_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_connective1_19f,'he')

#### male subject

In [301]:
transofposs_perfective_connective1_19m

                                             stimulus        he       she
12  Mr. Smith passed a sandwich to Miss Smith because  0.447580  0.552420
13     The man passed a sandwich to the woman because  0.538721  0.461279
14             John passed a sandwich to Mary because  0.460206  0.539794
15             Bob passed a sandwich to Alice because  0.451258  0.548742
16  The actor passed a sandwich to the actress bec...  0.630387  0.369613
17      The boy passed a sandwich to the girl because  0.520485  0.479515
18  Mr. William passed a sandwich to  Mrs. Taylor ...  0.363793  0.636207
19            David passed a sandwich to Emma because  0.391572  0.608428
20  The prince passed a sandwich to the princess b...  0.550263  0.449737
21          Robert passed a sandwich to Sarah because  0.440948  0.559052
22  Mr. Taylor passed a sandwich to Mrs. Williams ...  0.440001  0.559999
23            Paul passed a sandwich to Emily because  0.393174  0.606825

In [302]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_19m,'she'))

P('subj-pron'|subj=male) =  0.4690323819716771
P('non-subj-pron'|subj=male) =  0.5309676130612692

In [303]:
c1_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_connective1_19m,'he')
c1_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_connective1_19m,'she')

### verb: "served"

In [304]:
transofposs_perfective_connective1_20 = pd.read_csv("../results/gpt2/transofposs_perfective/connective1/20.csv")
transofposs_perfective_connective1_20.head()

                                          stimulus        he       she
0   Miss Smith served a chili to Mr. Smith because  0.669316  0.330684
1      The woman served a chili to the man because  0.509128  0.490872
2              Mary served a chili to John because  0.531176  0.468824
3              Alice served a chili to Bob because  0.572006  0.427994
4  The actress served a chili to the actor because  0.508717  0.491283

In [305]:
# female subject
transofposs_perfective_connective1_20f = transofposs_perfective_connective1_20[0:12]
transofposs_perfective_connective1_20f = transofposs_perfective_connective1_20f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_20m = transofposs_perfective_connective1_20[12:24]

#### female subject

In [306]:
transofposs_perfective_connective1_20f

                                             stimulus       she        he
0      Miss Smith served a chili to Mr. Smith because  0.330684  0.669316
1         The woman served a chili to the man because  0.490872  0.509128
2                 Mary served a chili to John because  0.468824  0.531176
3                 Alice served a chili to Bob because  0.427994  0.572006
4     The actress served a chili to the actor because  0.491283  0.508717
5          The girl served a chili to the boy because  0.495528  0.504472
6   Mrs. Taylor served a chili to Mr. Williams bec...  0.369094  0.630906
7                Emma served a chili to David because  0.469211  0.530789
8   The princess served a chili to the prince because  0.595426  0.404574
9              Sarah served a chili to Robert because  0.341492  0.658508
10  Mrs. Williams served a chili to Mr. Taylor bec...  0.357741  0.642259
11               Emily served a chili to Paul because  0.471892  0.528108

In [307]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_20f,'he'))

P('subj-pron'|subj=female) =  0.4425035019715627
P('non-subj-pron'|subj=female) =  0.5574964880943298

In [308]:
c1_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_connective1_20f,'she')
c1_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_connective1_20f,'he')

#### male subject

In [309]:
transofposs_perfective_connective1_20m

                                             stimulus        he       she
12     Mr. Smith served a chili to Miss Smith because  0.434922  0.565078
13        The man served a chili to the woman because  0.526851  0.473149
14                John served a chili to Mary because  0.503889  0.496111
15                Bob served a chili to Alice because  0.459592  0.540408
16    The actor served a chili to the actress because  0.543007  0.456993
17         The boy served a chili to the girl because  0.489804  0.510196
18  Mr. William served a chili to  Mrs. Taylor bec...  0.415985  0.584015
19               David served a chili to Emma because  0.411180  0.588820
20  The prince served a chili to the princess because  0.588900  0.411100
21             Robert served a chili to Sarah because  0.462974  0.537026
22  Mr. Taylor served a chili to Mrs. Williams bec...  0.496065  0.503935
23               Paul served a chili to Emily because  0.384223  0.615777

In [310]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_20m,'she'))

P('subj-pron'|subj=male) =  0.47644935299952823
P('non-subj-pron'|subj=male) =  0.5235506395498911

In [311]:
c1_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_connective1_20m,'he')
c1_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_connective1_20m,'she')

## Summary of Results

In [312]:
c1_results_fsubj_subjpron = pd.DataFrame(list(c1_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c1_results_fsubj_objpron = pd.DataFrame(list(c1_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c1_results_fsubj = c1_results_fsubj_subjpron.merge(c1_results_fsubj_objpron)
c1_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0       chucked              0.444834             0.555166
1         flung              0.477636             0.522364
2        kicked              0.533562             0.466438
3        lobbed              0.477077             0.522923
4        rolled              0.496738             0.503262
5         threw              0.501319             0.498681
6        tossed              0.507379             0.492621
7       brought              0.531195             0.468805
8     forwarded              0.663537             0.336463
9        mailed              0.699908             0.300092
10      shipped              0.592701             0.407299
11  transmitted              0.656398             0.343602
12        wired              0.615508             0.384492
13      carried              0.569209             0.430791
14    delivered              0.509052             0.490948
15         gave              0.506826             0.493174
16       handed              0.563877             0.436123
17       passed              0.472181             0.527819
18       served              0.442504             0.557496

In [313]:
c1_results_msubj_subjpron = pd.DataFrame(list(c1_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c1_results_msubj_objpron = pd.DataFrame(list(c1_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c1_results_msubj = c1_results_msubj_subjpron.merge(c1_results_msubj_objpron)
c1_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0       chucked            0.434930           0.565070
1         flung            0.484320           0.515680
2        kicked            0.490942           0.509058
3        lobbed            0.482517           0.517483
4        rolled            0.565692           0.434308
5         threw            0.446104           0.553896
6        tossed            0.445842           0.554158
7       brought            0.484399           0.515601
8     forwarded            0.554089           0.445911
9        mailed            0.680551           0.319449
10      shipped            0.607768           0.392232
11  transmitted            0.632894           0.367106
12        wired            0.587234           0.412766
13      carried            0.494507           0.505493
14    delivered            0.476280           0.523720
15         gave            0.460682           0.539318
16       handed            0.502582           0.497418
17       passed            0.469032           0.530968
18       served            0.476449           0.523551

In [314]:
c1_results = c1_results_fsubj.merge(c1_results_msubj)
c1_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,chucked,0.444834,0.555166,0.434930,0.565070
1,flung,0.477636,0.522364,0.484320,0.515680
2,kicked,0.533562,0.466438,0.490942,0.509058
3,lobbed,0.477077,0.522923,0.482517,0.517483
4,rolled,0.496738,0.503262,0.565692,0.434308
5,threw,0.501319,0.498681,0.446104,0.553896
6,tossed,0.507379,0.492621,0.445842,0.554158
7,brought,0.531195,0.468805,0.484399,0.515601
8,forwarded,0.663537,0.336463,0.554089,0.445911
9,mailed,0.699908,0.300092,0.680551,0.319449
10,shipped,0.592701,0.407299,0.607768,0.392232
11,transmitted,0.656398,0.343602,0.632894,0.367106
12,wired,0.615508,0.384492,0.587234,0.412766
13,carried,0.569209,0.430791,0.494507,0.505493
14,delivered,0.509052,0.490948,0.476280,0.523720
15,gave,0.506826,0.493174,0.460682,0.539318
16,handed,0.563877,0.436123,0.502582,0.497418
17,passed,0.472181,0.527819,0.469032,0.530968
18,served,0.442504,0.557496,0.476449,0.523551

In [315]:
print("P(subj_reference |subj=female)", compute_average(c1_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c1_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.5400757092263616
P(obj_reference |subj=female) 0.459924289662587

In [316]:
print("P(subj_reference |subj=male)", compute_average(c1_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c1_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.5145691956082981
P(obj_reference |subj=male) 0.4854308015813953

## Connective: "and, as a result"

In [317]:
c2_average_subj_female_subj_pron = {}
c2_average_subj_female_obj_pron = {}
c2_average_subj_male_subj_pron = {}
c2_average_subj_male_obj_pron = {}

### verb: "chucked"

In [318]:
transofposs_perfective_connective2_1 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/1.csv")
transofposs_perfective_connective2_1.head()

                                            stimulus        he       she
0  Miss Smith chucked a wrench to Mr. Smith and, ...  0.869201  0.130799
1  The woman chucked a wrench to the man and, as ...  0.872781  0.127219
2    Mary chucked a wrench to John and, as a result,  0.744466  0.255534
3    Alice chucked a wrench to Bob and, as a result,  0.592181  0.407819
4  The actress chucked a wrench to the actor and,...  0.767162  0.232838

In [319]:
# female subject
transofposs_perfective_connective2_1f = transofposs_perfective_connective2_1[0:12]
transofposs_perfective_connective2_1f = transofposs_perfective_connective2_1f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_1m = transofposs_perfective_connective2_1[12:24]

#### female subject

In [320]:
transofposs_perfective_connective2_1f

                                             stimulus       she        he
0   Miss Smith chucked a wrench to Mr. Smith and, ...  0.130799  0.869201
1   The woman chucked a wrench to the man and, as ...  0.127219  0.872781
2     Mary chucked a wrench to John and, as a result,  0.255534  0.744466
3     Alice chucked a wrench to Bob and, as a result,  0.407819  0.592181
4   The actress chucked a wrench to the actor and,...  0.232838  0.767162
5   The girl chucked a wrench to the boy and, as a...  0.234239  0.765761
6   Mrs. Taylor chucked a wrench to Mr. Williams a...  0.197641  0.802359
7    Emma chucked a wrench to David and, as a result,  0.320233  0.679767
8   The princess chucked a wrench to the prince an...  0.254031  0.745969
9   Sarah chucked a wrench to Robert and, as a res...  0.256081  0.743919
10  Mrs. Williams chucked a wrench to Mr. Taylor a...  0.227594  0.772406
11   Emily chucked a wrench to Paul and, as a result,  0.364018  0.635982

In [321]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_1f,'he'))

P('subj-pron'|subj=female) =  0.2506703572968642
P('non-subj-pron'|subj=female) =  0.7493296414613724

In [322]:
c2_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1f,'she')
c2_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1f,'he')

#### male subject

In [323]:
transofposs_perfective_connective2_1m

                                             stimulus        he       she
12  Mr. Smith chucked a wrench to Miss Smith and, ...  0.288709  0.711291
13  The man chucked a wrench to the woman and, as ...  0.161556  0.838444
14    John chucked a wrench to Mary and, as a result,  0.219767  0.780233
15    Bob chucked a wrench to Alice and, as a result,  0.159978  0.840022
16  The actor chucked a wrench to the actress and,...  0.189689  0.810311
17  The boy chucked a wrench to the girl and, as a...  0.207310  0.792690
18  Mr. William chucked a wrench to Mrs. Taylor an...  0.244483  0.755517
19   David chucked a wrench to Emma and, as a result,  0.242257  0.757743
20  The prince chucked a wrench to the princess an...  0.216610  0.783390
21  Robert chucked a wrench to Sarah and, as a res...  0.223398  0.776602
22  Mr. Taylor chucked a wrench to Mrs. Williams a...  0.241027  0.758973
23   Paul chucked a wrench to Emily and, as a result,  0.172970  0.827030

In [324]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_1m,'she'))

P('subj-pron'|subj=male) =  0.21397945657372475
P('non-subj-pron'|subj=male) =  0.7860205421845118

In [325]:
c2_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1m,'he')
c2_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1m,'she')

### verb: "flung"

In [326]:
transofposs_perfective_connective2_2 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/2.csv")
transofposs_perfective_connective2_2.head()

                                            stimulus        he       she
0  Miss Smith flung a frisbee to Mr. Smith and, a...  0.799324  0.200676
1  The woman flung a frisbee to the man and, as a...  0.800228  0.199772
2     Mary flung a frisbee to John and, as a result,  0.743974  0.256026
3     Alice flung a frisbee to Bob and, as a result,  0.568398  0.431601
4  The actress flung a frisbee to the actor and, ...  0.739711  0.260289

In [327]:
# female subject
transofposs_perfective_connective2_2f = transofposs_perfective_connective2_2[0:12]
transofposs_perfective_connective2_2f = transofposs_perfective_connective2_2f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_2m = transofposs_perfective_connective2_2[12:24]

#### female subject

In [328]:
transofposs_perfective_connective2_2f

                                             stimulus       she        he
0   Miss Smith flung a frisbee to Mr. Smith and, a...  0.200676  0.799324
1   The woman flung a frisbee to the man and, as a...  0.199772  0.800228
2      Mary flung a frisbee to John and, as a result,  0.256026  0.743974
3      Alice flung a frisbee to Bob and, as a result,  0.431601  0.568398
4   The actress flung a frisbee to the actor and, ...  0.260289  0.739711
5   The girl flung a frisbee to the boy and, as a ...  0.258236  0.741764
6   Mrs. Taylor flung a frisbee to Mr. Williams an...  0.223537  0.776463
7     Emma flung a frisbee to David and, as a result,  0.326389  0.673611
8   The princess flung a frisbee to the prince and...  0.345320  0.654680
9   Sarah flung a frisbee to Robert and, as a result,  0.269057  0.730943
10  Mrs. Williams flung a frisbee to  Mr. Taylor a...  0.291506  0.708494
11    Emily flung a frisbee to Paul and, as a result,  0.349317  0.650683

In [329]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_2f,'he'))

P('subj-pron'|subj=female) =  0.284310519695282
P('non-subj-pron'|subj=female) =  0.7156894852717718

In [330]:
c2_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_connective2_2f,'she')
c2_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_connective2_2f,'he')

#### male subject

In [331]:
transofposs_perfective_connective2_2m

                                             stimulus        he       she
12  Mr. Smith flung a frisbee to Miss Smith and, a...  0.339402  0.660598
13  The man flung a frisbee to the woman and, as a...  0.180922  0.819078
14     John flung a frisbee to Mary and, as a result,  0.212330  0.787670
15     Bob flung a frisbee to Alice and, as a result,  0.145504  0.854496
16  The actor flung a frisbee to the actress and, ...  0.231051  0.768949
17  The boy flung a frisbee to the girl and, as a ...  0.227709  0.772291
18  Mr. William flung a frisbee to  Mrs. Taylor an...  0.403000  0.597000
19    David flung a frisbee to Emma and, as a result,  0.205619  0.794381
20  The prince flung a frisbee to the princess and...  0.267551  0.732449
21  Robert flung a frisbee to Sarah and, as a result,  0.234770  0.765230
22  Mr. Taylor flung a frisbee to Mrs. Williams an...  0.323436  0.676564
23    Paul flung a frisbee to Emily and, as a result,  0.172012  0.827988

In [332]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_2m,'she'))

P('subj-pron'|subj=male) =  0.24527543286482492
P('non-subj-pron'|subj=male) =  0.7547245770692825

In [333]:
c2_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_connective2_2m,'he')
c2_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_connective2_2m,'she')

### verb: "kicked"

In [334]:
transofposs_perfective_connective2_3 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/3.csv")
transofposs_perfective_connective2_3.head()

                                            stimulus        he       she
0  Miss Smith kicked a soccer ball to Mr. Smith a...  0.793848  0.206152
1  The woman kicked a soccer ball to the man and,...  0.790015  0.209985
2  Mary kicked a soccer ball to John and, as a re...  0.624857  0.375143
3  Alice kicked a soccer ball to Bob and, as a re...  0.446342  0.553658
4  The actress kicked a soccer ball to the actor ...  0.652700  0.347300

In [335]:
# female subject
transofposs_perfective_connective2_3f = transofposs_perfective_connective2_3[0:12]
transofposs_perfective_connective2_3f = transofposs_perfective_connective2_3f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_3m = transofposs_perfective_connective2_3[12:24]

#### female subject

In [336]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_3f,'he'))

P('subj-pron'|subj=female) =  0.3541125903526942
P('non-subj-pron'|subj=female) =  0.6458874071637789

In [337]:
c2_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3f,'she')
c2_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3f,'he')

#### male subject

In [338]:
transofposs_perfective_connective2_3m

                                             stimulus        he       she
12  Mr. Smith kicked a soccer ball to Miss Smith a...  0.341764  0.658236
13  The man kicked a soccer ball to the woman and,...  0.190400  0.809600
14  John kicked a soccer ball to Mary and, as a re...  0.287834  0.712166
15  Bob kicked a soccer ball to Alice and, as a re...  0.198204  0.801796
16  The actor kicked a soccer ball to the actress ...  0.277458  0.722542
17  The boy kicked a soccer ball to the girl and, ...  0.243228  0.756772
18  Mr. William kicked a soccer ball to  Mrs. Tayl...  0.403005  0.596995
19  David kicked a soccer ball to Emma and, as a r...  0.235919  0.764081
20  The prince kicked a soccer ball to the princes...  0.325538  0.674462
21  Robert kicked a soccer ball to Sarah and, as a...  0.295622  0.704378
22  Mr. Taylor kicked a soccer ball to Mrs. Willia...  0.298478  0.701522
23  Paul kicked a soccer ball to Emily and, as a r...  0.199313  0.800687

In [339]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_3m,'she'))

P('subj-pron'|subj=male) =  0.2747301508982976
P('non-subj-pron'|subj=male) =  0.7252698491017023

In [340]:
c2_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3m,'he')
c2_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3m,'she')

### verb: "lobbed"

In [341]:
transofposs_perfective_connective2_4 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/4.csv")
transofposs_perfective_connective2_4.head()

                                            stimulus        he       she
0  Miss Smith lobbed a football to Mr. Smith and,...  0.860500  0.139500
1  The woman lobbed a football to the man and, as...  0.791011  0.208989
2   Mary lobbed a football to John and, as a result,  0.705357  0.294643
3   Alice lobbed a football to Bob and, as a result,  0.503231  0.496769
4  The actress lobbed a football to the actor and...  0.758843  0.241157

In [342]:
# female subject
transofposs_perfective_connective2_4f = transofposs_perfective_connective2_4[0:12]
transofposs_perfective_connective2_4f = transofposs_perfective_connective2_4f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_4m = transofposs_perfective_connective2_4[12:24]

#### female subject

In [343]:
transofposs_perfective_connective2_4f

                                             stimulus       she        he
0   Miss Smith lobbed a football to Mr. Smith and,...  0.139500  0.860500
1   The woman lobbed a football to the man and, as...  0.208989  0.791011
2    Mary lobbed a football to John and, as a result,  0.294643  0.705357
3    Alice lobbed a football to Bob and, as a result,  0.496769  0.503231
4   The actress lobbed a football to the actor and...  0.241157  0.758843
5   The girl lobbed a football to the boy and, as ...  0.234651  0.765349
6   Mrs. Taylor lobbed a football to Mr. Williams ...  0.132040  0.867960
7   Emma lobbed a football to David and, as a result,  0.244132  0.755868
8   The princess lobbed a football to the prince a...  0.267398  0.732602
9   Sarah lobbed a football to Robert and, as a re...  0.301935  0.698064
10  Mrs. Williams lobbed a football to  Mr. Taylor...  0.158654  0.841346
11  Emily lobbed a football to Paul and, as a result,  0.327314  0.672686

In [344]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_4f,'he'))

P('subj-pron'|subj=female) =  0.2539319557448228
P('non-subj-pron'|subj=female) =  0.746068000793457

In [345]:
c2_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4f,'she')
c2_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4f,'he')

#### male subject

In [346]:
transofposs_perfective_connective2_4m

                                             stimulus        he       she
12  Mr. Smith lobbed a football to Miss Smith and,...  0.240734  0.759266
13  The man lobbed a football to the woman and, as...  0.165367  0.834633
14   John lobbed a football to Mary and, as a result,  0.182062  0.817938
15   Bob lobbed a football to Alice and, as a result,  0.101247  0.898753
16  The actor lobbed a football to the actress and...  0.146411  0.853589
17  The boy lobbed a football to the girl and, as ...  0.181364  0.818636
18  Mr. William lobbed a football to  Mrs. Taylor ...  0.249713  0.750287
19  David lobbed a football to Emma and, as a result,  0.159323  0.840677
20  The prince lobbed a football to the princess a...  0.149162  0.850838
21  Robert lobbed a football to Sarah and, as a re...  0.188149  0.811851
22  Mr. Taylor lobbed a football to Mrs. Williams ...  0.219539  0.780461
23  Paul lobbed a football to Emily and, as a result,  0.148490  0.851510

In [347]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_4m,'she'))

P('subj-pron'|subj=male) =  0.1776301854600509
P('non-subj-pron'|subj=male) =  0.82236980398496

In [348]:
c2_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4m,'he')
c2_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4m,'she')

### verb: "rolled"

In [349]:
transofposs_perfective_connective2_5 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/5.csv")
transofposs_perfective_connective2_5.head()

                                            stimulus        he       she
0  Miss Smith rolled a toy truck to Mr. Smith and...  0.714545  0.285455
1  The woman rolled a toy truck to the man and, a...  0.711644  0.288356
2  Mary rolled a toy truck to John and, as a result,  0.599317  0.400683
3  Alice rolled a toy truck to Bob and, as a result,  0.437414  0.562586
4  The actress rolled a toy truck to the actor an...  0.589922  0.410078

In [350]:
# female subject
transofposs_perfective_connective2_5f = transofposs_perfective_connective2_5[0:12]
transofposs_perfective_connective2_5f = transofposs_perfective_connective2_5[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_5m = transofposs_perfective_connective2_5[12:24]

#### female subject

In [351]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_5f,'he'))

P('subj-pron'|subj=female) =  0.560339231044054
P('non-subj-pron'|subj=female) =  0.43966076026360196

In [352]:
c2_average_subj_female_subj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5f,'she')
c2_average_subj_female_obj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5f,'he')

#### male subject

In [353]:
transofposs_perfective_connective2_5m

                                             stimulus        he       she
12  Mr. Smith rolled a toy truck to Miss Smith and...  0.338785  0.661215
13  The man rolled a toy truck to the woman and, a...  0.212166  0.787834
14  John rolled a toy truck to Mary and, as a result,  0.310872  0.689128
15  Bob rolled a toy truck to Alice and, as a result,  0.196811  0.803189
16  The actor rolled a toy truck to the actress an...  0.275522  0.724478
17  The boy rolled a toy truck to the girl and, as...  0.276230  0.723770
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.429566  0.570434
19  David rolled a toy truck to Emma and, as a res...  0.255929  0.744071
20  The prince rolled a toy truck to the princess ...  0.310101  0.689899
21  Robert rolled a toy truck to Sarah and, as a r...  0.306758  0.693242
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.307585  0.692415
23  Paul rolled a toy truck to Emily and, as a res...  0.203076  0.796924

In [354]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_5m,'she'))

P('subj-pron'|subj=male) =  0.2852834189931552
P('non-subj-pron'|subj=male) =  0.7147165785233179

In [355]:
c2_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5m,'he')
c2_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5m,'she')

### verb: "threw"

In [356]:
transofposs_perfective_connective2_6 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/6.csv")
transofposs_perfective_connective2_6.head()

                                            stimulus        he       she
0  Miss Smith threw a hat to Mr. Smith and, as a ...  0.771291  0.228709
1  The woman threw a hat to the man and, as a res...  0.813631  0.186369
2         Mary threw a hat to John and, as a result,  0.688914  0.311086
3         Alice threw a hat to Bob and, as a result,  0.574348  0.425652
4  The actress threw a hat to the actor and, as a...  0.707411  0.292589

In [357]:
# female subject
transofposs_perfective_connective2_6f = transofposs_perfective_connective2_6[0:12]
transofposs_perfective_connective2_6f = transofposs_perfective_connective2_6[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_6m = transofposs_perfective_connective2_6[12:24]

#### female subject

In [358]:
transofposs_perfective_connective2_6f

                                             stimulus       she        he
0   Miss Smith threw a hat to Mr. Smith and, as a ...  0.228709  0.771291
1   The woman threw a hat to the man and, as a res...  0.186369  0.813631
2          Mary threw a hat to John and, as a result,  0.311086  0.688914
3          Alice threw a hat to Bob and, as a result,  0.425652  0.574348
4   The actress threw a hat to the actor and, as a...  0.292589  0.707411
5   The girl threw a hat to the boy and, as a result,  0.236680  0.763320
6   Mrs. Taylor threw a hat to Mr. Williams and, a...  0.217041  0.782959
7         Emma threw a hat to David and, as a result,  0.303351  0.696649
8   The princess threw a hat to the prince and, as...  0.303952  0.696047
9       Sarah threw a hat to Robert and, as a result,  0.292387  0.707613
10  Mrs. Williams threw a hat to  Mr. Taylor and, ...  0.264164  0.735836
11        Emily threw a hat to Paul and, as a result,  0.340365  0.659635
12  Mr. Smith threw a hat to Miss Smith and, as a ...  0.610196  0.389804
13  The man threw a hat to the woman and, as a res...  0.780849  0.219150
14         John threw a hat to Mary and, as a result,  0.601127  0.398873
15         Bob threw a hat to Alice and, as a result,  0.754774  0.245226
16  The actor threw a hat to the actress and, as a...  0.727621  0.272379
17  The boy threw a hat to the girl and, as a result,  0.754329  0.245671
18  Mr. William threw a hat to  Mrs. Taylor and, a...  0.596613  0.403387
19        David threw a hat to Emma and, as a result,  0.677429  0.322571
20  The prince threw a hat to the princess and, as...  0.767902  0.232098
21      Robert threw a hat to Sarah and, as a result,  0.661435  0.338565
22  Mr. Taylor threw a hat to Mrs. Williams and, a...  0.642383  0.357617
23        Paul threw a hat to Emily and, as a result,  0.696543  0.303457

In [359]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_6f,'he'))

P('subj-pron'|subj=female) =  0.48639778917034465
P('non-subj-pron'|subj=female) =  0.513602207104365

In [360]:
c2_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_connective2_6f,'she')
c2_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_connective2_6f,'he')

#### male subject

In [361]:
transofposs_perfective_connective2_6m

                                             stimulus        he       she
12  Mr. Smith threw a hat to Miss Smith and, as a ...  0.389804  0.610196
13  The man threw a hat to the woman and, as a res...  0.219150  0.780849
14         John threw a hat to Mary and, as a result,  0.398873  0.601127
15         Bob threw a hat to Alice and, as a result,  0.245226  0.754774
16  The actor threw a hat to the actress and, as a...  0.272379  0.727621
17  The boy threw a hat to the girl and, as a result,  0.245671  0.754329
18  Mr. William threw a hat to  Mrs. Taylor and, a...  0.403387  0.596613
19        David threw a hat to Emma and, as a result,  0.322571  0.677429
20  The prince threw a hat to the princess and, as...  0.232098  0.767902
21      Robert threw a hat to Sarah and, as a result,  0.338565  0.661435
22  Mr. Taylor threw a hat to Mrs. Williams and, a...  0.357617  0.642383
23        Paul threw a hat to Emily and, as a result,  0.303457  0.696543

In [362]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_6m,'she'))

P('subj-pron'|subj=male) =  0.31073308487733203
P('non-subj-pron'|subj=male) =  0.6892669002215067

In [363]:
c2_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_connective2_6m,'he')
c2_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_connective2_6m,'she')

### verb: "tossed"

In [364]:
transofposs_perfective_connective2_7 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/7.csv")
transofposs_perfective_connective2_7.head()

                                            stimulus        he       she
0  Miss Smith tossed a dish towel to Mr. Smith an...  0.775603  0.224397
1  The woman tossed a dish towel to the man and, ...  0.807403  0.192597
2  Mary tossed a dish towel to John and, as a res...  0.684317  0.315683
3  Alice tossed a dish towel to Bob and, as a res...  0.515267  0.484733
4  The actress tossed a dish towel to the actor a...  0.745307  0.254693

In [365]:
# female subject
transofposs_perfective_connective2_7f = transofposs_perfective_connective2_7[0:12]
transofposs_perfective_connective2_7f = transofposs_perfective_connective2_7f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_7m = transofposs_perfective_connective2_7[12:24]

#### female subject

In [366]:
transofposs_perfective_connective2_7f

                                             stimulus       she        he
0   Miss Smith tossed a dish towel to Mr. Smith an...  0.224397  0.775603
1   The woman tossed a dish towel to the man and, ...  0.192597  0.807403
2   Mary tossed a dish towel to John and, as a res...  0.315683  0.684317
3   Alice tossed a dish towel to Bob and, as a res...  0.484733  0.515267
4   The actress tossed a dish towel to the actor a...  0.254693  0.745307
5   The girl tossed a dish towel to the boy and, a...  0.325420  0.674580
6   Mrs. Taylor tossed a dish towel to Mr. William...  0.278144  0.721856
7   Emma tossed a dish towel to David and, as a re...  0.335863  0.664137
8   The princess tossed a dish towel to the prince...  0.379124  0.620876
9   Sarah tossed a dish towel to Robert and, as a ...  0.282494  0.717506
10  Mrs. Williams tossed a dish towel to  Mr. Tayl...  0.342870  0.657130
11  Emily tossed a dish towel to Paul and, as a re...  0.381214  0.618787

In [367]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_7f,'he'))

P('subj-pron'|subj=female) =  0.31643598650892574
P('non-subj-pron'|subj=female) =  0.6835640172163645

In [368]:
c2_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7f,'she')
c2_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7f,'he')

#### male subject

In [369]:
transofposs_perfective_connective2_7m

                                             stimulus        he       she
12  Mr. Smith tossed a dish towel to Miss Smith an...  0.338454  0.661546
13  The man tossed a dish towel to the woman and, ...  0.171752  0.828248
14  John tossed a dish towel to Mary and, as a res...  0.251829  0.748171
15  Bob tossed a dish towel to Alice and, as a res...  0.159452  0.840548
16  The actor tossed a dish towel to the actress a...  0.235331  0.764669
17  The boy tossed a dish towel to the girl and, a...  0.238394  0.761606
18  Mr. William tossed a dish towel to  Mrs. Taylo...  0.338388  0.661612
19  David tossed a dish towel to Emma and, as a re...  0.217101  0.782899
20  The prince tossed a dish towel to the princess...  0.281339  0.718661
21  Robert tossed a dish towel to Sarah and, as a ...  0.251141  0.748859
22  Mr. Taylor tossed a dish towel to Mrs. William...  0.253984  0.746016
23  Paul tossed a dish towel to Emily and, as a re...  0.182100  0.817900

In [370]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_7m,'she'))

P('subj-pron'|subj=male) =  0.24327202265461287
P('non-subj-pron'|subj=male) =  0.756727953751882

In [371]:
c2_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7m,'he')
c2_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7m,'she')

#### verb: "brought"

In [372]:
transofposs_perfective_connective2_8 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/8.csv")
transofposs_perfective_connective2_8.head()

                                            stimulus        he       she
0  Miss Smith brought a glass of water to Mr. Smi...  0.861173  0.138827
1  The woman brought a glass of water to the man ...  0.797235  0.202765
2  Mary brought a glass of water to John and, as ...  0.856510  0.143490
3  Alice brought a glass of water to Bob and, as ...  0.638731  0.361269
4  The actress brought a glass of water to the ac...  0.830321  0.169679

In [373]:
# female subject
transofposs_perfective_connective2_8f = transofposs_perfective_connective2_8[0:12]
transofposs_perfective_connective2_8f = transofposs_perfective_connective2_8f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_8m = transofposs_perfective_connective2_8[12:24]

#### female subject

In [374]:
transofposs_perfective_connective2_8f

                                             stimulus       she        he
0   Miss Smith brought a glass of water to Mr. Smi...  0.138827  0.861173
1   The woman brought a glass of water to the man ...  0.202765  0.797235
2   Mary brought a glass of water to John and, as ...  0.143490  0.856510
3   Alice brought a glass of water to Bob and, as ...  0.361269  0.638731
4   The actress brought a glass of water to the ac...  0.169679  0.830321
5   The girl brought a glass of water to the boy a...  0.203419  0.796581
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.172767  0.827233
7   Emma brought a glass of water to David and, as...  0.213192  0.786808
8   The princess brought a glass of water to the p...  0.219414  0.780586
9   Sarah brought a glass of water to Robert and, ...  0.204842  0.795158
10  Mrs. Williams brought a glass of water to  Mr....  0.237057  0.762943
11  Emily brought a glass of water to Paul and, as...  0.248844  0.751157

In [375]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_8f,'he'))

P('subj-pron'|subj=female) =  0.20963039125005403
P('non-subj-pron'|subj=female) =  0.7903696149587631

In [376]:
c2_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_connective2_8f,'she')
c2_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_connective2_8f,'he')

#### male subject

In [377]:
transofposs_perfective_connective2_8m

                                             stimulus        he       she
12  Mr. Smith brought a glass of water to Miss Smi...  0.280382  0.719617
13  The man brought a glass of water to the woman ...  0.168633  0.831367
14  John brought a glass of water to Mary and, as ...  0.177384  0.822616
15  Bob brought a glass of water to Alice and, as ...  0.099559  0.900441
16  The actor brought a glass of water to the actr...  0.164368  0.835632
17  The boy brought a glass of water to the girl a...  0.193487  0.806513
18  Mr. William brought a glass of water to  Mrs. ...  0.266174  0.733826
19  David brought a glass of water to Emma and, as...  0.158832  0.841168
20  The prince brought a glass of water to the pri...  0.141707  0.858293
21  Robert brought a glass of water to Sarah and, ...  0.198096  0.801904
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.229366  0.770634
23  Paul brought a glass of water to Emily and, as...  0.136195  0.863805

In [378]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_8m,'she'))

P('subj-pron'|subj=male) =  0.18451517634093761
P('non-subj-pron'|subj=male) =  0.8154848118623098

In [379]:
c2_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_connective2_8m,'he')
c2_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_connective2_8m,'she')

### verb: "forwarded"

In [380]:
transofposs_perfective_connective2_9 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/9.csv")
transofposs_perfective_connective2_9.head()

                                            stimulus        he       she
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.800933  0.199067
1  The woman forwarded a gossipy email to the man...  0.789775  0.210225
2  Mary forwarded a gossipy email to John and, as...  0.773497  0.226502
3  Alice forwarded a gossipy email to Bob and, as...  0.597637  0.402363
4  The actress forwarded a gossipy email to the a...  0.737599  0.262401

In [381]:
# female subject
transofposs_perfective_connective2_9f = transofposs_perfective_connective2_9[0:12]
transofposs_perfective_connective2_9f = transofposs_perfective_connective2_9f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_9m = transofposs_perfective_connective2_9[12:24]

#### female subject

In [382]:
transofposs_perfective_connective2_9f

                                             stimulus       she        he
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.199067  0.800933
1   The woman forwarded a gossipy email to the man...  0.210225  0.789775
2   Mary forwarded a gossipy email to John and, as...  0.226502  0.773497
3   Alice forwarded a gossipy email to Bob and, as...  0.402363  0.597637
4   The actress forwarded a gossipy email to the a...  0.262401  0.737599
5   The girl forwarded a gossipy email to the boy ...  0.190403  0.809597
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.263428  0.736572
7   Emma forwarded a gossipy email to David and, a...  0.198435  0.801565
8   The princess forwarded a gossipy email to the ...  0.232841  0.767159
9   Sarah forwarded a gossipy email to Robert and,...  0.290527  0.709473
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.283222  0.716778
11  Emily forwarded a gossipy email to Paul and, a...  0.240162  0.759838

In [383]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_9f,'he'))

P('subj-pron'|subj=female) =  0.2499646469950676
P('non-subj-pron'|subj=female) =  0.750035360455513

In [384]:
c2_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9f,'she')
c2_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9f,'he')

#### male subject

In [385]:
transofposs_perfective_connective2_9m

                                             stimulus        he       she
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.193703  0.806297
13  The man forwarded a gossipy email to the woman...  0.173749  0.826251
14  John forwarded a gossipy email to Mary and, as...  0.219330  0.780670
15  Bob forwarded a gossipy email to Alice and, as...  0.115197  0.884803
16  The actor forwarded a gossipy email to the act...  0.152334  0.847666
17  The boy forwarded a gossipy email to the girl ...  0.191321  0.808679
18  Mr. William forwarded a gossipy email to  Mrs....  0.177671  0.822329
19  David forwarded a gossipy email to Emma and, a...  0.168706  0.831294
20  The prince forwarded a gossipy email to the pr...  0.119664  0.880336
21  Robert forwarded a gossipy email to Sarah and,...  0.202378  0.797622
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.148357  0.851643
23  Paul forwarded a gossipy email to Emily and, a...  0.188508  0.811492

In [386]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_9m,'she'))

P('subj-pron'|subj=male) =  0.1709099281579256
P('non-subj-pron'|subj=male) =  0.8290900637706121

In [387]:
c2_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9m,'he')
c2_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9m,'she')

### verb: "mailed"

In [388]:
transofposs_perfective_connective2_10 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/10.csv")
transofposs_perfective_connective2_10.head()

                                            stimulus        he       she
0  Miss Smith mailed a letter to Mr. Smith and, a...  0.830674  0.169326
1  The woman mailed a letter to the man and, as a...  0.831382  0.168618
2     Mary mailed a letter to John and, as a result,  0.710469  0.289531
3     Alice mailed a letter to Bob and, as a result,  0.582170  0.417830
4  The actress mailed a letter to the actor and, ...  0.674766  0.325234

In [389]:
# female subject
transofposs_perfective_connective2_10f = transofposs_perfective_connective2_10[0:12]
transofposs_perfective_connective2_10f = transofposs_perfective_connective2_10f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_10m = transofposs_perfective_connective2_10[12:24]

#### female subject

In [390]:
transofposs_perfective_connective2_10f

                                             stimulus       she        he
0   Miss Smith mailed a letter to Mr. Smith and, a...  0.169326  0.830674
1   The woman mailed a letter to the man and, as a...  0.168618  0.831382
2      Mary mailed a letter to John and, as a result,  0.289531  0.710469
3      Alice mailed a letter to Bob and, as a result,  0.417830  0.582170
4   The actress mailed a letter to the actor and, ...  0.325234  0.674766
5   The girl mailed a letter to the boy and, as a ...  0.215534  0.784466
6   Mrs. Taylor mailed a letter to Mr. Williams an...  0.253597  0.746403
7     Emma mailed a letter to David and, as a result,  0.237931  0.762069
8   The princess mailed a letter to the prince and...  0.342088  0.657912
9   Sarah mailed a letter to Robert and, as a result,  0.311729  0.688271
10  Mrs. Williams mailed a letter to  Mr. Taylor a...  0.284086  0.715914
11    Emily mailed a letter to Paul and, as a result,  0.216226  0.783774

In [391]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_10f,'he'))

P('subj-pron'|subj=female) =  0.26931089411179227
P('non-subj-pron'|subj=female) =  0.7306890885035197

In [392]:
c2_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10f,'she')
c2_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10f,'he')

#### male subject

In [393]:
transofposs_perfective_connective2_10m

                                             stimulus        he       she
12  Mr. Smith mailed a letter to Miss Smith and, a...  0.200174  0.799826
13  The man mailed a letter to the woman and, as a...  0.195783  0.804217
14     John mailed a letter to Mary and, as a result,  0.243727  0.756273
15     Bob mailed a letter to Alice and, as a result,  0.146961  0.853039
16  The actor mailed a letter to the actress and, ...  0.194759  0.805241
17  The boy mailed a letter to the girl and, as a ...  0.278591  0.721409
18  Mr. William mailed a letter to  Mrs. Taylor an...  0.251537  0.748463
19    David mailed a letter to Emma and, as a result,  0.210477  0.789523
20  The prince mailed a letter to the princess and...  0.159807  0.840193
21  Robert mailed a letter to Sarah and, as a result,  0.248042  0.751958
22  Mr. Taylor mailed a letter to Mrs. Williams an...  0.158381  0.841619
23    Paul mailed a letter to Emily and, as a result,  0.180767  0.819233

In [394]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_10m,'she'))

P('subj-pron'|subj=male) =  0.20575068021814027
P('non-subj-pron'|subj=male) =  0.7942493309577306

In [395]:
c2_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10m,'he')
c2_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10m,'she')

### verb: "shipped"

In [396]:
transofposs_perfective_connective2_11 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/11.csv")
transofposs_perfective_connective2_11.head()

                                            stimulus        he       she
0  Miss Smith shipped a package to Mr. Smith and,...  0.794876  0.205124
1  The woman shipped a package to the man and, as...  0.679110  0.320890
2   Mary shipped a package to John and, as a result,  0.639510  0.360490
3   Alice shipped a package to Bob and, as a result,  0.559995  0.440005
4  The actress shipped a package to the actor and...  0.648264  0.351736

In [397]:
# female subject
transofposs_perfective_connective2_11f = transofposs_perfective_connective2_11[0:12]
transofposs_perfective_connective2_11f = transofposs_perfective_connective2_11f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_11m = transofposs_perfective_connective2_11[12:24]

#### female subject

In [398]:
transofposs_perfective_connective2_11f

                                             stimulus       she        he
0   Miss Smith shipped a package to Mr. Smith and,...  0.205124  0.794876
1   The woman shipped a package to the man and, as...  0.320890  0.679110
2    Mary shipped a package to John and, as a result,  0.360490  0.639510
3    Alice shipped a package to Bob and, as a result,  0.440005  0.559995
4   The actress shipped a package to the actor and...  0.351736  0.648264
5   The girl shipped a package to the boy and, as ...  0.409660  0.590340
6   Mrs. Taylor shipped a package to Mr. Williams ...  0.221070  0.778930
7   Emma shipped a package to David and, as a result,  0.336176  0.663824
8   The princess shipped a package to the prince a...  0.363807  0.636193
9   Sarah shipped a package to Robert and, as a re...  0.272398  0.727602
10  Mrs. Williams shipped a package to  Mr. Taylor...  0.260555  0.739445
11  Emily shipped a package to Paul and, as a result,  0.311549  0.688451

In [399]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_11f,'he'))

P('subj-pron'|subj=female) =  0.3211215063929558
P('non-subj-pron'|subj=female) =  0.6788784911235174

In [400]:
c2_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11f,'she')
c2_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11f,'he')

#### male subject

In [401]:
transofposs_perfective_connective2_11m

                                             stimulus        he       she
12  Mr. Smith shipped a package to Miss Smith and,...  0.235399  0.764601
13  The man shipped a package to the woman and, as...  0.244427  0.755573
14   John shipped a package to Mary and, as a result,  0.248515  0.751485
15   Bob shipped a package to Alice and, as a result,  0.124624  0.875376
16  The actor shipped a package to the actress and...  0.203815  0.796185
17  The boy shipped a package to the girl and, as ...  0.319103  0.680897
18  Mr. William shipped a package to  Mrs. Taylor ...  0.240671  0.759329
19  David shipped a package to Emma and, as a result,  0.160936  0.839064
20  The prince shipped a package to the princess a...  0.242985  0.757015
21  Robert shipped a package to Sarah and, as a re...  0.208067  0.791933
22  Mr. Taylor shipped a package to Mrs. Williams ...  0.205351  0.794649
23  Paul shipped a package to Emily and, as a result,  0.162665  0.837335

In [402]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_11m,'she'))

P('subj-pron'|subj=male) =  0.21637988276779652
P('non-subj-pron'|subj=male) =  0.7836201240619024

In [403]:
c2_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11m,'he')
c2_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11m,'she')

### verb: "transmitted"

In [404]:
transofposs_perfective_connective2_12 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/12.csv")
transofposs_perfective_connective2_12.head()

                                            stimulus        he       she
0  Miss Smith transmitted a message to Mr. Smith ...  0.857142  0.142858
1  The woman transmitted a message to the man and...  0.844719  0.155281
2  Mary transmitted a message to John and, as a r...  0.844064  0.155936
3  Alice transmitted a message to Bob and, as a r...  0.695489  0.304511
4  The actress transmitted a message to the actor...  0.697320  0.302680

In [405]:
# female subject
transofposs_perfective_connective2_12f = transofposs_perfective_connective2_12[0:12]
transofposs_perfective_connective2_12f = transofposs_perfective_connective2_12f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_12m = transofposs_perfective_connective2_12[12:24]

#### female subject

In [406]:
transofposs_perfective_connective2_12f

                                             stimulus       she        he
0   Miss Smith transmitted a message to Mr. Smith ...  0.142858  0.857142
1   The woman transmitted a message to the man and...  0.155281  0.844719
2   Mary transmitted a message to John and, as a r...  0.155936  0.844064
3   Alice transmitted a message to Bob and, as a r...  0.304511  0.695489
4   The actress transmitted a message to the actor...  0.302680  0.697320
5   The girl transmitted a message to the boy and,...  0.179231  0.820769
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.173186  0.826814
7   Emma transmitted a message to David and, as a ...  0.199963  0.800037
8   The princess transmitted a message to the prin...  0.281585  0.718414
9   Sarah transmitted a message to Robert and, as ...  0.180859  0.819141
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.185322  0.814678
11  Emily transmitted a message to Paul and, as a ...  0.195402  0.804599

In [407]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_12f,'he'))

P('subj-pron'|subj=female) =  0.2047344110906124
P('non-subj-pron'|subj=female) =  0.7952655901511511

In [408]:
c2_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12f,'she')
c2_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12f,'he')

#### male subject

In [409]:
transofposs_perfective_connective2_12m

                                             stimulus        he       she
12  Mr. Smith transmitted a message to Miss Smith ...  0.270235  0.729765
13  The man transmitted a message to the woman and...  0.241109  0.758891
14  John transmitted a message to Mary and, as a r...  0.161119  0.838881
15  Bob transmitted a message to Alice and, as a r...  0.127793  0.872207
16  The actor transmitted a message to the actress...  0.203738  0.796262
17  The boy transmitted a message to the girl and,...  0.236975  0.763025
18  Mr. William transmitted a message to  Mrs. Tay...  0.300494  0.699506
19  David transmitted a message to Emma and, as a ...  0.192378  0.807622
20  The prince transmitted a message to the prince...  0.161460  0.838540
21  Robert transmitted a message to Sarah and, as ...  0.208368  0.791632
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.214563  0.785438
23  Paul transmitted a message to Emily and, as a ...  0.164840  0.835160

In [410]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_12m,'she'))

P('subj-pron'|subj=male) =  0.2069226341942946
P('non-subj-pron'|subj=male) =  0.7930773595968882

In [411]:
c2_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12m,'he')
c2_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12m,'she')

### verb: "wired"

In [412]:
transofposs_perfective_connective2_14 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/14.csv")
transofposs_perfective_connective2_14.head()

                                            stimulus        he       she
0  Miss Smith wired money to Mr. Smith and, as a ...  0.783224  0.216776
1  The woman wired money to the man and, as a res...  0.772007  0.227993
2         Mary wired money to John and, as a result,  0.641280  0.358720
3         Alice wired money to Bob and, as a result,  0.542943  0.457057
4  The actress wired money to the actor and, as a...  0.657532  0.342468

In [413]:
# female subject
transofposs_perfective_connective2_14f = transofposs_perfective_connective2_14[0:12]
transofposs_perfective_connective2_14f = transofposs_perfective_connective2_14f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_14m = transofposs_perfective_connective2_14[12:24]

#### female subject

In [414]:
transofposs_perfective_connective2_14f

                                             stimulus       she        he
0   Miss Smith wired money to Mr. Smith and, as a ...  0.216776  0.783224
1   The woman wired money to the man and, as a res...  0.227993  0.772007
2          Mary wired money to John and, as a result,  0.358720  0.641280
3          Alice wired money to Bob and, as a result,  0.457057  0.542943
4   The actress wired money to the actor and, as a...  0.342468  0.657532
5   The girl wired money to the boy and, as a result,  0.253811  0.746189
6   Mrs. Taylor wired money to Mr. Williams and, a...  0.192883  0.807118
7         Emma wired money to David and, as a result,  0.310460  0.689540
8   The princess wired money to the prince and, as...  0.301044  0.698956
9       Sarah wired money to Robert and, as a result,  0.301054  0.698946
10  Mrs. Williams wired money to  Mr. Taylor and, ...  0.218168  0.781832
11        Emily wired money to Paul and, as a result,  0.295745  0.704255

In [415]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_14f,'he'))

P('subj-pron'|subj=female) =  0.28968164697289467
P('non-subj-pron'|subj=female) =  0.7103183567523956

In [416]:
c2_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_connective2_14f,'she')
c2_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_connective2_14f,'he')

#### male subject

In [417]:
transofposs_perfective_connective2_14m

                                             stimulus        he       she
12  Mr. Smith wired money to Miss Smith and, as a ...  0.248352  0.751648
13  The man wired money to the woman and, as a res...  0.223065  0.776935
14         John wired money to Mary and, as a result,  0.235044  0.764956
15         Bob wired money to Alice and, as a result,  0.200640  0.799360
16  The actor wired money to the actress and, as a...  0.179536  0.820464
17  The boy wired money to the girl and, as a result,  0.265304  0.734696
18  Mr. William wired money to  Mrs. Taylor and, a...  0.299709  0.700291
19        David wired money to Emma and, as a result,  0.215581  0.784419
20  The prince wired money to the princess and, as...  0.173709  0.826291
21      Robert wired money to Sarah and, as a result,  0.206346  0.793654
22  Mr. Taylor wired money to Mrs. Williams and, a...  0.251966  0.748034
23        Paul wired money to Emily and, as a result,  0.191099  0.808901

In [418]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_14m,'she'))

P('subj-pron'|subj=male) =  0.22419618194301924
P('non-subj-pron'|subj=male) =  0.7758038093646368

In [419]:
c2_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_connective2_14m,'he')
c2_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_connective2_14m,'she')

### verb: "carried"

In [420]:
transofposs_perfective_connective2_15 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/15.csv")
transofposs_perfective_connective2_15.head()

                                            stimulus        he       she
0  Miss Smith carried a tray to Mr. Smith and, as...  0.672670  0.327330
1  The woman carried a tray to the man and, as a ...  0.520387  0.479613
2      Mary carried a tray to John and, as a result,  0.574630  0.425370
3      Alice carried a tray to Bob and, as a result,  0.425622  0.574378
4  The actress carried a tray to the actor and, a...  0.501407  0.498593

In [421]:
# female subject
transofposs_perfective_connective2_15f = transofposs_perfective_connective2_15[0:12]
transofposs_perfective_connective2_15f = transofposs_perfective_connective2_15f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_15m = transofposs_perfective_connective2_15[12:24]

#### female subject

In [422]:
transofposs_perfective_connective2_15f

                                             stimulus       she        he
0   Miss Smith carried a tray to Mr. Smith and, as...  0.327330  0.672670
1   The woman carried a tray to the man and, as a ...  0.479613  0.520387
2       Mary carried a tray to John and, as a result,  0.425370  0.574630
3       Alice carried a tray to Bob and, as a result,  0.574378  0.425622
4   The actress carried a tray to the actor and, a...  0.498593  0.501407
5   The girl carried a tray to the boy and, as a r...  0.500666  0.499334
6   Mrs. Taylor carried a tray to Mr. Williams and...  0.367319  0.632681
7      Emma carried a tray to David and, as a result,  0.448953  0.551047
8   The princess carried a tray to the prince and,...  0.601180  0.398820
9    Sarah carried a tray to Robert and, as a result,  0.413827  0.586173
10  Mrs. Williams carried a tray to  Mr. Taylor an...  0.412403  0.587597
11     Emily carried a tray to Paul and, as a result,  0.533179  0.466821

In [423]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_15f,'he'))

P('subj-pron'|subj=female) =  0.46523427218198776
P('non-subj-pron'|subj=female) =  0.5347657278180122

In [424]:
c2_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_connective2_15f,'she')
c2_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_connective2_15f,'he')

#### male subject

In [425]:
transofposs_perfective_connective2_15m

                                             stimulus        he       she
12  Mr. Smith carried a tray to Miss Smith and, as...  0.387141  0.612859
13  The man carried a tray to the woman and, as a ...  0.330226  0.669774
14      John carried a tray to Mary and, as a result,  0.320357  0.679643
15      Bob carried a tray to Alice and, as a result,  0.264816  0.735184
16  The actor carried a tray to the actress and, a...  0.358433  0.641567
17  The boy carried a tray to the girl and, as a r...  0.356681  0.643319
18  Mr. William carried a tray to  Mrs. Taylor and...  0.459303  0.540697
19     David carried a tray to Emma and, as a result,  0.278271  0.721729
20  The prince carried a tray to the princess and,...  0.370769  0.629231
21   Robert carried a tray to Sarah and, as a result,  0.320882  0.679118
22  Mr. Taylor carried a tray to Mrs. Williams and...  0.379178  0.620822
23     Paul carried a tray to Emily and, as a result,  0.221028  0.778972

In [426]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_15m,'she'))

P('subj-pron'|subj=male) =  0.33725691959261894
P('non-subj-pron'|subj=male) =  0.662743071715037

In [427]:
c2_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_connective2_15m,'he')
c2_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_connective2_15m,'she')

### verb: "delivered"

In [428]:
transofposs_perfective_connective2_16 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/16.csv")
transofposs_perfective_connective2_16.head()

                                            stimulus        he       she
0  Miss Smith delivered a subpoena to Mr. Smith a...  0.955858  0.044142
1  The woman delivered a subpoena to the man and,...  0.837685  0.162315
2  Mary delivered a subpoena to John and, as a re...  0.830709  0.169291
3  Alice delivered a subpoena to Bob and, as a re...  0.748960  0.251040
4  The actress delivered a subpoena to the actor ...  0.666724  0.333276

In [429]:
# female subject
transofposs_perfective_connective2_16f = transofposs_perfective_connective2_16[0:12]
transofposs_perfective_connective2_16f = transofposs_perfective_connective2_16f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_16m = transofposs_perfective_connective2_16[12:24]

#### female subject

In [430]:
transofposs_perfective_connective2_16f

                                             stimulus       she        he
0   Miss Smith delivered a subpoena to Mr. Smith a...  0.044142  0.955858
1   The woman delivered a subpoena to the man and,...  0.162315  0.837685
2   Mary delivered a subpoena to John and, as a re...  0.169291  0.830709
3   Alice delivered a subpoena to Bob and, as a re...  0.251040  0.748960
4   The actress delivered a subpoena to the actor ...  0.333276  0.666724
5   The girl delivered a subpoena to the boy and, ...  0.172181  0.827819
6   Mrs. Taylor delivered a subpoena to Mr. Willia...  0.078818  0.921182
7   Emma delivered a subpoena to David and, as a r...  0.136270  0.863730
8   The princess delivered a subpoena to the princ...  0.214324  0.785676
9   Sarah delivered a subpoena to Robert and, as a...  0.207494  0.792506
10  Mrs. Williams delivered a subpoena to Mr. Tayl...  0.113189  0.886811
11  Emily delivered a subpoena to Paul and, as a r...  0.146362  0.853638

In [431]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_16f,'he'))

P('subj-pron'|subj=female) =  0.16905848402529955
P('non-subj-pron'|subj=female) =  0.8309415181477865

In [432]:
c2_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16f,'she')
c2_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16f,'he')

#### male subject

In [433]:
transofposs_perfective_connective2_16m

                                             stimulus        he       she
12  Mr. Smith delivered a subpoena to Miss Smith a...  0.146063  0.853937
13  The man delivered a subpoena to the woman and,...  0.184760  0.815240
14  John delivered a subpoena to Mary and, as a re...  0.178999  0.821001
15  Bob delivered a subpoena to Alice and, as a re...  0.137479  0.862521
16  The actor delivered a subpoena to the actress ...  0.121375  0.878625
17  The boy delivered a subpoena to the girl and, ...  0.232292  0.767708
18  Mr. William delivered a subpoena to Mrs. Taylo...  0.162548  0.837452
19  David delivered a subpoena to Emma and, as a r...  0.140152  0.859848
20  The prince delivered a subpoena to the princes...  0.157931  0.842069
21  Robert delivered a subpoena to Sarah and, as a...  0.141260  0.858740
22  Mr. Taylor delivered a subpoena to Mrs. Willia...  0.124810  0.875190
23  Paul delivered a subpoena to Emily and, as a r...  0.167055  0.832945

In [434]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_16m,'she'))

P('subj-pron'|subj=male) =  0.15789363781611124
P('non-subj-pron'|subj=male) =  0.8421063472827276

In [435]:
c2_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16m,'he')
c2_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16m,'she')

### verb: "gave"

In [436]:
transofposs_perfective_connective2_17 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/17.csv")
transofposs_perfective_connective2_17.head()

                                            stimulus        he       she
0  Miss Smith gave a sweater to Mr. Smith and, as...  0.826481  0.173519
1  The woman gave a sweater to the man and, as a ...  0.833713  0.166287
2      Mary gave a sweater to John and, as a result,  0.726811  0.273189
3      Alice gave a sweater to Bob and, as a result,  0.600193  0.399807
4  The actress gave a sweater to the actor and, a...  0.767291  0.232709

In [437]:
# female subject
transofposs_perfective_connective2_17f = transofposs_perfective_connective2_17[0:12]
transofposs_perfective_connective2_17f = transofposs_perfective_connective2_17f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_17m = transofposs_perfective_connective2_17[12:24]

#### female subject

In [438]:
transofposs_perfective_connective2_17f

                                             stimulus       she        he
0   Miss Smith gave a sweater to Mr. Smith and, as...  0.173519  0.826481
1   The woman gave a sweater to the man and, as a ...  0.166287  0.833713
2       Mary gave a sweater to John and, as a result,  0.273189  0.726811
3       Alice gave a sweater to Bob and, as a result,  0.399807  0.600193
4   The actress gave a sweater to the actor and, a...  0.232709  0.767291
5   The girl gave a sweater to the boy and, as a r...  0.230489  0.769511
6   Mrs. Taylor gave a sweater to Mr. Williams and...  0.183502  0.816498
7      Emma gave a sweater to David and, as a result,  0.254301  0.745699
8   The princess gave a sweater to the prince and,...  0.231450  0.768550
9    Sarah gave a sweater to Robert and, as a result,  0.244961  0.755039
10  Mrs. Williams gave a sweater to  Mr. Taylor an...  0.213319  0.786681
11     Emily gave a sweater to Paul and, as a result,  0.330584  0.669416

In [439]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_17f,'he'))

P('subj-pron'|subj=female) =  0.2445095938940843
P('non-subj-pron'|subj=female) =  0.7554903874794642

In [440]:
c2_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_connective2_17f,'she')
c2_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_connective2_17f,'he')

#### male subject

In [441]:
transofposs_perfective_connective2_17m

                                             stimulus        he       she
12  Mr. Smith gave a sweater to Miss Smith and, as...  0.335489  0.664511
13  The man gave a sweater to the woman and, as a ...  0.209678  0.790322
14      John gave a sweater to Mary and, as a result,  0.321383  0.678617
15      Bob gave a sweater to Alice and, as a result,  0.177461  0.822539
16  The actor gave a sweater to the actress and, a...  0.228160  0.771841
17  The boy gave a sweater to the girl and, as a r...  0.245480  0.754520
18  Mr. William gave a sweater to  Mrs. Taylor and...  0.349803  0.650197
19     David gave a sweater to Emma and, as a result,  0.282774  0.717226
20  The prince gave a sweater to the princess and,...  0.201538  0.798462
21   Robert gave a sweater to Sarah and, as a result,  0.296052  0.703948
22  Mr. Taylor gave a sweater to Mrs. Williams and...  0.285769  0.714232
23     Paul gave a sweater to Emily and, as a result,  0.211459  0.788541

In [442]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_17m,'she'))

P('subj-pron'|subj=male) =  0.26208710422118503
P('non-subj-pron'|subj=male) =  0.7379129081964493

In [443]:
c2_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_connective2_17m,'he')
c2_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_connective2_17m,'she')

### verb: "handed"

In [444]:
transofposs_perfective_connective2_18 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/18.csv")
transofposs_perfective_connective2_18.head()

                                            stimulus        he       she
0  Miss Smith handed a book to Mr. Smith and, as ...  0.863873  0.136127
1  The woman handed a book to the man and, as a r...  0.794266  0.205734
2       Mary handed a book to John and, as a result,  0.765391  0.234609
3       Alice handed a book to Bob and, as a result,  0.613478  0.386522
4  The actress handed a book to the actor and, as...  0.820924  0.179076

In [445]:
# female subject
transofposs_perfective_connective2_18f = transofposs_perfective_connective2_18[0:12]
transofposs_perfective_connective2_18f = transofposs_perfective_connective2_18f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_18m = transofposs_perfective_connective2_18[12:24]

#### female subject

In [446]:
transofposs_perfective_connective2_18f

                                             stimulus       she        he
0   Miss Smith handed a book to Mr. Smith and, as ...  0.136127  0.863873
1   The woman handed a book to the man and, as a r...  0.205734  0.794266
2        Mary handed a book to John and, as a result,  0.234609  0.765391
3        Alice handed a book to Bob and, as a result,  0.386522  0.613478
4   The actress handed a book to the actor and, as...  0.179076  0.820924
5   The girl handed a book to the boy and, as a re...  0.211339  0.788661
6   Mrs. Taylor handed a book to Mr. Williams and,...  0.184280  0.815720
7       Emma handed a book to David and, as a result,  0.261835  0.738165
8   The princess handed a book to the prince and, ...  0.290919  0.709082
9     Sarah handed a book to Robert and, as a result,  0.263348  0.736652
10  Mrs. Williams handed a book to Mr. Taylor and,...  0.201626  0.798374
11      Emily handed a book to Paul and, as a result,  0.305391  0.694609

In [447]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_18f,'he'))

P('subj-pron'|subj=female) =  0.2384004071354866
P('non-subj-pron'|subj=female) =  0.7615995953480402

In [448]:
c2_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_connective2_18f,'she')
c2_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_connective2_18f,'he')

#### male subject

In [449]:
transofposs_perfective_connective2_18m

                                             stimulus        he       she
12  Mr. Smith handed a book to Miss Smith and, as ...  0.280797  0.719203
13  The man handed a book to the woman and, as a r...  0.176047  0.823953
14       John handed a book to Mary and, as a result,  0.209078  0.790922
15       Bob handed a book to Alice and, as a result,  0.118410  0.881590
16  The actor handed a book to the actress and, as...  0.167698  0.832302
17  The boy handed a book to the girl and, as a re...  0.230407  0.769593
18  Mr. William handed a book to Mrs. Taylor and, ...  0.257290  0.742710
19      David handed a book to Emma and, as a result,  0.204659  0.795341
20  The prince handed a book to the princess and, ...  0.151240  0.848760
21    Robert handed a book to Sarah and, as a result,  0.222687  0.777313
22  Mr. Taylor handed a book to Mrs. Williams and,...  0.232668  0.767332
23      Paul handed a book to Emily and, as a result,  0.163083  0.836917

In [450]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_18m,'she'))

P('subj-pron'|subj=male) =  0.20117219599584737
P('non-subj-pron'|subj=male) =  0.7988278269767761

In [451]:
c2_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_connective2_18m,'he')
c2_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_connective2_18m,'she')

### verb: "passed"

In [452]:
transofposs_perfective_connective2_19 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/19.csv")
transofposs_perfective_connective2_19.head()

                                            stimulus        he       she
0  Miss Smith passed a sandwich to Mr. Smith and,...  0.843191  0.156809
1  The woman passed a sandwich to the man and, as...  0.743969  0.256031
2   Mary passed a sandwich to John and, as a result,  0.822379  0.177621
3   Alice passed a sandwich to Bob and, as a result,  0.655917  0.344083
4  The actress passed a sandwich to the actor and...  0.761526  0.238474

In [453]:
# female subject
transofposs_perfective_connective2_19f = transofposs_perfective_connective2_19[0:12]
transofposs_perfective_connective2_19f = transofposs_perfective_connective2_19f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_19m = transofposs_perfective_connective2_19[12:24]

#### female subject

In [454]:
transofposs_perfective_connective2_19f

                                             stimulus       she        he
0   Miss Smith passed a sandwich to Mr. Smith and,...  0.156809  0.843191
1   The woman passed a sandwich to the man and, as...  0.256031  0.743969
2    Mary passed a sandwich to John and, as a result,  0.177621  0.822379
3    Alice passed a sandwich to Bob and, as a result,  0.344083  0.655917
4   The actress passed a sandwich to the actor and...  0.238474  0.761526
5   The girl passed a sandwich to the boy and, as ...  0.306402  0.693598
6   Mrs. Taylor passed a sandwich to Mr. Williams ...  0.137328  0.862672
7   Emma passed a sandwich to David and, as a result,  0.211199  0.788801
8   The princess passed a sandwich to the prince a...  0.288363  0.711637
9   Sarah passed a sandwich to Robert and, as a re...  0.192417  0.807583
10  Mrs. Williams passed a sandwich to  Mr. Taylor...  0.166732  0.833268
11  Emily passed a sandwich to Paul and, as a result,  0.247170  0.752830

In [455]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_19f,'he'))

P('subj-pron'|subj=female) =  0.22688559566934904
P('non-subj-pron'|subj=female) =  0.7731144030888876

In [456]:
c2_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_connective2_19f,'she')
c2_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_connective2_19f,'he')

#### male subject

In [457]:
transofposs_perfective_connective2_19m

                                             stimulus        he       she
12  Mr. Smith passed a sandwich to Miss Smith and,...  0.313537  0.686463
13  The man passed a sandwich to the woman and, as...  0.220297  0.779703
14   John passed a sandwich to Mary and, as a result,  0.280451  0.719549
15   Bob passed a sandwich to Alice and, as a result,  0.152600  0.847400
16  The actor passed a sandwich to the actress and...  0.238549  0.761451
17  The boy passed a sandwich to the girl and, as ...  0.265369  0.734631
18  Mr. William passed a sandwich to  Mrs. Taylor ...  0.308206  0.691794
19  David passed a sandwich to Emma and, as a result,  0.219906  0.780094
20  The prince passed a sandwich to the princess a...  0.237083  0.762917
21  Robert passed a sandwich to Sarah and, as a re...  0.261254  0.738746
22  Mr. Taylor passed a sandwich to Mrs. Williams ...  0.266170  0.733830
23  Paul passed a sandwich to Emily and, as a result,  0.155941  0.844059

In [458]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_19m,'she'))

P('subj-pron'|subj=male) =  0.24328013633688292
P('non-subj-pron'|subj=male) =  0.7567198723554611

In [459]:
c2_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_connective2_19m,'he')
c2_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_connective2_19m,'she')

### verb: "served"

In [460]:
transofposs_perfective_connective2_20 = pd.read_csv("../results/gpt2/transofposs_perfective/connective2/20.csv")
transofposs_perfective_connective2_20.head()

                                            stimulus        he       she
0  Miss Smith served a chili to Mr. Smith and, as...  0.897323  0.102677
1  The woman served a chili to the man and, as a ...  0.762090  0.237910
2      Mary served a chili to John and, as a result,  0.816033  0.183967
3      Alice served a chili to Bob and, as a result,  0.662116  0.337884
4  The actress served a chili to the actor and, a...  0.786055  0.213945

In [461]:
# female subject
transofposs_perfective_connective2_20f = transofposs_perfective_connective2_20[0:12]
transofposs_perfective_connective2_20f = transofposs_perfective_connective2_20f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_20m = transofposs_perfective_connective2_20[12:24]

#### female subject

In [462]:
transofposs_perfective_connective2_20f

                                             stimulus       she        he
0   Miss Smith served a chili to Mr. Smith and, as...  0.102677  0.897323
1   The woman served a chili to the man and, as a ...  0.237910  0.762090
2       Mary served a chili to John and, as a result,  0.183967  0.816033
3       Alice served a chili to Bob and, as a result,  0.337884  0.662116
4   The actress served a chili to the actor and, a...  0.213945  0.786055
5   The girl served a chili to the boy and, as a r...  0.264998  0.735002
6   Mrs. Taylor served a chili to Mr. Williams and...  0.092035  0.907965
7      Emma served a chili to David and, as a result,  0.196304  0.803696
8   The princess served a chili to the prince and,...  0.290180  0.709820
9    Sarah served a chili to Robert and, as a result,  0.183221  0.816779
10  Mrs. Williams served a chili to Mr. Taylor and...  0.119080  0.880920
11     Emily served a chili to Paul and, as a result,  0.281850  0.718150

In [463]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_20f,'he'))

P('subj-pron'|subj=female) =  0.20867097564041615
P('non-subj-pron'|subj=female) =  0.791329006354014

In [464]:
c2_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_connective2_20f,'she')
c2_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_connective2_20f,'he')

#### male subject

In [465]:
transofposs_perfective_connective2_20m

                                             stimulus        he       she
12  Mr. Smith served a chili to Miss Smith and, as...  0.231005  0.768995
13  The man served a chili to the woman and, as a ...  0.240586  0.759414
14      John served a chili to Mary and, as a result,  0.255896  0.744104
15      Bob served a chili to Alice and, as a result,  0.148257  0.851743
16  The actor served a chili to the actress and, a...  0.182505  0.817495
17  The boy served a chili to the girl and, as a r...  0.239234  0.760766
18  Mr. William served a chili to  Mrs. Taylor and...  0.320646  0.679354
19     David served a chili to Emma and, as a result,  0.203671  0.796329
20  The prince served a chili to the princess and,...  0.202636  0.797365
21   Robert served a chili to Sarah and, as a result,  0.267822  0.732178
22  Mr. Taylor served a chili to Mrs. Williams and...  0.218667  0.781333
23     Paul served a chili to Emily and, as a result,  0.164385  0.835615

In [466]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_20m,'she'))

P('subj-pron'|subj=male) =  0.22294233242670694
P('non-subj-pron'|subj=male) =  0.7770576675732931

In [467]:
c2_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_connective2_20m,'he')
c2_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_connective2_20m,'she')

## Summary of Results

In [468]:
c2_results_fsubj_subjpron = pd.DataFrame(list(c2_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c2_results_fsubj_objpron = pd.DataFrame(list(c2_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c2_results_fsubj = c2_results_fsubj_subjpron.merge(c2_results_fsubj_objpron)
c2_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0       chucked              0.250670             0.749330
1         flung              0.284311             0.715689
2        kicked              0.354113             0.645887
3        lobbed              0.253932             0.746068
4        rolled              0.560339             0.439661
5         threw              0.486398             0.513602
6        tossed              0.316436             0.683564
7       brought              0.209630             0.790370
8     forwarded              0.249965             0.750035
9        mailed              0.269311             0.730689
10      shipped              0.321122             0.678878
11  transmitted              0.204734             0.795266
12        wired              0.289682             0.710318
13      carried              0.465234             0.534766
14    delivered              0.169058             0.830942
15         gave              0.244510             0.755490
16       handed              0.238400             0.761600
17       passed              0.226886             0.773114
18       served              0.208671             0.791329

In [469]:
c2_results_msubj_subjpron = pd.DataFrame(list(c2_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c2_results_msubj_objpron = pd.DataFrame(list(c2_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c2_results_msubj = c2_results_msubj_subjpron.merge(c2_results_msubj_objpron)
c2_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0       chucked            0.213979           0.786021
1         flung            0.245275           0.754725
2        kicked            0.274730           0.725270
3        lobbed            0.177630           0.822370
4        rolled            0.285283           0.714717
5         threw            0.310733           0.689267
6        tossed            0.243272           0.756728
7       brought            0.184515           0.815485
8     forwarded            0.170910           0.829090
9        mailed            0.205751           0.794249
10      shipped            0.216380           0.783620
11  transmitted            0.206923           0.793077
12        wired            0.224196           0.775804
13      carried            0.337257           0.662743
14    delivered            0.157894           0.842106
15         gave            0.262087           0.737913
16       handed            0.201172           0.798828
17       passed            0.243280           0.756720
18       served            0.222942           0.777058

In [470]:
c2_results = c2_results_fsubj.merge(c2_results_msubj)
c2_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,chucked,0.250670,0.749330,0.213979,0.786021
1,flung,0.284311,0.715689,0.245275,0.754725
2,kicked,0.354113,0.645887,0.274730,0.725270
3,lobbed,0.253932,0.746068,0.177630,0.822370
4,rolled,0.560339,0.439661,0.285283,0.714717
5,threw,0.486398,0.513602,0.310733,0.689267
6,tossed,0.316436,0.683564,0.243272,0.756728
7,brought,0.209630,0.790370,0.184515,0.815485
8,forwarded,0.249965,0.750035,0.170910,0.829090
9,mailed,0.269311,0.730689,0.205751,0.794249
10,shipped,0.321122,0.678878,0.216380,0.783620
11,transmitted,0.204734,0.795266,0.206923,0.793077
12,wired,0.289682,0.710318,0.224196,0.775804
13,carried,0.465234,0.534766,0.337257,0.662743
14,delivered,0.169058,0.830942,0.157894,0.842106
15,gave,0.244510,0.755490,0.262087,0.737913
16,handed,0.238400,0.761600,0.201172,0.798828
17,passed,0.226886,0.773114,0.243280,0.756720
18,served,0.208671,0.791329,0.222942,0.777058

In [471]:
print("P(subj_reference |subj=female)", compute_average(c2_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c2_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.2949158555354204
P(obj_reference |subj=female) 0.7050841399713567

In [472]:
print("P(subj_reference |subj=male)", compute_average(c2_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c2_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.23074792433334024
P(obj_reference |subj=male) 0.7692520736079468

In [473]:
# save results to csv
col_headers = ['verb','subj_ref_female_subj','obj_ref_female_subj','subj_ref_male_subj','obj_ref_male_subj']
np_results.to_csv("../results/gpt2/summary/transofposs_perfective-noprompt.csv",index=False,header=col_headers)
c1_results.to_csv("../results/gpt2/summary/transofposs_perfective-connective1.csv",index=False,header=col_headers)
c2_results.to_csv("../results/gpt2/summary/transofposs_perfective-connective2.csv",index=False,header=col_headers)