In [1]:
import pandas as pd
import numpy as np

In [2]:
def compute_average(df,col):
    return np.mean(df[col].values)

## No-prompt

In [3]:
np_average_subj_female_subj_pron = {}
np_average_subj_female_obj_pron = {}
np_average_subj_male_subj_pron = {}
np_average_subj_male_obj_pron = {}

### Verb: "chucked" (NOTE: gets tokenized to 'unk')

In [4]:
transofposs_perfective_noprompt_1 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/1.csv")
transofposs_perfective_noprompt_1.head()

                                     stimulus        He       She
0   Miss Smith chucked a wrench to Mr. Smith.  0.235922  0.764078
1      The woman chucked a wrench to the man.  0.826104  0.173896
2              Mary chucked a wrench to John.  0.640590  0.359410
3              Alice chucked a wrench to Bob.  0.448256  0.551745
4  The actress chucked a wrench to the actor.  0.846662  0.153338

In [5]:
# female subject
transofposs_perfective_noprompt_1f = transofposs_perfective_noprompt_1[0:12]
transofposs_perfective_noprompt_1f = transofposs_perfective_noprompt_1f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_1m = transofposs_perfective_noprompt_1[12:24]

#### female subject

In [6]:
transofposs_perfective_noprompt_1f

                                         stimulus       She        He
0       Miss Smith chucked a wrench to Mr. Smith.  0.764078  0.235922
1          The woman chucked a wrench to the man.  0.173896  0.826104
2                  Mary chucked a wrench to John.  0.359410  0.640590
3                  Alice chucked a wrench to Bob.  0.551745  0.448256
4      The actress chucked a wrench to the actor.  0.153338  0.846662
5           The girl chucked a wrench to the boy.  0.173599  0.826401
6   Mrs. Taylor chucked a wrench to Mr. Williams.  0.790315  0.209685
7                 Emma chucked a wrench to David.  0.900048  0.099952
8    The princess chucked a wrench to the prince.  0.170355  0.829645
9               Sarah chucked a wrench to Robert.  0.519845  0.480155
10  Mrs. Williams chucked a wrench to Mr. Taylor.  0.628588  0.371412
11                Emily chucked a wrench to Paul.  0.526842  0.473158

In [7]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_1f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_1f,'He'))

P('subj-pron'|subj=female) =  0.47600482652584714
P('non-subj-pron'|subj=female) =  0.523995186512669

In [8]:
#np_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1f,'She')
#np_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1f,'He')

#### male subject

In [9]:
transofposs_perfective_noprompt_1m

                                         stimulus        He       She
12      Mr. Smith chucked a wrench to Miss Smith.  0.871038  0.128962
13         The man chucked a wrench to the woman.  0.890486  0.109514
14                 John chucked a wrench to Mary.  0.857151  0.142849
15                 Bob chucked a wrench to Alice.  0.396040  0.603960
16     The actor chucked a wrench to the actress.  0.877342  0.122658
17          The boy chucked a wrench to the girl.  0.883681  0.116319
18   Mr. William chucked a wrench to Mrs. Taylor.  0.592968  0.407033
19                David chucked a wrench to Emma.  0.166027  0.833973
20   The prince chucked a wrench to the princess.  0.884878  0.115122
21              Robert chucked a wrench to Sarah.  0.241629  0.758371
22  Mr. Taylor chucked a wrench to Mrs. Williams.  0.187180  0.812820
23                Paul chucked a wrench to Emily.  0.839077  0.160923

In [10]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_1m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_1m,'She'))

P('subj-pron'|subj=male) =  0.6406246287127336
P('non-subj-pron'|subj=male) =  0.35937535266081494

In [11]:
#np_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1m,'He')
#np_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_noprompt_1m,'She')

### Verb: "flung"

In [12]:
transofposs_perfective_noprompt_2 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/2.csv")
transofposs_perfective_noprompt_2.head()

                                    stimulus        He       She
0   Miss Smith flung a frisbee to Mr. Smith.  0.348062  0.651938
1      The woman flung a frisbee to the man.  0.827435  0.172565
2              Mary flung a frisbee to John.  0.804828  0.195172
3              Alice flung a frisbee to Bob.  0.830949  0.169051
4  The actress flung a frisbee to the actor.  0.847283  0.152717

In [13]:
# female subject
transofposs_perfective_noprompt_2f = transofposs_perfective_noprompt_2[0:12]
transofposs_perfective_noprompt_2f = transofposs_perfective_noprompt_2f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_2m = transofposs_perfective_noprompt_2[12:24]

#### female subject

In [14]:
transofposs_perfective_noprompt_2f

                                         stimulus       She        He
0        Miss Smith flung a frisbee to Mr. Smith.  0.651938  0.348062
1           The woman flung a frisbee to the man.  0.172565  0.827435
2                   Mary flung a frisbee to John.  0.195172  0.804828
3                   Alice flung a frisbee to Bob.  0.169051  0.830949
4       The actress flung a frisbee to the actor.  0.152717  0.847283
5            The girl flung a frisbee to the boy.  0.165339  0.834661
6    Mrs. Taylor flung a frisbee to Mr. Williams.  0.675904  0.324096
7                  Emma flung a frisbee to David.  0.179364  0.820636
8     The princess flung a frisbee to the prince.  0.163196  0.836804
9                Sarah flung a frisbee to Robert.  0.461891  0.538109
10  Mrs. Williams flung a frisbee to  Mr. Taylor.  0.524925  0.475075
11                 Emily flung a frisbee to Paul.  0.392674  0.607326

In [15]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_2f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_2f,'He'))

P('subj-pron'|subj=female) =  0.3253944789369901
P('non-subj-pron'|subj=female) =  0.6746055285135905

In [16]:
np_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2f,'She')
np_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2f,'He')

#### male subject

In [17]:
transofposs_perfective_noprompt_2m

                                        stimulus        He       She
12      Mr. Smith flung a frisbee to Miss Smith.  0.869496  0.130504
13         The man flung a frisbee to the woman.  0.891547  0.108453
14                 John flung a frisbee to Mary.  0.874662  0.125338
15                 Bob flung a frisbee to Alice.  0.868292  0.131708
16     The actor flung a frisbee to the actress.  0.886855  0.113145
17          The boy flung a frisbee to the girl.  0.885740  0.114260
18  Mr. William flung a frisbee to  Mrs. Taylor.  0.377479  0.622521
19                David flung a frisbee to Emma.  0.125841  0.874159
20   The prince flung a frisbee to the princess.  0.888303  0.111697
21              Robert flung a frisbee to Sarah.  0.182054  0.817946
22  Mr. Taylor flung a frisbee to Mrs. Williams.  0.186225  0.813775
23                Paul flung a frisbee to Emily.  0.856329  0.143671

In [18]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_2m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_2m,'She'))

P('subj-pron'|subj=male) =  0.6577352186044058
P('non-subj-pron'|subj=male) =  0.3422647813955943

In [19]:
np_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2m,'He')
np_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_noprompt_2m,'She')

### Verb: "kicked"

In [20]:
transofposs_perfective_noprompt_3 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/3.csv")
transofposs_perfective_noprompt_3.head()

                                         stimulus        He       She
0   Miss Smith kicked a soccer ball to Mr. Smith.  0.353249  0.646751
1      The woman kicked a soccer ball to the man.  0.806581  0.193419
2              Mary kicked a soccer ball to John.  0.792460  0.207540
3              Alice kicked a soccer ball to Bob.  0.813195  0.186805
4  The actress kicked a soccer ball to the actor.  0.833553  0.166447

In [21]:
# female subject
transofposs_perfective_noprompt_3f = transofposs_perfective_noprompt_3[0:12]
transofposs_perfective_noprompt_3f = transofposs_perfective_noprompt_3f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_3m = transofposs_perfective_noprompt_3[12:24]

#### female subject

In [22]:
transofposs_perfective_noprompt_3f

                                             stimulus       She        He
0       Miss Smith kicked a soccer ball to Mr. Smith.  0.646751  0.353249
1          The woman kicked a soccer ball to the man.  0.193419  0.806581
2                  Mary kicked a soccer ball to John.  0.207540  0.792460
3                  Alice kicked a soccer ball to Bob.  0.186805  0.813195
4      The actress kicked a soccer ball to the actor.  0.166447  0.833553
5           The girl kicked a soccer ball to the boy.  0.182214  0.817786
6   Mrs. Taylor kicked a soccer ball to Mr. Williams.  0.679757  0.320243
7                 Emma kicked a soccer ball to David.  0.179700  0.820300
8    The princess kicked a soccer ball to the prince.  0.184314  0.815686
9               Sarah kicked a soccer ball to Robert.  0.516914  0.483086
10  Mrs. Williams kicked a soccer ball to  Mr. Tay...  0.580806  0.419194
11                Emily kicked a soccer ball to Paul.  0.652218  0.347782

In [23]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_3f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_3f,'He'))

P('subj-pron'|subj=female) =  0.36474055672685307
P('non-subj-pron'|subj=female) =  0.6352594420313835

In [24]:
np_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3f,'She')
np_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3f,'He')

#### male subject

In [25]:
transofposs_perfective_noprompt_3m

                                             stimulus        He       She
12      Mr. Smith kicked a soccer ball to Miss Smith.  0.866960  0.133040
13         The man kicked a soccer ball to the woman.  0.888854  0.111146
14                 John kicked a soccer ball to Mary.  0.881491  0.118509
15                 Bob kicked a soccer ball to Alice.  0.876264  0.123736
16     The actor kicked a soccer ball to the actress.  0.883064  0.116936
17          The boy kicked a soccer ball to the girl.  0.882366  0.117634
18  Mr. William kicked a soccer ball to  Mrs. Taylor.  0.355765  0.644235
19                David kicked a soccer ball to Emma.  0.861316  0.138684
20   The prince kicked a soccer ball to the princess.  0.885479  0.114521
21              Robert kicked a soccer ball to Sarah.  0.267029  0.732971
22  Mr. Taylor kicked a soccer ball to Mrs. Williams.  0.187445  0.812555
23                Paul kicked a soccer ball to Emily.  0.863846  0.136154

In [26]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_3m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_3m,'She'))

P('subj-pron'|subj=male) =  0.7249898438652357
P('non-subj-pron'|subj=male) =  0.2750101728985707

In [27]:
np_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3m,'He')
np_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_noprompt_3m,'She')

### verb: "lobbed"

In [28]:
transofposs_perfective_noprompt_4 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/4.csv")
transofposs_perfective_noprompt_4.head()

                                      stimulus        He       She
0   Miss Smith lobbed a football to Mr. Smith.  0.357503  0.642497
1      The woman lobbed a football to the man.  0.824881  0.175119
2              Mary lobbed a football to John.  0.808805  0.191195
3              Alice lobbed a football to Bob.  0.888319  0.111681
4  The actress lobbed a football to the actor.  0.840282  0.159718

In [29]:
# female subject
transofposs_perfective_noprompt_4f = transofposs_perfective_noprompt_4[0:12]
transofposs_perfective_noprompt_4f = transofposs_perfective_noprompt_4f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_4m = transofposs_perfective_noprompt_4[12:24]

#### female subject

In [30]:
transofposs_perfective_noprompt_4f

                                           stimulus       She        He
0        Miss Smith lobbed a football to Mr. Smith.  0.642497  0.357503
1           The woman lobbed a football to the man.  0.175119  0.824881
2                   Mary lobbed a football to John.  0.191195  0.808805
3                   Alice lobbed a football to Bob.  0.111681  0.888319
4       The actress lobbed a football to the actor.  0.159718  0.840282
5            The girl lobbed a football to the boy.  0.170777  0.829223
6    Mrs. Taylor lobbed a football to Mr. Williams.  0.682002  0.317998
7                  Emma lobbed a football to David.  0.179010  0.820990
8     The princess lobbed a football to the prince.  0.168817  0.831183
9                Sarah lobbed a football to Robert.  0.369653  0.630347
10  Mrs. Williams lobbed a football to  Mr. Taylor.  0.560610  0.439390
11                 Emily lobbed a football to Paul.  0.514933  0.485067

In [31]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_4f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_4f,'He'))

P('subj-pron'|subj=female) =  0.32716764447589713
P('non-subj-pron'|subj=female) =  0.6728323424855868

In [32]:
np_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4f,'She')
np_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4f,'He')

#### male subject

In [33]:
transofposs_perfective_noprompt_4m

                                          stimulus        He       She
12      Mr. Smith lobbed a football to Miss Smith.  0.867906  0.132094
13         The man lobbed a football to the woman.  0.889922  0.110078
14                 John lobbed a football to Mary.  0.873743  0.126257
15                 Bob lobbed a football to Alice.  0.512220  0.487780
16     The actor lobbed a football to the actress.  0.883476  0.116524
17          The boy lobbed a football to the girl.  0.883186  0.116814
18  Mr. William lobbed a football to  Mrs. Taylor.  0.385963  0.614037
19                David lobbed a football to Emma.  0.153112  0.846888
20   The prince lobbed a football to the princess.  0.886647  0.113353
21              Robert lobbed a football to Sarah.  0.132683  0.867317
22  Mr. Taylor lobbed a football to Mrs. Williams.  0.201998  0.798002
23                Paul lobbed a football to Emily.  0.855602  0.144398

In [34]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_4m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_4m,'She'))

P('subj-pron'|subj=male) =  0.6272048602501551
P('non-subj-pron'|subj=male) =  0.3727951354036729

In [35]:
np_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4m,'He')
np_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_4m,'She')

### verb: "rolled"

In [36]:
transofposs_perfective_noprompt_5 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/5.csv")
transofposs_perfective_noprompt_5.head()

                                       stimulus        He       She
0   Miss Smith rolled a toy truck to Mr. Smith.  0.274985  0.725015
1      The woman rolled a toy truck to the man.  0.803928  0.196072
2              Mary rolled a toy truck to John.  0.519925  0.480075
3              Alice rolled a toy truck to Bob.  0.339838  0.660162
4  The actress rolled a toy truck to the actor.  0.826966  0.173034

In [37]:
# female subject
transofposs_perfective_noprompt_5f = transofposs_perfective_noprompt_5[0:12]
transofposs_perfective_noprompt_5f = transofposs_perfective_noprompt_5f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_5m = transofposs_perfective_noprompt_5[12:24]

#### female subject

In [38]:
transofposs_perfective_noprompt_5f

                                            stimulus       She        He
0        Miss Smith rolled a toy truck to Mr. Smith.  0.725015  0.274985
1           The woman rolled a toy truck to the man.  0.196072  0.803928
2                   Mary rolled a toy truck to John.  0.480075  0.519925
3                   Alice rolled a toy truck to Bob.  0.660162  0.339838
4       The actress rolled a toy truck to the actor.  0.173034  0.826966
5            The girl rolled a toy truck to the boy.  0.187187  0.812813
6    Mrs. Taylor rolled a toy truck to Mr. Williams.  0.801486  0.198514
7                  Emma rolled a toy truck to David.  0.186642  0.813358
8     The princess rolled a toy truck to the prince.  0.190923  0.809077
9                Sarah rolled a toy truck to Robert.  0.787032  0.212968
10  Mrs. Williams rolled a toy truck to  Mr. Taylor.  0.660010  0.339990
11                 Emily rolled a toy truck to Paul.  0.169293  0.830706

In [39]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_5f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_5f,'He'))

P('subj-pron'|subj=female) =  0.43474422271053
P('non-subj-pron'|subj=female) =  0.5652557599047819

In [40]:
np_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_5f,'She')
np_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_noprompt_5f,'He')

#### male subject

In [41]:
transofposs_perfective_noprompt_5m

                                           stimulus        He       She
12      Mr. Smith rolled a toy truck to Miss Smith.  0.867642  0.132358
13         The man rolled a toy truck to the woman.  0.890622  0.109378
14                 John rolled a toy truck to Mary.  0.881025  0.118975
15                 Bob rolled a toy truck to Alice.  0.877431  0.122569
16     The actor rolled a toy truck to the actress.  0.883325  0.116675
17          The boy rolled a toy truck to the girl.  0.878384  0.121616
18  Mr. William rolled a toy truck to  Mrs. Taylor.  0.416800  0.583200
19                David rolled a toy truck to Emma.  0.857952  0.142048
20   The prince rolled a toy truck to the princess.  0.884155  0.115845
21              Robert rolled a toy truck to Sarah.  0.393231  0.606769
22  Mr. Taylor rolled a toy truck to Mrs. Williams.  0.147921  0.852079
23                Paul rolled a toy truck to Emily.  0.869612  0.130388

In [42]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_5m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_5m,'She'))

P('subj-pron'|subj=male) =  0.737341703226169
P('non-subj-pron'|subj=male) =  0.26265830049912137

In [43]:
np_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_noprompt_5m,'He')
np_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_noprompt_5m,'She')

### verb: "threw"

In [44]:
transofposs_perfective_noprompt_6 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/6.csv")
transofposs_perfective_noprompt_6.head()

                                stimulus        He       She
0   Miss Smith threw a hat to Mr. Smith.  0.325871  0.674129
1      The woman threw a hat to the man.  0.824942  0.175058
2              Mary threw a hat to John.  0.685381  0.314619
3              Alice threw a hat to Bob.  0.687074  0.312926
4  The actress threw a hat to the actor.  0.842843  0.157157

In [45]:
# female subject
transofposs_perfective_noprompt_6f = transofposs_perfective_noprompt_6[0:12]
transofposs_perfective_noprompt_6f = transofposs_perfective_noprompt_6f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_6m = transofposs_perfective_noprompt_6[12:24]

#### female subject

In [46]:
transofposs_perfective_noprompt_6f

                                     stimulus       She        He
0        Miss Smith threw a hat to Mr. Smith.  0.674129  0.325871
1           The woman threw a hat to the man.  0.175058  0.824942
2                   Mary threw a hat to John.  0.314619  0.685381
3                   Alice threw a hat to Bob.  0.312926  0.687074
4       The actress threw a hat to the actor.  0.157157  0.842843
5            The girl threw a hat to the boy.  0.168764  0.831236
6    Mrs. Taylor threw a hat to Mr. Williams.  0.746846  0.253154
7                  Emma threw a hat to David.  0.185664  0.814336
8     The princess threw a hat to the prince.  0.166788  0.833212
9                Sarah threw a hat to Robert.  0.583833  0.416167
10  Mrs. Williams threw a hat to  Mr. Taylor.  0.594426  0.405575
11                 Emily threw a hat to Paul.  0.624753  0.375247

In [47]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_6f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_6f,'He'))

P('subj-pron'|subj=female) =  0.39208009590705234
P('non-subj-pron'|subj=female) =  0.6079199090600014

In [48]:
np_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6f,'She')
np_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6f,'He')

#### male subject

In [49]:
transofposs_perfective_noprompt_6m

                                    stimulus        He       She
12      Mr. Smith threw a hat to Miss Smith.  0.869234  0.130766
13         The man threw a hat to the woman.  0.891664  0.108336
14                 John threw a hat to Mary.  0.874941  0.125059
15                 Bob threw a hat to Alice.  0.867972  0.132028
16     The actor threw a hat to the actress.  0.884325  0.115675
17          The boy threw a hat to the girl.  0.885919  0.114081
18  Mr. William threw a hat to  Mrs. Taylor.  0.346010  0.653990
19                David threw a hat to Emma.  0.253675  0.746325
20   The prince threw a hat to the princess.  0.886438  0.113562
21              Robert threw a hat to Sarah.  0.159699  0.840301
22  Mr. Taylor threw a hat to Mrs. Williams.  0.169161  0.830839
23                Paul threw a hat to Emily.  0.857280  0.142720

In [50]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_6m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_6m,'She'))

P('subj-pron'|subj=male) =  0.6621932225922743
P('non-subj-pron'|subj=male) =  0.33780678982536

In [51]:
np_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6m,'He')
np_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_noprompt_6m,'She')

### verb: "tossed"

In [52]:
transofposs_perfective_noprompt_7 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/7.csv")
transofposs_perfective_noprompt_7.head()

                                        stimulus        He       She
0   Miss Smith tossed a dish towel to Mr. Smith.  0.347924  0.652076
1      The woman tossed a dish towel to the man.  0.807853  0.192147
2              Mary tossed a dish towel to John.  0.649616  0.350384
3              Alice tossed a dish towel to Bob.  0.689577  0.310423
4  The actress tossed a dish towel to the actor.  0.829946  0.170054

In [53]:
# female subject
transofposs_perfective_noprompt_7f = transofposs_perfective_noprompt_7[0:12]
transofposs_perfective_noprompt_7f = transofposs_perfective_noprompt_7f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_7m = transofposs_perfective_noprompt_7[12:24]

#### female subject

In [54]:
transofposs_perfective_noprompt_7f

                                             stimulus       She        He
0        Miss Smith tossed a dish towel to Mr. Smith.  0.652076  0.347924
1           The woman tossed a dish towel to the man.  0.192147  0.807853
2                   Mary tossed a dish towel to John.  0.350384  0.649616
3                   Alice tossed a dish towel to Bob.  0.310423  0.689577
4       The actress tossed a dish towel to the actor.  0.170054  0.829946
5            The girl tossed a dish towel to the boy.  0.182972  0.817028
6    Mrs. Taylor tossed a dish towel to Mr. Williams.  0.705345  0.294655
7                  Emma tossed a dish towel to David.  0.182672  0.817327
8     The princess tossed a dish towel to the prince.  0.184582  0.815418
9                Sarah tossed a dish towel to Robert.  0.549396  0.450604
10  Mrs. Williams tossed a dish towel to  Mr. Taylor.  0.583970  0.416030
11                 Emily tossed a dish towel to Paul.  0.497968  0.502032

In [55]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_7f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_7f,'He'))

P('subj-pron'|subj=female) =  0.3801657321552436
P('non-subj-pron'|subj=female) =  0.6198342790206274

In [56]:
np_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7f,'She')
np_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7f,'He')

#### male subject

In [57]:
transofposs_perfective_noprompt_7m

                                            stimulus        He       She
12      Mr. Smith tossed a dish towel to Miss Smith.  0.868195  0.131805
13         The man tossed a dish towel to the woman.  0.889961  0.110039
14                 John tossed a dish towel to Mary.  0.882468  0.117532
15                 Bob tossed a dish towel to Alice.  0.876220  0.123780
16     The actor tossed a dish towel to the actress.  0.881360  0.118641
17          The boy tossed a dish towel to the girl.  0.881116  0.118884
18  Mr. William tossed a dish towel to  Mrs. Taylor.  0.322376  0.677624
19                David tossed a dish towel to Emma.  0.100091  0.899909
20   The prince tossed a dish towel to the princess.  0.881968  0.118032
21              Robert tossed a dish towel to Sarah.  0.133869  0.866131
22  Mr. Taylor tossed a dish towel to Mrs. Williams.  0.161187  0.838813
23                Paul tossed a dish towel to Emily.  0.866883  0.133117

In [58]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_7m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_7m,'She'))

P('subj-pron'|subj=male) =  0.6454746002952257
P('non-subj-pron'|subj=male) =  0.3545254282653332

In [59]:
np_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7m,'He')
np_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_noprompt_7m,'She')

### verb: "brought"

In [60]:
transofposs_perfective_noprompt_8 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/8.csv")
transofposs_perfective_noprompt_8.head()

                                            stimulus        He       She
0  Miss Smith brought a glass of water to Mr. Smith.  0.389591  0.610409
1     The woman brought a glass of water to the man.  0.778322  0.221678
2             Mary brought a glass of water to John.  0.491599  0.508401
3             Alice brought a glass of water to Bob.  0.426335  0.573665
4  The actress brought a glass of water to the ac...  0.798962  0.201038

In [61]:
# female subject
transofposs_perfective_noprompt_8f = transofposs_perfective_noprompt_8[0:12]
transofposs_perfective_noprompt_8f = transofposs_perfective_noprompt_8f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_8m = transofposs_perfective_noprompt_8[12:24]

#### female subject

In [62]:
transofposs_perfective_noprompt_8f

                                             stimulus       She        He
0   Miss Smith brought a glass of water to Mr. Smith.  0.610409  0.389591
1      The woman brought a glass of water to the man.  0.221678  0.778322
2              Mary brought a glass of water to John.  0.508401  0.491599
3              Alice brought a glass of water to Bob.  0.573665  0.426335
4   The actress brought a glass of water to the ac...  0.201038  0.798962
5       The girl brought a glass of water to the boy.  0.212859  0.787141
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.696832  0.303168
7             Emma brought a glass of water to David.  0.215132  0.784869
8   The princess brought a glass of water to the p...  0.220057  0.779943
9           Sarah brought a glass of water to Robert.  0.660035  0.339965
10  Mrs. Williams brought a glass of water to  Mr....  0.577699  0.422302
11            Emily brought a glass of water to Paul.  0.639685  0.360315

In [63]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_8f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_8f,'He'))

P('subj-pron'|subj=female) =  0.44479063029090565
P('non-subj-pron'|subj=female) =  0.5552093957861265

In [64]:
np_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8f,'She')
np_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8f,'He')

#### male subject

In [65]:
transofposs_perfective_noprompt_8m

                                             stimulus        He       She
12  Mr. Smith brought a glass of water to Miss Smith.  0.865289  0.134711
13     The man brought a glass of water to the woman.  0.891014  0.108986
14             John brought a glass of water to Mary.  0.884218  0.115782
15             Bob brought a glass of water to Alice.  0.877615  0.122385
16  The actor brought a glass of water to the actr...  0.876903  0.123097
17      The boy brought a glass of water to the girl.  0.879796  0.120204
18  Mr. William brought a glass of water to  Mrs. ...  0.355231  0.644769
19            David brought a glass of water to Emma.  0.264142  0.735858
20  The prince brought a glass of water to the pri...  0.880578  0.119422
21          Robert brought a glass of water to Sarah.  0.232098  0.767902
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.166579  0.833421
23            Paul brought a glass of water to Emily.  0.870773  0.129227

In [66]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_8m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_8m,'She'))

P('subj-pron'|subj=male) =  0.6703529941538969
P('non-subj-pron'|subj=male) =  0.32964700398345786

In [67]:
np_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8m,'He')
np_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_noprompt_8m,'She')

### verb: "forwarded"

In [68]:
transofposs_perfective_noprompt_9 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/9.csv")
transofposs_perfective_noprompt_9.head()

                                            stimulus        He       She
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.208054  0.791946
1    The woman forwarded a gossipy email to the man.  0.800841  0.199159
2            Mary forwarded a gossipy email to John.  0.745312  0.254688
3            Alice forwarded a gossipy email to Bob.  0.729229  0.270771
4  The actress forwarded a gossipy email to the a...  0.812977  0.187023

In [69]:
# female subject
transofposs_perfective_noprompt_9f = transofposs_perfective_noprompt_9[0:12]
transofposs_perfective_noprompt_9f = transofposs_perfective_noprompt_9f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_9m = transofposs_perfective_noprompt_9[12:24]

#### female subject

In [70]:
transofposs_perfective_noprompt_9f

                                             stimulus       She        He
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.791946  0.208054
1     The woman forwarded a gossipy email to the man.  0.199159  0.800841
2             Mary forwarded a gossipy email to John.  0.254688  0.745312
3             Alice forwarded a gossipy email to Bob.  0.270771  0.729229
4   The actress forwarded a gossipy email to the a...  0.187023  0.812977
5      The girl forwarded a gossipy email to the boy.  0.195522  0.804478
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.795113  0.204887
7            Emma forwarded a gossipy email to David.  0.226098  0.773902
8   The princess forwarded a gossipy email to the ...  0.203254  0.796746
9          Sarah forwarded a gossipy email to Robert.  0.462638  0.537362
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.719557  0.280443
11           Emily forwarded a gossipy email to Paul.  0.387689  0.612311

In [71]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_9f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_9f,'He'))

P('subj-pron'|subj=female) =  0.39112140983343124
P('non-subj-pron'|subj=female) =  0.6088786125183105

In [72]:
np_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9f,'She')
np_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9f,'He')

#### male subject

In [73]:
transofposs_perfective_noprompt_9m

                                             stimulus        He       She
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.858925  0.141075
13    The man forwarded a gossipy email to the woman.  0.885176  0.114824
14            John forwarded a gossipy email to Mary.  0.873923  0.126077
15            Bob forwarded a gossipy email to Alice.  0.370592  0.629408
16  The actor forwarded a gossipy email to the act...  0.876998  0.123002
17     The boy forwarded a gossipy email to the girl.  0.874256  0.125744
18  Mr. William forwarded a gossipy email to  Mrs....  0.310680  0.689320
19           David forwarded a gossipy email to Emma.  0.087074  0.912926
20  The prince forwarded a gossipy email to the pr...  0.879450  0.120550
21         Robert forwarded a gossipy email to Sarah.  0.238579  0.761421
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.121513  0.878487
23           Paul forwarded a gossipy email to Emily.  0.845841  0.154159

In [74]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_9m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_9m,'She'))

P('subj-pron'|subj=male) =  0.60191735252738
P('non-subj-pron'|subj=male) =  0.39808263443410397

In [75]:
np_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9m,'He')
np_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_noprompt_9m,'She')

### verb: "mailed"

In [76]:
transofposs_perfective_noprompt_10 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/10.csv")
transofposs_perfective_noprompt_10.head()

                                    stimulus        He       She
0   Miss Smith mailed a letter to Mr. Smith.  0.129193  0.870807
1      The woman mailed a letter to the man.  0.812676  0.187324
2              Mary mailed a letter to John.  0.778813  0.221187
3              Alice mailed a letter to Bob.  0.747157  0.252843
4  The actress mailed a letter to the actor.  0.813931  0.186069

In [77]:
# female subject
transofposs_perfective_noprompt_10f = transofposs_perfective_noprompt_10[0:12]
transofposs_perfective_noprompt_10f = transofposs_perfective_noprompt_10f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_10m = transofposs_perfective_noprompt_10[12:24]

#### female subject

In [78]:
transofposs_perfective_noprompt_10f

                                         stimulus       She        He
0        Miss Smith mailed a letter to Mr. Smith.  0.870807  0.129193
1           The woman mailed a letter to the man.  0.187324  0.812676
2                   Mary mailed a letter to John.  0.221187  0.778813
3                   Alice mailed a letter to Bob.  0.252843  0.747157
4       The actress mailed a letter to the actor.  0.186069  0.813931
5            The girl mailed a letter to the boy.  0.187449  0.812551
6    Mrs. Taylor mailed a letter to Mr. Williams.  0.797148  0.202852
7                  Emma mailed a letter to David.  0.940952  0.059048
8     The princess mailed a letter to the prince.  0.196522  0.803478
9                Sarah mailed a letter to Robert.  0.329456  0.670544
10  Mrs. Williams mailed a letter to  Mr. Taylor.  0.728360  0.271639
11                 Emily mailed a letter to Paul.  0.509363  0.490637

In [79]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_10f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_10f,'He'))

P('subj-pron'|subj=female) =  0.45062339926759404
P('non-subj-pron'|subj=female) =  0.549376607251664

In [80]:
np_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10f,'She')
np_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10f,'He')

#### male subject

In [81]:
transofposs_perfective_noprompt_10m

                                        stimulus        He       She
12      Mr. Smith mailed a letter to Miss Smith.  0.856056  0.143944
13         The man mailed a letter to the woman.  0.887319  0.112681
14                 John mailed a letter to Mary.  0.870860  0.129140
15                 Bob mailed a letter to Alice.  0.362775  0.637225
16     The actor mailed a letter to the actress.  0.883070  0.116930
17          The boy mailed a letter to the girl.  0.882247  0.117753
18  Mr. William mailed a letter to  Mrs. Taylor.  0.417936  0.582064
19                David mailed a letter to Emma.  0.135779  0.864221
20   The prince mailed a letter to the princess.  0.886600  0.113400
21              Robert mailed a letter to Sarah.  0.161831  0.838169
22  Mr. Taylor mailed a letter to Mrs. Williams.  0.158367  0.841633
23                Paul mailed a letter to Emily.  0.839679  0.160321

In [82]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_10m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_10m,'She'))

P('subj-pron'|subj=male) =  0.6118765870730082
P('non-subj-pron'|subj=male) =  0.38812342782815296

In [83]:
np_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10m,'He')
np_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_noprompt_10m,'She')

### verb: "shipped"

In [84]:
transofposs_perfective_noprompt_11 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/11.csv")
transofposs_perfective_noprompt_11.head()

                                      stimulus        He       She
0   Miss Smith shipped a package to Mr. Smith.  0.136107  0.863893
1      The woman shipped a package to the man.  0.812126  0.187874
2              Mary shipped a package to John.  0.660532  0.339468
3              Alice shipped a package to Bob.  0.638420  0.361580
4  The actress shipped a package to the actor.  0.812409  0.187591

In [85]:
# female subject
transofposs_perfective_noprompt_11f = transofposs_perfective_noprompt_11[0:12]
transofposs_perfective_noprompt_11f = transofposs_perfective_noprompt_11f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_11m = transofposs_perfective_noprompt_11[12:24]

#### female subject

In [86]:
transofposs_perfective_noprompt_11f

                                           stimulus       She        He
0        Miss Smith shipped a package to Mr. Smith.  0.863893  0.136107
1           The woman shipped a package to the man.  0.187874  0.812126
2                   Mary shipped a package to John.  0.339468  0.660532
3                   Alice shipped a package to Bob.  0.361580  0.638420
4       The actress shipped a package to the actor.  0.187591  0.812409
5            The girl shipped a package to the boy.  0.193039  0.806961
6    Mrs. Taylor shipped a package to Mr. Williams.  0.767878  0.232122
7                  Emma shipped a package to David.  0.249004  0.750996
8     The princess shipped a package to the prince.  0.200825  0.799174
9                Sarah shipped a package to Robert.  0.546277  0.453723
10  Mrs. Williams shipped a package to  Mr. Taylor.  0.672389  0.327611
11                 Emily shipped a package to Paul.  0.609076  0.390924

In [87]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_11f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_11f,'He'))

P('subj-pron'|subj=female) =  0.4315744328002135
P('non-subj-pron'|subj=female) =  0.5684255721668402

In [88]:
np_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11f,'She')
np_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11f,'He')

#### male subject

In [89]:
transofposs_perfective_noprompt_11m

                                          stimulus        He       She
12      Mr. Smith shipped a package to Miss Smith.  0.852725  0.147275
13         The man shipped a package to the woman.  0.883032  0.116968
14                 John shipped a package to Mary.  0.857072  0.142928
15                 Bob shipped a package to Alice.  0.399790  0.600210
16     The actor shipped a package to the actress.  0.873681  0.126319
17          The boy shipped a package to the girl.  0.868334  0.131666
18  Mr. William shipped a package to  Mrs. Taylor.  0.290651  0.709349
19                David shipped a package to Emma.  0.041602  0.958398
20   The prince shipped a package to the princess.  0.875123  0.124877
21              Robert shipped a package to Sarah.  0.192670  0.807330
22  Mr. Taylor shipped a package to Mrs. Williams.  0.108001  0.891999
23                Paul shipped a package to Emily.  0.826961  0.173039

In [90]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_11m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_11m,'She'))

P('subj-pron'|subj=male) =  0.5891369649519523
P('non-subj-pron'|subj=male) =  0.41086302883923054

In [91]:
np_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11m,'He')
np_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_noprompt_11m,'She')

### verb: "transmitted"

In [92]:
transofposs_perfective_noprompt_12 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/12.csv")
transofposs_perfective_noprompt_12.head()

                                          stimulus        He       She
0   Miss Smith transmitted a message to Mr. Smith.  0.188234  0.811766
1      The woman transmitted a message to the man.  0.811751  0.188249
2              Mary transmitted a message to John.  0.768318  0.231682
3              Alice transmitted a message to Bob.  0.829270  0.170730
4  The actress transmitted a message to the actor.  0.823745  0.176255

In [93]:
# female subject
transofposs_perfective_noprompt_12f = transofposs_perfective_noprompt_12[0:12]
transofposs_perfective_noprompt_12f = transofposs_perfective_noprompt_12f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_12m = transofposs_perfective_noprompt_12[12:24]

#### female subject

In [94]:
transofposs_perfective_noprompt_12f

                                             stimulus       She        He
0      Miss Smith transmitted a message to Mr. Smith.  0.811766  0.188234
1         The woman transmitted a message to the man.  0.188249  0.811751
2                 Mary transmitted a message to John.  0.231682  0.768318
3                 Alice transmitted a message to Bob.  0.170730  0.829270
4     The actress transmitted a message to the actor.  0.176255  0.823745
5          The girl transmitted a message to the boy.  0.187308  0.812692
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.744860  0.255140
7                Emma transmitted a message to David.  0.926839  0.073161
8   The princess transmitted a message to the prince.  0.190645  0.809355
9              Sarah transmitted a message to Robert.  0.357119  0.642881
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.679712  0.320288
11               Emily transmitted a message to Paul.  0.411869  0.588131

In [95]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_12f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_12f,'He'))

P('subj-pron'|subj=female) =  0.42308614030480385
P('non-subj-pron'|subj=female) =  0.5769138503819704

In [96]:
np_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12f,'She')
np_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12f,'He')

#### male subject

In [97]:
transofposs_perfective_noprompt_12m

                                             stimulus        He       She
12     Mr. Smith transmitted a message to Miss Smith.  0.855525  0.144475
13        The man transmitted a message to the woman.  0.886698  0.113302
14                John transmitted a message to Mary.  0.865406  0.134594
15                Bob transmitted a message to Alice.  0.245864  0.754136
16    The actor transmitted a message to the actress.  0.879413  0.120587
17         The boy transmitted a message to the girl.  0.876583  0.123417
18  Mr. William transmitted a message to  Mrs. Tay...  0.333891  0.666109
19               David transmitted a message to Emma.  0.031951  0.968049
20  The prince transmitted a message to the princess.  0.881738  0.118262
21             Robert transmitted a message to Sarah.  0.070152  0.929848
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.117860  0.882140
23               Paul transmitted a message to Emily.  0.838976  0.161024

In [98]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_12m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_12m,'She'))

P('subj-pron'|subj=male) =  0.573671397442619
P('non-subj-pron'|subj=male) =  0.4263286118706067

In [99]:
np_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12m,'He')
np_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_noprompt_12m,'She')

### verb: "wired"

In [100]:
transofposs_perfective_noprompt_14 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/14.csv")
transofposs_perfective_noprompt_14.head()

                                stimulus        He       She
0   Miss Smith wired money to Mr. Smith.  0.206095  0.793905
1      The woman wired money to the man.  0.814641  0.185359
2              Mary wired money to John.  0.782995  0.217005
3              Alice wired money to Bob.  0.830609  0.169391
4  The actress wired money to the actor.  0.824792  0.175208

In [101]:
# female subject
transofposs_perfective_noprompt_14f = transofposs_perfective_noprompt_14[0:12]
transofposs_perfective_noprompt_14f = transofposs_perfective_noprompt_14f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_14m = transofposs_perfective_noprompt_14[12:24]

#### female subject

In [102]:
transofposs_perfective_noprompt_14f

                                     stimulus       She        He
0        Miss Smith wired money to Mr. Smith.  0.793905  0.206095
1           The woman wired money to the man.  0.185359  0.814641
2                   Mary wired money to John.  0.217005  0.782995
3                   Alice wired money to Bob.  0.169391  0.830609
4       The actress wired money to the actor.  0.175208  0.824792
5            The girl wired money to the boy.  0.175643  0.824357
6    Mrs. Taylor wired money to Mr. Williams.  0.739207  0.260793
7                  Emma wired money to David.  0.824540  0.175460
8     The princess wired money to the prince.  0.176915  0.823085
9                Sarah wired money to Robert.  0.543604  0.456396
10  Mrs. Williams wired money to  Mr. Taylor.  0.625551  0.374449
11                 Emily wired money to Paul.  0.378742  0.621258

In [103]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_14f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_14f,'He'))

P('subj-pron'|subj=female) =  0.41708915928999585
P('non-subj-pron'|subj=female) =  0.582910834501187

In [104]:
np_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14f,'She')
np_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14f,'He')

#### male subject

In [105]:
transofposs_perfective_noprompt_14m

                                    stimulus        He       She
12      Mr. Smith wired money to Miss Smith.  0.391228  0.608772
13         The man wired money to the woman.  0.889394  0.110606
14                 John wired money to Mary.  0.869190  0.130810
15                 Bob wired money to Alice.  0.174995  0.825005
16     The actor wired money to the actress.  0.885237  0.114763
17          The boy wired money to the girl.  0.885913  0.114087
18  Mr. William wired money to  Mrs. Taylor.  0.341431  0.658568
19                David wired money to Emma.  0.087474  0.912526
20   The prince wired money to the princess.  0.888351  0.111649
21              Robert wired money to Sarah.  0.167480  0.832520
22  Mr. Taylor wired money to Mrs. Williams.  0.139089  0.860911
23                Paul wired money to Emily.  0.842400  0.157600

In [106]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_14m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_14m,'She'))

P('subj-pron'|subj=male) =  0.546848651021719
P('non-subj-pron'|subj=male) =  0.453151340285937

In [107]:
np_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14m,'He')
np_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_noprompt_14m,'She')

### verb: "carried"

In [108]:
transofposs_perfective_noprompt_15 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/15.csv")
transofposs_perfective_noprompt_15.head()

                                   stimulus        He       She
0   Miss Smith carried a tray to Mr. Smith.  0.243845  0.756155
1      The woman carried a tray to the man.  0.819455  0.180545
2              Mary carried a tray to John.  0.672541  0.327459
3              Alice carried a tray to Bob.  0.467826  0.532174
4  The actress carried a tray to the actor.  0.834219  0.165781

In [109]:
# female subject
transofposs_perfective_noprompt_15f = transofposs_perfective_noprompt_15[0:12]
transofposs_perfective_noprompt_15f = transofposs_perfective_noprompt_15f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_15m = transofposs_perfective_noprompt_15[12:24]

#### female subject

In [110]:
transofposs_perfective_noprompt_15f

                                        stimulus       She        He
0        Miss Smith carried a tray to Mr. Smith.  0.756155  0.243845
1           The woman carried a tray to the man.  0.180545  0.819455
2                   Mary carried a tray to John.  0.327459  0.672541
3                   Alice carried a tray to Bob.  0.532174  0.467826
4       The actress carried a tray to the actor.  0.165781  0.834219
5            The girl carried a tray to the boy.  0.175894  0.824106
6    Mrs. Taylor carried a tray to Mr. Williams.  0.777504  0.222496
7                  Emma carried a tray to David.  0.198670  0.801330
8     The princess carried a tray to the prince.  0.175435  0.824565
9                Sarah carried a tray to Robert.  0.612781  0.387219
10  Mrs. Williams carried a tray to  Mr. Taylor.  0.649622  0.350378
11                 Emily carried a tray to Paul.  0.558937  0.441063

In [111]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_15f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_15f,'He'))

P('subj-pron'|subj=female) =  0.42591320474942523
P('non-subj-pron'|subj=female) =  0.5740868163605531

In [112]:
np_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15f,'She')
np_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15f,'He')

#### male subject

In [113]:
transofposs_perfective_noprompt_15m

                                       stimulus        He       She
12      Mr. Smith carried a tray to Miss Smith.  0.866820  0.133180
13         The man carried a tray to the woman.  0.891012  0.108988
14                 John carried a tray to Mary.  0.871948  0.128052
15                 Bob carried a tray to Alice.  0.863630  0.136370
16     The actor carried a tray to the actress.  0.881565  0.118435
17          The boy carried a tray to the girl.  0.881835  0.118165
18  Mr. William carried a tray to  Mrs. Taylor.  0.345319  0.654681
19                David carried a tray to Emma.  0.086158  0.913842
20   The prince carried a tray to the princess.  0.885878  0.114122
21              Robert carried a tray to Sarah.  0.413151  0.586849
22  Mr. Taylor carried a tray to Mrs. Williams.  0.172944  0.827056
23                Paul carried a tray to Emily.  0.848182  0.151818

In [114]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_15m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_15m,'She'))

P('subj-pron'|subj=male) =  0.6673701945692301
P('non-subj-pron'|subj=male) =  0.33262982964515686

In [115]:
np_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15m,'He')
np_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_noprompt_15m,'She')

### verb: "delivered"

In [116]:
transofposs_perfective_noprompt_16 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/16.csv")
transofposs_perfective_noprompt_16.head()

                                         stimulus        He       She
0   Miss Smith delivered a subpoena to Mr. Smith.  0.176441  0.823559
1      The woman delivered a subpoena to the man.  0.824373  0.175627
2              Mary delivered a subpoena to John.  0.804221  0.195779
3              Alice delivered a subpoena to Bob.  0.758671  0.241329
4  The actress delivered a subpoena to the actor.  0.835182  0.164818

In [117]:
# female subject
transofposs_perfective_noprompt_16f = transofposs_perfective_noprompt_16[0:12]
transofposs_perfective_noprompt_16f = transofposs_perfective_noprompt_16f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_16m = transofposs_perfective_noprompt_16[12:24]

#### female subject

In [118]:
transofposs_perfective_noprompt_16f

                                             stimulus       She        He
0       Miss Smith delivered a subpoena to Mr. Smith.  0.823559  0.176441
1          The woman delivered a subpoena to the man.  0.175627  0.824373
2                  Mary delivered a subpoena to John.  0.195779  0.804221
3                  Alice delivered a subpoena to Bob.  0.241329  0.758671
4      The actress delivered a subpoena to the actor.  0.164818  0.835182
5           The girl delivered a subpoena to the boy.  0.172498  0.827502
6   Mrs. Taylor delivered a subpoena to Mr. Williams.  0.796951  0.203049
7                 Emma delivered a subpoena to David.  0.927948  0.072052
8    The princess delivered a subpoena to the prince.  0.172588  0.827412
9               Sarah delivered a subpoena to Robert.  0.304124  0.695876
10  Mrs. Williams delivered a subpoena to Mr. Taylor.  0.717573  0.282427
11                Emily delivered a subpoena to Paul.  0.535885  0.464115

In [119]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_16f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_16f,'He'))

P('subj-pron'|subj=female) =  0.4357231482863426
P('non-subj-pron'|subj=female) =  0.5642768641312917

In [120]:
np_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16f,'She')
np_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16f,'He')

#### male subject

In [121]:
transofposs_perfective_noprompt_16m

                                             stimulus        He       She
12      Mr. Smith delivered a subpoena to Miss Smith.  0.864440  0.135560
13         The man delivered a subpoena to the woman.  0.892141  0.107859
14                 John delivered a subpoena to Mary.  0.878049  0.121951
15                 Bob delivered a subpoena to Alice.  0.158621  0.841379
16     The actor delivered a subpoena to the actress.  0.883561  0.116439
17          The boy delivered a subpoena to the girl.  0.883164  0.116836
18   Mr. William delivered a subpoena to Mrs. Taylor.  0.329742  0.670258
19                David delivered a subpoena to Emma.  0.042676  0.957324
20   The prince delivered a subpoena to the princess.  0.887682  0.112318
21              Robert delivered a subpoena to Sarah.  0.124508  0.875492
22  Mr. Taylor delivered a subpoena to Mrs. Williams.  0.115651  0.884349
23                Paul delivered a subpoena to Emily.  0.845717  0.154284

In [122]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_16m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_16m,'She'))

P('subj-pron'|subj=male) =  0.5754959937185049
P('non-subj-pron'|subj=male) =  0.42450400441884995

In [123]:
np_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16m,'He')
np_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_noprompt_16m,'She')

### verb: "gave"

In [124]:
transofposs_perfective_noprompt_17 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/17.csv")
transofposs_perfective_noprompt_17.head()

                                   stimulus        He       She
0   Miss Smith gave a sweater to Mr. Smith.  0.198732  0.801268
1      The woman gave a sweater to the man.  0.821106  0.178894
2              Mary gave a sweater to John.  0.566159  0.433841
3              Alice gave a sweater to Bob.  0.611178  0.388822
4  The actress gave a sweater to the actor.  0.833737  0.166263

In [125]:
# female subject
transofposs_perfective_noprompt_17f = transofposs_perfective_noprompt_17[0:12]
transofposs_perfective_noprompt_17f = transofposs_perfective_noprompt_17f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_17m = transofposs_perfective_noprompt_17[12:24]

#### female subject

In [126]:
transofposs_perfective_noprompt_17f

                                        stimulus       She        He
0        Miss Smith gave a sweater to Mr. Smith.  0.801268  0.198732
1           The woman gave a sweater to the man.  0.178894  0.821106
2                   Mary gave a sweater to John.  0.433841  0.566159
3                   Alice gave a sweater to Bob.  0.388822  0.611178
4       The actress gave a sweater to the actor.  0.166263  0.833737
5            The girl gave a sweater to the boy.  0.177147  0.822853
6    Mrs. Taylor gave a sweater to Mr. Williams.  0.798401  0.201599
7                  Emma gave a sweater to David.  0.901106  0.098894
8     The princess gave a sweater to the prince.  0.175579  0.824421
9                Sarah gave a sweater to Robert.  0.570531  0.429469
10  Mrs. Williams gave a sweater to  Mr. Taylor.  0.682796  0.317204
11                 Emily gave a sweater to Paul.  0.720914  0.279086

In [127]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_17f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_17f,'He'))

P('subj-pron'|subj=female) =  0.4996302065749963
P('non-subj-pron'|subj=female) =  0.5003697915623585

In [128]:
np_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17f,'She')
np_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17f,'He')

#### female subject

In [129]:
transofposs_perfective_noprompt_17m

                                       stimulus        He       She
12      Mr. Smith gave a sweater to Miss Smith.  0.848155  0.151845
13         The man gave a sweater to the woman.  0.894423  0.105577
14                 John gave a sweater to Mary.  0.877197  0.122803
15                 Bob gave a sweater to Alice.  0.307227  0.692773
16     The actor gave a sweater to the actress.  0.886629  0.113371
17          The boy gave a sweater to the girl.  0.887696  0.112304
18  Mr. William gave a sweater to  Mrs. Taylor.  0.345800  0.654200
19                David gave a sweater to Emma.  0.045572  0.954428
20   The prince gave a sweater to the princess.  0.887347  0.112653
21              Robert gave a sweater to Sarah.  0.116885  0.883115
22  Mr. Taylor gave a sweater to Mrs. Williams.  0.102147  0.897853
23                Paul gave a sweater to Emily.  0.857175  0.142825

In [130]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_17m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_17m,'She'))

P('subj-pron'|subj=male) =  0.5880211669330796
P('non-subj-pron'|subj=male) =  0.4119788135091464

In [131]:
np_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17m,'He')
np_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_noprompt_17m,'She')

### verb: "handed"

In [132]:
transofposs_perfective_noprompt_18 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/18.csv")
transofposs_perfective_noprompt_18.head()

                                  stimulus        He       She
0   Miss Smith handed a book to Mr. Smith.  0.126144  0.873856
1      The woman handed a book to the man.  0.819191  0.180809
2              Mary handed a book to John.  0.731480  0.268520
3              Alice handed a book to Bob.  0.740801  0.259199
4  The actress handed a book to the actor.  0.830194  0.169806

In [133]:
# female subject
transofposs_perfective_noprompt_18f = transofposs_perfective_noprompt_18[0:12]
transofposs_perfective_noprompt_18f = transofposs_perfective_noprompt_18f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_18m = transofposs_perfective_noprompt_18[12:24]

#### female subject

In [134]:
transofposs_perfective_noprompt_18f

                                      stimulus       She        He
0       Miss Smith handed a book to Mr. Smith.  0.873856  0.126144
1          The woman handed a book to the man.  0.180809  0.819191
2                  Mary handed a book to John.  0.268520  0.731480
3                  Alice handed a book to Bob.  0.259199  0.740801
4      The actress handed a book to the actor.  0.169806  0.830194
5           The girl handed a book to the boy.  0.178263  0.821737
6   Mrs. Taylor handed a book to Mr. Williams.  0.812983  0.187017
7                 Emma handed a book to David.  0.941734  0.058266
8    The princess handed a book to the prince.  0.179606  0.820394
9               Sarah handed a book to Robert.  0.444507  0.555493
10  Mrs. Williams handed a book to Mr. Taylor.  0.714304  0.285696
11                Emily handed a book to Paul.  0.537372  0.462628

In [135]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_18f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_18f,'He'))

P('subj-pron'|subj=female) =  0.4634132559100787
P('non-subj-pron'|subj=female) =  0.536586736018459

In [136]:
np_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18f,'She')
np_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18f,'He')

#### male subject

In [137]:
transofposs_perfective_noprompt_18m

                                      stimulus        He       She
12      Mr. Smith handed a book to Miss Smith.  0.858285  0.141715
13         The man handed a book to the woman.  0.889464  0.110536
14                 John handed a book to Mary.  0.870143  0.129857
15                 Bob handed a book to Alice.  0.054571  0.945429
16     The actor handed a book to the actress.  0.310834  0.689166
17          The boy handed a book to the girl.  0.882445  0.117555
18   Mr. William handed a book to Mrs. Taylor.  0.193857  0.806143
19                David handed a book to Emma.  0.006281  0.993719
20   The prince handed a book to the princess.  0.884189  0.115811
21              Robert handed a book to Sarah.  0.029659  0.970341
22  Mr. Taylor handed a book to Mrs. Williams.  0.082565  0.917435
23                Paul handed a book to Emily.  0.853714  0.146286

In [138]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_18m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_18m,'She'))

P('subj-pron'|subj=male) =  0.4930004942386101
P('non-subj-pron'|subj=male) =  0.5069994914035002

In [139]:
np_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18m,'He')
np_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_noprompt_18m,'She')

### verb: "passed"

In [140]:
transofposs_perfective_noprompt_19 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/19.csv")
transofposs_perfective_noprompt_19.head()

                                      stimulus        He       She
0   Miss Smith passed a sandwich to Mr. Smith.  0.325651  0.674349
1      The woman passed a sandwich to the man.  0.813425  0.186575
2              Mary passed a sandwich to John.  0.659419  0.340581
3              Alice passed a sandwich to Bob.  0.715295  0.284705
4  The actress passed a sandwich to the actor.  0.829511  0.170489

In [141]:
# female subject
transofposs_perfective_noprompt_19f = transofposs_perfective_noprompt_19[0:12]
transofposs_perfective_noprompt_19f = transofposs_perfective_noprompt_19f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_19m = transofposs_perfective_noprompt_19[12:24]

#### female subject

In [142]:
transofposs_perfective_noprompt_19f

                                           stimulus       She        He
0        Miss Smith passed a sandwich to Mr. Smith.  0.674349  0.325651
1           The woman passed a sandwich to the man.  0.186575  0.813425
2                   Mary passed a sandwich to John.  0.340581  0.659419
3                   Alice passed a sandwich to Bob.  0.284705  0.715295
4       The actress passed a sandwich to the actor.  0.170489  0.829511
5            The girl passed a sandwich to the boy.  0.185383  0.814617
6    Mrs. Taylor passed a sandwich to Mr. Williams.  0.664820  0.335180
7                  Emma passed a sandwich to David.  0.208522  0.791478
8     The princess passed a sandwich to the prince.  0.182844  0.817156
9                Sarah passed a sandwich to Robert.  0.569988  0.430012
10  Mrs. Williams passed a sandwich to  Mr. Taylor.  0.548559  0.451441
11                 Emily passed a sandwich to Paul.  0.563791  0.436209

In [143]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_19f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_19f,'He'))

P('subj-pron'|subj=female) =  0.3817170349260171
P('non-subj-pron'|subj=female) =  0.6182829563816389

In [144]:
np_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19f,'She')
np_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19f,'He')

#### male subject

In [145]:
transofposs_perfective_noprompt_19m

                                          stimulus        He       She
12      Mr. Smith passed a sandwich to Miss Smith.  0.865260  0.134740
13         The man passed a sandwich to the woman.  0.893456  0.106544
14                 John passed a sandwich to Mary.  0.883347  0.116653
15                 Bob passed a sandwich to Alice.  0.724687  0.275313
16     The actor passed a sandwich to the actress.  0.893472  0.106528
17          The boy passed a sandwich to the girl.  0.893264  0.106736
18  Mr. William passed a sandwich to  Mrs. Taylor.  0.403249  0.596751
19                David passed a sandwich to Emma.  0.076526  0.923474
20   The prince passed a sandwich to the princess.  0.890624  0.109376
21              Robert passed a sandwich to Sarah.  0.270251  0.729749
22  Mr. Taylor passed a sandwich to Mrs. Williams.  0.186372  0.813628
23                Paul passed a sandwich to Emily.  0.863558  0.136442

In [146]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_19m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_19m,'She'))

P('subj-pron'|subj=male) =  0.6536723629881939
P('non-subj-pron'|subj=male) =  0.3463276332865159

In [147]:
np_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19m,'He')
np_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_noprompt_19m,'She')

### verb: "served"

In [148]:
transofposs_perfective_noprompt_20 = pd.read_csv("../results/transfoxl/transofposs_perfective/no-prompt/20.csv")
transofposs_perfective_noprompt_20.head()

                                   stimulus        He       She
0   Miss Smith served a chili to Mr. Smith.  0.282792  0.717208
1      The woman served a chili to the man.  0.819984  0.180016
2              Mary served a chili to John.  0.565666  0.434334
3              Alice served a chili to Bob.  0.320089  0.679911
4  The actress served a chili to the actor.  0.835695  0.164305

In [149]:
# female subject
transofposs_perfective_noprompt_20f = transofposs_perfective_noprompt_20[0:12]
transofposs_perfective_noprompt_20f = transofposs_perfective_noprompt_20f[["stimulus","She","He"]]
# male subject
transofposs_perfective_noprompt_20m = transofposs_perfective_noprompt_20[12:24]

#### female subject

In [150]:
transofposs_perfective_noprompt_20f

                                       stimulus       She        He
0       Miss Smith served a chili to Mr. Smith.  0.717208  0.282792
1          The woman served a chili to the man.  0.180016  0.819984
2                  Mary served a chili to John.  0.434334  0.565666
3                  Alice served a chili to Bob.  0.679911  0.320089
4      The actress served a chili to the actor.  0.164305  0.835695
5           The girl served a chili to the boy.  0.177849  0.822151
6   Mrs. Taylor served a chili to Mr. Williams.  0.832674  0.167326
7                 Emma served a chili to David.  0.196999  0.803001
8    The princess served a chili to the prince.  0.178364  0.821636
9               Sarah served a chili to Robert.  0.831327  0.168673
10  Mrs. Williams served a chili to Mr. Taylor.  0.690692  0.309308
11                Emily served a chili to Paul.  0.849796  0.150204

In [151]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_20f,'She'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_noprompt_20f,'He'))

P('subj-pron'|subj=female) =  0.49445636322100955
P('non-subj-pron'|subj=female) =  0.5055436243613561

In [152]:
np_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_noprompt_20f,'She')
np_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_noprompt_20f,'He')

#### male subject

In [153]:
transofposs_perfective_noprompt_20m

                                       stimulus        He       She
12      Mr. Smith served a chili to Miss Smith.  0.868514  0.131486
13         The man served a chili to the woman.  0.889032  0.110968
14                 John served a chili to Mary.  0.877203  0.122797
15                 Bob served a chili to Alice.  0.866925  0.133075
16     The actor served a chili to the actress.  0.881117  0.118883
17          The boy served a chili to the girl.  0.882366  0.117634
18  Mr. William served a chili to  Mrs. Taylor.  0.518375  0.481625
19                David served a chili to Emma.  0.456254  0.543746
20   The prince served a chili to the princess.  0.887356  0.112644
21              Robert served a chili to Sarah.  0.553450  0.446550
22  Mr. Taylor served a chili to Mrs. Williams.  0.170199  0.829801
23                Paul served a chili to Emily.  0.854626  0.145374

In [154]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_20m,'He'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_noprompt_20m,'She'))

P('subj-pron'|subj=male) =  0.7254515824218591
P('non-subj-pron'|subj=male) =  0.2745484213034312

In [155]:
np_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_noprompt_20m,'He')
np_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_noprompt_20m,'She')

## Summary of Results

In [156]:
np_results_fsubj_subjpron = pd.DataFrame(list(np_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
np_results_fsubj_objpron = pd.DataFrame(list(np_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
np_results_fsubj = np_results_fsubj_subjpron.merge(np_results_fsubj_objpron)
np_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0         flung              0.325394             0.674606
1        kicked              0.364741             0.635259
2        lobbed              0.434744             0.565256
3         threw              0.392080             0.607920
4        tossed              0.380166             0.619834
5       brought              0.444791             0.555209
6     forwarded              0.391121             0.608879
7        mailed              0.450623             0.549377
8       shipped              0.431574             0.568426
9   transmitted              0.423086             0.576914
10        wired              0.417089             0.582911
11      carried              0.425913             0.574087
12    delivered              0.435723             0.564277
13         gave              0.499630             0.500370
14       handed              0.463413             0.536587
15       passed              0.381717             0.618283
16       served              0.494456             0.505544

In [157]:
np_results_msubj_subjpron = pd.DataFrame(list(np_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
np_results_msubj_objpron = pd.DataFrame(list(np_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
np_results_msubj = np_results_msubj_subjpron.merge(np_results_msubj_objpron)
np_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0         flung            0.657735           0.342265
1        kicked            0.724990           0.275010
2        lobbed            0.627205           0.372795
3        rolled            0.737342           0.262658
4         threw            0.662193           0.337807
5        tossed            0.645475           0.354525
6       brought            0.670353           0.329647
7     forwarded            0.601917           0.398083
8        mailed            0.611877           0.388123
9       shipped            0.589137           0.410863
10  transmitted            0.573671           0.426329
11        wired            0.546849           0.453151
12      carried            0.667370           0.332630
13    delivered            0.575496           0.424504
14         gave            0.588021           0.411979
15       handed            0.493000           0.506999
16       passed            0.653672           0.346328
17       served            0.725452           0.274548

In [158]:
np_results = np_results_fsubj.merge(np_results_msubj)
np_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,flung,0.325394,0.674606,0.657735,0.342265
1,kicked,0.364741,0.635259,0.724990,0.275010
2,lobbed,0.434744,0.565256,0.627205,0.372795
3,threw,0.392080,0.607920,0.662193,0.337807
4,tossed,0.380166,0.619834,0.645475,0.354525
5,brought,0.444791,0.555209,0.670353,0.329647
6,forwarded,0.391121,0.608879,0.601917,0.398083
7,mailed,0.450623,0.549377,0.611877,0.388123
8,shipped,0.431574,0.568426,0.589137,0.410863
9,transmitted,0.423086,0.576914,0.573671,0.426329
10,wired,0.417089,0.582911,0.546849,0.453151
11,carried,0.425913,0.574087,0.667370,0.332630
12,delivered,0.435723,0.564277,0.575496,0.424504
13,gave,0.499630,0.500370,0.588021,0.411979
14,handed,0.463413,0.536587,0.493000,0.506999
15,passed,0.381717,0.618283,0.653672,0.346328
16,served,0.494456,0.505544,0.725452,0.274548

In [159]:
print("P(subj_reference |subj=female)", compute_average(np_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(np_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.42095667481714605
P(obj_reference |subj=female) 0.579043328232479

In [160]:
print("P(subj_reference |subj=male)", compute_average(np_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(np_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.624377263979256
P(obj_reference |subj=male) 0.37562273815274244

## Connective: "because"

In [161]:
c1_average_subj_female_subj_pron = {}
c1_average_subj_female_obj_pron = {}
c1_average_subj_male_subj_pron = {}
c1_average_subj_male_obj_pron = {}

### verb: "chucked"

In [162]:
transofposs_perfective_connective1_1 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/1.csv")
transofposs_perfective_connective1_1.head()

                                            stimulus        he       she
0   Miss Smith chucked a wrench to Mr. Smith because  0.139411  0.860589
1      The woman chucked a wrench to the man because  0.453211  0.546788
2              Mary chucked a wrench to John because  0.256879  0.743121
3              Alice chucked a wrench to Bob because  0.226170  0.773830
4  The actress chucked a wrench to the actor because  0.267859  0.732141

In [163]:
# female subject
transofposs_perfective_connective1_1f = transofposs_perfective_connective1_1[0:12]
transofposs_perfective_connective1_1f = transofposs_perfective_connective1_1f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_1m = transofposs_perfective_connective1_1[12:24]

#### female subject

In [164]:
transofposs_perfective_connective1_1f

                                             stimulus       she        he
0    Miss Smith chucked a wrench to Mr. Smith because  0.860589  0.139411
1       The woman chucked a wrench to the man because  0.546788  0.453211
2               Mary chucked a wrench to John because  0.743121  0.256879
3               Alice chucked a wrench to Bob because  0.773830  0.226170
4   The actress chucked a wrench to the actor because  0.732141  0.267859
5        The girl chucked a wrench to the boy because  0.652357  0.347643
6   Mrs. Taylor chucked a wrench to Mr. Williams b...  0.518296  0.481704
7              Emma chucked a wrench to David because  0.752160  0.247840
8   The princess chucked a wrench to the prince be...  0.602794  0.397206
9            Sarah chucked a wrench to Robert because  0.739982  0.260018
10  Mrs. Williams chucked a wrench to Mr. Taylor b...  0.521798  0.478202
11             Emily chucked a wrench to Paul because  0.607295  0.392705

In [165]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_1f,'he'))

P('subj-pron'|subj=female) =  0.6709293127059937
P('non-subj-pron'|subj=female) =  0.32907069971164066

In [166]:
c1_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1f,'she')
c1_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1f,'he')

#### male subject

In [167]:
transofposs_perfective_connective1_1m

                                             stimulus        he       she
12   Mr. Smith chucked a wrench to Miss Smith because  0.468613  0.531387
13      The man chucked a wrench to the woman because  0.552549  0.447451
14              John chucked a wrench to Mary because  0.569454  0.430546
15              Bob chucked a wrench to Alice because  0.423528  0.576472
16  The actor chucked a wrench to the actress because  0.418109  0.581891
17       The boy chucked a wrench to the girl because  0.598121  0.401879
18  Mr. William chucked a wrench to Mrs. Taylor be...  0.321811  0.678189
19             David chucked a wrench to Emma because  0.485725  0.514275
20  The prince chucked a wrench to the princess be...  0.655980  0.344020
21           Robert chucked a wrench to Sarah because  0.354373  0.645627
22  Mr. Taylor chucked a wrench to Mrs. Williams b...  0.283920  0.716080
23             Paul chucked a wrench to Emily because  0.456970  0.543030

In [168]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_1m,'she'))

P('subj-pron'|subj=male) =  0.46576274434725445
P('non-subj-pron'|subj=male) =  0.5342372556527456

In [169]:
c1_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1m,'he')
c1_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_connective1_1m,'she')

### verb: "flung"

In [170]:
transofposs_perfective_connective1_2 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/2.csv")
transofposs_perfective_connective1_2.head()

                                           stimulus        he       she
0   Miss Smith flung a frisbee to Mr. Smith because  0.073479  0.926521
1      The woman flung a frisbee to the man because  0.502161  0.497839
2              Mary flung a frisbee to John because  0.469157  0.530843
3              Alice flung a frisbee to Bob because  0.512816  0.487184
4  The actress flung a frisbee to the actor because  0.378903  0.621097

In [171]:
# female subject
transofposs_perfective_connective1_2f = transofposs_perfective_connective1_2[0:12]
transofposs_perfective_connective1_2f = transofposs_perfective_connective1_2f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_2m = transofposs_perfective_connective1_2[12:24]

#### female subject

In [172]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_2f,'he'))

P('subj-pron'|subj=female) =  0.5964790557821592
P('non-subj-pron'|subj=female) =  0.40352094111343223

In [173]:
c1_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_connective1_2f,'she')
c1_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_connective1_2f,'he')

#### male subject

In [174]:
transofposs_perfective_connective1_2m

                                             stimulus        he       she
12    Mr. Smith flung a frisbee to Miss Smith because  0.530962  0.469038
13       The man flung a frisbee to the woman because  0.481168  0.518832
14               John flung a frisbee to Mary because  0.568747  0.431253
15               Bob flung a frisbee to Alice because  0.319874  0.680126
16   The actor flung a frisbee to the actress because  0.218456  0.781544
17        The boy flung a frisbee to the girl because  0.483595  0.516405
18  Mr. William flung a frisbee to  Mrs. Taylor be...  0.386771  0.613229
19              David flung a frisbee to Emma because  0.358723  0.641277
20  The prince flung a frisbee to the princess bec...  0.534078  0.465922
21            Robert flung a frisbee to Sarah because  0.147004  0.852996
22  Mr. Taylor flung a frisbee to Mrs. Williams be...  0.231663  0.768337
23              Paul flung a frisbee to Emily because  0.303048  0.696952

In [175]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_2m,'she'))

P('subj-pron'|subj=male) =  0.38034073635935783
P('non-subj-pron'|subj=male) =  0.6196592524647713

In [176]:
c1_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_connective1_2m,'he')
c1_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_connective1_2m,'she')

### verb: "kicked"

In [177]:
transofposs_perfective_connective1_3 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/3.csv")
transofposs_perfective_connective1_3.head()

                                            stimulus        he       she
0  Miss Smith kicked a soccer ball to Mr. Smith b...  0.067138  0.932862
1  The woman kicked a soccer ball to the man because  0.466283  0.533717
2          Mary kicked a soccer ball to John because  0.427209  0.572791
3          Alice kicked a soccer ball to Bob because  0.506465  0.493535
4  The actress kicked a soccer ball to the actor ...  0.337886  0.662114

In [178]:
# female subject
transofposs_perfective_connective1_3f = transofposs_perfective_connective1_3[0:12]
transofposs_perfective_connective1_3f = transofposs_perfective_connective1_3f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_3m = transofposs_perfective_connective1_3[12:24]

#### female subject

In [179]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_3f,'he'))

P('subj-pron'|subj=female) =  0.58124112089475
P('non-subj-pron'|subj=female) =  0.41875887600084144

In [180]:
c1_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3f,'she')
c1_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3f,'he')

#### male subject

In [181]:
transofposs_perfective_connective1_3m

                                             stimulus        he       she
12  Mr. Smith kicked a soccer ball to Miss Smith b...  0.415654  0.584346
13  The man kicked a soccer ball to the woman because  0.441916  0.558084
14          John kicked a soccer ball to Mary because  0.400963  0.599037
15          Bob kicked a soccer ball to Alice because  0.350174  0.649826
16  The actor kicked a soccer ball to the actress ...  0.245621  0.754379
17   The boy kicked a soccer ball to the girl because  0.415727  0.584274
18  Mr. William kicked a soccer ball to  Mrs. Tayl...  0.312998  0.687002
19         David kicked a soccer ball to Emma because  0.363268  0.636732
20  The prince kicked a soccer ball to the princes...  0.436987  0.563013
21       Robert kicked a soccer ball to Sarah because  0.296212  0.703788
22  Mr. Taylor kicked a soccer ball to Mrs. Willia...  0.161189  0.838811
23         Paul kicked a soccer ball to Emily because  0.358969  0.641031

In [182]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_3m,'she'))

P('subj-pron'|subj=male) =  0.34997322286168736
P('non-subj-pron'|subj=male) =  0.6500267833471298

In [183]:
c1_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3m,'he')
c1_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_connective1_3m,'she')

### verb: "lobbed"

In [184]:
transofposs_perfective_connective1_4 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/4.csv")
transofposs_perfective_connective1_4.head()

                                            stimulus        he       she
0  Miss Smith lobbed a football to Mr. Smith because  0.112749  0.887251
1     The woman lobbed a football to the man because  0.619297  0.380703
2             Mary lobbed a football to John because  0.531905  0.468095
3             Alice lobbed a football to Bob because  0.654363  0.345637
4  The actress lobbed a football to the actor bec...  0.458226  0.541774

In [185]:
# female subject
transofposs_perfective_connective1_4f = transofposs_perfective_connective1_4[0:12]
transofposs_perfective_connective1_4f = transofposs_perfective_connective1_4f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_4m = transofposs_perfective_connective1_4[12:24]

#### female subject

In [186]:
transofposs_perfective_connective1_4f

                                             stimulus       she        he
0   Miss Smith lobbed a football to Mr. Smith because  0.887251  0.112749
1      The woman lobbed a football to the man because  0.380703  0.619297
2              Mary lobbed a football to John because  0.468095  0.531905
3              Alice lobbed a football to Bob because  0.345637  0.654363
4   The actress lobbed a football to the actor bec...  0.541774  0.458226
5       The girl lobbed a football to the boy because  0.423421  0.576579
6   Mrs. Taylor lobbed a football to Mr. Williams ...  0.564721  0.435279
7             Emma lobbed a football to David because  0.509544  0.490456
8   The princess lobbed a football to the prince b...  0.366141  0.633859
9           Sarah lobbed a football to Robert because  0.417061  0.582939
10  Mrs. Williams lobbed a football to  Mr. Taylor...  0.519176  0.480824
11            Emily lobbed a football to Paul because  0.411230  0.588770

In [187]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_4f,'he'))

P('subj-pron'|subj=female) =  0.48622934023539227
P('non-subj-pron'|subj=female) =  0.5137706566601992

In [188]:
c1_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4f,'she')
c1_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4f,'he')

#### male subject

In [189]:
transofposs_perfective_connective1_4m

                                             stimulus        he       she
12  Mr. Smith lobbed a football to Miss Smith because  0.456221  0.543779
13     The man lobbed a football to the woman because  0.356285  0.643715
14             John lobbed a football to Mary because  0.345697  0.654303
15             Bob lobbed a football to Alice because  0.230117  0.769883
16  The actor lobbed a football to the actress bec...  0.204185  0.795815
17      The boy lobbed a football to the girl because  0.376035  0.623965
18  Mr. William lobbed a football to  Mrs. Taylor ...  0.320718  0.679282
19            David lobbed a football to Emma because  0.313695  0.686305
20  The prince lobbed a football to the princess b...  0.388822  0.611178
21          Robert lobbed a football to Sarah because  0.147863  0.852137
22  Mr. Taylor lobbed a football to Mrs. Williams ...  0.192481  0.807519
23            Paul lobbed a football to Emily because  0.259813  0.740187

In [190]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_4m,'she'))

P('subj-pron'|subj=male) =  0.29932765538493794
P('non-subj-pron'|subj=male) =  0.7006723433732986

In [191]:
c1_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4m,'he')
c1_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective1_4m,'she')

### verb: "rolled"

In [192]:
transofposs_perfective_connective1_5 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/5.csv")
transofposs_perfective_connective1_5.head()

                                            stimulus        he       she
0  Miss Smith rolled a toy truck to Mr. Smith bec...  0.048415  0.951585
1    The woman rolled a toy truck to the man because  0.405182  0.594818
2            Mary rolled a toy truck to John because  0.255642  0.744358
3            Alice rolled a toy truck to Bob because  0.220522  0.779478
4  The actress rolled a toy truck to the actor be...  0.190407  0.809593

In [193]:
# female subject
transofposs_perfective_connective1_5f = transofposs_perfective_connective1_5[0:12]
transofposs_perfective_connective1_5f = transofposs_perfective_connective1_5[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_5m = transofposs_perfective_connective1_5[12:24]

#### female subject

In [194]:
transofposs_perfective_connective1_5f

                                             stimulus       she        he
0   Miss Smith rolled a toy truck to Mr. Smith bec...  0.951585  0.048415
1     The woman rolled a toy truck to the man because  0.594818  0.405182
2             Mary rolled a toy truck to John because  0.744358  0.255642
3             Alice rolled a toy truck to Bob because  0.779478  0.220522
4   The actress rolled a toy truck to the actor be...  0.809593  0.190407
5      The girl rolled a toy truck to the boy because  0.757317  0.242683
6   Mrs. Taylor rolled a toy truck to Mr. Williams...  0.682798  0.317202
7            Emma rolled a toy truck to David because  0.890648  0.109352
8   The princess rolled a toy truck to the prince ...  0.772113  0.227887
9          Sarah rolled a toy truck to Robert because  0.758277  0.241723
10  Mrs. Williams rolled a toy truck to  Mr. Taylo...  0.661908  0.338092
11           Emily rolled a toy truck to Paul because  0.695908  0.304092
12  Mr. Smith rolled a toy truck to Miss Smith bec...  0.465571  0.534429
13    The man rolled a toy truck to the woman because  0.484685  0.515316
14            John rolled a toy truck to Mary because  0.358372  0.641628
15            Bob rolled a toy truck to Alice because  0.309030  0.690970
16  The actor rolled a toy truck to the actress be...  0.724527  0.275473
17     The boy rolled a toy truck to the girl because  0.563547  0.436453
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.646733  0.353267
19           David rolled a toy truck to Emma because  0.522930  0.477070
20  The prince rolled a toy truck to the princess ...  0.363444  0.636556
21         Robert rolled a toy truck to Sarah because  0.745150  0.254850
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.813409  0.186591
23           Paul rolled a toy truck to Emily because  0.598969  0.401031

In [195]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_5f,'he'))

P('subj-pron'|subj=female) =  0.6539653614163399
P('non-subj-pron'|subj=female) =  0.34603463594491285

In [196]:
c1_average_subj_female_subj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5f,'she')
c1_average_subj_female_obj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5f,'he')

#### male subject

In [197]:
transofposs_perfective_connective1_5m

                                             stimulus        he       she
12  Mr. Smith rolled a toy truck to Miss Smith bec...  0.534429  0.465571
13    The man rolled a toy truck to the woman because  0.515316  0.484685
14            John rolled a toy truck to Mary because  0.641628  0.358372
15            Bob rolled a toy truck to Alice because  0.690970  0.309030
16  The actor rolled a toy truck to the actress be...  0.275473  0.724527
17     The boy rolled a toy truck to the girl because  0.436453  0.563547
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.353267  0.646733
19           David rolled a toy truck to Emma because  0.477070  0.522930
20  The prince rolled a toy truck to the princess ...  0.636556  0.363444
21         Robert rolled a toy truck to Sarah because  0.254850  0.745150
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.186591  0.813409
23           Paul rolled a toy truck to Emily because  0.401031  0.598969

In [198]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_5m,'she'))

P('subj-pron'|subj=male) =  0.45030274366339046
P('non-subj-pron'|subj=male) =  0.5496972550948461

In [199]:
c1_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5m,'he')
c1_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_connective1_5m,'she')

### verb: "threw"

In [200]:
transofposs_perfective_connective1_6 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/6.csv")
transofposs_perfective_connective1_6.head()

                                       stimulus        he       she
0   Miss Smith threw a hat to Mr. Smith because  0.073799  0.926201
1      The woman threw a hat to the man because  0.530537  0.469463
2              Mary threw a hat to John because  0.363265  0.636735
3              Alice threw a hat to Bob because  0.442376  0.557624
4  The actress threw a hat to the actor because  0.319705  0.680295

In [201]:
# female subject
transofposs_perfective_connective1_6f = transofposs_perfective_connective1_6[0:12]
transofposs_perfective_connective1_6f = transofposs_perfective_connective1_6[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_6m = transofposs_perfective_connective1_6[12:24]

#### female subject

In [202]:
transofposs_perfective_connective1_6f

                                            stimulus       she        he
0        Miss Smith threw a hat to Mr. Smith because  0.926201  0.073799
1           The woman threw a hat to the man because  0.469463  0.530537
2                   Mary threw a hat to John because  0.636735  0.363265
3                   Alice threw a hat to Bob because  0.557624  0.442376
4       The actress threw a hat to the actor because  0.680295  0.319705
5            The girl threw a hat to the boy because  0.567223  0.432777
6    Mrs. Taylor threw a hat to Mr. Williams because  0.599678  0.400322
7                  Emma threw a hat to David because  0.726011  0.273989
8     The princess threw a hat to the prince because  0.486376  0.513624
9                Sarah threw a hat to Robert because  0.695274  0.304726
10  Mrs. Williams threw a hat to  Mr. Taylor because  0.551620  0.448380
11                 Emily threw a hat to Paul because  0.592197  0.407803
12       Mr. Smith threw a hat to Miss Smith because  0.488363  0.511637
13          The man threw a hat to the woman because  0.491172  0.508828
14                  John threw a hat to Mary because  0.456706  0.543294
15                  Bob threw a hat to Alice because  0.644251  0.355749
16      The actor threw a hat to the actress because  0.675656  0.324344
17           The boy threw a hat to the girl because  0.483958  0.516042
18   Mr. William threw a hat to  Mrs. Taylor because  0.612970  0.387030
19                 David threw a hat to Emma because  0.562066  0.437934
20    The prince threw a hat to the princess because  0.430083  0.569917
21               Robert threw a hat to Sarah because  0.647486  0.352514
22   Mr. Taylor threw a hat to Mrs. Williams because  0.770168  0.229832
23                 Paul threw a hat to Emily because  0.599507  0.400493

In [203]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_6f,'he'))

P('subj-pron'|subj=female) =  0.5979617796838284
P('non-subj-pron'|subj=female) =  0.4020382175222039

In [204]:
c1_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_connective1_6f,'she')
c1_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_connective1_6f,'he')

#### male subject

In [205]:
transofposs_perfective_connective1_6m

                                           stimulus        he       she
12      Mr. Smith threw a hat to Miss Smith because  0.511637  0.488363
13         The man threw a hat to the woman because  0.508828  0.491172
14                 John threw a hat to Mary because  0.543294  0.456706
15                 Bob threw a hat to Alice because  0.355749  0.644251
16     The actor threw a hat to the actress because  0.324344  0.675656
17          The boy threw a hat to the girl because  0.516042  0.483958
18  Mr. William threw a hat to  Mrs. Taylor because  0.387030  0.612970
19                David threw a hat to Emma because  0.437934  0.562066
20   The prince threw a hat to the princess because  0.569917  0.430083
21              Robert threw a hat to Sarah because  0.352514  0.647486
22  Mr. Taylor threw a hat to Mrs. Williams because  0.229832  0.770168
23                Paul threw a hat to Emily because  0.400493  0.599507

In [206]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_6m,'she'))

P('subj-pron'|subj=male) =  0.4281345382332802
P('non-subj-pron'|subj=male) =  0.5718654642502466

In [207]:
c1_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_connective1_6m,'he')
c1_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_connective1_6m,'she')

### verb: "tossed"

In [208]:
transofposs_perfective_connective1_7 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/7.csv")
transofposs_perfective_connective1_7.head()

                                            stimulus        he       she
0  Miss Smith tossed a dish towel to Mr. Smith be...  0.069720  0.930280
1   The woman tossed a dish towel to the man because  0.570725  0.429275
2           Mary tossed a dish towel to John because  0.484538  0.515462
3           Alice tossed a dish towel to Bob because  0.520818  0.479182
4  The actress tossed a dish towel to the actor b...  0.366916  0.633084

In [209]:
# female subject
transofposs_perfective_connective1_7f = transofposs_perfective_connective1_7[0:12]
transofposs_perfective_connective1_7f = transofposs_perfective_connective1_7f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_7m = transofposs_perfective_connective1_7[12:24]

#### female subject

In [210]:
transofposs_perfective_connective1_7f

                                             stimulus       she        he
0   Miss Smith tossed a dish towel to Mr. Smith be...  0.930280  0.069720
1    The woman tossed a dish towel to the man because  0.429275  0.570725
2            Mary tossed a dish towel to John because  0.515462  0.484538
3            Alice tossed a dish towel to Bob because  0.479182  0.520818
4   The actress tossed a dish towel to the actor b...  0.633084  0.366916
5     The girl tossed a dish towel to the boy because  0.492789  0.507211
6   Mrs. Taylor tossed a dish towel to Mr. William...  0.589266  0.410734
7           Emma tossed a dish towel to David because  0.601490  0.398510
8   The princess tossed a dish towel to the prince...  0.430689  0.569311
9         Sarah tossed a dish towel to Robert because  0.489279  0.510720
10  Mrs. Williams tossed a dish towel to  Mr. Tayl...  0.554598  0.445402
11          Emily tossed a dish towel to Paul because  0.429328  0.570672

In [211]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_7f,'he'))

P('subj-pron'|subj=female) =  0.5478936632474264
P('non-subj-pron'|subj=female) =  0.4521063199887673

In [212]:
c1_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7f,'she')
c1_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7f,'he')

#### male subject

In [213]:
transofposs_perfective_connective1_7m

                                             stimulus        he       she
12  Mr. Smith tossed a dish towel to Miss Smith be...  0.391843  0.608157
13   The man tossed a dish towel to the woman because  0.379556  0.620444
14           John tossed a dish towel to Mary because  0.466655  0.533345
15           Bob tossed a dish towel to Alice because  0.199606  0.800394
16  The actor tossed a dish towel to the actress b...  0.182211  0.817789
17    The boy tossed a dish towel to the girl because  0.389112  0.610888
18  Mr. William tossed a dish towel to  Mrs. Taylo...  0.285439  0.714562
19          David tossed a dish towel to Emma because  0.307024  0.692976
20  The prince tossed a dish towel to the princess...  0.479456  0.520544
21        Robert tossed a dish towel to Sarah because  0.155226  0.844774
22  Mr. Taylor tossed a dish towel to Mrs. William...  0.169160  0.830840
23          Paul tossed a dish towel to Emily because  0.260654  0.739346

In [214]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_7m,'she'))

P('subj-pron'|subj=male) =  0.30549517025550205
P('non-subj-pron'|subj=male) =  0.6945048322280248

In [215]:
c1_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7m,'he')
c1_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_connective1_7m,'she')

### verb: "brought"

In [216]:
transofposs_perfective_connective1_8 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/8.csv")
transofposs_perfective_connective1_8.head()

                                            stimulus        he       she
0  Miss Smith brought a glass of water to Mr. Smi...  0.103736  0.896264
1  The woman brought a glass of water to the man ...  0.443728  0.556272
2      Mary brought a glass of water to John because  0.261947  0.738053
3      Alice brought a glass of water to Bob because  0.346367  0.653633
4  The actress brought a glass of water to the ac...  0.086090  0.913910

In [217]:
# female subject
transofposs_perfective_connective1_8f = transofposs_perfective_connective1_8[0:12]
transofposs_perfective_connective1_8f = transofposs_perfective_connective1_8f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_8m = transofposs_perfective_connective1_8[12:24]

#### female subject

In [218]:
transofposs_perfective_connective1_8f

                                             stimulus       she        he
0   Miss Smith brought a glass of water to Mr. Smi...  0.896264  0.103736
1   The woman brought a glass of water to the man ...  0.556272  0.443728
2       Mary brought a glass of water to John because  0.738053  0.261947
3       Alice brought a glass of water to Bob because  0.653633  0.346367
4   The actress brought a glass of water to the ac...  0.913910  0.086090
5   The girl brought a glass of water to the boy b...  0.699756  0.300244
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.558687  0.441313
7      Emma brought a glass of water to David because  0.753645  0.246355
8   The princess brought a glass of water to the p...  0.748616  0.251384
9    Sarah brought a glass of water to Robert because  0.581999  0.418001
10  Mrs. Williams brought a glass of water to  Mr....  0.535520  0.464480
11     Emily brought a glass of water to Paul because  0.541427  0.458573

In [219]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_8f,'he'))

P('subj-pron'|subj=female) =  0.6814818580945333
P('non-subj-pron'|subj=female) =  0.3185181487351656

In [220]:
c1_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_connective1_8f,'she')
c1_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_connective1_8f,'he')

#### male subject

In [221]:
transofposs_perfective_connective1_8m

                                             stimulus        he       she
12  Mr. Smith brought a glass of water to Miss Smi...  0.444825  0.555175
13  The man brought a glass of water to the woman ...  0.488130  0.511870
14      John brought a glass of water to Mary because  0.455747  0.544253
15      Bob brought a glass of water to Alice because  0.317865  0.682135
16  The actor brought a glass of water to the actr...  0.421001  0.578999
17  The boy brought a glass of water to the girl b...  0.491336  0.508664
18  Mr. William brought a glass of water to  Mrs. ...  0.317785  0.682215
19     David brought a glass of water to Emma because  0.477993  0.522007
20  The prince brought a glass of water to the pri...  0.594872  0.405128
21   Robert brought a glass of water to Sarah because  0.158829  0.841171
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.162747  0.837253
23     Paul brought a glass of water to Emily because  0.358102  0.641898

In [222]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_8m,'she'))

P('subj-pron'|subj=male) =  0.39076920474569005
P('non-subj-pron'|subj=male) =  0.6092308064301809

In [223]:
c1_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_connective1_8m,'he')
c1_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_connective1_8m,'she')

### verb: "forwarded"

In [224]:
transofposs_perfective_connective1_9 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/9.csv")
transofposs_perfective_connective1_9.head()

                                            stimulus        he       she
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.034738  0.965262
1  The woman forwarded a gossipy email to the man...  0.537543  0.462457
2     Mary forwarded a gossipy email to John because  0.264517  0.735483
3     Alice forwarded a gossipy email to Bob because  0.475777  0.524223
4  The actress forwarded a gossipy email to the a...  0.206793  0.793207

In [225]:
# female subject
transofposs_perfective_connective1_9f = transofposs_perfective_connective1_9[0:12]
transofposs_perfective_connective1_9f = transofposs_perfective_connective1_9f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_9m = transofposs_perfective_connective1_9[12:24]

#### female subject

In [226]:
transofposs_perfective_connective1_9f

                                             stimulus       she        he
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.965262  0.034738
1   The woman forwarded a gossipy email to the man...  0.462457  0.537543
2      Mary forwarded a gossipy email to John because  0.735483  0.264517
3      Alice forwarded a gossipy email to Bob because  0.524223  0.475777
4   The actress forwarded a gossipy email to the a...  0.793207  0.206793
5   The girl forwarded a gossipy email to the boy ...  0.485199  0.514801
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.649948  0.350052
7     Emma forwarded a gossipy email to David because  0.824981  0.175019
8   The princess forwarded a gossipy email to the ...  0.496716  0.503284
9   Sarah forwarded a gossipy email to Robert because  0.630836  0.369164
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.666578  0.333422
11    Emily forwarded a gossipy email to Paul because  0.662059  0.337941

In [227]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_9f,'he'))

P('subj-pron'|subj=female) =  0.6580790157119433
P('non-subj-pron'|subj=female) =  0.3419209752852718

In [228]:
c1_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9f,'she')
c1_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9f,'he')

#### male subject

In [229]:
transofposs_perfective_connective1_9m

                                             stimulus        he       she
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.509555  0.490445
13  The man forwarded a gossipy email to the woman...  0.507807  0.492193
14     John forwarded a gossipy email to Mary because  0.593202  0.406798
15     Bob forwarded a gossipy email to Alice because  0.351753  0.648247
16  The actor forwarded a gossipy email to the act...  0.261484  0.738516
17  The boy forwarded a gossipy email to the girl ...  0.451773  0.548227
18  Mr. William forwarded a gossipy email to  Mrs....  0.253616  0.746384
19    David forwarded a gossipy email to Emma because  0.506533  0.493467
20  The prince forwarded a gossipy email to the pr...  0.593513  0.406487
21  Robert forwarded a gossipy email to Sarah because  0.366978  0.633022
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.133181  0.866819
23    Paul forwarded a gossipy email to Emily because  0.432607  0.567393

In [230]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_9m,'she'))

P('subj-pron'|subj=male) =  0.4135000246266524
P('non-subj-pron'|subj=male) =  0.5864999641974767

In [231]:
c1_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9m,'he')
c1_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective1_9m,'she')

### verb: "mailed"

In [232]:
transofposs_perfective_connective1_10 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/10.csv")
transofposs_perfective_connective1_10.head()

                                           stimulus        he       she
0   Miss Smith mailed a letter to Mr. Smith because  0.030549  0.969451
1      The woman mailed a letter to the man because  0.428986  0.571014
2              Mary mailed a letter to John because  0.189923  0.810077
3              Alice mailed a letter to Bob because  0.365998  0.634002
4  The actress mailed a letter to the actor because  0.115131  0.884869

In [233]:
# female subject
transofposs_perfective_connective1_10f = transofposs_perfective_connective1_10[0:12]
transofposs_perfective_connective1_10f = transofposs_perfective_connective1_10f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_10m = transofposs_perfective_connective1_10[12:24]

#### female subject

In [234]:
transofposs_perfective_connective1_10f

                                             stimulus       she        he
0     Miss Smith mailed a letter to Mr. Smith because  0.969451  0.030549
1        The woman mailed a letter to the man because  0.571014  0.428986
2                Mary mailed a letter to John because  0.810077  0.189923
3                Alice mailed a letter to Bob because  0.634002  0.365998
4    The actress mailed a letter to the actor because  0.884869  0.115131
5         The girl mailed a letter to the boy because  0.588936  0.411064
6   Mrs. Taylor mailed a letter to Mr. Williams be...  0.677286  0.322714
7               Emma mailed a letter to David because  0.916963  0.083037
8   The princess mailed a letter to the prince bec...  0.637479  0.362521
9             Sarah mailed a letter to Robert because  0.729941  0.270059
10  Mrs. Williams mailed a letter to  Mr. Taylor b...  0.685510  0.314490
11              Emily mailed a letter to Paul because  0.839518  0.160482

In [235]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_10f,'he'))

P('subj-pron'|subj=female) =  0.7454204012950262
P('non-subj-pron'|subj=female) =  0.25457959606622654

In [236]:
c1_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10f,'she')
c1_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10f,'he')

#### male subject

In [237]:
transofposs_perfective_connective1_10m

                                             stimulus        he       she
12    Mr. Smith mailed a letter to Miss Smith because  0.554524  0.445476
13       The man mailed a letter to the woman because  0.523210  0.476790
14               John mailed a letter to Mary because  0.797820  0.202180
15               Bob mailed a letter to Alice because  0.439032  0.560968
16   The actor mailed a letter to the actress because  0.346654  0.653346
17        The boy mailed a letter to the girl because  0.502701  0.497299
18  Mr. William mailed a letter to  Mrs. Taylor be...  0.353631  0.646369
19              David mailed a letter to Emma because  0.674621  0.325379
20  The prince mailed a letter to the princess bec...  0.682867  0.317133
21            Robert mailed a letter to Sarah because  0.437772  0.562228
22  Mr. Taylor mailed a letter to Mrs. Williams be...  0.183078  0.816922
23              Paul mailed a letter to Emily because  0.541937  0.458063

In [238]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_10m,'she'))

P('subj-pron'|subj=male) =  0.503153865536054
P('non-subj-pron'|subj=male) =  0.49684612328807515

In [239]:
c1_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10m,'he')
c1_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_connective1_10m,'she')

### verb: "shipped"

In [240]:
transofposs_perfective_connective1_11 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/11.csv")
transofposs_perfective_connective1_11.head()

                                            stimulus        he       she
0  Miss Smith shipped a package to Mr. Smith because  0.043585  0.956415
1     The woman shipped a package to the man because  0.425283  0.574717
2             Mary shipped a package to John because  0.213314  0.786686
3             Alice shipped a package to Bob because  0.306684  0.693316
4  The actress shipped a package to the actor bec...  0.147401  0.852600

In [241]:
# female subject
transofposs_perfective_connective1_11f = transofposs_perfective_connective1_11[0:12]
transofposs_perfective_connective1_11f = transofposs_perfective_connective1_11f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_11m = transofposs_perfective_connective1_11[12:24]

#### female subject

In [242]:
transofposs_perfective_connective1_11f

                                             stimulus       she        he
0   Miss Smith shipped a package to Mr. Smith because  0.956415  0.043585
1      The woman shipped a package to the man because  0.574717  0.425283
2              Mary shipped a package to John because  0.786686  0.213314
3              Alice shipped a package to Bob because  0.693316  0.306684
4   The actress shipped a package to the actor bec...  0.852600  0.147401
5       The girl shipped a package to the boy because  0.672447  0.327553
6   Mrs. Taylor shipped a package to Mr. Williams ...  0.603905  0.396095
7             Emma shipped a package to David because  0.916277  0.083723
8   The princess shipped a package to the prince b...  0.568375  0.431625
9           Sarah shipped a package to Robert because  0.793239  0.206761
10  Mrs. Williams shipped a package to  Mr. Taylor...  0.643792  0.356208
11            Emily shipped a package to Paul because  0.740113  0.259887

In [243]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_11f,'he'))

P('subj-pron'|subj=female) =  0.7334901690483093
P('non-subj-pron'|subj=female) =  0.2665098365396261

In [244]:
c1_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11f,'she')
c1_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11f,'he')

#### male subject

In [245]:
transofposs_perfective_connective1_11m

                                             stimulus        he       she
12  Mr. Smith shipped a package to Miss Smith because  0.349472  0.650528
13     The man shipped a package to the woman because  0.432496  0.567504
14             John shipped a package to Mary because  0.428942  0.571058
15             Bob shipped a package to Alice because  0.191800  0.808200
16  The actor shipped a package to the actress bec...  0.128088  0.871912
17      The boy shipped a package to the girl because  0.268871  0.731129
18  Mr. William shipped a package to  Mrs. Taylor ...  0.196098  0.803902
19            David shipped a package to Emma because  0.284457  0.715543
20  The prince shipped a package to the princess b...  0.504777  0.495223
21          Robert shipped a package to Sarah because  0.128950  0.871050
22  Mr. Taylor shipped a package to Mrs. Williams ...  0.115406  0.884594
23            Paul shipped a package to Emily because  0.242748  0.757252

In [246]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_11m,'she'))

P('subj-pron'|subj=male) =  0.272675300637881
P('non-subj-pron'|subj=male) =  0.7273246894280115

In [247]:
c1_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11m,'he')
c1_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_connective1_11m,'she')

### verb: "transmitted"

In [248]:
transofposs_perfective_connective1_12 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/12.csv")
transofposs_perfective_connective1_12.head()

                                            stimulus        he       she
0  Miss Smith transmitted a message to Mr. Smith ...  0.059579  0.940421
1  The woman transmitted a message to the man bec...  0.370823  0.629177
2         Mary transmitted a message to John because  0.169927  0.830073
3         Alice transmitted a message to Bob because  0.332626  0.667374
4  The actress transmitted a message to the actor...  0.183668  0.816332

In [249]:
# female subject
transofposs_perfective_connective1_12f = transofposs_perfective_connective1_12[0:12]
transofposs_perfective_connective1_12f = transofposs_perfective_connective1_12f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_12m = transofposs_perfective_connective1_12[12:24]

#### female subject

In [250]:
transofposs_perfective_connective1_12f

                                             stimulus       she        he
0   Miss Smith transmitted a message to Mr. Smith ...  0.940421  0.059579
1   The woman transmitted a message to the man bec...  0.629177  0.370823
2          Mary transmitted a message to John because  0.830073  0.169927
3          Alice transmitted a message to Bob because  0.667374  0.332626
4   The actress transmitted a message to the actor...  0.816332  0.183668
5   The girl transmitted a message to the boy because  0.694185  0.305815
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.630958  0.369042
7         Emma transmitted a message to David because  0.884486  0.115514
8   The princess transmitted a message to the prin...  0.666701  0.333299
9       Sarah transmitted a message to Robert because  0.791430  0.208570
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.634110  0.365890
11        Emily transmitted a message to Paul because  0.682621  0.317379

In [251]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_12f,'he'))

P('subj-pron'|subj=female) =  0.7389889707167944
P('non-subj-pron'|subj=female) =  0.2610110354920228

In [252]:
c1_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12f,'she')
c1_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12f,'he')

#### male subject

In [253]:
transofposs_perfective_connective1_12m

                                             stimulus        he       she
12  Mr. Smith transmitted a message to Miss Smith ...  0.532951  0.467050
13  The man transmitted a message to the woman bec...  0.558871  0.441129
14         John transmitted a message to Mary because  0.686754  0.313246
15         Bob transmitted a message to Alice because  0.351211  0.648789
16  The actor transmitted a message to the actress...  0.295453  0.704547
17  The boy transmitted a message to the girl because  0.479901  0.520099
18  Mr. William transmitted a message to  Mrs. Tay...  0.305576  0.694424
19        David transmitted a message to Emma because  0.516106  0.483894
20  The prince transmitted a message to the prince...  0.688369  0.311631
21      Robert transmitted a message to Sarah because  0.331737  0.668263
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.142382  0.857618
23        Paul transmitted a message to Emily because  0.420748  0.579252

In [254]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_12m,'she'))

P('subj-pron'|subj=male) =  0.4425048728783925
P('non-subj-pron'|subj=male) =  0.5574951395392418

In [255]:
c1_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12m,'he')
c1_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective1_12m,'she')

### verb: "wired"

In [256]:
transofposs_perfective_connective1_14 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/14.csv")
transofposs_perfective_connective1_14.head()

                                       stimulus        he       she
0   Miss Smith wired money to Mr. Smith because  0.070812  0.929188
1      The woman wired money to the man because  0.505137  0.494863
2              Mary wired money to John because  0.487218  0.512782
3              Alice wired money to Bob because  0.614548  0.385452
4  The actress wired money to the actor because  0.436052  0.563948

In [257]:
# female subject
transofposs_perfective_connective1_14f = transofposs_perfective_connective1_14[0:12]
transofposs_perfective_connective1_14f = transofposs_perfective_connective1_14f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_14m = transofposs_perfective_connective1_14[12:24]

#### female subject

In [258]:
transofposs_perfective_connective1_14f

                                            stimulus       she        he
0        Miss Smith wired money to Mr. Smith because  0.929188  0.070812
1           The woman wired money to the man because  0.494863  0.505137
2                   Mary wired money to John because  0.512782  0.487218
3                   Alice wired money to Bob because  0.385452  0.614548
4       The actress wired money to the actor because  0.563948  0.436052
5            The girl wired money to the boy because  0.519021  0.480979
6    Mrs. Taylor wired money to Mr. Williams because  0.576959  0.423041
7                  Emma wired money to David because  0.672695  0.327305
8     The princess wired money to the prince because  0.501296  0.498704
9                Sarah wired money to Robert because  0.609974  0.390026
10  Mrs. Williams wired money to  Mr. Taylor because  0.577235  0.422765
11                 Emily wired money to Paul because  0.554659  0.445341

In [259]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_14f,'he'))

P('subj-pron'|subj=female) =  0.5748394007484118
P('non-subj-pron'|subj=female) =  0.42516059428453445

In [260]:
c1_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_connective1_14f,'she')
c1_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_connective1_14f,'he')

#### male subject

In [261]:
transofposs_perfective_connective1_14m

                                           stimulus        he       she
12      Mr. Smith wired money to Miss Smith because  0.469856  0.530144
13         The man wired money to the woman because  0.548108  0.451892
14                 John wired money to Mary because  0.550469  0.449531
15                 Bob wired money to Alice because  0.211194  0.788806
16     The actor wired money to the actress because  0.253392  0.746607
17          The boy wired money to the girl because  0.536788  0.463212
18  Mr. William wired money to  Mrs. Taylor because  0.303708  0.696292
19                David wired money to Emma because  0.412133  0.587867
20   The prince wired money to the princess because  0.598861  0.401139
21              Robert wired money to Sarah because  0.143966  0.856034
22  Mr. Taylor wired money to Mrs. Williams because  0.142148  0.857852
23                Paul wired money to Emily because  0.314755  0.685245

In [262]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_14m,'she'))

P('subj-pron'|subj=male) =  0.3737815171480179
P('non-subj-pron'|subj=male) =  0.6262184704343478

In [263]:
c1_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_connective1_14m,'he')
c1_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_connective1_14m,'she')

### verb: "carried"

In [264]:
transofposs_perfective_connective1_15 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/15.csv")
transofposs_perfective_connective1_15.head()

                                          stimulus        he       she
0   Miss Smith carried a tray to Mr. Smith because  0.066681  0.933319
1      The woman carried a tray to the man because  0.373576  0.626424
2              Mary carried a tray to John because  0.173136  0.826864
3              Alice carried a tray to Bob because  0.144738  0.855262
4  The actress carried a tray to the actor because  0.145341  0.854659

In [265]:
# female subject
transofposs_perfective_connective1_15f = transofposs_perfective_connective1_15[0:12]
transofposs_perfective_connective1_15f = transofposs_perfective_connective1_15f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_15m = transofposs_perfective_connective1_15[12:24]

#### female subject

In [266]:
transofposs_perfective_connective1_15f

                                             stimulus       she        he
0      Miss Smith carried a tray to Mr. Smith because  0.933319  0.066681
1         The woman carried a tray to the man because  0.626424  0.373576
2                 Mary carried a tray to John because  0.826864  0.173136
3                 Alice carried a tray to Bob because  0.855262  0.144738
4     The actress carried a tray to the actor because  0.854659  0.145341
5          The girl carried a tray to the boy because  0.802178  0.197822
6   Mrs. Taylor carried a tray to Mr. Williams bec...  0.626682  0.373319
7                Emma carried a tray to David because  0.930759  0.069241
8   The princess carried a tray to the prince because  0.702234  0.297766
9              Sarah carried a tray to Robert because  0.843478  0.156522
10  Mrs. Williams carried a tray to  Mr. Taylor be...  0.626251  0.373749
11               Emily carried a tray to Paul because  0.736488  0.263512

In [267]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_15f,'he'))

P('subj-pron'|subj=female) =  0.7803832093874613
P('non-subj-pron'|subj=female) =  0.21961679682135582

In [268]:
c1_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_connective1_15f,'she')
c1_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_connective1_15f,'he')

#### male subject

In [269]:
transofposs_perfective_connective1_15m

                                             stimulus        he       she
12     Mr. Smith carried a tray to Miss Smith because  0.547506  0.452494
13        The man carried a tray to the woman because  0.525127  0.474873
14                John carried a tray to Mary because  0.654248  0.345752
15                Bob carried a tray to Alice because  0.386317  0.613683
16    The actor carried a tray to the actress because  0.279399  0.720601
17         The boy carried a tray to the girl because  0.522840  0.477160
18  Mr. William carried a tray to  Mrs. Taylor bec...  0.324747  0.675253
19               David carried a tray to Emma because  0.362863  0.637137
20  The prince carried a tray to the princess because  0.601591  0.398409
21             Robert carried a tray to Sarah because  0.238016  0.761984
22  Mr. Taylor carried a tray to Mrs. Williams bec...  0.191181  0.808819
23               Paul carried a tray to Emily because  0.370930  0.629070

In [270]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_15m,'she'))

P('subj-pron'|subj=male) =  0.4170637180407842
P('non-subj-pron'|subj=male) =  0.5829362620910009

In [271]:
c1_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_connective1_15m,'he')
c1_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_connective1_15m,'she')

### verb: "delivered"

In [272]:
transofposs_perfective_connective1_16 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/16.csv")
transofposs_perfective_connective1_16.head()

                                            stimulus        he       she
0  Miss Smith delivered a subpoena to Mr. Smith b...  0.068001  0.931999
1  The woman delivered a subpoena to the man because  0.537902  0.462098
2          Mary delivered a subpoena to John because  0.298065  0.701935
3          Alice delivered a subpoena to Bob because  0.482563  0.517437
4  The actress delivered a subpoena to the actor ...  0.429616  0.570384

In [273]:
# female subject
transofposs_perfective_connective1_16f = transofposs_perfective_connective1_16[0:12]
transofposs_perfective_connective1_16f = transofposs_perfective_connective1_16f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_16m = transofposs_perfective_connective1_16[12:24]

#### female subject

In [274]:
transofposs_perfective_connective1_16f

                                             stimulus       she        he
0   Miss Smith delivered a subpoena to Mr. Smith b...  0.931999  0.068001
1   The woman delivered a subpoena to the man because  0.462098  0.537902
2           Mary delivered a subpoena to John because  0.701935  0.298065
3           Alice delivered a subpoena to Bob because  0.517437  0.482563
4   The actress delivered a subpoena to the actor ...  0.570384  0.429616
5    The girl delivered a subpoena to the boy because  0.498783  0.501217
6   Mrs. Taylor delivered a subpoena to Mr. Willia...  0.587761  0.412239
7          Emma delivered a subpoena to David because  0.707696  0.292304
8   The princess delivered a subpoena to the princ...  0.474075  0.525925
9        Sarah delivered a subpoena to Robert because  0.636937  0.363063
10  Mrs. Williams delivered a subpoena to Mr. Tayl...  0.594545  0.405455
11         Emily delivered a subpoena to Paul because  0.575769  0.424231

In [275]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_16f,'he'))

P('subj-pron'|subj=female) =  0.604951466123263
P('non-subj-pron'|subj=female) =  0.3950485388437907

In [276]:
c1_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16f,'she')
c1_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16f,'he')

#### male subject

In [277]:
transofposs_perfective_connective1_16m

                                             stimulus        he       she
12  Mr. Smith delivered a subpoena to Miss Smith b...  0.412060  0.587940
13  The man delivered a subpoena to the woman because  0.379656  0.620344
14          John delivered a subpoena to Mary because  0.412396  0.587604
15          Bob delivered a subpoena to Alice because  0.183241  0.816759
16  The actor delivered a subpoena to the actress ...  0.173326  0.826674
17   The boy delivered a subpoena to the girl because  0.328063  0.671937
18  Mr. William delivered a subpoena to Mrs. Taylo...  0.228548  0.771452
19         David delivered a subpoena to Emma because  0.394352  0.605648
20  The prince delivered a subpoena to the princes...  0.529596  0.470404
21       Robert delivered a subpoena to Sarah because  0.171949  0.828052
22  Mr. Taylor delivered a subpoena to Mrs. Willia...  0.137276  0.862724
23         Paul delivered a subpoena to Emily because  0.287484  0.712516

In [278]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_16m,'she'))

P('subj-pron'|subj=male) =  0.30316221341490746
P('non-subj-pron'|subj=male) =  0.6968377754092216

In [279]:
c1_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16m,'he')
c1_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_connective1_16m,'she')

### verb: "gave"

In [280]:
transofposs_perfective_connective1_17 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/17.csv")
transofposs_perfective_connective1_17.head()

                                          stimulus        he       she
0   Miss Smith gave a sweater to Mr. Smith because  0.081331  0.918669
1      The woman gave a sweater to the man because  0.513157  0.486843
2              Mary gave a sweater to John because  0.284716  0.715284
3              Alice gave a sweater to Bob because  0.423494  0.576506
4  The actress gave a sweater to the actor because  0.111340  0.888660

In [281]:
# female subject
transofposs_perfective_connective1_17f = transofposs_perfective_connective1_17[0:12]
transofposs_perfective_connective1_17f = transofposs_perfective_connective1_17f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_17m = transofposs_perfective_connective1_17[12:24]

#### female subject

In [282]:
transofposs_perfective_connective1_17f

                                             stimulus       she        he
0      Miss Smith gave a sweater to Mr. Smith because  0.918669  0.081331
1         The woman gave a sweater to the man because  0.486843  0.513157
2                 Mary gave a sweater to John because  0.715284  0.284716
3                 Alice gave a sweater to Bob because  0.576506  0.423494
4     The actress gave a sweater to the actor because  0.888660  0.111340
5          The girl gave a sweater to the boy because  0.616246  0.383754
6   Mrs. Taylor gave a sweater to Mr. Williams bec...  0.619227  0.380773
7                Emma gave a sweater to David because  0.805483  0.194517
8   The princess gave a sweater to the prince because  0.570068  0.429932
9              Sarah gave a sweater to Robert because  0.709721  0.290279
10  Mrs. Williams gave a sweater to  Mr. Taylor be...  0.604312  0.395688
11               Emily gave a sweater to Paul because  0.701868  0.298132

In [283]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_17f,'he'))

P('subj-pron'|subj=female) =  0.6844072590271632
P('non-subj-pron'|subj=female) =  0.315592751527826

In [284]:
c1_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_connective1_17f,'she')
c1_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_connective1_17f,'he')

#### male subject

In [285]:
transofposs_perfective_connective1_17m

                                             stimulus        he       she
12     Mr. Smith gave a sweater to Miss Smith because  0.463168  0.536832
13        The man gave a sweater to the woman because  0.517013  0.482987
14                John gave a sweater to Mary because  0.612349  0.387651
15                Bob gave a sweater to Alice because  0.362181  0.637819
16    The actor gave a sweater to the actress because  0.555040  0.444960
17         The boy gave a sweater to the girl because  0.570746  0.429254
18  Mr. William gave a sweater to  Mrs. Taylor bec...  0.332346  0.667654
19               David gave a sweater to Emma because  0.514870  0.485130
20  The prince gave a sweater to the princess because  0.671028  0.328972
21             Robert gave a sweater to Sarah because  0.441397  0.558603
22  Mr. Taylor gave a sweater to Mrs. Williams bec...  0.145871  0.854129
23               Paul gave a sweater to Emily because  0.422825  0.577175

In [286]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_17m,'she'))

P('subj-pron'|subj=male) =  0.4674026779830456
P('non-subj-pron'|subj=male) =  0.5325973108410835

In [287]:
c1_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_connective1_17m,'he')
c1_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_connective1_17m,'she')

### verb: "handed"

In [288]:
transofposs_perfective_connective1_18 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/18.csv")
transofposs_perfective_connective1_18.head()

                                         stimulus        he       she
0   Miss Smith handed a book to Mr. Smith because  0.060672  0.939328
1      The woman handed a book to the man because  0.503231  0.496769
2              Mary handed a book to John because  0.317259  0.682741
3              Alice handed a book to Bob because  0.434511  0.565489
4  The actress handed a book to the actor because  0.296611  0.703389

In [289]:
# female subject
transofposs_perfective_connective1_18f = transofposs_perfective_connective1_18[0:12]
transofposs_perfective_connective1_18f = transofposs_perfective_connective1_18f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_18m = transofposs_perfective_connective1_18[12:24]

#### female subject

In [290]:
transofposs_perfective_connective1_18f

                                             stimulus       she        he
0       Miss Smith handed a book to Mr. Smith because  0.939328  0.060672
1          The woman handed a book to the man because  0.496769  0.503231
2                  Mary handed a book to John because  0.682741  0.317259
3                  Alice handed a book to Bob because  0.565489  0.434511
4      The actress handed a book to the actor because  0.703389  0.296611
5           The girl handed a book to the boy because  0.507681  0.492319
6   Mrs. Taylor handed a book to Mr. Williams because  0.612239  0.387761
7                 Emma handed a book to David because  0.765661  0.234339
8    The princess handed a book to the prince because  0.478955  0.521045
9               Sarah handed a book to Robert because  0.626627  0.373373
10  Mrs. Williams handed a book to Mr. Taylor because  0.610754  0.389246
11                Emily handed a book to Paul because  0.623868  0.376132

In [291]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_18f,'he'))

P('subj-pron'|subj=female) =  0.6344585120677948
P('non-subj-pron'|subj=female) =  0.36554149507234496

In [292]:
c1_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_connective1_18f,'she')
c1_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_connective1_18f,'he')

#### male subject

In [293]:
transofposs_perfective_connective1_18m

                                             stimulus        he       she
12      Mr. Smith handed a book to Miss Smith because  0.410342  0.589658
13         The man handed a book to the woman because  0.411555  0.588445
14                 John handed a book to Mary because  0.411084  0.588916
15                 Bob handed a book to Alice because  0.262652  0.737348
16     The actor handed a book to the actress because  0.287527  0.712473
17          The boy handed a book to the girl because  0.419652  0.580348
18   Mr. William handed a book to Mrs. Taylor because  0.210460  0.789540
19                David handed a book to Emma because  0.409656  0.590344
20   The prince handed a book to the princess because  0.506925  0.493075
21              Robert handed a book to Sarah because  0.239232  0.760768
22  Mr. Taylor handed a book to Mrs. Williams because  0.119070  0.880930
23                Paul handed a book to Emily because  0.376935  0.623065

In [294]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_18m,'she'))

P('subj-pron'|subj=male) =  0.33875749073922634
P('non-subj-pron'|subj=male) =  0.6612425024310747

In [295]:
c1_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_connective1_18m,'he')
c1_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_connective1_18m,'she')

### verb: "passed"

In [296]:
transofposs_perfective_connective1_19 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/19.csv")
transofposs_perfective_connective1_19.head()

                                            stimulus        he       she
0  Miss Smith passed a sandwich to Mr. Smith because  0.066213  0.933787
1     The woman passed a sandwich to the man because  0.463658  0.536342
2             Mary passed a sandwich to John because  0.343408  0.656592
3             Alice passed a sandwich to Bob because  0.478458  0.521542
4  The actress passed a sandwich to the actor bec...  0.278904  0.721096

In [297]:
# female subject
transofposs_perfective_connective1_19f = transofposs_perfective_connective1_19[0:12]
transofposs_perfective_connective1_19f = transofposs_perfective_connective1_19f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_19m = transofposs_perfective_connective1_19[12:24]

#### female subject

In [298]:
transofposs_perfective_connective1_19f

                                             stimulus       she        he
0   Miss Smith passed a sandwich to Mr. Smith because  0.933787  0.066213
1      The woman passed a sandwich to the man because  0.536342  0.463658
2              Mary passed a sandwich to John because  0.656592  0.343408
3              Alice passed a sandwich to Bob because  0.521542  0.478458
4   The actress passed a sandwich to the actor bec...  0.721096  0.278904
5       The girl passed a sandwich to the boy because  0.603244  0.396756
6   Mrs. Taylor passed a sandwich to Mr. Williams ...  0.530702  0.469298
7             Emma passed a sandwich to David because  0.729884  0.270116
8   The princess passed a sandwich to the prince b...  0.551037  0.448963
9           Sarah passed a sandwich to Robert because  0.664666  0.335334
10  Mrs. Williams passed a sandwich to  Mr. Taylor...  0.510507  0.489493
11            Emily passed a sandwich to Paul because  0.597256  0.402744

In [299]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_19f,'he'))

P('subj-pron'|subj=female) =  0.6297210405270258
P('non-subj-pron'|subj=female) =  0.3702789694070816

In [300]:
c1_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_connective1_19f,'she')
c1_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_connective1_19f,'he')

#### male subject

In [301]:
transofposs_perfective_connective1_19m

                                             stimulus        he       she
12  Mr. Smith passed a sandwich to Miss Smith because  0.524903  0.475097
13     The man passed a sandwich to the woman because  0.549274  0.450726
14             John passed a sandwich to Mary because  0.583600  0.416400
15             Bob passed a sandwich to Alice because  0.321738  0.678262
16  The actor passed a sandwich to the actress bec...  0.429665  0.570335
17      The boy passed a sandwich to the girl because  0.530558  0.469442
18  Mr. William passed a sandwich to  Mrs. Taylor ...  0.346960  0.653040
19            David passed a sandwich to Emma because  0.582204  0.417796
20  The prince passed a sandwich to the princess b...  0.718875  0.281125
21          Robert passed a sandwich to Sarah because  0.339474  0.660526
22  Mr. Taylor passed a sandwich to Mrs. Williams ...  0.166808  0.833193
23            Paul passed a sandwich to Emily because  0.401824  0.598176

In [302]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_19m,'she'))

P('subj-pron'|subj=male) =  0.4579902080198129
P('non-subj-pron'|subj=male) =  0.5420097957054774

In [303]:
c1_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_connective1_19m,'he')
c1_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_connective1_19m,'she')

### verb: "served"

In [304]:
transofposs_perfective_connective1_20 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective1/20.csv")
transofposs_perfective_connective1_20.head()

                                          stimulus        he       she
0   Miss Smith served a chili to Mr. Smith because  0.048728  0.951272
1      The woman served a chili to the man because  0.391486  0.608514
2              Mary served a chili to John because  0.084395  0.915605
3              Alice served a chili to Bob because  0.097701  0.902299
4  The actress served a chili to the actor because  0.121723  0.878277

In [305]:
# female subject
transofposs_perfective_connective1_20f = transofposs_perfective_connective1_20[0:12]
transofposs_perfective_connective1_20f = transofposs_perfective_connective1_20f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective1_20m = transofposs_perfective_connective1_20[12:24]

#### female subject

In [306]:
transofposs_perfective_connective1_20f

                                             stimulus       she        he
0      Miss Smith served a chili to Mr. Smith because  0.951272  0.048728
1         The woman served a chili to the man because  0.608514  0.391486
2                 Mary served a chili to John because  0.915605  0.084395
3                 Alice served a chili to Bob because  0.902299  0.097701
4     The actress served a chili to the actor because  0.878277  0.121723
5          The girl served a chili to the boy because  0.786302  0.213698
6   Mrs. Taylor served a chili to Mr. Williams bec...  0.755073  0.244927
7                Emma served a chili to David because  0.903205  0.096795
8   The princess served a chili to the prince because  0.741560  0.258440
9              Sarah served a chili to Robert because  0.906037  0.093963
10  Mrs. Williams served a chili to Mr. Taylor bec...  0.756854  0.243146
11               Emily served a chili to Paul because  0.818409  0.181591

In [307]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective1_20f,'he'))

P('subj-pron'|subj=female) =  0.8269506295522054
P('non-subj-pron'|subj=female) =  0.17304938472807407

In [308]:
c1_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_connective1_20f,'she')
c1_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_connective1_20f,'he')

#### male subject

In [309]:
transofposs_perfective_connective1_20m

                                             stimulus        he       she
12     Mr. Smith served a chili to Miss Smith because  0.717895  0.282105
13        The man served a chili to the woman because  0.582059  0.417941
14                John served a chili to Mary because  0.709425  0.290575
15                Bob served a chili to Alice because  0.656235  0.343765
16    The actor served a chili to the actress because  0.621813  0.378187
17         The boy served a chili to the girl because  0.692134  0.307866
18  Mr. William served a chili to  Mrs. Taylor bec...  0.552904  0.447096
19               David served a chili to Emma because  0.717709  0.282291
20  The prince served a chili to the princess because  0.859932  0.140068
21             Robert served a chili to Sarah because  0.616015  0.383985
22  Mr. Taylor served a chili to Mrs. Williams bec...  0.230401  0.769599
23               Paul served a chili to Emily because  0.556563  0.443437

In [310]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective1_20m,'she'))

P('subj-pron'|subj=male) =  0.6260904632508755
P('non-subj-pron'|subj=male) =  0.3739095367491245

In [311]:
c1_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_connective1_20m,'he')
c1_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_connective1_20m,'she')

## Summary of Results

In [312]:
c1_results_fsubj_subjpron = pd.DataFrame(list(c1_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c1_results_fsubj_objpron = pd.DataFrame(list(c1_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c1_results_fsubj = c1_results_fsubj_subjpron.merge(c1_results_fsubj_objpron)
c1_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0       chucked              0.670929             0.329071
1         flung              0.596479             0.403521
2        kicked              0.581241             0.418759
3        lobbed              0.486229             0.513771
4        rolled              0.653965             0.346035
5         threw              0.597962             0.402038
6        tossed              0.547894             0.452106
7       brought              0.681482             0.318518
8     forwarded              0.658079             0.341921
9        mailed              0.745420             0.254580
10      shipped              0.733490             0.266510
11  transmitted              0.738989             0.261011
12        wired              0.574839             0.425161
13      carried              0.780383             0.219617
14    delivered              0.604951             0.395049
15         gave              0.684407             0.315593
16       handed              0.634459             0.365541
17       passed              0.629721             0.370279
18       served              0.826951             0.173049

In [313]:
c1_results_msubj_subjpron = pd.DataFrame(list(c1_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c1_results_msubj_objpron = pd.DataFrame(list(c1_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c1_results_msubj = c1_results_msubj_subjpron.merge(c1_results_msubj_objpron)
c1_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0       chucked            0.465763           0.534237
1         flung            0.380341           0.619659
2        kicked            0.349973           0.650027
3        lobbed            0.299328           0.700672
4        rolled            0.450303           0.549697
5         threw            0.428135           0.571865
6        tossed            0.305495           0.694505
7       brought            0.390769           0.609231
8     forwarded            0.413500           0.586500
9        mailed            0.503154           0.496846
10      shipped            0.272675           0.727325
11  transmitted            0.442505           0.557495
12        wired            0.373782           0.626218
13      carried            0.417064           0.582936
14    delivered            0.303162           0.696838
15         gave            0.467403           0.532597
16       handed            0.338757           0.661243
17       passed            0.457990           0.542010
18       served            0.626090           0.373910

In [314]:
c1_results = c1_results_fsubj.merge(c1_results_msubj)
c1_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,chucked,0.670929,0.329071,0.465763,0.534237
1,flung,0.596479,0.403521,0.380341,0.619659
2,kicked,0.581241,0.418759,0.349973,0.650027
3,lobbed,0.486229,0.513771,0.299328,0.700672
4,rolled,0.653965,0.346035,0.450303,0.549697
5,threw,0.597962,0.402038,0.428135,0.571865
6,tossed,0.547894,0.452106,0.305495,0.694505
7,brought,0.681482,0.318518,0.390769,0.609231
8,forwarded,0.658079,0.341921,0.413500,0.586500
9,mailed,0.745420,0.254580,0.503154,0.496846
10,shipped,0.733490,0.266510,0.272675,0.727325
11,transmitted,0.738989,0.261011,0.442505,0.557495
12,wired,0.574839,0.425161,0.373782,0.626218
13,carried,0.780383,0.219617,0.417064,0.582936
14,delivered,0.604951,0.395049,0.303162,0.696838
15,gave,0.684407,0.315593,0.467403,0.532597
16,handed,0.634459,0.365541,0.338757,0.661243
17,passed,0.629721,0.370279,0.457990,0.542010
18,served,0.826951,0.173049,0.626090,0.373910

In [315]:
print("P(subj_reference |subj=female)", compute_average(c1_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c1_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.6540985034876748
P(obj_reference |subj=female) 0.34590149840764833

In [316]:
print("P(subj_reference |subj=male)", compute_average(c1_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c1_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.40453622990140786
P(obj_reference |subj=male) 0.5954637664713358

## Connective: "and, as a result"

In [317]:
c2_average_subj_female_subj_pron = {}
c2_average_subj_female_obj_pron = {}
c2_average_subj_male_subj_pron = {}
c2_average_subj_male_obj_pron = {}

### verb: "chucked"

In [318]:
transofposs_perfective_connective2_1 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/1.csv")
transofposs_perfective_connective2_1.head()

                                            stimulus        he       she
0  Miss Smith chucked a wrench to Mr. Smith and, ...  0.335461  0.664539
1  The woman chucked a wrench to the man and, as ...  0.489733  0.510267
2    Mary chucked a wrench to John and, as a result,  0.211756  0.788244
3    Alice chucked a wrench to Bob and, as a result,  0.404159  0.595841
4  The actress chucked a wrench to the actor and,...  0.683269  0.316731

In [319]:
# female subject
transofposs_perfective_connective2_1f = transofposs_perfective_connective2_1[0:12]
transofposs_perfective_connective2_1f = transofposs_perfective_connective2_1f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_1m = transofposs_perfective_connective2_1[12:24]

#### female subject

In [320]:
transofposs_perfective_connective2_1f

                                             stimulus       she        he
0   Miss Smith chucked a wrench to Mr. Smith and, ...  0.664539  0.335461
1   The woman chucked a wrench to the man and, as ...  0.510267  0.489733
2     Mary chucked a wrench to John and, as a result,  0.788244  0.211756
3     Alice chucked a wrench to Bob and, as a result,  0.595841  0.404159
4   The actress chucked a wrench to the actor and,...  0.316731  0.683269
5   The girl chucked a wrench to the boy and, as a...  0.527912  0.472088
6   Mrs. Taylor chucked a wrench to Mr. Williams a...  0.436925  0.563075
7    Emma chucked a wrench to David and, as a result,  0.660302  0.339698
8   The princess chucked a wrench to the prince an...  0.745503  0.254497
9   Sarah chucked a wrench to Robert and, as a res...  0.465285  0.534715
10  Mrs. Williams chucked a wrench to Mr. Taylor a...  0.441363  0.558637
11   Emily chucked a wrench to Paul and, as a result,  0.677053  0.322947

In [321]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_1f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_1f,'he'))

P('subj-pron'|subj=female) =  0.5691638911763827
P('non-subj-pron'|subj=female) =  0.4308361199994882

In [322]:
c2_average_subj_female_subj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1f,'she')
c2_average_subj_female_obj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1f,'he')

#### male subject

In [323]:
transofposs_perfective_connective2_1m

                                             stimulus        he       she
12  Mr. Smith chucked a wrench to Miss Smith and, ...  0.628247  0.371753
13  The man chucked a wrench to the woman and, as ...  0.837342  0.162658
14    John chucked a wrench to Mary and, as a result,  0.571167  0.428833
15    Bob chucked a wrench to Alice and, as a result,  0.859575  0.140425
16  The actor chucked a wrench to the actress and,...  0.935672  0.064328
17  The boy chucked a wrench to the girl and, as a...  0.898689  0.101311
18  Mr. William chucked a wrench to Mrs. Taylor an...  0.637082  0.362918
19   David chucked a wrench to Emma and, as a result,  0.636888  0.363112
20  The prince chucked a wrench to the princess an...  0.669728  0.330272
21  Robert chucked a wrench to Sarah and, as a res...  0.822018  0.177982
22  Mr. Taylor chucked a wrench to Mrs. Williams a...  0.508829  0.491171
23   Paul chucked a wrench to Emily and, as a result,  0.633505  0.366495

In [324]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_1m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_1m,'she'))

P('subj-pron'|subj=male) =  0.7198951741059622
P('non-subj-pron'|subj=male) =  0.28010482403139275

In [325]:
c2_average_subj_male_subj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1m,'he')
c2_average_subj_male_obj_pron['chucked'] = compute_average(transofposs_perfective_connective2_1m,'she')

### verb: "flung"

In [326]:
transofposs_perfective_connective2_2 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/2.csv")
transofposs_perfective_connective2_2.head()

                                            stimulus        he       she
0  Miss Smith flung a frisbee to Mr. Smith and, a...  0.393389  0.606611
1  The woman flung a frisbee to the man and, as a...  0.680153  0.319848
2     Mary flung a frisbee to John and, as a result,  0.438427  0.561573
3     Alice flung a frisbee to Bob and, as a result,  0.665419  0.334581
4  The actress flung a frisbee to the actor and, ...  0.811032  0.188968

In [327]:
# female subject
transofposs_perfective_connective2_2f = transofposs_perfective_connective2_2[0:12]
transofposs_perfective_connective2_2f = transofposs_perfective_connective2_2f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_2m = transofposs_perfective_connective2_2[12:24]

#### female subject

In [328]:
transofposs_perfective_connective2_2f

                                             stimulus       she        he
0   Miss Smith flung a frisbee to Mr. Smith and, a...  0.606611  0.393389
1   The woman flung a frisbee to the man and, as a...  0.319848  0.680153
2      Mary flung a frisbee to John and, as a result,  0.561573  0.438427
3      Alice flung a frisbee to Bob and, as a result,  0.334581  0.665419
4   The actress flung a frisbee to the actor and, ...  0.188968  0.811032
5   The girl flung a frisbee to the boy and, as a ...  0.211351  0.788648
6   Mrs. Taylor flung a frisbee to Mr. Williams an...  0.470148  0.529852
7     Emma flung a frisbee to David and, as a result,  0.482834  0.517166
8   The princess flung a frisbee to the prince and...  0.348108  0.651892
9   Sarah flung a frisbee to Robert and, as a result,  0.374462  0.625538
10  Mrs. Williams flung a frisbee to  Mr. Taylor a...  0.485904  0.514096
11    Emily flung a frisbee to Paul and, as a result,  0.573022  0.426978

In [329]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_2f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_2f,'he'))

P('subj-pron'|subj=female) =  0.41311748946706456
P('non-subj-pron'|subj=female) =  0.5868825192252795

In [330]:
c2_average_subj_female_subj_pron['flung'] = compute_average(transofposs_perfective_connective2_2f,'she')
c2_average_subj_female_obj_pron['flung'] = compute_average(transofposs_perfective_connective2_2f,'he')

#### male subject

In [331]:
transofposs_perfective_connective2_2m

                                             stimulus        he       she
12  Mr. Smith flung a frisbee to Miss Smith and, a...  0.347694  0.652306
13  The man flung a frisbee to the woman and, as a...  0.528529  0.471471
14     John flung a frisbee to Mary and, as a result,  0.264051  0.735949
15     Bob flung a frisbee to Alice and, as a result,  0.670430  0.329569
16  The actor flung a frisbee to the actress and, ...  0.713485  0.286515
17  The boy flung a frisbee to the girl and, as a ...  0.648859  0.351141
18  Mr. William flung a frisbee to  Mrs. Taylor an...  0.446046  0.553954
19    David flung a frisbee to Emma and, as a result,  0.256901  0.743099
20  The prince flung a frisbee to the princess and...  0.280431  0.719569
21  Robert flung a frisbee to Sarah and, as a result,  0.322554  0.677446
22  Mr. Taylor flung a frisbee to Mrs. Williams an...  0.466671  0.533329
23    Paul flung a frisbee to Emily and, as a result,  0.352918  0.647082

In [332]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_2m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_2m,'she'))

P('subj-pron'|subj=male) =  0.44154756764570874
P('non-subj-pron'|subj=male) =  0.5584524273872375

In [333]:
c2_average_subj_male_subj_pron['flung'] = compute_average(transofposs_perfective_connective2_2m,'he')
c2_average_subj_male_obj_pron['flung'] = compute_average(transofposs_perfective_connective2_2m,'she')

### verb: "kicked"

In [334]:
transofposs_perfective_connective2_3 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/3.csv")
transofposs_perfective_connective2_3.head()

                                            stimulus        he       she
0  Miss Smith kicked a soccer ball to Mr. Smith a...  0.483792  0.516208
1  The woman kicked a soccer ball to the man and,...  0.756467  0.243533
2  Mary kicked a soccer ball to John and, as a re...  0.452935  0.547065
3  Alice kicked a soccer ball to Bob and, as a re...  0.788258  0.211742
4  The actress kicked a soccer ball to the actor ...  0.794265  0.205735

In [335]:
# female subject
transofposs_perfective_connective2_3f = transofposs_perfective_connective2_3[0:12]
transofposs_perfective_connective2_3f = transofposs_perfective_connective2_3f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_3m = transofposs_perfective_connective2_3[12:24]

#### female subject

In [336]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_3f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_3f,'he'))

P('subj-pron'|subj=female) =  0.3447947750488917
P('non-subj-pron'|subj=female) =  0.6552052348852158

In [337]:
c2_average_subj_female_subj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3f,'she')
c2_average_subj_female_obj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3f,'he')

#### male subject

In [338]:
transofposs_perfective_connective2_3m

                                             stimulus        he       she
12  Mr. Smith kicked a soccer ball to Miss Smith a...  0.729454  0.270546
13  The man kicked a soccer ball to the woman and,...  0.809272  0.190728
14  John kicked a soccer ball to Mary and, as a re...  0.464169  0.535831
15  Bob kicked a soccer ball to Alice and, as a re...  0.920842  0.079158
16  The actor kicked a soccer ball to the actress ...  0.881102  0.118898
17  The boy kicked a soccer ball to the girl and, ...  0.888033  0.111967
18  Mr. William kicked a soccer ball to  Mrs. Tayl...  0.614309  0.385691
19  David kicked a soccer ball to Emma and, as a r...  0.636296  0.363704
20  The prince kicked a soccer ball to the princes...  0.540452  0.459548
21  Robert kicked a soccer ball to Sarah and, as a...  0.799286  0.200714
22  Mr. Taylor kicked a soccer ball to Mrs. Willia...  0.658665  0.341334
23  Paul kicked a soccer ball to Emily and, as a r...  0.719955  0.280045

In [339]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_3m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_3m,'she'))

P('subj-pron'|subj=male) =  0.7218195647001266
P('non-subj-pron'|subj=male) =  0.2781804172943036

In [340]:
c2_average_subj_male_subj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3m,'he')
c2_average_subj_male_obj_pron['kicked'] = compute_average(transofposs_perfective_connective2_3m,'she')

### verb: "lobbed"

In [341]:
transofposs_perfective_connective2_4 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/4.csv")
transofposs_perfective_connective2_4.head()

                                            stimulus        he       she
0  Miss Smith lobbed a football to Mr. Smith and,...  0.493636  0.506364
1  The woman lobbed a football to the man and, as...  0.649133  0.350867
2   Mary lobbed a football to John and, as a result,  0.453264  0.546736
3   Alice lobbed a football to Bob and, as a result,  0.741098  0.258902
4  The actress lobbed a football to the actor and...  0.784242  0.215758

In [342]:
# female subject
transofposs_perfective_connective2_4f = transofposs_perfective_connective2_4[0:12]
transofposs_perfective_connective2_4f = transofposs_perfective_connective2_4f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_4m = transofposs_perfective_connective2_4[12:24]

#### female subject

In [343]:
transofposs_perfective_connective2_4f

                                             stimulus       she        he
0   Miss Smith lobbed a football to Mr. Smith and,...  0.506364  0.493636
1   The woman lobbed a football to the man and, as...  0.350867  0.649133
2    Mary lobbed a football to John and, as a result,  0.546736  0.453264
3    Alice lobbed a football to Bob and, as a result,  0.258902  0.741098
4   The actress lobbed a football to the actor and...  0.215758  0.784242
5   The girl lobbed a football to the boy and, as ...  0.215213  0.784787
6   Mrs. Taylor lobbed a football to Mr. Williams ...  0.420979  0.579021
7   Emma lobbed a football to David and, as a result,  0.488498  0.511502
8   The princess lobbed a football to the prince a...  0.346822  0.653178
9   Sarah lobbed a football to Robert and, as a re...  0.320370  0.679630
10  Mrs. Williams lobbed a football to  Mr. Taylor...  0.452492  0.547508
11  Emily lobbed a football to Paul and, as a result,  0.573669  0.426331

In [344]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_4f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_4f,'he'))

P('subj-pron'|subj=female) =  0.39138907690842945
P('non-subj-pron'|subj=female) =  0.6086109181245168

In [345]:
c2_average_subj_female_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4f,'she')
c2_average_subj_female_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4f,'he')

#### male subject

In [346]:
transofposs_perfective_connective2_4m

                                             stimulus        he       she
12  Mr. Smith lobbed a football to Miss Smith and,...  0.353721  0.646279
13  The man lobbed a football to the woman and, as...  0.460312  0.539688
14   John lobbed a football to Mary and, as a result,  0.201381  0.798619
15   Bob lobbed a football to Alice and, as a result,  0.593669  0.406331
16  The actor lobbed a football to the actress and...  0.584436  0.415564
17  The boy lobbed a football to the girl and, as ...  0.507699  0.492301
18  Mr. William lobbed a football to  Mrs. Taylor ...  0.397729  0.602271
19  David lobbed a football to Emma and, as a result,  0.253272  0.746728
20  The prince lobbed a football to the princess a...  0.195758  0.804242
21  Robert lobbed a football to Sarah and, as a re...  0.346235  0.653765
22  Mr. Taylor lobbed a football to Mrs. Williams ...  0.415491  0.584509
23  Paul lobbed a football to Emily and, as a result,  0.304690  0.695310

In [347]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_4m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_4m,'she'))

P('subj-pron'|subj=male) =  0.38453276331226033
P('non-subj-pron'|subj=male) =  0.6154672503471375

In [348]:
c2_average_subj_male_subj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4m,'he')
c2_average_subj_male_obj_pron['lobbed'] = compute_average(transofposs_perfective_connective2_4m,'she')

### verb: "rolled"

In [349]:
transofposs_perfective_connective2_5 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/5.csv")
transofposs_perfective_connective2_5.head()

                                            stimulus        he       she
0  Miss Smith rolled a toy truck to Mr. Smith and...  0.369378  0.630622
1  The woman rolled a toy truck to the man and, a...  0.616002  0.383998
2  Mary rolled a toy truck to John and, as a result,  0.427277  0.572723
3  Alice rolled a toy truck to Bob and, as a result,  0.656119  0.343881
4  The actress rolled a toy truck to the actor an...  0.612813  0.387187

In [350]:
# female subject
transofposs_perfective_connective2_5f = transofposs_perfective_connective2_5[0:12]
transofposs_perfective_connective2_5f = transofposs_perfective_connective2_5[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_5m = transofposs_perfective_connective2_5[12:24]

#### female subject

In [351]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_5f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_5f,'he'))

P('subj-pron'|subj=female) =  0.4172429945319891
P('non-subj-pron'|subj=female) =  0.582757027198871

In [352]:
c2_average_subj_female_subj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5f,'she')
c2_average_subj_female_obj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5f,'he')

#### male subject

In [353]:
transofposs_perfective_connective2_5m

                                             stimulus        he       she
12  Mr. Smith rolled a toy truck to Miss Smith and...  0.585138  0.414862
13  The man rolled a toy truck to the woman and, a...  0.757696  0.242304
14  John rolled a toy truck to Mary and, as a result,  0.475148  0.524853
15  Bob rolled a toy truck to Alice and, as a result,  0.912245  0.087755
16  The actor rolled a toy truck to the actress an...  0.801019  0.198981
17  The boy rolled a toy truck to the girl and, as...  0.849446  0.150554
18  Mr. William rolled a toy truck to  Mrs. Taylor...  0.513024  0.486976
19  David rolled a toy truck to Emma and, as a res...  0.431303  0.568697
20  The prince rolled a toy truck to the princess ...  0.599678  0.400322
21  Robert rolled a toy truck to Sarah and, as a r...  0.627169  0.372831
22  Mr. Taylor rolled a toy truck to Mrs. Williams...  0.510500  0.489500
23  Paul rolled a toy truck to Emily and, as a res...  0.504723  0.495277

In [354]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_5m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_5m,'she'))

P('subj-pron'|subj=male) =  0.6305908014376959
P('non-subj-pron'|subj=male) =  0.3694092221558094

In [355]:
c2_average_subj_male_subj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5m,'he')
c2_average_subj_male_obj_pron['rolled'] = compute_average(transofposs_perfective_connective2_5m,'she')

### verb: "threw"

In [356]:
transofposs_perfective_connective2_6 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/6.csv")
transofposs_perfective_connective2_6.head()

                                            stimulus        he       she
0  Miss Smith threw a hat to Mr. Smith and, as a ...  0.368393  0.631607
1  The woman threw a hat to the man and, as a res...  0.698072  0.301928
2         Mary threw a hat to John and, as a result,  0.424314  0.575686
3         Alice threw a hat to Bob and, as a result,  0.627900  0.372100
4  The actress threw a hat to the actor and, as a...  0.776145  0.223855

In [357]:
# female subject
transofposs_perfective_connective2_6f = transofposs_perfective_connective2_6[0:12]
transofposs_perfective_connective2_6f = transofposs_perfective_connective2_6[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_6m = transofposs_perfective_connective2_6[12:24]

#### female subject

In [358]:
transofposs_perfective_connective2_6f

                                             stimulus       she        he
0   Miss Smith threw a hat to Mr. Smith and, as a ...  0.631607  0.368393
1   The woman threw a hat to the man and, as a res...  0.301928  0.698072
2          Mary threw a hat to John and, as a result,  0.575686  0.424314
3          Alice threw a hat to Bob and, as a result,  0.372100  0.627900
4   The actress threw a hat to the actor and, as a...  0.223855  0.776145
5   The girl threw a hat to the boy and, as a result,  0.270274  0.729726
6   Mrs. Taylor threw a hat to Mr. Williams and, a...  0.479957  0.520043
7         Emma threw a hat to David and, as a result,  0.558462  0.441538
8   The princess threw a hat to the prince and, as...  0.403499  0.596501
9       Sarah threw a hat to Robert and, as a result,  0.423407  0.576593
10  Mrs. Williams threw a hat to  Mr. Taylor and, ...  0.485278  0.514722
11        Emily threw a hat to Paul and, as a result,  0.525470  0.474530
12  Mr. Smith threw a hat to Miss Smith and, as a ...  0.596639  0.403361
13  The man threw a hat to the woman and, as a res...  0.290682  0.709318
14         John threw a hat to Mary and, as a result,  0.659809  0.340191
15         Bob threw a hat to Alice and, as a result,  0.288799  0.711201
16  The actor threw a hat to the actress and, as a...  0.297943  0.702057
17  The boy threw a hat to the girl and, as a result,  0.201940  0.798060
18  Mr. William threw a hat to  Mrs. Taylor and, a...  0.472710  0.527290
19        David threw a hat to Emma and, as a result,  0.688566  0.311434
20  The prince threw a hat to the princess and, as...  0.582483  0.417517
21      Robert threw a hat to Sarah and, as a result,  0.533135  0.466865
22  Mr. Taylor threw a hat to Mrs. Williams and, a...  0.473796  0.526204
23        Paul threw a hat to Emily and, as a result,  0.510229  0.489771

In [359]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_6f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_6f,'he'))

P('subj-pron'|subj=female) =  0.45201059865454835
P('non-subj-pron'|subj=female) =  0.5479894019663334

In [360]:
c2_average_subj_female_subj_pron['threw'] = compute_average(transofposs_perfective_connective2_6f,'she')
c2_average_subj_female_obj_pron['threw'] = compute_average(transofposs_perfective_connective2_6f,'he')

#### male subject

In [361]:
transofposs_perfective_connective2_6m

                                             stimulus        he       she
12  Mr. Smith threw a hat to Miss Smith and, as a ...  0.403361  0.596639
13  The man threw a hat to the woman and, as a res...  0.709318  0.290682
14         John threw a hat to Mary and, as a result,  0.340191  0.659809
15         Bob threw a hat to Alice and, as a result,  0.711201  0.288799
16  The actor threw a hat to the actress and, as a...  0.702057  0.297943
17  The boy threw a hat to the girl and, as a result,  0.798060  0.201940
18  Mr. William threw a hat to  Mrs. Taylor and, a...  0.527290  0.472710
19        David threw a hat to Emma and, as a result,  0.311434  0.688566
20  The prince threw a hat to the princess and, as...  0.417517  0.582483
21      Robert threw a hat to Sarah and, as a result,  0.466865  0.533135
22  Mr. Taylor threw a hat to Mrs. Williams and, a...  0.526204  0.473796
23        Paul threw a hat to Emily and, as a result,  0.489771  0.510229

In [362]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_6m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_6m,'she'))

P('subj-pron'|subj=male) =  0.5336058388153712
P('non-subj-pron'|subj=male) =  0.46639415994286537

In [363]:
c2_average_subj_male_subj_pron['threw'] = compute_average(transofposs_perfective_connective2_6m,'he')
c2_average_subj_male_obj_pron['threw'] = compute_average(transofposs_perfective_connective2_6m,'she')

### verb: "tossed"

In [364]:
transofposs_perfective_connective2_7 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/7.csv")
transofposs_perfective_connective2_7.head()

                                            stimulus        he       she
0  Miss Smith tossed a dish towel to Mr. Smith an...  0.457580  0.542420
1  The woman tossed a dish towel to the man and, ...  0.690942  0.309058
2  Mary tossed a dish towel to John and, as a res...  0.439713  0.560287
3  Alice tossed a dish towel to Bob and, as a res...  0.596938  0.403062
4  The actress tossed a dish towel to the actor a...  0.763445  0.236555

In [365]:
# female subject
transofposs_perfective_connective2_7f = transofposs_perfective_connective2_7[0:12]
transofposs_perfective_connective2_7f = transofposs_perfective_connective2_7f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_7m = transofposs_perfective_connective2_7[12:24]

#### female subject

In [366]:
transofposs_perfective_connective2_7f

                                             stimulus       she        he
0   Miss Smith tossed a dish towel to Mr. Smith an...  0.542420  0.457580
1   The woman tossed a dish towel to the man and, ...  0.309058  0.690942
2   Mary tossed a dish towel to John and, as a res...  0.560287  0.439713
3   Alice tossed a dish towel to Bob and, as a res...  0.403062  0.596938
4   The actress tossed a dish towel to the actor a...  0.236555  0.763445
5   The girl tossed a dish towel to the boy and, a...  0.236991  0.763009
6   Mrs. Taylor tossed a dish towel to Mr. William...  0.422563  0.577437
7   Emma tossed a dish towel to David and, as a re...  0.542048  0.457952
8   The princess tossed a dish towel to the prince...  0.378687  0.621313
9   Sarah tossed a dish towel to Robert and, as a ...  0.379519  0.620481
10  Mrs. Williams tossed a dish towel to  Mr. Tayl...  0.445775  0.554225
11  Emily tossed a dish towel to Paul and, as a re...  0.530046  0.469954

In [367]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_7f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_7f,'he'))

P('subj-pron'|subj=female) =  0.41558410972356796
P('non-subj-pron'|subj=female) =  0.5844159076611201

In [368]:
c2_average_subj_female_subj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7f,'she')
c2_average_subj_female_obj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7f,'he')

#### male subject

In [369]:
transofposs_perfective_connective2_7m

                                             stimulus        he       she
12  Mr. Smith tossed a dish towel to Miss Smith an...  0.385244  0.614756
13  The man tossed a dish towel to the woman and, ...  0.552720  0.447280
14  John tossed a dish towel to Mary and, as a res...  0.288883  0.711117
15  Bob tossed a dish towel to Alice and, as a res...  0.558754  0.441246
16  The actor tossed a dish towel to the actress a...  0.594726  0.405274
17  The boy tossed a dish towel to the girl and, a...  0.580542  0.419458
18  Mr. William tossed a dish towel to  Mrs. Taylo...  0.472927  0.527073
19  David tossed a dish towel to Emma and, as a re...  0.280854  0.719146
20  The prince tossed a dish towel to the princess...  0.292724  0.707276
21  Robert tossed a dish towel to Sarah and, as a ...  0.358095  0.641905
22  Mr. Taylor tossed a dish towel to Mrs. William...  0.488425  0.511575
23  Paul tossed a dish towel to Emily and, as a re...  0.361997  0.638003

In [370]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_7m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_7m,'she'))

P('subj-pron'|subj=male) =  0.4346574271718661
P('non-subj-pron'|subj=male) =  0.5653425777951876

In [371]:
c2_average_subj_male_subj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7m,'he')
c2_average_subj_male_obj_pron['tossed'] = compute_average(transofposs_perfective_connective2_7m,'she')

#### verb: "brought"

In [372]:
transofposs_perfective_connective2_8 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/8.csv")
transofposs_perfective_connective2_8.head()

                                            stimulus        he       she
0  Miss Smith brought a glass of water to Mr. Smi...  0.309633  0.690367
1  The woman brought a glass of water to the man ...  0.609039  0.390961
2  Mary brought a glass of water to John and, as ...  0.372617  0.627383
3  Alice brought a glass of water to Bob and, as ...  0.446428  0.553572
4  The actress brought a glass of water to the ac...  0.398107  0.601893

In [373]:
# female subject
transofposs_perfective_connective2_8f = transofposs_perfective_connective2_8[0:12]
transofposs_perfective_connective2_8f = transofposs_perfective_connective2_8f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_8m = transofposs_perfective_connective2_8[12:24]

#### female subject

In [374]:
transofposs_perfective_connective2_8f

                                             stimulus       she        he
0   Miss Smith brought a glass of water to Mr. Smi...  0.690367  0.309633
1   The woman brought a glass of water to the man ...  0.390961  0.609039
2   Mary brought a glass of water to John and, as ...  0.627383  0.372617
3   Alice brought a glass of water to Bob and, as ...  0.553572  0.446428
4   The actress brought a glass of water to the ac...  0.601893  0.398107
5   The girl brought a glass of water to the boy a...  0.265052  0.734948
6   Mrs. Taylor brought a glass of water to Mr. Wi...  0.453632  0.546368
7   Emma brought a glass of water to David and, as...  0.581942  0.418058
8   The princess brought a glass of water to the p...  0.489801  0.510199
9   Sarah brought a glass of water to Robert and, ...  0.427242  0.572758
10  Mrs. Williams brought a glass of water to  Mr....  0.455868  0.544132
11  Emily brought a glass of water to Paul and, as...  0.598700  0.401300

In [375]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_8f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_8f,'he'))

P('subj-pron'|subj=female) =  0.5113677506645521
P('non-subj-pron'|subj=female) =  0.4886322443683942

In [376]:
c2_average_subj_female_subj_pron['brought'] = compute_average(transofposs_perfective_connective2_8f,'she')
c2_average_subj_female_obj_pron['brought'] = compute_average(transofposs_perfective_connective2_8f,'he')

#### male subject

In [377]:
transofposs_perfective_connective2_8m

                                             stimulus        he       she
12  Mr. Smith brought a glass of water to Miss Smi...  0.341770  0.658230
13  The man brought a glass of water to the woman ...  0.449089  0.550911
14  John brought a glass of water to Mary and, as ...  0.241693  0.758307
15  Bob brought a glass of water to Alice and, as ...  0.501803  0.498197
16  The actor brought a glass of water to the actr...  0.502784  0.497216
17  The boy brought a glass of water to the girl a...  0.524185  0.475815
18  Mr. William brought a glass of water to  Mrs. ...  0.445506  0.554494
19  David brought a glass of water to Emma and, as...  0.395136  0.604864
20  The prince brought a glass of water to the pri...  0.247671  0.752329
21  Robert brought a glass of water to Sarah and, ...  0.484929  0.515071
22  Mr. Taylor brought a glass of water to Mrs. Wi...  0.411923  0.588077
23  Paul brought a glass of water to Emily and, as...  0.358031  0.641969

In [378]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_8m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_8m,'she'))

P('subj-pron'|subj=male) =  0.40870995943744975
P('non-subj-pron'|subj=male) =  0.5912900467713674

In [379]:
c2_average_subj_male_subj_pron['brought'] = compute_average(transofposs_perfective_connective2_8m,'he')
c2_average_subj_male_obj_pron['brought'] = compute_average(transofposs_perfective_connective2_8m,'she')

### verb: "forwarded"

In [380]:
transofposs_perfective_connective2_9 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/9.csv")
transofposs_perfective_connective2_9.head()

                                            stimulus        he       she
0  Miss Smith forwarded a gossipy email to Mr. Sm...  0.174340  0.825660
1  The woman forwarded a gossipy email to the man...  0.550808  0.449192
2  Mary forwarded a gossipy email to John and, as...  0.354063  0.645937
3  Alice forwarded a gossipy email to Bob and, as...  0.473394  0.526606
4  The actress forwarded a gossipy email to the a...  0.330456  0.669544

In [381]:
# female subject
transofposs_perfective_connective2_9f = transofposs_perfective_connective2_9[0:12]
transofposs_perfective_connective2_9f = transofposs_perfective_connective2_9f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_9m = transofposs_perfective_connective2_9[12:24]

#### female subject

In [382]:
transofposs_perfective_connective2_9f

                                             stimulus       she        he
0   Miss Smith forwarded a gossipy email to Mr. Sm...  0.825660  0.174340
1   The woman forwarded a gossipy email to the man...  0.449192  0.550808
2   Mary forwarded a gossipy email to John and, as...  0.645937  0.354063
3   Alice forwarded a gossipy email to Bob and, as...  0.526606  0.473394
4   The actress forwarded a gossipy email to the a...  0.669544  0.330456
5   The girl forwarded a gossipy email to the boy ...  0.408479  0.591521
6   Mrs. Taylor forwarded a gossipy email to Mr. W...  0.664810  0.335190
7   Emma forwarded a gossipy email to David and, a...  0.756976  0.243024
8   The princess forwarded a gossipy email to the ...  0.458346  0.541654
9   Sarah forwarded a gossipy email to Robert and,...  0.447131  0.552869
10  Mrs. Williams forwarded a gossipy email to  Mr...  0.685882  0.314118
11  Emily forwarded a gossipy email to Paul and, a...  0.692297  0.307703

In [383]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_9f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_9f,'he'))

P('subj-pron'|subj=female) =  0.6025717929005623
P('non-subj-pron'|subj=female) =  0.3974282244841258

In [384]:
c2_average_subj_female_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9f,'she')
c2_average_subj_female_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9f,'he')

#### male subject

In [385]:
transofposs_perfective_connective2_9m

                                             stimulus        he       she
12  Mr. Smith forwarded a gossipy email to Miss Sm...  0.232786  0.767214
13  The man forwarded a gossipy email to the woman...  0.449903  0.550097
14  John forwarded a gossipy email to Mary and, as...  0.200167  0.799833
15  Bob forwarded a gossipy email to Alice and, as...  0.415542  0.584458
16  The actor forwarded a gossipy email to the act...  0.356081  0.643919
17  The boy forwarded a gossipy email to the girl ...  0.438701  0.561299
18  Mr. William forwarded a gossipy email to  Mrs....  0.247823  0.752177
19  David forwarded a gossipy email to Emma and, a...  0.236669  0.763331
20  The prince forwarded a gossipy email to the pr...  0.328936  0.671064
21  Robert forwarded a gossipy email to Sarah and,...  0.367437  0.632563
22  Mr. Taylor forwarded a gossipy email to Mrs. W...  0.213269  0.786731
23  Paul forwarded a gossipy email to Emily and, a...  0.433206  0.566794

In [386]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_9m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_9m,'she'))

P('subj-pron'|subj=male) =  0.32670995220541954
P('non-subj-pron'|subj=male) =  0.6732900540033976

In [387]:
c2_average_subj_male_subj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9m,'he')
c2_average_subj_male_obj_pron['forwarded'] = compute_average(transofposs_perfective_connective2_9m,'she')

### verb: "mailed"

In [388]:
transofposs_perfective_connective2_10 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/10.csv")
transofposs_perfective_connective2_10.head()

                                            stimulus        he       she
0  Miss Smith mailed a letter to Mr. Smith and, a...  0.159676  0.840324
1  The woman mailed a letter to the man and, as a...  0.491690  0.508310
2     Mary mailed a letter to John and, as a result,  0.423385  0.576615
3     Alice mailed a letter to Bob and, as a result,  0.476378  0.523622
4  The actress mailed a letter to the actor and, ...  0.382718  0.617282

In [389]:
# female subject
transofposs_perfective_connective2_10f = transofposs_perfective_connective2_10[0:12]
transofposs_perfective_connective2_10f = transofposs_perfective_connective2_10f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_10m = transofposs_perfective_connective2_10[12:24]

#### female subject

In [390]:
transofposs_perfective_connective2_10f

                                             stimulus       she        he
0   Miss Smith mailed a letter to Mr. Smith and, a...  0.840324  0.159676
1   The woman mailed a letter to the man and, as a...  0.508310  0.491690
2      Mary mailed a letter to John and, as a result,  0.576615  0.423385
3      Alice mailed a letter to Bob and, as a result,  0.523622  0.476378
4   The actress mailed a letter to the actor and, ...  0.617282  0.382718
5   The girl mailed a letter to the boy and, as a ...  0.450837  0.549163
6   Mrs. Taylor mailed a letter to Mr. Williams an...  0.702403  0.297597
7     Emma mailed a letter to David and, as a result,  0.763676  0.236324
8   The princess mailed a letter to the prince and...  0.422419  0.577581
9   Sarah mailed a letter to Robert and, as a result,  0.435996  0.564004
10  Mrs. Williams mailed a letter to  Mr. Taylor a...  0.727027  0.272973
11    Emily mailed a letter to Paul and, as a result,  0.720895  0.279105

In [391]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_10f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_10f,'he'))

P('subj-pron'|subj=female) =  0.6074504852294922
P('non-subj-pron'|subj=female) =  0.39254951228698093

In [392]:
c2_average_subj_female_subj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10f,'she')
c2_average_subj_female_obj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10f,'he')

#### male subject

In [393]:
transofposs_perfective_connective2_10m

                                             stimulus        he       she
12  Mr. Smith mailed a letter to Miss Smith and, a...  0.166043  0.833957
13  The man mailed a letter to the woman and, as a...  0.276050  0.723950
14     John mailed a letter to Mary and, as a result,  0.216964  0.783036
15     Bob mailed a letter to Alice and, as a result,  0.357604  0.642396
16  The actor mailed a letter to the actress and, ...  0.215216  0.784784
17  The boy mailed a letter to the girl and, as a ...  0.247844  0.752156
18  Mr. William mailed a letter to  Mrs. Taylor an...  0.275522  0.724478
19    David mailed a letter to Emma and, as a result,  0.201732  0.798268
20  The prince mailed a letter to the princess and...  0.187715  0.812285
21  Robert mailed a letter to Sarah and, as a result,  0.203609  0.796391
22  Mr. Taylor mailed a letter to Mrs. Williams an...  0.206392  0.793608
23    Paul mailed a letter to Emily and, as a result,  0.444776  0.555224

In [394]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_10m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_10m,'she'))

P('subj-pron'|subj=male) =  0.24995565538605055
P('non-subj-pron'|subj=male) =  0.7500443508227667

In [395]:
c2_average_subj_male_subj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10m,'he')
c2_average_subj_male_obj_pron['mailed'] = compute_average(transofposs_perfective_connective2_10m,'she')

### verb: "shipped"

In [396]:
transofposs_perfective_connective2_11 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/11.csv")
transofposs_perfective_connective2_11.head()

                                            stimulus        he       she
0  Miss Smith shipped a package to Mr. Smith and,...  0.198396  0.801604
1  The woman shipped a package to the man and, as...  0.489779  0.510221
2   Mary shipped a package to John and, as a result,  0.291920  0.708080
3   Alice shipped a package to Bob and, as a result,  0.327949  0.672051
4  The actress shipped a package to the actor and...  0.259352  0.740648

In [397]:
# female subject
transofposs_perfective_connective2_11f = transofposs_perfective_connective2_11[0:12]
transofposs_perfective_connective2_11f = transofposs_perfective_connective2_11f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_11m = transofposs_perfective_connective2_11[12:24]

#### female subject

In [398]:
transofposs_perfective_connective2_11f

                                             stimulus       she        he
0   Miss Smith shipped a package to Mr. Smith and,...  0.801604  0.198396
1   The woman shipped a package to the man and, as...  0.510221  0.489779
2    Mary shipped a package to John and, as a result,  0.708080  0.291920
3    Alice shipped a package to Bob and, as a result,  0.672051  0.327949
4   The actress shipped a package to the actor and...  0.740648  0.259352
5   The girl shipped a package to the boy and, as ...  0.435608  0.564392
6   Mrs. Taylor shipped a package to Mr. Williams ...  0.690399  0.309601
7   Emma shipped a package to David and, as a result,  0.847090  0.152910
8   The princess shipped a package to the prince a...  0.551994  0.448006
9   Sarah shipped a package to Robert and, as a re...  0.617733  0.382267
10  Mrs. Williams shipped a package to  Mr. Taylor...  0.702546  0.297454
11  Emily shipped a package to Paul and, as a result,  0.763072  0.236928

In [399]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_11f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_11f,'he'))

P('subj-pron'|subj=female) =  0.6700871388117472
P('non-subj-pron'|subj=female) =  0.3299128785729408

In [400]:
c2_average_subj_female_subj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11f,'she')
c2_average_subj_female_obj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11f,'he')

#### male subject

In [401]:
transofposs_perfective_connective2_11m

                                             stimulus        he       she
12  Mr. Smith shipped a package to Miss Smith and,...  0.344880  0.655119
13  The man shipped a package to the woman and, as...  0.494234  0.505766
14   John shipped a package to Mary and, as a result,  0.249118  0.750882
15   Bob shipped a package to Alice and, as a result,  0.558998  0.441002
16  The actor shipped a package to the actress and...  0.446275  0.553725
17  The boy shipped a package to the girl and, as ...  0.565970  0.434030
18  Mr. William shipped a package to  Mrs. Taylor ...  0.260148  0.739852
19  David shipped a package to Emma and, as a result,  0.233895  0.766105
20  The prince shipped a package to the princess a...  0.354935  0.645065
21  Robert shipped a package to Sarah and, as a re...  0.417444  0.582556
22  Mr. Taylor shipped a package to Mrs. Williams ...  0.219788  0.780212
23  Paul shipped a package to Emily and, as a result,  0.379676  0.620324

In [402]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_11m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_11m,'she'))

P('subj-pron'|subj=male) =  0.37711334476868313
P('non-subj-pron'|subj=male) =  0.62288665274779

In [403]:
c2_average_subj_male_subj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11m,'he')
c2_average_subj_male_obj_pron['shipped'] = compute_average(transofposs_perfective_connective2_11m,'she')

### verb: "transmitted"

In [404]:
transofposs_perfective_connective2_12 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/12.csv")
transofposs_perfective_connective2_12.head()

                                            stimulus        he       she
0  Miss Smith transmitted a message to Mr. Smith ...  0.253135  0.746865
1  The woman transmitted a message to the man and...  0.601858  0.398142
2  Mary transmitted a message to John and, as a r...  0.356817  0.643183
3  Alice transmitted a message to Bob and, as a r...  0.525969  0.474031
4  The actress transmitted a message to the actor...  0.471903  0.528097

In [405]:
# female subject
transofposs_perfective_connective2_12f = transofposs_perfective_connective2_12[0:12]
transofposs_perfective_connective2_12f = transofposs_perfective_connective2_12f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_12m = transofposs_perfective_connective2_12[12:24]

#### female subject

In [406]:
transofposs_perfective_connective2_12f

                                             stimulus       she        he
0   Miss Smith transmitted a message to Mr. Smith ...  0.746865  0.253135
1   The woman transmitted a message to the man and...  0.398142  0.601858
2   Mary transmitted a message to John and, as a r...  0.643183  0.356817
3   Alice transmitted a message to Bob and, as a r...  0.474031  0.525969
4   The actress transmitted a message to the actor...  0.528097  0.471903
5   The girl transmitted a message to the boy and,...  0.322070  0.677930
6   Mrs. Taylor transmitted a message to Mr. Willi...  0.659976  0.340024
7   Emma transmitted a message to David and, as a ...  0.746302  0.253698
8   The princess transmitted a message to the prin...  0.357156  0.642844
9   Sarah transmitted a message to Robert and, as ...  0.514250  0.485750
10  Mrs. Williams transmitted a message to  Mr. Ta...  0.703060  0.296940
11  Emily transmitted a message to Paul and, as a ...  0.735399  0.264601

In [407]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_12f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_12f,'he'))

P('subj-pron'|subj=female) =  0.5690442820390066
P('non-subj-pron'|subj=female) =  0.43095571796099347

In [408]:
c2_average_subj_female_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12f,'she')
c2_average_subj_female_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12f,'he')

#### male subject

In [409]:
transofposs_perfective_connective2_12m

                                             stimulus        he       she
12  Mr. Smith transmitted a message to Miss Smith ...  0.216480  0.783520
13  The man transmitted a message to the woman and...  0.239673  0.760327
14  John transmitted a message to Mary and, as a r...  0.099747  0.900253
15  Bob transmitted a message to Alice and, as a r...  0.339973  0.660027
16  The actor transmitted a message to the actress...  0.209092  0.790908
17  The boy transmitted a message to the girl and,...  0.218412  0.781588
18  Mr. William transmitted a message to  Mrs. Tay...  0.189520  0.810480
19  David transmitted a message to Emma and, as a ...  0.162173  0.837827
20  The prince transmitted a message to the prince...  0.131749  0.868251
21  Robert transmitted a message to Sarah and, as ...  0.168931  0.831069
22  Mr. Taylor transmitted a message to Mrs. Willi...  0.166465  0.833535
23  Paul transmitted a message to Emily and, as a ...  0.304204  0.695796

In [410]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_12m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_12m,'she'))

P('subj-pron'|subj=male) =  0.2038682090739409
P('non-subj-pron'|subj=male) =  0.7961317896842957

In [411]:
c2_average_subj_male_subj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12m,'he')
c2_average_subj_male_obj_pron['transmitted'] = compute_average(transofposs_perfective_connective2_12m,'she')

### verb: "wired"

In [412]:
transofposs_perfective_connective2_14 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/14.csv")
transofposs_perfective_connective2_14.head()

                                            stimulus        he       she
0  Miss Smith wired money to Mr. Smith and, as a ...  0.262092  0.737908
1  The woman wired money to the man and, as a res...  0.668662  0.331338
2         Mary wired money to John and, as a result,  0.549238  0.450762
3         Alice wired money to Bob and, as a result,  0.648068  0.351932
4  The actress wired money to the actor and, as a...  0.624528  0.375472

In [413]:
# female subject
transofposs_perfective_connective2_14f = transofposs_perfective_connective2_14[0:12]
transofposs_perfective_connective2_14f = transofposs_perfective_connective2_14f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_14m = transofposs_perfective_connective2_14[12:24]

#### female subject

In [414]:
transofposs_perfective_connective2_14f

                                             stimulus       she        he
0   Miss Smith wired money to Mr. Smith and, as a ...  0.737908  0.262092
1   The woman wired money to the man and, as a res...  0.331338  0.668662
2          Mary wired money to John and, as a result,  0.450762  0.549238
3          Alice wired money to Bob and, as a result,  0.351932  0.648068
4   The actress wired money to the actor and, as a...  0.375472  0.624528
5   The girl wired money to the boy and, as a result,  0.300746  0.699254
6   Mrs. Taylor wired money to Mr. Williams and, a...  0.621885  0.378115
7         Emma wired money to David and, as a result,  0.615974  0.384026
8   The princess wired money to the prince and, as...  0.280738  0.719262
9       Sarah wired money to Robert and, as a result,  0.383018  0.616982
10  Mrs. Williams wired money to  Mr. Taylor and, ...  0.617256  0.382744
11        Emily wired money to Paul and, as a result,  0.566222  0.433778

In [415]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_14f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_14f,'he'))

P('subj-pron'|subj=female) =  0.4694378152489662
P('non-subj-pron'|subj=female) =  0.530562199652195

In [416]:
c2_average_subj_female_subj_pron['wired'] = compute_average(transofposs_perfective_connective2_14f,'she')
c2_average_subj_female_obj_pron['wired'] = compute_average(transofposs_perfective_connective2_14f,'he')

#### male subject

In [417]:
transofposs_perfective_connective2_14m

                                             stimulus        he       she
12  Mr. Smith wired money to Miss Smith and, as a ...  0.176966  0.823034
13  The man wired money to the woman and, as a res...  0.255962  0.744038
14         John wired money to Mary and, as a result,  0.111509  0.888491
15         Bob wired money to Alice and, as a result,  0.320415  0.679585
16  The actor wired money to the actress and, as a...  0.207012  0.792988
17  The boy wired money to the girl and, as a result,  0.242691  0.757309
18  Mr. William wired money to  Mrs. Taylor and, a...  0.200726  0.799274
19        David wired money to Emma and, as a result,  0.165959  0.834041
20  The prince wired money to the princess and, as...  0.110497  0.889503
21      Robert wired money to Sarah and, as a result,  0.190411  0.809589
22  Mr. Taylor wired money to Mrs. Williams and, a...  0.149060  0.850940
23        Paul wired money to Emily and, as a result,  0.331955  0.668045

In [418]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_14m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_14m,'she'))

P('subj-pron'|subj=male) =  0.20526351096729437
P('non-subj-pron'|subj=male) =  0.7947364797194799

In [419]:
c2_average_subj_male_subj_pron['wired'] = compute_average(transofposs_perfective_connective2_14m,'he')
c2_average_subj_male_obj_pron['wired'] = compute_average(transofposs_perfective_connective2_14m,'she')

### verb: "carried"

In [420]:
transofposs_perfective_connective2_15 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/15.csv")
transofposs_perfective_connective2_15.head()

                                            stimulus        he       she
0  Miss Smith carried a tray to Mr. Smith and, as...  0.285293  0.714707
1  The woman carried a tray to the man and, as a ...  0.477933  0.522067
2      Mary carried a tray to John and, as a result,  0.228827  0.771173
3      Alice carried a tray to Bob and, as a result,  0.418149  0.581851
4  The actress carried a tray to the actor and, a...  0.378523  0.621477

In [421]:
# female subject
transofposs_perfective_connective2_15f = transofposs_perfective_connective2_15[0:12]
transofposs_perfective_connective2_15f = transofposs_perfective_connective2_15f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_15m = transofposs_perfective_connective2_15[12:24]

#### female subject

In [422]:
transofposs_perfective_connective2_15f

                                             stimulus       she        he
0   Miss Smith carried a tray to Mr. Smith and, as...  0.714707  0.285293
1   The woman carried a tray to the man and, as a ...  0.522067  0.477933
2       Mary carried a tray to John and, as a result,  0.771173  0.228827
3       Alice carried a tray to Bob and, as a result,  0.581851  0.418149
4   The actress carried a tray to the actor and, a...  0.621477  0.378523
5   The girl carried a tray to the boy and, as a r...  0.488823  0.511177
6   Mrs. Taylor carried a tray to Mr. Williams and...  0.614045  0.385955
7      Emma carried a tray to David and, as a result,  0.759506  0.240494
8   The princess carried a tray to the prince and,...  0.627023  0.372977
9    Sarah carried a tray to Robert and, as a result,  0.572755  0.427245
10  Mrs. Williams carried a tray to  Mr. Taylor an...  0.649604  0.350396
11     Emily carried a tray to Paul and, as a result,  0.688608  0.311392

In [423]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_15f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_15f,'he'))

P('subj-pron'|subj=female) =  0.6343031252423922
P('non-subj-pron'|subj=female) =  0.36569685861468315

In [424]:
c2_average_subj_female_subj_pron['carried'] = compute_average(transofposs_perfective_connective2_15f,'she')
c2_average_subj_female_obj_pron['carried'] = compute_average(transofposs_perfective_connective2_15f,'he')

#### male subject

In [425]:
transofposs_perfective_connective2_15m

                                             stimulus        he       she
12  Mr. Smith carried a tray to Miss Smith and, as...  0.401659  0.598341
13  The man carried a tray to the woman and, as a ...  0.700897  0.299103
14      John carried a tray to Mary and, as a result,  0.407661  0.592338
15      Bob carried a tray to Alice and, as a result,  0.828587  0.171413
16  The actor carried a tray to the actress and, a...  0.819727  0.180273
17  The boy carried a tray to the girl and, as a r...  0.779301  0.220699
18  Mr. William carried a tray to  Mrs. Taylor and...  0.364001  0.635999
19     David carried a tray to Emma and, as a result,  0.382586  0.617414
20  The prince carried a tray to the princess and,...  0.641836  0.358164
21   Robert carried a tray to Sarah and, as a result,  0.554839  0.445161
22  Mr. Taylor carried a tray to Mrs. Williams and...  0.350523  0.649477
23     Paul carried a tray to Emily and, as a result,  0.425022  0.574978

In [426]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_15m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_15m,'she'))

P('subj-pron'|subj=male) =  0.5547199745972952
P('non-subj-pron'|subj=male) =  0.4452800241609414

In [427]:
c2_average_subj_male_subj_pron['carried'] = compute_average(transofposs_perfective_connective2_15m,'he')
c2_average_subj_male_obj_pron['carried'] = compute_average(transofposs_perfective_connective2_15m,'she')

### verb: "delivered"

In [428]:
transofposs_perfective_connective2_16 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/16.csv")
transofposs_perfective_connective2_16.head()

                                            stimulus        he       she
0  Miss Smith delivered a subpoena to Mr. Smith a...  0.275935  0.724065
1  The woman delivered a subpoena to the man and,...  0.646000  0.354000
2  Mary delivered a subpoena to John and, as a re...  0.418113  0.581887
3  Alice delivered a subpoena to Bob and, as a re...  0.575614  0.424386
4  The actress delivered a subpoena to the actor ...  0.527315  0.472685

In [429]:
# female subject
transofposs_perfective_connective2_16f = transofposs_perfective_connective2_16[0:12]
transofposs_perfective_connective2_16f = transofposs_perfective_connective2_16f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_16m = transofposs_perfective_connective2_16[12:24]

#### female subject

In [430]:
transofposs_perfective_connective2_16f

                                             stimulus       she        he
0   Miss Smith delivered a subpoena to Mr. Smith a...  0.724065  0.275935
1   The woman delivered a subpoena to the man and,...  0.354000  0.646000
2   Mary delivered a subpoena to John and, as a re...  0.581887  0.418113
3   Alice delivered a subpoena to Bob and, as a re...  0.424386  0.575614
4   The actress delivered a subpoena to the actor ...  0.472685  0.527315
5   The girl delivered a subpoena to the boy and, ...  0.316854  0.683146
6   Mrs. Taylor delivered a subpoena to Mr. Willia...  0.526108  0.473892
7   Emma delivered a subpoena to David and, as a r...  0.624695  0.375305
8   The princess delivered a subpoena to the princ...  0.447984  0.552016
9   Sarah delivered a subpoena to Robert and, as a...  0.460005  0.539995
10  Mrs. Williams delivered a subpoena to Mr. Tayl...  0.545245  0.454755
11  Emily delivered a subpoena to Paul and, as a r...  0.643058  0.356942

In [431]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_16f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_16f,'he'))

P('subj-pron'|subj=female) =  0.5100810378789902
P('non-subj-pron'|subj=female) =  0.48991894721984863

In [432]:
c2_average_subj_female_subj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16f,'she')
c2_average_subj_female_obj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16f,'he')

#### male subject

In [433]:
transofposs_perfective_connective2_16m

                                             stimulus        he       she
12  Mr. Smith delivered a subpoena to Miss Smith a...  0.295215  0.704785
13  The man delivered a subpoena to the woman and,...  0.549491  0.450509
14  John delivered a subpoena to Mary and, as a re...  0.239592  0.760408
15  Bob delivered a subpoena to Alice and, as a re...  0.464649  0.535351
16  The actor delivered a subpoena to the actress ...  0.610139  0.389861
17  The boy delivered a subpoena to the girl and, ...  0.565903  0.434097
18  Mr. William delivered a subpoena to Mrs. Taylo...  0.295806  0.704194
19  David delivered a subpoena to Emma and, as a r...  0.387274  0.612726
20  The prince delivered a subpoena to the princes...  0.337145  0.662855
21  Robert delivered a subpoena to Sarah and, as a...  0.489633  0.510367
22  Mr. Taylor delivered a subpoena to Mrs. Willia...  0.277619  0.722381
23  Paul delivered a subpoena to Emily and, as a r...  0.439762  0.560238

In [434]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_16m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_16m,'she'))

P('subj-pron'|subj=male) =  0.41268571590383846
P('non-subj-pron'|subj=male) =  0.5873142952720324

In [435]:
c2_average_subj_male_subj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16m,'he')
c2_average_subj_male_obj_pron['delivered'] = compute_average(transofposs_perfective_connective2_16m,'she')

### verb: "gave"

In [436]:
transofposs_perfective_connective2_17 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/17.csv")
transofposs_perfective_connective2_17.head()

                                            stimulus        he       she
0  Miss Smith gave a sweater to Mr. Smith and, as...  0.308714  0.691286
1  The woman gave a sweater to the man and, as a ...  0.757729  0.242271
2      Mary gave a sweater to John and, as a result,  0.543267  0.456733
3      Alice gave a sweater to Bob and, as a result,  0.644162  0.355838
4  The actress gave a sweater to the actor and, a...  0.669398  0.330602

In [437]:
# female subject
transofposs_perfective_connective2_17f = transofposs_perfective_connective2_17[0:12]
transofposs_perfective_connective2_17f = transofposs_perfective_connective2_17f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_17m = transofposs_perfective_connective2_17[12:24]

#### female subject

In [438]:
transofposs_perfective_connective2_17f

                                             stimulus       she        he
0   Miss Smith gave a sweater to Mr. Smith and, as...  0.691286  0.308714
1   The woman gave a sweater to the man and, as a ...  0.242271  0.757729
2       Mary gave a sweater to John and, as a result,  0.456733  0.543267
3       Alice gave a sweater to Bob and, as a result,  0.355838  0.644162
4   The actress gave a sweater to the actor and, a...  0.330602  0.669398
5   The girl gave a sweater to the boy and, as a r...  0.217131  0.782869
6   Mrs. Taylor gave a sweater to Mr. Williams and...  0.535832  0.464168
7      Emma gave a sweater to David and, as a result,  0.599846  0.400154
8   The princess gave a sweater to the prince and,...  0.337372  0.662628
9    Sarah gave a sweater to Robert and, as a result,  0.454101  0.545899
10  Mrs. Williams gave a sweater to  Mr. Taylor an...  0.535171  0.464829
11     Emily gave a sweater to Paul and, as a result,  0.547229  0.452772

In [439]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_17f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_17f,'he'))

P('subj-pron'|subj=female) =  0.4419509246945381
P('non-subj-pron'|subj=female) =  0.5580490802725157

In [440]:
c2_average_subj_female_subj_pron['gave'] = compute_average(transofposs_perfective_connective2_17f,'she')
c2_average_subj_female_obj_pron['gave'] = compute_average(transofposs_perfective_connective2_17f,'he')

#### male subject

In [441]:
transofposs_perfective_connective2_17m

                                             stimulus        he       she
12  Mr. Smith gave a sweater to Miss Smith and, as...  0.356366  0.643634
13  The man gave a sweater to the woman and, as a ...  0.493822  0.506178
14      John gave a sweater to Mary and, as a result,  0.255652  0.744348
15      Bob gave a sweater to Alice and, as a result,  0.468774  0.531226
16  The actor gave a sweater to the actress and, a...  0.629303  0.370697
17  The boy gave a sweater to the girl and, as a r...  0.511717  0.488283
18  Mr. William gave a sweater to  Mrs. Taylor and...  0.355870  0.644130
19     David gave a sweater to Emma and, as a result,  0.277046  0.722954
20  The prince gave a sweater to the princess and,...  0.313932  0.686068
21   Robert gave a sweater to Sarah and, as a result,  0.373177  0.626823
22  Mr. Taylor gave a sweater to Mrs. Williams and...  0.366491  0.633509
23     Paul gave a sweater to Emily and, as a result,  0.358187  0.641813

In [442]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_17m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_17m,'she'))

P('subj-pron'|subj=male) =  0.39669473220904666
P('non-subj-pron'|subj=male) =  0.6033052851756414

In [443]:
c2_average_subj_male_subj_pron['gave'] = compute_average(transofposs_perfective_connective2_17m,'he')
c2_average_subj_male_obj_pron['gave'] = compute_average(transofposs_perfective_connective2_17m,'she')

### verb: "handed"

In [444]:
transofposs_perfective_connective2_18 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/18.csv")
transofposs_perfective_connective2_18.head()

                                            stimulus        he       she
0  Miss Smith handed a book to Mr. Smith and, as ...  0.248804  0.751196
1  The woman handed a book to the man and, as a r...  0.583246  0.416754
2       Mary handed a book to John and, as a result,  0.438043  0.561957
3       Alice handed a book to Bob and, as a result,  0.509889  0.490111
4  The actress handed a book to the actor and, as...  0.452428  0.547572

In [445]:
# female subject
transofposs_perfective_connective2_18f = transofposs_perfective_connective2_18[0:12]
transofposs_perfective_connective2_18f = transofposs_perfective_connective2_18f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_18m = transofposs_perfective_connective2_18[12:24]

#### female subject

In [446]:
transofposs_perfective_connective2_18f

                                             stimulus       she        he
0   Miss Smith handed a book to Mr. Smith and, as ...  0.751196  0.248804
1   The woman handed a book to the man and, as a r...  0.416754  0.583246
2        Mary handed a book to John and, as a result,  0.561957  0.438043
3        Alice handed a book to Bob and, as a result,  0.490111  0.509889
4   The actress handed a book to the actor and, as...  0.547572  0.452428
5   The girl handed a book to the boy and, as a re...  0.323814  0.676186
6   Mrs. Taylor handed a book to Mr. Williams and,...  0.668026  0.331974
7       Emma handed a book to David and, as a result,  0.730768  0.269232
8   The princess handed a book to the prince and, ...  0.373571  0.626429
9     Sarah handed a book to Robert and, as a result,  0.378073  0.621927
10  Mrs. Williams handed a book to Mr. Taylor and,...  0.740613  0.259387
11      Emily handed a book to Paul and, as a result,  0.666703  0.333297

In [447]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_18f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_18f,'he'))

P('subj-pron'|subj=female) =  0.5540965894858042
P('non-subj-pron'|subj=female) =  0.4459034229318301

In [448]:
c2_average_subj_female_subj_pron['handed'] = compute_average(transofposs_perfective_connective2_18f,'she')
c2_average_subj_female_obj_pron['handed'] = compute_average(transofposs_perfective_connective2_18f,'he')

#### male subject

In [449]:
transofposs_perfective_connective2_18m

                                             stimulus        he       she
12  Mr. Smith handed a book to Miss Smith and, as ...  0.212523  0.787477
13  The man handed a book to the woman and, as a r...  0.377789  0.622211
14       John handed a book to Mary and, as a result,  0.198449  0.801551
15       Bob handed a book to Alice and, as a result,  0.321031  0.678969
16  The actor handed a book to the actress and, as...  0.336845  0.663155
17  The boy handed a book to the girl and, as a re...  0.324399  0.675601
18  Mr. William handed a book to Mrs. Taylor and, ...  0.233891  0.766109
19      David handed a book to Emma and, as a result,  0.153058  0.846942
20  The prince handed a book to the princess and, ...  0.243444  0.756556
21    Robert handed a book to Sarah and, as a result,  0.333186  0.666814
22  Mr. Taylor handed a book to Mrs. Williams and,...  0.219351  0.780649
23      Paul handed a book to Emily and, as a result,  0.280482  0.719518

In [450]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_18m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_18m,'she'))

P('subj-pron'|subj=male) =  0.2695373023549716
P('non-subj-pron'|subj=male) =  0.7304626802603403

In [451]:
c2_average_subj_male_subj_pron['handed'] = compute_average(transofposs_perfective_connective2_18m,'he')
c2_average_subj_male_obj_pron['handed'] = compute_average(transofposs_perfective_connective2_18m,'she')

### verb: "passed"

In [452]:
transofposs_perfective_connective2_19 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/19.csv")
transofposs_perfective_connective2_19.head()

                                            stimulus        he       she
0  Miss Smith passed a sandwich to Mr. Smith and,...  0.263056  0.736944
1  The woman passed a sandwich to the man and, as...  0.553942  0.446059
2   Mary passed a sandwich to John and, as a result,  0.341996  0.658005
3   Alice passed a sandwich to Bob and, as a result,  0.496588  0.503412
4  The actress passed a sandwich to the actor and...  0.618849  0.381151

In [453]:
# female subject
transofposs_perfective_connective2_19f = transofposs_perfective_connective2_19[0:12]
transofposs_perfective_connective2_19f = transofposs_perfective_connective2_19f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_19m = transofposs_perfective_connective2_19[12:24]

#### female subject

In [454]:
transofposs_perfective_connective2_19f

                                             stimulus       she        he
0   Miss Smith passed a sandwich to Mr. Smith and,...  0.736944  0.263056
1   The woman passed a sandwich to the man and, as...  0.446059  0.553942
2    Mary passed a sandwich to John and, as a result,  0.658005  0.341996
3    Alice passed a sandwich to Bob and, as a result,  0.503412  0.496588
4   The actress passed a sandwich to the actor and...  0.381151  0.618849
5   The girl passed a sandwich to the boy and, as ...  0.325887  0.674113
6   Mrs. Taylor passed a sandwich to Mr. Williams ...  0.527332  0.472668
7   Emma passed a sandwich to David and, as a result,  0.699059  0.300941
8   The princess passed a sandwich to the prince a...  0.500994  0.499006
9   Sarah passed a sandwich to Robert and, as a re...  0.466848  0.533152
10  Mrs. Williams passed a sandwich to  Mr. Taylor...  0.570160  0.429840
11  Emily passed a sandwich to Paul and, as a result,  0.697592  0.302408

In [455]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_19f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_19f,'he'))

P('subj-pron'|subj=female) =  0.5427867869536082
P('non-subj-pron'|subj=female) =  0.457213227947553

In [456]:
c2_average_subj_female_subj_pron['passed'] = compute_average(transofposs_perfective_connective2_19f,'she')
c2_average_subj_female_obj_pron['passed'] = compute_average(transofposs_perfective_connective2_19f,'he')

#### male subject

In [457]:
transofposs_perfective_connective2_19m

                                             stimulus        he       she
12  Mr. Smith passed a sandwich to Miss Smith and,...  0.338868  0.661132
13  The man passed a sandwich to the woman and, as...  0.536149  0.463851
14   John passed a sandwich to Mary and, as a result,  0.272604  0.727396
15   Bob passed a sandwich to Alice and, as a result,  0.629853  0.370147
16  The actor passed a sandwich to the actress and...  0.846240  0.153760
17  The boy passed a sandwich to the girl and, as ...  0.662044  0.337956
18  Mr. William passed a sandwich to  Mrs. Taylor ...  0.359055  0.640945
19  David passed a sandwich to Emma and, as a result,  0.389799  0.610201
20  The prince passed a sandwich to the princess a...  0.415130  0.584870
21  Robert passed a sandwich to Sarah and, as a re...  0.641178  0.358822
22  Mr. Taylor passed a sandwich to Mrs. Williams ...  0.310500  0.689500
23  Paul passed a sandwich to Emily and, as a result,  0.492175  0.507825

In [458]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_19m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_19m,'she'))

P('subj-pron'|subj=male) =  0.49113281816244125
P('non-subj-pron'|subj=male) =  0.5088671793540319

In [459]:
c2_average_subj_male_subj_pron['passed'] = compute_average(transofposs_perfective_connective2_19m,'he')
c2_average_subj_male_obj_pron['passed'] = compute_average(transofposs_perfective_connective2_19m,'she')

### verb: "served"

In [460]:
transofposs_perfective_connective2_20 = pd.read_csv("../results/transfoxl/transofposs_perfective/connective2/20.csv")
transofposs_perfective_connective2_20.head()

                                            stimulus        he       she
0  Miss Smith served a chili to Mr. Smith and, as...  0.164795  0.835205
1  The woman served a chili to the man and, as a ...  0.576440  0.423560
2      Mary served a chili to John and, as a result,  0.176650  0.823350
3      Alice served a chili to Bob and, as a result,  0.317405  0.682595
4  The actress served a chili to the actor and, a...  0.482706  0.517294

In [461]:
# female subject
transofposs_perfective_connective2_20f = transofposs_perfective_connective2_20[0:12]
transofposs_perfective_connective2_20f = transofposs_perfective_connective2_20f[["stimulus","she","he"]]
# male subject
transofposs_perfective_connective2_20m = transofposs_perfective_connective2_20[12:24]

#### female subject

In [462]:
transofposs_perfective_connective2_20f

                                             stimulus       she        he
0   Miss Smith served a chili to Mr. Smith and, as...  0.835205  0.164795
1   The woman served a chili to the man and, as a ...  0.423560  0.576440
2       Mary served a chili to John and, as a result,  0.823350  0.176650
3       Alice served a chili to Bob and, as a result,  0.682595  0.317405
4   The actress served a chili to the actor and, a...  0.517294  0.482706
5   The girl served a chili to the boy and, as a r...  0.355623  0.644377
6   Mrs. Taylor served a chili to Mr. Williams and...  0.640146  0.359854
7      Emma served a chili to David and, as a result,  0.771972  0.228028
8   The princess served a chili to the prince and,...  0.627587  0.372413
9    Sarah served a chili to Robert and, as a result,  0.720624  0.279376
10  Mrs. Williams served a chili to Mr. Taylor and...  0.661623  0.338377
11     Emily served a chili to Paul and, as a result,  0.875121  0.124879

In [463]:
print("P('subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_20f,'she'))
print("P('non-subj-pron'|subj=female) = ", compute_average(transofposs_perfective_connective2_20f,'he'))

P('subj-pron'|subj=female) =  0.6612250655889511
P('non-subj-pron'|subj=female) =  0.3387749257187049

In [464]:
c2_average_subj_female_subj_pron['served'] = compute_average(transofposs_perfective_connective2_20f,'she')
c2_average_subj_female_obj_pron['served'] = compute_average(transofposs_perfective_connective2_20f,'he')

#### male subject

In [465]:
transofposs_perfective_connective2_20m

                                             stimulus        he       she
12  Mr. Smith served a chili to Miss Smith and, as...  0.699448  0.300552
13  The man served a chili to the woman and, as a ...  0.864256  0.135744
14      John served a chili to Mary and, as a result,  0.785339  0.214661
15      Bob served a chili to Alice and, as a result,  0.945063  0.054937
16  The actor served a chili to the actress and, a...  0.948341  0.051659
17  The boy served a chili to the girl and, as a r...  0.917647  0.082353
18  Mr. William served a chili to  Mrs. Taylor and...  0.759950  0.240050
19     David served a chili to Emma and, as a result,  0.821299  0.178701
20  The prince served a chili to the princess and,...  0.889071  0.110929
21   Robert served a chili to Sarah and, as a result,  0.947457  0.052543
22  Mr. Taylor served a chili to Mrs. Williams and...  0.585662  0.414338
23     Paul served a chili to Emily and, as a result,  0.804670  0.195330

In [466]:
print("P('subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_20m,'he'))
print("P('non-subj-pron'|subj=male) = ", compute_average(transofposs_perfective_connective2_20m,'she'))

P('subj-pron'|subj=male) =  0.8306837032238642
P('non-subj-pron'|subj=male) =  0.16931630981465182

In [467]:
c2_average_subj_male_subj_pron['served'] = compute_average(transofposs_perfective_connective2_20m,'he')
c2_average_subj_male_obj_pron['served'] = compute_average(transofposs_perfective_connective2_20m,'she')

## Summary of Results

In [468]:
c2_results_fsubj_subjpron = pd.DataFrame(list(c2_average_subj_female_subj_pron.items()),columns=['verb','subj_ref_female_subj'])
c2_results_fsubj_objpron = pd.DataFrame(list(c2_average_subj_female_obj_pron.items()),columns=['verb','obj_ref_female_subj'])
c2_results_fsubj = c2_results_fsubj_subjpron.merge(c2_results_fsubj_objpron)
c2_results_fsubj

           verb  subj_ref_female_subj  obj_ref_female_subj
0       chucked              0.569164             0.430836
1         flung              0.413117             0.586883
2        kicked              0.344795             0.655205
3        lobbed              0.391389             0.608611
4        rolled              0.417243             0.582757
5         threw              0.452011             0.547989
6        tossed              0.415584             0.584416
7       brought              0.511368             0.488632
8     forwarded              0.602572             0.397428
9        mailed              0.607450             0.392550
10      shipped              0.670087             0.329913
11  transmitted              0.569044             0.430956
12        wired              0.469438             0.530562
13      carried              0.634303             0.365697
14    delivered              0.510081             0.489919
15         gave              0.441951             0.558049
16       handed              0.554097             0.445903
17       passed              0.542787             0.457213
18       served              0.661225             0.338775

In [469]:
c2_results_msubj_subjpron = pd.DataFrame(list(c2_average_subj_male_subj_pron.items()),columns=['verb','subj_ref_male_subj'])
c2_results_msubj_objpron = pd.DataFrame(list(c2_average_subj_male_obj_pron.items()),columns=['verb','obj_ref_male_subj'])
c2_results_msubj = c2_results_msubj_subjpron.merge(c2_results_msubj_objpron)
c2_results_msubj

           verb  subj_ref_male_subj  obj_ref_male_subj
0       chucked            0.719895           0.280105
1         flung            0.441548           0.558452
2        kicked            0.721820           0.278180
3        lobbed            0.384533           0.615467
4        rolled            0.630591           0.369409
5         threw            0.533606           0.466394
6        tossed            0.434657           0.565343
7       brought            0.408710           0.591290
8     forwarded            0.326710           0.673290
9        mailed            0.249956           0.750044
10      shipped            0.377113           0.622887
11  transmitted            0.203868           0.796132
12        wired            0.205264           0.794736
13      carried            0.554720           0.445280
14    delivered            0.412686           0.587314
15         gave            0.396695           0.603305
16       handed            0.269537           0.730463
17       passed            0.491133           0.508867
18       served            0.830684           0.169316

In [470]:
c2_results = c2_results_fsubj.merge(c2_results_msubj)
c2_results

,verb,subj_ref_female_subj,obj_ref_female_subj,subj_ref_male_subj,obj_ref_male_subj
0,chucked,0.569164,0.430836,0.719895,0.280105
1,flung,0.413117,0.586883,0.441548,0.558452
2,kicked,0.344795,0.655205,0.721820,0.278180
3,lobbed,0.391389,0.608611,0.384533,0.615467
4,rolled,0.417243,0.582757,0.630591,0.369409
5,threw,0.452011,0.547989,0.533606,0.466394
6,tossed,0.415584,0.584416,0.434657,0.565343
7,brought,0.511368,0.488632,0.408710,0.591290
8,forwarded,0.602572,0.397428,0.326710,0.673290
9,mailed,0.607450,0.392550,0.249956,0.750044
10,shipped,0.670087,0.329913,0.377113,0.622887
11,transmitted,0.569044,0.430956,0.203868,0.796132
12,wired,0.469438,0.530562,0.205264,0.794736
13,carried,0.634303,0.365697,0.554720,0.445280
14,delivered,0.510081,0.489919,0.412686,0.587314
15,gave,0.441951,0.558049,0.396695,0.603305
16,handed,0.554097,0.445903,0.269537,0.730463
17,passed,0.542787,0.457213,0.491133,0.508867
18,served,0.661225,0.338775,0.830684,0.169316

In [471]:
print("P(subj_reference |subj=female)", compute_average(c2_results,'subj_ref_female_subj'))
print("P(obj_reference |subj=female)", compute_average(c2_results,'obj_ref_female_subj'))

P(subj_reference |subj=female) 0.5146160910657622
P(obj_reference |subj=female) 0.4853839141627152

In [472]:
print("P(subj_reference |subj=male)", compute_average(c2_results,'subj_ref_male_subj'))
print("P(obj_reference |subj=male)", compute_average(c2_results,'obj_ref_male_subj'))

P(subj_reference |subj=male) 0.45230126397259407
P(obj_reference |subj=male) 0.5476987382495091

In [473]:
# save results to csv
col_headers = ['verb','subj_ref_female_subj','obj_ref_female_subj','subj_ref_male_subj','obj_ref_male_subj']
np_results.to_csv("../results/transfoxl/summary/transofposs_perfective-noprompt.csv",index=False,header=col_headers)
c1_results.to_csv("../results/transfoxl/summary/transofposs_perfective-connective1.csv",index=False,header=col_headers)
c2_results.to_csv("../results/transfoxl/summary/transofposs_perfective-connective2.csv",index=False,header=col_headers)